"use client";

import { Suspense, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { ArrowLeft, Lightning, BookOpen } from "@phosphor-icons/react";
import { toast } from "sonner";
import { NoteQuiz } from "@/components/free-study/NoteQuiz";
import {
  generateQuiz,
  type GenerateQuizQuestion,
} from "@/lib/free-study/generateQuiz";
import styles from "@/components/free-study/free-study-quiz.module.css";

function QuizContent() {
  const searchParams = useSearchParams();
  const initialText = searchParams.get("text") ?? "";
  const initialTitle = searchParams.get("title") ?? "";

  const [text, setText] = useState(initialText);
  const [title, setTitle] = useState(initialTitle);
  const [questions, setQuestions] = useState<GenerateQuizQuestion[]>([]);
  const [generating, setGenerating] = useState(false);
  const [showQuiz, setShowQuiz] = useState(false);

  const canGenerate = text.replace(/\s/g, "").length >= 40;

  const autoGenerated = useMemo(() => {
    if (initialText && initialText.replace(/\s/g, "").length >= 40) {
      return true;
    }
    return false;
  }, [initialText]);

  useEffect(() => {
    if (!autoGenerated || generating || showQuiz) return;
    setGenerating(true);
    generateQuiz({ text: initialText, count: 5 })
      .then((result) => {
        setQuestions(result.questions);
        setShowQuiz(true);
      })
      .catch((err) => {
        toast.error(
          err instanceof Error ? err.message : "Failed to generate quiz",
        );
      })
      .finally(() => setGenerating(false));
  }, [autoGenerated, initialText, generating, showQuiz]);

  const handleGenerate = useCallback(async () => {
    if (!canGenerate) return;
    setGenerating(true);
    try {
      const result = await generateQuiz({ text, count: 5 });
      setQuestions(result.questions);
      setShowQuiz(true);
    } catch (err) {
      toast.error(
        err instanceof Error ? err.message : "Failed to generate quiz",
      );
    } finally {
      setGenerating(false);
    }
  }, [text, canGenerate]);

  if (showQuiz && questions.length > 0) {
    return (
      <NoteQuiz
        questions={questions}
        onComplete={(score) => {
          toast.success(
            `Quiz done — ${score.correct} of ${score.total} correct`,
          );
        }}
        onClose={() => {
          setShowQuiz(false);
          setQuestions([]);
        }}
      />
    );
  }

  return (
    <div className={styles.page}>
      <Link href="/dashboard/free-study" className={styles.backLink}>
        <ArrowLeft size={14} weight="bold" aria-hidden />
        Back to Free Studying
      </Link>

      <h1 className={styles.title}>Quiz Generator</h1>
      <p className={styles.subtitle}>
        {initialText
          ? `Generating quiz from "${title || "your notes"}"…`
          : "Paste your study material below and we'll generate a quiz to test your knowledge."}
      </p>

      {initialText ? (
        <div className={styles.importedSource}>
          <BookOpen size={16} weight="fill" aria-hidden />
          <span>Imported from notes</span>
        </div>
      ) : null}

      <div className={styles.inputSection}>
        <textarea
          className={styles.textarea}
          value={text}
          onChange={(e) => {
            setText(e.target.value);
            setTitle("");
          }}
          placeholder="Paste your notes, textbook content, or study material here..."
          rows={8}
          readOnly={!!initialText}
        />
        <button
          type="button"
          className={styles.generateBtn}
          onClick={handleGenerate}
          disabled={!canGenerate || generating}
        >
          {generating ? (
            <span className={styles.loadingDots}>
              <span /><span /><span />
            </span>
          ) : (
            <>
              <Lightning size={16} weight="fill" aria-hidden />
              {initialText ? "Regenerate Quiz" : "Generate Quiz"}
            </>
          )}
        </button>
      </div>
    </div>
  );
}

export default function FreeStudyQuizPage() {
  return (
    <Suspense
      fallback={
        <div className={styles.page}>
          <div className={styles.loadingDots}>
            <span /><span /><span />
          </div>
        </div>
      }
    >
      <QuizContent />
    </Suspense>
  );
}
