INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'A circle has a radius of 5.  A chord of the circle is 8 units long.  What is the distance from the center of the circle to the chord? ',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Draw a diagram of the circle and the chord.  Draw a perpendicular segment from the center of the circle to the chord.  This segment bisects the chord, creating two right triangles.  The hypotenuse of each triangle is the radius of the circle, 5, and the length of one leg is half the length of the chord, 4.  Using the Pythagorean theorem, we find the length of the other leg, which is the distance from the center of the circle to the chord: $\sqrt{5^2 - 4^2} = \sqrt{25-16} = \sqrt{9} = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_67503ff4cb517dfc_math_00782',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_f8","opensat_index":782}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined as $f(x) = \frac{1}{x^2+1}$.  What is the value of $f(\frac{1}{2})$?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{1}{5}$","is_correct":true,"explanation":""},{"id":"B","text":"$\\frac{2}{5}$","is_correct":false,"explanation":""},{"id":"C","text":"$\\frac{4}{5}$","is_correct":false,"explanation":""},{"id":"D","text":"$\\frac{5}{4}$","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Substituting $\frac{1}{2}$ for $x$ in the equation $f(x) = \frac{1}{x^2+1}$ yields $f(\frac{1}{2}) = \frac{1}{(\frac{1}{2})^2+1}$. Simplifying the denominator gives us $f(\frac{1}{2}) = \frac{1}{\frac{1}{4}+1}$, or $f(\frac{1}{2}) = \frac{1}{\frac{5}{4}}$. Dividing 1 by $\frac{5}{4}$ is the same as multiplying by $\frac{4}{5}$, so $f(\frac{1}{2}) = \frac{4}{5}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_de17ed769e8b0be6_math_00783',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_b9","opensat_index":783}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of 10 students took a test, and the average score on the test was 70.  If one student scored 100 on the test, what was the average score of the other 9 students? ',
    'multiple_choice',
    '[{"id":"A","text":"65","is_correct":false,"explanation":""},{"id":"B","text":"68","is_correct":true,"explanation":""},{"id":"C","text":"70","is_correct":false,"explanation":""},{"id":"D","text":"72","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The total score of all 10 students is 10 * 70 = 700. If one student scored 100, the total score of the other 9 students is 700 – 100 = 600. The average score of the other 9 students is 600 / 9 = 66.67, which rounds to 68.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_6d7a5bce0776d19c_math_00784',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c5","opensat_index":784}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 centimeters. What is the circumference of the circle, in centimeters? (Express your answer in terms of $\pi$.)',
    'multiple_choice',
    '[{"id":"A","text":"$\\pi$","is_correct":false,"explanation":""},{"id":"B","text":"$5\\pi$","is_correct":false,"explanation":""},{"id":"C","text":"$10\\pi$","is_correct":true,"explanation":""},{"id":"D","text":"$25\\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius.  Substituting 5 for $r$ gives us $C = 2\pi (5) = 10\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_a72f9eac2cea96f3_math_00785',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_c3","opensat_index":785}'::jsonb
  ),
(
    gen_random_uuid(),
    'The sum of two numbers is 10.  One number is 4 less than twice the other number.  What is the value of the larger number?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Let x represent the smaller number.  The larger number is 2x - 4.  The sum of the two numbers is x + (2x - 4) = 10.  Combining like terms, we get 3x - 4 = 10.  Adding 4 to both sides, we get 3x = 14.  Dividing both sides by 3, we get x = 14/3.  The larger number is 2(14/3) - 4 = 28/3 - 4 = 16/3 = 5 1/3.  Therefore, the larger number is 6.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_b13f4188d1bc1653_math_00786',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c1","opensat_index":786}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 2x - 15 = 0$, what are the solutions for $x$?',
    'multiple_choice',
    '[{"id":"A","text":"x = -5, x = 3","is_correct":false,"explanation":""},{"id":"B","text":"x = 5, x = -3","is_correct":true,"explanation":""},{"id":"C","text":"x = -15, x = 1","is_correct":false,"explanation":""},{"id":"D","text":"x = 15, x = -1","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for $x$, we can factor the quadratic equation: $(x + 5)(x - 3) = 0$. For this equation to equal 0, either $(x + 5) = 0$ or $(x - 3) = 0$. Solving for $x$ in each case, we get $x = -5$ or $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_86700310872e4dba_math_00787',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_b8","opensat_index":787}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm. What is the circumference of the circle? (Use $\pi = 3.14$)',
    'multiple_choice',
    '[{"id":"A","text":"15.7","is_correct":false,"explanation":""},{"id":"B","text":"31.4","is_correct":true,"explanation":""},{"id":"C","text":"62.8","is_correct":false,"explanation":""},{"id":"D","text":"157","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius.  Substituting the given values, we get $C = 2(3.14)(5) = 31.4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_c414f7e5521dccf1_math_00788',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_2","opensat_index":788}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function f(x) is defined as $f(x) = x^2 - 3x + 2$. If the graph of y = f(x) intersects the x-axis at the points (a, 0) and (b, 0), what is the value of a + b?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The x-intercepts of the graph of y = f(x) occur where the function crosses the x-axis, which means y = 0.  So we need to find the roots of the equation f(x) = 0.  Factoring the quadratic, we get (x - 1)(x - 2) = 0.  Therefore, the roots are x = 1 and x = 2.  So, a + b = 1 + 2 = 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_ef8434ca745b869f_math_00789',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a4","opensat_index":789}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $(x+2)^2 + (y-1)^2 = 4$ defines a circle in the $xy$-plane.  What is the radius of this circle?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The standard form of the equation of a circle with center $(h,k)$ and radius $r$ is $(x-h)^2 + (y-k)^2 = r^2$.  In this case, the equation of the circle is $(x+2)^2 + (y-1)^2 = 4$, which can be rewritten as $(x-(-2))^2 + (y-1)^2 = 2^2$.  Therefore, the radius of the circle is 2.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_3f93e8a55d2d74e7_math_00790',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a9","opensat_index":790}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the solution to the equation $\frac{x-3}{x+2} = 1$ ?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":false,"explanation":""},{"id":"D","text":"No solution","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Multiplying both sides of the equation by $x+2$ gives $x-3 = x+2$. Subtracting $x$ from both sides gives $-3 = 2$. This equation is false, so there is no solution to the original equation. The original equation is undefined when $x=-2$. ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_7765b0bb5fc17fcf_math_00791',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_a3","opensat_index":791}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined as $f(x) = \frac{x^2 + 1}{x - 3}$. What is the value of $f(4)$?',
    'multiple_choice',
    '[{"id":"A","text":"-21","is_correct":false,"explanation":""},{"id":"B","text":"-5","is_correct":false,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"21","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find the value of f(4), we substitute 4 for x in the function''s definition: $f(4) = \frac{4^2 + 1}{4 - 3} = \frac{16 + 1}{1} = \frac{17}{1} = 17$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_b02c69c5e2e3a88b_math_00792',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_15","opensat_index":792}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with center $O$ has a radius of 5.  Point $A$ lies on the circle, and the measure of angle $AOB$ is 60 degrees.  What is the length of chord $AB$?',
    'multiple_choice',
    '[{"id":"A","text":"5","is_correct":false,"explanation":""},{"id":"B","text":"10","is_correct":false,"explanation":""},{"id":"C","text":"5\\sqrt{3}","is_correct":true,"explanation":""},{"id":"D","text":"10\\sqrt{3}","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Angle $AOB$ is a central angle of the circle, so triangle $AOB$ is an equilateral triangle.  Therefore, chord $AB$ has the same length as the radius of the circle, 5.  The height of triangle $AOB$ is  $5\sqrt{3}$, and this is also the length of the altitude from point $O$ to chord $AB$, which divides chord $AB$ into two congruent segments.  Since the altitude bisects chord $AB$, the length of chord $AB$ is $2(5\sqrt{3}) = 5\sqrt{3}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '83a1729c_math_00793',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"83a1729c","opensat_index":793}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 centimeters. What is the area, in square centimeters, of the circle?  (Use $\pi \approx 3.14$)',
    'multiple_choice',
    '[{"id":"A","text":"15.7","is_correct":false,"explanation":""},{"id":"B","text":"31.4","is_correct":false,"explanation":""},{"id":"C","text":"78.5","is_correct":true,"explanation":""},{"id":"D","text":"157","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula $A = \pi r^2$, where r is the radius. Substituting 5 for r and 3.14 for $\pi$, we get $A \approx 3.14 \cdot 5^2 \approx 3.14 \cdot 25 \approx 78.5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_e220261dcbbb92d7_math_00794',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c7","opensat_index":794}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 2x - 3 = 0$, what is the value of $x^2 + 2x + 1$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":true,"explanation":""},{"id":"C","text":"7","is_correct":false,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Notice that $x^2 + 2x + 1$ is a perfect square trinomial: $(x+1)^2$. Since we know $x^2 + 2x - 3 = 0$, we can add 4 to both sides of this equation to get $x^2 + 2x + 1 = 4$. Therefore, $x^2 + 2x + 1$ is equal to 4.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '3a3f291c_math_00795',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"3a3f291c","opensat_index":795}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $f(x) = x^2 + 2x - 3$, what is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-7","is_correct":true,"explanation":""},{"id":"B","text":"-3","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To find the value of f(-2), we substitute -2 for x in the given function: f(-2) = (-2)^2 + 2(-2) - 3. This simplifies to 4 - 4 - 3 = -3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_d0b54e7e0fee2536_math_00796',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c1","opensat_index":796}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  \(3x+5=11\), what is the value of  \(x\)?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":true,"explanation":""},{"id":"D","text":"3","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    '1. Subtract 5 from both sides of the equation to get \(3x=6\). 2. Divide both sides by 3 to get \(x=2\). Therefore, the value of \(x\) is \(2\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '156d897b_math_00797',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"156d897b","opensat_index":797}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f$ is defined by $f(x) = \sqrt{x^2 + 1}$. What is the value of $f(\sqrt{3})$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"$\\sqrt{3}$","is_correct":false,"explanation":""},{"id":"D","text":"$\\sqrt{10}$","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Substituting $\sqrt{3}$ for $x$ in the function definition, we get $f(\sqrt{3}) = \sqrt{(\sqrt{3})^2 + 1}$. Simplifying, we have $f(\sqrt{3}) = \sqrt{3 + 1} = \sqrt{4} = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '728424a4_math_00798',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"728424a4","opensat_index":798}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x-2$ is a factor of $2x^2 + ax + b$, where $a$ and $b$ are constants, what is the value of $b$?',
    'multiple_choice',
    '[{"id":"A","text":"-8","is_correct":true,"explanation":""},{"id":"B","text":"-4","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'If $x-2$ is a factor of $2x^2 + ax + b$, then the polynomial must equal 0 when $x = 2$.  Substituting 2 for $x$ in the expression, we get $2(2)^2 + a(2) + b = 0$.  Simplifying, we have $8 + 2a + b = 0$. Since the coefficient of $x^2$ is 2, the coefficient of the constant term $b$ must also be 2 times the constant term in the factored form $(x - 2)$.  This means that $b = -8$, which is the constant term in the factored form,  $2(x-2)(x+2) = 0$.  Substituting $b = -8$ into the equation $8 + 2a + b = 0$ gives $8 + 2a - 8 = 0$, or $2a = 0$, so $a = 0$.  Therefore, the value of $b$ is -8.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'f125a218_math_00799',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"f125a218","opensat_index":799}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm. What is the circumference of the circle? (Use $\pi = 3.14$)',
    'multiple_choice',
    '[{"id":"A","text":"15.7 cm","is_correct":false,"explanation":""},{"id":"B","text":"31.4 cm","is_correct":true,"explanation":""},{"id":"C","text":"78.5 cm","is_correct":false,"explanation":""},{"id":"D","text":"157 cm","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius. Plugging in the values, we get $C = 2(3.14)(5) = 31.4$ cm.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_307fe8e24d6d9fd8_math_00800',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a4","opensat_index":800}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function f(x) is defined as $f(x) = x^2 - 3$. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-7","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"7","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find the value of $f(-2)$, we substitute -2 for $x$ in the function. This gives us  $f(-2) = (-2)^2 - 3$, or $f(-2) = 4 - 3 = 1$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '2d8c4434_math_00801',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"2d8c4434","opensat_index":801}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x + 4y = 17$ and $2x - 3y = 9$, what is the value of $x + y$?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"7","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To solve for $x+y$, we can add the two equations together.  Adding the left sides gives us $(3x + 4y) + (2x - 3y) = 5x + y$.  Adding the right sides gives us $17 + 9 = 26$.  Therefore, $5x + y = 26$.  Dividing both sides by 5 gives us $x + y = \frac{26}{5}$, or $x + y = 5.2$.  Since the answer must be a whole number, we round 5.2 to the nearest whole number, 5.  Therefore, $x + y = 5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'b678452b_math_00802',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"b678452b","opensat_index":802}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = \frac{1}{x} + 4$. What is the value of $f(\frac{1}{4})$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":false,"explanation":""},{"id":"D","text":"17","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find the value of $f(\frac{1}{4})$, we substitute $\frac{1}{4}$ for $x$ in the expression for $f(x)$: $f(\frac{1}{4}) = \frac{1}{\frac{1}{4}} + 4 = 4 + 4 = 17$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_c6f45a92da7eae9f_math_00803',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_8","opensat_index":803}'::jsonb
  ),
(
    gen_random_uuid(),
    'The area of a rectangle is $100$ square inches. If the width of the rectangle is $5$ inches, what is the length of the rectangle, in inches?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":true,"explanation":""},{"id":"B","text":"10","is_correct":false,"explanation":""},{"id":"C","text":"25","is_correct":false,"explanation":""},{"id":"D","text":"50","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The area of a rectangle is found by multiplying its length and width.  If the area is 100 square inches and the width is 5 inches, the length is 100/5 = 20 inches.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_a31327b0ea4b4c03_math_00804',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_b8","opensat_index":804}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with radius 5 is inscribed in a square. What is the area of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square.  Since the radius of the circle is 5, the diameter is 10.  Therefore, the side length of the square is 10, and the area of the square is 10² = 100.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_bff9faf8bc8e10e9_math_00805',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a2","opensat_index":805}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = \frac{x^2 - 4}{x - 2}$ is defined for all real numbers except $x = 2$. What is the value of $f(4)$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can simplify the function by factoring the numerator: $f(x) = \frac{x^2 - 4}{x - 2} = \frac{(x+2)(x-2)}{x-2}$.  Since $x \neq 2$, we can cancel the common factor of $x-2$ to get $f(x) = x + 2$. Therefore, $f(4) = 4 + 2 = 6$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '714fd53a_math_00806',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"714fd53a","opensat_index":806}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;