INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'In a right triangle, one angle measures 30 degrees.  The side opposite this angle has a length of 5.  What is the length of the hypotenuse?',
    'multiple_choice',
    '[{"id":"A","text":"5\\sqrt{2}","is_correct":false,"explanation":""},{"id":"B","text":"5\\sqrt{3}","is_correct":false,"explanation":""},{"id":"C","text":"10","is_correct":true,"explanation":""},{"id":"D","text":"10\\sqrt{3}","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'A 30-60-90 right triangle has side lengths in the ratio 1:sqrt(3):2.  Since the side opposite the 30-degree angle has length 5, the hypotenuse has length 10.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_03de3a4dde8406c0_math_00532',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c1","opensat_index":532}'::jsonb
  ),
(
    gen_random_uuid(),
    'If \(x+2\) is a factor of the polynomial \(x^3+5x^2-4x-20\), what is the value of \(x^3+5x^2-4x-20\) when \(x=-2\)?',
    'multiple_choice',
    '[{"id":"A","text":"-24","is_correct":false,"explanation":""},{"id":"B","text":"0","is_correct":true,"explanation":""},{"id":"C","text":"12","is_correct":false,"explanation":""},{"id":"D","text":"24","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'If \(x+2\) is a factor of the polynomial \(x^3+5x^2-4x-20\), then by the Factor Theorem, the polynomial must equal 0 when \(x=-2\).  Therefore, \((-2)^3+5(-2)^2-4(-2)-20 = -8 + 20 + 8 - 20 = 0\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '84977e3c_math_00533',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"84977e3c","opensat_index":533}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a diameter of 10 units is inscribed in a square. What is the area of the square, in square units?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square.  Since the diameter is 10 units, the side length of the square is 10 units.  The area of a square is side length squared, so the area of the square is 10^2 = 100 square units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_b233b984aec0428e_math_00534',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_d7","opensat_index":534}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 200 randomly selected college students found that 120 students prefer to study in a quiet environment, 80 students prefer to study in a noisy environment, and 50 students prefer to study in either a quiet or noisy environment. How many of the 200 students surveyed prefer to study in a quiet environment only?',
    'multiple_choice',
    '[{"id":"A","text":"70","is_correct":true,"explanation":""},{"id":"B","text":"90","is_correct":false,"explanation":""},{"id":"C","text":"110","is_correct":false,"explanation":""},{"id":"D","text":"130","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    '50 students prefer to study in either a quiet or noisy environment, but 120 students prefer to study in a quiet environment. Therefore, 120 - 50 = 70 students prefer to study in a quiet environment only.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'f876c81c_math_00535',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"f876c81c","opensat_index":535}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  \(3x + 2y = 10\)  and  \(x - y = 1\), what is the value of  \(x + y\)?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":true,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for  \(x + y\), we can use the elimination method.  Multiplying the second equation by 2 gives  \(2x - 2y = 2\). Adding this equation to the first equation gives \(5x = 12\), so \(x = \frac{12}{5}\). Substituting this value of x back into the second equation gives \(\frac{12}{5} - y = 1\), so \(y = \frac{7}{5}\).  Therefore, \(x + y = \frac{12}{5} + \frac{7}{5} = \frac{19}{5} = 3 \frac{4}{5}\), but only 5 is a choice.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_ecfd557c1be78a08_math_00536',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c1","opensat_index":536}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store is selling apples for $1.50 per pound and oranges for $2.00 per pound.  If a customer buys 3 pounds of apples and 2 pounds of oranges, what is the total cost, in dollars?',
    'multiple_choice',
    '[{"id":"A","text":"5.50","is_correct":false,"explanation":""},{"id":"B","text":"6.50","is_correct":false,"explanation":""},{"id":"C","text":"7.50","is_correct":false,"explanation":""},{"id":"D","text":"8.50","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The cost of the apples is 3 pounds * $1.50/pound = $4.50.  The cost of the oranges is 2 pounds * $2.00/pound = $4.00.  The total cost is $4.50 + $4.00 = $8.50.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '768237bf_math_00537',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"768237bf","opensat_index":537}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $2x+3y=12$ represents a line in the $xy$-plane.  Which of the following points lies on this line?',
    'multiple_choice',
    '[{"id":"A","text":"(0, 4)","is_correct":false,"explanation":""},{"id":"B","text":"(3, 2)","is_correct":true,"explanation":""},{"id":"C","text":"(4, 0)","is_correct":false,"explanation":""},{"id":"D","text":"(6, -2)","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To determine if a point lies on a line, we can substitute the coordinates of the point into the equation of the line and see if the equation holds true.  Substituting the coordinates of choice B, (3, 2), into the equation 2x + 3y = 12, we get 2(3) + 3(2) = 12, which simplifies to 6 + 6 = 12.  Since this equation is true, the point (3, 2) lies on the line 2x + 3y = 12.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_528b652d4587b415_math_00538',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a9","opensat_index":538}'::jsonb
  ),
(
    gen_random_uuid(),
    'A regular hexagon is inscribed in a circle with a radius of 6.  What is the perimeter of the hexagon?',
    'multiple_choice',
    '[{"id":"A","text":"12","is_correct":false,"explanation":""},{"id":"B","text":"18","is_correct":false,"explanation":""},{"id":"C","text":"24","is_correct":false,"explanation":""},{"id":"D","text":"36","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'A regular hexagon can be divided into 6 equilateral triangles, each with a side length equal to the radius of the circle. The perimeter of the hexagon is 6 times the side length of one of these triangles, so the perimeter is 6 * 6 = 36.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_ec39aa76d24bd6db_math_00539',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c9","opensat_index":539}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units. What is the area, in square units, of a sector of this circle that has a central angle of $72^{\circ}$?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":true,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":false,"explanation":""},{"id":"D","text":"50\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The area of a sector of a circle is given by the formula \frac{\theta}{360^{\circ}}\cdot \pi r^2, where $\theta$ is the central angle of the sector in degrees and r is the radius of the circle.  Substituting $72^{\circ}$ for $\theta$ and 5 for r, we get \frac{72^{\circ}}{360^{\circ}}\cdot \pi (5)^2 = \frac{1}{5}\cdot 25\pi = 5\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_5d8b2186c200f789_math_00540',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_e8","opensat_index":540}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 3x^2 - 2x + 1. What is the value of *f*(2)?',
    'multiple_choice',
    '[{"id":"A","text":"9","is_correct":false,"explanation":""},{"id":"B","text":"11","is_correct":false,"explanation":""},{"id":"C","text":"13","is_correct":true,"explanation":""},{"id":"D","text":"15","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find *f*(2), we substitute 2 for *x* in the function: *f*(2) = 3(2)^2 - 2(2) + 1 = 3(4) - 4 + 1 = 12 - 4 + 1 = 9. Therefore, *f*(2) = 9.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '3d88374a_math_00541',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"3d88374a","opensat_index":541}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = \frac{x^2 + 3x - 4}{x - 1}$ is undefined for what value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":false,"explanation":""},{"id":"B","text":"0","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":true,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'A rational function is undefined when the denominator equals zero. In this case, the denominator is $x-1$, which equals zero when $x=1$. Therefore, the function is undefined for $x=1$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_7906d50e7022e422_math_00542',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_b8","opensat_index":542}'::jsonb
  ),
(
    gen_random_uuid(),
    'A school is holding a fundraiser. They are selling raffle tickets for \$3 each. If they sell 120 raffle tickets, how much money will they raise?',
    'multiple_choice',
    '[{"id":"A","text":"360","is_correct":true,"explanation":""},{"id":"B","text":"36","is_correct":false,"explanation":""},{"id":"C","text":"3600","is_correct":false,"explanation":""},{"id":"D","text":"300","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Multiplying the number of tickets sold by the price of each ticket gives the total amount raised: 120 tickets * \$3/ticket = \$360.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'c85492a4_math_00543',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"c85492a4","opensat_index":543}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  \(3x + 4y = 12\) and \(x - 2y = 4\), what is the value of \(x\) ?',
    'multiple_choice',
    '[{"id":"A","text":"0","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can solve for \(x\) by using elimination. Multiplying the second equation by 2, we get \(2x - 4y = 8\). Adding this equation to the first equation, we get \(5x = 20\). Dividing both sides by 5, we get \(x = 4\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '49d388b4_math_00544',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"49d388b4","opensat_index":544}'::jsonb
  ),
(
    gen_random_uuid(),
    'The graph of the equation $y = -x^2 + 4x - 3$ in the xy-plane is a parabola. What is the x-coordinate of the vertex of this parabola?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":true,"explanation":""},{"id":"D","text":"3","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The x-coordinate of the vertex of a parabola in the form $y = ax^2 + bx + c$ is given by the formula $x = \frac{-b}{2a}$. In this case, $a = -1$ and $b = 4$, so the x-coordinate of the vertex is $x = \frac{-4}{2(-1)} = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '9201b00f_math_00545',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"9201b00f","opensat_index":545}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 2x - 8 = 0$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-4","is_correct":false,"explanation":""},{"id":"B","text":"-2","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'We can solve this quadratic equation by factoring. The equation can be factored as $(x-4)(x+2)=0$. Therefore, the solutions are $x=4$ and $x=-2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_6c811d49da112509_math_00546',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c1","opensat_index":546}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a radius of 5 centimeters is inscribed in a square. What is the area, in square centimeters, of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square. Since the radius of the circle is 5 centimeters, the diameter is 10 centimeters. Therefore, the side length of the square is 10 centimeters, and the area of the square is (10 cm)(10 cm) = 100 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_818db5ea9a924264_math_00547',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c1","opensat_index":547}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of friends are planning a trip. They decide to split the cost of the trip evenly among themselves. The total cost of the trip is \$2,400. If the cost per person is \$300, how many friends are going on the trip?',
    'multiple_choice',
    '[{"id":"A","text":"6","is_correct":false,"explanation":""},{"id":"B","text":"8","is_correct":true,"explanation":""},{"id":"C","text":"10","is_correct":false,"explanation":""},{"id":"D","text":"12","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To find the number of friends, we divide the total cost of the trip by the cost per person: \$2,400 / \$300 = 8. Therefore, there are 8 friends going on the trip.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_4b055b8e1c319d34_math_00548',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c1","opensat_index":548}'::jsonb
  ),
(
    gen_random_uuid(),
    'A triangle has sides of length 5, 12, and 13.  Is this triangle a right triangle?  Explain your reasoning.',
    'multiple_choice',
    '[{"id":"A","text":"Yes, because $5^2 + 12^2 = 13^2$.","is_correct":true,"explanation":""},{"id":"B","text":"Yes, because $5 + 12 = 13$.","is_correct":false,"explanation":""},{"id":"C","text":"No, because $5^2 + 12^2 \\neq 13^2$.","is_correct":false,"explanation":""},{"id":"D","text":"No, because $5 + 12 \\neq 13$.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'A triangle is a right triangle if and only if the square of the length of the longest side is equal to the sum of the squares of the lengths of the other two sides. In this case, the longest side is 13, and $5^2 + 12^2 = 25 + 144 = 169 = 13^2$, so the triangle is a right triangle.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_8c15cd68c2668d26_math_00549',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a4","opensat_index":549}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 centimeters. What is the circumference of the circle, in centimeters?  (Express your answer in terms of $\pi$.)',
    'multiple_choice',
    '[{"id":"A","text":"5$\\pi$","is_correct":false,"explanation":""},{"id":"B","text":"10$\\pi$","is_correct":true,"explanation":""},{"id":"C","text":"25$\\pi$","is_correct":false,"explanation":""},{"id":"D","text":"50$\\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where r is the radius of the circle.  Substituting 5 for r, we get $C = 2\pi(5) = 10\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_6051fe2d0fdb884a_math_00550',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_e4","opensat_index":550}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $2x^2 + 5x - 3 = 0$ has two solutions, $x_1$ and $x_2$. What is the value of $x_1^2 + x_2^2$ ?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{1}{4}$","is_correct":false,"explanation":""},{"id":"B","text":"$\\frac{25}{4}$","is_correct":true,"explanation":""},{"id":"C","text":"$\\frac{13}{4}$","is_correct":false,"explanation":""},{"id":"D","text":"$\\frac{65}{4}$","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can use the following relationship: for a quadratic equation of the form $ax^2 + bx + c = 0$, the sum of the squares of the roots is equal to $\frac{b^2 - 2ac}{a^2}$. In this case, $a = 2$, $b = 5$, and $c = -3$. Therefore, $x_1^2 + x_2^2 = \frac{5^2 - 2(2)(-3)}{2^2} = \frac{25 + 12}{4} = \frac{37}{4}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '3a6bd3a7_math_00551',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"3a6bd3a7","opensat_index":551}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  $x^2 - 6x + 8 = 0$, what is the sum of the solutions to this equation?',
    'multiple_choice',
    '[{"id":"A","text":"-6","is_correct":false,"explanation":""},{"id":"B","text":"-8","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Factoring the quadratic equation, we get  (x - 2)(x - 4) = 0.  The solutions to this equation are x = 2 and x = 4. The sum of these solutions is 2 + 4 = 6.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_8bd9f425a360412d_math_00552',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_1","opensat_index":552}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 4$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To solve for $x$, we can use the elimination method. Multiplying the second equation by 3, we get $3x - 3y = 12$.  Adding this equation to the first equation, we get $5x = 24$, or $x=\frac{24}{5}$ = 4.8, which is closest to 4.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'e89f2c9a_math_00553',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"e89f2c9a","opensat_index":553}'::jsonb
  ),
(
    gen_random_uuid(),
    'A square has a side length of 10 cm. What is the area of the square in square centimeters?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"20","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a square is found by multiplying the side length by itself.  Therefore, the area is 10 cm * 10 cm = 100 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_990ab7d4cad0fc34_math_00554',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_4","opensat_index":554}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a diameter of 10 inches is inscribed in a square. What is the area, in square inches, of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square. Since the diameter is 10 inches, the side length of the square is also 10 inches. The area of a square is found by squaring the side length, so the area of the square is 10^2 = 100 square inches.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'd04919d8_math_00555',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"d04919d8","opensat_index":555}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 2x - 8 = 0$, what is the sum of the solutions to the equation?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":true,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The sum of the solutions to a quadratic equation of the form ax^2 + bx + c = 0 is -b/a. In this case, a = 1 and b = -2, so the sum of the solutions is -(-2)/1 = 2.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_40d3734bf18c39b2_math_00556',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a4","opensat_index":556}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;