INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'A circle is inscribed in a square with side length 8. What is the area of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"8\\pi","is_correct":false,"explanation":""},{"id":"B","text":"16\\pi","is_correct":true,"explanation":""},{"id":"C","text":"32\\pi","is_correct":false,"explanation":""},{"id":"D","text":"64\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The diameter of the circle is equal to the side length of the square, which is 8. Therefore, the radius of the circle is 4. The area of the circle is $\pi r^2 = \pi(4)^2 = 16\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'e55931d8_math_00082',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"e55931d8","opensat_index":82}'::jsonb
  ),
(
    gen_random_uuid(),
    'In a right triangle, one acute angle measures 30 degrees.  If the length of the hypotenuse is 10, what is the length of the side opposite the 30 degree angle?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":true,"explanation":""},{"id":"C","text":"5\\sqrt{3}","is_correct":false,"explanation":""},{"id":"D","text":"10\\sqrt{3}","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A 30-60-90 triangle has side lengths in the ratio 1 : \sqrt{3} : 2.  Since the hypotenuse has length 10, the side opposite the 30 degree angle has length 10 / 2 = 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_c8d6a5fcc42a976e_math_00083',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c1","opensat_index":83}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by \(f(x) = x^2 + 3x - 10\). What is the value of *f*(2)?',
    'multiple_choice',
    '[{"id":"A","text":"-4","is_correct":false,"explanation":""},{"id":"B","text":"0","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"12","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find *f*(2), we substitute 2 for *x* in the function''s definition: *f*(2) = (2)^2 + 3(2) - 10 = 4 + 6 - 10 = 12.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_e5cebe2ea2024c2b_math_00084',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_d6","opensat_index":84}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells apples for $2 per pound and oranges for $1.50 per pound. A customer buys 3 pounds of apples and 2 pounds of oranges. What is the total cost of the apples and oranges?',
    'multiple_choice',
    '[{"id":"A","text":"$7.00","is_correct":false,"explanation":""},{"id":"B","text":"$7.50","is_correct":false,"explanation":""},{"id":"C","text":"$8.00","is_correct":false,"explanation":""},{"id":"D","text":"$9.00","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The cost of the apples is 3 pounds * $2/pound = $6. The cost of the oranges is 2 pounds * $1.50/pound = $3. The total cost is $6 + $3 = $9.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_c1b2142242bcd51c_math_00085',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a9","opensat_index":85}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has legs of length 5 and 12. What is the length of the hypotenuse?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"13","is_correct":true,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"19","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs.  Therefore, the length of the hypotenuse is \sqrt{5^2 + 12^2} = \sqrt{169} = 13.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_e92b7f80c7a57c3d_math_00086',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c9","opensat_index":86}'::jsonb
  ),
(
    gen_random_uuid(),
    'In a right triangle, one angle measures 30 degrees and the hypotenuse has a length of 10. What is the length of the side opposite the 30-degree angle?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":true,"explanation":""},{"id":"C","text":"5\\sqrt{3}","is_correct":false,"explanation":""},{"id":"D","text":"10\\sqrt{3}","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A 30-60-90 right triangle has sides in the ratio of 1:√3:2. Since the hypotenuse has a length of 10, the side opposite the 30-degree angle has a length of 10 / 2 = 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_1c4414f8a85cac1d_math_00087',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_a5","opensat_index":87}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 200 students found that 120 students enjoy watching movies, 80 students enjoy reading books, and 60 students enjoy both. How many of the 200 students enjoy neither watching movies nor reading books?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":false,"explanation":""},{"id":"B","text":"40","is_correct":true,"explanation":""},{"id":"C","text":"60","is_correct":false,"explanation":""},{"id":"D","text":"100","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can use a Venn diagram to solve this problem.  Let M represent the set of students who enjoy watching movies and B represent the set of students who enjoy reading books.  We are given that |M|=120, |B|=80, and |M∩B|=60.  The number of students who enjoy only watching movies is 120 - 60 = 60.  The number of students who enjoy only reading books is 80 - 60 = 20.  The total number of students who enjoy at least one of these activities is 60 + 20 + 60 = 140. Therefore, 200 - 140 = 60 students enjoy neither.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_81b4ee881760ff23_math_00088',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c8","opensat_index":88}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells bags of apples for $\$3.50$ per bag.  If the store makes a profit of $\$0.75$ per bag, what is the cost, in dollars, of each bag of apples?',
    'multiple_choice',
    '[{"id":"A","text":"$\\$2.75$","is_correct":true,"explanation":""},{"id":"B","text":"$\\$3.25$","is_correct":false,"explanation":""},{"id":"C","text":"$\\$4.25$","is_correct":false,"explanation":""},{"id":"D","text":"$\\$4.75$","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The cost of a bag of apples is the selling price minus the profit: $\$3.50 - \$0.75 = \$2.75$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_dd5e7f9103d9cbeb_math_00089',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c3","opensat_index":89}'::jsonb
  ),
(
    gen_random_uuid(),
    'In a right triangle, the length of one leg is 5 units and the length of the hypotenuse is 13 units.  What is the area of the triangle?',
    'multiple_choice',
    '[{"id":"A","text":"30","is_correct":false,"explanation":""},{"id":"B","text":"60","is_correct":false,"explanation":""},{"id":"C","text":"15","is_correct":true,"explanation":""},{"id":"D","text":"36","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a right triangle is given by (1/2)bh, where b is the length of the base and h is the length of the height.  In a right triangle, the legs can be considered the base and height.  Using the Pythagorean Theorem, we can find the length of the other leg: a^2 + b^2 = c^2, where a and b are the legs and c is the hypotenuse.  Plugging in the values, we get 5^2 + b^2 = 13^2.  This simplifies to 25 + b^2 = 169.  Subtracting 25 from both sides, we get b^2 = 144.  Taking the square root of both sides, we get b = 12.  Now, the area of the triangle is (1/2)(5)(12) = 30.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_a6afe1c7e19a43a9_math_00090',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c3","opensat_index":90}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 students found that 60 students liked apples, 40 students liked oranges, and 15 students liked both apples and oranges. How many students liked neither apples nor oranges?',
    'multiple_choice',
    '[{"id":"A","text":"5","is_correct":false,"explanation":""},{"id":"B","text":"15","is_correct":false,"explanation":""},{"id":"C","text":"25","is_correct":true,"explanation":""},{"id":"D","text":"35","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can use a Venn diagram to solve this problem.  Let the number of students who like only apples be  and the number of students who like only oranges be .  We know that , , and .  We can use the following equation to find the number of students who like neither apples nor oranges: , or .  Therefore, students liked neither apples nor oranges.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_150c264b7747cd1d_math_00091',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c4","opensat_index":91}'::jsonb
  ),
(
    gen_random_uuid(),
    'In a right triangle, one angle measures 30 degrees and the hypotenuse has a length of 10. What is the length of the side opposite the 30 degree angle?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":true,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'In a 30-60-90 right triangle, the side opposite the 30 degree angle is half the length of the hypotenuse. Therefore, the length of the side opposite the 30 degree angle is 10/2 = 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_f2cc9fc749b98ea1_math_00092',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_b5","opensat_index":92}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the median of the seven data values shown? 2, 2, 3, 4, 4, 11',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The median of a data set with an odd number of values is the middle value. The values are already presented in order from least to greatest, and there are 7 values. Therefore, the median is the fourth value in the list, which is 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'f890dc20_math_00093',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"f890dc20","opensat_index":93}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a radius of 5 units is inscribed in a square. What is the area, in square units, of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square.  Since the radius of the circle is 5 units, the diameter is 10 units. Therefore, the side length of the square is 10 units, and the area of the square is 10^2 = 100 square units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_3aa3671576896375_math_00094',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a3","opensat_index":94}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x - 2y = 11$ and $x + 2y = 5$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Adding the two equations together, we eliminate y: $3x - 2y + (x + 2y) = 11 + 5$, which simplifies to $4x = 16$. Dividing both sides by 4, we find $x = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'a9f12c4a_math_00095',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"a9f12c4a","opensat_index":95}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x + 2y = 10$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve this system of equations using elimination. Multiplying the second equation by 2, we get $2x - 2y = 2$. Adding this equation to the first equation, we get $5x = 12$. Dividing both sides by 5, we get $x = \frac{12}{5}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_de748ca0d4c1ec1c_math_00096',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_5","opensat_index":96}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x - 2y = 10$ and $x + 2y = 2$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for x, we can add the two equations together. Notice that the y terms will cancel out: \begin{align*} 3x - 2y &= 10 \\ + (x + 2y &= 2) \\ \hline 4x &= 12 \\ \end{align*} Dividing both sides by 4, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_664f67917f06639a_math_00097',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a2","opensat_index":97}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 randomly selected students found that 60 students prefer to study in a quiet environment and 40 students prefer to study in a noisy environment. If 300 students are surveyed, how many are likely to prefer to study in a quiet environment?',
    'multiple_choice',
    '[{"id":"A","text":"60","is_correct":false,"explanation":""},{"id":"B","text":"120","is_correct":false,"explanation":""},{"id":"C","text":"180","is_correct":true,"explanation":""},{"id":"D","text":"240","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The ratio of students who prefer quiet to the total number of students is 60/100 = 3/5. If 300 students are surveyed, we can multiply this ratio by 300 to estimate the number of students who prefer quiet: (3/5) * 300 = 180.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_cfcbffdc8f2d9bf2_math_00098',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c9","opensat_index":98}'::jsonb
  ),
(
    gen_random_uuid(),
    'A triangle has vertices at the points $(0,0), (1,0),$ and $(0,1)$. What is the area of this triangle?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{1}{4}$","is_correct":true,"explanation":""},{"id":"B","text":"$\\frac{1}{2}$","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"2","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The triangle is a right triangle with a base of 1 and a height of 1. The area of a triangle is given by the formula $\frac{1}{2}bh$.  Therefore, the area of the triangle is $\frac{1}{2}(1)(1) = \frac{1}{2}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_b289b6061937add9_math_00099',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c2","opensat_index":99}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has legs of length 5 and 12. What is the length of the hypotenuse?',
    'multiple_choice',
    '[{"id":"A","text":"7","is_correct":false,"explanation":""},{"id":"B","text":"13","is_correct":true,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"25","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The Pythagorean theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs.  In this case, the hypotenuse squared is equal to $5^2 + 12^2 = 25 + 144 = 169$.  The square root of 169 is 13, so the length of the hypotenuse is 13.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '12d8c11e_math_00100',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"12d8c11e","opensat_index":100}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 200 people found that 120 people liked apples, 80 people liked oranges, and 50 people liked both apples and oranges. How many people liked only oranges?',
    'multiple_choice',
    '[{"id":"A","text":"30","is_correct":true,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"70","is_correct":false,"explanation":""},{"id":"D","text":"130","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To find the number of people who liked only oranges, we subtract the number of people who liked both apples and oranges from the number who liked oranges: 80 - 50 = 30.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_9ff3d0f90f85d9e5_math_00101',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a5","opensat_index":101}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 students found that 60 students like to play basketball, 50 students like to play soccer, and 20 students like to play both.  How many students like to play only basketball?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"20","is_correct":false,"explanation":""},{"id":"C","text":"40","is_correct":true,"explanation":""},{"id":"D","text":"60","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find the number of students who like only basketball, we need to subtract the number of students who like both sports from the total number of students who like basketball.  This gives us 60 – 20 = 40.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_8bf922ff74fca93b_math_00102',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c9","opensat_index":102}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the value of  $\frac{x^2 + 2x + 1}{x^2 - 1}$ when $x=3$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":true,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"8","is_correct":false,"explanation":""},{"id":"D","text":"16","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can simplify the expression first by factoring the numerator and denominator:  $\frac{x^2 + 2x + 1}{x^2 - 1} = \frac{(x+1)(x+1)}{(x+1)(x-1)}$.  Since $x=3$, we can substitute to get $\frac{(3+1)(3+1)}{(3+1)(3-1)} = \frac{(4)(4)}{(4)(2)} = \frac{16}{8} = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_da7af8505ea56051_math_00103',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a1","opensat_index":103}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units.  What is the area, in square units, of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":true,"explanation":""},{"id":"D","text":"100\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula A = \pi r^2, where r is the radius.  Substituting 5 for r, we get A = \pi (5)^2 = 25\pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_47f5f75604396bd3_math_00104',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a7","opensat_index":104}'::jsonb
  ),
(
    gen_random_uuid(),
    'A regular hexagon is inscribed in a circle with a radius of 6. What is the perimeter of the hexagon?',
    'multiple_choice',
    '[{"id":"A","text":"18","is_correct":false,"explanation":""},{"id":"B","text":"24","is_correct":false,"explanation":""},{"id":"C","text":"36","is_correct":true,"explanation":""},{"id":"D","text":"48","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'A regular hexagon can be divided into 6 equilateral triangles. The side of each equilateral triangle is equal to the radius of the circle, which is 6. Therefore, the perimeter of the hexagon is 6 * 6 = 36.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_c7a8ec5bd9a81d5d_math_00105',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a9","opensat_index":105}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with center (2,3) passes through the point (5,7). What is the radius of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":true,"explanation":""},{"id":"C","text":"8","is_correct":false,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The radius of the circle is the distance between the center of the circle and any point on the circle.  Using the distance formula, the distance between (2,3) and (5,7) is $\sqrt{(5-2)^2 + (7-3)^2} = \sqrt{3^2 + 4^2} = \sqrt{25} = 5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_8c5ca1ffe92f53c8_math_00106',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_9","opensat_index":106}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;