INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'In this passage, the author most likely describes a problem and then offers a solution in order to',
    'multiple_choice',
    '[{"id":"A","text":"establish the author’s authority on the subject.","is_correct":false,"explanation":""},{"id":"B","text":"present the author’s perspective as unbiased and objective.","is_correct":false,"explanation":""},{"id":"C","text":"encourage the reader to think critically about the issue.","is_correct":false,"explanation":""},{"id":"D","text":"make the author’s argument more persuasive to the reader.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The author chose to use this strategy in order to make the argument more persuasive to the reader. By describing a problem and then offering a solution, the author makes it clear to the reader what the issue is and how it can be addressed. This can be more persuasive than simply stating a solution without context.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author’s purpose in this passage is to persuade the reader to take action, but the text doesn’t include a direct call for action. The author instead uses a strategy of describing a problem and then offering a solution. This strategy is common in persuasive writing, but it’s not always the most effective way to persuade a reader to act. What is the most likely reason why the author chose to use this strategy?',
    'passage',
    'reading_writing',
    'Expression of Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Expression of Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Expression of Ideas']::text[],
    'f21e275e_english_01200',
    'college_board_opensat',
    '{"opensat_domain":"Expression of Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"f21e275e","opensat_index":1200}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best combines the two underlined portions of the text into a single, correct sentence?',
    'multiple_choice',
    '[{"id":"A","text":"The author was particularly interested in the way that his characters responded to their changing environments, and characters responding could help readers understand the deeper meanings of the story.","is_correct":false,"explanation":""},{"id":"B","text":"The author was particularly interested in the way his characters responded to their changing environments, which could help readers understand the deeper meanings of the story.","is_correct":true,"explanation":""},{"id":"C","text":"The author was particularly interested in how his characters responded to their changing environments, which could help readers understand the deeper meanings of the story.","is_correct":false,"explanation":""},{"id":"D","text":"The author was particularly interested in how his characters responded to their changing environments, and how characters responded could help readers understand the deeper meanings of the story.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The best way to combine the two underlined portions of the text is to use a comma and the conjunction “which” to create a single, correct sentence. This is because the second underlined portion is a dependent clause that modifies the first underlined portion, which is an independent clause. The conjunction “which” correctly connects these two clauses because it is a relative pronoun that refers to the first clause. Choice A is incorrect because it creates a comma splice, a sentence error that occurs when two independent clauses are joined together with only a comma. Choice C is incorrect because the conjunction “how” does not make sense in the context of the sentence. Choice D is incorrect because it creates a comma splice and the conjunction “how” does not make sense in the context of the sentence.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author was particularly interested in the _way_ that his characters responded to their changing environments. He believed that the _way_ characters responded could help readers understand the deeper meanings of the story.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_fceca6cd47be9b2a_english_01201',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"random_id_e8","opensat_index":1201}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best combines the sentences at the underlined portion so that it conforms to the conventions of Standard English?',
    'multiple_choice',
    '[{"id":"A","text":"However, the building''s residents, who had been living there for several years, expressed a strong preference for the new building''s airy and open spaces.","is_correct":true,"explanation":""},{"id":"B","text":"However, the building''s residents, who had been living there for several years, expressed a strong preference for the new building''s airy and open spaces,","is_correct":false,"explanation":""},{"id":"C","text":"However, the building''s residents, who had been living there for several years, expressed a strong preference for the new building''s airy and open spaces; ","is_correct":false,"explanation":""},{"id":"D","text":"However, the building''s residents, who had been living there for several years, expressed a strong preference for the new building''s airy and open spaces—","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The most effective way to combine these sentences is to use a comma to separate the two independent clauses. The comma correctly creates a pause between the two clauses and allows the reader to understand the relationship between them.  It also avoids the common errors of comma splices, fused sentences, and incorrect use of semicolons.',
    'Review the passage and eliminate choices that contradict the text.',
    'The new building was constructed in a modern style, with sleek lines and minimalist design. Although it was praised for its functionality, some critics felt that it lacked the warmth and character of traditional architecture. However, the building’s residents, who had been living there for several years, expressed a strong preference for the new building’s airy and open spaces.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '8123596d_english_01202',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"8123596d","opensat_index":1202}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best corrects the underlined portion of the passage?',
    'multiple_choice',
    '[{"id":"A","text":"When her brother tells her","is_correct":true,"explanation":""},{"id":"B","text":"When her brother, telling her","is_correct":false,"explanation":""},{"id":"C","text":"When her brother tells her,","is_correct":false,"explanation":""},{"id":"D","text":"When her brother telling her","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The sentence needs a finite verb to indicate what the brother did. Of the choices, only "tells" is a finite verb. The other choices either use a non-finite verb or a non-finite phrase, which cannot perform the action of the subject in a main clause.',
    'Review the passage and eliminate choices that contradict the text.',
    'The first chapter of this novel is set in a rural village in 19th century England.  The narrator is a young woman, and she is traveling with her brother.  She is excited to be away from home and to explore the world.  The narrator is surprised to find a vast array of wildlife in the village, and she and her brother enjoy observing the animals.  When her brother, he tells her that he has seen a rare bird, a red kite, the narrator becomes excited.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '6a7f420c_english_01203',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"6a7f420c","opensat_index":1203}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best combines the sentences at the underlined portion to create a more concise and effective sentence?',
    'multiple_choice',
    '[{"id":"A","text":"However, the story of New York is not just about the people who have lived there; it also about the places they have lived in.","is_correct":false,"explanation":""},{"id":"B","text":"However, the story of New York is not just about the people who have lived there, but also about the places they have lived in.","is_correct":false,"explanation":""},{"id":"C","text":"However, the story of New York is not just about the people who have lived there, it is also about the places they have lived in.","is_correct":true,"explanation":""},{"id":"D","text":"However, the story of New York is not just about the people who have lived there, and it is also about the places they have lived in.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Choice C is the most concise and effective way to combine the two sentences.  It uses a comma to separate the two independent clauses and creates a smooth and natural flow between them.',
    'Review the passage and eliminate choices that contradict the text.',
    'The history of the city of New York is a fascinating one.  It is a city where people from all over the world have come to build new lives, and it is a city that has seen its share of triumphs and tragedies.  However, the story of New York is not just about the people who have lived there, but also about the places they have lived in.  Over the centuries, the city has been shaped by the buildings that have been built, the streets that have been paved, and the parks that have been created.  The history of the city of New York is a history of change, and it is a history that is still being written today.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '8a34e70f_english_01204',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"8a34e70f","opensat_index":1204}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best combines the sentences at the underlined portion? ',
    'multiple_choice',
    '[{"id":"A","text":"Indeed, some authors dedicate entire chapters to descriptions of things like food and clothing.","is_correct":true,"explanation":""},{"id":"B","text":"Indeed; some authors dedicate entire chapters to descriptions of things like food and clothing.","is_correct":false,"explanation":""},{"id":"C","text":"Indeed, some authors, dedicate entire chapters to descriptions of things like food and clothing.","is_correct":false,"explanation":""},{"id":"D","text":"Indeed, some authors dedicate entire chapters to descriptions of things, like food and clothing.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The best way to combine the two sentences is to use a comma and the word "indeed" to create a smooth transition between the two ideas.  The comma and "indeed" create a grammatically correct and stylistically pleasing sentence.',
    'Review the passage and eliminate choices that contradict the text.',
    'The recent popularity of historical fiction, in which novelists explore the past, has led to a surge in interest in the details of daily life in past eras.  Indeed, some authors dedicate entire chapters to descriptions of things like food and clothing.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '4e71293d_english_01205',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"4e71293d","opensat_index":1205}'::jsonb
  ),
(
    gen_random_uuid(),
    'The most likely reason why the author uses these literary devices is to',
    'multiple_choice',
    '[{"id":"A","text":"provide a detailed and factual account of the natural world.","is_correct":false,"explanation":""},{"id":"B","text":"create a sense of wonder and awe in the reader.","is_correct":true,"explanation":""},{"id":"C","text":"explain the author’s personal feelings about the natural world.","is_correct":false,"explanation":""},{"id":"D","text":"convince the reader that the natural world is a dangerous place.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The author uses these literary devices to create a sense of wonder and awe in the reader. By comparing the trees to sentinels and suggesting that the forest has secrets, the author invites the reader to imagine a world that is both beautiful and mysterious.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author uses a variety of literary devices, including metaphors, similes, and personification, to create a vivid and evocative portrait of the natural world. For example, the author writes, "The trees stood like sentinels, guarding the forest''s secrets." This use of simile helps to create a sense of mystery and intrigue, making the reader feel as if they are entering a hidden world. What is the most likely reason why the writer uses these devices?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '7248511d_english_01206',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"7248511d","opensat_index":1206}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which sentence most clearly emphasizes the contrast between the storm on Wednesday and the fair weather on Thursday?',
    'multiple_choice',
    '[{"id":"A","text":"On Tuesday, the weather was fair.","is_correct":false,"explanation":""},{"id":"B","text":"On Wednesday, a storm came in, bringing with it wind, rain, and lightning.","is_correct":false,"explanation":""},{"id":"C","text":"In the end, however, the storm broke, and the sun came out again.","is_correct":false,"explanation":""},{"id":"D","text":"The fair weather on Thursday was a pleasant change from the storm on Wednesday.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The sentence "The fair weather on Thursday was a pleasant change from the storm on Wednesday" explicitly contrasts the storm with the fair weather, making the contrast between the two days clear.',
    'Review the passage and eliminate choices that contradict the text.',
    'On Tuesday, the weather was fair. The sun shone brightly, and the birds were singing. On Wednesday, a storm came in, bringing with it wind, rain, and lightning. In the end, however, the storm broke, and the sun came out again. The fair weather on Thursday was a pleasant change from the storm on Wednesday.',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '46ab1c1e_english_01207',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"46ab1c1e","opensat_index":1207}'::jsonb
  ),
(
    gen_random_uuid(),
    'The debate is likely to continue for many years to come, but it is clear that social media has had a profound impact on modern society, and it is important to understand the ways in which it can be used for both good and bad.',
    'multiple_choice',
    '[{"id":"A","text":"but it is clear that social media has had a profound impact on modern society, and it is important to understand the ways in which it can be used for both good and bad.","is_correct":true,"explanation":""},{"id":"B","text":"it is clear that social media has had a profound impact on modern society, and it is important to understand the ways in which it can be used for both good and bad.","is_correct":false,"explanation":""},{"id":"C","text":"but it is clear that social media has had a profound impact on modern society, and it is important to understand the ways in which it can be used for both good and bad.","is_correct":false,"explanation":""},{"id":"D","text":"but it is clear that social media has had a profound impact on modern society, and it is important to understand the ways in which it can be used for both good and bad.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Choice A is the best answer because it uses a comma to separate the two independent clauses that follow the conjunction "but." This is the correct way to punctuate a complex sentence with two independent clauses. Choices B, C, and D are incorrect because they all result in comma splices, which occur when two independent clauses are joined together with only a comma.',
    'Review the passage and eliminate choices that contradict the text.',
    'The debate about the role of social media in modern society has been ongoing for years. Some people argue that social media is a valuable tool that can be used to connect with others, share information, and build community. They point to the many ways that social media has been used to organize protests, raise awareness about important issues, and provide support to those in need. Others argue that social media is a harmful force that can be used to spread misinformation, promote hatred, and create echo chambers. They point to the many cases of social media being used to spread false information, incite violence, and contribute to the spread of harmful ideologies. The debate is likely to continue for many years to come, but it is clear that social media has had a profound impact on modern society, and it is important to understand the ways in which it can be used for both good and bad. Which of the following choices best completes the text so that it conforms to the conventions of Standard English?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '92ef1d2e_english_01208',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"92ef1d2e","opensat_index":1208}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best revises the sentence so that it conforms to the conventions of Standard English?',
    'multiple_choice',
    '[{"id":"A","text":"The author’s use of the word ‘love’ is significant; it is used to show the characters’ affection for their hometown.","is_correct":false,"explanation":""},{"id":"B","text":"The author’s use of the word ‘love’ is significant, because it is used to show the characters’ affection for their hometown.","is_correct":true,"explanation":""},{"id":"C","text":"The author’s use of the word ‘love’ is significant and it is used to show the characters’ affection for their hometown.","is_correct":false,"explanation":""},{"id":"D","text":"The author’s use of the word ‘love’ is significant, being used to show the characters’ affection for their hometown.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The original sentence incorrectly uses a comma to separate two independent clauses. This error is called a comma splice. The correct way to separate the two clauses is with a semicolon or a comma followed by a coordinating conjunction. Choice B is the only choice that correctly separates the two clauses with a comma followed by a coordinating conjunction.',
    'Review the passage and eliminate choices that contradict the text.',
    'The sentence "The author’s use of the word ‘love’ is significant, it is used to show the characters’ affection for their hometown." needs to be revised to conform to the conventions of Standard English.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '21c55a17_english_01209',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"21c55a17","opensat_index":1209}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice correctly combines the two sentences into one grammatically correct sentence?  

Sentence 1: The poet was widely admired for her ability to capture the nuances of human emotion. 
Sentence 2: She used a unique style of imagery that was both compelling and accessible.',
    'multiple_choice',
    '[{"id":"A","text":"The poet, who was widely admired for her ability to capture the nuances of human emotion, she used a unique style of imagery that was both compelling and accessible.","is_correct":false,"explanation":""},{"id":"B","text":"The poet was widely admired for her ability to capture the nuances of human emotion; and she used a unique style of imagery that was both compelling and accessible.","is_correct":false,"explanation":""},{"id":"C","text":"The poet was widely admired for her ability to capture the nuances of human emotion, using a unique style of imagery that was both compelling and accessible.","is_correct":true,"explanation":""},{"id":"D","text":"The poet was widely admired for her ability to capture the nuances of human emotion, she used a unique style of imagery, that was both compelling and accessible.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The correct answer is C because it uses a comma to join two independent clauses. The resulting sentence is grammatically correct and clearly expresses the relationship between the two ideas.  The other choices are incorrect because they contain grammatical errors (comma splice, incorrect punctuation of a non-essential clause, or run-on sentence).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_dd0d7dc5260741db_english_01210',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"random_id_e8","opensat_index":1210}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best combines the sentences at the underlined portion into a single sentence that is consistent with the conventions of Standard English?',
    'multiple_choice',
    '[{"id":"A","text":"It was called \"The Art of the Americas,\" which, by the way, made some visitors believe the exhibit covered all the Americas.","is_correct":false,"explanation":""},{"id":"B","text":"It was called \"The Art of the Americas,\" making some visitors believe the exhibit covered all the Americas.","is_correct":false,"explanation":""},{"id":"C","text":"It was called \"The Art of the Americas,\" which made some visitors believe the exhibit covered all the Americas.","is_correct":true,"explanation":""},{"id":"D","text":"It was called \"The Art of the Americas,\" leading some visitors to believe that the exhibit covered all the Americas.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Choice C is the best option because it combines the sentences without introducing a new clause or changing the meaning of the sentence. Choice A is incorrect because it contains a comma splice, which is a grammatical error. Choice B is incorrect because it makes the exhibit the subject of the clause "making some visitors believe the exhibit covered all the Americas," which doesn’t make sense in the context of the sentence. Choice D is incorrect because the word "leading" implies that visitors were encouraged to believe that the exhibit covered all the Americas, but the text states that some visitors simply believed this. ',
    'Review the passage and eliminate choices that contradict the text.',
    'The museum’s newest exhibit was a great success, but one could argue that the exhibit’s title was misleading. It was called "The Art of the Americas," which, by the way, made some visitors believe the exhibit covered all the Americas. However, the exhibit was focused only on art from North America. That is, the exhibition did not include works from the Americas south of the United States.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_d9bd3afcfb702c56_english_01211',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"random_id_a2","opensat_index":1211}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following best summarizes the main idea of the passage?',
    'multiple_choice',
    '[{"id":"A","text":"The Cherokee people have had a rich history, but they have also faced many challenges.","is_correct":true,"explanation":""},{"id":"B","text":"The Cherokee people have a long history of resilience and have been working to revitalize their culture and language.","is_correct":false,"explanation":""},{"id":"C","text":"The Trail of Tears was a devastating experience for the Cherokee people, and many of them died along the way.","is_correct":false,"explanation":""},{"id":"D","text":"The Cherokee Nation is now a thriving community, and they are proud of their heritage and their resilience.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The passage focuses on the Cherokee people’s history, which includes both their rich culture and their experiences of adversity. The passage highlights the Trail of Tears as a significant event in their history, and it ends by noting the Cherokee Nation’s current success and resilience.',
    'Review the passage and eliminate choices that contradict the text.',
    'The story of the Cherokee people in the United States is long and complex. For many centuries, the Cherokee lived in the southeastern part of what is now the United States, and they had a rich culture, language, and history. However, in the nineteenth century, the United States government began to force the Cherokee to move west, a process known as the Trail of Tears. This was a devastating experience for the Cherokee, and many of them died along the way.  It was also a major turning point in their history. In more recent times, the Cherokee have been working to revitalize their culture and language and to assert their sovereignty.  The Cherokee Nation is now a thriving community, and they are proud of their heritage and their resilience.',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    '3284b112_english_01212',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"3284b112","opensat_index":1212}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this sentence, the word “but” is used to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of urgency and excitement.","is_correct":false,"explanation":""},{"id":"B","text":"introduce a comparison between two contrasting ideas.","is_correct":true,"explanation":""},{"id":"C","text":"emphasize the importance of the speaker’s message.","is_correct":false,"explanation":""},{"id":"D","text":"suggest that the speaker is addressing a large audience.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The word "but" is used to create a contrast between two opposing ideas. The sentence suggests that humans are more likely to use complex language than other animals are, which is a direct contrast to the idea that other animals communicate in a different way.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author''s use of the word "but" in this sentence creates a contrast between two ideas, one about the way humans communicate and one about the way other animals communicate. The sentence suggests that humans are more likely to use complex language than other animals are. What is the most likely reason why the writer uses the word "but" in this sentence?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_940f3f0f25990523_english_01213',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_english_b2","opensat_index":1213}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best combines the sentences at the underlined portion to maintain the style and tone of the passage?',
    'multiple_choice',
    '[{"id":"A","text":"lonely, and they have trouble connecting with others in real life.","is_correct":false,"explanation":""},{"id":"B","text":"lonely, and are more likely to have trouble connecting with others in real life.","is_correct":true,"explanation":""},{"id":"C","text":"lonely, and they are more likely to have trouble connecting with others in real life.","is_correct":false,"explanation":""},{"id":"D","text":"lonely; they have trouble connecting with others in real life.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Choice B uses a comma and a coordinating conjunction to combine the two sentences, creating a smooth flow and maintaining the style of the passage. The other choices either create comma splices or use punctuation that is not typical for this style of writing.',
    'Review the passage and eliminate choices that contradict the text.',
    'A new study suggests that the more time people spend on social media, the less likely they are to engage in meaningful conversations with others. The research team found that individuals who check social media frequently are more likely to feel "lonely" and have trouble connecting with others in real life.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_ad3e105c9cd4dc5b_english_01214',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a12","opensat_index":1214}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author of the passage emphasizes the importance of personal history in order to',
    'multiple_choice',
    '[{"id":"A","text":"suggest that it is impossible to fully understand another person’s experiences.","is_correct":false,"explanation":""},{"id":"B","text":"explain that individual experiences are interconnected and influence one another.","is_correct":true,"explanation":""},{"id":"C","text":"show that personal history is more important than shared history.","is_correct":false,"explanation":""},{"id":"D","text":"argue that history is a powerful tool for understanding the past.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The author emphasizes that “every person has a personal history” in order to explain how individual experiences are interconnected and influence one another.  The author states that "personal histories intersect," which suggests that individual experiences are part of a larger tapestry of human experience. By emphasizing the importance of personal history, the author shows that it is impossible to understand a person''s experiences without considering the context of their personal history.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author of the passage suggests that “every person has a personal history,” and that “personal histories intersect.”  This intersection of histories can lead to a rich understanding of the complexities of the human experience. What is the most likely reason why the author of the passage emphasizes that "every person has a personal history"?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'b123456_english_01215',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"b123456","opensat_index":1215}'::jsonb
  ),
(
    gen_random_uuid(),
    'The details about the Bering Strait most likely function to',
    'multiple_choice',
    '[{"id":"A","text":"highlight the geographical significance of Alaska.","is_correct":false,"explanation":""},{"id":"B","text":"provide evidence of the long history of interaction between cultures.","is_correct":true,"explanation":""},{"id":"C","text":"show that the Bering Strait is a narrow body of water.","is_correct":false,"explanation":""},{"id":"D","text":"describe the methods that Indigenous people use to cross the Bering Strait.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The details about the Bering Strait most likely function to provide evidence of the long history of interaction between cultures. The text states that for centuries, Indigenous people from both sides of the Bering Strait traveled between Alaska and Russia, which demonstrates that the two cultures have a long history of interaction. The other choices are not supported by the text. The Bering Strait’s geographical significance is not the main focus of the text, and the details about the Bering Strait’s width and the methods used by Indigenous people to cross the strait are not the main points of the text.',
    'Review the passage and eliminate choices that contradict the text.',
    'Although most of the United States is located on the North American continent, parts of Alaska are in Asia.  These parts of Alaska are separated from mainland Russia by the Bering Strait, a body of water that is only about 53 miles wide at its narrowest point. For centuries, Indigenous people from both sides of the Bering Strait traveled between Alaska and Russia.  They have used a variety of methods to cross the strait, including kayaks, dog sleds, and snowmobiles. What’s the most likely reason for the author to include the details about the Bering Strait?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '6a578c7d_english_01216',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"6a578c7d","opensat_index":1216}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice corrects the comma splice in the sentence?',
    'multiple_choice',
    '[{"id":"A","text":"The most recent scientific evidence of the link between sugar consumption and Alzheimer’s disease was published in 2018; and it is generally accepted by the scientific community.","is_correct":false,"explanation":""},{"id":"B","text":"The most recent scientific evidence of the link between sugar consumption and Alzheimer’s disease was published in 2018, it is generally accepted by the scientific community.","is_correct":false,"explanation":""},{"id":"C","text":"The most recent scientific evidence of the link between sugar consumption and Alzheimer’s disease was published in 2018, however, it is generally accepted by the scientific community.","is_correct":true,"explanation":""},{"id":"D","text":"The most recent scientific evidence of the link between sugar consumption and Alzheimer’s disease was published in 2018 because it is generally accepted by the scientific community.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'A comma splice occurs when two independent clauses are joined together only by a comma.  To correct a comma splice, the two clauses must be joined by a semicolon, a comma followed by a coordinating conjunction, or a period. Choice C is correct because it uses a comma followed by the coordinating conjunction "however" to separate the two independent clauses in the sentence.  Choice A is incorrect because the semicolon should be followed by a comma, not "and."  Choice B is incorrect because a comma alone cannot separate the two independent clauses in the sentence.  Choice D is incorrect because the word "because" is a subordinating conjunction, which should only be used to link a dependent clause to an independent clause.',
    'Review the passage and eliminate choices that contradict the text.',
    'The following sentence contains a comma splice: "The most recent scientific evidence of the link between sugar consumption and Alzheimer’s disease was published in 2018, and it is generally accepted by the scientific community." Which choice corrects the comma splice in the sentence?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '61b87506_english_01217',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"61b87506","opensat_index":1217}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best completes the text so that it conforms to the conventions of Standard English?',
    'multiple_choice',
    '[{"id":"A","text":"For example, turning off the lights, which was selected by 19.6 percent of respondents, is a curtailment.","is_correct":true,"explanation":""},{"id":"B","text":"For example, turning off the lights—which was selected by 19.6 percent of respondents—is a curtailment.","is_correct":false,"explanation":""},{"id":"C","text":"For example, turning off the lights, which was selected by 19.6 percent of respondents, is a curtailment; ","is_correct":false,"explanation":""},{"id":"D","text":"For example, turning off the lights, which was selected by 19.6 percent of respondents, is a curtailment—","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Choice A is the best answer. The convention being tested is punctuation between a preposition and its complement. No punctuation is needed between the preposition "of" and its complement, the noun phrase "healing, self-discovery, and memory." Choice B is incorrect because no punctuation is needed between a preposition and its complement. Choice C is incorrect because no punctuation is needed between a preposition and its complement. Choice D is incorrect because no punctuation is needed between a preposition and its complement.',
    'Review the passage and eliminate choices that contradict the text.',
    'A study was done in which researchers tried to determine the most effective method for people to conserve energy. In the study, researchers asked participants to identify the most effective action that people can take to save energy. The team then classified each action as either an efficiency (using a more efficient appliance or lightbulb) or a curtailment (using a bike or public transportation, or turning off the lights).',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'a19a46ff_english_01218',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"a19a46ff","opensat_index":1218}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following statements best reflects the viewpoint of the argument that the current trend in popular music has led to a decline in creativity?',
    'multiple_choice',
    '[{"id":"A","text":"The current trend in popular music has made it easier for artists to experiment with new sounds and styles.","is_correct":false,"explanation":""},{"id":"B","text":"The rise of streaming services has actually led to a wider range of music being available to listeners.","is_correct":false,"explanation":""},{"id":"C","text":"The music industry has become more focused on producing songs that are likely to be commercially successful, rather than songs that are innovative or challenging.","is_correct":true,"explanation":""},{"id":"D","text":"The current trend in popular music has led to a wider range of music being available to listeners, and that this trend has made it easier for artists to experiment with new sounds and styles.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The argument that the current trend in popular music has led to a decline in creativity is based on the idea that the music industry is more focused on commercial success than on innovation. Choice C accurately reflects this viewpoint by stating that the music industry is more focused on producing commercially successful songs than innovative or challenging songs.',
    'Review the passage and eliminate choices that contradict the text.',
    'Some argue that the current trend in popular music has led to a decline in creativity. They point out that the music industry has become more focused on producing songs that are likely to be commercially successful, rather than songs that are innovative or challenging.  Others argue that the rise of streaming services has actually led to a wider range of music being available to listeners, and that the current trend in popular music has made it easier for artists to experiment with new sounds and styles.  Which of the following statements best reflects the viewpoint of the argument that the current trend in popular music has led to a decline in creativity?',
    'passage',
    'reading_writing',
    'Expression of Ideas',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Expression of Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Expression of Ideas']::text[],
    '37f8a72d_english_01219',
    'college_board_opensat',
    '{"opensat_domain":"Expression of Ideas","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"37f8a72d","opensat_index":1219}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice most effectively combines the sentences at the underlined portion to maintain the style and tone of the passage?',
    'multiple_choice',
    '[{"id":"A","text":"The woman standing in the doorway, her eyes were dark, and her face was pale.","is_correct":false,"explanation":""},{"id":"B","text":"The woman standing in the doorway had dark eyes and a pale face.","is_correct":false,"explanation":""},{"id":"C","text":"Standing in the doorway, her eyes were dark, her face was pale.","is_correct":true,"explanation":""},{"id":"D","text":"The woman in the doorway, her eyes were dark and her face was pale.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Choice C is the most effective way to combine the sentences because it maintains the style and tone of the passage. The use of the participle phrase, “Standing in the doorway,” creates a more elegant and descriptive sentence than the other choices.  Choice A is incorrect because it results in a comma splice. Choice B is incorrect because it introduces a new sentence. Choice D is incorrect because it uses a less formal tone.',
    'Review the passage and eliminate choices that contradict the text.',
    'The text below is adapted from a novel by Toni Morrison. In the novel, the narrator describes a dream that he had, where he saw a woman standing in the doorway of his home. 
The woman standing in the doorway, her eyes were dark and her face was pale.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'a7791e3e_english_01220',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"a7791e3e","opensat_index":1220}'::jsonb
  ),
(
    gen_random_uuid(),
    'The speaker’s use of the phrase “the most powerful weapon in the world” is meant to emphasize that',
    'multiple_choice',
    '[{"id":"A","text":"the audience should be wary of the speaker’s words.","is_correct":false,"explanation":""},{"id":"B","text":"the speaker is an expert on the topic of weapons.","is_correct":false,"explanation":""},{"id":"C","text":"the power of words can be very effective.","is_correct":true,"explanation":""},{"id":"D","text":"the speaker is using a metaphor to make a point.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The speaker is using a rhetorical device to emphasize the power of words. By comparing words to a weapon, the speaker is highlighting the potential impact of words.',
    'Review the passage and eliminate choices that contradict the text.',
    '“What is the most powerful weapon in the world?,” the speaker asked. The audience leaned forward in their chairs, eager for the answer. “The most powerful weapon in the world,” the speaker continued, “is the power of words.”',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_e3740ce3c2d939cd_english_01221',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_b8","opensat_index":1221}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the main idea of this passage?',
    'multiple_choice',
    '[{"id":"A","text":"The author argues that the meaning of words can change depending on the context in which they are used.","is_correct":false,"explanation":""},{"id":"B","text":"The author argues that the word \"love\" can have different meanings depending on the context in which it is used.","is_correct":false,"explanation":""},{"id":"C","text":"The author argues that it is important to be aware of the context in which communication occurs.","is_correct":true,"explanation":""},{"id":"D","text":"The author argues that it is important to avoid misunderstandings in communication.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The passage focuses on the importance of considering the context in which communication occurs. The author uses the word "love" as an example, but the main point is the broader concept of context and its impact on meaning.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author''s main argument in the passage is that it is important to consider the context in which something is said or written. The author suggests that the meaning of a word or phrase can change depending on the audience, the situation, and the purpose of the communication. For example, the author points out that the word "love" can have different meanings depending on whether it is used in a romantic context, a familial context, or a platonic context. The author concludes by arguing that it is important to be aware of the context in which communication occurs in order to avoid misunderstandings and to ensure that the message is received as intended.',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_3eb5a4cb4e725688_english_01222',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a3","opensat_index":1222}'::jsonb
  ),
(
    gen_random_uuid(),
    'The contrast between the protagonist''s childhood home and his adult life serves to',
    'multiple_choice',
    '[{"id":"A","text":"highlight the protagonist''s sense of nostalgia for a simpler time.","is_correct":false,"explanation":""},{"id":"B","text":"emphasize the protagonist''s desire for a more fulfilling life.","is_correct":false,"explanation":""},{"id":"C","text":"reveal the protagonist''s growing disillusionment with the world.","is_correct":true,"explanation":""},{"id":"D","text":"suggest that the protagonist''s childhood experiences have shaped his adult life.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The contrast between the protagonist''s idyllic childhood home and his harsh adult life serves to highlight the protagonist''s growing disillusionment with the world. By contrasting the two settings, the author emphasizes the loss of innocence and the harsh realities that the protagonist faces in his adult life. This creates a sense of pathos for the reader and suggests that the protagonist''s dreams and aspirations are being slowly crushed by the indifference of the world.',
    'Review the passage and eliminate choices that contradict the text.',
    'The novel opens with a description of the protagonist''s childhood home, a modest cottage nestled among rolling hills. The author then contrasts this idyllic setting with the harsh realities of the protagonist''s adult life in the city, where he struggles to find his place in a world that seems increasingly indifferent to his dreams and aspirations. What is the most likely reason why the writer contrasts the protagonist''s childhood home with his adult life?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_19c6baa27ffa908f_english_01223',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_b8","opensat_index":1223}'::jsonb
  ),
(
    gen_random_uuid(),
    'The phrase "our little world" is most likely used to',
    'multiple_choice',
    '[{"id":"A","text":"emphasize the speaker’s sense of isolation and loneliness.","is_correct":false,"explanation":""},{"id":"B","text":"create a feeling of shared experience between the speaker and the reader.","is_correct":true,"explanation":""},{"id":"C","text":"suggest that the speaker is speaking to a specific group of people.","is_correct":false,"explanation":""},{"id":"D","text":"describe the speaker’s perception of the world around them.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The phrase "our little world" is used to create a feeling of shared experience between the speaker and the reader. The speaker is suggesting that they are both a part of the same world, and that they are both experiencing the same things. This helps to create a sense of connection and intimacy between the speaker and the reader.',
    'Review the passage and eliminate choices that contradict the text.',
    'The speaker’s use of the word "you" and the phrase "our little world" suggests that the speaker is trying to create a sense of intimacy with the reader. The speaker is attempting to make the reader feel as if they are part of the speaker’s inner world, and that the speaker is sharing something special with the reader.  What is the most likely reason the writer chooses to use the phrase "our little world"?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_0287745c35454583_english_01224',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_1","opensat_index":1224}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;