INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'The passage primarily focuses on',
    'multiple_choice',
    '[{"id":"A","text":"the need for more research and development in order to make this technology more effective.","is_correct":false,"explanation":""},{"id":"B","text":"the potential benefits and challenges of a new technology.","is_correct":true,"explanation":""},{"id":"C","text":"the ethical concerns that are associated with this new technology.","is_correct":false,"explanation":""},{"id":"D","text":"the impact of this technology on different industries.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The passage discusses the potential benefits and challenges of a new technology, such as its power and versatility, as well as the need for further research and ethical considerations.  While it touches on some of the impacts on different industries, the focus is on the overall benefits and challenges of the new technology.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author describes a new technology that is being used in a variety of fields, including healthcare, agriculture, and manufacturing.  The technology is described as being "powerful" and "versatile," and it is said to have the potential to "revolutionize" many industries.  The author also discusses some of the challenges that are associated with this technology, including the need for more research and development, as well as the potential for ethical concerns. What is the main idea of the passage?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    '15678c4d_english_00375',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"15678c4d","opensat_index":375}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best summarizes the speaker’s point of view?',
    'multiple_choice',
    '[{"id":"A","text":"values her independence and self-reliance.","is_correct":true,"explanation":""},{"id":"B","text":"prefers to avoid asking for help.","is_correct":false,"explanation":""},{"id":"C","text":"believes that people are often insensitive to her needs.","is_correct":false,"explanation":""},{"id":"D","text":"is uncomfortable with showing her weaknesses.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The speaker’s words suggest that she values her independence and self-reliance. She prefers to do things herself rather than relying on others for help because she believes that she does a better job when she does things herself. This is evident in her statement, “I’d rather do it myself. And honestly, I do better when I do it myself anyway.”',
    'Review the passage and eliminate choices that contradict the text.',
    '“If they’d tried to take care of me, they’d have just made a mess of it,” she told me. “I’m not sure I’d be able to put up with that. The way people always try to ‘help’ is so patronizing and condescending. I’d rather do it myself. And honestly, I do better when I do it myself anyway.” The speaker’s words suggest that she',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'e892a937_english_00376',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"e892a937","opensat_index":376}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best combines the two sentences at the end of the passage into a single sentence that is grammatically correct and avoids redundancy?',
    'multiple_choice',
    '[{"id":"A","text":"Because these results are promising, the researchers say, additional studies need to be conducted to determine the exact mechanisms by which nature may enhance cognitive and social development.","is_correct":false,"explanation":""},{"id":"B","text":"These results are promising, say the researchers, so additional studies need to be conducted to determine the exact mechanisms by which nature may enhance cognitive and social development.","is_correct":false,"explanation":""},{"id":"C","text":"These results are promising, the researchers say, and additional studies need to be conducted to determine the exact mechanisms by which nature may enhance cognitive and social development.","is_correct":true,"explanation":""},{"id":"D","text":"Because these results are promising, additional studies need to be conducted to determine the exact mechanisms by which nature may enhance cognitive and social development, the researchers say.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Choice C is the best option because it effectively combines the two sentences into one grammatically correct sentence without redundancy. The phrase "the researchers say" is included once in the combined sentence, which avoids repetition and keeps the sentence concise. Choices A, B, and D are grammatically incorrect because they use unnecessary punctuation or fail to combine the sentences effectively.',
    'Review the passage and eliminate choices that contradict the text.',
    'A new study suggests that children who spend time outdoors in nature may benefit from improved cognitive and social development. The study found that children in the study group who spent at least one hour per day in a natural setting performed better on tests that measure attention and problem-solving skills than those who spent less time in nature. The researchers believe that the benefits of spending time in nature may be related to the increased exposure to sensory stimuli and the opportunity for unstructured play and exploration. "Because these results are promising," say the researchers, "additional studies need to be conducted to determine the exact mechanisms by which nature may enhance cognitive and social development."',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '894f566c_english_00377',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"894f566c","opensat_index":377}'::jsonb
  ),
(
    gen_random_uuid(),
    'This passage uses the word "you" in order to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of intimacy and connection with the reader.","is_correct":true,"explanation":""},{"id":"B","text":"describe the speaker’s feelings and experiences.","is_correct":false,"explanation":""},{"id":"C","text":"emphasize the importance of the speaker’s message.","is_correct":false,"explanation":""},{"id":"D","text":"suggest that the speaker is addressing a large audience.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The speaker is addressing the reader directly by using the word "you." This creates a sense of intimacy and connection with the reader, which can help the reader feel more engaged with the message.',
    'Review the passage and eliminate choices that contradict the text.',
    'From the outset, the author of this passage aims to engage the reader on a personal level by using the second person. The author uses the word "you" throughout, which can make the reader feel more connected to the author''s message. The author also provides specific examples that the reader can relate to and uses a conversational tone. What is the author''s purpose in using this style?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'a7793d8e_english_00378',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"a7793d8e","opensat_index":378}'::jsonb
  ),
(
    gen_random_uuid(),
    'The passage is primarily about',
    'multiple_choice',
    '[{"id":"A","text":"the history of experimental writing.","is_correct":true,"explanation":""},{"id":"B","text":"the benefits of experimental writing.","is_correct":false,"explanation":""},{"id":"C","text":"the challenges of experimental writing.","is_correct":false,"explanation":""},{"id":"D","text":"the different types of experimental writing.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The passage describes the history of a new type of writing that allows for greater creativity. The passage does not focus on the benefits, challenges, or types of experimental writing, so the most likely reason for its existence is to provide information about the history of experimental writing.',
    'Review the passage and eliminate choices that contradict the text.',
    'The passage describes the history of a new type of writing that allows for greater creativity. This new form of writing, which is called "experimental writing," is characterized by its use of nonstandard grammar, punctuation, and capitalization. Experimental writing is often used to express personal experiences and emotions, and it can help readers to see the world in new and different ways. While experimental writing is not always easy to understand, it can be very rewarding. What is the main idea of the passage?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_b33514d0e9856001_english_00379',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_e8","opensat_index":379}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice provides the most effective and precise use of language?',
    'multiple_choice',
    '[{"id":"A","text":"The farmer, who worked long hours and endured the heat and cold, had to learn to adapt to the harsh conditions of the land.","is_correct":false,"explanation":""},{"id":"B","text":"The farmer worked long hours and endured the heat and cold, but he had to learn to adapt to the harsh conditions of the land.","is_correct":false,"explanation":""},{"id":"C","text":"The farmer had to learn to adapt to the harsh conditions of the land, working long hours and enduring the heat and cold.","is_correct":true,"explanation":""},{"id":"D","text":"The farmer had to learn to adapt to the harsh conditions of the land, because he worked long hours and endured the heat and cold.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Choice C combines the two independent clauses into one grammatically correct sentence that flows more smoothly and effectively conveys the idea that the farmer had to learn to adapt to the harsh conditions of the land.  It also avoids unnecessary repetition of the phrase "he had to learn to adapt."  Choice A is incorrect because the nonrestrictive clause creates a pause in the flow of the sentence.  Choice B is incorrect because the conjunction "but" creates a sense of contrast that doesn’t fit the intended meaning of the sentence.  Choice D is incorrect because the conjunction "because" incorrectly implies that the farmer worked long hours and endured the heat and cold as a result of having to adapt to the harsh conditions of the land.',
    'Review the passage and eliminate choices that contradict the text.',
    'The following is a paragraph adapted from a short story. While the sentence is grammatically correct, it may not be the most effective way to present the information. The writer is trying to convey that the character has learned to adapt to the difficult circumstances he faces.  Which choice best improves the sentence by providing a more precise and effective use of language?  
 *The farmer had to learn to adapt to the harsh conditions of the land, he worked long hours and endured the heat and cold. *',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'a99c827e_english_00380',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"a99c827e","opensat_index":380}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following revisions to the underlined portion of the passage would be most effective in improving the clarity and conciseness of the passage?',
    'multiple_choice',
    '[{"id":"A","text":"—meaningfulness plays a role in memory.","is_correct":true,"explanation":""},{"id":"B","text":", a factor that contributes to memory.","is_correct":false,"explanation":""},{"id":"C","text":", which has an impact on memory.","is_correct":false,"explanation":""},{"id":"D","text":", and that is an important factor in memory.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Choice A is the best answer because it most effectively improves the clarity and conciseness of the passage. The original sentence is somewhat redundant, as it simply restates the idea that meaningfulness plays a role in memory. Choice A eliminates this redundancy by using a dash to introduce a brief explanation of this idea, which makes the sentence more concise and easier to understand. Choices B, C, and D are less effective because they are not as concise or clear as Choice A. Choice B uses a comma and a participial phrase, which makes the sentence more complex and less concise. Choice C uses a comma and a prepositional phrase, which is also less concise than Choice A. Choice D uses a comma and a coordinating conjunction, which is not as concise or clear as Choice A.',
    'Review the passage and eliminate choices that contradict the text.',
    'A recent study found that people are more likely to remember information when they have a personal connection to it. In other words, the more meaningful the information is to someone, the more likely they are to recall it. For instance, people are more likely to remember the name of their first pet than they are to remember the names of all the U.S. presidents. This is because they have a personal connection to the names of their pets, but they do not have a personal connection to the names of all the U.S. presidents. This suggests that meaningfulness plays a role in memory.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '3f833a7c_english_00381',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"3f833a7c","opensat_index":381}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best combines the underlined portion into a single, correctly punctuated sentence?',
    'multiple_choice',
    '[{"id":"A","text":"known for his creative use of local ingredients, was excited to be working with the new produce at the market.","is_correct":true,"explanation":""},{"id":"B","text":"known for his creative use of local ingredients, was excited to be working with the new produce at the market; ","is_correct":false,"explanation":""},{"id":"C","text":"known for his creative use of local ingredients, was excited to be working with the new produce at the market—","is_correct":false,"explanation":""},{"id":"D","text":"known for his creative use of local ingredients was excited to be working with the new produce at the market.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The best way to combine the underlined portion is to use a comma to separate the introductory phrase from the rest of the sentence.  The introductory phrase adds information about the chef and modifies the main clause: "the chef was excited to be working with the new produce at the market."  The other choices are incorrect because they use incorrect punctuation to separate the introductory phrase from the rest of the sentence.  Choice B is incorrect because it uses a semicolon incorrectly.  Semicolons are used to separate two independent clauses.  Choice C is incorrect because it uses a dash incorrectly.  Dashes can be used to separate a nonessential clause or phrase from the rest of the sentence, but this is not the case here.  Choice D is incorrect because it uses no punctuation at all.  A comma is needed to separate an introductory phrase from the rest of the sentence.',
    'Review the passage and eliminate choices that contradict the text.',
    'The chef, **known for his creative use of local ingredients**  was excited to be working with the new produce at the market.  He had spent the last few months exploring the area’s farms and learning about the sustainable practices used to cultivate their bounty.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'e4d82e7a_english_00382',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"e4d82e7a","opensat_index":382}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the main benefit of the "neuromorphic chip" described in this passage?',
    'multiple_choice',
    '[{"id":"A","text":"It can be used to build faster and more efficient computers.","is_correct":true,"explanation":""},{"id":"B","text":"It is more powerful than traditional computers.","is_correct":false,"explanation":""},{"id":"C","text":"It is more expensive than traditional computers.","is_correct":false,"explanation":""},{"id":"D","text":"It is less energy-efficient than traditional computers.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The passage states that the "neuromorphic chip" is "faster and more energy-efficient than traditional computers." Therefore, the key advantage of this chip is its ability to create faster and more efficient computers.',
    'Review the passage and eliminate choices that contradict the text.',
    'The text states that a new type of microchip called a "neuromorphic chip" was developed by a research team at the University of Manchester. This chip functions by mimicking the human brain, creating a system that is faster and more energy-efficient than traditional computers. According to the article, what is the key advantage of this "neuromorphic chip"?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_4e2ad288ede59fb7_english_00383',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"random_id_a7","opensat_index":383}'::jsonb
  ),
(
    gen_random_uuid(),
    'The blending of suspense and emotional themes in the novel most likely serves to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of realism and believability.","is_correct":false,"explanation":""},{"id":"B","text":"emphasize the novel’s themes of love, loss, and redemption.","is_correct":false,"explanation":""},{"id":"C","text":"enhance the reader’s emotional connection to the story.","is_correct":true,"explanation":""},{"id":"D","text":"help the reader better understand the novel’s complex plot.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The blending of suspense and emotional themes creates a more engaging and immersive reading experience for the reader.  Suspense keeps the reader on the edge of their seat, while the emotional themes allow the reader to connect with the characters on a deeper level.  This combination of elements helps to enhance the reader''s emotional connection to the story.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author of the novel is a master of suspense, weaving a complex web of clues and red herrings that keep the reader guessing until the very end.  But the novel also has a strong emotional impact, exploring themes of love, loss, and redemption. The author’s ability to blend these elements is what makes the novel so compelling. What is the most likely reason why the author blended suspense and emotional themes?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '59a1634f_english_00384',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"59a1634f","opensat_index":384}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the most likely reason why the author uses the word “even” in this sentence?',
    'multiple_choice',
    '[{"id":"A","text":"the speaker is surprised by how long ago the event occurred.","is_correct":true,"explanation":""},{"id":"B","text":"the speaker is attempting to persuade the reader to agree with the speaker.","is_correct":false,"explanation":""},{"id":"C","text":"the speaker is trying to emphasize the importance of the event.","is_correct":false,"explanation":""},{"id":"D","text":"the speaker is making a claim about the reader’s thoughts and feelings.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The word “even” is used to suggest that the speaker is surprised by how long ago the event occurred. The speaker is emphasizing that the event is still fresh in their mind, even though it happened a long time ago.',
    'Review the passage and eliminate choices that contradict the text.',
    'The use of the word “even” in the first sentence, “Even after all this time, I still remember the day I first met my best friend,” helps to establish the speaker’s point of view by suggesting',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '1190214f_english_00385',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"1190214f","opensat_index":385}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following best describes the point that the author is trying to illustrate in the passage?',
    'multiple_choice',
    '[{"id":"A","text":"The author is comparing two seemingly different things to emphasize their similarities.","is_correct":true,"explanation":""},{"id":"B","text":"The author is using an analogy to show that something is very complicated.","is_correct":false,"explanation":""},{"id":"C","text":"The author is explaining why the analogy is a useful writing technique.","is_correct":false,"explanation":""},{"id":"D","text":"The author is showing the reader how to use an analogy in their own writing.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The author is comparing two seemingly different things, a bicycle and an automobile, to highlight the similarities between them, which helps the reader better understand the author’s point.',
    'Review the passage and eliminate choices that contradict the text.',
    'A common writing technique is the use of an analogy, in which a writer compares two things that are seemingly different to highlight the similarities between them.  The passage below uses an analogy to help illustrate a point. What point is the author trying to illustrate with this analogy?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_cf924f017e9a9bf2_english_00386',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_d2","opensat_index":386}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following best summarizes the main idea of the passage?',
    'multiple_choice',
    '[{"id":"A","text":"The reasons for the decline in populations of *Chondrus crispus* are unclear, but the researchers have identified human activity as the root cause of the decline.","is_correct":false,"explanation":""},{"id":"B","text":"The decline in populations of *Chondrus crispus* is not necessarily the result of human activity, but the researchers are looking at other possible explanations for this decline.","is_correct":false,"explanation":""},{"id":"C","text":"The decline in populations of *Chondrus crispus* may be the result of human activity, but the researchers are unsure about the root cause of the decline.","is_correct":true,"explanation":""},{"id":"D","text":"The researchers are unsure about the reasons for the decline in populations of *Chondrus crispus*, but they hope to identify the root cause of the decline by studying the algae over time.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The passage states that the decline in *C. crispus* populations is not necessarily the result of human activity, but that the researchers are looking at other possible explanations for the decline.  This suggests that human activity may be a factor, but the researchers are unsure about the root cause of the decline.',
    'Review the passage and eliminate choices that contradict the text.',
    'A certain type of algae, called *Chondrus crispus,* is found in cold, rocky marine environments. It is a crucial source of *carrageenan,* a substance commonly used as a thickener in foods like ice cream. In 2022, researchers at the University of California, San Diego, noted that populations of *C. crispus* in the state are declining. The reasons for this decline are unclear, but the researchers suggested that human activity may be a factor.  The population of *C. crispus* was much higher in the 1990s than it is today. It was not until recent years that they noticed a change in the population of the algae. The decline in algae populations is not necessarily the result of human activity. The researchers are looking at other possible explanations for this decline.  The researchers hope to identify the root cause of the decline by studying the algae over time.  What is the main idea of the passage?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'f890dc20_english_00387',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"f890dc20","opensat_index":387}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the author includes details about the time of day but not the date or length of the trip to',
    'multiple_choice',
    '[{"id":"A","text":"create a more specific setting for the reader.","is_correct":false,"explanation":""},{"id":"B","text":"highlight the importance of the author’s journey.","is_correct":false,"explanation":""},{"id":"C","text":"emphasize the passage’s focus on a broader theme.","is_correct":true,"explanation":""},{"id":"D","text":"suggest that the author’s experiences were short-lived.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The passage focuses on the broader theme of travel, not the specifics of a particular trip. The author doesn’t mention the date or length of the trip to avoid focusing too much on those details. The author is instead trying to convey the essence of travel, which is why the time of day is the only detail mentioned.',
    'Review the passage and eliminate choices that contradict the text.',
    'The passage describes the author’s experiences during a trip to a specific location. However, the author makes no mention of the date of the trip or the length of the trip, only noting the time of day during which it occurred. This suggests that the author''s main purpose in the passage is not to recount the details of a particular trip but rather to offer a broader reflection on the experience of travel. What is the most likely reason why the author chooses to include details about the time of day but not the date or length of the trip?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '089f567b_english_00388',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"089f567b","opensat_index":388}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best combines the sentences at the underlined portion to create a grammatically correct and clear sentence?',
    'multiple_choice',
    '[{"id":"A","text":"The song is a powerful reminder, that even in the darkest of times, there is always light to be found.","is_correct":false,"explanation":""},{"id":"B","text":"The song is a powerful reminder, that even in the darkest of times, there is always light to be found.","is_correct":false,"explanation":""},{"id":"C","text":"The song is a powerful reminder that even in the darkest of times, there is always light to be found.","is_correct":true,"explanation":""},{"id":"D","text":"The song, is a powerful reminder that even in the darkest of times, there is always light to be found.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The correct answer is C, which removes the unnecessary comma. Choice A is incorrect because it contains an unnecessary comma. Choice B is incorrect because it contains an unnecessary comma. Choice D is incorrect because it contains an unnecessary comma and an incorrect placement of a comma.',
    'Review the passage and eliminate choices that contradict the text.',
    'The first time I heard the song "You Say" by Lauren Daigle, I was immediately struck by its beautiful message of hope and redemption. The song is a powerful reminder that even in the darkest of times, there is always light to be found.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_1a4acca0998261dd_english_00389',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"random_id_e8","opensat_index":389}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the word "you" is used to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of intimacy and connection with the reader.","is_correct":true,"explanation":""},{"id":"B","text":"describe the speaker’s feelings and experiences.","is_correct":false,"explanation":""},{"id":"C","text":"emphasize the importance of the speaker’s message.","is_correct":false,"explanation":""},{"id":"D","text":"suggest that the speaker is addressing a large audience.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The speaker is addressing the reader directly by using the word "you." This creates a sense of intimacy and connection with the reader, which can help the reader feel more engaged with the message.',
    'Review the passage and eliminate choices that contradict the text.',
    'The most obvious sign that the speaker is speaking directly to the reader is the use of the word "you." There are other elements of the passage that may help to make the speaker seem more immediate and personal. The speaker refers to events and places that are familiar to the reader, and the speaker uses a conversational tone throughout the passage. What is the most likely reason why the writer uses the word "you"?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '12d8c11d_english_00390',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"12d8c11d","opensat_index":390}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best maintains the parallel structure of the sentence?',
    'multiple_choice',
    '[{"id":"A","text":"The driver, however, was not in the least disturbed, nor did he keep turning his head to left and right.","is_correct":false,"explanation":""},{"id":"B","text":"The driver, however, was not in the least disturbed, and kept turning his head to left and right.","is_correct":true,"explanation":""},{"id":"C","text":"The driver, however, was not in the least disturbed, and kept turning his head to left and right; he could not see anything through the darkness.","is_correct":false,"explanation":""},{"id":"D","text":"The driver, however, was not in the least disturbed, although he kept turning his head to left and right.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The original sentence uses a semicolon to separate two independent clauses, but the semicolon should not be used in the same sentence as a conjunction. The conjunction "and" and the verb "kept"  match the verb tense of the first clause, "was not."',
    'Review the passage and eliminate choices that contradict the text.',
    'The following text is from Bram Stoker’s 1897 novel Dracula. The narrator is being driven in a carriage through a remote region at night. 

The baying of the wolves sounded nearer and nearer, as though they were closing round on us from every side. I grew dreadfully afraid, and the horses shared my fear. The driver, however, was not in the least disturbed; he kept turning his head to left and right, but I could not see anything through the darkness. 

Which choice best maintains the parallel structure of the sentence?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '97ab5669_english_00391',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"97ab5669","opensat_index":391}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following choices is the most effective way to combine the last two sentences of the passage to maintain the grammatical coherence of the passage?',
    'multiple_choice',
    '[{"id":"A","text":"It has been praised for its realism, its humor, and its social commentary, and it is widely considered to be a classic of American literature.","is_correct":false,"explanation":""},{"id":"B","text":"Twain''s novel is widely considered to be a classic of American literature, and it has been praised for its realism, its humor, and its social commentary.","is_correct":true,"explanation":""},{"id":"C","text":"It has been praised for its realism, its humor, and its social commentary, which is widely considered to be a classic of American literature.","is_correct":false,"explanation":""},{"id":"D","text":"Being praised for its realism, its humor, and its social commentary, Twain''s novel is widely considered to be a classic of American literature.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The most effective way to combine the last two sentences is to use a comma and the coordinating conjunction "and." This creates a grammatically correct and concise sentence. The other choices create either a run-on sentence or a comma splice, or they are grammatically incorrect.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author of the novel *The Adventures of Huckleberry Finn*  is Mark Twain. The story follows the experiences of Huckleberry Finn, a young boy who runs away from home and travels down the Mississippi River with an escaped slave. Twain''s novel is widely considered to be a classic of American literature. It has been praised for its realism, its humor, and its social commentary.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_e920fe40e2165922_english_00392',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a5","opensat_index":392}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice provides the best punctuation for the final sentence of this passage, according to the conventions of Standard English?',
    'multiple_choice',
    '[{"id":"A","text":"the societies of Spain and the Aztec Empire, but the references to beliefs and customs in Spain should be attributed to a coincidental resemblance between the societies of Spain and the Aztec Empire.","is_correct":true,"explanation":""},{"id":"B","text":"the societies of Spain and the Aztec Empire; but the references to beliefs and customs in Spain should be attributed to a coincidental resemblance between the societies of Spain and the Aztec Empire.","is_correct":false,"explanation":""},{"id":"C","text":"the societies of Spain and the Aztec Empire, but the references to beliefs and customs in Spain should be attributed to a coincidental resemblance between the societies of Spain and the Aztec Empire; ","is_correct":false,"explanation":""},{"id":"D","text":"the societies of Spain and the Aztec Empire, but the references to beliefs and customs in Spain should be attributed to a coincidental resemblance between the societies of Spain and the Aztec Empire—","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Choice A is the best answer. The convention being tested is punctuation between a main clause and a supplementary element within a sentence. The comma after "Empire" pairs with the comma after "Spain" to separate the supplementary element "but the references to beliefs and customs in Spain" from the rest of the sentence.  This supplementary element functions to define the term "society," and the pair of commas indicates that this element could be removed without affecting the grammatical coherence of the sentence.  ',
    'Review the passage and eliminate choices that contradict the text.',
    'The first sentence of the passage is a run-on sentence.  It does not have a proper punctuation mark at the end of the first clause.  A comma should be added after "society" to separate the first clause from the second clause.  The second clause needs a comma to separate the supplementary element from the rest of the sentence.  The correct punctuation is as follows: "The societies of Spain and the Aztec Empire had a rich history, but the references to beliefs and customs in Spain should be attributed to a coincidental resemblance between the societies of Spain and the Aztec Empire."',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_697b38cf848bd361_english_00393',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_c9","opensat_index":393}'::jsonb
  ),
(
    gen_random_uuid(),
    'The third sentence in this passage primarily serves to',
    'multiple_choice',
    '[{"id":"A","text":"explain the causes of the Industrial Revolution.","is_correct":false,"explanation":""},{"id":"B","text":"describe the effects of the Industrial Revolution.","is_correct":true,"explanation":""},{"id":"C","text":"provide an example of the Industrial Revolution.","is_correct":false,"explanation":""},{"id":"D","text":"offer a historical context for the Industrial Revolution.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The third sentence describes the effects of the Industrial Revolution, specifically the emergence of large cities and a mass migration of people from rural areas to urban centers.  The sentence serves as a transition from the second sentence, which describes the economic changes that led to the Industrial Revolution, to the fourth sentence, which describes the economic and societal consequences of the Industrial Revolution.',
    'Review the passage and eliminate choices that contradict the text.',
    'A large-scale shift in the American economy occurred during the late 19th century.  Prior to the Industrial Revolution, most Americans worked in agriculture.  However, the demand for industrial goods, such as textiles and steel, increased, and factories sprung up throughout the nation.  This rapid industrialization led to the emergence of large cities and a mass migration of people from rural areas to urban centers.  The Industrial Revolution transformed the United States into a nation of factory workers, and the country’s economy became more reliant on manufacturing.  What is the purpose of the third sentence in the passage?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '2387b412_english_00394',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"2387b412","opensat_index":394}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best completes the text so that it conforms to the conventions of Standard English?',
    'multiple_choice',
    '[{"id":"A","text":"Jazz music, it has since influenced many other musical styles.","is_correct":false,"explanation":""},{"id":"B","text":"Jazz music, which has since influenced many other musical styles.","is_correct":true,"explanation":""},{"id":"C","text":"Jazz music, that has since influenced many other musical styles.","is_correct":false,"explanation":""},{"id":"D","text":"Jazz music, has since influenced many other musical styles.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The comma and the relative pronoun "which" correctly combine the two clauses into a single sentence. The comma separates the two clauses, and "which" refers back to "Jazz music." The other choices create incorrect comma splices or use incorrect relative pronouns.',
    'Review the passage and eliminate choices that contradict the text.',
    'In the early 1900s, the term "jazz" was used to describe a variety of musical styles, but it became associated with a particular style of music that originated in New Orleans. During the 1920s, jazz music was often played in clubs and dance halls. By the 1930s, jazz music was a global phenomenon, and it has since influenced many other musical styles.  Jazz musicians use improvisation—playing music spontaneously, without a written score. This creates a sense of excitement and energy that is unique to jazz music.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_4242757159fc452d_english_00395',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_e7","opensat_index":395}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following best expresses the central conflict that Elizabeth Bennet faces in *Pride and Prejudice*? ',
    'multiple_choice',
    '[{"id":"A","text":"She must choose between her love for Mr. Darcy and her desire to maintain her social standing.","is_correct":false,"explanation":""},{"id":"B","text":"She must choose between her desire for a wealthy husband and her desire for a fulfilling career.","is_correct":false,"explanation":""},{"id":"C","text":"She must choose between her family''s expectations and her own dreams of independence.","is_correct":false,"explanation":""},{"id":"D","text":"She must choose between her belief in the importance of reason and her belief in the importance of sensibility.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The novel explores the contrast between the values of reason and sensibility, and Elizabeth''s journey is marked by this conflict. Her initial judgment of Mr. Darcy is based on her sensibilities, but she eventually learns to see him through the lens of reason, ultimately accepting him as a suitable match.',
    'Review the passage and eliminate choices that contradict the text.',
    'In the novel *Pride and Prejudice*, Jane Austen explores the complex social dynamics of the English gentry during the late 18th century.  Through witty dialogue and keen observation, Austen presents a world of social expectations, marriage as a financial transaction, and the importance of reputation.  One of the central themes of the novel is the clash between the values of reason and sensibility.  The protagonist, Elizabeth Bennet, is a strong and independent woman who challenges the societal norms of her time.  She is initially attracted to Mr. Darcy, a wealthy and proud gentleman, but she is repelled by his arrogance and his disdain for her social standing.  As the novel progresses, Elizabeth learns to see beyond appearances and to appreciate Mr. Darcy’s true character.  Ultimately, Elizabeth and Darcy find happiness together, but their journey is not without its obstacles.  The novel''s enduring popularity suggests that its themes of love, marriage, and social class continue to resonate with readers today.',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_74989d81bbf7c78c_english_00396',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a8","opensat_index":396}'::jsonb
  ),
(
    gen_random_uuid(),
    'As a teenager, I''ve been fortunate enough to experience "home" in many different ways.',
    'multiple_choice',
    '[{"id":"A","text":"As a teenager, I’ve been fortunate enough to experience “home” in many different ways.","is_correct":false,"explanation":""},{"id":"B","text":"As a teenager, I have been fortunate enough to experience \"home\" in many different ways.","is_correct":true,"explanation":""},{"id":"C","text":"As a teenager, I’ve been fortunate to experience home in many different ways.","is_correct":false,"explanation":""},{"id":"D","text":"Being a teenager, I’ve been fortunate enough to experience \"home\" in many different ways.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Choice B is the best option because it follows the conventions of Standard English by using proper capitalization and punctuation for the quotation marks. Choice A is incorrect because it doesn’t have proper capitalization of the word "home." Choice C is incorrect because it doesn’t include the quotation marks for the word "home." Choice D is incorrect because it uses a participial phrase that does not grammatically modify the rest of the sentence.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author of this essay is a student who wants to go to college. She hopes that her essay will impress her potential professors. The student is writing about the idea of "home" and how it has changed over time for her. What is the best way to rewrite the following sentence, paying attention to the conventions of Standard English?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '234eb589_english_00397',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"234eb589","opensat_index":397}'::jsonb
  ),
(
    gen_random_uuid(),
    'The sentence below contains an error in punctuation. Which choice corrects the error in the sentence? <br> **The old, weathered house, stood at the end of the road, its windows boarded up.**',
    'multiple_choice',
    '[{"id":"A","text":"The old, weathered house stood at the end of the road, its windows boarded up.","is_correct":true,"explanation":""},{"id":"B","text":"The old, weathered house; stood at the end of the road, its windows boarded up.","is_correct":false,"explanation":""},{"id":"C","text":"The old, weathered house stood at the end of the road; its windows boarded up.","is_correct":false,"explanation":""},{"id":"D","text":"The old, weathered house, stood at the end of the road its windows boarded up.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The original sentence incorrectly uses commas to separate the words "house" and "stood." The correct sentence separates these words with a period, as in choice A.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_941d3c2f8bf5cd41_english_00398',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"random_id_22","opensat_index":398}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice most effectively combines the sentences below into a single sentence with correct punctuation? 
"The artist was known for his detailed, realistic paintings. He was also a skilled sculptor.  "',
    'multiple_choice',
    '[{"id":"A","text":"The artist, who was known for his detailed, realistic paintings, was also a skilled sculptor.","is_correct":false,"explanation":""},{"id":"B","text":"The artist was known for his detailed, realistic paintings; he was also a skilled sculptor.","is_correct":false,"explanation":""},{"id":"C","text":"The artist was known for his detailed, realistic paintings, and he was also a skilled sculptor.","is_correct":true,"explanation":""},{"id":"D","text":"The artist was known for his detailed, realistic paintings he was also a skilled sculptor.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The most effective way to combine the sentences is to use a comma and a coordinating conjunction. This creates a grammatically correct sentence with the correct punctuation.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_a546938bd8c09afd_english_00399',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"random_id_c8","opensat_index":399}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;