INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'If  $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve this system of equations using elimination. Multiplying the second equation by 3, we get $3x - 3y = 3$. Adding this equation to the first equation, we get $5x = 15$. Dividing both sides by 5, we find that $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_4017f04669e3db1f_math_00857',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_12","opensat_index":857}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 12 meters and a width of 5 meters. What is the area, in square meters, of the rectangle?',
    'multiple_choice',
    '[{"id":"A","text":"17","is_correct":false,"explanation":""},{"id":"B","text":"34","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":true,"explanation":""},{"id":"D","text":"144","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is found by multiplying its length and width. Therefore, the area of this rectangle is 12 meters * 5 meters = 60 square meters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_73876ddd2c8714f0_math_00858',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a1","opensat_index":858}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 students found that 60 students like to play basketball and 40 students like to play soccer.  If 20 students like to play both basketball and soccer, how many students like to play only basketball?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":false,"explanation":""},{"id":"B","text":"40","is_correct":true,"explanation":""},{"id":"C","text":"60","is_correct":false,"explanation":""},{"id":"D","text":"80","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can use a Venn diagram to help visualize the problem.  Let $B$ represent the set of students who like basketball, and let $S$ represent the set of students who like soccer.  We know that $n(B) = 60$, $n(S) = 40$, and $n(B \cap S) = 20$.  The number of students who like only basketball is given by $n(B) - n(B \cap S) = 60 - 20 = 40$.  

[asy]
unitsize(0.6 cm);
label("Basketball", (2,7), E);
label("Soccer", (7,2), S);
draw(Circle((2,5), 2.5));
draw(Circle((6,1), 2.5));
draw((2,5)--(6,1));
label("20", (4,3.5));
label("40", (6,4.5), E);
label("20", (3,1), S);
[/asy]',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'f84c95a3_math_00859',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"f84c95a3","opensat_index":859}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 6x + 9 = 0$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":true,"explanation":""},{"id":"B","text":"6","is_correct":false,"explanation":""},{"id":"C","text":"9","is_correct":false,"explanation":""},{"id":"D","text":"18","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The given equation is a perfect square trinomial, which can be factored as $(x-3)^2 = 0$. Taking the square root of both sides, we get $x - 3 = 0$. Adding 3 to both sides, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '1348f21a_math_00860',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"1348f21a","opensat_index":860}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of 100 students took a test. The average score on the test was 75.  A second group of 50 students took the same test, and their average score was 85. What is the average score of all 150 students who took the test?',
    'multiple_choice',
    '[{"id":"A","text":"78","is_correct":false,"explanation":""},{"id":"B","text":"79","is_correct":false,"explanation":""},{"id":"C","text":"80","is_correct":true,"explanation":""},{"id":"D","text":"81","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The total score of the first group of students is 100 * 75 = 7500. The total score of the second group of students is 50 * 85 = 4250. The total score of all 150 students is 7500 + 4250 = 11750. Therefore, the average score of all 150 students is 11750 / 150 = 80.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_b086fd10d1619f93_math_00861',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_5","opensat_index":861}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $\frac{2x+1}{x-3} = 4$ is equivalent to which of the following equations?',
    'multiple_choice',
    '[{"id":"A","text":"$2x + 1 = 4x - 12$","is_correct":false,"explanation":""},{"id":"B","text":"$2x + 1 = 4$","is_correct":false,"explanation":""},{"id":"C","text":"$2x + 1 = 4(x - 3)$","is_correct":true,"explanation":""},{"id":"D","text":"$2x + 1 = 4x - 3$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for x, we multiply both sides of the equation by (x-3). This gives us $2x + 1 = 4(x - 3)$.  The other options are incorrect and may result from errors in distributing the 4 on the right-hand side of the equation.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_665311a3b5b94528_math_00862',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a5","opensat_index":862}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5.  What is the circumference of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":true,"explanation":""},{"id":"C","text":"25\\pi","is_correct":false,"explanation":""},{"id":"D","text":"50\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius. In this case, $r = 5$, so the circumference is $C = 2\pi (5) = 10\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_54be56768246c728_math_00863',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_b6","opensat_index":863}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of friends are planning a trip. They decide to rent a car for \$45 per day plus a one-time insurance fee of \$20.  If the total cost of renting the car is \$145, how many days did the group rent the car?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Let''s use the variable *d* to represent the number of days the car was rented. The total cost can be represented by the equation: 45d + 20 = 145. Subtracting 20 from both sides gives 45d = 125. Dividing both sides by 45 gives d = 2.78. Since we can''t rent a car for a fraction of a day, the group rented the car for 3 days.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_dd99a7aa3b950851_math_00864',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a9","opensat_index":864}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has legs of length 5 and 12. What is the length of the hypotenuse?',
    'multiple_choice',
    '[{"id":"A","text":"7","is_correct":false,"explanation":""},{"id":"B","text":"13","is_correct":true,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"24","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs.  Therefore, the length of the hypotenuse is $\sqrt{5^2 + 12^2} = \sqrt{169} = 13$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_319f954a30ac4ce3_math_00865',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a9","opensat_index":865}'::jsonb
  ),
(
    gen_random_uuid(),
    'The sum of two numbers is 10, and their difference is 4. What is the value of the larger number?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"7","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Let the larger number be x and the smaller number be y. We are given that x + y = 10 and x - y = 4. Adding these two equations together eliminates y, giving us 2x = 14. Solving for x, we get x = 7. Therefore, the larger number is 7.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_b8e7affa938f3164_math_00866',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_b9","opensat_index":866}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = \frac{x^2 - 4}{x - 2}$. For what value(s) of $x$ is $f(x)$ undefined?',
    'multiple_choice',
    '[{"id":"A","text":"0","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"-2","is_correct":false,"explanation":""},{"id":"D","text":"2 and -2","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A function is undefined when the denominator of the fraction is equal to zero. In this case, the denominator is $x-2$. Solving the equation $x-2 = 0$, we find that $x = 2$. Therefore, $f(x)$ is undefined when $x = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '2c31ff5c_math_00867',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"2c31ff5c","opensat_index":867}'::jsonb
  ),
(
    gen_random_uuid(),
    'In triangle $ABC$, angle $C$ is a right angle, and $AC = BC$. What is the measure of angle $A$?',
    'multiple_choice',
    '[{"id":"A","text":"30°","is_correct":false,"explanation":""},{"id":"B","text":"45°","is_correct":true,"explanation":""},{"id":"C","text":"60°","is_correct":false,"explanation":""},{"id":"D","text":"90°","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Since $AC=BC$, triangle $ABC$ is a 45-45-90 triangle.  Therefore, the measure of angle $A$ is 45°.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_009b67088fd5e7cb_math_00868',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a9","opensat_index":868}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells two types of cookies: chocolate chip and peanut butter. The store can sell a maximum of 100 cookies per day. On a particular day, the store sold 25 chocolate chip cookies. If the number of peanut butter cookies sold was 3 times the number of chocolate chip cookies sold, what was the number of peanut butter cookies sold that day?',
    'multiple_choice',
    '[{"id":"A","text":"30","is_correct":false,"explanation":""},{"id":"B","text":"60","is_correct":false,"explanation":""},{"id":"C","text":"75","is_correct":true,"explanation":""},{"id":"D","text":"90","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Since 25 chocolate chip cookies were sold, and the number of peanut butter cookies sold was 3 times that amount, the store sold 3 * 25 = 75 peanut butter cookies.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'f54c918d_math_00869',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"f54c918d","opensat_index":869}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangular prism has a length of 5 centimeters, a width of 4 centimeters, and a height of 3 centimeters. What is the volume, in cubic centimeters, of the prism?',
    'multiple_choice',
    '[{"id":"A","text":"12","is_correct":false,"explanation":""},{"id":"B","text":"24","is_correct":false,"explanation":""},{"id":"C","text":"36","is_correct":false,"explanation":""},{"id":"D","text":"60","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The volume of a rectangular prism is found by multiplying its length, width, and height.  So, the volume of the prism is 5 * 4 * 3 = 60 cubic centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '645fd11a_math_00870',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"645fd11a","opensat_index":870}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 5x - 6 = 0$, what is the sum of the solutions to this equation?',
    'multiple_choice',
    '[{"id":"A","text":"-5","is_correct":true,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The sum of the solutions to the quadratic equation $ax^2 + bx + c = 0$ is given by $-b/a$. In this case, $a = 1$ and $b = 5$, so the sum of the solutions is $-5/1 = -5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_77260794a90743ff_math_00871',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_6","opensat_index":871}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 2x^2 + 3x - 1. What is the value of *f*(2)?',
    'multiple_choice',
    '[{"id":"A","text":"11","is_correct":false,"explanation":""},{"id":"B","text":"15","is_correct":false,"explanation":""},{"id":"C","text":"19","is_correct":true,"explanation":""},{"id":"D","text":"23","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find *f*(2), we substitute 2 for *x* in the function: *f*(2) = 2(2)^2 + 3(2) - 1.  Simplifying, we get *f*(2) = 8 + 6 - 1, or *f*(2) = 13.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_f9ed043c304232e4_math_00872',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a7","opensat_index":872}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the value of  $x$ if  $x^2 - 10x + 25 = 0$?',
    'multiple_choice',
    '[{"id":"A","text":"5","is_correct":true,"explanation":""},{"id":"B","text":"10","is_correct":false,"explanation":""},{"id":"C","text":"25","is_correct":false,"explanation":""},{"id":"D","text":"50","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The equation $x^2 - 10x + 25 = 0$ is a perfect square trinomial, which can be factored as $(x - 5)^2 = 0$. Taking the square root of both sides gives $x - 5 = 0$. Adding 5 to both sides gives $x = 5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '132b6748_math_00873',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"132b6748","opensat_index":873}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $\frac{2x + 3}{x - 1} = 5$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for $x$, we first multiply both sides of the equation by $x - 1$: $2x + 3 = 5(x - 1)$. Expanding the right side of the equation, we get $2x + 3 = 5x - 5$. Combining like terms, we get $8 = 3x$. Dividing both sides of the equation by 3, we get $x = \frac{8}{3}$ or $x = 2\frac{2}{3}$. Of the given choices, the closest value is 4. Therefore, the value of $x$ is 4.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '899b8d7b_math_00874',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"899b8d7b","opensat_index":874}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a radius of 5 units is inscribed in a square.  What is the area, in square units, of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square. The diameter of the circle is twice the radius, or 10 units.  The area of the square is the side length squared, so the area of the square is 10^2 = 100 square units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_f748949ec475f186_math_00875',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_d5","opensat_index":875}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5. What is the circumference of the circle?  (Express your answer in terms of \pi.)',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":true,"explanation":""},{"id":"C","text":"25\\pi","is_correct":false,"explanation":""},{"id":"D","text":"50\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula C = 2\pi r, where r is the radius.  Substituting 5 for r gives us C = 2\pi(5) = 10\pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_98b2b59387463744_math_00876',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c6","opensat_index":876}'::jsonb
  ),
(
    gen_random_uuid(),
    'A line passes through the points $(-2, 5)$ and $(4, -3)$. What is the slope of this line?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":true,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"2","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The slope of a line passing through points $(x_1, y_1)$ and $(x_2, y_2)$ is given by the formula: $\frac{y_2 - y_1}{x_2 - x_1}$.  Substituting the given points into the formula, we get: $\frac{-3 - 5}{4 - (-2)} = \frac{-8}{6} = -\frac{4}{3}$.  Therefore, the slope of the line is $-\frac{4}{3}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'd42b6e8f_math_00877',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"d42b6e8f","opensat_index":877}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units.  What is the area of the circle in square units?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":true,"explanation":""},{"id":"D","text":"100\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula $A = \pi r^2$, where $r$ is the radius.  Substituting 5 for $r$, we get $A = \pi (5)^2 = 25\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_3f7414489623763a_math_00878',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_b8","opensat_index":878}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the solution to the equation $3x - 2 = 10 - x$?',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":false,"explanation":""},{"id":"B","text":"-2","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"3","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To solve for x, we add x to both sides of the equation: $3x - 2 + x = 10 - x + x$, which gives us $4x - 2 = 10$. Then, we add 2 to both sides: $4x - 2 + 2 = 10 + 2$, or $4x = 12$. Dividing both sides by 4, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '8b85219d_math_00879',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"8b85219d","opensat_index":879}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store is having a sale on all items, with a discount of 20%. If a customer buys an item originally priced at $150, how much will they save?',
    'multiple_choice',
    '[{"id":"A","text":"$15","is_correct":false,"explanation":""},{"id":"B","text":"$30","is_correct":true,"explanation":""},{"id":"C","text":"$60","is_correct":false,"explanation":""},{"id":"D","text":"$75","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A 20% discount on a $150 item is equivalent to 0.20 * $150 = $30.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_44b1c56aa1c6c4cc_math_00880',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c9","opensat_index":880}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  $y = 2x + 1$ and  $x = 3$, what is the value of *y*?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"7","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substituting *x* = 3 into the equation  *y* = 2*x* + 1, we get *y* = 2(3) + 1, or *y* = 6 + 1, or *y* = 7.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'd3d44ee4_math_00881',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"d3d44ee4","opensat_index":881}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;