INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'The passage is primarily intended to',
    'multiple_choice',
    '[{"id":"A","text":"highlight the speaker’s passion for the game.","is_correct":false,"explanation":""},{"id":"B","text":"explain the rules of the speaker’s favorite game.","is_correct":false,"explanation":""},{"id":"C","text":"persuade the reader to play the speaker’s favorite game.","is_correct":true,"explanation":""},{"id":"D","text":"describe the history of the speaker’s favorite game.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The passage is written to persuade the reader to play the speaker''s favorite game. The speaker lists a series of reasons why the game is appealing, uses vivid language to appeal to the reader''s senses, and uses a conversational tone to engage the reader.',
    'Review the passage and eliminate choices that contradict the text.',
    'The speaker’s main goal is to persuade the reader that their favorite game is the best. The speaker’s argument relies on a series of reasons, each of which is meant to demonstrate the game’s unique appeal.  The speaker makes use of descriptive language to appeal to the reader’s senses.  In addition, the speaker uses a conversational tone to enhance the reader’s engagement with the passage. What is the main idea of the passage?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_222e79badc8d26da_english_00300',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"random_id_e5","opensat_index":300}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice provides the best punctuation for the sentence:  “For example, avoid using jargon or technical terms that the reader might not be familiar with, and make sure that your sentences are well-constructed and grammatically correct”?',
    'multiple_choice',
    '[{"id":"A","text":"For example, avoid using jargon or technical terms that the reader might not be familiar with, and make sure that your sentences are well-constructed and grammatically correct.","is_correct":true,"explanation":""},{"id":"B","text":"For example, avoid using jargon or technical terms, that the reader might not be familiar with, and make sure that your sentences are well-constructed and grammatically correct.","is_correct":false,"explanation":""},{"id":"C","text":"For example, avoid using jargon or technical terms that the reader might not be familiar with, and make sure that your sentences are well-constructed, and grammatically correct.","is_correct":false,"explanation":""},{"id":"D","text":"For example, avoid using jargon, or technical terms, that the reader might not be familiar with, and make sure that your sentences are well-constructed and grammatically correct.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The sentence correctly uses a comma after "For example" to separate the introductory phrase from the rest of the sentence.  The sentence also correctly uses a comma to separate the two independent clauses in the sentence.  There is no need for a comma before "and" because it is connecting two verbs that are acting on the same subject: "avoid using jargon or technical terms" and "make sure that your sentences are well-constructed and grammatically correct."  The sentence does not need a comma after "familiar with" because the phrase "and make sure that your sentences are well-constructed and grammatically correct" is essential to the meaning of the sentence, and it is not a nonessential element.  Therefore, choice A provides the best punctuation for the sentence.',
    'Review the passage and eliminate choices that contradict the text.',
    'The most important thing to remember about writing is to be clear.  You should always write in a way that is easy for the reader to understand.  For example, avoid using jargon or technical terms that the reader might not be familiar with, and make sure that your sentences are well-constructed and grammatically correct.  How do you write clearly?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'b23a1d1b_english_00301',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"b23a1d1b","opensat_index":301}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best completes the sentence with the most logical transition and correct punctuation?',
    'multiple_choice',
    '[{"id":"A","text":"Indeed, the poet''s use of imagery, particularly in the line \"the wind howls like a wolf,\" evokes a sense of isolation and fear in the reader.","is_correct":false,"explanation":""},{"id":"B","text":"For example, the poet''s use of imagery, particularly in the line \"the wind howls like a wolf,\" evokes a sense of isolation and fear in the reader.","is_correct":true,"explanation":""},{"id":"C","text":"The poet''s use of imagery, particularly in the line \"the wind howls like a wolf,\" evokes a sense of isolation and fear in the reader; however,","is_correct":false,"explanation":""},{"id":"D","text":"For example, the poet''s use of imagery, particularly in the line \"the wind howls like a wolf,\" evokes a sense of isolation and fear in the reader, for instance,","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The sentence requires an example to illustrate the claim that a poet''s use of language can affect a reader’s understanding of a poem. The word "for example" logically introduces an example. The semicolon in Choice C and the comma followed by "for instance" in Choice D both create a comma splice, an error in sentence structure.',
    'Review the passage and eliminate choices that contradict the text.',
    'The poet''s use of imagery, particularly in the line "the wind howls like a wolf," evokes a sense of isolation and fear in the reader.  The poet''s use of language is effective, but it is important to note that it is not always clear how a poet''s use of language can affect a reader’s understanding of a poem.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_54871f2cb3dc6dd9_english_00302',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"random_id_a8","opensat_index":302}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the phrase “more nuanced understanding” is most likely intended to',
    'multiple_choice',
    '[{"id":"A","text":"demonstrate the author’s expertise on the subject.","is_correct":false,"explanation":""},{"id":"B","text":"highlight the author’s unique perspective on the subject.","is_correct":false,"explanation":""},{"id":"C","text":"emphasize the complexity of the subject.","is_correct":true,"explanation":""},{"id":"D","text":"convince the reader to accept the author’s argument.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The author’s use of this phrase highlights the complexity of the subject, emphasizing that it is more nuanced than previously thought. This complexity is supported by the author’s use of evidence from a variety of sources.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author uses the phrase "more nuanced understanding" to suggest that the previous view of the subject was too simplistic and that the new view, presented in this essay, is more complex and accurate. This is evident in the way that the author presents evidence from a variety of sources, including historical documents, scientific studies, and personal anecdotes.  The author’s use of this phrase is most likely intended to',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_1ca952a9dfcd9a38_english_00303',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a1","opensat_index":303}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following best combines the two sentences at the underlined portion into a single sentence?  ',
    'multiple_choice',
    '[{"id":"A","text":"She was, however, a controversial figure, and many disagreed with her methods and interpretations. ","is_correct":false,"explanation":""},{"id":"B","text":"However, she was a controversial figure, and many disagreed with her methods and interpretations.","is_correct":true,"explanation":""},{"id":"C","text":"A controversial figure, however, she was, and many disagreed with her methods and interpretations.","is_correct":false,"explanation":""},{"id":"D","text":"She was, however, a controversial figure because many disagreed with her methods and interpretations.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The best way to combine these sentences is to use the conjunction "however" to show the contrast between the two parts of the sentence.  The phrase "however, she was" is placed correctly because the conjunction "however" is a conjunctive adverb, which should be set off with a comma before and after it.  The phrase "and many disagreed with her methods and interpretations" is a dependent clause, which should also be set off with a comma before it.',
    'Review the passage and eliminate choices that contradict the text.',
    'The scientist’s research was groundbreaking, and her findings were widely discussed in the scientific community.  She was, however, a controversial figure, and many disagreed with her methods and interpretations.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '1111111_english_00304',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"1111111","opensat_index":304}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice provides the most effective transition between the two sentences? ',
    'multiple_choice',
    '[{"id":"A","text":"As a result,","is_correct":false,"explanation":""},{"id":"B","text":"For instance,","is_correct":true,"explanation":""},{"id":"C","text":"In addition,","is_correct":false,"explanation":""},{"id":"D","text":"Therefore,","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The most effective transition is "For instance," because it introduces an example that illustrates the point made in the previous sentence.  The previous sentence states that some individuals who took risks transformed the country, and the example of Henry Ford illustrates this point. The other choices are less effective. "As a result" suggests a cause-and-effect relationship, which is not present in the two sentences. "In addition" suggests that the example is additional information to the previous sentence, but the example is actually an illustration of the previous sentence. "Therefore" suggests a conclusion, but the example is not a conclusion.',
    'Review the passage and eliminate choices that contradict the text.',
    'The history of the United States is filled with stories of individuals who, by taking risks, transformed the country. Some of these individuals were inventors, others were entrepreneurs, and still others were activists.  The entrepreneur Henry Ford, for example, changed the way people traveled by perfecting a system of mass production for automobiles.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_5da4544d4af19258_english_00305',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"random_id_c7","opensat_index":305}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice most effectively combines the two sentences at the end of the passage?  The text is a compilation of all of Shakespeare’s plays, and it is considered to be the definitive source for his work.',
    'multiple_choice',
    '[{"id":"A","text":"The text is a compilation of all of Shakespeare’s plays; it is considered to be the definitive source for his work.","is_correct":true,"explanation":""},{"id":"B","text":"The text is a compilation of all of Shakespeare’s plays, it is considered to be the definitive source for his work.","is_correct":false,"explanation":""},{"id":"C","text":"The text is a compilation of all of Shakespeare’s plays; considered to be the definitive source for his work.","is_correct":false,"explanation":""},{"id":"D","text":"The text is a compilation of all of Shakespeare’s plays, considered to be the definitive source for his work.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The semicolon correctly joins the two independent clauses in the sentence, because the second clause provides a restatement of the information in the first clause. The other answer choices do not correctly combine the sentences and create grammatical errors.',
    'Review the passage and eliminate choices that contradict the text.',
    'The first edition of "The Complete Works of William Shakespeare" was published in 1623 and contained 36 plays, including "The Tempest," "Hamlet," and "Romeo and Juliet." The text is a compilation of all of Shakespeare’s plays, and it is considered to be the definitive source for his work.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_32b16a6b6433f151_english_00306',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a8","opensat_index":306}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice provides the best punctuation for the underlined portion in the sentence? ',
    'multiple_choice',
    '[{"id":"A","text":"album, with its introspective lyrics and infectious melodies","is_correct":true,"explanation":""},{"id":"B","text":"album; with its introspective lyrics and infectious melodies","is_correct":false,"explanation":""},{"id":"C","text":"album, with its introspective lyrics, and infectious melodies","is_correct":false,"explanation":""},{"id":"D","text":"album—with its introspective lyrics and infectious melodies","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The underlined portion is a nonrestrictive clause, which means that it could be removed without affecting the meaning of the sentence. Nonrestrictive clauses are set off with commas. Choice B is incorrect because semicolons are used to join two independent clauses. Choice C is incorrect because commas are not used to separate items in a series that is already punctuated with commas. Choice D is incorrect because em dashes are used to set off parenthetical information that is more important than the information around it.',
    'Review the passage and eliminate choices that contradict the text.',
    'In the late 1990s, the band The Wallflowers, fronted by Jakob Dylan, son of music legend Bob Dylan, gained significant popularity with the release of their debut album, *Bringing Down the Horse*. The album spawned three hit singles, "One Headlight," "6th Avenue Heartache," and "The Difference."  This album, with its introspective lyrics and infectious melodies, helped to define the sound of alternative rock.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '64236d4f_english_00307',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"64236d4f","opensat_index":307}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the word "erosion" is used to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of urgency and alarm about the decline of the middle class.","is_correct":false,"explanation":""},{"id":"B","text":"describe the gradual and irreversible nature of the decline of the middle class.","is_correct":true,"explanation":""},{"id":"C","text":"suggest that the decline of the middle class is a natural and inevitable process.","is_correct":false,"explanation":""},{"id":"D","text":"emphasize the importance of the author’s argument about the decline of the middle class.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The author uses the word "erosion" to describe the gradual and irreversible nature of the decline of the middle class. This suggests that the decline is a slow and steady process, and that it is likely to continue in the future.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author’s main argument is that the decline of the American middle class is a result of the increasing complexity of the modern economy. The author supports this argument by discussing a number of factors that have contributed to the decline of the middle class, such as the rise of automation, the globalization of the economy, and the decline of labor unions. The author also argues that the decline of the middle class has had a number of negative consequences, such as the erosion of social mobility and the increasing inequality between the rich and the poor.  What is the most likely reason why the writer uses the word "erosion"?',
    'passage',
    'reading_writing',
    'Expression of Ideas',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Expression of Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Expression of Ideas']::text[],
    'opensat_bada71bd4ddb7f2b_english_00308',
    'college_board_opensat',
    '{"opensat_domain":"Expression of Ideas","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"random_id_c5","opensat_index":308}'::jsonb
  ),
(
    gen_random_uuid(),
    'According to the passage, the primary purpose of irony in literature is to',
    'multiple_choice',
    '[{"id":"A","text":"entertain the reader with clever and unexpected twists.","is_correct":false,"explanation":""},{"id":"B","text":"create a sense of mystery and suspense.","is_correct":false,"explanation":""},{"id":"C","text":"provide social commentary and provoke thought.","is_correct":true,"explanation":""},{"id":"D","text":"highlight the author’s personal beliefs and opinions.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The passage states that irony is used to expose hypocrisy and absurdity and to invite the reader to consider alternative perspectives.  This indicates that irony is used as a tool for social commentary and to provoke thought.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author of the following passage discusses the use of irony in a particular type of literature. "Irony, in the hands of a skilled writer, can be a powerful tool for social commentary. It allows the writer to expose hypocrisy and absurdity, while also inviting the reader to consider alternative perspectives. The irony is often subtle and can be easily missed by the casual reader. It is, in fact, a hallmark of good literature to have the reader, through the use of irony, come to a deeper understanding of the text and the world it portrays." Based on the passage, what is the primary purpose of irony in literature?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    '495164c8_english_00309',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"495164c8","opensat_index":309}'::jsonb
  ),
(
    gen_random_uuid(),
    'This excerpt is mainly about',
    'multiple_choice',
    '[{"id":"A","text":"the significance of fashion in nineteenth-century American society.","is_correct":false,"explanation":""},{"id":"B","text":"the challenges of dressmaking in the nineteenth century.","is_correct":true,"explanation":""},{"id":"C","text":"the impact of fashion on the social status of nineteenth-century Americans.","is_correct":false,"explanation":""},{"id":"D","text":"the different ways in which nineteenth-century women expressed their individual tastes through fashion.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The excerpt describes the challenges and complexities involved in dressmaking in the nineteenth century. The author highlights the intricate nature of the work, the need for skill and precision, and the common practice of seeking professional help. While the excerpt touches upon social status and individual tastes, the focus is primarily on the challenges of the craft itself.',
    'Review the passage and eliminate choices that contradict the text.',
    'The following excerpt is from the preface to a book on nineteenth-century fashion: "The world of nineteenth-century textiles was a fascinating one, full of rich textures, bold patterns, and intricate designs. Women—and men—of the time, took great pride in their dress, often choosing fabrics and styles that reflected their social status, their individual tastes, or simply their desire for the most elaborate and eye-catching garments. However, in this complex and ever-changing world, the art of dressmaking itself was a difficult one, requiring great skill and precision. This is why many women sought the help of professional seamstresses, who would assist them in fashioning garments that would make them feel confident and elegant." Which choice best states the main idea of this excerpt?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '8364a72c_english_00310',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"8364a72c","opensat_index":310}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice correctly punctuates the following sentence:
"The most recent scientific research on the impact of climate change on coral reefs indicates that rising sea levels are leading to the destruction of reefs—in many locations the damage is severe."',
    'multiple_choice',
    '[{"id":"A","text":"\"The most recent scientific research on the impact of climate change on coral reefs indicates that rising sea levels are leading to the destruction of reefs, in many locations the damage is severe.\"","is_correct":false,"explanation":""},{"id":"B","text":"\"The most recent scientific research on the impact of climate change on coral reefs indicates that rising sea levels are leading to the destruction of reefs; in many locations the damage is severe.\"","is_correct":false,"explanation":""},{"id":"C","text":"\"The most recent scientific research on the impact of climate change on coral reefs indicates that rising sea levels are leading to the destruction of reefs, in many locations, the damage is severe.\"","is_correct":true,"explanation":""},{"id":"D","text":"\"The most recent scientific research on the impact of climate change on coral reefs indicates that rising sea levels are leading to the destruction of reefs—in many locations, the damage is severe.\"","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The comma after "reefs" is correct because it separates two independent clauses: the first clause is "The most recent scientific research on the impact of climate change on coral reefs indicates that rising sea levels are leading to the destruction of reefs" and the second is "in many locations, the damage is severe.". The second comma is needed because it sets off a nonessential phrase: "in many locations."',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_93eb8c7d3af68737_english_00311',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"random_id_a1","opensat_index":311}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author’s use of figurative language is most likely intended to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of immediacy and realism in the passage.","is_correct":false,"explanation":""},{"id":"B","text":"help the reader understand the author’s personal perspective.","is_correct":false,"explanation":""},{"id":"C","text":"evoke a more abstract and symbolic meaning in the passage.","is_correct":true,"explanation":""},{"id":"D","text":"highlight the importance of the speaker’s message.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The author uses figurative language to evoke a more abstract and symbolic meaning in the passage. Figurative language is a way of using words to create a more evocative and suggestive effect. In this case, the author uses a simile to compare the night sky to a canvas, which is a metaphor for the vastness of the universe. This comparison helps the reader to see the night sky in a new way and to appreciate its beauty and mystery. The author’s use of figurative language helps to create a more memorable and lasting impression on the reader''s mind.',
    'Review the passage and eliminate choices that contradict the text.',
    'The passage discusses how the author uses language to evoke a sense of place and time in the reader''s mind. The author uses specific details to paint a vivid picture of the setting, and the author uses sensory language to appeal to the reader''s senses. However, the author also uses figurative language to create a more abstract and symbolic effect. The author’s use of figurative language is evident in the following excerpt from the passage: "The sky was a canvas of deep blue, dotted with the silver stars."  The sentence uses a simile to compare the night sky to a canvas, which is a metaphor for the vastness of the universe. In this way, the author is able to create a sense of wonder and awe in the reader''s mind. Why does the author use figurative language?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '8a4d4672_english_00312',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"8a4d4672","opensat_index":312}'::jsonb
  ),
(
    gen_random_uuid(),
    'The phrase "despite the progress of technology" is used to',
    'multiple_choice',
    '[{"id":"A","text":"introduce a contradiction in the speaker’s belief system.","is_correct":false,"explanation":""},{"id":"B","text":"highlight the speaker’s lack of appreciation for technology.","is_correct":false,"explanation":""},{"id":"C","text":"emphasize the ongoing tension between tradition and modernity.","is_correct":true,"explanation":""},{"id":"D","text":"suggest that the elder’s perspective is outdated and irrelevant.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The phrase "despite the progress of technology" highlights the contrast between the speaker''s modern perspective and the elder''s traditional perspective. This contrast emphasizes the ongoing tension between tradition and modernity.',
    'Review the passage and eliminate choices that contradict the text.',
    'One of the central ideas of the passage is that despite the progress of technology, some people still hold onto traditional beliefs. The writer achieves this by contrasting the speaker’s modern perspective with the traditional perspective of the elder he is talking to. For example, the elder believes that the world is a place of wonder and mystery, while the speaker believes that the world is a place of logic and reason.  What is the most likely reason why the writer uses the phrase "despite the progress of technology"?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '45678910_english_00313',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"45678910","opensat_index":313}'::jsonb
  ),
(
    gen_random_uuid(),
    'The structural shift in the passage serves to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of suspense and anticipation for the reader.","is_correct":false,"explanation":""},{"id":"B","text":"contrast the character''s past and present experiences.","is_correct":true,"explanation":""},{"id":"C","text":"highlight the character''s flaws and weaknesses.","is_correct":false,"explanation":""},{"id":"D","text":"emphasize the character''s determination to succeed.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The passage''s structure is designed to highlight the contrast between the character''s past and present experiences.  The initial description of the character''s childhood and family life sets the stage for a comparison with their present-day life, revealing how they have changed and evolved.  This structural choice serves to create a more dynamic and engaging narrative.',
    'Review the passage and eliminate choices that contradict the text.',
    'The first paragraph of the passage introduces the main character, describing their childhood and family life. The second paragraph shifts focus to the character''s present-day life, highlighting their aspirations and challenges. The final paragraph provides a brief reflection on the character''s journey, suggesting the importance of embracing change. What is the effect of this structural shift?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '2321c54b_english_00314',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"2321c54b","opensat_index":314}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which sentence most clearly expresses the author''s central claim?',
    'multiple_choice',
    '[{"id":"A","text":"Mindfulness is a practice that involves focusing on the present moment and accepting thoughts and feelings without judgment.","is_correct":false,"explanation":""},{"id":"B","text":"When we practice mindfulness, we are training our brains to be more aware of our thoughts and feelings.","is_correct":false,"explanation":""},{"id":"C","text":"Practicing mindfulness can help to reduce the negative effects of stress on the brain.","is_correct":true,"explanation":""},{"id":"D","text":"The practice of mindfulness has been shown to have a number of benefits for both mental and physical health.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The author is making the claim that mindfulness is a practice that can have a positive effect on the brain. This claim is supported by the author''s discussion of how mindfulness can reduce the effects of stress.  Choice A is incorrect because it defines mindfulness, not states a claim about it. Choice B is incorrect because it describes a benefit of mindfulness, not a claim about its effects. Choice D is incorrect because it describes the benefits of mindfulness, but does not make a claim about its effect on the brain.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author''s central claim is that the practice of mindfulness can have a positive effect on the brain.  The author develops this claim by discussing the brain''s response to stress and how the practice of mindfulness can help to reduce the effects of stress.  This claim is supported by the author''s use of a personal anecdote about how mindfulness has helped them cope with stress.  Which sentence most clearly expresses the author''s central claim?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_c40a3d0f24f0f4a3_english_00315',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"random_id_e7","opensat_index":315}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author uses the word "awe" to',
    'multiple_choice',
    '[{"id":"A","text":"contrast the speaker’s current feelings with the reader’s.","is_correct":false,"explanation":""},{"id":"B","text":"emphasize the speaker’s perspective.","is_correct":false,"explanation":""},{"id":"C","text":"show how the speaker’s perspective has changed.","is_correct":false,"explanation":""},{"id":"D","text":"describe the speaker’s intense reaction to the natural world.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The author uses the word "awe" to convey the speaker''s intense reaction to the natural world. The use of the word "awe" suggests that the speaker is deeply moved by the beauty and power of nature. This helps the reader to connect with the speaker''s feelings.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author uses several methods to appeal to the reader’s emotions. The author uses vivid imagery, describing the sights and sounds of the natural world. The author also uses figurative language, such as metaphors and similes. The author’s use of these devices creates a sense of wonder and awe, and it helps the reader to connect with the speaker’s feelings. What is the most likely reason the author uses the word ''awe''?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '894f832a_english_00316',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"894f832a","opensat_index":316}'::jsonb
  ),
(
    gen_random_uuid(),
    'The passage suggests that',
    'multiple_choice',
    '[{"id":"A","text":"being yourself is the most important thing in life.","is_correct":false,"explanation":""},{"id":"B","text":"it is important to be considerate of others.","is_correct":true,"explanation":""},{"id":"C","text":"introverts should avoid social gatherings.","is_correct":false,"explanation":""},{"id":"D","text":"being true to yourself is essential for a healthy life.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The passage emphasizes the importance of being considerate of others as a key aspect of being yourself in a healthy way. The passage argues that "being yourself" shouldn''t come at the expense of others'' needs or feelings. Therefore, the primary message of the passage is that it is important to be considerate of others.',
    'Review the passage and eliminate choices that contradict the text.',
    'It is often said that the most important thing in life is to "be yourself." This advice is well-intentioned, but it can also be harmful. If one always tries to "be themselves" without regard for the context or the needs of others, they may come across as selfish or insensitive. It is important to recognize that being yourself in a healthy way means striking a balance between your own needs and the needs of those around you. The key is to be true to yourself while also being considerate and respectful of others. If, for example, you are an introvert who enjoys spending time alone, you don’t need to force yourself to attend every party or social gathering. However, it is also important to be mindful of your friends and family members who may enjoy these events and who may be disappointed if you are always unavailable. What, therefore, is the primary message of this passage?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_75b38d77b2b408a8_english_00317',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"random_id_c5","opensat_index":317}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice completes the text so that it conforms to the conventions of Standard English?',
    'multiple_choice',
    '[{"id":"A","text":"that involved","is_correct":false,"explanation":""},{"id":"B","text":"which involved","is_correct":true,"explanation":""},{"id":"C","text":"involving","is_correct":false,"explanation":""},{"id":"D","text":"involved","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The correct answer is B. The sentence requires a relative clause, which is a clause that modifies a noun.  Choice A is incorrect because a relative clause that begins with *that* should not be used to modify a noun that is the object of a preposition (in this case, the preposition *in*). Choice C is incorrect because a present participle phrase is generally used to modify a noun that is the subject of the sentence, not the object of a preposition.  Choice D is incorrect because it creates a fragment.  Choice B is correct because it creates a relative clause that modifies the noun *work*.',
    'Review the passage and eliminate choices that contradict the text.',
    'The scientist’s work, ______ the use of the new instrument, has been praised as a significant advance in the field of astrophysics.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'e12f48df_english_00318',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"e12f48df","opensat_index":318}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this excerpt, the author is suggesting that',
    'multiple_choice',
    '[{"id":"A","text":"we should avoid making assumptions about others’ experiences.","is_correct":false,"explanation":""},{"id":"B","text":"our personal experiences can influence our perception of the world.","is_correct":false,"explanation":""},{"id":"C","text":"we should strive to avoid bias in our understanding of the world.","is_correct":true,"explanation":""},{"id":"D","text":"we should recognize that our own experiences are not always reliable.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The author emphasizes the importance of recognizing our own biases and assumptions to create a more inclusive and equitable understanding of the world.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author writes, “We need to be mindful of the ways in which our own experiences can shape our perceptions and beliefs.  We are all susceptible to biases and assumptions, but by acknowledging these tendencies, we can strive to create more inclusive and equitable understanding.” What is the author’s main point in this passage?',
    'passage',
    'reading_writing',
    'Expression of Ideas',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Expression of Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Expression of Ideas']::text[],
    'opensat_f29ec57a694cf801_english_00319',
    'college_board_opensat',
    '{"opensat_domain":"Expression of Ideas","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"random_id_c6","opensat_index":319}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author of the passage most likely cites the study about jam sampling in order to',
    'multiple_choice',
    '[{"id":"A","text":"present evidence that supports the claim that people often choose badly.","is_correct":true,"explanation":""},{"id":"B","text":"highlight the importance of making good choices when presented with a variety of options.","is_correct":false,"explanation":""},{"id":"C","text":"introduce the idea that shoppers are more susceptible to making bad choices when they feel overwhelmed.","is_correct":false,"explanation":""},{"id":"D","text":"argue that shoppers are more likely to buy a product if they have a limited number of options to choose from.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The study about jam sampling provides evidence that supports the author''s claim that when we have too many choices, we often make bad choices. The author presents the study to show that shoppers are more likely to make poor choices in situations with more options. Therefore, the study supports the overall claim that we tend to choose poorly when we have too many choices.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author of the passage argues that "when we are free to choose, we often choose badly." The author supports this claim by citing a study in which shoppers were given a choice of either 6 or 24 jams to sample at a grocery store. Shoppers who had fewer options to choose from ended up buying more jam, while those who had more options to choose from bought less jam. According to the author, this study suggests that we tend to be more susceptible to making poor choices when we feel overwhelmed by choice.  Why does the author cite the study about jam sampling?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_19de65069b4cf528_english_00320',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_c1","opensat_index":320}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author’s precise and accurate language in this excerpt helps to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of mystery and intrigue.","is_correct":false,"explanation":""},{"id":"B","text":"explain the concept of “epistemic framing” in a clear and concise way.","is_correct":true,"explanation":""},{"id":"C","text":"persuade the reader to agree with the author’s point of view.","is_correct":false,"explanation":""},{"id":"D","text":"highlight the importance of the author’s own experiences.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The author''s use of precise language helps to explain the concept of “epistemic framing” in a clear and concise way, making it easier for the reader to understand.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author of this excerpt is explaining the concept of “epistemic framing,” which is used in philosophy to describe how people’s beliefs are shaped by their experiences. The author is careful to use the term “epistemic framing” in a precise and accurate way, and the author is also careful to avoid using any jargon that the reader might not understand. Which of the following choices best describes the effect of the author’s careful language in this excerpt?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_404ff1a2f87bba69_english_00321',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a8","opensat_index":321}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the author uses a comparison to',
    'multiple_choice',
    '[{"id":"A","text":"present the musician’s style in a more detailed and nuanced way.","is_correct":false,"explanation":""},{"id":"B","text":"suggest that the musician is similar to other musicians.","is_correct":false,"explanation":""},{"id":"C","text":"emphasize the musician’s unique talent.","is_correct":true,"explanation":""},{"id":"D","text":"create a contrast between the musician’s style and the music’s style.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The comparison between the musician’s talent and the music’s style is used to emphasize the musician’s unique talent by highlighting a particular quality that sets the musician apart from others.',
    'Review the passage and eliminate choices that contradict the text.',
    'The opening sentence of this excerpt establishes the author’s purpose. The author has two key objectives: to offer readers a glimpse into the life of a specific musician and to provide evidence of a particular quality that makes the musician unique. This is a common rhetorical strategy for writers who want to engage readers in a compelling narrative. The author first describes the music as a means of showcasing this quality. In a later sentence, the author elaborates on the musician’s unique quality by making a comparison. What is the most likely reason why the author uses a comparison?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '645fd11a_english_00322',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"645fd11a","opensat_index":322}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following revisions to the underlined portion of the passage would correct the error in sentence structure?',
    'multiple_choice',
    '[{"id":"A","text":"It discusses the development of the internet from its early stages to its current widespread use, explaining how the internet has transformed the world in several ways.","is_correct":true,"explanation":""},{"id":"B","text":"It explains how the internet has transformed the world in several ways, and it discusses the development of the internet from its early stages to its current widespread use.","is_correct":false,"explanation":""},{"id":"C","text":"It discusses the development of the internet from its early stages to its current widespread use, it explains how the internet has transformed the world in several ways.","is_correct":false,"explanation":""},{"id":"D","text":"It discusses the development of the internet from its early stages to its current widespread use; it explains how the internet has transformed the world in several ways.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The original sentence contains a comma splice, which is an error in sentence structure.  A comma splice occurs when two independent clauses are joined together with only a comma.  The correct way to correct a comma splice is to either use a semicolon, a conjunction, or to separate the clauses into two separate sentences. Choice A correctly corrects the comma splice by using a comma followed by a conjunction.',
    'Review the passage and eliminate choices that contradict the text.',
    'The following text is from an article about the early development of the internet. The text explores how the internet changed the way people communicate and access information.  It discusses the development of the internet from its early stages to its current widespread use.  It explains how the internet has transformed the world in several ways.  It emphasizes the importance of the internet as a tool for connecting people and sharing knowledge.  The text also discusses some of the challenges that the internet has faced, such as censorship and privacy concerns.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_1ae2bbcac794fe45_english_00323',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"random_id_b6","opensat_index":323}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following best describes the central idea of the passage?',
    'multiple_choice',
    '[{"id":"A","text":"The rapid advancement of AI has led to a variety of new applications, but the potential risks are also significant.","is_correct":true,"explanation":""},{"id":"B","text":"AI is being used to automate tasks that were once thought to be impossible for machines.","is_correct":false,"explanation":""},{"id":"C","text":"Experts are divided on whether AI will eventually surpass human intelligence.","is_correct":false,"explanation":""},{"id":"D","text":"The potential benefits of AI are significant, and it is important to think carefully about the potential consequences.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The passage discusses both the benefits and risks of AI, suggesting that while the technology has made great strides, we must be careful about its potential consequences. This is the central idea of the passage.',
    'Review the passage and eliminate choices that contradict the text.',
    'The development of artificial intelligence, or AI, has progressed quickly in recent decades. With the availability of large amounts of data and powerful computers, AI is being used to do a variety of tasks that were once thought to be impossible for machines. AI is now being used to automate tasks such as driving cars, translating languages, and writing articles. Some experts believe that AI will eventually surpass human intelligence, while others are more cautious. The potential benefits of AI are significant, but so are the risks.  It is important to think carefully about the potential consequences of AI before it becomes too powerful.',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_f9c3eb13cfb1d02b_english_00324',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a9","opensat_index":324}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;