INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'The second paragraph of this passage primarily functions to',
    'multiple_choice',
    '[{"id":"A","text":"show how Anya''s artistic vision is influenced by Tom''s encouragement.","is_correct":true,"explanation":""},{"id":"B","text":"compare Anya''s use of traditional techniques with her use of digital technology.","is_correct":false,"explanation":""},{"id":"C","text":"reveal how Anya''s paintings reflect her life experiences.","is_correct":false,"explanation":""},{"id":"D","text":"describe the relationship between Anya and Tom.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The second paragraph focuses on how Tom''s encouragement inspires Anya to explore new ideas and develop her artistic vision. This is the primary purpose of the paragraph.',
    'Review the passage and eliminate choices that contradict the text.',
    'The opening paragraph introduces the reader to the main character, a woman named  Anya. She is a passionate artist who is focused on painting portraits of women. She lives with her husband, Tom, who encourages her and helps her to develop her craft. Anya believes that the act of painting is a powerful expression of emotions.  The next paragraph reveals how Anya''s painting process is influenced by Tom. Tom''s encouragement helps Anya to explore new ideas and develop her artistic vision.  The third paragraph contrasts the two methods that Anya uses to create her paintings. Anya has discovered that she can create a sense of depth and realism by using a traditional, hands-on approach. However, she is also interested in exploring new techniques, such as using a digital tablet.   What is the purpose of the second paragraph in this passage?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '8a39f125_english_00775',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"8a39f125","opensat_index":775}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice provides the best way to combine the sentences, “This is a significant finding because it suggests that city residents may be at higher risk of developing certain health conditions, such as obesity, heart disease, and diabetes.” and “However, the study also found that people who live in cities tend to have access to more health care resources than those who live in rural areas.”?',
    'multiple_choice',
    '[{"id":"A","text":"This is a significant finding because it suggests that city residents may be at higher risk of developing certain health conditions, such as obesity, heart disease, and diabetes, however, the study also found that people who live in cities tend to have access to more health care resources than those who live in rural areas.","is_correct":false,"explanation":""},{"id":"B","text":"This is a significant finding because it suggests that city residents may be at higher risk of developing certain health conditions, such as obesity, heart disease, and diabetes; however, the study also found that people who live in cities tend to have access to more health care resources than those who live in rural areas.","is_correct":false,"explanation":""},{"id":"C","text":"This is a significant finding because it suggests that city residents may be at higher risk of developing certain health conditions, such as obesity, heart disease, and diabetes, but the study also found that people who live in cities tend to have access to more health care resources than those who live in rural areas.","is_correct":true,"explanation":""},{"id":"D","text":"This is a significant finding because it suggests that city residents may be at higher risk of developing certain health conditions, such as obesity, heart disease, and diabetes; and the study also found that people who live in cities tend to have access to more health care resources than those who live in rural areas.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The best way to combine these two sentences is by using a coordinating conjunction, “but,” which shows a contrast between the two ideas. The other choices result in comma splices or incorrect use of punctuation.',
    'Review the passage and eliminate choices that contradict the text.',
    'The study found that people who spend more time outside have a lower risk of developing certain health conditions. The study also found that, in general, people who live in urban areas spend less time outdoors than those who live in rural areas.  This is a significant finding because it suggests that city residents may be at higher risk of developing certain health conditions, such as obesity, heart disease, and diabetes. However, the study also found that people who live in cities tend to have access to more health care resources than those who live in rural areas. Therefore, it’s important to consider the availability of health care resources when evaluating the relationship between outdoor time and health.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_b480abff30e6dc3d_english_00776',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_c2","opensat_index":776}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice completes the text with the most logical and precise word or phrase?',
    'multiple_choice',
    '[{"id":"A","text":"demands","is_correct":false,"explanation":""},{"id":"B","text":"speculates","is_correct":true,"explanation":""},{"id":"C","text":"doubts","is_correct":false,"explanation":""},{"id":"D","text":"establishes","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Choice B is the best answer because it most logically completes the text’s discussion of Ochoa’s prediction that humans will one day need to live in places other than Earth. As used in this context, “speculates” would mean puts forward an idea without firm evidence. The text states that Ochoa “doesn’t have a definite idea” about when humans might need to live in other environments and characterizes Ochoa’s prediction as a “conjecture,” or a conclusion presented without convincing evidence. This context indicates that Ochoa speculates when she makes this prediction.

Choice A is incorrect because saying that Ochoa “demands,” or insists or requires, that humans will one day need to live in other environments than Earth’s would not make sense in context. The text indicates that she’s unsure about the timing but hypothesizes that it will someday happen. Choice C is incorrect because  saying that Ochoa “doubts,” or questions or disbelieves, that humans will one day need to live in other environments than Earth’s would not make sense in context. The text indicates that although Ochoa is unsure about the timing, she hypothesizes that humans will need to live in places other than Earth and encourages research into future travel to the moon. Choice D is incorrect because  saying that Ochoa “establishes,” or proves, that humans will one day need to live in other environments than Earth’s would not make sense in context. Rather than stating that Ochoa discusses her idea with certainty and supports it with evidence, the text indicates that Ochoa is unsure about when humans might need to live in other environments.',
    'Review the passage and eliminate choices that contradict the text.',
    'Former astronaut Ellen Ochoa says that although she doesn’t have a definite idea of when it might happen, she ______ that humans will someday need to be able to live in other environments than those found on Earth. This conjecture informs her interest in future research missions to the moon.',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '97ab5669_english_00777',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"97ab5669","opensat_index":777}'::jsonb
  ),
(
    gen_random_uuid(),
    'The semicolon in this sentence is used to',
    'multiple_choice',
    '[{"id":"A","text":"join two closely related independent clauses.","is_correct":true,"explanation":""},{"id":"B","text":"separate a dependent clause from an independent clause.","is_correct":false,"explanation":""},{"id":"C","text":"indicate that the writer is about to provide an example.","is_correct":false,"explanation":""},{"id":"D","text":"set off a nonessential phrase or clause.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The semicolon is used to join two closely related independent clauses.  The first independent clause states that the new fertilizer had a positive impact on farming practices.  The second independent clause explains that the new fertilizer could not be used to grow certain types of crops.  Both of these clauses are complete sentences, and they are closely related in meaning.  Therefore, the semicolon is the correct punctuation mark to use.',
    'Review the passage and eliminate choices that contradict the text.',
    'The scientist’s research on the effectiveness of a new type of fertilizer had a positive impact on agricultural practices.  Specifically, the new fertilizer helped farmers to increase crop yields and reduce the use of harmful pesticides.  Although the scientist’s research had a positive impact on farming practices, the scientist found that the new fertilizer could not be used to grow certain types of crops.  What is the most likely reason why the writer uses a semicolon in this sentence?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '82ab5679_english_00778',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"82ab5679","opensat_index":778}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author of this passage uses a metaphor to',
    'multiple_choice',
    '[{"id":"A","text":"provide a more vivid and engaging explanation of photosynthesis.","is_correct":true,"explanation":""},{"id":"B","text":"explain the scientific principles behind photosynthesis.","is_correct":false,"explanation":""},{"id":"C","text":"convince the reader that photosynthesis is an important process.","is_correct":false,"explanation":""},{"id":"D","text":"create a sense of mystery and intrigue around photosynthesis.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The author is using a metaphor to make the process of photosynthesis more vivid and engaging for the reader. This can help the reader to better understand and remember the process.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author of this passage is trying to explain the process of photosynthesis, which is how plants use sunlight, water, and carbon dioxide to make food.  The author describes this process as a series of steps, and then uses a metaphor to help the reader understand the importance of each step. The author concludes by explaining that the process of photosynthesis is essential for all life on Earth.  What is the most likely reason why the author uses a metaphor to explain photosynthesis?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_c222d916e6668c97_english_00779',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_c2","opensat_index":779}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author uses the metaphor of a “lonely, desolate place” to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of empathy for the speaker.","is_correct":false,"explanation":""},{"id":"B","text":"describe the speaker’s physical surroundings.","is_correct":false,"explanation":""},{"id":"C","text":"emphasize the speaker’s emotional state.","is_correct":true,"explanation":""},{"id":"D","text":"suggest that the speaker is in danger.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The metaphor of a “lonely, desolate place” is used to emphasize the speaker’s emotional state, which is characterized by grief and isolation.  The author is not simply describing the speaker’s surroundings; instead, the author is using the metaphor to create a powerful image of the speaker’s internal feelings.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author uses several rhetorical devices to create a powerful and memorable image of the speaker’s grief in the passage.  For instance, the author uses vivid imagery to describe the speaker’s tears as “falling like rain” and emphasizes the speaker’s sense of isolation by comparing the speaker’s feelings to “a lonely, desolate place.”  What is the author’s purpose in using the metaphor of a “lonely, desolate place” to describe the speaker’s grief?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_d7cbd38959c591c9_english_00780',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_e1","opensat_index":780}'::jsonb
  ),
(
    gen_random_uuid(),
    'The word "wonder" at the end of the passage is used to ',
    'multiple_choice',
    '[{"id":"A","text":"highlight the speaker’s curiosity.","is_correct":false,"explanation":""},{"id":"B","text":"emphasize the speaker’s joy.","is_correct":false,"explanation":""},{"id":"C","text":"create a sense of mystery.","is_correct":false,"explanation":""},{"id":"D","text":"suggest that the speaker is reflecting on the passage.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The word "wonder" at the end of the passage suggests that the speaker is reflecting on the passage, considering its meaning and implications. It creates a sense of contemplation and wonder, which is reinforced by the shift in tone throughout the passage.',
    'Review the passage and eliminate choices that contradict the text.',
    'The text begins with a vivid description of the natural world and how the narrator is feeling. As the narrator continues to describe the natural world, there is a shift in the tone of the passage. The descriptions become more reflective and contemplative. This shift in tone is reinforced by the use of the word "wonder" at the end of the passage. What is the most likely reason why the writer uses the word "wonder"?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'b7a981b2_english_00781',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"b7a981b2","opensat_index":781}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the speaker is most likely trying to',
    'multiple_choice',
    '[{"id":"A","text":"explain the process of change and how it can be achieved.","is_correct":false,"explanation":""},{"id":"B","text":"suggest that waiting for change is not a viable option.","is_correct":false,"explanation":""},{"id":"C","text":"critique those who are waiting for change.","is_correct":false,"explanation":""},{"id":"D","text":"advocate for a specific approach to making change.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The speaker is advocating for a specific approach to making change.  The speaker contrasts the idea of “waiting” for change with the idea of “making” change, suggesting that making change is a more active and effective approach.  The speaker’s use of strong verbs and figurative language further emphasizes the speaker’s belief that taking action is the best way to achieve change.',
    'Review the passage and eliminate choices that contradict the text.',
    'The speaker emphasizes the importance of taking action by contrasting the idea of “waiting” for change with the idea of “making” change.  The speaker uses strong verbs, such as “wait,” “make,” “stand,” and “demand,” to contrast the two approaches to change. The speaker also uses figurative language such as “waiting for the world to change” and “stand and demand” to make the contrast more vivid. What is the speaker’s main purpose in this passage?',
    'passage',
    'reading_writing',
    'Expression of Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Expression of Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Expression of Ideas']::text[],
    'opensat_07587ff48f150d5d_english_00782',
    'college_board_opensat',
    '{"opensat_domain":"Expression of Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a2","opensat_index":782}'::jsonb
  ),
(
    gen_random_uuid(),
    'The use of the word "whereas" in this passage is most likely intended to',
    'multiple_choice',
    '[{"id":"A","text":"provide the reader with a contrast between two ideas.","is_correct":true,"explanation":""},{"id":"B","text":"give an example of a common type of word relationship.","is_correct":false,"explanation":""},{"id":"C","text":"explain the origin of the English language.","is_correct":false,"explanation":""},{"id":"D","text":"describe the process of learning new vocabulary.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The word "whereas" is used to introduce a contrast between two ideas: the meanings of synonyms and the meanings of antonyms.  This contrast helps the reader to understand the different ways that words can be related to each other.',
    'Review the passage and eliminate choices that contradict the text.',
    'The study of the history of the English language, a subject that many people find challenging, requires an understanding of the relationships between words.  Words with similar meanings are called synonyms, whereas words with opposite meanings are called antonyms.  Some words, like the words "happy" and "sad," have very distinct meanings, while others, like the words "big" and "large," have very similar meanings.  What is the most likely reason why the writer uses the word "whereas"?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_034cba7942cf8fd4_english_00783',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_e4","opensat_index":783}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best combines the sentences at the underlined portion to create a grammatically correct and stylistically effective sentence? ',
    'multiple_choice',
    '[{"id":"A","text":"Each sculpture was made with a unique combination of materials, and using a variety of techniques, the artist wanted each piece to convey a sense of unity and harmony.","is_correct":false,"explanation":""},{"id":"B","text":"Each sculpture was made with a unique combination of materials, using a variety of techniques, the artist wanted each piece to convey a sense of unity and harmony.","is_correct":false,"explanation":""},{"id":"C","text":"Each sculpture was made with a unique combination of materials, using a variety of techniques, the artist wanted to convey a sense of unity and harmony in each piece.","is_correct":false,"explanation":""},{"id":"D","text":"Each sculpture was made with a unique combination of materials, and the artist wanted to convey a sense of unity and harmony in each piece.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Choice D is the best option because it combines the two sentences smoothly and correctly using a comma and a conjunction.  Choice A uses incorrect punctuation.  Choice B is grammatically correct but stylistically awkward.  Choice C is grammatically correct but creates an unnecessary repetition of "each piece."',
    'Review the passage and eliminate choices that contradict the text.',
    'The artist spent months researching and creating a series of intricate sculptures that reflected the beauty and complexity of nature.  Each sculpture was made with a unique combination of materials, and the artist used a variety of techniques.  In the end, however,  the artist wanted each piece to convey a sense of unity and harmony.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '3c77395d_english_00784',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"3c77395d","opensat_index":784}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author uses the sentence “the first time I saw the ocean, it was an entirely different experience than I expected” to',
    'multiple_choice',
    '[{"id":"A","text":"provide a clear and concise summary of the main idea of the passage.","is_correct":false,"explanation":""},{"id":"B","text":"establish a contrast between the speaker’s expectations and reality.","is_correct":true,"explanation":""},{"id":"C","text":"introduce a new idea that will be explored in the following sentences.","is_correct":false,"explanation":""},{"id":"D","text":"create a sense of intrigue and suspense for the reader.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The sentence introduces a contrast between the speaker’s expectations of the ocean and their actual experience, setting up a comparison that will likely be explored in the rest of the paragraph.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author states that “the first time I saw the ocean, it was an entirely different experience than I expected.” What is the most likely reason why the author uses this sentence to begin the paragraph?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_58ecb8ff05736d1c_english_00785',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"random_id_1","opensat_index":785}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best combines the sentences at the underlined portion to create a grammatically correct and stylistically effective sentence?',
    'multiple_choice',
    '[{"id":"A","text":"Tubman’s courage and determination are an inspiration to us all: she demonstrated that with hard work and dedication, we can overcome any obstacle.","is_correct":false,"explanation":""},{"id":"B","text":"Tubman’s courage and determination are an inspiration to us all; she demonstrated that with hard work and dedication, we can overcome any obstacle.","is_correct":false,"explanation":""},{"id":"C","text":"Tubman’s courage and determination are an inspiration to us all; she demonstrated that with hard work and dedication, we can overcome any obstacle.","is_correct":false,"explanation":""},{"id":"D","text":"Tubman’s courage and determination are an inspiration to us all, she demonstrated that with hard work and dedication, we can overcome any obstacle.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The correct answer is D. It creates a complex sentence with a comma to separate the two independent clauses. This creates a smoother flow of the sentence than a colon, a semicolon, or a dash would.',
    'Review the passage and eliminate choices that contradict the text.',
    'The history of the United States is full of remarkable stories of people who have overcome difficult challenges to achieve great things. One such story is that of Harriet Tubman, who escaped slavery and then risked her life to help others escape. Tubman’s courage and determination are an inspiration to us all. She demonstrated that with hard work and dedication, we can overcome any obstacle.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_3c0f9cce5c81b72d_english_00786',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a1","opensat_index":786}'::jsonb
  ),
(
    gen_random_uuid(),
    'The writer uses the analogy of a piece of art most likely to',
    'multiple_choice',
    '[{"id":"A","text":"explain a complex concept in a way that is easy to understand.","is_correct":true,"explanation":""},{"id":"B","text":"describe the speaker’s personal experiences with art.","is_correct":false,"explanation":""},{"id":"C","text":"convince the reader that literary merit is important.","is_correct":false,"explanation":""},{"id":"D","text":"create a sense of beauty and elegance in the passage.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The writer is using the analogy of art to make the abstract concept of "literary merit" more concrete and understandable for the reader.',
    'Review the passage and eliminate choices that contradict the text.',
    'The writer is trying to explain the concept of "literary merit." To do this, the writer uses the analogy of a piece of art. The goal is to communicate that, like a piece of art, a piece of literature can be appreciated for its beauty, its craftsmanship, and its power to move the reader.  The writer begins by saying that "literary merit" is not something that can be objectively measured. What is the most likely reason that the writer uses the analogy of a piece of art?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_a8b8844b9ad1f3f9_english_00787',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"random_id_c5","opensat_index":787}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice completes the text so that it conforms to the conventions of Standard English?',
    'multiple_choice',
    '[{"id":"A","text":"want","is_correct":true,"explanation":""},{"id":"B","text":"wanted","is_correct":false,"explanation":""},{"id":"C","text":"wanting","is_correct":false,"explanation":""},{"id":"D","text":"to want","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The verb "want" is the correct choice because it agrees in number with the singular subject "viewers." The other choices are incorrect because they do not agree in number with the subject. "Wanted" is the past tense of "want" and is not appropriate in this context. "Wanting" is a present participle, which cannot stand alone as a verb. "To want" is an infinitive, which can be used as a noun or adjective, but not as a verb in this context.',
    'Review the passage and eliminate choices that contradict the text.',
    'The artist’s unique style, using bold colors and expressive brushstrokes, was immediately recognizable. It was something that made viewers ______ to look at her paintings for hours.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '8d99f348_english_00788',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"8d99f348","opensat_index":788}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice provides the best way to combine the two sentences at the end of the passage so that they are grammatically correct and the meaning is preserved? ',
    'multiple_choice',
    '[{"id":"A","text":"The scrapbook is a detailed account of Alspaugh’s life, and it’s a rich historical record of nineteenth-century textile and dressmaking.","is_correct":true,"explanation":""},{"id":"B","text":"The scrapbook is a detailed account of Alspaugh’s life, and it also a rich historical record of nineteenth-century textile and dressmaking.","is_correct":false,"explanation":""},{"id":"C","text":"The scrapbook, a detailed account of Alspaugh’s life, is also a rich historical record of nineteenth-century textile and dressmaking.","is_correct":false,"explanation":""},{"id":"D","text":"The scrapbook is a detailed account of Alspaugh’s life, a rich historical record of nineteenth-century textile and dressmaking.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The most effective way to combine the two sentences is to use a comma and a coordinating conjunction, such as "and." This choice accurately reflects the structure of the original two sentences and maintains their meaning. ',
    'Review the passage and eliminate choices that contradict the text.',
    'In the late 19th century, many women in the United States began to collect fabric scraps in scrapbooks, documenting their lives through these materials as well as historical shifts in textile and clothing styles. While these scrapbooks were once considered a popular hobby,  the scrapbook Hannah Ditzler Alspaugh created in the 1870s, is an especially meticulous one. Along with each piece of fabric, Alspaugh included detailed descriptions of how she acquired and used the fabric, and she even noted the price she paid for each one. Historians consider Alspaugh’s scrapbook to be a detailed account of her life and a rich historical record of nineteenth-century textile and dressmaking.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '1a966f88_english_00789',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"1a966f88","opensat_index":789}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice completes the text so that it conforms to the conventions of Standard English?',
    'multiple_choice',
    '[{"id":"A","text":"encouraged","is_correct":true,"explanation":""},{"id":"B","text":"encouraging","is_correct":false,"explanation":""},{"id":"C","text":"was encouraging","is_correct":false,"explanation":""},{"id":"D","text":"had encouraged","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The sentence requires a finite verb to perform the action of the subject, "director." The correct choice is "encouraged" because it is a past tense finite verb that accurately indicates the time frame of the action.',
    'Review the passage and eliminate choices that contradict the text.',
    'The director of the play, who is known for his innovative and often controversial staging choices,  the actors to experiment with a new style of movement that incorporates elements of contemporary dance.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_e738ba0b37f8ad90_english_00790',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_e3","opensat_index":790}'::jsonb
  ),
(
    gen_random_uuid(),
    'The phrase "the very air grew darker" is used to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of mystery and intrigue.","is_correct":true,"explanation":""},{"id":"B","text":"emphasize the speaker’s sense of fear and isolation.","is_correct":false,"explanation":""},{"id":"C","text":"provide a physical description of the setting.","is_correct":false,"explanation":""},{"id":"D","text":"highlight the contrast between light and darkness.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The phrase "the very air grew darker" creates a sense of mystery and intrigue. The darkness suggests that something is hidden or unknown, and the word "very" intensifies this feeling. This creates a sense of suspense, which is an important element of the passage.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author uses the phrase "the very air grew darker" to convey a sense of growing tension and uncertainty. This contributes to the overall mood of the passage, which is one of suspense. The author uses a variety of techniques to create this mood, including vivid imagery, sensory details, and foreshadowing. The author’s use of this phrase to create suspense is an example of how literary techniques can be used to create a particular mood in a story.',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '22e46f75_english_00791',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"22e46f75","opensat_index":791}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this text, the author focuses on ',
    'multiple_choice',
    '[{"id":"A","text":"the process of creating art.","is_correct":false,"explanation":""},{"id":"B","text":"the history of a particular art form.","is_correct":false,"explanation":""},{"id":"C","text":"the materials that are used in art.","is_correct":false,"explanation":""},{"id":"D","text":"the evolution of a particular artistic technique.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The text focuses on the development of a specific artistic technique over time. It highlights the changing materials and methods used, which demonstrates the evolution of the technique.',
    'Review the passage and eliminate choices that contradict the text.',
    'The main purpose of the text is to explain how an artistic technique developed over time.  The author traces the history of how this technique was first developed and its evolution in the years since.  The author focuses on the materials that were used in the past and the materials that are currently used in the art form.  What does the text emphasize?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '2c20a342_english_00792',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"2c20a342","opensat_index":792}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice completes the sentence so that it conforms to the conventions of Standard English?',
    'multiple_choice',
    '[{"id":"A","text":"To understand nature, you must open your eyes to its details. ","is_correct":true,"explanation":""},{"id":"B","text":"To understand nature, you must open your eyes to its details; ","is_correct":false,"explanation":""},{"id":"C","text":"To understand nature, you must open your eyes to its details, ","is_correct":false,"explanation":""},{"id":"D","text":"To understand nature, you must open your eyes to its details— ","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Choice A is the best answer. The convention being tested is punctuation between a preposition and its complement. No punctuation is needed between the preposition "to" and its complement, the noun phrase "open your eyes to its details."',
    'Review the passage and eliminate choices that contradict the text.',
    'The author is trying to convey the message that the best way to understand nature is to look at it from a personal perspective. The author is also trying to persuade the reader to pay attention to the natural world and to appreciate its beauty. The author uses the word “you” to make the passage more personal and to engage the reader.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '89f131a2_english_00793',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"89f131a2","opensat_index":793}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which statement best describes the main idea of the poem?',
    'multiple_choice',
    '[{"id":"A","text":"The poet describes the beauty of nature and how it can be both inspiring and comforting.","is_correct":false,"explanation":""},{"id":"B","text":"The poet uses a cyclical pattern of events to show how life is constantly changing.","is_correct":true,"explanation":""},{"id":"C","text":"The poet suggests that the changes in nature are a reflection of the poet''s own personal journey.","is_correct":false,"explanation":""},{"id":"D","text":"The poet suggests that winter is a time of great sadness and loss.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The poem’s main idea is that life is constantly changing, just like the seasons of the year. The poet uses the changing seasons as a metaphor for the changes that happen in life, and the poem’s structure reflects this cyclical pattern. The poem begins with a description of a beautiful spring day, when everything is new and full of life. As the poem progresses, the seasons change, and the poet describes the beauty of summer and the sadness of autumn. Finally, the poem ends with a description of a cold, bleak winter day. This use of natural imagery helps to reinforce the poem’s central theme.',
    'Review the passage and eliminate choices that contradict the text.',
    'The poet writes about the changing seasons of the year, and how they reflect the changes that happen in life. The poem begins with a description of a beautiful spring day, when everything is new and full of life. As the poem progresses, the seasons change, and the poet describes the beauty of summer and the sadness of autumn. Finally, the poem ends with a description of a cold, bleak winter day. This use of natural imagery helps to reinforce the poem’s central theme.',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    '8097b20d_english_00794',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"8097b20d","opensat_index":794}'::jsonb
  ),
(
    gen_random_uuid(),
    'According to the passage, the Black Arts Movement believed that art should:',
    'multiple_choice',
    '[{"id":"A","text":"be accessible to a wide audience.","is_correct":false,"explanation":""},{"id":"B","text":"reflect the beauty and wonder of the natural world.","is_correct":false,"explanation":""},{"id":"C","text":"be a catalyst for social change.","is_correct":true,"explanation":""},{"id":"D","text":"preserve traditional artistic techniques.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The passage states that the Black Arts Movement believed art should be “socially and politically engaged,” using their work to “address issues of race, poverty, and injustice” and “serve as a powerful tool for social change.”',
    'Review the passage and eliminate choices that contradict the text.',
    'In the 1960s, the Black Arts Movement called for art to be more than just aesthetically pleasing; it should also be socially and politically engaged. Artists began to use their work to address issues of race, poverty, and injustice, and to challenge the dominant narratives of the time. Their art served as a powerful tool for social change, prompting dialogue and inspiring action.',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_00f80a0e309fd55d_english_00795',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_c7","opensat_index":795}'::jsonb
  ),
(
    gen_random_uuid(),
    'The essay argues that social media has transformed how people communicate, leading to a shift in the way people',
    'multiple_choice',
    '[{"id":"A","text":"express their beliefs and values.","is_correct":true,"explanation":""},{"id":"B","text":"engage in debate.","is_correct":false,"explanation":""},{"id":"C","text":"share their opinions.","is_correct":false,"explanation":""},{"id":"D","text":"communicate with each other.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The essay argues that social media has led to a shift in the way people communicate, specifically by making people more likely to make pronouncements about their beliefs and values rather than engaging in dialogue. Thus, the central claim of the essay is that social media has transformed how people express their beliefs and values.',
    'Review the passage and eliminate choices that contradict the text.',
    'The essay argues that the rise of social media has fundamentally changed the way people communicate with each other.  One of the most significant changes, the essay argues, is that people have become more likely to make pronouncements about their beliefs and values rather than engaging in dialogue.  The essay concludes by suggesting that social media is no longer an environment for exchanging ideas but rather a battleground for defending one’s own perspective.  Which of the following best describes the central claim made by the essay?',
    'passage',
    'reading_writing',
    'Expression of Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Expression of Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Expression of Ideas']::text[],
    '8d66548c_english_00796',
    'college_board_opensat',
    '{"opensat_domain":"Expression of Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"8d66548c","opensat_index":796}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the author introduces an alternative approach to',
    'multiple_choice',
    '[{"id":"A","text":"describe the flaws in the main approach.","is_correct":false,"explanation":""},{"id":"B","text":"compare the advantages and disadvantages of both approaches.","is_correct":false,"explanation":""},{"id":"C","text":"emphasize the complexity of the main approach.","is_correct":false,"explanation":""},{"id":"D","text":"suggest that the main approach is not the only one.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The author mentions another approach to highlight that the main approach is not the only way to achieve the desired outcome. By mentioning an alternative approach, the author emphasizes that there are other possibilities and that the reader should not limit themselves to only one way of thinking.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author is not stating that this method of creating art is bad or that it’s not worth pursuing. However, the author is suggesting that there are other ways to achieve the same outcome that might be considered more effective or desirable. What is the most likely reason why the writer uses a sentence that focuses on an alternative approach?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'a444088e_english_00797',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"a444088e","opensat_index":797}'::jsonb
  ),
(
    gen_random_uuid(),
    'The sentence "The cat sat on the mat, watching the birds." is grammatically correct, but it lacks a clear subject. Which of the following is the BEST way to rewrite the sentence to include a clear subject? ',
    'multiple_choice',
    '[{"id":"A","text":"As the cat sat on the mat, watching the birds.","is_correct":false,"explanation":""},{"id":"B","text":"The cat, sitting on the mat, watched the birds.","is_correct":true,"explanation":""},{"id":"C","text":"While watching the birds, the cat sat on the mat.","is_correct":false,"explanation":""},{"id":"D","text":"The cat, it sat on the mat, watching the birds.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Choice B is the best option because it adds a clear subject to the sentence while maintaining the original meaning. The phrase "sitting on the mat" modifies the subject "The cat." Choice A creates a dependent clause and doesn''t have a clear subject. Choice C also creates a dependent clause and doesn''t have a clear subject. Choice D is redundant and unnecessary. The pronoun "it" is unnecessary, and it creates an awkward sentence structure.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '6288a321_english_00798',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"6288a321","opensat_index":798}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following sentences demonstrates the correct use of the word "affect"?',
    'multiple_choice',
    '[{"id":"A","text":"The heat did not effect the plants, and they continued to grow.","is_correct":false,"explanation":""},{"id":"B","text":"The heat did not affect the plants, and they continued to grow.","is_correct":true,"explanation":""},{"id":"C","text":"The heat did not affect the plants, and they continued to grow.","is_correct":false,"explanation":""},{"id":"D","text":"The heat did not affect the plants, and they continued to grow.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The sentence demonstrates the correct use of the word "affect" because it describes an action (the heat producing a change in the plants).',
    'Review the passage and eliminate choices that contradict the text.',
    'The most common spelling error for the word "affect" is "effect." This can be confusing because "effect" is a noun, while "affect" is a verb.  In this case, the writer is describing an action, so the correct spelling is "affect."   While the two words sound similar, they have distinct meanings and grammatical uses. When referring to something that causes a change, you should use "effect."  However, when describing something that produces a change, you should use "affect." Which of the following sentences demonstrates the correct use of the word "affect"?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '6758427d_english_00799',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"6758427d","opensat_index":799}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;