INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'The function $f(x) = 2x^2 + 3x - 5$ is defined for all real numbers $x$. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-15","is_correct":false,"explanation":""},{"id":"B","text":"-9","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"11","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substituting -2 for $x$ into the function, we get:  $f(-2) = 2(-2)^2 + 3(-2) - 5$. Simplifying, we have $f(-2) = 8 - 6 - 5 = 11$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_4f41c727b13d527f_math_00382',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c9","opensat_index":382}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with center O has a radius of 5.  A chord AB of the circle is 8 units long.  What is the distance from the center O to chord AB?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Draw a radius from O to point A and a radius from O to point B.  Draw a segment from O perpendicular to AB, and let the point of intersection of the segment and AB be point C.  Triangle AOC is a right triangle with hypotenuse OA = 5 and AC = 4.  By the Pythagorean Theorem,  OC = \sqrt{5^2-4^2} = \sqrt{9} = 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_0fb13ab167efcc39_math_00383',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a1","opensat_index":383}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store is having a sale on all items.  The price of a shirt is reduced from $\$25 to $\$15. What is the percent decrease in the price of the shirt?',
    'multiple_choice',
    '[{"id":"A","text":"10%","is_correct":false,"explanation":""},{"id":"B","text":"20%","is_correct":false,"explanation":""},{"id":"C","text":"30%","is_correct":false,"explanation":""},{"id":"D","text":"40%","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The price decrease is $25 - $15 = $10.  The percent decrease is the price decrease divided by the original price, multiplied by 100%:  $\frac{10}{25} \times 100% = 40%$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_8b2aea99733efc20_math_00384',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c1","opensat_index":384}'::jsonb
  ),
(
    gen_random_uuid(),
    'The vertices of a triangle are located at the points $(0,0)$, $(4,0)$, and $(0,3)$. What is the area of the triangle?',
    'multiple_choice',
    '[{"id":"A","text":"6","is_correct":true,"explanation":""},{"id":"B","text":"12","is_correct":false,"explanation":""},{"id":"C","text":"18","is_correct":false,"explanation":""},{"id":"D","text":"24","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The triangle is a right triangle with a base of 4 units and a height of 3 units. The area of a triangle is given by (1/2) * base * height, so the area of this triangle is (1/2) * 4 * 3 = 6 square units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_5fd132af14493deb_math_00385',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a2","opensat_index":385}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = 3x^2 + 5x - 2$ is defined for all real numbers. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-12","is_correct":false,"explanation":""},{"id":"B","text":"-4","is_correct":false,"explanation":""},{"id":"C","text":"8","is_correct":true,"explanation":""},{"id":"D","text":"16","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Substituting $-2$ for $x$ in the function $f(x) = 3x^2 + 5x - 2$ yields  $f(-2) = 3(-2)^2 + 5(-2) - 2$ = 12 - 10 - 2 = 8.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '949c662a_math_00386',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"949c662a","opensat_index":386}'::jsonb
  ),
(
    gen_random_uuid(),
    'The graph of the function \(f(x) = x^2 + 2x - 3\) intersects the x-axis at two points. What are the coordinates of these points of intersection?',
    'multiple_choice',
    '[{"id":"A","text":"(1, 0) and (-3, 0)","is_correct":true,"explanation":""},{"id":"B","text":"(-1, 0) and (3, 0)","is_correct":false,"explanation":""},{"id":"C","text":"(2, 0) and (-1, 0)","is_correct":false,"explanation":""},{"id":"D","text":"(-2, 0) and (1, 0)","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The x-intercepts of a function occur where the graph intersects the x-axis, meaning when y = 0. So, we need to solve the equation \(0 = x^2 + 2x - 3\). Factoring the quadratic, we get \(0 = (x+3)(x-1)\), which means \(x = -3\) or \(x = 1\).  Since the y-coordinate at the x-intercept is always 0, the points of intersection are (1, 0) and (-3, 0).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '8436f365_math_00387',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"8436f365","opensat_index":387}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = \sqrt{x} - 4$. For what value of $x$ does $f(x) = 9$?',
    'multiple_choice',
    '[{"id":"A","text":"13","is_correct":false,"explanation":""},{"id":"B","text":"81","is_correct":false,"explanation":""},{"id":"C","text":"169","is_correct":true,"explanation":""},{"id":"D","text":"289","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for $x$, we set the function equal to 9: $\sqrt{x} - 4 = 9$. Adding 4 to both sides gives us $\sqrt{x} = 13$. Squaring both sides, we get $x = 13^2$, or $x = 169$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_e03452986a76eb94_math_00388',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_5","opensat_index":388}'::jsonb
  ),
(
    gen_random_uuid(),
    'In the $xy$-plane, a circle with center $(2,-3)$ is tangent to the line $y = 5$. What is the radius of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"5","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The radius of the circle is the perpendicular distance from the center of the circle to the tangent line.  Since the center of the circle is $(2,-3)$ and the tangent line is $y=5$, the radius is the difference between the y-coordinate of the center and the y-coordinate of the line, which is $5 - (-3) = 8$.  Therefore, the radius of the circle is 8.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '8976e141_math_00389',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"8976e141","opensat_index":389}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 centimeters. What is the circumference of the circle, in centimeters? (Express your answer in terms of $\pi$.)',
    'multiple_choice',
    '[{"id":"A","text":"$\\pi$","is_correct":false,"explanation":""},{"id":"B","text":"$5\\pi$","is_correct":false,"explanation":""},{"id":"C","text":"$10\\pi$","is_correct":true,"explanation":""},{"id":"D","text":"$25\\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius of the circle.  Substituting 5 for $r$, we get $C = 2\pi(5) = 10\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '34652f15_math_00390',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"34652f15","opensat_index":390}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x + y = 5$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Adding the two equations together, we get $(x + y) + (x - y) = 5 + 1$, which simplifies to $2x = 6$. Dividing both sides by 2, we find that $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_925e128c22ca8702_math_00391',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_a2","opensat_index":391}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 2x - 8 = 0$, what is the sum of the solutions to this equation?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"0","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The sum of the solutions to the quadratic equation $ax^2 + bx + c = 0$ is given by $-b/a$.  Factoring the given quadratic equation yields $(x - 4)(x + 2) = 0$. Therefore, the solutions to the equation are $x = 4$ and $x = -2$.  The sum of these solutions is $4 + (-2) = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_84b8b060145fb8ed_math_00392',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c4","opensat_index":392}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units.  What is the area of the circle, in square units?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":true,"explanation":""},{"id":"D","text":"100\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula $A = \pi r^2$, where r is the radius of the circle.  Substituting r = 5 into the formula gives $A = \pi (5)^2 = 25\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_e95b8254796dfc0f_math_00393',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a4","opensat_index":393}'::jsonb
  ),
(
    gen_random_uuid(),
    'A regular hexagon is inscribed in a circle with radius 10. What is the perimeter of the hexagon?',
    'multiple_choice',
    '[{"id":"A","text":"30","is_correct":false,"explanation":""},{"id":"B","text":"60","is_correct":true,"explanation":""},{"id":"C","text":"60\\sqrt{3}","is_correct":false,"explanation":""},{"id":"D","text":"120\\sqrt{3}","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A regular hexagon can be divided into 6 equilateral triangles.  The side length of each equilateral triangle is equal to the radius of the circle, which is 10.  Thus, the perimeter of the hexagon is 6 * 10 = 60.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'e9ff8933_math_00394',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"e9ff8933","opensat_index":394}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people like apples, 40 people like oranges, and 20 people like both apples and oranges. How many people like only oranges?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":true,"explanation":""},{"id":"B","text":"20","is_correct":false,"explanation":""},{"id":"C","text":"30","is_correct":false,"explanation":""},{"id":"D","text":"40","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can use a Venn diagram to visualize the information. Since 20 people like both apples and oranges, 60 - 20 = 40 people like only apples and 40 - 20 = 20 people like only oranges.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_9eb79a3c55a9fec2_math_00395',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_b8","opensat_index":395}'::jsonb
  ),
(
    gen_random_uuid(),
    'The area of a circle is 36$\pi$ square meters.  What is the circumference of the circle, in meters?',
    'multiple_choice',
    '[{"id":"A","text":"6$\\pi$","is_correct":false,"explanation":""},{"id":"B","text":"12$\\pi$","is_correct":true,"explanation":""},{"id":"C","text":"18$\\pi$","is_correct":false,"explanation":""},{"id":"D","text":"36$\\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The area of a circle is given by $A = \pi r^2$, where $r$ is the radius of the circle.  We are given that the area is 36$\pi$ square meters, so $36\pi = \pi r^2$. Dividing both sides by $\pi$ gives $36 = r^2$. Taking the square root of both sides gives $r = 6$. The circumference of a circle is given by $C = 2\pi r$. Substituting 6 for $r$ gives $C = 2\pi(6) = 12\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_cfe0cfbdbe66a4f6_math_00396',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_e9","opensat_index":396}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells apples for $1.25 each and oranges for $0.75 each.  A customer buys 3 apples and 5 oranges. What is the total cost, in dollars, of the customer''s purchase?',
    'multiple_choice',
    '[{"id":"A","text":"6.25","is_correct":false,"explanation":""},{"id":"B","text":"7.50","is_correct":false,"explanation":""},{"id":"C","text":"8.75","is_correct":false,"explanation":""},{"id":"D","text":"9.25","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The cost of the apples is 3 * $1.25 = $3.75.  The cost of the oranges is 5 * $0.75 = $3.75.  The total cost is $3.75 + $3.75 = $7.50.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_8fb395309980a38c_math_00397',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_1","opensat_index":397}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 2x + 1 = 0$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":true,"explanation":""},{"id":"B","text":"0","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"2","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The expression on the left side of the equation is a perfect square trinomial: $(x + 1)^2$.  Taking the square root of both sides, we get $x + 1 = 0$.  Subtracting 1 from both sides gives us $x = -1$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'f4a9fd2e_math_00398',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"f4a9fd2e","opensat_index":398}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = 3x^2 - 2x + 1$. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-9","is_correct":false,"explanation":""},{"id":"B","text":"1","is_correct":false,"explanation":""},{"id":"C","text":"13","is_correct":false,"explanation":""},{"id":"D","text":"17","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find the value of f(-2), we substitute -2 for x in the function: f(-2) = 3(-2)^2 - 2(-2) + 1. Simplifying, we get f(-2) = 3(4) + 4 + 1 = 12 + 4 + 1 = 17.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'e16a3ff5_math_00399',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"e16a3ff5","opensat_index":399}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 centimeters. What is the circumference of the circle, in centimeters? (Express your answer in terms of $\pi$.)',
    'multiple_choice',
    '[{"id":"A","text":"$\\pi$","is_correct":false,"explanation":""},{"id":"B","text":"$5\\pi$","is_correct":false,"explanation":""},{"id":"C","text":"$10\\pi$","is_correct":true,"explanation":""},{"id":"D","text":"$25\\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius.  Substituting 5 for $r$ gives $C = 2\pi (5) = 10\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'f86d2a4f_math_00400',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"f86d2a4f","opensat_index":400}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 6x + 5 = 0$, what is the sum of the solutions to the equation?',
    'multiple_choice',
    '[{"id":"A","text":"5","is_correct":false,"explanation":""},{"id":"B","text":"6","is_correct":true,"explanation":""},{"id":"C","text":"11","is_correct":false,"explanation":""},{"id":"D","text":"-6","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The sum of the solutions to a quadratic equation in the form $ax^2 + bx + c = 0$ is equal to $-b/a$.  In this case, $a = 1$ and $b = -6$, so the sum of the solutions is $-(-6)/1 = 6$. ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_220a2a76c802e38a_math_00401',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c2","opensat_index":401}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with center O has a radius of 5.  A chord AB of the circle has length 8.  What is the distance from O to the chord AB?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Draw a segment from O perpendicular to chord AB, intersecting AB at point M.  Since the perpendicular from the center of a circle to a chord bisects the chord, AM = MB = 4.  Triangle OAM is a right triangle with OA as the hypotenuse and AM as a leg.  By the Pythagorean Theorem, .  Therefore, OM = 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_b026b93190344080_math_00402',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c1","opensat_index":402}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units. A chord of the circle is 8 units long. What is the distance, in units, from the center of the circle to the chord?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Draw a diagram of the circle with the chord and the radius drawn to the midpoint of the chord.  The radius, the chord, and the line segment from the center of the circle to the midpoint of the chord form a right triangle, with the radius being the hypotenuse. Since the chord is 8 units long, the line segment from the center of the circle to the midpoint of the chord is 4 units long.  The Pythagorean Theorem tells us that  The distance from the center of the circle to the chord is 3 units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_d54dce100deb6b86_math_00403',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a11","opensat_index":403}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells two types of cookies: chocolate chip and peanut butter.  On a particular day, the store sold 180 chocolate chip cookies. If the ratio of chocolate chip cookies to peanut butter cookies sold that day was 5:3, how many peanut butter cookies did the store sell?',
    'multiple_choice',
    '[{"id":"A","text":"60","is_correct":false,"explanation":""},{"id":"B","text":"90","is_correct":false,"explanation":""},{"id":"C","text":"108","is_correct":true,"explanation":""},{"id":"D","text":"180","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The ratio 5:3 means that for every 5 chocolate chip cookies sold, 3 peanut butter cookies were sold. We can set up a proportion:  \frac{5}{3} = \frac{180}{x}.  Cross-multiplying gives 5x = 540.  Dividing both sides by 5 gives $x = 108$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '54f587b2_math_00404',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"54f587b2","opensat_index":404}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with center (2, -1) is tangent to the x-axis. What is the radius of this circle? ',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":true,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Since the circle is tangent to the x-axis, the distance from the center of the circle to the x-axis is equal to the radius. The y-coordinate of the center is -1, so the radius of the circle is 1.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '97fb89f7_math_00405',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"97fb89f7","opensat_index":405}'::jsonb
  ),
(
    gen_random_uuid(),
    'In the xy-plane, a circle has a radius of 5 and a center at (3, -2). What is the equation of this circle?',
    'multiple_choice',
    '[{"id":"A","text":"(x - 3)^2 + (y + 2)^2 = 25","is_correct":true,"explanation":""},{"id":"B","text":"(x + 3)^2 + (y - 2)^2 = 5","is_correct":false,"explanation":""},{"id":"C","text":"(x + 3)^2 + (y - 2)^2 = 25","is_correct":false,"explanation":""},{"id":"D","text":"(x - 3)^2 + (y + 2)^2 = 5","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The standard form of the equation of a circle with center (h, k) and radius r is (x - h)^2 + (y - k)^2 = r^2. Substituting the given values of (h, k) = (3, -2) and r = 5, we get the equation (x - 3)^2 + (y + 2)^2 = 25.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_2f93035e17888838_math_00406',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_d4","opensat_index":406}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;