INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'The semicolon in the sentence is most likely used to',
    'multiple_choice',
    '[{"id":"A","text":"separate two closely related independent clauses.","is_correct":true,"explanation":""},{"id":"B","text":"introduce a list of items.","is_correct":false,"explanation":""},{"id":"C","text":"set off a nonessential phrase.","is_correct":false,"explanation":""},{"id":"D","text":"indicate a pause in the flow of the sentence.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The semicolon is used to separate two closely related independent clauses. The first independent clause is "The scientist explained that the sense of smell is more powerful than the sense of sight." The second independent clause is "this theory was supported by a recent study that found that people were more likely to remember a happy memory when they smelled a familiar scent than when they saw a familiar picture." The two clauses are related because the second clause provides evidence for the first clause. Semicolons are often used to separate two related independent clauses when a conjunction is not used.',
    'Review the passage and eliminate choices that contradict the text.',
    'The scientist discovered that while the color of a flower can be perceived by the human eye, the scent of a flower can be detected by the nose. The scientist explained that the sense of smell is more powerful than the sense of sight because the sense of smell can trigger memories and emotions. This theory was supported by a recent study that found that people were more likely to remember a happy memory when they smelled a familiar scent than when they saw a familiar picture. What is the most likely reason why the writer chose to use a semicolon in the sentence, "The scientist explained that the sense of smell is more powerful than the sense of sight; this theory was supported by a recent study that found that people were more likely to remember a happy memory when they smelled a familiar scent than when they saw a familiar picture."',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_ae826f692a6ea2c3_english_01425',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"random_id_a3","opensat_index":1425}'::jsonb
  ),
(
    gen_random_uuid(),
    'The passage is best described as',
    'multiple_choice',
    '[{"id":"A","text":"a problem and solution.","is_correct":true,"explanation":""},{"id":"B","text":"a cause and effect.","is_correct":false,"explanation":""},{"id":"C","text":"a comparison and contrast.","is_correct":false,"explanation":""},{"id":"D","text":"a definition and example.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The passage identifies a problem (the need to protect the environment) and then offers a solution (using less energy and reducing consumption).',
    'Review the passage and eliminate choices that contradict the text.',
    'The passage discusses the importance of protecting the environment for future generations, and it emphasizes that one way to do this is to use less energy. It also suggests that people should reduce their consumption of products that require a lot of energy to produce. The passage concludes by suggesting that the next generation will be in a better position to help protect the environment than the current generation. What is the best way to describe the structure of this passage?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'f678a74b_english_01426',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"f678a74b","opensat_index":1426}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author most likely includes details about the speaker''s worries in order to',
    'multiple_choice',
    '[{"id":"A","text":"highlight the speaker''s desire for privacy and her conflicted feelings about public attention.","is_correct":true,"explanation":""},{"id":"B","text":"show that the speaker is a complex and multifaceted character.","is_correct":false,"explanation":""},{"id":"C","text":"illustrate the speaker''s deep sense of responsibility to her fans.","is_correct":false,"explanation":""},{"id":"D","text":"emphasize the speaker''s dedication to her craft.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The author is emphasizing the speaker''s conflicted feelings about fame and success. The speaker wants to maintain her privacy, but she also understands that her writing has a public impact. This creates a sense of tension and conflict for the speaker, which makes her a more relatable and interesting character.',
    'Review the passage and eliminate choices that contradict the text.',
    'The passage describes a woman who is a successful writer and has many fans, but it also discusses the challenges of maintaining her privacy. She worries about the impact that her writing might have on her loved ones. The speaker also discusses the challenges of navigating the expectations and pressures of being a public figure. What is the most likely reason why the author includes information about the speaker''s worries?',
    'passage',
    'reading_writing',
    'Expression of Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Expression of Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Expression of Ideas']::text[],
    '876fc521_english_01427',
    'college_board_opensat',
    '{"opensat_domain":"Expression of Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"876fc521","opensat_index":1427}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best describes the overall structure of the passage?',
    'multiple_choice',
    '[{"id":"A","text":"The passage presents a problem, examines a possible solution to the problem, and then offers a conclusion.","is_correct":false,"explanation":""},{"id":"B","text":"The passage introduces a topic, provides specific examples of the topic, and then concludes by summarizing the examples.","is_correct":false,"explanation":""},{"id":"C","text":"The passage describes a process in a chronological order, highlighting the different stages involved.","is_correct":true,"explanation":""},{"id":"D","text":"The passage compares and contrasts two different approaches to a task, and then concludes by arguing for the most effective approach.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The passage describes the process of writing a screenplay in a chronological order, starting with the development of a story idea and moving through each step of the process in sequence. This is highlighted by the phrases "starting with" and "moving through." The writer then concludes by summarizing the importance of one specific step, creating a visual representation, in the process.',
    'Review the passage and eliminate choices that contradict the text.',
    'The passage details the process of writing a screenplay, starting with the development of a basic story idea and moving through outlining, character development, and finally to the final draft. The writer suggests that one important step in this process is to create a visual representation of the story, such as a storyboard, and that this can help the writer to understand the story better.  Which choice best describes the organizational structure of the passage?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_c63f5f6760e23819_english_01428',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"random_id_e7","opensat_index":1428}'::jsonb
  ),
(
    gen_random_uuid(),
    'The phrase "it is a place for peace" suggests that the speaker finds the countryside to be',
    'multiple_choice',
    '[{"id":"A","text":"a place where they can find relief from the stresses of city life.","is_correct":true,"explanation":""},{"id":"B","text":"a place that is free from conflict and violence.","is_correct":false,"explanation":""},{"id":"C","text":"a place where they can escape the noise and commotion of the city.","is_correct":false,"explanation":""},{"id":"D","text":"a place where they can find inspiration and creativity.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The speaker uses the phrase “it is a place for peace” to suggest that they find the countryside to be a place where they can find relief from the stresses of city life. This idea is further supported by the speaker’s description of the countryside as a “sweet” and “quiet” place.',
    'Review the passage and eliminate choices that contradict the text.',
    'After spending a long time in the city, the speaker has a newfound appreciation for the natural world. The speaker mentions that the "countryside" is a "sweet" and "quiet" place, and then uses the phrase "it is a place for peace." What does the speaker mean when they say that the countryside is a place for peace?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'f81d448f_english_01429',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"f81d448f","opensat_index":1429}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice completes the text so that it conforms to the conventions of Standard English?',
    'multiple_choice',
    '[{"id":"A","text":"For instance, the earliest forms of jazz were not recognized as “jazz” until after the invention of jazz music’s most important instrument: the saxophone.","is_correct":true,"explanation":""},{"id":"B","text":"For instance, the earliest forms of jazz were not recognized as “jazz” until after the invention, of jazz music’s most important instrument, the saxophone.","is_correct":false,"explanation":""},{"id":"C","text":"For instance, the earliest forms of jazz were not recognized as “jazz” until after the invention of jazz music’s most important instrument; the saxophone.","is_correct":false,"explanation":""},{"id":"D","text":"For instance, the earliest forms of jazz were not recognized as “jazz” until after the invention of jazz music’s most important instrument, the saxophone.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The text tests the punctuation of a nonessential element. Choice A is the best answer because it correctly sets off the nonessential element "the invention of jazz music’s most important instrument: the saxophone." with a pair of commas.  The other choices are incorrect because they either incorrectly use a comma or incorrectly use a semicolon or a dash to set off the nonessential element.  A semicolon is used to separate two main clauses or to separate items in a complex series, and a dash is used to separate a nonessential element from the rest of a sentence or to indicate an abrupt shift in thought. The use of a dash in the other choices is incorrect because there is no abrupt shift in thought or break in the sentence.',
    'Review the passage and eliminate choices that contradict the text.',
    'The first recorded use of the word “jazz” to describe music was in the early 1900s, but the music that the word referred to had already been around for a while. The earliest form of jazz came out of African American culture, which was, in turn, influenced by both European musical traditions and West African musical traditions, giving it a distinctly American sound. But, some historians argue that the earliest forms of jazz were not recognized as “jazz” until after the invention of jazz music’s most important instrument: the saxophone. Which choice completes the text so that it conforms to the conventions of Standard English?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'b41b7924_english_01430',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"b41b7924","opensat_index":1430}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice provides the best way to combine the underlined sentences without changing the meaning?',
    'multiple_choice',
    '[{"id":"A","text":"Griffith’s vision was both revolutionary and highly influential, and he was constantly searching for ways to push the boundaries of the medium, his work, which is, without any doubt, one of the greatest accomplishments of the American cinema.","is_correct":false,"explanation":""},{"id":"B","text":"Griffith’s vision was both revolutionary and highly influential, and he was constantly searching for ways to push the boundaries of the medium; his work, which is, without any doubt, one of the greatest accomplishments of the American cinema.","is_correct":false,"explanation":""},{"id":"C","text":"Griffith’s vision was both revolutionary and highly influential, and he was constantly searching for ways to push the boundaries of the medium, his work, which is without any doubt, one of the greatest accomplishments of the American cinema.","is_correct":true,"explanation":""},{"id":"D","text":"Griffith’s vision was both revolutionary and highly influential, and he was constantly searching for ways to push the boundaries of the medium, his work, which is, without any doubt, one of the greatest accomplishments of the American cinema, remains a timeless inspiration to filmmakers today.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The most effective way to combine the sentences is to insert a comma between the two independent clauses.  No other punctuation is needed because the second clause modifies the first clause.',
    'Review the passage and eliminate choices that contradict the text.',
    'The following excerpt is taken from a novel about the early days of the American film industry.  "The director’s name was D. W. Griffith, and he was, it is safe to say, the most influential filmmaker of the silent era.  Griffith’s vision was both revolutionary and highly influential, and he was constantly searching for ways to push the boundaries of the medium.  His work, which is, without any doubt, one of the greatest accomplishments of the American cinema, remains a timeless inspiration to filmmakers today.  "',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '60f67a8c_english_01431',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"60f67a8c","opensat_index":1431}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best combines the sentences in the underlined portion of the passage?',
    'multiple_choice',
    '[{"id":"A","text":"The two stars that appear closest to each other are so close together that they appear to be a single star, though astronomers know that there are, in fact, only six visible stars in the cluster.","is_correct":false,"explanation":""},{"id":"B","text":"Though astronomers know that there are, in fact, only six visible stars in the cluster, the two stars that appear closest to each other are so close together that they appear to be a single star.","is_correct":true,"explanation":""},{"id":"C","text":"The two stars that appear closest to each other are so close together that they appear to be a single star, and astronomers know that there are, in fact, only six visible stars in the cluster.","is_correct":false,"explanation":""},{"id":"D","text":"Astronomers know that there are, in fact, only six visible stars in the cluster; the two stars that appear closest to each other are so close together that they appear to be a single star.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Choice B is the best answer because it accurately combines the two sentences using a transition word that signals a contrast. The transition word "though" creates a logical connection between the two ideas, showing that despite the fact that astronomers know there are only six stars, the stars that appear closest to each other appear to be one star. Choice A uses the transition word "and" to connect the two sentences, which is not the best choice because it does not create a sense of contrast. Choice C uses the transition word "and" to connect the two sentences, which is not the best choice because it does not create a sense of contrast. Choice D uses a semicolon to connect the two sentences, which is not the best choice because a semicolon is generally used to connect related independent clauses, but the two sentences in this case are not independent clauses.  Choice B creates the most logical and grammatically correct connection between the two sentences.',
    'Review the passage and eliminate choices that contradict the text.',
    'The ancient Greeks viewed the Pleiades, a cluster of stars, as a group of seven stars. They believed that these stars were the Seven Sisters, a group of women who had been transformed into stars. This idea is still popular in some cultures, though astronomers know that there are, in fact, only six visible stars in the cluster. The two stars that appear closest to each other are so close together that they appear to be a single star.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'a698e32b_english_01432',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"a698e32b","opensat_index":1432}'::jsonb
  ),
(
    gen_random_uuid(),
    'The primary function of the first paragraph of the passage is to',
    'multiple_choice',
    '[{"id":"A","text":"introduce a character and his motivations.","is_correct":true,"explanation":""},{"id":"B","text":"describe a conflict that the character is facing.","is_correct":false,"explanation":""},{"id":"C","text":"establish the setting for the story.","is_correct":false,"explanation":""},{"id":"D","text":"explain the history of the character’s family.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The first paragraph introduces William, the main character, and establishes his love for the land, which is a key motivator for him in the story. The paragraph sets up his internal conflict, but it doesn''t fully develop the conflict. Therefore, the best answer is that the first paragraph introduces the character and his motivations.',
    'Review the passage and eliminate choices that contradict the text.',
    'The story begins in 1950, and it tells of a man named William. William is the son of a farmer, and he has always been fascinated by the land. From a young age, he has spent countless hours exploring the fields, watching the seasons change, and learning the secrets of nature. He is an expert on all matters concerning farming, and he is deeply respected by the people in his community. However, William''s love for the land is put to the test when he is forced to make a difficult decision. After his father’s death, William inherits the family farm, but he is also offered a job in the city that would provide him with a much higher income and a more comfortable lifestyle. William is torn between his love for the land and his desire for a better life. He wrestles with the decision, trying to weigh the pros and cons of each option.',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '7796753e_english_01433',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"7796753e","opensat_index":1433}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the writer’s emphasis on the fish’s unique characteristics most likely serves to',
    'multiple_choice',
    '[{"id":"A","text":"highlight the importance of adaptation in the animal world.","is_correct":false,"explanation":""},{"id":"B","text":"illustrate the challenges that animals face in adapting to new environments.","is_correct":false,"explanation":""},{"id":"C","text":"emphasize the vulnerability of species to changes in their environment.","is_correct":true,"explanation":""},{"id":"D","text":"suggest that the fish’s characteristics make it an example of a successful adaptation.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The passage highlights the fish''s unique characteristics, but also points out how those characteristics may make the fish more vulnerable to environmental changes. This suggests that the writer is emphasizing the vulnerability of species to change.',
    'Review the passage and eliminate choices that contradict the text.',
    'The passage describes a type of fish that has adapted to life in a very particular environment. The fish has developed unique characteristics that allow it to thrive in this environment, but these characteristics may also make it more vulnerable to changes in the environment. What is the most likely reason why the writer chose to focus on these characteristics?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    '6b21c548_english_01434',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"6b21c548","opensat_index":1434}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best combines the sentences at the underlined portion to maintain the style and tone of the passage?',
    'multiple_choice',
    '[{"id":"A","text":"awards, including a Tony Award, for his groundbreaking work in the genre.","is_correct":false,"explanation":""},{"id":"B","text":"awards, including a Tony Award for his groundbreaking work in the genre.","is_correct":true,"explanation":""},{"id":"C","text":"awards, including a Tony Award, for his groundbreaking work, in the genre.","is_correct":false,"explanation":""},{"id":"D","text":"awards including a Tony Award, for his groundbreaking work in the genre.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Choice B is the best option because it uses the correct punctuation and avoids an unnecessary comma.  A comma after "awards" is needed to separate the introductory phrase from the rest of the sentence. Choice A is incorrect because it uses a comma after "Award" which creates a comma splice.  Choice C is incorrect because it uses a comma after "work" which splits the modifying phrase unnecessarily. Choice D is incorrect because it is missing a comma after "awards" and therefore creates a comma splice.',
    'Review the passage and eliminate choices that contradict the text.',
    'The playwright, best known for his work in musical theatre, has won numerous awards, including a Tony Award,  for his groundbreaking work in the genre.  He was known for his use of innovative and challenging musical styles and for his  profound  ability to connect with audiences.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '37148a9f_english_01435',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"37148a9f","opensat_index":1435}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this excerpt, the phrase “keep at it” is used to ',
    'multiple_choice',
    '[{"id":"A","text":"emphasize the importance of perseverance.","is_correct":true,"explanation":""},{"id":"B","text":"describe the process of learning a new skill.","is_correct":false,"explanation":""},{"id":"C","text":"suggest that learning new skills is challenging.","is_correct":false,"explanation":""},{"id":"D","text":"provide an example of how to improve one’s skills.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The phrase “keep at it” is a common expression that emphasizes the importance of perseverance. This is the most likely reason the author used this phrase in this excerpt.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author of this excerpt believes that the most important thing to consider when trying to learn new skills is to be patient and persistent. This is shown by the emphasis on the phrase "keep at it." What is the most likely reason the author uses the phrase “keep at it” in this excerpt?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_008f4aa00a042f72_english_01436',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"random_id_c8","opensat_index":1436}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this sentence, the word “however” serves as a',
    'multiple_choice',
    '[{"id":"A","text":"transition word that signals a shift in thought.","is_correct":true,"explanation":""},{"id":"B","text":"descriptor word that clarifies the meaning of a word.","is_correct":false,"explanation":""},{"id":"C","text":"qualifier word that limits the scope of a statement.","is_correct":false,"explanation":""},{"id":"D","text":"conjunction word that joins two independent clauses.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The word "however" acts as a transition word that signals a shift in thought. It contrasts the information in the current sentence with the information in the previous sentence.',
    'Review the passage and eliminate choices that contradict the text.',
    'The use of the word "however" in the sentence "They had not spoken in a long time, however, they still had a lot to talk about" signals that the information in this sentence contrasts with the information in the previous sentence. In the sentence, the word "however" serves as a',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'c674e894_english_01437',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"c674e894","opensat_index":1437}'::jsonb
  ),
(
    gen_random_uuid(),
    'The conflicting views about the organization of genes in the early 1900s were most likely due to',
    'multiple_choice',
    '[{"id":"A","text":"the lack of available technology to study genes.","is_correct":false,"explanation":""},{"id":"B","text":"the lack of a consensus about the nature of genes.","is_correct":false,"explanation":""},{"id":"C","text":"the lack of knowledge about the structure of chromosomes.","is_correct":true,"explanation":""},{"id":"D","text":"the lack of understanding about the process of inheritance.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The passage states that the field of genetics was still relatively new in the early 1900s. This suggests that scientists were still learning about the structure of chromosomes, and the organization of genes on chromosomes.  The passage also explains that it wasn’t until the 1930s that scientists began to understand how genes are organized on chromosomes. This suggests that the lack of knowledge about the structure of chromosomes contributed to the conflicting views about the organization of genes.',
    'Review the passage and eliminate choices that contradict the text.',
    'In the early 1900s, the study of genetics was just beginning, and the field was still relatively new. Some scientists believed that genes were carried on chromosomes, while others believed that genes were carried on something else.  It was not until the 1930s that scientists began to understand how genes are organized on chromosomes. Some scientists thought that genes were arranged in a linear fashion, while others thought they were arranged in a circular fashion.  What is the most likely reason why there were conflicting views about the organization of genes in the early 1900s?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'a452c78f_english_01438',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"a452c78f","opensat_index":1438}'::jsonb
  ),
(
    gen_random_uuid(),
    'The phrase "from economic hardship to mental illness" is most likely included in the passage to',
    'multiple_choice',
    '[{"id":"A","text":"emphasize the many causes of homelessness.","is_correct":true,"explanation":""},{"id":"B","text":"explain the history of homelessness.","is_correct":false,"explanation":""},{"id":"C","text":"describe the different types of homeless shelters.","is_correct":false,"explanation":""},{"id":"D","text":"suggest that homelessness is a recent problem.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The phrase "from economic hardship to mental illness" lists a few of the many factors that can contribute to homelessness, which emphasizes the complexity of the problem.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author states that “the problem of homelessness is a complex one, and many factors play a role in its persistence, from economic hardship to mental illness.” What is the most likely reason why the author includes the phrase “from economic hardship to mental illness?”',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    '892f182a_english_01439',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"892f182a","opensat_index":1439}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author uses descriptive details in this passage to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of mystery and suspense.","is_correct":true,"explanation":""},{"id":"B","text":"provide information about the history of the castle.","is_correct":false,"explanation":""},{"id":"C","text":"compare the castle to other castles.","is_correct":false,"explanation":""},{"id":"D","text":"explain the importance of the castle to the story.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The descriptive details are used to create a sense of mystery and suspense, which helps to create a more immersive reading experience for the reader.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author uses several descriptive details to create a vivid image of the setting. The text describes the “dark, cool, and cavernous halls” of the castle, as well as the “high, pointed windows” that allow light to stream in. The text also mentions the “ancient tapestries” that hang on the walls and the “creaking floorboards” that add to the castle’s sense of age and mystery. What is the most likely reason why the author includes these descriptive details?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'd79f1d90_english_01440',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"d79f1d90","opensat_index":1440}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author’s primary purpose in the passage is to',
    'multiple_choice',
    '[{"id":"A","text":"describe the author’s changing perspective on a subject.","is_correct":true,"explanation":""},{"id":"B","text":"present a detailed account of the author’s research.","is_correct":false,"explanation":""},{"id":"C","text":"argue that the author’s earlier understanding of the subject was incorrect.","is_correct":false,"explanation":""},{"id":"D","text":"convince the reader to adopt the author’s current perspective.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The passage primarily focuses on the author’s evolution of thought on the subject. It highlights how the author’s initial understanding was limited and how it expanded over time. The author does not aim to convince the reader of a specific viewpoint but rather to illustrate the dynamic nature of his own thinking.',
    'Review the passage and eliminate choices that contradict the text.',
    'The passage presents a discussion of how the author’s perspective on the subject has changed over time. In the beginning, the author was convinced that his perception of the subject was accurate and comprehensive. However, as the author continued to explore the subject, he began to realize that his earlier understanding was limited. He came to appreciate that there were many different perspectives that were valid and important. What is the author’s primary purpose in the passage?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_0eaa3450eee19b37_english_01441',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a6","opensat_index":1441}'::jsonb
  ),
(
    gen_random_uuid(),
    'The use of "you" and a conversational tone help the author to',
    'multiple_choice',
    '[{"id":"A","text":"emphasize the importance of the speaker’s message.","is_correct":false,"explanation":""},{"id":"B","text":"highlight the speaker’s own feelings and experiences.","is_correct":false,"explanation":""},{"id":"C","text":"create a sense of intimacy and connection with the reader.","is_correct":true,"explanation":""},{"id":"D","text":"suggest that the speaker is addressing a large audience.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The author is attempting to create a sense of intimacy and connection with the reader by using the word "you" and a conversational tone. These techniques make the speaker seem more immediate and personal, which can help the reader feel more engaged with the message.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author is trying to establish a direct connection between the reader and the speaker, and to do that, the author uses the second person. For instance, the author says, "If you''re a little bit nervous, you can try…" The author also uses a conversational tone in this passage. What does the author hope to accomplish with these techniques?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_1263c5184573f6de_english_01442',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_e4","opensat_index":1442}'::jsonb
  ),
(
    gen_random_uuid(),
    'A certain college had 3,000 students enrolled in 2015. The college predicts that after 2015, the number of students enrolled each year will be 2% less than the number of students enrolled the year before. Which of the following functions models the relationship between the number of students enrolled, *f(x)*, and the number of years after 2015, *x*?',
    'multiple_choice',
    '[{"id":"A","text":"f(x) = 3,000(0.02)^x","is_correct":false,"explanation":""},{"id":"B","text":"f(x) = 0.98(3,000)^x","is_correct":false,"explanation":""},{"id":"C","text":"f(x) = 3,000(0.002)^x","is_correct":false,"explanation":""},{"id":"D","text":"f(x) = 3,000(0.98)^x","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Because the change in the number of students decreases by the same percentage each year, the relationship between the number of students and the number of years can be modeled with a decreasing, exponential function in the form *f(x) = a(1 - r)^x*, where *f(x)* is the number of students, *a* is the number of students in 2015, *r* is the rate of decrease each year, and *x* is the number of years since 2015. It’s given that 3,000 students were enrolled in 2015 and that the rate of decrease is predicted to be 2%, or 0.02. Substituting these values into the decreasing exponential function yields f(x) = 3,000(1 - 0.02)^x, which is equivalent to f(x) = 3,000(0.98)^x.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '281a4f3b_math_00000',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"281a4f3b","opensat_index":0}'::jsonb
  ),
(
    gen_random_uuid(),
    'The graph of the function \(f(x)= x^2 + 2x + 3\) intersects the x-axis at two points. What is the sum of the x-coordinates of these two points? ',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":true,"explanation":""},{"id":"B","text":"0","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The sum of the roots of a quadratic equation in the form of \(ax^2 + bx + c = 0\) is equal to \(-b/a\).  In this case, a = 1 and b = 2, so the sum of the roots is \(-2/1 = -2\). ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'b81173a5_math_00001',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"b81173a5","opensat_index":1}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = \frac{x^2 - 1}{x - 1}$. For what value(s) of $x$ is $f(x)$ undefined?',
    'multiple_choice',
    '[{"id":"A","text":"1 only","is_correct":true,"explanation":""},{"id":"B","text":"-1 only","is_correct":false,"explanation":""},{"id":"C","text":"0 only","is_correct":false,"explanation":""},{"id":"D","text":"1 and -1","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'A function is undefined when the denominator equals zero. In this case, the denominator is $x-1$, which is zero when $x=1$. Therefore, $f(x)$ is undefined when $x=1$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_7998d928b14b4890_math_00002',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a8","opensat_index":2}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people like apples, 50 people like bananas, and 20 people like both apples and bananas. How many people like only apples?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"20","is_correct":false,"explanation":""},{"id":"C","text":"40","is_correct":true,"explanation":""},{"id":"D","text":"60","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can use a Venn diagram to solve this problem. Let  represent the set of people who like apples, and  represent the set of people who like bananas. We know that . The problem states that 20 people like both apples and bananas, so . To find the number of people who like only apples, we subtract the number of people who like both apples and bananas from the number of people who like apples. So, the number of people who like only apples is .',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '9f6f8f8f_math_00003',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"9f6f8f8f","opensat_index":3}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 12 cm and a width of 5 cm. What is the area of the rectangle, in square cm?',
    'multiple_choice',
    '[{"id":"A","text":"17","is_correct":false,"explanation":""},{"id":"B","text":"34","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":true,"explanation":""},{"id":"D","text":"144","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is found by multiplying the length and width: 12 cm * 5 cm = 60 square cm.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_4d273f66c2e6528d_math_00004',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c4","opensat_index":4}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = \frac{1}{x^2 + 1}$. What is the value of $f(\sqrt{3})$?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{1}{4}$","is_correct":true,"explanation":""},{"id":"B","text":"$\\frac{1}{2}$","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Substituting $\sqrt{3}$ for x in the given function, we get $f(\sqrt{3}) = \frac{1}{(\sqrt{3})^2 + 1}$. Simplifying, we get $f(\sqrt{3}) = \frac{1}{3 + 1} = \frac{1}{4}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_b36f136ed539b1bb_math_00005',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c4","opensat_index":5}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units.  The point (-3,1) lies on the circle.  What is the equation of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"(x + 3)^2 + (y - 1)^2 = 25","is_correct":true,"explanation":""},{"id":"B","text":"(x + 3)^2 + (y - 1)^2 = 5","is_correct":false,"explanation":""},{"id":"C","text":"(x - 3)^2 + (y + 1)^2 = 25","is_correct":false,"explanation":""},{"id":"D","text":"(x - 3)^2 + (y + 1)^2 = 5","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The standard form of the equation of a circle with center (h, k) and radius r is (x - h)^2 + (y - k)^2 = r^2. Since the center of the circle is (-3, 1) and the radius is 5, the equation of the circle is (x - (-3))^2 + (y - 1)^2 = 5^2, or (x + 3)^2 + (y - 1)^2 = 25.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_9e35b96c214f097e_math_00006',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c9","opensat_index":6}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;