INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'A circle has a radius of 5 units. A chord of the circle is 8 units long. What is the distance, in units, from the center of the circle to the chord?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Draw a diagram of the circle with the chord and the radius to the midpoint of the chord. This creates a right triangle where the hypotenuse is the radius, one leg is half the length of the chord, and the other leg is the distance from the center to the chord.  Using the Pythagorean Theorem, we have 5² = 4² + d² where d is the distance from the center to the chord. Solving for d gives us d = 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_6a0b07df3b4cd47c_math_00007',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c1","opensat_index":7}'::jsonb
  ),
(
    gen_random_uuid(),
    'In the figure above, quadrilateral ABCD is a rectangle.  The length of diagonal is $\sqrt{20}$ units.  What is the area of the rectangle? ',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":false,"explanation":""},{"id":"B","text":"8","is_correct":false,"explanation":""},{"id":"C","text":"10","is_correct":true,"explanation":""},{"id":"D","text":"20","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diagonal of a rectangle divides the rectangle into two congruent right triangles.  Since the diagonal is the hypotenuse of each of these right triangles, the Pythagorean Theorem gives us $a^2 + b^2 = (\sqrt{20})^2$, or $a^2 + b^2 = 20$, where $a$ and $b$ are the length and width of the rectangle, respectively.  Since ABCD is a rectangle, the area is $ab$. Since the area is a product of two sides, the area will be a factor of 20.  Of the choices, 10 is the only factor of 20, and the area of the rectangle is $ab = (2)(5) = 10$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'd45a749b_math_00008',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"d45a749b","opensat_index":8}'::jsonb
  ),
(
    gen_random_uuid(),
    'The expression $(2x+1)(3x-5)$ is equivalent to which of the following? ',
    'multiple_choice',
    '[{"id":"A","text":"$6x^2-7x-5$","is_correct":true,"explanation":""},{"id":"B","text":"$6x^2+x-5$","is_correct":false,"explanation":""},{"id":"C","text":"$6x^2-x-5$","is_correct":false,"explanation":""},{"id":"D","text":"$6x^2+7x-5$","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can use the distributive property to multiply the binomials: $(2x+1)(3x-5) = 2x(3x-5) + 1(3x-5) = 6x^2 - 10x + 3x - 5 = 6x^2-7x-5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_2b63bf970cfe20d9_math_00009',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c1","opensat_index":9}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 2x - 8 = 0$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'We can factor the quadratic equation as $(x-4)(x+2) = 0$.  This means that either $x-4 = 0$ or $x+2 = 0$. Solving for $x$ in each case, we get $x = 4$ or $x = -2$.  Since the question asks for a solution to the equation, the answer is 4.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_9f39b2b5c74f8247_math_00010',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_a1","opensat_index":10}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x + 2y = 10$ and $x - 2y = 2$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can add the two equations together to eliminate $y$: \begin{align*} 3x + 2y &= 10 \\ + \\ x - 2y &= 2 \\ \hline 4x &= 12  \\ \end{align*} Dividing both sides by 4, we find that $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_0c073c951f0ff931_math_00011',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_b12","opensat_index":11}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 3x^2 - 2x + 1. What is the value of *f*(2)?',
    'multiple_choice',
    '[{"id":"A","text":"9","is_correct":true,"explanation":""},{"id":"B","text":"11","is_correct":false,"explanation":""},{"id":"C","text":"13","is_correct":false,"explanation":""},{"id":"D","text":"17","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To find *f*(2), we substitute 2 for *x* in the expression for *f*(x). This gives us *f*(2) = 3(2)^2 - 2(2) + 1 = 3(4) - 4 + 1 = 12 - 4 + 1 = 9.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '79802835_math_00012',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"79802835","opensat_index":12}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a radius of 5 units is inscribed in a square. What is the area, in square units, of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square. Since the radius of the circle is 5 units, the diameter is 10 units.  Therefore, the side length of the square is 10 units, and the area of the square is 10 * 10 = 100 square units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'f41b3483_math_00013',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"f41b3483","opensat_index":13}'::jsonb
  ),
(
    gen_random_uuid(),
    'A line in the $xy$-plane passes through the points $(2,4)$ and $(6,10)$. What is the slope of the line?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{1}{2}$","is_correct":false,"explanation":""},{"id":"B","text":"$\\frac{3}{2}$","is_correct":true,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"3","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The slope of a line passing through two points $(x_1, y_1)$ and $(x_2, y_2)$ is given by  $\frac{y_2 - y_1}{x_2 - x_1}$.  Substituting $(2,4)$ for $(x_1, y_1)$ and $(6,10)$ for $(x_2, y_2)$, we get $\frac{10-4}{6-2} = \frac{6}{4} = \frac{3}{2}$. Therefore, the slope of the line is $\frac{3}{2}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '893a69b2_math_00014',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"893a69b2","opensat_index":14}'::jsonb
  ),
(
    gen_random_uuid(),
    'A function  is defined by $f(x)= \frac{x^2 - 4}{x - 2}$. For what value of x is the function undefined?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"0","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":true,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'A function is undefined when the denominator is zero.  The denominator of this function, x - 2, is equal to zero when x = 2.  Therefore, the function is undefined when x = 2.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_c466b7e3ce0e4c8b_math_00015',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c8","opensat_index":15}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 3x^2 - 5x + 2. What is the value of *f*(2)?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":false,"explanation":""},{"id":"B","text":"6","is_correct":false,"explanation":""},{"id":"C","text":"8","is_correct":true,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find *f*(2), we substitute 2 for *x* in the function: *f*(2) = 3(2)^2 - 5(2) + 2 = 12 - 10 + 2 = 8.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '12d8c11d_math_00016',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"12d8c11d","opensat_index":16}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a radius of 5 centimeters is inscribed in a square. What is the area of the square, in square centimeters?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square.  The diameter of the circle is 2 times the radius, or 10 centimeters. Therefore, the area of the square is 10^2 = 100 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'd8f2679c_math_00017',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"d8f2679c","opensat_index":17}'::jsonb
  ),
(
    gen_random_uuid(),
    'The graph of the equation $y = x^2 - 6x + 5$ is a parabola. What are the coordinates of the vertex of this parabola?',
    'multiple_choice',
    '[{"id":"A","text":"(-3, -4)","is_correct":false,"explanation":""},{"id":"B","text":"(3, -4)","is_correct":true,"explanation":""},{"id":"C","text":"(3, 4)","is_correct":false,"explanation":""},{"id":"D","text":"(-3, 4)","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The x-coordinate of the vertex of the parabola is given by $-b/(2a)$, where a and b are the coefficients of the quadratic equation. In this case, $a = 1$ and $b = -6$, so the x-coordinate of the vertex is  6/(2*1) = 3. To find the y-coordinate of the vertex, we substitute x = 3 into the equation: $y = (3)^2 - 6(3) + 5 = 9 - 18 + 5 = -4$. Therefore, the vertex of the parabola is (3, -4).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_20a39844a06a04d8_math_00018',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a9","opensat_index":18}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve this system of equations using elimination. Multiplying the second equation by 3, we get $3x - 3y = 3$.  Adding this equation to the first equation, we get $5x = 15$.  Dividing both sides by 5, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_2685850814f61f4e_math_00019',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c2","opensat_index":19}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the simplified form of the expression $\frac{x^2 - 4}{x^2 + 4x + 4}$?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{x-2}{x+2}$","is_correct":true,"explanation":""},{"id":"B","text":"$\\frac{x+2}{x-2}$","is_correct":false,"explanation":""},{"id":"C","text":"$\\frac{x-2}{x+2}$","is_correct":false,"explanation":""},{"id":"D","text":"$\\frac{x+2}{x+2}$","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The expression can be simplified by factoring the numerator and the denominator. The numerator is a difference of squares, and the denominator is a perfect square trinomial. We have: \begin{align*} \frac{x^2 - 4}{x^2 + 4x + 4} &= \frac{(x+2)(x-2)}{(x+2)(x+2)}\\ &= \frac{x-2}{x+2}. \end{align*}',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_7b723d07e8fcba00_math_00020',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_c10","opensat_index":20}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 5x - 14 = 0$, what is the sum of the solutions to the equation?',
    'multiple_choice',
    '[{"id":"A","text":"-5","is_correct":false,"explanation":""},{"id":"B","text":"-2","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":true,"explanation":""},{"id":"D","text":"7","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can factor the quadratic equation as (x - 7)(x + 2) = 0.  The solutions to this equation are x = 7 and x = -2. The sum of these solutions is 7 + (-2) = 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_d6246b6230412e51_math_00021',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_f8","opensat_index":21}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units. What is the circumference of this circle? (Use $\pi = 3.14$)',
    'multiple_choice',
    '[{"id":"A","text":"15.7","is_correct":false,"explanation":""},{"id":"B","text":"31.4","is_correct":true,"explanation":""},{"id":"C","text":"62.8","is_correct":false,"explanation":""},{"id":"D","text":"78.5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2 \pi r$, where $r$ is the radius.  Substituting 5 for $r$ and 3.14 for $\pi$ gives $C = 2 (3.14) (5) = 31.4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_28eba7aa1cb915f2_math_00022',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c9","opensat_index":22}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells two types of candy bars, chocolate and caramel.  On a particular day, the store sells 120 chocolate candy bars and 80 caramel candy bars. If 30% of the chocolate candy bars sold that day were dark chocolate, and 40% of the caramel candy bars sold that day were milk chocolate, how many chocolate candy bars sold that day were dark chocolate?',
    'multiple_choice',
    '[{"id":"A","text":"12","is_correct":false,"explanation":""},{"id":"B","text":"36","is_correct":true,"explanation":""},{"id":"C","text":"48","is_correct":false,"explanation":""},{"id":"D","text":"60","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The store sold 120 * 0.30 = 36 dark chocolate candy bars.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'd9a8c19e_math_00023',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"d9a8c19e","opensat_index":23}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with center (2, 4) and radius 3 is graphed in the xy-plane. What is the equation of this circle?',
    'multiple_choice',
    '[{"id":"A","text":"(x - 2)^2 + (y - 4)^2 = 3","is_correct":false,"explanation":""},{"id":"B","text":"(x + 2)^2 + (y + 4)^2 = 9","is_correct":false,"explanation":""},{"id":"C","text":"(x - 2)^2 + (y - 4)^2 = 9","is_correct":true,"explanation":""},{"id":"D","text":"(x + 2)^2 + (y + 4)^2 = 3","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The standard form of the equation of a circle is (x - h)^2 + (y - k)^2 = r^2, where (h, k) is the center of the circle and r is the radius. Since the center of the circle is (2, 4) and the radius is 3, the equation of the circle is (x - 2)^2 + (y - 4)^2 = 3^2, or (x - 2)^2 + (y - 4)^2 = 9.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_8bbbe070430dbd71_math_00024',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a3","opensat_index":24}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  \(2x+3 = 11\), what is the value of \(x\)?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":true,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Subtracting 3 from both sides of the equation gives \(2x = 8\). Dividing both sides by 2 gives \(x = 4\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_4cb8710aee4e6eba_math_00025',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_c1","opensat_index":25}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey asked a group of 100 people about their favorite color. 25 people said their favorite color was blue, 30 people said their favorite color was green, and the rest said their favorite color was red.  What percentage of the people surveyed said their favorite color was red?',
    'multiple_choice',
    '[{"id":"A","text":"35%","is_correct":false,"explanation":""},{"id":"B","text":"45%","is_correct":true,"explanation":""},{"id":"C","text":"55%","is_correct":false,"explanation":""},{"id":"D","text":"65%","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'First find the number of people who said their favorite color was red: 100 people - 25 people - 30 people = 45 people.  Then divide the number of people who said red by the total number of people surveyed, and multiply by 100% to express the result as a percentage: (45 people / 100 people) * 100% = 45%.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '734eb82c_math_00026',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"734eb82c","opensat_index":26}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = \frac{1}{x-2}$ is defined for all real numbers $x$ except $x = 2$. What is the value of $f(f(3))$?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":false,"explanation":""},{"id":"B","text":"0","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":true,"explanation":""},{"id":"D","text":"2","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'First, we find $f(3)$: $f(3) = \frac{1}{3-2} = 1$. Then, we find $f(f(3))$, which is the same as $f(1)$: $f(1) = \frac{1}{1-2} = -1$. Therefore, $f(f(3)) = -1$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_20554e801a3f3f5c_math_00027',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c3","opensat_index":27}'::jsonb
  ),
(
    gen_random_uuid(),
    'A function *f* is defined by $f(x) = 2x^2 + 3x - 5$.  What is the value of *f*(-2)?',
    'multiple_choice',
    '[{"id":"A","text":"-11","is_correct":true,"explanation":""},{"id":"B","text":"-9","is_correct":false,"explanation":""},{"id":"C","text":"-5","is_correct":false,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Substituting -2 for *x* in the function *f*, we get: 

$f(-2) = 2(-2)^2 + 3(-2) - 5$ 

$f(-2) = 2(4) - 6 - 5$ 

$f(-2) = 8 - 6 - 5$ 

$f(-2) = -3$',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_92fd951f84b2c700_math_00028',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c5","opensat_index":28}'::jsonb
  ),
(
    gen_random_uuid(),
    'A bakery sells cookies in packages of 6.  If a customer buys 3 packages of cookies, how many cookies did the customer buy?',
    'multiple_choice',
    '[{"id":"A","text":"9","is_correct":false,"explanation":""},{"id":"B","text":"12","is_correct":false,"explanation":""},{"id":"C","text":"18","is_correct":true,"explanation":""},{"id":"D","text":"24","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The customer buys 3 packages of cookies, and each package contains 6 cookies.  Therefore, the customer bought 3 * 6 = 18 cookies.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_a977a37e6b2270c5_math_00029',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_f7","opensat_index":29}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined as $f(x) = \frac{x^2 - 4}{x - 2}$. For what value of $x$ is $f(x)$ undefined?',
    'multiple_choice',
    '[{"id":"A","text":"0","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"-2","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A function is undefined when its denominator is equal to zero. In this case, the denominator is $x-2$, so the function is undefined when $x-2 = 0$. Solving for $x$, we get $x = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_980f5226ef286040_math_00030',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c4","opensat_index":30}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = \frac{1}{x-2} + 3$. What is the vertical asymptote of the graph of $y = f(x)$ in the xy-plane?',
    'multiple_choice',
    '[{"id":"A","text":"x = -2","is_correct":false,"explanation":""},{"id":"B","text":"x = 2","is_correct":true,"explanation":""},{"id":"C","text":"x = -3","is_correct":false,"explanation":""},{"id":"D","text":"x = 3","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A vertical asymptote occurs where the denominator of a rational function equals zero.  The denominator of $f(x)$ is $x-2$, which equals zero when $x = 2$. Therefore, the vertical asymptote of the graph of $y = f(x)$ is $x = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_7fa8735e6bd46576_math_00031',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c5","opensat_index":31}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;