INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve for $x$ using the substitution method. Solving the second equation for $y$, we get $y = x - 1$. Substituting this into the first equation gives us $2x + 3(x - 1) = 12$. Simplifying the equation, we get $2x + 3x - 3 = 12$, or $5x - 3 = 12$. Adding 3 to both sides gives us $5x = 15$. Dividing both sides by 5, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_aeef36ef9af34aaa_math_00207',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_12","opensat_index":207}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = 2x^2 + 3x - 5$. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-15","is_correct":false,"explanation":""},{"id":"B","text":"-9","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":true,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find the value of f(-2), we substitute -2 for x in the function f(x).  This gives us f(-2) = 2(-2)^2 + 3(-2) - 5 = 8 - 6 - 5 = 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '34c8629c_math_00208',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"34c8629c","opensat_index":208}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 2x - 8 = 0$, what is the sum of the solutions to this equation?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"0","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The sum of the roots of a quadratic equation in the form ax² + bx + c = 0 is given by -b/a. In this equation, a = 1, b = -2, and c = -8. Therefore, the sum of the solutions is -(-2)/1 = 2.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '4321657a_math_00209',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"4321657a","opensat_index":209}'::jsonb
  ),
(
    gen_random_uuid(),
    'In the figure above, triangle $ABC$ is a right triangle with right angle at $C$.  If $AC = 12$ and $BC = 5$, what is the value of $sin A$?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{5}{12}$","is_correct":false,"explanation":""},{"id":"B","text":"$\\frac{5}{13}$","is_correct":true,"explanation":""},{"id":"C","text":"$\\frac{12}{13}$","is_correct":false,"explanation":""},{"id":"D","text":"$\\frac{13}{5}$","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The sine of an angle in a right triangle is equal to the length of the opposite side divided by the length of the hypotenuse.  The opposite side to angle $A$ is $BC$, and the hypotenuse is $AB$.  Since $ABC$ is a right triangle, we can use the Pythagorean Theorem to find the length of $AB$: $AB^2 = AC^2 + BC^2 = 12^2 + 5^2 = 169$, so $AB = 13$.  Therefore, $sin A = \frac{BC}{AB} = \frac{5}{13}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_7373b0f9b6004f03_math_00210',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c3","opensat_index":210}'::jsonb
  ),
(
    gen_random_uuid(),
    'The graph of the function $y = (x-2)^2 + 3$ intersects the y-axis at point $(0,a)$. What is the value of $a$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":false,"explanation":""},{"id":"D","text":"7","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The y-intercept of a graph is the point where the graph intersects the y-axis.  This occurs when $x=0$. Substituting 0 for x in the equation $y = (x-2)^2 + 3$ gives us $y = (0-2)^2 + 3 = 4 + 3 = 7$. Therefore, the y-intercept is $(0,7)$, and the value of a is 7.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'a218e3c2_math_00211',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"a218e3c2","opensat_index":211}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 2x - 15 = 0$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"-5","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Factoring the quadratic expression, we get $(x-5)(x+3) = 0$. This means either $(x-5) = 0$ or $(x+3) = 0$. Solving for $x$ in each case, we get $x = 5$ or $x = -3$. Since the question asks for the value of $x$, the answer is 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_a6b9dd5a9f030fbd_math_00212',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_c7","opensat_index":212}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store is selling a new video game for \$50.  The store also offers a discount if customers purchase two of the same video game.  If a customer buys two of the same video game, the price of the second video game is discounted by 20%.  What is the total cost, in dollars, of purchasing two of the same video game at this store? ',
    'multiple_choice',
    '[{"id":"A","text":"80","is_correct":false,"explanation":""},{"id":"B","text":"90","is_correct":true,"explanation":""},{"id":"C","text":"100","is_correct":false,"explanation":""},{"id":"D","text":"110","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The discount on the second video game is 20% of \$50, or \$10. The customer pays \$40 for the second video game and \$50 for the first, so the total cost is \$90.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_6cec7ce817b1f3a3_math_00213',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_8","opensat_index":213}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 students found that 60 students liked pizza, 50 students liked burgers, and 20 students liked both pizza and burgers. How many students liked only pizza?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"20","is_correct":false,"explanation":""},{"id":"C","text":"40","is_correct":true,"explanation":""},{"id":"D","text":"60","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can use a Venn diagram to visualize the problem. Since 20 students liked both pizza and burgers, we subtract this number from the total number of students who liked pizza and the total number of students who liked burgers to find the number of students who liked only each food: 60 - 20 = 40 students liked only pizza and 50 - 20 = 30 students liked only burgers.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_6e465d5178f98d5c_math_00214',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a1","opensat_index":214}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve for $x$ by using elimination.  Multiply the second equation by 3, which gives $3x - 3y = 3$.  Adding this equation to the first equation, we get $5x = 15$. Dividing both sides by 5, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '33c2025c_math_00215',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"33c2025c","opensat_index":215}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x + 2y = 12$ and $x - 2y = 4$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for *x*, we can add the two equations together.  Notice that the *y* terms cancel out.  This gives us  $3x + 2y + (x - 2y) = 12 + 4$, or $4x = 16$. Dividing both sides by 4, we get $x = 4$. ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_e5164b89b88d927a_math_00216',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_d9","opensat_index":216}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm.  What is the area of the circle in terms of pi?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":true,"explanation":""},{"id":"D","text":"100\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula \(A = \pi r^2\), where \(r\) is the radius.  Substituting 5 for \(r\) gives us \(A = \pi (5)^2\) = 25\pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_b8b3269678b7489b_math_00217',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c9","opensat_index":217}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 students was conducted to determine their favorite subjects. The results showed that 40 students liked math, 50 students liked science, and 20 students liked both math and science. How many students did *not* like either math or science?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":true,"explanation":""},{"id":"B","text":"20","is_correct":false,"explanation":""},{"id":"C","text":"30","is_correct":false,"explanation":""},{"id":"D","text":"40","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can use a Venn diagram to solve this problem.  Let M represent the set of students who like math and S represent the set of students who like science.  The number of students who like both math and science is represented by the intersection of M and S, which is 20.  Since 40 students like math, and 20 of those also like science, there are 40 – 20 = 20 students who like only math. Similarly, there are 50 – 20 = 30 students who like only science.  Therefore, the number of students who like neither math nor science is 100 – 20 – 30 – 20 = 10.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_82cac24e2aa65008_math_00218',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a5","opensat_index":218}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with center (2, -3) passes through the point (5, 0). What is the radius of the circle? ',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The radius of a circle is the distance from the center of the circle to any point on the circle.  We can use the distance formula to find the distance between the center (2, -3) and the point (5, 0).  The distance formula is $\sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}$.  Plugging in the values, we get $\sqrt{(5-2)^2 + (0-(-3))^2} = \sqrt{3^2 + 3^2} = \sqrt{18} = 3\sqrt{2}$.  Since the distance is $3\sqrt{2}$, the radius is $3\sqrt{2}$, and the square of the radius is $(3\sqrt{2})^2 = 18$.  Therefore, the radius is $\sqrt{18} = 3\sqrt{2}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_8f1828e09e0dddf8_math_00219',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c8","opensat_index":219}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the value of the expression  $$\frac{3^{12} \cdot 9^4}{27^3}$$? ',
    'multiple_choice',
    '[{"id":"A","text":"3^9","is_correct":false,"explanation":""},{"id":"B","text":"3^{12}","is_correct":false,"explanation":""},{"id":"C","text":"3^{15}","is_correct":true,"explanation":""},{"id":"D","text":"3^{18}","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The expression can be rewritten as $\frac{3^{12} \cdot (3^2)^4}{(3^3)^3}$. Applying the rules of exponents, we have $\frac{3^{12} \cdot 3^8}{3^9}$, which simplifies to $3^{12+8-9} = 3^{11}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '26f856bf_math_00220',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"26f856bf","opensat_index":220}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 2x - 8 = 0$, what is the sum of the solutions to this equation?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":true,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can factor the quadratic expression to get $(x-4)(x+2) = 0$. This means the solutions are $x = 4$ and $x = -2$. The sum of these solutions is $4 + (-2) = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '8a5e763b_math_00221',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"8a5e763b","opensat_index":221}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the value of the expression $\frac{5^2 - 3^2}{2^2 - 1^2}$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":true,"explanation":""},{"id":"C","text":"8","is_correct":false,"explanation":""},{"id":"D","text":"16","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can simplify the expression using the difference of squares pattern:  $\frac{5^2 - 3^2}{2^2 - 1^2} = \frac{(5+3)(5-3)}{(2+1)(2-1)} = \frac{8 \times 2}{3 \times 1} = \frac{16}{3} = \boxed{4}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '67eb899b_math_00222',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"67eb899b","opensat_index":222}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $x^2 - 2x + 1 = k$, where *k* is a constant, has exactly one solution. What is the value of *k*?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":true,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'A quadratic equation has exactly one solution if and only if its discriminant is equal to 0. The discriminant of the equation *ax² + bx + c = 0* is *b² - 4ac*. In this case, *a = 1*, *b = -2*, and *c = 1 - k*. So, the discriminant is (-2)² - 4(1)(1 - k) = 4 - 4 + 4k = 4k.  Setting this equal to 0, we get 4k = 0, or *k = 0*. However, since the equation is given as *x² - 2x + 1 = k*, we need to add 1 to both sides to get the correct value for *k*. Therefore, *k = 1*.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'b8a69f0c_math_00223',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"b8a69f0c","opensat_index":223}'::jsonb
  ),
(
    gen_random_uuid(),
    'If 2x + 3y = 12 and x - y = 1, what is the value of x?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for x, we can use elimination. Multiply the second equation by 3, which gives 3x - 3y = 3. Adding this equation to the first equation, we get 5x = 15. Dividing both sides by 5, we get x = 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_d1512715af29fe87_math_00224',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_d1","opensat_index":224}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has legs of length 5 and 12. What is the length of the hypotenuse?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"13","is_correct":true,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"20","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs. In this case, the hypotenuse, c, can be found by the equation: c² = 5² + 12² = 169.  The square root of 169 is 13, so the length of the hypotenuse is 13.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_378fd8f301e88e72_math_00225',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c4","opensat_index":225}'::jsonb
  ),
(
    gen_random_uuid(),
    'For what value of \(k\) does the equation \(x^2+6x+k=0\) have exactly one solution? ',
    'multiple_choice',
    '[{"id":"A","text":"9","is_correct":true,"explanation":""},{"id":"B","text":"6","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"0","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'A quadratic equation has exactly one solution if and only if its discriminant is equal to 0.  The discriminant of the quadratic equation \(ax^2 + bx + c = 0\) is \(b^2 - 4ac\).  In this case, the discriminant is \(6^2 - 4 \cdot 1 \cdot k = 36 - 4k\).  Setting the discriminant equal to 0 gives \(36 - 4k = 0\). Solving for \(k\) gives \(k = 9\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'f66432b2_math_00226',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"f66432b2","opensat_index":226}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with center O has a radius of 5. If point A lies on the circle and $\angle AOB = 120^\circ$, what is the length of minor arc AB?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{10\\pi}{3}$","is_correct":true,"explanation":""},{"id":"B","text":"$\\frac{20\\pi}{3}$","is_correct":false,"explanation":""},{"id":"C","text":"$\\frac{10\\pi}{6}$","is_correct":false,"explanation":""},{"id":"D","text":"$\\frac{5\\pi}{3}$","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The length of an arc is a fraction of the circumference of the circle, determined by the central angle of the arc. The fraction is the ratio of the arc''s central angle to 360 degrees. In this case, the ratio is $\frac{120^\circ}{360^\circ} = \frac{1}{3}$.  The circumference of the circle is given by $2\pi r = 2\pi (5) = 10\pi$.  Therefore, the length of minor arc AB is $\frac{1}{3} \cdot 10\pi = \frac{10\pi}{3}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'a9012a34_math_00227',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"a9012a34","opensat_index":227}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm. What is the circumference of the circle? (Use $\pi = 3.14$)',
    'multiple_choice',
    '[{"id":"A","text":"15.7 cm","is_correct":false,"explanation":""},{"id":"B","text":"31.4 cm","is_correct":true,"explanation":""},{"id":"C","text":"78.5 cm","is_correct":false,"explanation":""},{"id":"D","text":"157 cm","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2 \pi r$, where $r$ is the radius.  Substituting 5 for $r$ and 3.14 for $\pi$, we get $C = 2(3.14)(5) = 31.4$ cm.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_9ad54de27549fe3b_math_00228',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_12","opensat_index":228}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with radius 5 is inscribed in a square. What is the area of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square. The diameter is twice the radius, so the side length of the square is 10.  The area of the square is (side length)^2 = 10^2 = 100.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_c064756f20a3c38d_math_00229',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_d2","opensat_index":229}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x+3 = 7$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-4","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for x, subtract 3 from both sides of the equation:  x + 3 - 3 = 7 - 3.  This gives us x = 4.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_295634f58cdf6201_math_00230',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_a4","opensat_index":230}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people liked apples, 45 people liked oranges, and 20 people liked both apples and oranges. How many people liked neither apples nor oranges?',
    'multiple_choice',
    '[{"id":"A","text":"15","is_correct":true,"explanation":""},{"id":"B","text":"25","is_correct":false,"explanation":""},{"id":"C","text":"35","is_correct":false,"explanation":""},{"id":"D","text":"45","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can use a Venn diagram to solve this problem. Let the number of people who liked only apples be $a$, the number of people who liked only oranges be $b$, and the number of people who liked neither be $c$. Then, we have the following equations:  $a + 20 + b = 100$, $a + 20 = 60$, and $b + 20 = 45$. Solving for $a$ and $b$, we get $a = 40$ and $b = 25$. Substituting these values into the equation $a + 20 + b = 100$ gives us $40 + 20 + 25 = 100$. Therefore, $c = 100 - 85 = 15$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '9b262b21_math_00231',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"9b262b21","opensat_index":231}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;