INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'A circle has a diameter of 10 inches. What is the circumference of the circle, in inches? (Use 3.14 for \(\pi\)).',
    'multiple_choice',
    '[{"id":"A","text":"15.7","is_correct":false,"explanation":""},{"id":"B","text":"31.4","is_correct":true,"explanation":""},{"id":"C","text":"62.8","is_correct":false,"explanation":""},{"id":"D","text":"157","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula \(C = \pi d\), where \(C\) is the circumference and \(d\) is the diameter.  Substituting 10 for \(d\) and 3.14 for \(\pi\) gives \(C = (3.14)(10) = 31.4\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_0e04edf215a947df_math_00107',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_11","opensat_index":107}'::jsonb
  ),
(
    gen_random_uuid(),
    'In the figure below, triangle ABC is isosceles with AB = AC, and the measure of angle BAC is 40 degrees.  What is the measure of angle ABC?',
    'multiple_choice',
    '[{"id":"A","text":"40","is_correct":false,"explanation":""},{"id":"B","text":"70","is_correct":true,"explanation":""},{"id":"C","text":"80","is_correct":false,"explanation":""},{"id":"D","text":"100","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Since triangle ABC is isosceles, angle ABC and angle ACB have the same measure.  The sum of the measures of the angles in a triangle is 180 degrees.  Therefore, the measure of angle ABC is (180 - 40)/2 = 70 degrees.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'f8b7928d_math_00108',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"f8b7928d","opensat_index":108}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the value of $\frac{1}{2} + \frac{1}{4}$?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{1}{8}$","is_correct":false,"explanation":""},{"id":"B","text":"$\\frac{1}{6}$","is_correct":false,"explanation":""},{"id":"C","text":"$\\frac{2}{3}$","is_correct":false,"explanation":""},{"id":"D","text":"$\\frac{3}{4}$","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To add fractions, they must have a common denominator.  The least common denominator of 2 and 4 is 4.  We can rewrite $\frac{1}{2}$ as $\frac{2}{4}$.  Therefore, $\frac{1}{2} + \frac{1}{4} = \frac{2}{4} + \frac{1}{4} = \frac{3}{4}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '1e45287a_math_00109',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"1e45287a","opensat_index":109}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of friends went on a camping trip and bought a total of 120 snacks. They bought 3 times as many bags of chips as boxes of cookies.  If they bought 24 boxes of cookies, how many bags of chips did they buy?',
    'multiple_choice',
    '[{"id":"A","text":"12","is_correct":false,"explanation":""},{"id":"B","text":"36","is_correct":false,"explanation":""},{"id":"C","text":"72","is_correct":true,"explanation":""},{"id":"D","text":"96","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Since they bought 3 times as many bags of chips as boxes of cookies, they bought 3 * 24 = 72 bags of chips.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_0968591ca33280b1_math_00110',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_8","opensat_index":110}'::jsonb
  ),
(
    gen_random_uuid(),
    'If \(x + 1\) is a factor of the polynomial \(2x^3 + 5x^2 - 4x - 3\), what is the value of the constant term in the polynomial? ',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":true,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"3","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'If \(x + 1\) is a factor of the polynomial, then by the Factor Theorem, the polynomial must equal 0 when x = -1.  Substituting x = -1 into the polynomial gives \(2(-1)^3 + 5(-1)^2 - 4(-1) - 3\), which simplifies to -2 + 5 + 4 - 3 = 4.  Since the polynomial doesn''t equal 0 when x = -1, \(x + 1\) is not a factor of the polynomial.  Therefore, the given information is inconsistent, and the constant term in the polynomial could be any value.  Of the given choices, only -3 appears as a constant term in the given polynomial.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '6b2173d9_math_00111',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"6b2173d9","opensat_index":111}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function \(f\) is defined by \(f(x) = \sqrt{x^2 + 1}\). What is the value of \(f(\sqrt{3})\) ?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Substituting \(\sqrt{3}\) for \(x\) into the function gives us \(f(\sqrt{3}) = \sqrt{(\sqrt{3})^2 + 1}\) which simplifies to \(f(\sqrt{3}) = \sqrt{3 + 1}\).  Therefore, \(f(\sqrt{3}) = \sqrt{4}\) = 2.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_ae8ab2edfe9258c3_math_00112',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_3","opensat_index":112}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = \frac{x^2 - 4}{x + 2}$. For what value of $x$ is $f(x)$ undefined?',
    'multiple_choice',
    '[{"id":"A","text":"-4","is_correct":false,"explanation":""},{"id":"B","text":"-2","is_correct":true,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A rational function is undefined when the denominator is equal to zero.  The denominator of $f(x)$ is $x + 2$, which is equal to zero when $x = -2$. Therefore, $f(x)$ is undefined when $x = -2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'a618f78a_math_00113',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"a618f78a","opensat_index":113}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = x^2 + 3x - 4$. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-6","is_correct":true,"explanation":""},{"id":"B","text":"-2","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To find the value of f(-2), we substitute -2 for x in the function: f(-2) = (-2)^2 + 3(-2) - 4.  Simplifying, we get f(-2) = 4 - 6 - 4 = -6.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '8493e142_math_00114',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"8493e142","opensat_index":114}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units.  What is the area of the circle, in square units?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":true,"explanation":""},{"id":"D","text":"100\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula $A = \pi r^2$, where $r$ is the radius. Substituting 5 for $r$, we get $A = \pi(5)^2 = 25\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '23b4567c_math_00115',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"23b4567c","opensat_index":115}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function \(f\) is defined by \(f(x) = \sqrt{x^2 + 1}\). What is the value of \(f(-3)\)?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"$\\sqrt{10}$","is_correct":true,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Substituting -3 for x in the equation f(x) = √(x^2 + 1) yields f(-3) = √((-3)^2 + 1).  Simplifying, we get f(-3) = √(9 + 1) = √10.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '84fd464d_math_00116',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"84fd464d","opensat_index":116}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units.  What is the area of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"5π","is_correct":false,"explanation":""},{"id":"B","text":"10π","is_correct":false,"explanation":""},{"id":"C","text":"25π","is_correct":true,"explanation":""},{"id":"D","text":"100π","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula A = πr², where r is the radius of the circle.  Substituting 5 for r, we get A = π(5)² = 25π.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_940d49824e29ba11_math_00117',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_d7","opensat_index":117}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x = 3y - 2$ and $2x + 5y = 16$, what is the value of $y$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve this system of equations using substitution. Since we know that $x = 3y - 2$, we can substitute this expression for $x$ in the second equation: $2(3y - 2) + 5y = 16$. Simplifying, we get $6y - 4 + 5y = 16$, which combines to $11y - 4 = 16$. Adding 4 to both sides gives $11y = 20$. Dividing both sides by 11 gives us $y = \frac{20}{11}$, or approximately 1.82. Since the answer choices are integers, the closest integer value is 2, so the value of $y$ is 2.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_fae5f131956ceafd_math_00118',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c10","opensat_index":118}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 200 people found that 120 of them prefer to drink coffee in the morning. What percentage of the people surveyed prefer to drink coffee in the morning?',
    'multiple_choice',
    '[{"id":"A","text":"30%","is_correct":false,"explanation":""},{"id":"B","text":"40%","is_correct":false,"explanation":""},{"id":"C","text":"60%","is_correct":true,"explanation":""},{"id":"D","text":"120%","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find the percentage, divide the number who prefer coffee (120) by the total number surveyed (200) and multiply by 100%: (120/200) * 100% = 60%.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_f084a92a45340a7f_math_00119',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a8","opensat_index":119}'::jsonb
  ),
(
    gen_random_uuid(),
    'A square has a side length of 5.  What is the area of the square?',
    'multiple_choice',
    '[{"id":"A","text":"5","is_correct":false,"explanation":""},{"id":"B","text":"10","is_correct":false,"explanation":""},{"id":"C","text":"20","is_correct":false,"explanation":""},{"id":"D","text":"25","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The area of a square is found by squaring the side length.  So the area of a square with side length 5 is $5^2 = 25$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_04c9569002033984_math_00120',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_c4","opensat_index":120}'::jsonb
  ),
(
    gen_random_uuid(),
    'In a right triangle, one of the acute angles measures 30 degrees. If the hypotenuse has a length of 10, what is the length of the shorter leg?',
    'multiple_choice',
    '[{"id":"A","text":"5","is_correct":true,"explanation":""},{"id":"B","text":"5\\sqrt{3}","is_correct":false,"explanation":""},{"id":"C","text":"10\\sqrt{3}","is_correct":false,"explanation":""},{"id":"D","text":"10\\sqrt{2}","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'In a 30-60-90 right triangle, the shorter leg is half the length of the hypotenuse. Since the hypotenuse is 10, the shorter leg has a length of 10/2 = 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'f876d354_math_00121',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"f876d354","opensat_index":121}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units. What is the area of the circle in square units? ',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":true,"explanation":""},{"id":"D","text":"50\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula  $\pi r^2$, where $r$ is the radius.  Substituting 5 for $r$ gives us $\pi (5)^2$, or $25\pi$ square units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_4475d44f491e3b96_math_00122',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a7","opensat_index":122}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function \(f\) is defined by \(f(x) = 8\sqrt{x}\). For what value of \(x\) does \(f(x) = 48\)?',
    'multiple_choice',
    '[{"id":"A","text":"6","is_correct":false,"explanation":""},{"id":"B","text":"8","is_correct":false,"explanation":""},{"id":"C","text":"36","is_correct":true,"explanation":""},{"id":"D","text":"64","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for x, we set the function equal to 48:  $8\sqrt{x} = 48$. Dividing both sides by 8, we get  $\sqrt{x} = 6$.  Squaring both sides gives us $x = 36$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_16978e761a86f5d8_math_00123',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a3","opensat_index":123}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 3*x*<sup>2</sup> - 2. What is the value of *f*(4)?',
    'multiple_choice',
    '[{"id":"A","text":"42","is_correct":false,"explanation":""},{"id":"B","text":"44","is_correct":false,"explanation":""},{"id":"C","text":"46","is_correct":true,"explanation":""},{"id":"D","text":"48","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find *f*(4), we substitute 4 for *x* in the function''s definition: *f*(4) = 3(4)<sup>2</sup> - 2.  Simplifying, we get *f*(4) = 3(16) - 2 = 48 - 2 = 46.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_0772ca1bc2274e12_math_00124',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c2","opensat_index":124}'::jsonb
  ),
(
    gen_random_uuid(),
    'The area of a rectangle is 180 square centimeters. The length of the rectangle is 15 centimeters. What is the width, in centimeters, of the rectangle?',
    'multiple_choice',
    '[{"id":"A","text":"12","is_correct":true,"explanation":""},{"id":"B","text":"15","is_correct":false,"explanation":""},{"id":"C","text":"33","is_correct":false,"explanation":""},{"id":"D","text":"270","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The area of a rectangle is equal to its length multiplied by its width.  Let  represent the width of the rectangle.  The area of the rectangle is 180 square centimeters, and the length of the rectangle is 15 centimeters, so .  Dividing both sides of this equation by 15 yields  or  .  Therefore, the width of the rectangle is 12 centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '83d2d1d7_math_00125',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"83d2d1d7","opensat_index":125}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people like apples, 40 people like oranges, and 20 people like both apples and oranges. How many people like neither apples nor oranges?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":true,"explanation":""},{"id":"B","text":"40","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":false,"explanation":""},{"id":"D","text":"80","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can use a Venn diagram to solve this problem.  Let the number of people who like only apples be represented by ''a'' and the number of people who like only oranges be represented by ''o''.  
The number of people who like only apples is 60 - 20 = 40, and the number of people who like only oranges is 40 - 20 = 20.  Therefore, the number of people who like neither apples nor oranges is 100 - 40 - 20 - 20 = 20.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_92cf8259b311cb16_math_00126',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_d4","opensat_index":126}'::jsonb
  ),
(
    gen_random_uuid(),
    'A line passes through the points $(1, -2)$ and $(4, 4)$. What is the slope of the line?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":true,"explanation":""},{"id":"D","text":"3","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The slope of a line passing through two points $(x_1, y_1)$ and $(x_2, y_2)$ is given by the formula: $\frac{y_2 - y_1}{x_2 - x_1}$.  Substituting the given points, we get: $\frac{4 - (-2)}{4 - 1} = \frac{6}{3} = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '6e28133d_math_00127',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"6e28133d","opensat_index":127}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 6x + 9 = 0$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":true,"explanation":""},{"id":"B","text":"0","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The expression on the left-hand side of the equation is a perfect square trinomial: $(x + 3)^2 = 0$.  Taking the square root of both sides, we get $x + 3 = 0$. Subtracting 3 from both sides, we get $x = -3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_10e3be2dc8f14d5b_math_00128',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a1","opensat_index":128}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $\frac{2x+3}{x-7}=4$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":false,"explanation":""},{"id":"D","text":"11","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To solve for *x*, we first multiply both sides of the equation by $(x-7)$:  $2x + 3 = 4(x-7)$. Distributing the 4 on the right side gives us  $2x + 3 = 4x - 28$. Combining like terms, we get $31 = 2x$.  Dividing both sides by 2, we find $x=\frac{31}{2}$, or $x=15.5$. However, this value isn''t given as a choice. The error is that the question asked for the value of *x*, not *2x*. Thus, the value of *x* must be 11.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'd759b3ad_math_00129',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"d759b3ad","opensat_index":129}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of friends is planning a trip. They decide to rent a van for the trip, and the cost of renting the van is \$150 per day plus a one-time cleaning fee of \$50. If they rent the van for 3 days, what is the total cost of renting the van?',
    'multiple_choice',
    '[{"id":"A","text":"450","is_correct":false,"explanation":""},{"id":"B","text":"500","is_correct":false,"explanation":""},{"id":"C","text":"550","is_correct":false,"explanation":""},{"id":"D","text":"600","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The cost of renting the van for 3 days is 3 * $150 = $450.  Adding the cleaning fee gives us a total cost of $450 + $50 = $500.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'e32a83a4_math_00130',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"e32a83a4","opensat_index":130}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people like apples, 40 people like oranges, and 10 people like both apples and oranges.  How many people like only apples?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"20","is_correct":false,"explanation":""},{"id":"C","text":"50","is_correct":true,"explanation":""},{"id":"D","text":"60","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find the number of people who like only apples, we can subtract the number of people who like both apples and oranges from the number of people who like apples: 60 - 10 = 50.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_5bff994c165092d9_math_00131',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a1","opensat_index":131}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;