INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'The author''s use of short, declarative sentences in the beginning of the passage primarily serves to',
    'multiple_choice',
    '[{"id":"A","text":"highlight the speaker''s sense of confusion and uncertainty.","is_correct":false,"explanation":""},{"id":"B","text":"create a sense of immediacy and urgency.","is_correct":true,"explanation":""},{"id":"C","text":"emphasize the beauty and serenity of the natural world.","is_correct":false,"explanation":""},{"id":"D","text":"establish a connection between the speaker and the reader.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The use of short, declarative sentences helps to create a sense of immediacy and urgency, which reflects the speaker''s rapid movement through the setting and their growing concern about being lost.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author uses a series of short, declarative sentences to describe the initial setting, which creates a sense of urgency and immediacy. This is in contrast to the longer, more descriptive sentences used later in the passage, which create a more contemplative and reflective tone. What is the effect of the author''s use of short, declarative sentences in the beginning of the passage?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'a3c8d73c_english_01350',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"a3c8d73c","opensat_index":1350}'::jsonb
  ),
(
    gen_random_uuid(),
    'The passage suggests that the cyberpunk movement was primarily interested in',
    'multiple_choice',
    '[{"id":"A","text":"using technology to create art that would be more accessible to a wider audience.","is_correct":false,"explanation":""},{"id":"B","text":"exploring the potential of technology to change the way we experience the world.","is_correct":true,"explanation":""},{"id":"C","text":"promoting the use of digital technology in all forms of artistic expression.","is_correct":false,"explanation":""},{"id":"D","text":"creating art that would be more visually appealing than traditional art forms.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The passage states that the cyberpunk movement was interested in exploring the ways in which technology could be used to create new experiences for the viewer and to change the way we think about the world. This suggests that the cyberpunk movement was primarily interested in exploring the potential of technology to change the way we experience the world.',
    'Review the passage and eliminate choices that contradict the text.',
    'In the early 1980s, a group of artists and writers in New York City began to explore the use of digital technology in their work. They called their movement "cyberpunk," and they were interested in the ways in which technology could be used to create new forms of art and literature. They wanted to explore the ways in which technology could be used to create new experiences for the viewer, and they wanted to explore the ways in which technology could be used to create new forms of communication. They believed that technology had the potential to change the way we think about the world, and they wanted to use technology to create new forms of art and literature that reflected these changes.',
    'passage',
    'reading_writing',
    'Expression of Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Expression of Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Expression of Ideas']::text[],
    'opensat_da3f3a30d3793a6e_english_01351',
    'college_board_opensat',
    '{"opensat_domain":"Expression of Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_english_12","opensat_index":1351}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author uses the example of the "unfortunate" [person''s name] to suggest that',
    'multiple_choice',
    '[{"id":"A","text":"society often unfairly judges people based on their appearance.","is_correct":true,"explanation":""},{"id":"B","text":"people with a certain appearance are often more likely to be successful.","is_correct":false,"explanation":""},{"id":"C","text":"people who are treated unfairly are often more likely to have negative experiences.","is_correct":false,"explanation":""},{"id":"D","text":"society’s treatment of people based on their appearance is becoming less common.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The example of the [person''s name] illustrates how a person’s appearance can lead to unfair treatment from others. This suggests that society often unfairly judges people based on their appearance.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author uses the example of the “unfortunate” [person''s name] to illustrate a central idea about the relationship between a person’s appearance and their identity. In this example, the author describes how the [person''s name] is not treated kindly by others because of their appearance. The author also suggests that this unfair treatment is the result of a social system in which people are judged based on their appearance.',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    '45a48213_english_01352',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"45a48213","opensat_index":1352}'::jsonb
  ),
(
    gen_random_uuid(),
    'What revision of the sentence is best?',
    'multiple_choice',
    '[{"id":"A","text":"The team''s performance was impressive, they scored five goals and were the first team to reach the playoffs this season.","is_correct":false,"explanation":""},{"id":"B","text":"The team''s performance was impressive: they scored five goals, and they were the first team to reach the playoffs this season.","is_correct":false,"explanation":""},{"id":"C","text":"The team''s performance was impressive; they scored five goals, and were the first team to reach the playoffs this season.","is_correct":true,"explanation":""},{"id":"D","text":"The team''s performance was impressive, they scored five goals and were the first team to reach the playoffs this season.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The best way to revise the sentence is to use a semicolon to separate the two independent clauses.  This is because the two clauses are closely related in meaning.  The semicolon is the correct punctuation mark to join two independent clauses that are closely related.',
    'Review the passage and eliminate choices that contradict the text.',
    'The team''s performance was impressive. They scored five goals, and they were the first team to reach the playoffs this season.  Which of the following is the best way to revise the sentence so that it conforms to the conventions of Standard English?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_29bdd749197fa269_english_01353',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"random_id_english_1","opensat_index":1353}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice corrects the punctuation error in the sentence?',
    'multiple_choice',
    '[{"id":"A","text":"The museum curator was eager to impress visitors with the new exhibit: it featured stunning examples of early American furniture.","is_correct":false,"explanation":""},{"id":"B","text":"The museum curator was eager to impress visitors with the new exhibit; it featured stunning examples of early American furniture.","is_correct":false,"explanation":""},{"id":"C","text":"The museum curator was eager to impress visitors with the new exhibit, which featured stunning examples of early American furniture.","is_correct":true,"explanation":""},{"id":"D","text":"The museum curator was eager to impress visitors with the new exhibit, because it featured stunning examples of early American furniture.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The original sentence incorrectly uses a comma to separate two independent clauses. Choice C corrects the error by using a comma and a relative pronoun to combine the two clauses into a single, grammatically correct sentence.',
    'Review the passage and eliminate choices that contradict the text.',
    'The following sentence contains an error in punctuation. Which choice corrects this error?  The museum curator was eager to impress visitors with the new exhibit,  it featured stunning examples of early American furniture.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '12d8c11d_english_01354',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"12d8c11d","opensat_index":1354}'::jsonb
  ),
(
    gen_random_uuid(),
    'The passage suggests that social media has',
    'multiple_choice',
    '[{"id":"A","text":"made the world more interconnected but has also created new challenges.","is_correct":true,"explanation":""},{"id":"B","text":"replaced traditional forms of communication.","is_correct":false,"explanation":""},{"id":"C","text":"made it easier for people to spread misinformation.","is_correct":false,"explanation":""},{"id":"D","text":"created a more positive and productive way of communicating.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The passage describes both the positive and negative impacts of social media on communication. It states that social media has made the world more interconnected, but it also acknowledges the challenges of misinformation and fake news. Therefore, the main idea of the passage is that social media has made the world more interconnected but has also created new challenges.',
    'Review the passage and eliminate choices that contradict the text.',
    'The passage argues that the use of social media has changed the way we communicate. In the past, people would communicate face-to-face or through letters. Now, with social media, people can communicate with each other instantly, regardless of distance.  This has led to a more interconnected world, but it has also created new challenges. For example, social media can be used to spread misinformation, and it can be difficult to distinguish between reliable sources and fake news. What is the main idea of this passage?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_9f85c7f9358bb7a4_english_01355',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a3","opensat_index":1355}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author’s statement suggests that the author views a play’s success as dependent on which of the following?',
    'multiple_choice',
    '[{"id":"A","text":"The quality of the play’s writing.","is_correct":false,"explanation":""},{"id":"B","text":"The strength of the play’s themes.","is_correct":false,"explanation":""},{"id":"C","text":"The quality of the play’s acting.","is_correct":true,"explanation":""},{"id":"D","text":"The overall impact of the play’s production.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The author states that a play is only as good as the people enacting it, suggesting that the quality of the acting is the most important factor in a play’s success.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author states that while the "information" part of the play is "undeniably" well-written, it is the "performance" part that truly elevates the piece. According to the author, "A play of ideas is only as good as the people enacting it." The author then goes on to praise the actors for bringing "life, depth, and meaning" to the play’s many facets. The author’s statement about the "performance" part of the play suggests that the author views a play’s success as dependent on which of the following?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_f38b70df6175349a_english_01356',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"random_id_1","opensat_index":1356}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best maintains the sentence’s consistent use of verb tense?',
    'multiple_choice',
    '[{"id":"A","text":"The study of the effects of prolonged exposure to artificial light on the human circadian rhythm is a relatively new field, however, the results of these studies have already yielded interesting insights into the potential impact of artificial light on human health.","is_correct":true,"explanation":""},{"id":"B","text":"The study of the effects of prolonged exposure to artificial light on the human circadian rhythm is a relatively new field, however, the results of these studies have already yielded interesting insights into the potential impact of artificial light on human health.","is_correct":false,"explanation":""},{"id":"C","text":"The study of the effects of prolonged exposure to artificial light on the human circadian rhythm is a relatively new field, however, the results of these studies already yielded interesting insights into the potential impact of artificial light on human health.","is_correct":false,"explanation":""},{"id":"D","text":"The study of the effects of prolonged exposure to artificial light on the human circadian rhythm is a relatively new field, however, the results of these studies are already yielding interesting insights into the potential impact of artificial light on human health.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The sentence should maintain a consistent verb tense. The first part of the sentence is in the present tense. Therefore, the second part should also be in the present tense. "Have already yielded" is correct because it maintains the present tense.',
    'Review the passage and eliminate choices that contradict the text.',
    'The study of the effects of prolonged exposure to artificial light on the human circadian rhythm is a relatively new field, however, the results of these studies have already yielded interesting insights into the potential impact of artificial light on human health.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_50b1e733a5e9142a_english_01357',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a2","opensat_index":1357}'::jsonb
  ),
(
    gen_random_uuid(),
    'The underlined portion of the text is most likely intended to',
    'multiple_choice',
    '[{"id":"A","text":"summarize the main idea of the text.","is_correct":true,"explanation":""},{"id":"B","text":"provide an example of the complex ways in which sound can be experienced.","is_correct":false,"explanation":""},{"id":"C","text":"explain why the critics have a particular view about the album.","is_correct":false,"explanation":""},{"id":"D","text":"introduce a new point of view that will be discussed in the text.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The underlined portion of the text summarizes the main idea of the text, which is that the album explores the complex ways in which sound can be experienced.',
    'Review the passage and eliminate choices that contradict the text.',
    'The text states that some critics believe that the album questions the function of sound in the world, highlighting that the experience of sound is multifaceted. In other words, the text suggests that the album explores the complex ways in which sound can be experienced. What does the underlined portion of the text accomplish?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_5bf91e6cec8b79e6_english_01358',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a1","opensat_index":1358}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the author uses the phrase "a sea of faces" to',
    'multiple_choice',
    '[{"id":"A","text":"create a vivid image of the crowd.","is_correct":true,"explanation":""},{"id":"B","text":"describe the speaker''s emotional state.","is_correct":false,"explanation":""},{"id":"C","text":"emphasize the speaker''s sense of loneliness.","is_correct":false,"explanation":""},{"id":"D","text":"suggest that the speaker is overwhelmed by the crowd.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The phrase "a sea of faces" creates a vivid image of the crowd.  The reader can picture the faces as waves in a sea, which helps to emphasize the size and density of the crowd.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author''s use of the phrase "a sea of faces" is an example of figurative language, specifically a metaphor.  Metaphors are figures of speech that compare two unlike things without using words like *like* or *as*. What is the author''s main purpose in using this phrase?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_9a5ca4fb26ffdfc5_english_01359',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_d6","opensat_index":1359}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best describes the difference in the authors’ viewpoints?',
    'multiple_choice',
    '[{"id":"A","text":"Text 1 emphasizes the benefits of the technology, while text 2 focuses on the potential negative effects of the technology.","is_correct":true,"explanation":""},{"id":"B","text":"Text 1 discusses the history of the technology, while text 2 focuses on the future of the technology.","is_correct":false,"explanation":""},{"id":"C","text":"Text 1 presents a more personal viewpoint, while text 2 presents a more objective viewpoint.","is_correct":false,"explanation":""},{"id":"D","text":"Text 1 focuses on the economic impact of the technology, while text 2 focuses on the social impact of the technology.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Text 1 focuses on the positive impact of the technology, while text 2 focuses on the potential negative effects. This is the most likely reason why the authors have such different viewpoints. The author of text 1 is likely more optimistic about the technology, while the author of text 2 is likely more concerned about the potential downsides.',
    'Review the passage and eliminate choices that contradict the text.',
    'While the author of the text 1 believes that this is a positive development for the community, the author of text 2 presents a more cautious viewpoint, emphasizing the potential drawbacks of this new technology. Although text 1 highlights the advantages of increased efficiency and the potential to reduce costs, text 2 cautions that the technology could lead to job displacement and a decrease in economic opportunities. What is the most likely reason the authors of text 1 and text 2 have such different viewpoints?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '238f8392_english_01360',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"238f8392","opensat_index":1360}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the main idea of the passage?',
    'multiple_choice',
    '[{"id":"A","text":"Vinyl records are making a comeback due to their nostalgic appeal and the growing popularity of analog sound.","is_correct":true,"explanation":""},{"id":"B","text":"Record labels are reissuing albums on vinyl to cater to a niche market of audiophiles.","is_correct":false,"explanation":""},{"id":"C","text":"Digital music has become the dominant format for music consumption.","is_correct":false,"explanation":""},{"id":"D","text":"The resurgence of vinyl records is a sign that the music industry is embracing new technologies.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The passage focuses on the reasons behind the resurgence of vinyl records, specifically highlighting the appeal of analog sound and the tactile experience it offers. The passage also mentions the younger generation''s interest in vinyl, suggesting that it''s not just a nostalgic trend for older generations.',
    'Review the passage and eliminate choices that contradict the text.',
    'In the early 1990s, as a response to the popularity of compact discs, some record labels began reissuing their albums on vinyl. This was seen as a niche market catering to audiophiles who preferred the warmth and sound of analog recordings. However, by the late 2000s, vinyl records had gained a broader appeal. Younger generations were drawn to the tactile experience of vinyl and the accompanying album art. The resurgence of vinyl records is a testament to the enduring appeal of analog sound and the artistic value of music beyond its digital format.',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_0930156fbf208db7_english_01361',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"random_id_c6","opensat_index":1361}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice completes the text so that it conforms to the conventions of Standard English?',
    'multiple_choice',
    '[{"id":"A","text":"promise","is_correct":true,"explanation":""},{"id":"B","text":"promises","is_correct":false,"explanation":""},{"id":"C","text":"promising","is_correct":false,"explanation":""},{"id":"D","text":"promised","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The verb "promise" is the correct choice because it agrees in number with the singular subject "campaign." The other choices are incorrect because they don''t agree in number with the subject.',
    'Review the passage and eliminate choices that contradict the text.',
    'The company''s new advertising campaign ______ to be a success, featuring a catchy jingle and a memorable slogan.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_13a82706698fcd22_english_01362',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"random_id_e2","opensat_index":1362}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the word "you" is used to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of intimacy and connection with the reader.","is_correct":true,"explanation":""},{"id":"B","text":"describe the speaker’s feelings and experiences.","is_correct":false,"explanation":""},{"id":"C","text":"emphasize the importance of the speaker’s message.","is_correct":false,"explanation":""},{"id":"D","text":"suggest that the speaker is addressing a large audience.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The speaker is addressing the reader directly by using the word "you." This creates a sense of intimacy and connection with the reader, which can help the reader feel more engaged with the message.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author claims that "the most obvious sign that the speaker is speaking directly to the reader is the use of the word "you." There are other elements of the passage that may help to make the speaker seem more immediate and personal. The speaker refers to events and places that are familiar to the reader, and the speaker uses a conversational tone throughout the passage. What is the most likely reason why the writer uses the word "you"?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'f54c918d_english_01363',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"f54c918d","opensat_index":1363}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author of this passage most likely uses specific examples to',
    'multiple_choice',
    '[{"id":"A","text":"to help the reader visualize the topic.","is_correct":false,"explanation":""},{"id":"B","text":"to make the argument more persuasive.","is_correct":false,"explanation":""},{"id":"C","text":"to provide evidence that supports the author''s claims.","is_correct":true,"explanation":""},{"id":"D","text":"to demonstrate the author’s knowledge of the topic.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Specific examples are used to provide evidence that supports the author’s claims.  This makes the argument more persuasive and helps the reader to understand and believe the author’s point of view.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author of the passage is trying to persuade the reader that a particular view is correct.  To do so, the author uses a variety of rhetorical devices.  One of the most noticeable is the use of logical appeals.  For example, the author refers to a study that was conducted by experts in the field.  The author also provides specific examples to support the argument.  What is the most likely reason why the author provides specific examples?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_ece88a17657b47ed_english_01364',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_e4","opensat_index":1364}'::jsonb
  ),
(
    gen_random_uuid(),
    'The detail about Eric is included to',
    'multiple_choice',
    '[{"id":"A","text":"describe the speaker’s current method of remembering names.","is_correct":false,"explanation":""},{"id":"B","text":"demonstrate the speaker’s desire to learn names.","is_correct":false,"explanation":""},{"id":"C","text":"provide an example of the speaker’s memory problems.","is_correct":false,"explanation":""},{"id":"D","text":"illustrate the speaker’s connection between a name and a physical trait.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The detail about Eric is included to illustrate the speaker’s connection between a name and a physical trait. The speaker uses Eric as an example to show how the connection between a name and a physical or personal trait can help to remember names.',
    'Review the passage and eliminate choices that contradict the text.',
    'As a young child, I struggled to learn the names of my classmates. Each day, I felt a sense of panic, convinced that if I couldn’t remember their names, I would somehow be ostracized.  Each day, I would scramble to memorize the list of faces and names, but I couldn’t seem to hold on to the information for long.  My parents often helped me, but even their assistance proved unsuccessful.  I was desperate for a method to learn the names, and I felt a sense of profound relief when I discovered that I only needed to make small connections to their names to remember them.  For example,  if I could find a connection to the first letter of the name, such as a classmate with big eyes named Eric, I could easily remember his name. This method, which involved associating their names with a physical or personal trait, was a simple solution that I could use to retain the information in my memory.  What is the most likely reason the writer includes the detail about the classmate named Eric?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'f13e0657_english_01365',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"f13e0657","opensat_index":1365}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best summarizes the main idea of this paragraph?',
    'multiple_choice',
    '[{"id":"A","text":"People should conform to the expectations of society in order to be fulfilled.","is_correct":false,"explanation":""},{"id":"B","text":"People should be willing to embrace their individuality in order to be fulfilled.","is_correct":true,"explanation":""},{"id":"C","text":"Society often discourages people from being different.","is_correct":false,"explanation":""},{"id":"D","text":"People should be willing to follow the crowd in order to be fulfilled.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The author''s main point is that being true to oneself and embracing one''s individuality leads to fulfillment and happiness.  This is reflected in the phrase "it is okay to be different" and the statement that people who "embrace their individuality often find that they are more fulfilled and happier in the long run."',
    'Review the passage and eliminate choices that contradict the text.',
    'In a society where conformity is highly valued, it is easy to fall into the trap of following the crowd.  However, it is important to remember that everyone has their own unique qualities and that it is okay to be different.  People who are willing to embrace their individuality often find that they are more fulfilled and happier in the long run.  The author suggests that',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_7b9523c534fd50db_english_01366',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a6","opensat_index":1366}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the main point the author makes about the history of the world?',
    'multiple_choice',
    '[{"id":"A","text":"The history of the world is not a simple story of progress, but a complex tapestry of events, ideas, and people.","is_correct":true,"explanation":""},{"id":"B","text":"The Industrial Revolution has had a lasting impact on the world, and people are still trying to understand its full implications.","is_correct":false,"explanation":""},{"id":"C","text":"The challenges of global warming are still being addressed in the 21st century.","is_correct":false,"explanation":""},{"id":"D","text":"Democracy is a work in progress in the 21st century.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The author makes it clear that history is complex and nonlinear, and that the world is not simply progressing forward. This idea is reinforced throughout the passage with the use of examples and metaphors.',
    'Review the passage and eliminate choices that contradict the text.',
    'The most important thing to remember about the history of the world is that it’s not linear. History is a complicated, messy process, with lots of different threads and influences weaving together in unpredictable ways. For example, the development of democracy was not a simple progression from ancient Greece to modern times.  Instead, it was a long and winding road, with many setbacks and false starts. And even in the 21st century, democracy is still a work in progress.  It’s important to remember that history is not a simple story of progress, but a complex tapestry of events, ideas, and people.  In the 21st century, people are still trying to understand the full implications of the Industrial Revolution, and they’re still working to address the challenges of global warming.  It’s also important to remember that history is not just about the past.  It’s also about the present, and it’s about the future.',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_aa3dfd9744ad9a39_english_01367',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_c9","opensat_index":1367}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best combines the sentences at the underlined portion to create a complex sentence without changing the meaning?',
    'multiple_choice',
    '[{"id":"A","text":"The author of \"The Great Gatsby\" is known for his elegant style and his descriptions of lavish parties; however, many critics have pointed to the novel’s use of symbolism as a way to explore a larger theme.","is_correct":false,"explanation":""},{"id":"B","text":"The author of \"The Great Gatsby\" is known for his elegant style and his descriptions of lavish parties, however, many critics have pointed to the novel’s use of symbolism as a way to explore a larger theme.","is_correct":false,"explanation":""},{"id":"C","text":"The author of \"The Great Gatsby\" is known for his elegant style and his descriptions of lavish parties, many critics have pointed to the novel’s use of symbolism as a way to explore a larger theme.","is_correct":false,"explanation":""},{"id":"D","text":"The author of \"The Great Gatsby\" is known for his elegant style and his descriptions of lavish parties, but many critics have pointed to the novel’s use of symbolism as a way to explore a larger theme.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Choice D is the best answer.  Choice D uses the conjunction "but" to connect the two clauses, creating a complex sentence that maintains the original meaning. The other choices are incorrect because they either use incorrect punctuation or create a run-on sentence.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author of "The Great Gatsby" is known for his elegant style and his descriptions of lavish parties.  However, many critics have pointed to the novel’s use of symbolism as a way to explore a larger theme.  The story''s setting, in the Roaring Twenties of New York, is often interpreted as representing the rise and fall of the American Dream, and the green light across the bay can be seen as a symbol of hope and the unattainable.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '25e61f2c_english_01368',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"25e61f2c","opensat_index":1368}'::jsonb
  ),
(
    gen_random_uuid(),
    'The underlined portion of this passage primarily serves to',
    'multiple_choice',
    '[{"id":"A","text":"provide a summary of the author''s argument.","is_correct":false,"explanation":""},{"id":"B","text":"explain the author''s reasoning.","is_correct":false,"explanation":""},{"id":"C","text":"identify a specific problem the author is addressing.","is_correct":false,"explanation":""},{"id":"D","text":"highlight a solution to a problem the author is addressing.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The underlined portion of this passage summarizes the author''s recommendations for how to minimize the negative impacts of social media. This is the solution the author is offering to the problem that they have previously identified.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author’s central argument in the passage is that while the practice of using social media for social purposes can be beneficial, it can also have a negative impact. However, the author argues that this negative impact can be minimized by following a few simple rules. The author concludes that it’s important to be mindful of the time spent on social media, and to avoid using it for purposes that are not conducive to a positive social experience.  What is the main function of the underlined portion?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '98754f91_english_01369',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"98754f91","opensat_index":1369}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best describes the error in the underlined portion of this sentence?',
    'multiple_choice',
    '[{"id":"A","text":"The sentence contains a comma splice.","is_correct":true,"explanation":""},{"id":"B","text":"The sentence contains a misplaced modifier.","is_correct":false,"explanation":""},{"id":"C","text":"The sentence is missing a comma after the introductory phrase.","is_correct":false,"explanation":""},{"id":"D","text":"The sentence contains a dangling modifier.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The underlined portion of the sentence contains a comma splice, which is a grammatical error that occurs when two independent clauses are joined together with only a comma. To correct the error, the comma should be replaced with a semicolon or a conjunction, such as "and." The sentence could be corrected as follows:  "It was easy to imagine what life would have been like for the people who lived there a century ago; it''s a fascinating place, full of history and charm."',
    'Review the passage and eliminate choices that contradict the text.',
    'The first time I saw the city, it was like stepping into a time capsule. The streets were filled with charming old buildings that had been meticulously preserved, and the air was filled with the sounds of horse-drawn carriages. I felt as if I had traveled back to a bygone era.  It was easy to imagine what life would have been like for the people who lived there a century ago.  It''s a fascinating place, full of history and charm.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_4879719e25079538_english_01370',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a3","opensat_index":1370}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following best describes the author''s tone in this passage?',
    'multiple_choice',
    '[{"id":"A","text":"Critical","is_correct":false,"explanation":""},{"id":"B","text":"Objective","is_correct":true,"explanation":""},{"id":"C","text":"Apologetic","is_correct":false,"explanation":""},{"id":"D","text":"Euphoric","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The author''s tone is objective because they present a neutral perspective on the development of the atomic bomb. The author presents the scientific and historical context without expressing strong personal opinions or judgments.',
    'Review the passage and eliminate choices that contradict the text.',
    'The primary purpose of the text is to explain the history of the development of the atomic bomb. The author describes how the bomb was created, the scientists involved, and the ethical dilemmas that arose during its development. Although the author acknowledges the devastating consequences of the bomb, the overall tone of the passage is not one of condemnation. Instead, the author seems to be more interested in presenting the scientific and historical context in which the bomb was created.',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_e54c01e0b498775c_english_01371',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a2","opensat_index":1371}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following sentences best concludes the argument?',
    'multiple_choice',
    '[{"id":"A","text":"For a healthy and delicious snack, look no further than this new product.","is_correct":true,"explanation":""},{"id":"B","text":"While the product is available in several flavors, it is not suitable for people with nut allergies.","is_correct":false,"explanation":""},{"id":"C","text":"The product is made with all-natural ingredients and is a good source of protein.","is_correct":false,"explanation":""},{"id":"D","text":"The product is available at most grocery stores, and it is often on sale.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Choice A is the best answer because it effectively concludes the argument by summarizing the author’s main point—that the product is a healthy and delicious alternative to traditional snacks—and by encouraging the reader to try the product. The other choices are incorrect because they don’t effectively conclude the argument. Choice B introduces a new idea—that the product is not suitable for people with nut allergies—that isn’t relevant to the author’s main point. Choice C simply restates information that has already been presented in the passage, and Choice D provides information that is not relevant to the author’s main point.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author''s main goal in the passage is to describe the features of a new product—a special type of food that is being promoted as a healthy and delicious alternative to traditional snacks. The author claims that the product is made with all-natural ingredients, and that it is a source of essential vitamins and minerals. The author also states that the product is available in several flavors. Which of the following sentences should be added to the end of the passage to most effectively conclude the argument?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_d81c67afdf6f26a7_english_01372',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_c3","opensat_index":1372}'::jsonb
  ),
(
    gen_random_uuid(),
    'The phrase “cast a long shadow” is used in this passage to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of suspense and anticipation for the reader.","is_correct":false,"explanation":""},{"id":"B","text":"emphasize the lasting impact of the event.","is_correct":true,"explanation":""},{"id":"C","text":"highlight the author’s personal connection to the event.","is_correct":false,"explanation":""},{"id":"D","text":"describe the physical characteristics of the event.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The phrase "cast a long shadow" suggests that the event has had a lasting impact on the world, which is the central idea of the passage.',
    'Review the passage and eliminate choices that contradict the text.',
    'In this passage, the author uses the phrase "cast a long shadow" to describe the legacy of a particular historical event. This phrase is often used in a figurative sense to suggest that the event has had a lasting impact on the world. The author is employing this figurative language to create a sense of weight and significance for the event. The author’s use of this figurative language is also a way to emphasize the importance of the event for the reader. How does the phrase "cast a long shadow" contribute to the passage’s overall meaning?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_68eef80b7e2e6eaf_english_01373',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_c8","opensat_index":1373}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author most likely uses the metaphor in this passage to',
    'multiple_choice',
    '[{"id":"A","text":"create an image in the reader''s mind.","is_correct":true,"explanation":""},{"id":"B","text":"provide a concise explanation of a complex idea.","is_correct":false,"explanation":""},{"id":"C","text":"emphasize the importance of the subject matter.","is_correct":false,"explanation":""},{"id":"D","text":"suggest that the speaker is uncertain about the topic.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The author is using a metaphor to create a vivid image in the reader''s mind. By comparing the subject matter to something else, the author helps the reader to visualize the subject matter more clearly.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author of this excerpt is using a type of figurative language known as a metaphor.  A metaphor is a figure of speech that makes a comparison between two unlike things without using words like "like" or "as." What is the most likely reason the author is using a metaphor in this passage?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'd4f3a11d_english_01374',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"d4f3a11d","opensat_index":1374}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;