INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm. What is the circumference of the circle? (Use $\pi = 3.14$)',
    'multiple_choice',
    '[{"id":"A","text":"15.7 cm","is_correct":false,"explanation":""},{"id":"B","text":"31.4 cm","is_correct":true,"explanation":""},{"id":"C","text":"78.5 cm","is_correct":false,"explanation":""},{"id":"D","text":"157 cm","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius. Substituting 5 cm for $r$ and 3.14 for $\pi$, we get $C = 2(3.14)(5) = 31.4$ cm.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_88e07aa67bbfb458_math_00982',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_c2","opensat_index":982}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has legs of length 5 and 12. What is the length of the hypotenuse of the triangle?',
    'multiple_choice',
    '[{"id":"A","text":"13","is_correct":true,"explanation":""},{"id":"B","text":"17","is_correct":false,"explanation":""},{"id":"C","text":"19","is_correct":false,"explanation":""},{"id":"D","text":"25","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs.  Therefore, the length of the hypotenuse is  $\sqrt{5^2 + 12^2} = \sqrt{169} = 13$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'f1d7a634_math_00983',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"f1d7a634","opensat_index":983}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x+y = 5$ and $x-y=1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Adding the two equations together, we get $(x+y) + (x-y) = 5+1$, or $2x = 6$. Dividing both sides by 2 gives $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_f101fc79802c24a3_math_00984',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_d5","opensat_index":984}'::jsonb
  ),
(
    gen_random_uuid(),
    'A function is defined by the equation \(f(x) = 2x^2 + 3x - 5\). What is the value of \(f(-2)\)?',
    'multiple_choice',
    '[{"id":"A","text":"-17","is_correct":false,"explanation":""},{"id":"B","text":"-9","is_correct":true,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"13","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To find f(-2), we substitute -2 for x in the equation: \(f(-2) = 2(-2)^2 + 3(-2) - 5\). Simplifying, we get \(f(-2) = 8 - 6 - 5\), or \(f(-2) = -3\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_3ff063f611d1cdd8_math_00985',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c9","opensat_index":985}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of friends is planning a trip. They decide to rent a car for the trip.  The cost to rent a car is a flat fee of $25, plus $15 per day.  Let *c* represent the total cost, in dollars, and *d* represent the number of days the car is rented.  Which of the following equations represents the relationship between *c* and *d*?',
    'multiple_choice',
    '[{"id":"A","text":"c = 25d + 15","is_correct":false,"explanation":""},{"id":"B","text":"c = 15d + 25","is_correct":true,"explanation":""},{"id":"C","text":"c = 25 + 15d","is_correct":false,"explanation":""},{"id":"D","text":"c = 15 + 25d","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The flat fee of $25 is a constant cost, and the cost per day, $15, is multiplied by the number of days, *d*.  Therefore, the total cost, *c*, is represented by the equation c = 15d + 25.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '23ef2021_math_00986',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"23ef2021","opensat_index":986}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x$ is a real number, and $x^2 - 4x + 4 = 0$, what is the value of $x + 1$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":true,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The equation $x^2 - 4x + 4 = 0$ factors as $(x-2)^2 = 0$. This tells us that $x - 2 = 0$, or $x = 2$.  Therefore, $x + 1 = 2 + 1 = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '3d985142_math_00987',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"3d985142","opensat_index":987}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people liked apples, 40 people liked oranges, and 20 people liked both apples and oranges. How many people liked only apples?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":true,"explanation":""},{"id":"B","text":"40","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":false,"explanation":""},{"id":"D","text":"80","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can use a Venn diagram to solve this problem.  Let''s represent the number of people who like only apples as  *a*, the number of people who like only oranges as *o*, and the number of people who like both as *b*. We are given that *a* + *b* = 60, *o* + *b* = 40, and *b* = 20. Substituting *b* = 20 into the first two equations, we get *a* + 20 = 60 and *o* + 20 = 40. Solving for *a*, we find *a* = 60 - 20 = 40.  Therefore, 40 people like only apples.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_6acd3daf8c556f65_math_00988',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_d8","opensat_index":988}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 2x - 3 = 0$, what is the value of $x^3 + 2x^2 - 3x$?',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":false,"explanation":""},{"id":"B","text":"0","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":true,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can factor the given equation as $(x+3)(x-1)=0$.  This means that $x=-3$ or $x=1$.  Substituting either value into the expression $x^3 + 2x^2 - 3x$ gives us 3.  Therefore, the value of $x^3 + 2x^2 - 3x$ is 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '13b8a32c_math_00989',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"13b8a32c","opensat_index":989}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people like apples, 45 people like oranges, and 20 people like both apples and oranges. How many people like only apples?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":false,"explanation":""},{"id":"B","text":"40","is_correct":true,"explanation":""},{"id":"C","text":"60","is_correct":false,"explanation":""},{"id":"D","text":"80","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can use a Venn diagram to solve this.  Let the number of people who like only apples be represented by x.  
[asy] 
label("Apples",(1.5,1.5));
label("Oranges",(2.5,1.5));
label("x",(1,1));
label("20",(2,1));
label("25",(3,1));
draw(Circle((1,1),1));
draw(Circle((2,1),1));
draw((0.5,0)--(3.5,0));
draw((0,0.5)--(0,2.5));
[/asy]  The number of people who like oranges is 45, so 20 + 25 = 45. Therefore, the number of people who like only apples is 40.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_381a3a81fc5dfbfa_math_00990',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a8","opensat_index":990}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = \frac{x^2 - 4}{x - 2}$ is undefined for what value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-4","is_correct":false,"explanation":""},{"id":"B","text":"-2","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":true,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'A function is undefined when its denominator equals zero.  In this case, the denominator is $x-2$, which equals zero when $x=2$. Therefore, the function is undefined for $x=2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_79d8f8c66c43e1ae_math_00991',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_b21","opensat_index":991}'::jsonb
  ),
(
    gen_random_uuid(),
    'In the $xy$-plane, line $k$ passes through the points $(2,-1)$ and $(4,3)$. What is the slope of line $k$?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":true,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The slope of a line passing through two points $(x_1, y_1)$ and $(x_2, y_2)$ can be calculated using the formula: $m = \frac{y_2 - y_1}{x_2 - x_1}$.  Substituting the points (2, -1) and (4, 3) into the formula, we get: $m = \frac{3 - (-1)}{4 - 2} = \frac{4}{2} = 2$. Therefore, the slope of line $k$ is 2.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '1453c4d6_math_00992',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"1453c4d6","opensat_index":992}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $f(x) = \frac{x^2-1}{x+1}$ for $x \ne -1$, what is the value of $f(-3)$?',
    'multiple_choice',
    '[{"id":"A","text":"-4","is_correct":false,"explanation":""},{"id":"B","text":"-2","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substituting -3 for x in the function, we get: $f(-3) = \frac{(-3)^2-1}{-3+1}$. Simplifying the expression, we get $f(-3) = \frac{9-1}{-2} = \frac{8}{-2} = -4$. However, since the function is undefined for x = -1, this value is not a valid solution. Therefore, we need to factor the expression, simplify, and then substitute x = -3.  Factoring the expression, we get: $f(x) = \frac{(x+1)(x-1)}{x+1}$.  Since $x \ne -1$, we can cancel out the common factor of (x+1), leaving us with $f(x) = x-1$.  Substituting -3 for x in this simplified expression, we get $f(-3) = -3 - 1 = -4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'a22d8ac5_math_00993',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"a22d8ac5","opensat_index":993}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of 10 friends are planning a trip. They decide to split the cost of the trip evenly.  If the total cost of the trip is $1,200, how much will each friend pay?',
    'multiple_choice',
    '[{"id":"A","text":"$100","is_correct":false,"explanation":""},{"id":"B","text":"$120","is_correct":true,"explanation":""},{"id":"C","text":"$1,200","is_correct":false,"explanation":""},{"id":"D","text":"$12,000","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To find the cost per friend, we divide the total cost by the number of friends: $1,200 / 10 = $120.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_bded051901667ca4_math_00994',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c3","opensat_index":994}'::jsonb
  ),
(
    gen_random_uuid(),
    'A regular hexagon is inscribed in a circle with a radius of 6. What is the perimeter of the hexagon?',
    'multiple_choice',
    '[{"id":"A","text":"12","is_correct":false,"explanation":""},{"id":"B","text":"18","is_correct":false,"explanation":""},{"id":"C","text":"24","is_correct":false,"explanation":""},{"id":"D","text":"36","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'A regular hexagon can be divided into 6 equilateral triangles. The side of each equilateral triangle is equal to the radius of the circle, which is 6. So the perimeter of the hexagon is 6 * 6 = 36.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_caf31c7be649d523_math_00995',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c2","opensat_index":995}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $\frac{x}{y}= 3$ and $\frac{y}{z}= 2$, what is the value of $\frac{x}{z}$?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{1}{6}$","is_correct":false,"explanation":""},{"id":"B","text":"$\\frac{1}{2}$","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find the value of $\frac{x}{z}$, we can multiply the two given equations: $(\frac{x}{y}) \cdot (\frac{y}{z}) = 3 \cdot 2$.  Notice that the $y$ terms cancel out, leaving us with $\frac{x}{z} = 6$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_c81c2091c12ece7d_math_00996',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_a5","opensat_index":996}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm. What is the area of the circle in square centimeters?',
    'multiple_choice',
    '[{"id":"A","text":"10\\pi","is_correct":false,"explanation":""},{"id":"B","text":"25\\pi","is_correct":true,"explanation":""},{"id":"C","text":"50\\pi","is_correct":false,"explanation":""},{"id":"D","text":"100\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The area of a circle is given by the formula A = \pi r^2, where r is the radius.  Substituting 5 for r, we get A = \pi (5)^2 = 25\pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_810b3c694f3be1d9_math_00997',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_1","opensat_index":997}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of friends are planning a trip. They decide to split the cost of the trip evenly among themselves.  If the total cost of the trip is \$1500 and there are 5 friends, how much will each friend pay?',
    'multiple_choice',
    '[{"id":"A","text":"30","is_correct":false,"explanation":""},{"id":"B","text":"100","is_correct":false,"explanation":""},{"id":"C","text":"300","is_correct":true,"explanation":""},{"id":"D","text":"750","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find out how much each friend will pay, we divide the total cost by the number of friends: $1500 / 5 = $300.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_ff50ae08e6884e72_math_00998',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_15","opensat_index":998}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x$ is a positive integer, what is the smallest possible value of $x$ such that $\frac{x^2 - 4}{x - 2}$ is an integer?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The expression $\frac{x^2 - 4}{x - 2}$ can be simplified by factoring the numerator: $\frac{x^2 - 4}{x - 2} = \frac{(x+2)(x-2)}{x - 2} = x + 2$, as long as $x \neq 2$.  Since $x$ is a positive integer, the smallest possible value of $x$ that makes this expression an integer is $x = 4$. ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'd8c76f6a_math_00999',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"d8c76f6a","opensat_index":999}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - 2y = 4$, what is the value of $x + y$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for $x + y$, we can add the two equations together.  The $y$ terms will cancel out, leaving us with $3x = 16$.  Solving for $x$, we get $x = \frac{16}{3}$.  Substituting this value back into either of the original equations, we can solve for $y$.  Substituting into the first equation, we get $2 \cdot \frac{16}{3} + 3y = 12$, or $\frac{32}{3} + 3y = 12$.  Subtracting $\frac{32}{3}$ from both sides, we get $3y = 12 - \frac{32}{3}$, or $3y = \frac{4}{3}$.  Dividing both sides by 3, we get $y = \frac{4}{9}$.  Therefore, $x + y = \frac{16}{3} + \frac{4}{9} = 6$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'e83839db_math_01000',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"e83839db","opensat_index":1000}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a radius of 5 cm is inscribed in a square. What is the area, in square centimeters, of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square. Since the radius of the circle is 5 cm, the diameter is 10 cm.  Therefore, the side length of the square is 10 cm, and the area of the square is 10² = 100 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_e108864abd6adc57_math_01001',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_29","opensat_index":1001}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 12 meters and a width of 5 meters. What is the area of the rectangle, in square meters?',
    'multiple_choice',
    '[{"id":"A","text":"17","is_correct":false,"explanation":""},{"id":"B","text":"34","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":true,"explanation":""},{"id":"D","text":"72","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is calculated by multiplying its length and width.  In this case, the area is 12 meters * 5 meters = 60 square meters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_c98c7927fe878759_math_01002',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c1","opensat_index":1002}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  $3x + 2y = 12$ and $x - 2y = 4$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for $x$, we can add the two equations together. Notice that the $y$ terms cancel out: $(3x + 2y) + (x - 2y) = 12 + 4$, which simplifies to $4x = 16$. Dividing both sides by 4, we get $x = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'a1293ac5_math_01003',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"a1293ac5","opensat_index":1003}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people like apples, 40 people like oranges, and 20 people like both apples and oranges. How many people like only apples?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":true,"explanation":""},{"id":"B","text":"40","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":false,"explanation":""},{"id":"D","text":"80","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can use a Venn Diagram to represent the information given. \begin{align*} \text{People who like only apples} &= \text{People who like apples} - \text{People who like both apples and oranges} \\ &= 60 - 20\\ &= 40 \end{align*} Therefore, 40 people like only apples.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_9b91642bf82b1997_math_01004',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_a1","opensat_index":1004}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x + 2y = 5$ and $x - y = 2$, what is the value of $y$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":true,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can solve this system of equations by elimination. Adding the two equations together, we get  (x + 2y) + (x - y) = 5 + 2, or 2x + y = 7. Simplifying the first equation, we get x = 5 - 2y. Substituting this into the second equation, we get (5 - 2y) - y = 2, or 3y = 3. Therefore, y = 1.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_30015fdec3ac23d8_math_01005',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_c1","opensat_index":1005}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function \(f(x)\) is defined by \(f(x) = 2x - 3\). If \(f(a) = 11\), what is the value of \(a\)?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"7","is_correct":true,"explanation":""},{"id":"C","text":"11","is_correct":false,"explanation":""},{"id":"D","text":"17","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for a, we substitute 11 for f(a) in the equation f(x) = 2x - 3.  This gives us 11 = 2a - 3.  Adding 3 to both sides of the equation gives 14 = 2a.  Dividing both sides of the equation by 2 gives a = 7.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '432ef812_math_01006',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"432ef812","opensat_index":1006}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;