INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'If  $x + 3 = 7$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":true,"explanation":""},{"id":"B","text":"10","is_correct":false,"explanation":""},{"id":"C","text":"14","is_correct":false,"explanation":""},{"id":"D","text":"21","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To solve for $x$, we subtract 3 from both sides of the equation: $x + 3 - 3 = 7 - 3$.  This gives us $x = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_8689532986580b1d_math_00732',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_a1","opensat_index":732}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $\frac{2x + 3}{x - 7} = 5$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-16","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"16","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To solve for $x$, we first multiply both sides of the equation by $(x - 7)$: $2x + 3 = 5(x - 7)$. Expanding the right side, we get $2x + 3 = 5x - 35$. Subtracting $2x$ from both sides, we get $3 = 3x - 35$. Adding 35 to both sides, we get $38 = 3x$. Finally, dividing both sides by 3, we get $x = \frac{38}{3} = 12\frac{2}{3}$, which is not one of the given choices. Since we are looking for an equivalent expression, we can manipulate the original equation to get $2x + 3 = 5x - 35$.  Subtracting $2x$ and adding 35 to both sides, we get $38 = 3x$.  Finally, dividing both sides by 3, we get $x = \frac{38}{3} = 12\frac{2}{3}$. Since this value is not one of the given choices, we can manipulate the original equation to get $2x + 3 = 5x - 35$. Subtracting $2x$ and adding 35 to both sides, we get $38 = 3x$.  Finally, dividing both sides by 3, we get $x = \frac{38}{3} = 12\frac{2}{3}$.  Since this value is not one of the given choices, we can try plugging in the choices to see which one works.  Plugging in 16 for $x$ gives us $\frac{2(16) + 3}{16 - 7} = \frac{35}{9}$ which simplifies to 5.  Therefore, $x = 16$ is a solution to the equation.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_9dd1f91ea0a92dd3_math_00733',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c1","opensat_index":733}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $\frac{2x + 3}{x - 1} = 5$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for $x$, we begin by multiplying both sides of the equation by $(x - 1)$: $2x + 3 = 5(x - 1)$. Expanding the right side gives us $2x + 3 = 5x - 5$. Subtracting $2x$ from both sides and adding 5 to both sides, we get $8 = 3x$. Dividing both sides by 3, we obtain $x = \frac{8}{3}$, or $x = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_823e301b720c1cca_math_00734',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a3","opensat_index":734}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the solution to the equation $2x-3 = 15$?',
    'multiple_choice',
    '[{"id":"A","text":"6","is_correct":false,"explanation":""},{"id":"B","text":"9","is_correct":true,"explanation":""},{"id":"C","text":"12","is_correct":false,"explanation":""},{"id":"D","text":"18","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for $x$, we add 3 to both sides of the equation: $2x - 3 + 3 = 15 + 3$. This gives us $2x = 18$. Dividing both sides by 2, we get $x = 9$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '1d6df679_math_00735',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"1d6df679","opensat_index":735}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve for x by using elimination. Multiplying the second equation by 3, we get $3x - 3y = 3$.  Adding this equation to the first equation, we get $5x = 15$. Dividing both sides by 5, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_e6221a3b2ce7f33e_math_00736',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c1","opensat_index":736}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a diameter of 10.  What is the area of the circle, in terms of $\pi$?',
    'multiple_choice',
    '[{"id":"A","text":"5$\\pi$","is_correct":false,"explanation":""},{"id":"B","text":"10$\\pi$","is_correct":false,"explanation":""},{"id":"C","text":"25$\\pi$","is_correct":true,"explanation":""},{"id":"D","text":"100$\\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The radius of a circle is half its diameter.  So, the radius of this circle is 5.  The area of a circle is $\pi r^2$, so the area of this circle is $\pi (5)^2 = 25\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_9065319695adecab_math_00737',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c2","opensat_index":737}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of 10 friends are going to a concert.  They want to buy tickets in advance online, but there are only 6 tickets left.  What is the probability that all 10 friends will be able to get tickets?',
    'multiple_choice',
    '[{"id":"A","text":"0","is_correct":true,"explanation":""},{"id":"B","text":"1/10","is_correct":false,"explanation":""},{"id":"C","text":"1/6","is_correct":false,"explanation":""},{"id":"D","text":"1","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Since there are only 6 tickets left and 10 friends want tickets, it is impossible for all 10 friends to get tickets.  The probability of this event is 0.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_36571caa311dd484_math_00738',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c3","opensat_index":738}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm. What is the circumference of the circle, in terms of $\pi$?',
    'multiple_choice',
    '[{"id":"A","text":"$5 \\pi$","is_correct":false,"explanation":""},{"id":"B","text":"$10 \\pi$","is_correct":true,"explanation":""},{"id":"C","text":"$25 \\pi$","is_correct":false,"explanation":""},{"id":"D","text":"$100 \\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2 \pi r$, where $r$ is the radius.  Substituting 5 for $r$, we get $C = 2 \pi (5) = 10 \pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_33b0b450ca7798ab_math_00739',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c1","opensat_index":739}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x \neq 0$, what is the value of the expression $\frac{1}{x} + \frac{1}{x+1}$ expressed as a single fraction?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{1}{x(x+1)}$","is_correct":false,"explanation":""},{"id":"B","text":"$\\frac{2}{x(x+1)}$","is_correct":false,"explanation":""},{"id":"C","text":"$\\frac{2x+1}{x(x+1)}$","is_correct":true,"explanation":""},{"id":"D","text":"$\\frac{x+2}{x(x+1)}$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To add fractions, they must have a common denominator.  The least common denominator for $x$ and $x+1$ is $x(x+1)$.  Multiplying the first fraction by $\frac{x+1}{x+1}$ and the second fraction by $\frac{x}{x}$, we get: $\frac{1}{x} + \frac{1}{x+1} = \frac{1}{x} \cdot \frac{x+1}{x+1} + \frac{1}{x+1} \cdot \frac{x}{x} = \frac{x+1}{x(x+1)} + \frac{x}{x(x+1)}$.  Adding the numerators gives us $\frac{x+1 + x}{x(x+1)} = \frac{2x+1}{x(x+1)}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'd3897f3e_math_00740',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"d3897f3e","opensat_index":740}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a diameter of 10.  What is the circumference of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"5 \\pi","is_correct":false,"explanation":""},{"id":"B","text":"10 \\pi","is_correct":true,"explanation":""},{"id":"C","text":"25 \\pi","is_correct":false,"explanation":""},{"id":"D","text":"100 \\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula C = 2πr, where r is the radius of the circle. Since the diameter is 10, the radius is 5. Therefore, the circumference is C = 2π(5) = 10π.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '1f203579_math_00741',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"1f203579","opensat_index":741}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 4x + 3 = 0$, what is the sum of the solutions to the equation?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"7","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The sum of the roots of a quadratic equation in the form $ax^2 + bx + c = 0$ is given by $-b/a$.  In this equation, $a = 1$ and $b = -4$. Therefore, the sum of the roots is $-(-4)/1 = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_14856ffb9cc76516_math_00742',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a2","opensat_index":742}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve for x by using elimination.  Multiplying the second equation by 3, we get  $3x - 3y = 3$. Adding this equation to the first equation, we get $5x = 15$.  Dividing both sides by 5, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '98d37f8d_math_00743',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"98d37f8d","opensat_index":743}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 6x + 9 = 0$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"0","is_correct":false,"explanation":""},{"id":"D","text":"-9","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The given equation is a perfect square trinomial. It can be factored as $(x-3)^2 = 0$. Taking the square root of both sides gives $x-3 = 0$. Adding 3 to both sides, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'b7539c69_math_00744',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"b7539c69","opensat_index":744}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = 3x^2 - 5$. What is the value of $f(2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-11","is_correct":false,"explanation":""},{"id":"B","text":"-5","is_correct":false,"explanation":""},{"id":"C","text":"7","is_correct":true,"explanation":""},{"id":"D","text":"19","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find $f(2)$, we substitute 2 for $x$ in the function: $f(2) = 3(2)^2 - 5 = 3(4) - 5 = 12 - 5 = 7$. Therefore, $f(2) = 7$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_786d2485b03a397e_math_00745',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c9","opensat_index":745}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the solution to the equation $2x - 3 = 7$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":true,"explanation":""},{"id":"C","text":"7","is_correct":false,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for x, we first add 3 to both sides of the equation, which gives us $2x = 10$. Then, we divide both sides of the equation by 2, resulting in $x = 5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_7fe29a4ced35f705_math_00746',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c2","opensat_index":746}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the solution to the equation $2x + 5 = 17$?',
    'multiple_choice',
    '[{"id":"A","text":"-6","is_correct":false,"explanation":""},{"id":"B","text":"6","is_correct":true,"explanation":""},{"id":"C","text":"-11","is_correct":false,"explanation":""},{"id":"D","text":"11","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for x, we first subtract 5 from both sides of the equation: $2x + 5 - 5 = 17 - 5$, which simplifies to $2x = 12$.  Then we divide both sides of the equation by 2: $2x/2 = 12/2$, which gives us $x = 6$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_d02ccd2071e2322c_math_00747',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c1","opensat_index":747}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for $x$, we can use elimination.  Multiplying the second equation by 3, we get $3x - 3y = 3$. Adding this equation to the first equation, we get $5x = 15$, so $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_4fecd3de4e8efc65_math_00748',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a1","opensat_index":748}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people liked apples, 40 people liked oranges, and 20 people liked both apples and oranges. How many people liked neither apples nor oranges?',
    'multiple_choice',
    '[{"id":"A","text":"0","is_correct":false,"explanation":""},{"id":"B","text":"10","is_correct":false,"explanation":""},{"id":"C","text":"20","is_correct":true,"explanation":""},{"id":"D","text":"30","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can use a Venn diagram to solve this problem. Draw two overlapping circles, one for apples and one for oranges.  The overlap represents people who like both. Since 20 people liked both, we can fill in the overlap with 20. Since 60 people liked apples total, and 20 liked both, then 60-20 = 40 people liked only apples. Similarly, 40-20 = 20 people liked only oranges. This gives us a total of 40 + 20 + 20 = 80 people who liked at least one of the fruits.  Therefore, 100-80 = 20 people liked neither apples nor oranges.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '6a12b9d6_math_00749',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"6a12b9d6","opensat_index":749}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = 2x^2 - 5x + 3$. What is the value of $f(2)$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":true,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find the value of $f(2)$, we substitute 2 for $x$ in the function: $f(2) = 2(2)^2 - 5(2) + 3$.  Simplifying the expression, we get $f(2) = 8 - 10 + 3$, or $f(2) = 5$. ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'e8923ac1_math_00750',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"e8923ac1","opensat_index":750}'::jsonb
  ),
(
    gen_random_uuid(),
    'The circumference of a circle is $12 \pi$. What is the area of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"12\\pi","is_correct":false,"explanation":""},{"id":"B","text":"36\\pi","is_correct":true,"explanation":""},{"id":"C","text":"144\\pi","is_correct":false,"explanation":""},{"id":"D","text":"144","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius of the circle.  We are given that $C = 12\pi$, so we can solve for the radius: \begin{align*} 12\pi &= 2\pi r \\ \Rightarrow \qquad 6 &= r \end{align*} The area of a circle is given by the formula $A = \pi r^2$.  Substituting 6 for $r$ gives us $A = \pi (6)^2 = 36\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_0641090e44d66579_math_00751',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c4","opensat_index":751}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x + y = 5$ and $2x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for *x*, we can add the two equations together.  This eliminates *y* and gives us $3x = 6$.  Dividing both sides by 3, we get $x = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '82101135_math_00752',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"82101135","opensat_index":752}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a circumference of 12\pi. What is the radius of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"6","is_correct":true,"explanation":""},{"id":"C","text":"12","is_correct":false,"explanation":""},{"id":"D","text":"24","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula C = 2\pi r, where C is the circumference and r is the radius.  We are given that C = 12\pi. Substituting 12\pi for C in the formula gives 12\pi = 2\pi r.  Dividing both sides of this equation by 2\pi gives 6 = r. Therefore, the radius of the circle is 6.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '4534957f_math_00753',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"4534957f","opensat_index":753}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of friends are planning a trip. They decide to split the cost of the trip evenly.  The cost of the trip is \$1200. If there are 6 friends, how much will each friend pay?',
    'multiple_choice',
    '[{"id":"A","text":"$\\$100$","is_correct":false,"explanation":""},{"id":"B","text":"$\\$200$","is_correct":true,"explanation":""},{"id":"C","text":"$\\$300$","is_correct":false,"explanation":""},{"id":"D","text":"$\\$400$","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To find the cost per friend, divide the total cost of the trip by the number of friends: $\$1200 / 6 = \$200$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_0a3a8d0ee31ac0af_math_00754',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_b8","opensat_index":754}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = 2x^2 - 3x + 1$ is defined for all real numbers. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-17","is_correct":false,"explanation":""},{"id":"B","text":"-11","is_correct":false,"explanation":""},{"id":"C","text":"11","is_correct":false,"explanation":""},{"id":"D","text":"17","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substituting -2 for x in the function, we get: $f(-2) = 2(-2)^2 - 3(-2) + 1 = 8 + 6 + 1 = 15$. Therefore, the value of f(-2) is 15.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_eff9d3b51d04a2ec_math_00755',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c8","opensat_index":755}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has legs of length $12$ and $16$. What is the length of the hypotenuse of this triangle?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"20","is_correct":true,"explanation":""},{"id":"C","text":"28","is_correct":false,"explanation":""},{"id":"D","text":"40","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs.  In this case, the hypotenuse,  h, satisfies the equation $h^2 = 12^2 + 16^2 = 144 + 256 = 400$.  Therefore, the length of the hypotenuse is $h = \sqrt{400} = 20$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '2935a423_math_00756',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"2935a423","opensat_index":756}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;