INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'Which choice is the most effective way to correct the error in the sentence?',
    'multiple_choice',
    '[{"id":"A","text":"In the 1990s, the scientist discovered a new species of bacteria that live in the human gut. The scientists research, which was published in the journal Nature, showed that the bacteria played a critical role in maintaining the health of the human digestive system.","is_correct":false,"explanation":""},{"id":"B","text":"In the 1990s, the scientist discovered a new species of bacteria that live in the human gut. The scientist''s research, which was published in the journal Nature, showed that the bacteria played a critical role in maintaining the health of the human digestive system.","is_correct":true,"explanation":""},{"id":"C","text":"In the 1990s the scientist discovered a new species of bacteria that live in the human gut. The scientist’s research, which was published in the journal Nature, showed that the bacteria played a critical role in maintaining the health of the human digestive system.","is_correct":false,"explanation":""},{"id":"D","text":"In the 1990s the scientist discovered a new species of bacteria that live in the human gut, the scientist’s research, which was published in the journal Nature, showed that the bacteria played a critical role in maintaining the health of the human digestive system.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The error in the sentence is the lack of an apostrophe in the possessive noun "scientist''s." Choice B correctly adds the apostrophe to make the noun possessive.',
    'Review the passage and eliminate choices that contradict the text.',
    'In the 1990s, the scientist discovered a new species of bacteria that live in the human gut. The scientist’s research, which was published in the journal Nature, showed that the bacteria played a critical role in maintaining the health of the human digestive system. What is the most effective way to correct the error in the sentence?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_51fa1cdd843c8b6b_english_00975',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a1","opensat_index":975}'::jsonb
  ),
(
    gen_random_uuid(),
    'The phrase "no small feat" in this passage most likely serves to',
    'multiple_choice',
    '[{"id":"A","text":"highlight the speaker’s humility and respect for the subject.","is_correct":false,"explanation":""},{"id":"B","text":"emphasize the difficulty of the work being discussed.","is_correct":true,"explanation":""},{"id":"C","text":"suggest that the speaker is unsure of the work’s importance.","is_correct":false,"explanation":""},{"id":"D","text":"indicate that the speaker is concerned about the subject’s success.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The author uses the phrase "no small feat" to emphasize that the work being discussed is difficult. This suggests that the speaker is impressed by the work and wants the reader to be impressed as well.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author uses the phrase "no small feat" in this passage to emphasize the difficulty of the work being discussed. This suggests that the speaker is impressed by the work and that the speaker wants the reader to be impressed as well. What is the most likely reason why the author uses the phrase "no small feat" in this passage?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_2ef74c818cdd36f2_english_00976',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a1","opensat_index":976}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best completes the sentence with the most logical and precise word or phrase?',
    'multiple_choice',
    '[{"id":"A","text":"Stay a safe distance away, and observe the animal from afar.","is_correct":true,"explanation":""},{"id":"B","text":"Approach the animal cautiously, and try to interact with it.","is_correct":false,"explanation":""},{"id":"C","text":"Capture the animal and take it back to a ranger station.","is_correct":false,"explanation":""},{"id":"D","text":"Feed the animal and leave it food and water.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The best way to observe wildlife in a national park is to stay a safe distance away and observe the animal from afar. Approaching an animal can be dangerous for both the animal and the visitor. Capturing an animal is illegal and should only be done by park rangers. Feeding an animal is also illegal because it can disrupt the animal''s natural behavior.',
    'Review the passage and eliminate choices that contradict the text.',
    'When visiting a national park, it is essential to be prepared for a variety of weather conditions. Pack layers of clothing, rain gear, and sunscreen, regardless of the season. If you plan to hike, bring plenty of water and snacks. If you are going to camp, make sure you have a permit and familiarize yourself with the park’s rules and regulations.  Be sure to dispose of trash properly, leaving no trace of your presence.  What should you do if you see an animal in the park?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_f611f724dc97f93f_english_00977',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_e8","opensat_index":977}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best combines the sentences at the underlined portion so that it conforms to the conventions of Standard English?',
    'multiple_choice',
    '[{"id":"A","text":"innovative, using unconventional camera angles and lighting techniques.","is_correct":true,"explanation":""},{"id":"B","text":"innovative; using unconventional camera angles and lighting techniques.","is_correct":false,"explanation":""},{"id":"C","text":"innovative, using unconventional camera angles and lighting techniques, and","is_correct":false,"explanation":""},{"id":"D","text":"innovative; using unconventional camera angles and lighting techniques, he also","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The best option is A because it combines the two sentences with a comma and a comma plus a coordinating conjunction. Since both clauses could stand alone as complete sentences, this choice correctly links them together. This choice results in a correctly punctuated sentence.',
    'Review the passage and eliminate choices that contradict the text.',
    'The director’s approach to the film was innovative, he used unconventional camera angles and lighting techniques. He also incorporated elements of experimental film, such as surrealism and abstract imagery. This combination of traditional and experimental techniques was a unique, and ultimately successful, approach to filmmaking.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_c9f7fb0de32be0a2_english_00978',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"random_id_c5","opensat_index":978}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice provides the best way to combine the sentences in the underlined portion of the passage? ',
    'multiple_choice',
    '[{"id":"A","text":"Anya, whose name was eager to learn new strategies and techniques and hoped to contribute to the team’s success at upcoming tournaments.","is_correct":false,"explanation":""},{"id":"B","text":"Anya, whose name was, eager to learn new strategies and techniques, and she hoped to contribute to the team’s success at upcoming tournaments.","is_correct":false,"explanation":""},{"id":"C","text":"Anya, whose name was eager to learn new strategies and techniques, and she hoped to contribute to the team’s success at upcoming tournaments.","is_correct":false,"explanation":""},{"id":"D","text":"Anya, eager to learn new strategies and techniques, and she hoped to contribute to the team’s success at upcoming tournaments.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The best way to combine the sentences in the underlined portion is to remove the unnecessary phrase “whose name was” and to use a comma after “Anya” to introduce the two independent clauses. This creates a more concise and grammatically correct sentence.  Choice A is incorrect because the phrase “whose name was” is unnecessary and makes the sentence awkward. Choice B is incorrect because the comma after “techniques” is unnecessary. Choice C is incorrect because the comma after “techniques” is unnecessary and the phrase “whose name was” is unnecessary and makes the sentence awkward.',
    'Review the passage and eliminate choices that contradict the text.',
    'The new student, whose name was Anya, was excited to join the school’s debate team. She was eager to learn new strategies and techniques, and she hoped to contribute to the team’s success at upcoming tournaments. Anya was a quick learner, and she quickly mastered the art of persuasive argumentation.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_c987eb87d1075de7_english_00979',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_2","opensat_index":979}'::jsonb
  ),
(
    gen_random_uuid(),
    'The narrator feels',
    'multiple_choice',
    '[{"id":"A","text":"excited by the energy and stimulation of the city.","is_correct":false,"explanation":""},{"id":"B","text":"overwhelmed by the chaos and noise of the city.","is_correct":true,"explanation":""},{"id":"C","text":"happy to be living in a new and exciting place.","is_correct":false,"explanation":""},{"id":"D","text":"lonely and isolated in her new surroundings.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The passage describes the city as a chaotic and overwhelming place, and the narrator explicitly states that she missed the quiet of the country.  The phrase "overwhelmed by the rush of people and the constant movement" suggests that the narrator is feeling overwhelmed by the city, rather than excited or happy.',
    'Review the passage and eliminate choices that contradict the text.',
    'The narrator is a young girl who has just moved to the city with her family. She finds the city to be a very different place than the countryside she is used to.  "The sights and sounds of the city were a cacophony of noise and light.  I was overwhelmed by the rush of people and the constant movement.  I missed the quiet of the country, where I could hear the birds singing in the trees and the wind rustling through the leaves."  What is the main idea of this passage?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_de12fb4380c3266a_english_00980',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"random_id_english","opensat_index":980}'::jsonb
  ),
(
    gen_random_uuid(),
    'The most likely reason why the author uses a series of commas in this sentence is to ',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of emphasis and importance.","is_correct":false,"explanation":""},{"id":"B","text":"create a sense of rhythm and flow.","is_correct":true,"explanation":""},{"id":"C","text":"separate a list of items that are not related.","is_correct":false,"explanation":""},{"id":"D","text":"show that the sentence is complex and sophisticated.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The commas help to create a sense of rhythm and flow in the sentence, making it more pleasing to read. The author is using a series of commas to separate a list of words that describe the same thing, all of them aspects of the character’s personality.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author’s use of commas in this sentence separates a series of words that describe the same thing, all of them aspects of the character’s personality.  The commas help to create a sense of rhythm and flow in the sentence, making it more pleasing to read. What is the most likely reason why the author uses a series of commas in this sentence?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_d5474b8d5b8a681c_english_00981',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_e1","opensat_index":981}'::jsonb
  ),
(
    gen_random_uuid(),
    'The main idea of the text is that',
    'multiple_choice',
    '[{"id":"A","text":"the new type of research is more effective and reliable than traditional approaches.","is_correct":true,"explanation":""},{"id":"B","text":"the new type of imagery has been used successfully in research.","is_correct":false,"explanation":""},{"id":"C","text":"there are some who still dispute the accuracy of this new method.","is_correct":false,"explanation":""},{"id":"D","text":"the new type of research is more accurate and detailed than traditional methods.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The text describes the new research method in detail and then goes on to explain why it is more effective and reliable than previous approaches. The text acknowledges that some people still dispute the accuracy of the new method, but it ultimately suggests that the new method is more effective and reliable. Therefore, the main idea of the text is that the new type of research is more effective and reliable than traditional approaches.',
    'Review the passage and eliminate choices that contradict the text.',
    'The text is primarily concerned with describing the process of how a new kind of research has been developed. This research focuses on the use of a new type of imagery, which is thought to be able to provide a more accurate and detailed view of a phenomenon than traditional methods. Although the text acknowledges that there are some who still dispute the accuracy of this new method, it ultimately suggests that this new type of research is more effective and reliable than previous approaches. What is the main idea of the text?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    '647980b1_english_00982',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"647980b1","opensat_index":982}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author’s choice to avoid stating the point directly that the animals in the passage have features adapted to their environment is most likely due to',
    'multiple_choice',
    '[{"id":"A","text":"a desire to avoid stating the obvious.","is_correct":false,"explanation":""},{"id":"B","text":"a need to maintain a consistent tone and style throughout the passage.","is_correct":false,"explanation":""},{"id":"C","text":"a desire to emphasize the importance of the examples.","is_correct":false,"explanation":""},{"id":"D","text":"a need to create a more engaging and thought-provoking reading experience.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The author’s choice to avoid stating the point directly that the animals have features adapted to their environment is most likely due to a desire to create a more engaging and thought-provoking reading experience.  Instead of explicitly stating the point, the author allows the reader to make this inference on their own, which can make the passage more engaging and memorable.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author uses several examples of animals in the passage to illustrate the point that some of the animals’ most striking features are actually adaptations to their environment.  The author does not, however, directly state that point or use the word ‘adaptation.’  What is the most likely reason why the author makes this point indirectly?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_5105a2f11d690ebd_english_00983',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_c8","opensat_index":983}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author most likely includes information about the control group in this passage to',
    'multiple_choice',
    '[{"id":"A","text":"demonstrate that the new fertilizer is effective in promoting plant growth.","is_correct":false,"explanation":""},{"id":"B","text":"explain how the study was designed and conducted.","is_correct":false,"explanation":""},{"id":"C","text":"provide a basis for comparing the growth rates of the two groups of plants.","is_correct":true,"explanation":""},{"id":"D","text":"suggest that the new fertilizer may have unintended side effects.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The control group serves as a baseline for comparison, allowing the author to demonstrate the effectiveness of the new fertilizer by showing how the treatment group grew at a significantly faster rate than the control group. The control group provides a basis for comparing the growth rates of the two groups of plants.',
    'Review the passage and eliminate choices that contradict the text.',
    'The primary source of information in this passage is a study that was conducted to examine the effect of a new type of fertilizer on the growth rate of a certain type of plant.  The study involved two groups of plants: a control group and a treatment group. The control group was not given the new fertilizer, and the treatment group was given the new fertilizer. The study found that the plants in the treatment group grew at a significantly faster rate than the plants in the control group. Based on this information, the author concludes that the new fertilizer is effective in promoting plant growth. What is the most likely reason why the author includes information about the control group in this passage?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_d7fe8986bddd37d8_english_00984',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_d5","opensat_index":984}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the main point of the passage?',
    'multiple_choice',
    '[{"id":"A","text":"Historical fiction is a genre that helps readers understand their own lives.","is_correct":false,"explanation":""},{"id":"B","text":"Learning from the experiences of others is a key element of historical fiction.","is_correct":true,"explanation":""},{"id":"C","text":"Stories are a powerful way to learn about the past and present.","is_correct":false,"explanation":""},{"id":"D","text":"There are many different ways to learn about history.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The passage emphasizes the importance of stories in helping readers understand the lives and experiences of people in different times and places.  This is a central theme of historical fiction.',
    'Review the passage and eliminate choices that contradict the text.',
    'The idea that people can learn from the stories of others is a common one in literature.  This idea is especially prevalent in historical fiction, which often explores the lives and experiences of people in different times and places.  The author of this passage is most likely making the point that ______',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    '28f37645_english_00985',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"28f37645","opensat_index":985}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice corrects the error in the passage above?',
    'multiple_choice',
    '[{"id":"A","text":"“The new park,” the mayor announced, “is going to be the largest in the city.”","is_correct":true,"explanation":""},{"id":"B","text":"“The new park”, the mayor announced, “is going to be the largest in the city”.","is_correct":false,"explanation":""},{"id":"C","text":"“The new park” the mayor announced, “is going to be the largest in the city.”","is_correct":false,"explanation":""},{"id":"D","text":"“The new park”, the mayor announced, “is going to be the largest in the city.”","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The error in the passage is the lack of a comma after the introductory phrase "The new park."  A comma should be used after an introductory phrase that precedes a main clause.  Choice A correctly places a comma after the introductory phrase, while the other choices are incorrect.',
    'Review the passage and eliminate choices that contradict the text.',
    '“The new park”, the mayor announced, “is going to be the largest in the city.”',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_8e7d2392b9d80b11_english_00986',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_d5","opensat_index":986}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice most accurately summarizes the author’s main point in this passage?',
    'multiple_choice',
    '[{"id":"A","text":"The Third Wave, a predicted technological revolution, has failed to materialize in the way Alvin Toffler predicted.","is_correct":true,"explanation":""},{"id":"B","text":"The Third Wave, a concept popularized by Alvin Toffler, accurately predicted the impact of computers on modern society.","is_correct":false,"explanation":""},{"id":"C","text":"The Third Wave, a term that describes a cultural and technological revolution, was a significant concept in the 1960s.","is_correct":false,"explanation":""},{"id":"D","text":"The Third Wave, which has been popularized in recent decades, is a concept that accurately describes the impact of computers on modern society.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The passage states that some scholars question whether the Third Wave has occurred in the way that Toffler predicted, suggesting that the predicted revolution has not materialized. Therefore, choice A is the most accurate summary of the passage’s main point.',
    'Review the passage and eliminate choices that contradict the text.',
    'In the 1960s, the concept of "The Third Wave" emerged, describing a wave of change that was supposed to be a cultural and technological revolution. Alvin Toffler, the author of *Future Shock*, popularized this idea.  Toffler argued that the new technologies, particularly those involving computers, would have a profound impact on how we live, work, and think.   As we approach the end of the second decade of the 21st century, however, some scholars have begun to question whether this revolution has actually occurred.',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_b79bb56f3e17a23b_english_00987',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_e4","opensat_index":987}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following revisions to the underlined portion of the passage is most accurate and grammatically correct?',
    'multiple_choice',
    '[{"id":"A","text":"a change that was designed to boost morale and productivity, and  she also explained that the policy would be phased in over the next quarter, giving employees time to adjust to the new guidelines.","is_correct":false,"explanation":""},{"id":"B","text":"a change that was designed to boost morale and productivity, and  she also explained that the policy would be phased in over the next quarter, giving employees time to adjust to the new guidelines.","is_correct":false,"explanation":""},{"id":"C","text":"a change designed to boost morale and productivity, and she also explained that the policy would be phased in over the next quarter, giving employees time to adjust to the new guidelines.","is_correct":true,"explanation":""},{"id":"D","text":"a change designed to boost morale and productivity, and she also explained that the policy would be phased in over the next quarter, giving employees time to adjust to the new guidelines.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The most accurate and grammatically correct revision is to remove the unnecessary word “that” and the comma that follows it.  The phrase “a change designed to boost morale and productivity” is a nonessential modifying phrase that is correctly set off from the rest of the sentence by a comma.  The phrase “and she also explained” is redundant because the second clause in the sentence already implies that the CEO explained the policy. The phrase “giving employees time to adjust to the new guidelines” is a nonessential modifying phrase that is correctly set off from the rest of the sentence by a comma.',
    'Review the passage and eliminate choices that contradict the text.',
    'The new CEO announced that she would be implementing  a new policy to encourage employees to use their vacation time,  a change that was designed to boost morale and productivity.  She also explained that  the policy  would  be  phased  in  over the next quarter,  giving  employees  time to adjust to the new guidelines.  She  believes  that  the  policy  will  have  a  positive impact on  employee  well-being,  and  improve  the company’s overall performance.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_a32dd0c9a9fcba74_english_00988',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_english_5","opensat_index":988}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author''s use of a personal anecdote in the second paragraph serves primarily to',
    'multiple_choice',
    '[{"id":"A","text":"provide a humorous and entertaining digression.","is_correct":false,"explanation":""},{"id":"B","text":"establish the writer’s credibility as an expert.","is_correct":false,"explanation":""},{"id":"C","text":"illustrate the importance of the main topic of the essay.","is_correct":true,"explanation":""},{"id":"D","text":"introduce the author’s background and life experiences.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The personal anecdote is used to illustrate the main topic of the essay, which is the importance of self-reflection. The author uses the anecdote to show how self-reflection helped them overcome a challenging experience, making the point more relatable and understandable for the reader.',
    'Review the passage and eliminate choices that contradict the text.',
    'The first paragraph of this passage introduces the main topic of the essay, which is the importance of self-reflection. The author then provides a personal anecdote to illustrate this point, describing how they learned the value of self-reflection through a challenging experience. The author then concludes by suggesting that self-reflection is a skill that can be cultivated and that it can lead to a more fulfilling life. What is the most likely reason the writer uses a personal anecdote to illustrate their point?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '2f119146_english_00989',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"2f119146","opensat_index":989}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author uses the phrase "overly simplistic" to suggest that',
    'multiple_choice',
    '[{"id":"A","text":"language is not as important as other factors in understanding a culture.","is_correct":false,"explanation":""},{"id":"B","text":"understanding a culture is a simple and straightforward process.","is_correct":false,"explanation":""},{"id":"C","text":"language is a more important factor in understanding a culture than history, geography, or social customs.","is_correct":false,"explanation":""},{"id":"D","text":"the assertion that the best way to understand a culture is to learn its language is an inaccurate generalization.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The author argues that while language is important, it is not the only factor that shapes a culture. Therefore, the statement that understanding a culture is best achieved by learning its language is too simple and ignores the complexity of cultural identity. The author uses the phrase "overly simplistic" to highlight this oversimplification.',
    'Review the passage and eliminate choices that contradict the text.',
    'It is often said that the best way to understand a culture is to learn its language. However, this assertion is overly simplistic. While language certainly plays a role in shaping culture, it is only one piece of the puzzle. Other factors, such as history, geography, and social customs, also contribute to the tapestry of a culture. To ignore these other elements is to reduce a complex and multifaceted phenomenon to a single, easily digestible element. Thus, while language is undeniably important, it is not the sole key to unlocking the secrets of a culture.',
    'passage',
    'reading_writing',
    'Expression of Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Expression of Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Expression of Ideas']::text[],
    'c82f3c17_english_00990',
    'college_board_opensat',
    '{"opensat_domain":"Expression of Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"c82f3c17","opensat_index":990}'::jsonb
  ),
(
    gen_random_uuid(),
    'The writer most likely includes the example of a common stress reliever before discussing mindfulness in order to',
    'multiple_choice',
    '[{"id":"A","text":"demonstrate that mindfulness is a more effective stress reliever than other common stress relievers.","is_correct":false,"explanation":""},{"id":"B","text":"provide a context for the reader to understand how mindfulness can be used to reduce stress.","is_correct":true,"explanation":""},{"id":"C","text":"explain why mindfulness is becoming increasingly popular as a way to reduce stress.","is_correct":false,"explanation":""},{"id":"D","text":"contrast mindfulness with other common stress relievers.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The example of a common stress reliever helps the reader understand that mindfulness is a type of stress reliever. This context makes it easier for the reader to understand how mindfulness can be used to reduce stress. ',
    'Review the passage and eliminate choices that contradict the text.',
    'The introduction of this text establishes that people are constantly looking for new ways to reduce stress. After a general statement about the prevalence of stress, the text gives an example of a common stress reliever. Then, the text shifts to a more specific discussion about one particular stress reliever: mindfulness. The text discusses mindfulness as a technique that is gaining popularity and provides details about how it works. What is the most likely reason that the writer includes an example of a common stress reliever before discussing mindfulness?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_c7afe67929f642d7_english_00991',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_d3","opensat_index":991}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following sentences from the memoir is most effective at accomplishing this goal?',
    'multiple_choice',
    '[{"id":"A","text":"The train inched across the bridge, its wheels groaning slowly against the steel.","is_correct":true,"explanation":""},{"id":"B","text":"The train moved slowly across the bridge, its progress punctuated by the rhythmic clang of the wheels.","is_correct":false,"explanation":""},{"id":"C","text":"As the train crossed the bridge, it seemed to be moving at a snail’s pace.","is_correct":false,"explanation":""},{"id":"D","text":"The train was moving slowly across the bridge, but it seemed to be moving quickly.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Choice A uses the verb "inched" to create a sense of slow, deliberate movement. The phrase "its wheels groaning slowly against the steel" adds to the sense of anticipation and suspense by creating a more vivid and sensory image of the train’s progress. Choices B and C use less vivid language and don’t create the same sense of slowness. Choice D is incorrect because the sentence describes a contradiction, which is illogical in this context.',
    'Review the passage and eliminate choices that contradict the text.',
    'The writer of a memoir is describing an event where a train is traveling across a bridge. The writer wants to emphasize how slowly the train was moving in order to create a sense of anticipation and suspense for the reader.  Which of the following sentences from the memoir is most effective at accomplishing this goal?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '3452f782_english_00992',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"3452f782","opensat_index":992}'::jsonb
  ),
(
    gen_random_uuid(),
    'The example of the painting of a man holding a glass of wine is most likely used to illustrate the idea that',
    'multiple_choice',
    '[{"id":"A","text":"artistic taste is subjective and influenced by individual experience.","is_correct":true,"explanation":""},{"id":"B","text":"the details of a work of art can reveal the artist’s intentions.","is_correct":false,"explanation":""},{"id":"C","text":"the meaning of a work of art can be interpreted in multiple ways.","is_correct":false,"explanation":""},{"id":"D","text":"the value of a work of art is determined by its historical context.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The author describes how the painting can be interpreted in two different ways, depending on the individual’s experiences and perspective. This suggests that the author wants to make the point that artistic taste is subjective and influenced by individual experience. The other choices are not supported by the text.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author suggests that the way in which we perceive a work of art is influenced by our knowledge of the world. The author provides the example of a painting of a man holding a glass of wine. Some people, the author suggests, might find the painting to be elegant and refined, while others might find it to be mundane and common. What is the most likely reason why the author offers this example?',
    'passage',
    'reading_writing',
    'Expression of Ideas',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Expression of Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Expression of Ideas']::text[],
    '57dbb694_english_00993',
    'college_board_opensat',
    '{"opensat_domain":"Expression of Ideas","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"57dbb694","opensat_index":993}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best maintains the parallel structure of the sentence?',
    'multiple_choice',
    '[{"id":"A","text":"a move that will provide the community with a much needed space for recreation, and for relaxation.","is_correct":false,"explanation":""},{"id":"B","text":"a move that will provide the community with a much needed space for recreation, and to relax.","is_correct":false,"explanation":""},{"id":"C","text":"a move that will provide the community with a much needed space for recreation and to relax.","is_correct":false,"explanation":""},{"id":"D","text":"a move that will provide the community with a much needed space for recreation and relaxation.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The original sentence uses parallel structure by using the prepositional phrase “for recreation” and the noun “relaxation.”  The only choice that maintains this parallel structure is choice D, which also uses a prepositional phrase (“for recreation”) and a noun (“relaxation”).',
    'Review the passage and eliminate choices that contradict the text.',
    'The city council approved a plan to install a new public park in the neighborhood, a move that will provide the community with a much needed space for recreation and relaxation.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_852a7da31338fdc3_english_00994',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"random_id_e8","opensat_index":994}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which sentence in this paragraph best represents the author’s commitment to accuracy and informativeness?',
    'multiple_choice',
    '[{"id":"A","text":"The author is working on a new book about the history of the American West.","is_correct":false,"explanation":""},{"id":"B","text":"The author has also been reading a variety of books and articles on the subject, and the author has been visiting historical sites in the West.","is_correct":false,"explanation":""},{"id":"C","text":"The author is eager to make the book as accurate and informative as possible.","is_correct":true,"explanation":""},{"id":"D","text":"As part of the research, the author has been interviewing various experts, including historians and anthropologists.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The sentence "The author is eager to make the book as accurate and informative as possible." best represents the author’s commitment to accuracy and informativeness.  The sentence states that the author is making accuracy and informativeness a priority in the writing of the book.  The other sentences are more about the author’s research process. ',
    'Review the passage and eliminate choices that contradict the text.',
    'The author is working on a new book about the history of the American West.  As part of the research, the author has been interviewing various experts, including historians and anthropologists.  The author has also been reading a variety of books and articles on the subject, and the author has been visiting historical sites in the West. The author is eager to make the book as accurate and informative as possible.  Which sentence in this paragraph best represents the author’s commitment to accuracy and informativeness?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_40f53d85d2f405b3_english_00995',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"random_id_c1","opensat_index":995}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following changes to the text would improve its clarity and conciseness?',
    'multiple_choice',
    '[{"id":"A","text":"Change \"I want to be more than just a pretty face\" to \"I want to be more than a pretty face.\"","is_correct":false,"explanation":""},{"id":"B","text":"Change \"I’m not going to give up\" to \"I won’t give up.\"","is_correct":true,"explanation":""},{"id":"C","text":"Remove the sentence \"I’m not sure what I’m good at, or what I’m meant to be.\"","is_correct":false,"explanation":""},{"id":"D","text":"Change \"I’m going to keep searching until I find my way\" to \"I’ll keep searching until I find my way.\"","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Choice B improves the clarity and conciseness of the text by replacing the informal contraction "I’m" with the more formal and concise "I won’t." The other choices do not improve the clarity or conciseness of the text.',
    'Review the passage and eliminate choices that contradict the text.',
    'The following text is from a novel about a young woman who is trying to find her place in the world.  "I want to be more than just a pretty face, but I don’t know how to do that.  I feel like I’m stuck in a rut.  I’m not sure what I’m good at, or what I’m meant to be.  But I’m not going to give up.  I’m going to keep searching until I find my way."',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_0718cf8f0b6474eb_english_00996',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a1","opensat_index":996}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best describes the function of the underlined sentence in the text as a whole?',
    'multiple_choice',
    '[{"id":"A","text":"It establishes that a character is experiencing an internal conflict.","is_correct":false,"explanation":""},{"id":"B","text":"It introduces a problem that is examined in the text.","is_correct":true,"explanation":""},{"id":"C","text":"It makes a claim that is challenged in the text.","is_correct":false,"explanation":""},{"id":"D","text":"It presents a hypothesis that is evaluated in the text.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The underlined sentence introduces the problem of drowsy driving, which is examined in the rest of the passage. The passage goes on to describe the dangers of driving while drowsy, including the driver’s inability to stay awake and the fact that drowsy driving can be dangerous. Therefore, the function of the underlined sentence is to introduce a problem that is examined in the text.',
    'Review the passage and eliminate choices that contradict the text.',
    'The first sentence of this passage introduces the main topic, which is the dangers of driving while drowsy. The second sentence provides a specific example of the dangers of driving while drowsy, which is the driver’s inability to stay awake. The final sentence states that drowsy driving can be dangerous, but the passage doesn’t provide any specific details about the dangers. What is the main idea of this passage?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '765eb62e_english_00997',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"765eb62e","opensat_index":997}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the word "you" is used to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of intimacy and connection with the reader.","is_correct":true,"explanation":""},{"id":"B","text":"describe the speaker’s feelings and experiences.","is_correct":false,"explanation":""},{"id":"C","text":"emphasize the importance of the speaker’s message.","is_correct":false,"explanation":""},{"id":"D","text":"suggest that the speaker is addressing a large audience.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The speaker is addressing the reader directly by using the word "you." This creates a sense of intimacy and connection with the reader, which can help the reader feel more engaged with the message.',
    'Review the passage and eliminate choices that contradict the text.',
    'The most obvious sign that the speaker is speaking directly to the reader is the use of the word "you." There are other elements of the passage that may help to make the speaker seem more immediate and personal. The speaker refers to events and places that are familiar to the reader, and the speaker uses a conversational tone throughout the passage. What is the most likely reason why the writer uses the word "you"?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'f54c918d_english_00998',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"f54c918d","opensat_index":998}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice completes the text so that it conforms to the conventions of Standard English?',
    'multiple_choice',
    '[{"id":"A","text":"involves","is_correct":true,"explanation":""},{"id":"B","text":"involving","is_correct":false,"explanation":""},{"id":"C","text":"involved","is_correct":false,"explanation":""},{"id":"D","text":"to involve","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The correct answer is "involves." The sentence requires a finite verb to modify the noun phrase "the scientist’s research." The participle "involving" would be incorrect because it''s a nonfinite verb. The past participle "involved" would be incorrect because it suggests the action has already been completed. "To involve" would be incorrect because it''s a nonfinite to-infinitive.  Of these choices, only the present tense verb "involves" makes sense in the context.',
    'Review the passage and eliminate choices that contradict the text.',
    'The scientist''s research, which is focused on the impact of climate change on coral reefs, ______ a variety of complex factors.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_4aa740b4c77b5a02_english_00999',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_c1","opensat_index":999}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;