INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'The use of the word "we" in this passage is likely intended to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of intimacy and connection with the reader.","is_correct":false,"explanation":""},{"id":"B","text":"establish a sense of shared experience and commonality.","is_correct":true,"explanation":""},{"id":"C","text":"highlight the speaker''s unique perspective.","is_correct":false,"explanation":""},{"id":"D","text":"emphasize the importance of the speaker''s message.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The use of the word "we" in this passage is most likely intended to create a sense of shared experience and commonality. By using the word "we," the speaker is suggesting that they are speaking on behalf of a larger group of people, which can make the message feel more inclusive and persuasive.',
    'Review the passage and eliminate choices that contradict the text.',
    'The writer of the poem is most likely speaking to a large group of people, as indicated by the use of "we." Also, the poem’s use of words like "all" and "each" suggests that the speaker is trying to make a general statement rather than a specific one. What is the most likely reason why the poet chooses the word "we" in this passage?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '8d8298df_english_01175',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"8d8298df","opensat_index":1175}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author’s description of the “dark, empty halls” and the “silent, empty rooms” is primarily intended to',
    'multiple_choice',
    '[{"id":"A","text":"evoke the speaker’s sense of loneliness and despair.","is_correct":true,"explanation":""},{"id":"B","text":"create a sense of mystery and suspense.","is_correct":false,"explanation":""},{"id":"C","text":"highlight the physical surroundings of the speaker’s home.","is_correct":false,"explanation":""},{"id":"D","text":"emphasize the speaker’s sense of power and authority.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The description of the “dark, empty halls” and the “silent, empty rooms” creates a vivid image of a lonely and desolate space. This imagery evokes a sense of loneliness and despair, which contributes to the overall sense of isolation and alienation that the author conveys about the speaker.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author uses various literary devices in the passage to create a sense of the speaker''s isolation and alienation. One of these devices is the use of imagery, such as the description of the “dark, empty halls” and the “silent, empty rooms.” The author also uses figurative language, such as the metaphor of the “shadow” that “followed” the speaker, which suggests that the speaker’s isolation is pervasive and inescapable. What is the purpose of the author’s description of the “dark, empty halls” and the “silent, empty rooms?”',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_8522f290cc2bbe5d_english_01176',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_c3","opensat_index":1176}'::jsonb
  ),
(
    gen_random_uuid(),
    'How does the essay progress?',
    'multiple_choice',
    '[{"id":"A","text":"It moves from a personal anecdote to a more general discussion of a cultural tradition.","is_correct":true,"explanation":""},{"id":"B","text":"It presents a problem and then offers a solution.","is_correct":false,"explanation":""},{"id":"C","text":"It compares and contrasts two different perspectives on a particular subject.","is_correct":false,"explanation":""},{"id":"D","text":"It explains the steps involved in a specific process.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The essay starts with a personal anecdote about the speaker’s family’s tradition of making pies. The speaker then moves to a more general discussion of the importance of pie in their culture. This structure is common in essays that start with a personal experience and then broaden the scope to discuss a larger cultural or societal issue.',
    'Review the passage and eliminate choices that contradict the text.',
    'The essay begins with the speaker reminiscing about their family’s tradition of making summer pies. The author moves from a memory of making pies with their grandmother to discussing the importance of pie in their culture. The speaker then notes that the recipe for the pies is not a simple set of instructions but rather a guide that requires intuition and experience. Which choice best describes how the essay develops?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '472c409e_english_01177',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"472c409e","opensat_index":1177}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the main idea of the passage?',
    'multiple_choice',
    '[{"id":"A","text":"Electronic music has evolved significantly since its inception, with advancements in technology leading to new possibilities for sound creation.","is_correct":true,"explanation":""},{"id":"B","text":"The theremin was the first electronic instrument and played a crucial role in the development of electronic music.","is_correct":false,"explanation":""},{"id":"C","text":"Analog synthesizers allowed musicians to manipulate sound in ways that were previously impossible, but digital audio workstations have since surpassed their capabilities.","is_correct":false,"explanation":""},{"id":"D","text":"Personal computers have made music production more accessible and affordable, leading to a democratization of the music industry.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The passage describes the evolution of electronic music, highlighting the key innovations that have shaped its development. It starts with the origins of electronic music and then discusses the impact of analog synthesizers and digital audio workstations on the genre.',
    'Review the passage and eliminate choices that contradict the text.',
    'The following passage is from a news article about the history of music. The article discusses the origins of electronic music, the role of analog synthesizers, and the transition to digital music production.  "Electronic music, a genre characterized by the use of electronic instruments and technology, has its roots in the early 20th century with the invention of the theremin, a device that produces sound by controlling an electromagnetic field.  However, the real development of electronic music began in the 1960s, when analog synthesizers became widely available. These synthesizers, which used electrical signals to create sound, allowed musicians to manipulate sound in ways that were previously impossible.   The advent of personal computers in the 1980s revolutionized music production, as digital audio workstations (DAWs) replaced analog equipment. DAWs allowed musicians to record, edit, and mix music in ways that were more flexible, efficient, and precise. "',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_89f1d9e1ded9dec6_english_01178',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_e1","opensat_index":1178}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author most likely structures the passage in this way to',
    'multiple_choice',
    '[{"id":"A","text":"present a balanced view of the technology by highlighting both its positive and negative aspects.","is_correct":true,"explanation":""},{"id":"B","text":"explain the history of the technology and its development over time.","is_correct":false,"explanation":""},{"id":"C","text":"convince the reader that the technology should be used with caution.","is_correct":false,"explanation":""},{"id":"D","text":"persuade the reader to invest in the technology.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The author presents both the benefits and risks of the technology, creating a balanced view and allowing the reader to make an informed decision.',
    'Review the passage and eliminate choices that contradict the text.',
    'In the first paragraph, the author discusses the benefits of using a particular technology. The second paragraph provides a warning about the potential risks associated with using the technology. What is the most likely reason the author structures the passage in this way?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_b34ba5440f5bc6ed_english_01179',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_c5","opensat_index":1179}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the use of short sentences is most likely meant to',
    'multiple_choice',
    '[{"id":"A","text":"emphasize the speaker''s confidence.","is_correct":true,"explanation":""},{"id":"B","text":"create a sense of urgency.","is_correct":false,"explanation":""},{"id":"C","text":"highlight the speaker''s humor.","is_correct":false,"explanation":""},{"id":"D","text":"show the speaker''s lack of knowledge.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Short sentences are often used to create a sense of immediacy and urgency.  In this case, the speaker is using short sentences to emphasize her confidence.',
    'Review the passage and eliminate choices that contradict the text.',
    'The speaker is addressing a group of people that she knows well.  This is evident in the way she uses the word "you" and other elements of the passage.  The speaker is also confident and self-assured.  What is the most likely reason why the writer uses a lot of short sentences in this passage?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'b577194d_english_01180',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"b577194d","opensat_index":1180}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author focuses on the effect of the world’s increasing interconnectedness on how people live because',
    'multiple_choice',
    '[{"id":"A","text":"the author is arguing that the world has become more complex and challenging to live in.","is_correct":true,"explanation":""},{"id":"B","text":"the author is arguing that the world has become more exciting and rewarding to live in.","is_correct":false,"explanation":""},{"id":"C","text":"the author wants to emphasize the ways in which the world is becoming more interconnected.","is_correct":false,"explanation":""},{"id":"D","text":"the author wants to illustrate the ways in which the world is becoming more complex and challenging to live in.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The author’s main argument is that the world is a more interconnected place than it was before, and the author concludes by arguing that these changes have made the world a more complex and challenging place to live in, but also a more exciting and rewarding one. The author focuses on the effect of the world’s increasing interconnectedness on how people live because the author is arguing that the world has become more complex and challenging to live in.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author’s central argument is that the world is a more interconnected place than it was before, citing advances in technology, communication, and transportation as evidence. The author uses several examples to illustrate the ways in which the world is becoming more interconnected, such as the growth of the internet and the increase in international travel. The author concludes by arguing that these changes have made the world a more complex and challenging place to live in, but also a more exciting and rewarding one. What is the most likely reason why the author focuses on the effects of these changes on how people live?',
    'passage',
    'reading_writing',
    'Expression of Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Expression of Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Expression of Ideas']::text[],
    'opensat_2e7adddccf007f19_english_01181',
    'college_board_opensat',
    '{"opensat_domain":"Expression of Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_c3","opensat_index":1181}'::jsonb
  ),
(
    gen_random_uuid(),
    'By using the phrase "a different kind of power," the author is most likely trying to',
    'multiple_choice',
    '[{"id":"A","text":"suggest that storytelling is a more powerful tool than other forms of communication.","is_correct":false,"explanation":""},{"id":"B","text":"argue that storytelling can be used to achieve positive social change.","is_correct":false,"explanation":""},{"id":"C","text":"emphasize the unique and transformative nature of storytelling.","is_correct":true,"explanation":""},{"id":"D","text":"explain how storytelling can be used to inspire empathy and compassion.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The author is suggesting that storytelling has a unique and transformative power that sets it apart from other forms of communication. The phrase "a different kind of power" emphasizes that storytelling can create change, inspire understanding, and challenge the status quo in ways that other forms of communication cannot.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author uses the phrase "a different kind of power" to describe the power of storytelling.  The author suggests that storytelling is a powerful tool that can be used to connect people, inspire change, and create understanding.  The author also suggests that storytelling can be used to challenge the status quo and to make people think differently about the world.   What is the author''s purpose in using this phrase?',
    'passage',
    'reading_writing',
    'Expression of Ideas',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Expression of Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Expression of Ideas']::text[],
    'a8d4f72c_english_01182',
    'college_board_opensat',
    '{"opensat_domain":"Expression of Ideas","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"a8d4f72c","opensat_index":1182}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice most effectively combines the sentences at the underlined portion?',
    'multiple_choice',
    '[{"id":"A","text":"The *Architeuthis dux*, a type of squid, is characterized by its enormous size, and it can reach a length of up to 60 feet. These findings, scientists believe, will lead to further research into the social behavior of this fascinating creature.","is_correct":true,"explanation":""},{"id":"B","text":"The *Architeuthis dux*, which is a type of squid, is characterized by its enormous size, and it can reach a length of up to 60 feet. These findings, scientists believe, will lead to further research into the social behavior of this fascinating creature.","is_correct":false,"explanation":""},{"id":"C","text":"The *Architeuthis dux*, a type of squid, is characterized by its enormous size, and can reach a length of up to 60 feet. These findings, scientists believe, will lead to further research into the social behavior of this fascinating creature.","is_correct":false,"explanation":""},{"id":"D","text":"The *Architeuthis dux*, a type of squid, is characterized by its enormous size, and can reach a length of up to 60 feet. These findings, scientists believe, will lead to further research into the social behavior of this fascinating creature.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The best way to combine the sentences is to use a comma after the word "size" and to add the conjunction "and" to the second sentence. This creates a grammatically correct sentence and maintains the flow of the passage.',
    'Review the passage and eliminate choices that contradict the text.',
    'The recent discovery of a previously unknown species of deep-sea fish, the *Architeuthis dux*, has sent shockwaves through the scientific community. Scientists had long believed that the *Architeuthis dux* was a solitary creature, but the new findings suggest that it may be a social animal. The *Architeuthis dux*, which is a type of squid, is characterized by its enormous size, and can reach a length of up to 60 feet.  These findings, scientists believe, will lead to further research into the social behavior of this fascinating creature.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '119b489c_english_01183',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"119b489c","opensat_index":1183}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice correctly revises the sentence to conform to the conventions of Standard English?',
    'multiple_choice',
    '[{"id":"A","text":"Austen was a prolific writer, she published six novels in her lifetime.","is_correct":false,"explanation":""},{"id":"B","text":"Austen was a prolific writer, publishing six novels in her lifetime.","is_correct":true,"explanation":""},{"id":"C","text":"Austen was a prolific writer; she published six novels in her lifetime.","is_correct":false,"explanation":""},{"id":"D","text":"Austen was a prolific writer, she published six novels, in her lifetime.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The sentence is a comma splice because it combines two independent clauses with only a comma.  The correct way to combine two independent clauses is to use a comma and a coordinating conjunction.  Choice B is the only option that does this.  Choice A is incorrect because the comma does not connect two independent clauses properly.  Choice C is incorrect because the semicolon is not the correct punctuation to connect two independent clauses. Choice D is incorrect because the comma is not the correct punctuation to connect two independent clauses.',
    'Review the passage and eliminate choices that contradict the text.',
    'A group of students are working on a project for their English class. They need to research and write a report on a famous author. They decide to write about Jane Austen.  One student writes the following sentence in their report: "Austen was a prolific writer, she published six novels in her lifetime."',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'f8767a8f_english_01184',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"f8767a8f","opensat_index":1184}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the word "you" is used to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of intimacy and connection with the reader.","is_correct":true,"explanation":""},{"id":"B","text":"describe the speaker’s feelings and experiences.","is_correct":false,"explanation":""},{"id":"C","text":"emphasize the importance of the speaker’s message.","is_correct":false,"explanation":""},{"id":"D","text":"suggest that the speaker is addressing a large audience.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The speaker is addressing the reader directly by using the word "you." This creates a sense of intimacy and connection with the reader, which can help the reader feel more engaged with the message.',
    'Review the passage and eliminate choices that contradict the text.',
    'The most obvious sign that the speaker is speaking directly to the reader is the use of the word "you." There are other elements of the passage that may help to make the speaker seem more immediate and personal. The speaker refers to events and places that are familiar to the reader, and the speaker uses a conversational tone throughout the passage. What is the most likely reason why the writer uses the word "you"?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_0c55a14f5752ca1b_english_01185',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"random_id_e6","opensat_index":1185}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best completes the sentence with correct punctuation?',
    'multiple_choice',
    '[{"id":"A","text":"Their findings, which have been well-received by the scientific community.","is_correct":true,"explanation":""},{"id":"B","text":"Their findings which have been well-received by the scientific community.","is_correct":false,"explanation":""},{"id":"C","text":"Their findings; which have been well-received by the scientific community.","is_correct":false,"explanation":""},{"id":"D","text":"Their findings, which have been well-received by the scientific community;","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The sentence is a complex sentence with a nonrestrictive clause.  Nonrestrictive clauses are set off with commas. The sentence should read: "The research team has published several papers on their findings, which have been well-received by the scientific community."',
    'Review the passage and eliminate choices that contradict the text.',
    'The scientists who discovered the new species of bacteria are all graduates of the same university.  They are conducting a long-term study of the bacteria’s effects on the environment. The research team has published several papers on their findings, which have been well-received by the scientific community.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_e2b4f98621f5b426_english_01186',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a5","opensat_index":1186}'::jsonb
  ),
(
    gen_random_uuid(),
    'The underlined sentence in the passage functions to',
    'multiple_choice',
    '[{"id":"A","text":"offer evidence to support a previous claim.","is_correct":false,"explanation":""},{"id":"B","text":"introduce a comparison between two related ideas.","is_correct":true,"explanation":""},{"id":"C","text":"describe the similarities between the Arctic and Antarctica.","is_correct":false,"explanation":""},{"id":"D","text":"explain why the two regions are so different.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The underlined sentence introduces a comparison between the Arctic and Antarctica, highlighting that they are similar in some ways despite their differences. This comparison helps to emphasize the main point of the passage: that while the Arctic and Antarctica are different, they also share some similarities.',
    'Review the passage and eliminate choices that contradict the text.',
    'I have never been to the Arctic, but I have been to Antarctica. You could call the Arctic the "top" of the world and Antarctica the "bottom." The Arctic is a frozen ocean surrounded by land, while Antarctica is a continent of land surrounded by ocean. Although the two regions are very different, they are similar in some ways. In both regions, the temperatures are extremely cold, the winters are long and dark, and the landscapes are vast and breathtakingly beautiful. Both regions are also home to unique ecosystems and wildlife. What is the function of the underlined sentence in the passage?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '47f6c5d4_english_01187',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"47f6c5d4","opensat_index":1187}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice most effectively combines the sentences at the underlined portion?',
    'multiple_choice',
    '[{"id":"A","text":"Her long hair cascaded down her back, framing her face, and her eyes were bright with intelligence, making her appear almost ethereal.","is_correct":true,"explanation":""},{"id":"B","text":"Her long hair cascaded down her back, framing her face, and her eyes were bright with intelligence; she was wearing a simple white dress that flowed gracefully around her, making her appear almost ethereal.","is_correct":false,"explanation":""},{"id":"C","text":"Her long hair cascaded down her back, framing her face, and her eyes were bright with intelligence, she was wearing a simple white dress that flowed gracefully around her, making her appear almost ethereal.","is_correct":false,"explanation":""},{"id":"D","text":"Her long hair cascaded down her back, framing her face, and her eyes were bright with intelligence; making her appear almost ethereal, she was wearing a simple white dress that flowed gracefully around her.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Choice A is the most effective because it combines the two sentences smoothly and correctly uses a comma to separate the introductory phrase from the main clause. The other choices create either a comma splice or an incorrect use of a semicolon.',
    'Review the passage and eliminate choices that contradict the text.',
    'The first time I saw her, she was sitting in a cafe, reading a book. Her long hair cascaded down her back, framing her face, and her eyes were bright with intelligence. She was wearing a simple white dress that flowed gracefully around her, making her appear almost ethereal. She was the most beautiful woman I had ever seen.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_70d3e7edcd4baa23_english_01188',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a3","opensat_index":1188}'::jsonb
  ),
(
    gen_random_uuid(),
    'The writer most likely includes this idea in the excerpt to',
    'multiple_choice',
    '[{"id":"A","text":"imply that his experience with loneliness is unique to him.","is_correct":false,"explanation":""},{"id":"B","text":"demonstrate the prevalence of loneliness in society.","is_correct":false,"explanation":""},{"id":"C","text":"highlight the universality of the experience of loneliness.","is_correct":false,"explanation":""},{"id":"D","text":"suggest that his experience with loneliness is a symptom of a larger social problem.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The writer includes the idea that his experience with loneliness is not simply a personal struggle to suggest that his experience with loneliness is a symptom of a larger social problem. This idea helps to explain why the writer feels like he can’t relate to others, and it also helps to explain why others might feel like they can’t relate to him. The writer’s experience with loneliness is not simply a personal struggle, but a more complex reflection of how society works.',
    'Review the passage and eliminate choices that contradict the text.',
    'In this excerpt from a book of memoirs, the writer describes his experience with loneliness.  He finds it difficult to relate to others, but he also is aware of how others are likely to relate to him.  In that sense, his experience with loneliness is not simply a personal struggle, but a more complex reflection of how society works.  What is the most likely reason why the writer includes the idea that his experience with loneliness is not simply a personal struggle, but a more complex reflection of how society works?',
    'passage',
    'reading_writing',
    'Expression of Ideas',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Expression of Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Expression of Ideas']::text[],
    'f999c801_english_01189',
    'college_board_opensat',
    '{"opensat_domain":"Expression of Ideas","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"f999c801","opensat_index":1189}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice corrects the punctuation error in the passage?',
    'multiple_choice',
    '[{"id":"A","text":"The first time I met my best friend, I was surprised to learn that he shared the same birthday as me, making us both Gemini twins!","is_correct":true,"explanation":""},{"id":"B","text":"The first time I met my best friend I was surprised to learn that, he shared the same birthday as me, making us both Gemini twins!","is_correct":false,"explanation":""},{"id":"C","text":"The first time I met my best friend, I was surprised to learn that he shared the same birthday as me, making us both Gemini twins! ","is_correct":false,"explanation":""},{"id":"D","text":"The first time I met my best friend, I was surprised to learn that he shared the same birthday as me making us both Gemini twins!","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The comma after "learn" is unnecessary because it separates a dependent clause from its independent clause.  The sentence should be: The first time I met my best friend, I was surprised to learn that he shared the same birthday as me, making us both Gemini twins!',
    'Review the passage and eliminate choices that contradict the text.',
    'The first time I met my best friend, I was surprised to learn that, he shared the same birthday as me, making us both Gemini twins!',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '87654321_english_01190',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"87654321","opensat_index":1190}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best combines the sentences at the underlined portion to create a grammatically correct and stylistically effective sentence?',
    'multiple_choice',
    '[{"id":"A","text":"but only if people know a lot about what we already know, which is a problem.\" ","is_correct":false,"explanation":""},{"id":"B","text":"but only if people know a lot about what we already know, which is a problem.","is_correct":true,"explanation":""},{"id":"C","text":"but only if people know a lot about what we already know which is a problem.","is_correct":false,"explanation":""},{"id":"D","text":"but only if people know a lot about what we already know; which is a problem.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Choice B is the best answer because it correctly uses a comma and a conjunction to combine the two sentences. Choices A and C are incorrect because they are comma splices, and Choice D is incorrect because it uses a semicolon incorrectly. Semicolons can be used to combine two independent clauses, but the two clauses in the underlined portion are not independent clauses.',
    'Review the passage and eliminate choices that contradict the text.',
    'The team members wanted to make their research relevant to as wide an audience as possible. One of the members of the research team noted that, because of the way they had designed their research, the team’s findings were only useful to those who already had a strong background in the field of research. "Our results can be applied to many other situations, but only if people know a lot about what we already know, which is a problem," she said. The team members decided to adjust their research methods to make the results more accessible.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '8a6c30fa_english_01191',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"8a6c30fa","opensat_index":1191}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best describes the overall structure of the text?',
    'multiple_choice',
    '[{"id":"A","text":"It traces the history of an Indigenous political movement and speculates about its future development.","is_correct":false,"explanation":""},{"id":"B","text":"It argues that Indigenous politicians in the United States should form their own political party.","is_correct":false,"explanation":""},{"id":"C","text":"It highlights two approaches to achieving political representation for Indigenous people.","is_correct":true,"explanation":""},{"id":"D","text":"It considers how Indigenous politicians in the United States have influenced Indigenous politicians in Canada and Latin America.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The text presents two different approaches to achieving political representation for Indigenous people: joining existing political parties and forming their own political parties. This is the main idea of the text, and the text goes on to give examples of each approach.',
    'Review the passage and eliminate choices that contradict the text.',
    'A number of Indigenous politicians have been elected to the United States Congress since 2000 as members of the country’s two established political parties. In Canada and several Latin American countries, on the other hand, Indigenous people have formed their own political parties to advance candidates who will advocate for the interests of their communities. This movement has been particularly successful in Ecuador, where Guadalupe Llori, a member of the Indigenous party known as Pachakutik, was elected president of the National Assembly in 2021.',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '957b0602_english_01192',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"957b0602","opensat_index":1192}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best completes the sentence so that it conforms to the conventions of Standard English? The book''s cover is a vivid representation of the novel''s themes. ______, the novel''s story is set in a world of darkness and despair.',
    'multiple_choice',
    '[{"id":"A","text":"Therefore","is_correct":false,"explanation":""},{"id":"B","text":"However","is_correct":true,"explanation":""},{"id":"C","text":"Although","is_correct":false,"explanation":""},{"id":"D","text":"Moreover","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The word "however" correctly creates a contrast between the two clauses, which is the relationship the sentence is trying to express. "However" is the only choice that correctly sets up a contrast between the ideas in the two clauses. The other choices create logical connections or build on the first clause, but they do not create a contrasting relationship.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '5423ac01_english_01193',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"5423ac01","opensat_index":1193}'::jsonb
  ),
(
    gen_random_uuid(),
    'The imagery in this passage primarily serves to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of place and time.","is_correct":false,"explanation":""},{"id":"B","text":"develop a sense of the speaker''s emotional state.","is_correct":true,"explanation":""},{"id":"C","text":"explain the speaker''s actions and motivations.","is_correct":false,"explanation":""},{"id":"D","text":"highlight the speaker’s unique perspective.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The author uses sensory details to help the reader visualize the speaker''s feelings, which makes the speaker''s emotional state more vivid and relatable.',
    'Review the passage and eliminate choices that contradict the text.',
    'Throughout the passage, the author relies heavily on imagery to convey the speaker’s feelings and experiences.  The author’s use of sensory details allows the reader to experience the speaker’s joy, fear, and loneliness. This technique is particularly effective when describing the speaker’s feelings of loneliness.  What is the primary function of imagery in this passage?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_35269b675fae4381_english_01194',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_e2","opensat_index":1194}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice provides the most effective combination of sentences and punctuation?',
    'multiple_choice',
    '[{"id":"A","text":"Although, the author’s new book is more introspective, it’s as though the author is trying to capture the nuanced feelings and unspoken thoughts of the main character.","is_correct":false,"explanation":""},{"id":"B","text":"The author’s new book is more introspective, it’s as though the author is trying to capture the nuanced feelings and unspoken thoughts of the main character.","is_correct":false,"explanation":""},{"id":"C","text":"The author’s new book, is more introspective; it’s as though the author is trying to capture the nuanced feelings and unspoken thoughts of the main character.","is_correct":false,"explanation":""},{"id":"D","text":"The author’s new book is more introspective: it’s as though the author is trying to capture the nuanced feelings and unspoken thoughts of the main character.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The sentence in choice D uses a colon to introduce the explanation for why the author''s new book is more introspective. This is the most effective way to combine the sentences and punctuation because it makes the relationship between the two parts of the sentence clear.',
    'Review the passage and eliminate choices that contradict the text.',
    'A popular author has written a new novel about a character who is a high school teacher who struggles to find meaning in a life of constant routine. The author’s previous books were often praised for their sharp dialogue and their exploration of complex themes. However, the author’s new book is more introspective, as though the author is trying to capture the nuanced feelings and unspoken thoughts of the main character. Which sentence best describes the author’s new book?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_12ab2fe56a67f066_english_01195',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"random_id_e4","opensat_index":1195}'::jsonb
  ),
(
    gen_random_uuid(),
    'The reference to specific research in this passage is most likely meant to',
    'multiple_choice',
    '[{"id":"A","text":"highlight the speaker’s personal involvement in the research.","is_correct":false,"explanation":""},{"id":"B","text":"provide the reader with evidence to support the speaker’s claims.","is_correct":true,"explanation":""},{"id":"C","text":"explain the speaker’s motivation for conducting the research.","is_correct":false,"explanation":""},{"id":"D","text":"convince the reader of the speaker’s authority on the subject.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The reference to specific research is meant to provide the reader with evidence to support the speaker’s claims. This helps to make the speaker''s argument more credible and persuasive.',
    'Review the passage and eliminate choices that contradict the text.',
    'The speaker of this passage is most likely a scientist. The speaker’s expertise in the subject matter is evident in the precise and technical language used. The speaker also uses evidence to support their claims, such as the mention of specific studies and data. What is the most likely reason why the writer refers to specific research in this passage?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    '70f2a59a_english_01196',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"70f2a59a","opensat_index":1196}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the writer’s use of sensory details is primarily intended to',
    'multiple_choice',
    '[{"id":"A","text":"create a vivid image of the speaker’s home for the reader.","is_correct":false,"explanation":""},{"id":"B","text":"emphasize the speaker’s connection to her home.","is_correct":true,"explanation":""},{"id":"C","text":"reveal the speaker’s feelings about the natural world.","is_correct":false,"explanation":""},{"id":"D","text":"convey the speaker’s sense of isolation and loneliness.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The writer uses sensory details to help the reader feel as if they are in the garden with the speaker, making the speaker seem more connected to her home and implying a deeper sense of belonging.',
    'Review the passage and eliminate choices that contradict the text.',
    'Although it may seem that the speaker is simply describing her home, the text actually reveals a deeper meaning about how she feels about where she lives. She uses the term "my home" to imply that she is more than just a visitor. She is a part of this place, and she is invested in its well-being. This is further emphasized by the speaker’s use of sensory details, such as the “smell” of the air and the "buzz" of the bees. These details help to create a sense of immediacy and intimacy, making the reader feel like they are right there in the garden with the speaker. What is the most likely reason the writer uses sensory details?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'b456777a_english_01197',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"b456777a","opensat_index":1197}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best combines the sentences at the underlined portion to create a grammatically correct and effective sentence?',
    'multiple_choice',
    '[{"id":"A","text":"Despite this accomplishment, Earhart, who had earned a reputation for courage and skill, continued to push the boundaries of aviation.","is_correct":false,"explanation":""},{"id":"B","text":"Despite this accomplishment, Earhart, who earned a reputation for courage and skill, continued to push the boundaries of aviation.","is_correct":true,"explanation":""},{"id":"C","text":"Despite this accomplishment, Earhart continued to push the boundaries of aviation, and she had earned a reputation for courage and skill.","is_correct":false,"explanation":""},{"id":"D","text":"Despite this accomplishment, Earhart earned a reputation for courage and skill, continued to push the boundaries of aviation.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The best way to combine the two sentences is to create a nonrestrictive clause to modify the subject "Earhart." The clause "who earned a reputation for courage and skill" should be set off by commas because it is nonrestrictive.',
    'Review the passage and eliminate choices that contradict the text.',
    'In 1929, Amelia Earhart, an American aviation pioneer, became the first woman to fly solo across the Atlantic Ocean.  Despite this accomplishment, Earhart, who had earned a reputation for courage and skill, continued to push the boundaries of aviation. In 1932, she became the first woman to make a solo nonstop flight across the United States, from Harbor Grace, Newfoundland, to Derry, Northern Ireland.  Earhart''s accomplishments helped pave the way for women in aviation, and her pioneering spirit inspired generations of pilots.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '0739f512_english_01198',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"0739f512","opensat_index":1198}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice correctly combines the two clauses?',
    'multiple_choice',
    '[{"id":"A","text":"The invention of the printing press transformed the process of knowledge distribution; however, it took several centuries for the printing press to become widely adopted and to have a significant impact on society.","is_correct":false,"explanation":""},{"id":"B","text":"The invention of the printing press transformed the process of knowledge distribution, however, it took several centuries for the printing press to become widely adopted and to have a significant impact on society.","is_correct":true,"explanation":""},{"id":"C","text":"The invention of the printing press transformed the process of knowledge distribution; it took several centuries, however, for the printing press to become widely adopted and to have a significant impact on society.","is_correct":false,"explanation":""},{"id":"D","text":"The invention of the printing press transformed the process of knowledge distribution, it took several centuries for the printing press to become widely adopted and to have a significant impact on society.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The comma is used correctly to separate two main clauses when followed by a conjunction.  Choice A is incorrect because the conjunction is not immediately after the comma, and Choice C is incorrect because the conjunction is not immediately after the comma. Choice D is incorrect because no conjunction is used to link the two clauses.',
    'Review the passage and eliminate choices that contradict the text.',
    'The speaker of the following passage is a historian who is explaining to a group of students the history of the printing press.  The speaker has used a semicolon to separate two closely related independent clauses, each of which could stand alone as a complete sentence. However, the punctuation is incorrect because no conjunction is used to link the two clauses.  Which choice correctly combines the two clauses?  \begin{align*} \text{The invention of the printing press transformed the process of knowledge}\\ \text{distribution; however, it took several centuries for the printing press to become}\\ \text{widely adopted and to have a significant impact on society.}\end{align*}',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '8464956f_english_01199',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"8464956f","opensat_index":1199}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;