INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'A circle with radius 5 has its center at (4, -2). Which of the following is an equation of this circle?',
    'multiple_choice',
    '[{"id":"A","text":"(x + 4)^2 + (y - 2)^2 = 5","is_correct":false,"explanation":""},{"id":"B","text":"(x + 4)^2 + (y - 2)^2 = 25","is_correct":false,"explanation":""},{"id":"C","text":"(x - 4)^2 + (y + 2)^2 = 5","is_correct":false,"explanation":""},{"id":"D","text":"(x - 4)^2 + (y + 2)^2 = 25","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The standard form of the equation of a circle is (x - h)^2 + (y - k)^2 = r^2, where (h, k) is the center of the circle and r is the radius of the circle.  Since the center of the circle is (4, -2) and the radius is 5, the equation of the circle is (x - 4)^2 + (y - (-2))^2 = 5^2, or (x - 4)^2 + (y + 2)^2 = 25.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_8696027f393b1707_math_00832',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c6","opensat_index":832}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $(x+2)^2 + (y-3)^2 = 25$ represents a circle in the xy-plane.  What is the radius of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":true,"explanation":""},{"id":"C","text":"10","is_correct":false,"explanation":""},{"id":"D","text":"25","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The standard form of the equation of a circle is $(x-h)^2 + (y-k)^2 = r^2$, where $(h,k)$ is the center of the circle, and $r$ is the radius.  In this case, the equation is already in standard form, and we can see that $r^2 = 25$.  Therefore, the radius of the circle is $\sqrt{25} = 5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_a22d00d6be916a61_math_00833',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c9","opensat_index":833}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60% of them prefer brand A, 30% prefer brand B, and the rest prefer brand C. How many people prefer brand C? ',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":true,"explanation":""},{"id":"B","text":"30","is_correct":false,"explanation":""},{"id":"C","text":"40","is_correct":false,"explanation":""},{"id":"D","text":"70","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'If 60% prefer brand A, then 60 people prefer brand A (0.60 * 100 = 60). If 30% prefer brand B, then 30 people prefer brand B (0.30 * 100 = 30).  Since 60 + 30 = 90, then 100 – 90 = 10 people prefer brand C.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_399fb9b7e4147cea_math_00834',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_b8","opensat_index":834}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x = 3y + 2$, and $y = 4$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"12","is_correct":false,"explanation":""},{"id":"C","text":"14","is_correct":true,"explanation":""},{"id":"D","text":"16","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Substituting 4 for *y* in the equation *x* = 3*y* + 2 gives *x* = 3(4) + 2, or *x* = 12 + 2 = 14.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_05d1470eda73f379_math_00835',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_b8","opensat_index":835}'::jsonb
  ),
(
    gen_random_uuid(),
    'Data set A: 5, 5, 9, 5, 5, 5, 5, 5, 5, 5
Data set B: 5, 5, 9, 5, 5, 5, 5, 5, 10, 100
Which of the following statements about the means and medians of data set A and data set B is true?',
    'multiple_choice',
    '[{"id":"A","text":"Only the means are different.","is_correct":true,"explanation":""},{"id":"B","text":"Only the medians are different.","is_correct":false,"explanation":""},{"id":"C","text":"Both the means and the medians are different.","is_correct":false,"explanation":""},{"id":"D","text":"Neither the means nor the medians are different.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The mean of a data set is the sum of the values divided by the number of values. The mean of data set A is 45/9, or 5. The mean of data set B is 145/10, or 14.5. Thus, the means are different. The median of a data set is the middle value when the values are ordered from least to greatest. The medians of data sets A and B are both 5. Therefore, the medians are the same, so only the means are different.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '9110c120_math_00836',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"9110c120","opensat_index":836}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  $y = 2x + 3$ and $x = 5$, what is the value of $y$?',
    'multiple_choice',
    '[{"id":"A","text":"8","is_correct":false,"explanation":""},{"id":"B","text":"10","is_correct":false,"explanation":""},{"id":"C","text":"13","is_correct":true,"explanation":""},{"id":"D","text":"16","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Substituting the value of $x = 5$ into the equation $y = 2x + 3$ gives us $y = 2(5) + 3 = 10 + 3 = 13$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_8139f07756164149_math_00837',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_a5","opensat_index":837}'::jsonb
  ),
(
    gen_random_uuid(),
    'In triangle $ABC$, angle $A$ is a right angle, and $AB = 3$ and $BC = 5$. What is the length of $AC$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":true,"explanation":""},{"id":"C","text":"8","is_correct":false,"explanation":""},{"id":"D","text":"16","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Triangle $ABC$ is a right triangle, so we can use the Pythagorean theorem to find the length of $AC$.  The Pythagorean theorem states that in a right triangle, the square of the hypotenuse (the side opposite the right angle) is equal to the sum of the squares of the other two sides. In this case, $BC$ is the hypotenuse, so $BC^2 = AB^2 + AC^2$.  Substituting the given values, we get $5^2 = 3^2 + AC^2$.  This simplifies to $25 = 9 + AC^2$.  Subtracting 9 from both sides, we get $16 = AC^2$. Taking the square root of both sides, we get $AC = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_91b57ed4660d2be0_math_00838',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c2","opensat_index":838}'::jsonb
  ),
(
    gen_random_uuid(),
    'The table shows the number of students enrolled in each of four clubs at a high school. \begin{tabular}{c|c|c|c|c} & Math Club & Science Club & History Club & Art Club\hline Number of Students & 200 & 150 & 100 & 75 \end{tabular} What percentage of the students enrolled in the four clubs are enrolled in the Math Club?',
    'multiple_choice',
    '[{"id":"A","text":"20%","is_correct":false,"explanation":""},{"id":"B","text":"25%","is_correct":false,"explanation":""},{"id":"C","text":"33.3%","is_correct":false,"explanation":""},{"id":"D","text":"40%","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The total number of students enrolled in the four clubs is 200 + 150 + 100 + 75 = 525.  The fraction of students enrolled in the Math Club is 200/525, which simplifies to 8/21.  To convert this fraction to a percentage, multiply by 100%, which gives 38.1%.  Of the given choices, 40% is closest to 38.1%.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '837f97e2_math_00839',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"837f97e2","opensat_index":839}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following is equivalent to $(x^2 + 3)^2$?',
    'multiple_choice',
    '[{"id":"A","text":"x^4 + 9","is_correct":false,"explanation":""},{"id":"B","text":"x^4 + 6x^2 + 9","is_correct":false,"explanation":""},{"id":"C","text":"x^4 + 9x^2 + 9","is_correct":false,"explanation":""},{"id":"D","text":"x^4 + 12x^2 + 9","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'We can expand the expression using the FOIL method (First, Outer, Inner, Last):

$(x^2 + 3)^2 = (x^2 + 3)(x^2 + 3) = x^4 + 3x^2 + 3x^2 + 9 = x^4 + 6x^2 + 9$.

Therefore, the correct answer is D.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_288d09c8bf2fbace_math_00840',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c8","opensat_index":840}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x + 5 = 26$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"7","is_correct":true,"explanation":""},{"id":"B","text":"9","is_correct":false,"explanation":""},{"id":"C","text":"11","is_correct":false,"explanation":""},{"id":"D","text":"21","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To solve for $x$, we subtract 5 from both sides of the equation: $3x + 5 - 5 = 26 - 5$. This gives us $3x = 21$.  Dividing both sides by 3, we get $x = 7$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'e54712ac_math_00841',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"e54712ac","opensat_index":841}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with radius 5 has a chord of length 8. What is the distance, in units, from the center of the circle to the midpoint of the chord?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A chord of a circle and the radius drawn to the midpoint of the chord form a right triangle. The radius is the hypotenuse of this triangle. The midpoint of the chord divides the chord into two equal segments of length 4.  Therefore, the distance from the center of the circle to the midpoint of the chord is one leg of a right triangle with hypotenuse of length 5 and the other leg of length 4. Using the Pythagorean Theorem, we have  or . Therefore, the distance is 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_0d207ee6546a2574_math_00842',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a4","opensat_index":842}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function \(f(x)\) is defined by \(f(x) = 8\sqrt{x}\). For what value of \(x\) does \(f(x) = 48\)?',
    'multiple_choice',
    '[{"id":"A","text":"6","is_correct":false,"explanation":""},{"id":"B","text":"8","is_correct":false,"explanation":""},{"id":"C","text":"36","is_correct":true,"explanation":""},{"id":"D","text":"64","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for \(x\), we substitute 48 for \(f(x)\) in the equation \(f(x) = 8\sqrt{x}\). This gives us \(48 = 8\sqrt{x}\). Dividing both sides of this equation by 8 yields \(6 = \sqrt{x}\). This can be rewritten as \(\sqrt{x} = 6\). Squaring both sides of this equation yields \(x = 36\). Therefore, the value of \(x\) for which \(f(x) = 48\) is 36.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'f452410b_math_00843',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"f452410b","opensat_index":843}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x = 3y + 2$ and $y = 2$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":false,"explanation":""},{"id":"B","text":"6","is_correct":false,"explanation":""},{"id":"C","text":"8","is_correct":true,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Substituting 2 for $y$ in the equation $x = 3y + 2$, we get $x = 3(2) + 2$. Simplifying, we have $x = 6 + 2$, or $x = 8$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_8cde1a4fb263312e_math_00844',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c2","opensat_index":844}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle is inscribed in a square. The length of a side of the square is $8\sqrt{2}$ centimeters. What is the area, in square centimeters, of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"32\\pi","is_correct":false,"explanation":""},{"id":"B","text":"64\\pi","is_correct":true,"explanation":""},{"id":"C","text":"128\\pi","is_correct":false,"explanation":""},{"id":"D","text":"256\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The diameter of the circle is equal to the length of a side of the square.  Since the length of a side of the square is $8\sqrt{2}$ centimeters, the diameter of the circle is $8\sqrt{2}$ centimeters, and the radius of the circle is half of that, $4\sqrt{2}$ centimeters. The area of the circle is $\pi r^2 = \pi (4\sqrt{2})^2 = 64\pi$ square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_b982aabb19b0d5ae_math_00845',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a9","opensat_index":845}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = \frac{x^2 - 4}{x - 2}$ is undefined for which value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"0","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":true,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'A function is undefined when its denominator equals zero.  In this case, the denominator is $x - 2$, which equals zero when $x = 2$. Therefore, the function $f(x)$ is undefined for $x = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_0e28b3f7dd72402d_math_00846',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_5","opensat_index":846}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 10 centimeters and a width of 6 centimeters. What is the area, in square centimeters, of the rectangle? ',
    'multiple_choice',
    '[{"id":"A","text":"16","is_correct":false,"explanation":""},{"id":"B","text":"32","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":true,"explanation":""},{"id":"D","text":"100","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is calculated by multiplying its length and width.  Therefore, the area of the rectangle is (10)(6) = 60 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_aa82963e5a1884bf_math_00847',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c4","opensat_index":847}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store is selling a certain type of shirt for $\$20 each. The store is having a sale, offering a discount of 15% off the original price. What is the sale price of the shirt?',
    'multiple_choice',
    '[{"id":"A","text":"$17","is_correct":true,"explanation":""},{"id":"B","text":"$18","is_correct":false,"explanation":""},{"id":"C","text":"$19","is_correct":false,"explanation":""},{"id":"D","text":"$21","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'A 15% discount means the customer pays 85% of the original price.  To find the sale price, we multiply the original price by 0.85: $20 * 0.85 = $17.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_06f70e70bde2bdf1_math_00848',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_9","opensat_index":848}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the solution to the equation $4x + 3 = 19$?',
    'multiple_choice',
    '[{"id":"A","text":"-4","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":true,"explanation":""},{"id":"C","text":"12","is_correct":false,"explanation":""},{"id":"D","text":"16","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for $x$, we first subtract 3 from both sides of the equation: $4x + 3 - 3 = 19 - 3$, or $4x = 16$.  Then we divide both sides of the equation by 4: $\frac{4x}{4} = \frac{16}{4}$, or $x = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_632798dd86403e91_math_00849',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a9","opensat_index":849}'::jsonb
  ),
(
    gen_random_uuid(),
    'If the expression  $\frac{2x+3}{x-1}$  is undefined, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":false,"explanation":""},{"id":"B","text":"1","is_correct":true,"explanation":""},{"id":"C","text":"$\\frac{3}{2}$","is_correct":false,"explanation":""},{"id":"D","text":"$\\frac{-3}{2}$","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A fraction is undefined when the denominator is equal to zero. So, we set the denominator, $x-1$, equal to zero and solve for $x$: $x-1 = 0$. Adding 1 to both sides of the equation gives $x = 1$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_e29dfceb4b1fcba6_math_00850',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_b5","opensat_index":850}'::jsonb
  ),
(
    gen_random_uuid(),
    'A function is defined by $f(x) = \frac{x^2}{2} + 3x - 5$. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-9","is_correct":true,"explanation":""},{"id":"B","text":"-7","is_correct":false,"explanation":""},{"id":"C","text":"-5","is_correct":false,"explanation":""},{"id":"D","text":"-3","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To find the value of f(-2), we substitute -2 for x in the function''s formula: $f(-2) = \frac{(-2)^2}{2} + 3(-2) - 5$. Simplifying, we get $f(-2) = \frac{4}{2} - 6 - 5$, or $f(-2) = 2 - 6 - 5$, which equals -9.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_7bed6d0d10aef79c_math_00851',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a9","opensat_index":851}'::jsonb
  ),
(
    gen_random_uuid(),
    'A function $f(x)$ is defined as $f(x) = 2x^2 - 3x + 1$.  What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-17","is_correct":false,"explanation":""},{"id":"B","text":"-11","is_correct":false,"explanation":""},{"id":"C","text":"11","is_correct":false,"explanation":""},{"id":"D","text":"17","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substitute -2 for $x$ in the function: $f(-2) = 2(-2)^2 - 3(-2) + 1$. Simplify: $f(-2) = 2(4) + 6 + 1$, or $f(-2) = 8 + 6 + 1 = 15$. Therefore, the value of f(-2) is 15.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'f4b36293_math_00852',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"f4b36293","opensat_index":852}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following is equivalent to $(x+y)^2 - (x-y)^2$?',
    'multiple_choice',
    '[{"id":"A","text":"2x^2 + 2y^2","is_correct":false,"explanation":""},{"id":"B","text":"4xy","is_correct":true,"explanation":""},{"id":"C","text":"2x^2 - 2y^2","is_correct":false,"explanation":""},{"id":"D","text":"x^2 - y^2","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can use the difference of squares pattern to simplify the expression.  The difference of squares pattern states that $a^2 - b^2 = (a+b)(a-b)$. Applying this pattern to our expression, we get: 
 $(x+y)^2 - (x-y)^2 = (x+y + x-y)(x+y - x+y)$ 
 Simplifying, we get $(2x)(2y) = 4xy$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'a9478db4_math_00853',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"a9478db4","opensat_index":853}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 200 students found that 120 students prefer pizza, 80 students prefer tacos, and 50 students prefer both pizza and tacos. How many students prefer only pizza?',
    'multiple_choice',
    '[{"id":"A","text":"40","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"70","is_correct":true,"explanation":""},{"id":"D","text":"120","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Since 50 students prefer both pizza and tacos, 120 - 50 = 70 students prefer only pizza.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '834f21d4_math_00854',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"834f21d4","opensat_index":854}'::jsonb
  ),
(
    gen_random_uuid(),
    'The expression  is equivalent to $\frac{a}{b}$, where *a* and *b* are integers with no common factors. What is the value of *b*?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":false,"explanation":""},{"id":"B","text":"16","is_correct":false,"explanation":""},{"id":"C","text":"64","is_correct":true,"explanation":""},{"id":"D","text":"256","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Simplify the given expression:  \begin{align*} \frac{16x^2 + 64}{8x^2 + 32} &= \frac{16(x^2 + 4)}{8(x^2 + 4)}\\ &= \frac{16}{8} \\ &= 2. \end{align*} To express 2 as a fraction in the form $\frac{a}{b}$, where *a* and *b* have no common factors, we can rewrite it as $\frac{2}{1}$. Thus, the value of *b* is 1.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_675423d47b85bee2_math_00855',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a5","opensat_index":855}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm. What is the area, in square centimeters, of a sector of this circle with a central angle of 72 degrees?',
    'multiple_choice',
    '[{"id":"A","text":"10\\pi","is_correct":true,"explanation":""},{"id":"B","text":"20\\pi","is_correct":false,"explanation":""},{"id":"C","text":"30\\pi","is_correct":false,"explanation":""},{"id":"D","text":"40\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The area of a sector of a circle is given by (central angle/360 degrees) * (pi * radius^2).  Plugging in the values we get (72/360) * (pi * 5^2) = (1/5) * 25pi = 5pi.  Therefore, the area of the sector is 5pi square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_b54850c8a6ed7d28_math_00856',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_b2","opensat_index":856}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;