INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'If $\frac{2x+3}{x-1} = 5$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for x, we first multiply both sides of the equation by $(x - 1)$: $2x+3 = 5(x-1)$. Expanding the right-hand side of the equation gives $2x + 3 = 5x - 5$. Combining the x-terms on the left-hand side, we get $2x - 5x = -5 - 3$, or $-3x = -8$. Dividing both sides by -3, we get $x = \frac{-8}{-3} = \frac{8}{3} = 2\frac{2}{3}$. Since only 4 is given as a choice, the answer is 4.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'd84e67c3_math_00957',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"d84e67c3","opensat_index":957}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 2x - 15 = 0$, what are the solutions for $x$?',
    'multiple_choice',
    '[{"id":"A","text":"x = 3 or x = -5","is_correct":false,"explanation":""},{"id":"B","text":"x = -3 or x = 5","is_correct":true,"explanation":""},{"id":"C","text":"x = 15 or x = -1","is_correct":false,"explanation":""},{"id":"D","text":"x = -15 or x = 1","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for $x$, we can factor the quadratic expression.  The expression factors as $(x + 5)(x - 3) = 0$. For the product of two terms to equal zero, at least one of the terms must equal zero.  Therefore, either $x + 5 = 0$, or $x - 3 = 0$. Solving for $x$ in each case gives us $x = -5$ or $x = 3$.  Since neither of these solutions is listed as a choice, the correct answer is the only other option, $x = -3$ or $x = 5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'a3d8c31d_math_00958',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"a3d8c31d","opensat_index":958}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x+5=12$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"7","is_correct":true,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"60","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for *x*, we subtract 5 from both sides of the equation:  *x* + 5 - 5 = 12 - 5, which simplifies to *x* = 7.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_edd7b9529fcf1417_math_00959',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_a8","opensat_index":959}'::jsonb
  ),
(
    gen_random_uuid(),
    'A regular hexagon has a side length of 10.  What is the perimeter of the hexagon?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"20","is_correct":false,"explanation":""},{"id":"C","text":"30","is_correct":false,"explanation":""},{"id":"D","text":"60","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'A regular hexagon has 6 equal sides.  The perimeter is the total length of all the sides, so the perimeter of this hexagon is 6 * 10 = 60.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_d8ed7336c0ed382f_math_00960',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c1","opensat_index":960}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve for $x$ using the elimination method.  Multiplying the second equation by 3, we get $3x - 3y = 3$. Adding this equation to the first equation, we get $5x = 15$.  Dividing both sides by 5, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'f298c515_math_00961',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"f298c515","opensat_index":961}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a circumference of 12\pi. What is the area of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"12\\pi","is_correct":false,"explanation":""},{"id":"B","text":"36\\pi","is_correct":true,"explanation":""},{"id":"C","text":"144\\pi","is_correct":false,"explanation":""},{"id":"D","text":"144","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula C = 2\pi r, where r is the radius.  We are given that the circumference is 12\pi, so 12\pi = 2\pi r.  Dividing both sides by 2\pi gives r = 6.  The area of a circle is given by the formula A = \pi r^2, so the area of this circle is A = \pi (6)^2 = 36\pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_d57611c7b934a672_math_00962',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c8","opensat_index":962}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve for $x$ by using the elimination method. Multiplying the second equation by 3, we get $3x - 3y = 3$. Adding this equation to the first equation, we get $5x = 15$. Dividing both sides by 5, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_890390dc76002d34_math_00963',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a7","opensat_index":963}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people like apples, 40 people like bananas, and 20 people like both apples and bananas. How many people like only bananas?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":true,"explanation":""},{"id":"B","text":"40","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":false,"explanation":""},{"id":"D","text":"80","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can use a Venn diagram to solve this problem.  Let the circle representing people who like apples be labeled "A" and the circle representing people who like bananas be labeled "B".  The overlap between the two circles represents the people who like both apples and bananas. We know that 20 people like both apples and bananas, so we can fill in the overlap of the circles with 20.  Since 60 people like apples in total, we can subtract the 20 who like both apples and bananas to find that 60 - 20 = 40 people like only apples.  Since 40 people like bananas in total, we can subtract the 20 who like both apples and bananas to find that 40 - 20 = 20 people like only bananas.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_6a238e47147966a3_math_00964',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a4","opensat_index":964}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 12 cm and a width of 5 cm. What is the area of the rectangle, in square centimeters?',
    'multiple_choice',
    '[{"id":"A","text":"17","is_correct":false,"explanation":""},{"id":"B","text":"34","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":true,"explanation":""},{"id":"D","text":"120","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is found by multiplying its length and width. In this case, the area is 12 cm * 5 cm = 60 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_c40ef8a8d955a876_math_00965',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a2","opensat_index":965}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = \sqrt{x}$ is defined for all $x \ge 0$. What is the value of $f(16)$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":true,"explanation":""},{"id":"C","text":"8","is_correct":false,"explanation":""},{"id":"D","text":"16","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The function $f(x) = \sqrt{x}$ means that the output of the function is the square root of the input.  Therefore, $f(16) = \sqrt{16} = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_cee4e591448f02f2_math_00966',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c1","opensat_index":966}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a circumference of $10\pi$ centimeters. What is the area of the circle, in square centimeters?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":true,"explanation":""},{"id":"D","text":"100\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius of the circle.  We are given that the circumference is $10\pi$ centimeters, so $10\pi = 2\pi r$.  Dividing both sides by $2\pi$ gives us $r = 5$. The area of a circle is given by the formula $A = \pi r^2$, so the area of this circle is $A = \pi (5)^2 = 25\pi$ square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_a3d99ea4506f5844_math_00967',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_b8","opensat_index":967}'::jsonb
  ),
(
    gen_random_uuid(),
    'The expression  $\frac{x^{10}y^6}{x^2y^2}$ is equivalent to $x^ay^b$, where a and b are constants. What is the value of $a+b$?',
    'multiple_choice',
    '[{"id":"A","text":"6","is_correct":false,"explanation":""},{"id":"B","text":"8","is_correct":true,"explanation":""},{"id":"C","text":"10","is_correct":false,"explanation":""},{"id":"D","text":"12","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Using the properties of exponents, we can simplify the expression as follows:  $\frac{x^{10}y^6}{x^2y^2} = x^{10-2}y^{6-2} = x^8y^4$.  Therefore, $a+b = 8+4 = 12$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_bd68aa3721b46554_math_00968',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_27","opensat_index":968}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 6x + 5 = 0$, what is the sum of the solutions to the equation?',
    'multiple_choice',
    '[{"id":"A","text":"-6","is_correct":true,"explanation":""},{"id":"B","text":"-5","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The sum of the solutions to the quadratic equation $ax^2 + bx + c = 0$ is given by $-b/a$. In this case, the sum of the solutions is $-6/1 = -6$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '4a1f5b7a_math_00969',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"4a1f5b7a","opensat_index":969}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = 2x^2 - 4x + 3$ is defined for all real numbers.  What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-13","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"19","is_correct":true,"explanation":""},{"id":"D","text":"27","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Substitute -2 for $x$ in the function:  $f(-2) = 2(-2)^2 - 4(-2) + 3 = 8 + 8 + 3 = 19$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_fc76affcd9d56f24_math_00970',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_9","opensat_index":970}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells apples for $1.25 each and oranges for $0.75 each. A customer buys 5 apples and 3 oranges. How much did the customer spend in total?',
    'multiple_choice',
    '[{"id":"A","text":"$6.25","is_correct":false,"explanation":""},{"id":"B","text":"$7.50","is_correct":false,"explanation":""},{"id":"C","text":"$8.75","is_correct":false,"explanation":""},{"id":"D","text":"$10.00","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The cost of the apples is 5 x $1.25 = $6.25. The cost of the oranges is 3 x $0.75 = $2.25. The total cost is $6.25 + $2.25 = $8.50.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_d9a5a2492bd5ffa4_math_00971',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_4","opensat_index":971}'::jsonb
  ),
(
    gen_random_uuid(),
    'The area of a circle is $16\pi$ square inches.  What is the circumference of the circle, in inches?',
    'multiple_choice',
    '[{"id":"A","text":"4\\pi","is_correct":false,"explanation":""},{"id":"B","text":"8\\pi","is_correct":true,"explanation":""},{"id":"C","text":"16\\pi","is_correct":false,"explanation":""},{"id":"D","text":"64\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The area of a circle is given by $A = \pi r^2$, where $r$ is the radius of the circle.  We are given that the area is $16\pi$ square inches, so $16\pi = \pi r^2$. Dividing both sides by $\pi$ gives $16 = r^2$, so $r = 4$. The circumference of a circle is given by $C = 2\pi r$, so $C = 2\pi (4) = 8\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '4c9664d4_math_00972',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"4c9664d4","opensat_index":972}'::jsonb
  ),
(
    gen_random_uuid(),
    'In a right triangle, the length of the hypotenuse is 10 and the length of one leg is 6. What is the length of the other leg?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":false,"explanation":""},{"id":"B","text":"8","is_correct":false,"explanation":""},{"id":"C","text":"$\\sqrt{64}$","is_correct":false,"explanation":""},{"id":"D","text":"$\\sqrt{136}$","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'We can use the Pythagorean theorem to solve for the missing leg. The Pythagorean theorem states that in a right triangle, the square of the hypotenuse (the longest side) is equal to the sum of the squares of the other two sides.  Let $x$ be the length of the missing leg.  We have the equation: $10^2 = 6^2 + x^2$.  Simplifying, we get $100 = 36 + x^2$.  Subtracting 36 from both sides, we get $64 = x^2$.  Taking the square root of both sides, we get $x = \sqrt{64}$ or $x = -\sqrt{64}$.  Since a length cannot be negative, the length of the other leg is $x = \sqrt{64}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_cfc4e0e9455c5696_math_00973',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_d9","opensat_index":973}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm. What is the area of the circle, in square centimeters? (Use $\pi = 3.14$)',
    'multiple_choice',
    '[{"id":"A","text":"15.7","is_correct":false,"explanation":""},{"id":"B","text":"31.4","is_correct":false,"explanation":""},{"id":"C","text":"78.5","is_correct":true,"explanation":""},{"id":"D","text":"157","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula $A = \pi r^2$, where $r$ is the radius. Substituting $r = 5$ cm and $\pi = 3.14$, we get $A = 3.14 \cdot 5^2 = 3.14 \cdot 25 = 78.5$ square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_f5e4a6815d4396cf_math_00974',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_24","opensat_index":974}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2-4x+3 = 0$, what is the sum of the solutions of this equation?',
    'multiple_choice',
    '[{"id":"A","text":"-4","is_correct":false,"explanation":""},{"id":"B","text":"-3","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'We can factor the quadratic equation: $(x-1)(x-3)=0$.  This tells us that the solutions to the equation are $x=1$ and $x=3$. The sum of these solutions is $1+3 = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '2466792a_math_00975',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"2466792a","opensat_index":975}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 4x + 4 = 0$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":true,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The given equation is a perfect square trinomial: $(x+2)^2 = 0$. Taking the square root of both sides, we get $x+2 = 0$. Subtracting 2 from both sides, we get $x = -2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'f8f51193_math_00976',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"f8f51193","opensat_index":976}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by \(f(x) = 2x^2 + 3x - 1\). What is the value of \(f(-2)\)?',
    'multiple_choice',
    '[{"id":"A","text":"-9","is_correct":true,"explanation":""},{"id":"B","text":"-3","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Substituting -2 for *x* in the function, we get \(f(-2) = 2(-2)^2 + 3(-2) - 1\). Simplifying, we get \(f(-2) = 8 - 6 - 1\), or \(f(-2) = -9\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'c824d513_math_00977',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"c824d513","opensat_index":977}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 10 inches and a width of 5 inches. What is the area of the rectangle, in square inches?',
    'multiple_choice',
    '[{"id":"A","text":"15","is_correct":false,"explanation":""},{"id":"B","text":"25","is_correct":false,"explanation":""},{"id":"C","text":"50","is_correct":true,"explanation":""},{"id":"D","text":"100","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is calculated by multiplying its length and width.  In this case, the area is 10 inches * 5 inches = 50 square inches.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_01fdc28a51ee7ecf_math_00978',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_b9","opensat_index":978}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $\frac{2x-3}{x+1} = 5$ is equivalent to which of the following equations?',
    'multiple_choice',
    '[{"id":"A","text":"2x - 3 = 5x + 5","is_correct":true,"explanation":""},{"id":"B","text":"2x - 3 = 5x - 5","is_correct":false,"explanation":""},{"id":"C","text":"2x + 3 = 5x + 5","is_correct":false,"explanation":""},{"id":"D","text":"2x + 3 = 5x - 5","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To solve for x, we multiply both sides of the equation by (x+1).  This gives us $2x - 3 = 5(x+1)$.  Distributing the 5 on the right side, we get $2x - 3 = 5x + 5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_3b5549a8ae883f46_math_00979',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a3","opensat_index":979}'::jsonb
  ),
(
    gen_random_uuid(),
    'A bakery has 120 cakes on display.  Of those cakes, 25% are chocolate, 30% are vanilla, and the rest are strawberry. How many strawberry cakes are on display?',
    'multiple_choice',
    '[{"id":"A","text":"36","is_correct":false,"explanation":""},{"id":"B","text":"48","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":true,"explanation":""},{"id":"D","text":"72","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'First, we need to find the total percentage of chocolate and vanilla cakes: 25% + 30% = 55%. This means 55% of the cakes are either chocolate or vanilla.  The remaining cakes must be strawberry: 100% - 55% = 45%.  To find the number of strawberry cakes, we multiply the total number of cakes by 45%: 120 cakes * 0.45 = 54 cakes.  The closest answer choice to 54 cakes is 60, so the answer is C.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '28f140fd_math_00980',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"28f140fd","opensat_index":980}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with radius 5 is inscribed in a square. What is the area of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square.  Since the radius of the circle is 5, the diameter is 10.  The area of the square is then $10^2 = 100$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_e765520698af8c42_math_00981',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a9","opensat_index":981}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;