INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'If the function $f(x) = \frac{x^2 - 9}{x - 3}$ is defined for all real numbers except $x = 3$, what is the value of $f(4)$?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"7","is_correct":true,"explanation":""},{"id":"D","text":"undefined","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'First, we can factor the numerator: $f(x) = \frac{(x+3)(x-3)}{x-3}$. Since $x \neq 3$, we can cancel out the common factor of $(x-3)$ in the numerator and denominator, leaving us with $f(x) = x + 3$.  Now, substituting $x = 4$, we get $f(4) = 4 + 3 = 7$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '6c3a844e_math_00482',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"6c3a844e","opensat_index":482}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  \(2x + 3y = 10\) and \(x - y = 2\), what is the value of \(x + y\)?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for x + y, we can add the two equations together. Notice that the y terms will cancel out. The result is: (2x + 3y) + (x - y) = 10 + 2. Combining like terms, we get 3x + 2y = 12.  Since we are looking for x + y, we can''t simplify further.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '87676666_math_00483',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"87676666","opensat_index":483}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $y = 3x - 5$ and $x = 2y + 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":false,"explanation":""},{"id":"B","text":"1","is_correct":false,"explanation":""},{"id":"C","text":"7","is_correct":true,"explanation":""},{"id":"D","text":"13","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can solve this system of equations by substitution.  Since we know that $x = 2y + 1$, we can substitute $2y + 1$ for $x$ in the equation $y = 3x - 5$.  This gives us $y = 3(2y + 1) - 5$.  Distributing the 3, we get $y = 6y + 3 - 5$.  Combining like terms, we have $y = 6y - 2$.  Subtracting $y$ from both sides, we get $0 = 5y - 2$.  Adding 2 to both sides, we get $2 = 5y$.  Dividing both sides by 5, we get $y = \frac{2}{5}$.  Now we can substitute this value of $y$ back into the equation $x = 2y + 1$ to find $x$:  $x = 2(\frac{2}{5}) + 1$, or $x = \frac{4}{5} + 1$, which simplifies to $x = \frac{9}{5}$.  The value of $x$ is then $\frac{9}{5} \cdot \frac{5}{5} = \frac{45}{5} = 9$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'f872419e_math_00484',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"f872419e","opensat_index":484}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a circumference of $12\pi$ centimeters. What is the area, in square centimeters, of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"6\\pi","is_correct":false,"explanation":""},{"id":"B","text":"12\\pi","is_correct":false,"explanation":""},{"id":"C","text":"36\\pi","is_correct":true,"explanation":""},{"id":"D","text":"144\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius of the circle.  We are given that the circumference is $12\pi$ centimeters, so we can solve for the radius: 
 $12\pi = 2\pi r$ 
 $r = 6$ 
 The area of a circle is given by the formula $A = \pi r^2$. Substituting 6 for $r$ gives us $A = \pi(6)^2 = 36\pi$ square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_dae165a2aeb884af_math_00485',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_c4","opensat_index":485}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells two types of cookies: chocolate chip and peanut butter.  The store sold 30 chocolate chip cookies and 40 peanut butter cookies.  If the store sold a total of 80 cookies, what percentage of the cookies sold were chocolate chip?',
    'multiple_choice',
    '[{"id":"A","text":"15%","is_correct":false,"explanation":""},{"id":"B","text":"25%","is_correct":false,"explanation":""},{"id":"C","text":"37.5%","is_correct":true,"explanation":""},{"id":"D","text":"62.5%","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The store sold 30 chocolate chip cookies out of a total of 80 cookies.  This represents 30/80 = 0.375, or 37.5% of the cookies sold.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_2aa2d6efded37bc7_math_00486',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a7","opensat_index":486}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5. A chord of the circle is 8 units long. What is the distance, in units, from the center of the circle to the chord?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A chord of a circle is a line segment whose endpoints lie on the circle.  The distance from the center of the circle to a chord is the length of the perpendicular segment from the center to the chord. This perpendicular segment bisects the chord. Thus, we have a right triangle with legs of length 4 and a hypotenuse of length 5. Using the Pythagorean Theorem, we can find the length of the third side:  4^2 + x^2 = 5^2. Solving for x, we get x = 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '4793902d_math_00487',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"4793902d","opensat_index":487}'::jsonb
  ),
(
    gen_random_uuid(),
    'If the function *f* is defined by *f*(x) = 2x^2 + 3x - 1, what is the value of *f*(2)?',
    'multiple_choice',
    '[{"id":"A","text":"15","is_correct":false,"explanation":""},{"id":"B","text":"17","is_correct":false,"explanation":""},{"id":"C","text":"21","is_correct":true,"explanation":""},{"id":"D","text":"23","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find *f*(2), we substitute 2 for *x* in the function: *f*(2) = 2(2)^2 + 3(2) - 1 = 8 + 6 - 1 = 13.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '53c35c79_math_00488',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"53c35c79","opensat_index":488}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units. A chord of the circle is 8 units long. What is the distance, in units, from the center of the circle to the chord?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Draw a diagram of the circle with the chord and a radius drawn to an endpoint of the chord. This radius will be perpendicular to the chord and will bisect the chord. This creates a right triangle with the radius as the hypotenuse, half the chord length as one leg, and the distance from the center of the circle to the chord as the other leg. Using the Pythagorean theorem, we have  . Solving for the distance, we get  , or .',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_f9d8e6cf3402a4ca_math_00489',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a3","opensat_index":489}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 4x + 4 = 0$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"2","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The expression on the left-hand side of the equation is a perfect square trinomial: $(x-2)^2 = 0$. Taking the square root of both sides, we get $x-2 = 0$. Adding 2 to both sides, we find $x = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_baf04e920b48804b_math_00490',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_12","opensat_index":490}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells apples for $1.50 each and oranges for $0.75 each. If a customer buys 3 apples and 5 oranges, how much will the customer spend in total?',
    'multiple_choice',
    '[{"id":"A","text":"$7.50","is_correct":false,"explanation":""},{"id":"B","text":"$9.75","is_correct":false,"explanation":""},{"id":"C","text":"$10.50","is_correct":false,"explanation":""},{"id":"D","text":"$11.25","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The customer will spend 3 * $1.50 = $4.50 on apples and 5 * $0.75 = $3.75 on oranges. The total cost is $4.50 + $3.75 = $11.25.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '7c38d13a_math_00491',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"7c38d13a","opensat_index":491}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  $x^2 - 6x + 9 = 0$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":true,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The equation is a perfect square trinomial, which can be factored as $(x - 3)^2 = 0$. Taking the square root of both sides gives $x - 3 = 0$, which means $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_0f93c3798b8a50a7_math_00492',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_a4","opensat_index":492}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  \(3x+2y=11\) and \(5x-y=2\), what is the value of \(x\)?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":false,"explanation":""},{"id":"B","text":"1","is_correct":true,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"3","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for \(x\), we can use elimination. Multiplying the second equation by 2, we get \(10x-2y=4\). Adding this equation to the first equation, we get \(13x=15\). Dividing both sides by 13, we get \(x=\frac{15}{13}\).  Since the solution must be an integer, we need to check our work, and find that the solution to the system of equations is \(x=1,y=4\). Therefore, the value of x is 1.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '32d85d4f_math_00493',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"32d85d4f","opensat_index":493}'::jsonb
  ),
(
    gen_random_uuid(),
    'In a right triangle, one angle measures 30 degrees, and the side opposite that angle has a length of 10. What is the length of the hypotenuse of the triangle?',
    'multiple_choice',
    '[{"id":"A","text":"5","is_correct":false,"explanation":""},{"id":"B","text":"10\\sqrt{3}","is_correct":false,"explanation":""},{"id":"C","text":"20","is_correct":true,"explanation":""},{"id":"D","text":"10\\sqrt{2}","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'In a 30-60-90 triangle, the hypotenuse is twice the length of the shorter leg. Since the shorter leg has a length of 10, the hypotenuse has a length of 2(10) = 20.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_7d9ec2f382d2b082_math_00494',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c8","opensat_index":494}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  $x^2 + 2x - 15 = 0$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-5 and 3","is_correct":true,"explanation":""},{"id":"B","text":"5 and -3","is_correct":false,"explanation":""},{"id":"C","text":"-5 and -3","is_correct":false,"explanation":""},{"id":"D","text":"5 and 3","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can factor the quadratic equation as (x + 5)(x - 3) = 0.  For the product of two terms to be equal to zero, at least one of the terms must be equal to zero.  Setting each term equal to zero, we get x + 5 = 0 or x - 3 = 0.  Solving for x, we get x = -5 and x = 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_5ff97cc9a2181d9d_math_00495',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a9","opensat_index":495}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle is inscribed in a square. The area of the square is 64. What is the area of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"$\\pi$","is_correct":false,"explanation":""},{"id":"B","text":"$\\pi2$","is_correct":false,"explanation":""},{"id":"C","text":"$\\pi4$","is_correct":false,"explanation":""},{"id":"D","text":"$\\pi16$","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The area of the square is 64, so the side length of the square is 8. The diagonal of the square is equal to the diameter of the circle.  Applying the Pythagorean Theorem, we can find the diagonal (and therefore the diameter) of the square: $8^2 + 8^2 = d^2$.  This simplifies to $128 = d^2$, which means the diameter is $\sqrt{128} = 8\sqrt{2}$. The radius of the circle is half the diameter, so the radius is $4\sqrt{2}$. The area of the circle is $\pi r^2$, so the area is $\pi (4\sqrt{2})^2 = \pi (16 \cdot 2) = \pi (32) = 16 \pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '9f12e366_math_00496',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"9f12e366","opensat_index":496}'::jsonb
  ),
(
    gen_random_uuid(),
    'A regular hexagon is inscribed in a circle with radius 6. What is the perimeter of the hexagon?',
    'multiple_choice',
    '[{"id":"A","text":"12","is_correct":false,"explanation":""},{"id":"B","text":"18","is_correct":false,"explanation":""},{"id":"C","text":"24","is_correct":false,"explanation":""},{"id":"D","text":"36","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'A regular hexagon can be divided into six equilateral triangles.  The side length of each equilateral triangle is equal to the radius of the circle, which is 6.  Therefore, the perimeter of the hexagon is 6 * 6 = 36.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_52a631fc995dd718_math_00497',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a8","opensat_index":497}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = \frac{1}{x^2 + 1}$ is defined for all real numbers. What is the value of $f(\frac{1}{2})$?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{1}{5}$","is_correct":false,"explanation":""},{"id":"B","text":"$\\frac{2}{5}$","is_correct":false,"explanation":""},{"id":"C","text":"$\\frac{4}{5}$","is_correct":true,"explanation":""},{"id":"D","text":"$\\frac{5}{4}$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Substituting $x = \frac{1}{2}$ into the function, we get: $f(\frac{1}{2}) = \frac{1}{(\frac{1}{2})^2 + 1}$. Simplifying the denominator, we have: $f(\frac{1}{2}) = \frac{1}{\frac{1}{4} + 1} = \frac{1}{\frac{5}{4}} = \frac{4}{5}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_cca8d2ffc7fce172_math_00498',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a8","opensat_index":498}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = x^2 - 3x + 1$ is defined for all real numbers. What is the value of $f(2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":false,"explanation":""},{"id":"B","text":"1","is_correct":true,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"7","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To find $f(2)$, we substitute 2 for $x$ in the function: $f(2) = 2^2 - 3(2) + 1 = 4 - 6 + 1 = -2 + 1 = 1$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_60b72ebd6051d298_math_00499',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_9","opensat_index":499}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of 5 friends are planning a trip.  They decide to split the cost of the trip evenly.  If the total cost of the trip is \$450, how much will each friend pay? ',
    'multiple_choice',
    '[{"id":"A","text":"9","is_correct":false,"explanation":""},{"id":"B","text":"90","is_correct":true,"explanation":""},{"id":"C","text":"455","is_correct":false,"explanation":""},{"id":"D","text":"2250","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To find out how much each friend will pay, we divide the total cost by the number of friends: $450 / 5 = $90.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '4b50a70e_math_00500',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"4b50a70e","opensat_index":500}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5. What is the area of the circle?  (Use $\pi \approx 3.14$)',
    'multiple_choice',
    '[{"id":"A","text":"15.7","is_correct":false,"explanation":""},{"id":"B","text":"31.4","is_correct":false,"explanation":""},{"id":"C","text":"78.5","is_correct":true,"explanation":""},{"id":"D","text":"157","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula $A = \pi r^2$, where $r$ is the radius.  Substituting 5 for $r$ and 3.14 for $\pi$, we get $A \approx 3.14 \cdot 5^2 \approx 3.14 \cdot 25 \approx 78.5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_51cfcd8793324b7e_math_00501',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a6","opensat_index":501}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with center at the origin and radius 5 intersects the line $x + y = 7$ at two points. What is the distance between these two points?',
    'multiple_choice',
    '[{"id":"A","text":"5\\sqrt{2}","is_correct":true,"explanation":""},{"id":"B","text":"10","is_correct":false,"explanation":""},{"id":"C","text":"5\\sqrt{3}","is_correct":false,"explanation":""},{"id":"D","text":"7\\sqrt{2}","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The equation of the circle with center at the origin and radius 5 is $x^2 + y^2 = 25$.  We can solve the system of equations $x^2 + y^2 = 25$ and $x + y = 7$ to find the points of intersection. Solving for $x$ in the second equation, we get $x = 7 - y$. Substituting this into the first equation, we get $(7-y)^2 + y^2 = 25$. Expanding the equation, we get $49 - 14y + y^2 + y^2 = 25$. Combining like terms, we get $2y^2 - 14y + 24 = 0$. Dividing both sides by 2, we get $y^2 - 7y + 12 = 0$. Factoring, we get $(y-3)(y-4) = 0$. Therefore, $y = 3$ or $y = 4$. Substituting these values back into the equation $x = 7 - y$, we get the points of intersection as $(4,3)$ and $(3,4)$. The distance between these two points can be found using the distance formula: $\sqrt{(4-3)^2 + (3-4)^2} = \sqrt{1+1} = \sqrt{2}$.  Thus, the distance between the two points is $5\sqrt{2}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'a12f3478_math_00502',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"a12f3478","opensat_index":502}'::jsonb
  ),
(
    gen_random_uuid(),
    'If \(\frac{x^2 - 9}{x + 3} = 8\), and \(x \neq -3\), what is the value of \(x\)?',
    'multiple_choice',
    '[{"id":"A","text":"-11","is_correct":false,"explanation":""},{"id":"B","text":"-5","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":false,"explanation":""},{"id":"D","text":"11","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'We can factor the numerator of the fraction, giving us \(\frac{(x + 3)(x - 3)}{x + 3} = 8\).  Since \(x \neq -3\), we can cancel the \(x + 3\) terms, leaving us with \(x - 3 = 8\).  Adding 3 to both sides gives us \(x = 11\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_65a226346459944b_math_00503',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_f1","opensat_index":503}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2+4x=21$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-7 or 3","is_correct":true,"explanation":""},{"id":"B","text":"7 or -3","is_correct":false,"explanation":""},{"id":"C","text":"-3 or 3","is_correct":false,"explanation":""},{"id":"D","text":"7 or 3","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can solve this quadratic equation by factoring. First, we need to move all the terms to one side: $x^2 + 4x - 21 = 0$.  Then we factor the quadratic expression:  $(x+7)(x-3) = 0$.  For the product of two terms to be zero, at least one of the terms must be zero. Therefore, either $x+7 = 0$ or $x-3 = 0$, which gives us $x = -7$ or $x=3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '642e4e1a_math_00504',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"642e4e1a","opensat_index":504}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function \(f\) is defined by \(f(x) = \frac{x^2 - 4}{x - 2}\). For what value(s) of \(x\) is the function undefined?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"-2 and 2","is_correct":false,"explanation":""},{"id":"D","text":"The function is defined for all values of x.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A function is undefined when the denominator of a fraction equals zero.  In this case, the denominator, \(x - 2\), equals zero when \(x = 2\).  Therefore, the function is undefined when \(x = 2\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_056ffb9977e14643_math_00505',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c9","opensat_index":505}'::jsonb
  ),
(
    gen_random_uuid(),
    'A line passes through the points $(2, 5)$ and $(-1, -4)$. What is the slope of the line?',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":false,"explanation":""},{"id":"B","text":"-\\frac{1}{3}","is_correct":false,"explanation":""},{"id":"C","text":"\\frac{1}{3}","is_correct":false,"explanation":""},{"id":"D","text":"3","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The slope of a line passing through points $(x_1, y_1)$ and $(x_2, y_2)$ is given by the formula \frac{y_2 - y_1}{x_2 - x_1}. Substituting the given points, we get \frac{-4 - 5}{-1 - 2} = \frac{-9}{-3} = 3. Therefore, the slope of the line is 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'c7c7699b_math_00506',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"c7c7699b","opensat_index":506}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;