INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'In this essay, figurative language is used primarily to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of urgency and immediacy.","is_correct":false,"explanation":""},{"id":"B","text":"explain complex concepts in a more accessible way.","is_correct":true,"explanation":""},{"id":"C","text":"highlight the author’s personal experiences and beliefs.","is_correct":false,"explanation":""},{"id":"D","text":"emphasize the emotional impact of the author’s ideas.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Figurative language is used to make complex concepts more accessible to readers. By using metaphors and similes, the author can create vivid images in the reader''s mind, which can help to make the concepts more understandable.',
    'Review the passage and eliminate choices that contradict the text.',
    'In the essay, the author uses several stylistic choices to enhance the overall argument, including the use of short sentences and the repetition of phrases.  The author also uses figurative language, such as metaphors and similes, to help readers visualize the complex concepts being discussed. What is the primary function of the figurative language?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '622a351d_english_00725',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"622a351d","opensat_index":725}'::jsonb
  ),
(
    gen_random_uuid(),
    'The main reason why a comma splice is a punctuation error is that',
    'multiple_choice',
    '[{"id":"A","text":"it creates a run-on sentence.","is_correct":true,"explanation":""},{"id":"B","text":"it results in a phrase that’s too long.","is_correct":false,"explanation":""},{"id":"C","text":"it makes the writing too formal.","is_correct":false,"explanation":""},{"id":"D","text":"it makes the writing too casual.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'A comma splice occurs when a comma is used incorrectly to separate two complete sentences without a conjunction.  This is incorrect because it creates a run-on sentence, which is a sentence that is too long because two independent clauses are fused together without proper punctuation.',
    'Review the passage and eliminate choices that contradict the text.',
    'The most common punctuation error that occurs in this type of writing is a comma splice.  A comma splice is a comma used incorrectly to separate two complete sentences without a conjunction. This is incorrect because a comma cannot be used in this way to join two complete sentences.  What is the main reason why this is a punctuation error?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'f453a864_english_00726',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"f453a864","opensat_index":726}'::jsonb
  ),
(
    gen_random_uuid(),
    'The vivid language in this passage most likely serves to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of immediacy and excitement in the reader.","is_correct":true,"explanation":""},{"id":"B","text":"describe the character’s physical appearance.","is_correct":false,"explanation":""},{"id":"C","text":"emphasize the character’s intelligence.","is_correct":false,"explanation":""},{"id":"D","text":"suggest that the character is struggling with a difficult decision.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The author uses vivid language to create a sense of immediacy and excitement in the reader. This helps the reader feel more engaged with the story and the character’s experiences.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author describes how the main character''s actions are affected by her emotions.  This is shown through the use of vivid language and imagery. The author uses words like "flung" and "tore" to describe the character''s movements, which emphasizes the intensity of her feelings.  What is the most likely reason why the writer uses such vivid language?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_48b6659b79e909c1_english_00727',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_eng_1","opensat_index":727}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the word "however" is used to',
    'multiple_choice',
    '[{"id":"A","text":"introduce a contrasting idea.","is_correct":true,"explanation":""},{"id":"B","text":"emphasize the importance of the author’s message.","is_correct":false,"explanation":""},{"id":"C","text":"describe the author’s feelings and experiences.","is_correct":false,"explanation":""},{"id":"D","text":"suggest that the author is addressing a large audience.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The word "however" is a transition word used to introduce a contrasting idea. The author is trying to balance the need to explain complex ideas in a clear and concise way with the need to maintain a sense of intellectual rigor. By using the word "however," the author signals that the following sentence will introduce a contrasting idea.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author of the passage is a prominent philosopher who is writing a book on the nature of reality. The book is intended for a general audience, so the author tries to explain complex ideas in a clear and concise way. However, the author also wants to maintain a sense of intellectual rigor and avoid oversimplification. What is the most likely reason why the author would use the word "however" in the passage?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_18f06e9b26223116_english_00728',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_b8","opensat_index":728}'::jsonb
  ),
(
    gen_random_uuid(),
    'The phrase "a sense of relief" in the passage primarily serves to',
    'multiple_choice',
    '[{"id":"A","text":"highlight the speaker’s newfound appreciation for his surroundings.","is_correct":false,"explanation":""},{"id":"B","text":"underscore the speaker’s sense of accomplishment.","is_correct":false,"explanation":""},{"id":"C","text":"emphasize the speaker’s newfound freedom from past burdens.","is_correct":true,"explanation":""},{"id":"D","text":"suggest that the speaker’s emotional state is one of contentment.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The phrase "a sense of relief" emphasizes the speaker''s newfound freedom from past burdens. The speaker is relieved to have escaped from a difficult situation and is grateful for the opportunity to be free from the pressures of his past life. This is the most direct and immediate effect of the phrase in the passage.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author''s use of the phrase "a sense of relief" in the passage helps to convey the speaker’s point of view. The author emphasizes that the speaker is relieved to have escaped from a difficult situation. The author also suggests that the speaker is grateful for the opportunity to be free from the pressures of his past life. In doing so, the author helps the reader understand the speaker’s emotional state. Which choice best describes the effect of the phrase "a sense of relief" in the passage?',
    'passage',
    'reading_writing',
    'Expression of Ideas',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Expression of Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Expression of Ideas']::text[],
    'opensat_4b5efe6413a86e98_english_00729',
    'college_board_opensat',
    '{"opensat_domain":"Expression of Ideas","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"random_id_a8","opensat_index":729}'::jsonb
  ),
(
    gen_random_uuid(),
    'The word "consequences" in the passage most nearly means',
    'multiple_choice',
    '[{"id":"A","text":"results","is_correct":true,"explanation":""},{"id":"B","text":"alternatives","is_correct":false,"explanation":""},{"id":"C","text":"causes","is_correct":false,"explanation":""},{"id":"D","text":"predictions","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The sentence discusses the results of the development of new technologies.  "Consequences" means "results."  The other choices don’t fit the context.',
    'Review the passage and eliminate choices that contradict the text.',
    'The 19th century saw a rapid development of new technologies, such as the telegraph and the railroad, which revolutionized the way people lived and worked.  However, these innovations also had unintended consequences, as can be seen in the rise of urban poverty, the spread of infectious diseases, and the widening gap between the rich and the poor.  In the passage, what does the word “consequences” most nearly mean?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'd6f6f68d_english_00730',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"d6f6f68d","opensat_index":730}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best completes the text so that it conforms to the conventions of Standard English?',
    'multiple_choice',
    '[{"id":"A","text":"understand the evolution of the artist’s style.","is_correct":true,"explanation":""},{"id":"B","text":"understand the evolution of the artist’s style, and","is_correct":false,"explanation":""},{"id":"C","text":"understand the evolution of the artist’s style; and","is_correct":false,"explanation":""},{"id":"D","text":"understand the evolution of the artist’s style, and,","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The most logical and grammatically correct way to complete the sentence is with a period after "style."  A period creates a clear separation between two independent clauses.  The other choices create comma splices or use unnecessary punctuation.',
    'Review the passage and eliminate choices that contradict the text.',
    'The museum curator is trying to create a timeline of the famous artist’s life.  The curator has chosen to include pieces of the artist’s work that are representative of different periods in the artist’s life.   For example, a sketch created by the artist in 1932 will be included alongside a large sculpture the artist made in 1958.  All of the pieces will be grouped in chronological order.  The curator hopes that this will help visitors to',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_a4b7ba4d91d0c139_english_00731',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_e9","opensat_index":731}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the author is most likely revisiting the scene because',
    'multiple_choice',
    '[{"id":"A","text":"the author wants to revisit a scene that is particularly meaningful to the reader.","is_correct":false,"explanation":""},{"id":"B","text":"the author wants to show how the scene has changed over time.","is_correct":false,"explanation":""},{"id":"C","text":"the author wants to provide a new interpretation of the scene.","is_correct":true,"explanation":""},{"id":"D","text":"the author wants to provide a more detailed description of the scene.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The author is revisiting the scene to provide a new interpretation of it. The author mentions that they have chosen to revisit this scene for a reason, and they are looking at the scene with a fresh perspective, focusing on specific details. This suggests that the author is trying to understand the scene in a new way.',
    'Review the passage and eliminate choices that contradict the text.',
    'The passage describes how the author, having read the entire novel, is now revisiting a specific scene.  The author mentions that there are many scenes and that the author has chosen to revisit this specific scene for a reason.  The author is now looking at the scene with a fresh perspective, focusing on specific details. What is the most likely reason why the author has chosen to revisit this scene?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_048b557d5f67fe6f_english_00732',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_c1","opensat_index":732}'::jsonb
  ),
(
    gen_random_uuid(),
    'What does the text suggest is the most likely reason for the results of the study?',
    'multiple_choice',
    '[{"id":"A","text":"The students who were provided with one-on-one assistance were more likely to be motivated to learn the concepts of the study.","is_correct":false,"explanation":""},{"id":"B","text":"The students who were provided with one-on-one assistance were more likely to be able to understand the concepts of the study.","is_correct":true,"explanation":""},{"id":"C","text":"The students who were provided with one-on-one assistance were more likely to have a better understanding of the concepts of the study.","is_correct":false,"explanation":""},{"id":"D","text":"The students who were provided with one-on-one assistance were more likely to be able to recall the concepts of the study.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The text suggests that the most likely reason for the results of the study is that the students who were provided with one-on-one assistance were more likely to be able to understand the concepts of the study. This is because the text states that the number of young children who were able to learn the concepts in a normal classroom setting was much lower than the number of students who were able to learn the concepts in a setting where they were provided with one-on-one assistance.  This finding suggests that providing one-on-one assistance can help children understand concepts better.',
    'Review the passage and eliminate choices that contradict the text.',
    'The text states that the scientists involved in this research found that the number of young children who were able to learn the concepts of the study in a normal classroom setting was much lower than the number of students who were able to learn the concepts in a setting where they were provided with one-on-one assistance.  This finding suggests that there is a benefit to providing one-on-one assistance to children, but it does not necessarily mean that all children would benefit from such assistance, nor does it mean that one-on-one assistance would be the most effective approach for all children. What does the text suggest is the most likely reason for the results of the study?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'a134913c_english_00733',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"a134913c","opensat_index":733}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author’s use of a metaphor in this passage helps to',
    'multiple_choice',
    '[{"id":"A","text":"explain a complex technical process in simple terms.","is_correct":false,"explanation":""},{"id":"B","text":"illustrate the effect of a new invention on human perception.","is_correct":true,"explanation":""},{"id":"C","text":"compare the invention’s impact to that of earlier inventions.","is_correct":false,"explanation":""},{"id":"D","text":"emphasize the importance of the invention’s inventor.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The author uses the metaphor "gave people a new sense of ownership over their environment" to help the reader understand how the invention changed the way that people perceive and understand their surroundings. The metaphor emphasizes the idea that the invention gave people a new level of control over their environment, which made it seem less intimidating and disorienting.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author of the text describes how a particular invention in the nineteenth century changed the way that we perceive and understand our surroundings. The author notes that before this invention, the experience of navigating unfamiliar spaces was “intimidating” and “disorienting,” since those spaces were unknown and unpredictable. After the invention, however, people could use this new tool to “master their surroundings,” and the author uses a metaphor to explain that this tool “gave people a new sense of ownership over their environment.” What is the most likely reason why the author uses a metaphor in this text?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    '32ef691a_english_00734',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"32ef691a","opensat_index":734}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this sentence, the phrase "who has worked in many prestigious restaurants around the world" is a',
    'multiple_choice',
    '[{"id":"A","text":"dependent clause, so it should be set off by commas.","is_correct":false,"explanation":""},{"id":"B","text":"nonessential element, so it should be set off by commas.","is_correct":true,"explanation":""},{"id":"C","text":"restrictive clause, so it should not be set off by commas.","is_correct":false,"explanation":""},{"id":"D","text":"simple sentence, so it should not be set off by commas.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The phrase "who has worked in many prestigious restaurants around the world" provides additional information about the chef, but it isn''t essential to understanding who the chef is.  Nonessential elements are set off by commas.  So the correct answer is B.',
    'Review the passage and eliminate choices that contradict the text.',
    'The chef, who has worked in many prestigious restaurants around the world, is known for his innovative use of spices.  He uses a variety of spices, both common and exotic, to create complex and flavorful dishes.  In his latest cookbook, the chef shares his signature recipes and techniques, encouraging home cooks to experiment with spices.  What is the best way to punctuate the sentence: ''The chef who has worked in many prestigious restaurants around the world is known for his innovative use of spices''?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '9828f842_english_00735',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"9828f842","opensat_index":735}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best completes the sentence so that it conforms to the conventions of Standard English?',
    'multiple_choice',
    '[{"id":"A","text":"It’s a complex meditation on the nature of identity and the power of memory.","is_correct":false,"explanation":""},{"id":"B","text":"It’s a complex meditation on the nature of identity and the power of memory,","is_correct":false,"explanation":""},{"id":"C","text":"It’s a complex meditation on the nature of identity, and the power of memory.","is_correct":false,"explanation":""},{"id":"D","text":"It is a complex meditation on the nature of identity and the power of memory.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The sentence requires a finite verb to complete the main clause.  Only Choice D correctly provides this with the finite verb "is."  A comma would be needed before the conjunction "and" in Choices B and C.',
    'Review the passage and eliminate choices that contradict the text.',
    'The novel begins with a description of the protagonist’s childhood, tracing his journey from a small town to a bustling city. As the story unfolds, the protagonist encounters a series of challenges that force him to confront his past and to grapple with the complexities of modern life. While this journey is undoubtedly fraught with difficulties, the protagonist ultimately emerges as a stronger, more resilient person. But the novel’s central theme is not simply one of personal growth. Rather, it is a complex meditation on the nature of identity and the power of memory.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_6c3be97602849598_english_00736',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a3","opensat_index":736}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author’s use of the word "our" most directly suggests that the author is',
    'multiple_choice',
    '[{"id":"A","text":"highlighting the speaker’s unique perspective on the planet.","is_correct":false,"explanation":""},{"id":"B","text":"emphasizing the shared experience of the speaker and the reader.","is_correct":true,"explanation":""},{"id":"C","text":"creating a sense of urgency about the topic of the planet''s history.","is_correct":false,"explanation":""},{"id":"D","text":"referring to the planet''s history as a singular event.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The author’s use of the word "our" is most likely intended to emphasize the shared experience of the speaker and the reader, suggesting that they both have a common interest in the history of the planet. This can help create a more personal connection with the reader.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author of the passage describes the “history of our planet.” In the sentence that contains this phrase, the writer uses the word “our,” which suggests that the author is addressing the reader directly, in a way that can encourage a personal connection between the writer and the reader.  Which choice best explains why the author uses the word "our" in this context?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'c486a23b_english_00737',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"c486a23b","opensat_index":737}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following is the most effective way to combine the two sentences about the song''s message, keeping the meaning of the original text?',
    'multiple_choice',
    '[{"id":"A","text":"The song''s message is a critique of the influence of media, particularly television, on society, and a call for greater awareness and engagement—in the years since, Franti has continued to use music as a platform for social change.","is_correct":false,"explanation":""},{"id":"B","text":"The song''s message is a critique of the influence of media, particularly television, on society, and a call for greater awareness and engagement, and in the years since, Franti has continued to use music as a platform for social change.","is_correct":false,"explanation":""},{"id":"C","text":"The song''s message is a critique of the influence of media, particularly television, on society, and a call for greater awareness and engagement; in the years since, Franti has continued to use music as a platform for social change.","is_correct":true,"explanation":""},{"id":"D","text":"The song''s message is a critique of the influence of media, particularly television, on society, and a call for greater awareness and engagement, Franti has continued to use music as a platform for social change.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Choice C is the best answer. The semicolon correctly separates two closely related independent clauses, while maintaining the flow and coherence of the sentence.',
    'Review the passage and eliminate choices that contradict the text.',
    'In the late 1980s, the musician and composer Michael Franti—who is known for blending hip-hop, funk, and world music—formed a band called the Disposable Heroes of Hiphoprisy. The group’s music, which is infused with social and political themes, is often described as a blend of activism and artistry, with Franti''s lyrics often exploring themes of peace, social justice, and environmentalism. The group''s music became popular in the 1990s, with its song "Television, the Drug of the Nation" becoming a popular anthem. The song''s message is a critique of the influence of media, particularly television, on society, and a call for greater awareness and engagement. In the years since, Franti has continued to use music as a platform for social change. What is the best way to combine the two sentences about the song''s message?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'a7893d9d_english_00738',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"a7893d9d","opensat_index":738}'::jsonb
  ),
(
    gen_random_uuid(),
    'The word "however" is used to',
    'multiple_choice',
    '[{"id":"A","text":"provide a transition between contrasting ideas.","is_correct":true,"explanation":""},{"id":"B","text":"emphasize the importance of the writer’s message.","is_correct":false,"explanation":""},{"id":"C","text":"create a sense of intimacy and connection with the reader.","is_correct":false,"explanation":""},{"id":"D","text":"suggest that the writer is addressing a large audience.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The word "however" is used to signal a contrast between two ideas. The first idea is that the human body is a perfect machine. The second idea is that this assumption is incorrect. This transition helps the reader understand that the writer is about to present a different view than the one previously expressed.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author of this excerpt is describing a common misconception about the human body. The writer states that most people assume that the human body is designed to be a perfect machine. However, the text goes on to say that this assumption is incorrect, as the human body is often inefficient and can break down easily.  What is the most likely reason why the writer uses the word "however"?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_dc896ffbb109807a_english_00739',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_c5","opensat_index":739}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the word "wandered" is used to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of mystery and intrigue.","is_correct":false,"explanation":""},{"id":"B","text":"highlight the beauty and wonder of the natural world.","is_correct":false,"explanation":""},{"id":"C","text":"emphasize the narrator’s lack of direction and purpose.","is_correct":true,"explanation":""},{"id":"D","text":"suggest that the narrator is feeling lost and alone.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The word "wandered" suggests a lack of direction and purpose, which is consistent with the narrator''s state of uncertainty and confusion. The narrator is looking for guidance to regain his sense of direction, and the word "wandered" emphasizes this feeling of disorientation.',
    'Review the passage and eliminate choices that contradict the text.',
    'The narrator is describing a time when he felt disconnected and unsure, and he is looking for guidance to regain his sense of direction. The word “wandered” is used to convey a sense of confusion and disorientation, emphasizing the narrator’s state of uncertainty. What is the most likely reason why the writer uses the word "wandered"?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'a2382a1f_english_00740',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"a2382a1f","opensat_index":740}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author’s use of specific details in this passage primarily serves to',
    'multiple_choice',
    '[{"id":"A","text":"create a vivid and memorable image of the process.","is_correct":true,"explanation":""},{"id":"B","text":"explain the science behind the process.","is_correct":false,"explanation":""},{"id":"C","text":"convince the reader that the process is easy to follow.","is_correct":false,"explanation":""},{"id":"D","text":"persuade the reader to try making the food.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The author’s use of specific details helps the reader to visualize the process, making it more vivid and memorable. The details help the reader to understand the process, but they are not primarily intended to explain the science, convince the reader that the process is easy, or persuade the reader to try making the food.',
    'Review the passage and eliminate choices that contradict the text.',
    'The passage describes the process of making a particular type of food, beginning with the ingredients and ending with the final product. The author includes specific instructions and details about each step of the process. What is the most likely reason why the author provides such specific details?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '23423424_english_00741',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"23423424","opensat_index":741}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best replaces the underlined portion to create a sentence that is consistent with the conventions of standard written English?',
    'multiple_choice',
    '[{"id":"A","text":"and he had invited","is_correct":false,"explanation":""},{"id":"B","text":"he was inviting","is_correct":false,"explanation":""},{"id":"C","text":"he had invited","is_correct":true,"explanation":""},{"id":"D","text":"inviting","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The underlined portion needs a past perfect tense verb to show an action that happened before another action in the past. The past perfect tense “had invited” correctly reflects this, while the other options do not.',
    'Review the passage and eliminate choices that contradict the text.',
    'The following is a short excerpt from a historical text.  

“In 1864, the Civil War raged on, but one young soldier, Corporal Thomas Jones, dared to dream of a different life. He envisioned a world free from conflict and violence, where all people lived in harmony.  This dream, he thought, would be possible if only the two sides could learn to understand each other’s values and beliefs. Jones knew that this would be a long and difficult journey, but he resolved to start with the people in his own community. He began by organizing meetings to discuss important issues that divided the two sides of the conflict, and he invited people from both sides to participate.  Jones’s efforts were met with resistance, but he remained undeterred.”',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '4a6c98ef_english_00742',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"4a6c98ef","opensat_index":742}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the writer uses the word "I" to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of intimacy with the reader.","is_correct":false,"explanation":""},{"id":"B","text":"emphasize the importance of the writer’s message.","is_correct":false,"explanation":""},{"id":"C","text":"highlight the writer’s unique perspective on the topic.","is_correct":true,"explanation":""},{"id":"D","text":"suggest that the writer is addressing a large audience.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The writer uses the word "I" to emphasize that their interpretation is unique to them and is not necessarily shared by others. This emphasizes that their interpretation of the piece of media is based on their own experience and may not be the same for everyone.',
    'Review the passage and eliminate choices that contradict the text.',
    'The speaker, an academic, is addressing a general audience. They are talking about the impact of a specific piece of media. They cite a specific effect of the piece on the reader, but then state a possible reason that the effect would not have the same impact on everyone. They go on to emphasize that their interpretation is based on their own assumptions, which may not reflect other people''s experiences. What is the most likely reason why the writer uses the word "I"?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'f9c69993_english_00743',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"f9c69993","opensat_index":743}'::jsonb
  ),
(
    gen_random_uuid(),
    'According to the passage, what is the most significant contribution of the discovery of *Dreadnoughtus schrani* to paleontology?',
    'multiple_choice',
    '[{"id":"A","text":"It allows scientists to understand the evolution of giant dinosaurs in more detail.","is_correct":false,"explanation":""},{"id":"B","text":"It proves that giant dinosaurs could reach sizes previously thought impossible.","is_correct":true,"explanation":""},{"id":"C","text":"It provides evidence that giant dinosaurs were more common than previously thought.","is_correct":false,"explanation":""},{"id":"D","text":"It suggests that giant dinosaurs were more agile than previously thought.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The passage specifically states that the discovery of *Dreadnoughtus schrani* provides evidence that giant dinosaurs could grow to sizes previously thought impossible. This is the most significant contribution of the discovery because it challenges a long-held belief about the limitations of dinosaur size.',
    'Review the passage and eliminate choices that contradict the text.',
    'The passage describes the discovery of a new dinosaur species, *Dreadnoughtus schrani*, and its significance to paleontology.  The author writes, "Dreadnoughtus schrani is the most complete giant dinosaur ever found, a remarkable discovery that sheds light on the evolution of these enormous creatures."   The author continues, "The discovery of *Dreadnoughtus schrani*  is important because it provides evidence that giant dinosaurs could grow to sizes previously thought impossible."',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    '62478b2b_english_00744',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"62478b2b","opensat_index":744}'::jsonb
  ),
(
    gen_random_uuid(),
    'The sun was setting, the sky was ablaze with color.',
    'multiple_choice',
    '[{"id":"A","text":"The sun was setting and the sky was ablaze with color.","is_correct":false,"explanation":""},{"id":"B","text":"The sun was setting; the sky was ablaze with color.","is_correct":true,"explanation":""},{"id":"C","text":"The sun was setting, but the sky was ablaze with color.","is_correct":false,"explanation":""},{"id":"D","text":"The sun was setting; and the sky was ablaze with color.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The best way to correct a comma splice is to use a semicolon. In this case, the semicolon is being used to connect two independent clauses that are closely related. Choice A is incorrect because it uses a conjunction instead of a semicolon. Choice C is incorrect because it uses a conjunction that does not logically connect the two clauses. Choice D is incorrect because it uses a semicolon and a conjunction, which is not necessary.',
    'Review the passage and eliminate choices that contradict the text.',
    'In the following sentence, a comma splice has been used. "The sun was setting, the sky was ablaze with color." Which choice below is the best way to correct the comma splice?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'f174e85a_english_00745',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"f174e85a","opensat_index":745}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the quotation marks around the phrase "the most important feature of a good research paper is its clarity" are used to',
    'multiple_choice',
    '[{"id":"A","text":"indicate that the phrase is a direct quotation from a source.","is_correct":true,"explanation":""},{"id":"B","text":"emphasize the importance of the phrase.","is_correct":false,"explanation":""},{"id":"C","text":"show that the phrase is a common saying.","is_correct":false,"explanation":""},{"id":"D","text":"suggest that the phrase is debatable.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The quotation marks indicate that the phrase "the most important feature of a good research paper is its clarity" is a direct quotation from an outside source. This is important because it shows that the speaker is not simply expressing his or her own opinion, but is relying on the authority of an expert to support his or her argument.',
    'Review the passage and eliminate choices that contradict the text.',
    'According to experts, "the most important feature of a good research paper is its clarity." However, good research papers are not simply clear; they are also concise, well-organized, and well-supported.  The writing should be free of errors in grammar and mechanics. The argument should be logical, and the evidence should be relevant, credible, and persuasive. What is the most likely reason for the use of quotation marks?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '2a903f45_english_00746',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"2a903f45","opensat_index":746}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice combines the sentences in the paragraph in a way that is both grammatically correct and stylistically effective?',
    'multiple_choice',
    '[{"id":"A","text":"Many cultures have developed unique forms of storytelling, and the ways in which these stories are told vary widely; for example, in some cultures, stories are told orally, while in others, stories are written down. Stories can also be passed down through generations, and they can be adapted or changed as they are passed on. Whatever form they take, however, stories have the power to transport us to other places and times.","is_correct":false,"explanation":""},{"id":"B","text":"Many cultures have developed unique forms of storytelling, and the ways in which these stories are told vary widely: for example, in some cultures, stories are told orally, while in others, stories are written down. Stories can also be passed down through generations, and they can be adapted or changed as they are passed on. Whatever form they take, however, stories have the power to transport us to other places and times.","is_correct":false,"explanation":""},{"id":"C","text":"Many cultures have developed unique forms of storytelling, and the ways in which these stories are told vary widely; for example, in some cultures, stories are told orally, while in others, they are written down; stories can also be passed down through generations, and they can be adapted or changed as they are passed on. Whatever form they take, however, stories have the power to transport us to other places and times.","is_correct":false,"explanation":""},{"id":"D","text":"Many cultures have developed unique forms of storytelling, and the ways in which these stories are told vary widely. For example, in some cultures, stories are told orally, while in others, stories are written down. Stories can also be passed down through generations, and they can be adapted or changed as they are passed on; whatever form they take, however, stories have the power to transport us to other places and times.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The best way to combine the sentences in the paragraph is to use a semicolon to connect the first two sentences because the second sentence provides an example of the idea presented in the first. The semicolon is also used correctly to connect the third and fourth sentences because the fourth sentence continues the idea from the third.  A semicolon is used to connect closely related independent clauses.  A comma splice is when two independent clauses are connected with only a comma, which creates a grammatical error. A comma splice is also created when a comma is used incorrectly before a coordinating conjunction.  A comma followed by a coordinating conjunction can be used correctly to connect two independent clauses but not when the two clauses are not closely related.  A colon can be used to introduce a list but is not the correct choice here because the second sentence is not a list.  The semicolon is the most effective way to connect the sentences in this paragraph.',
    'Review the passage and eliminate choices that contradict the text.',
    'Many cultures have developed unique forms of storytelling, and the ways in which these stories are told vary widely. For example, in some cultures, stories are told orally, while in others, stories are written down. Stories can also be passed down through generations, and they can be adapted or changed as they are passed on.  Whatever form they take, however, stories have the power to transport us to other places and times.  What is the best way to combine the sentences in this paragraph?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_94c2b1b7790a108d_english_00747',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_8","opensat_index":747}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author’s use of descriptive language in this passage primarily serves to',
    'multiple_choice',
    '[{"id":"A","text":"highlight the narrator’s sense of isolation and loneliness.","is_correct":false,"explanation":""},{"id":"B","text":"create a mood of mystery and suspense.","is_correct":true,"explanation":""},{"id":"C","text":"establish the setting of the story as a rural and peaceful place.","is_correct":false,"explanation":""},{"id":"D","text":"convey the narrator’s feelings of excitement and wonder.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The author''s choice of words creates a mood of mystery and suspense by suggesting that the narrator is lost and unsure of his surroundings. This uncertainty is heightened by the vivid imagery of the "confusedly" winding path and the "sweet village" that the narrator is trying to reach.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author uses vivid imagery to describe the setting. She writes about the "sweet village of B——" and the "confusedly" winding path. She also uses words to create a sense of suspense and anticipation, such as "somewhat embarrassed" and "no longer knew." This helps the reader feel the narrator’s anxiety as he tries to find his way.',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '7239as8f_english_00748',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"7239as8f","opensat_index":748}'::jsonb
  ),
(
    gen_random_uuid(),
    'The scientists are most likely studying the impact of climate change on this species of bird because they want to',
    'multiple_choice',
    '[{"id":"A","text":"understand how the birds are adapting to changing environmental conditions.","is_correct":true,"explanation":""},{"id":"B","text":"determine whether the birds are more common in some areas than in others.","is_correct":false,"explanation":""},{"id":"C","text":"test the effects of different types of food on the birds'' health.","is_correct":false,"explanation":""},{"id":"D","text":"develop new methods for protecting the birds from predators.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The scientists are studying the impact of climate change on this species of bird to understand how the birds are adapting to changing environmental conditions. The scientists have observed that the birds are arriving at their nesting grounds earlier in the year and nesting in higher elevations than they did in the past. These changes suggest that the birds are adapting to the changing climate.',
    'Review the passage and eliminate choices that contradict the text.',
    'A group of scientists are studying the impact of climate change on a particular species of bird. The scientists have noticed that the birds are now arriving at their nesting grounds earlier in the year than they did in the past. They have also observed that the birds are nesting in higher elevations than they did in the past. The scientists are trying to determine whether these changes are due to climate change. They hypothesize that the earlier arrival of the birds is due to an earlier onset of spring, and that the higher nesting elevations are due to the birds searching for cooler temperatures as the climate warms. What is the most likely reason why the scientists are studying the impact of climate change on this species of bird?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_637f5119349a22e0_english_00749',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_b8","opensat_index":749}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;