INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'The author''s shift to a less formal tone when referring to "our nervous, sporadic games" most likely serves to',
    'multiple_choice',
    '[{"id":"A","text":"contrast the author''s informal tone with the formal tone of the rest of the passage.","is_correct":false,"explanation":""},{"id":"B","text":"indicate that the author is addressing a specific audience.","is_correct":false,"explanation":""},{"id":"C","text":"emphasize the importance of the author’s message.","is_correct":false,"explanation":""},{"id":"D","text":"create a sense of intimacy and connection with the reader.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The author''s shift to a less formal tone when referring to "our nervous, sporadic games" helps to create a sense of intimacy and connection with the reader. The author is acknowledging that the reader is part of a shared culture and experience, which can help the reader feel more engaged with the message.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author''s tone in the passage is best described as formal and objective, though there are some instances where the author conveys a more personal tone, such as when the author refers to "our nervous, sporadic games." This is an example of how the author can shift between a formal and an informal tone to make the passage more engaging for the reader. What is the most likely reason why the author refers to "our nervous, sporadic games" in a less formal tone?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'b89af982_english_01250',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"b89af982","opensat_index":1250}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the author''s use of imagery most likely serves to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of place.","is_correct":true,"explanation":""},{"id":"B","text":"evoke a particular emotion.","is_correct":false,"explanation":""},{"id":"C","text":"compare the river to something else.","is_correct":false,"explanation":""},{"id":"D","text":"explain a scientific concept.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The author''s use of the word "meandering" helps to create a vivid mental picture of the river, which helps the reader imagine the setting of the passage. This is an example of how imagery can be used to create a sense of place.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author''s use of the word "meandering" to describe the river is an example of imagery. Imagery is the use of figurative language to create a vivid sensory experience for the reader. In this case, the author uses the word "meandering" to appeal to the reader''s sense of sight, creating a mental image of a winding river. Imagery is often used to create a sense of place, and it can also be used to evoke emotions. What is the most likely reason the author chose to use imagery in this passage?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '234ds124_english_01251',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"234ds124","opensat_index":1251}'::jsonb
  ),
(
    gen_random_uuid(),
    'The study’s findings suggest that the way we experience sound is',
    'multiple_choice',
    '[{"id":"A","text":"primarily a reflection of the physical world around us.","is_correct":false,"explanation":""},{"id":"B","text":"influenced by a complex interaction between our senses and our minds.","is_correct":true,"explanation":""},{"id":"C","text":"a simple and straightforward process.","is_correct":false,"explanation":""},{"id":"D","text":"a purely internal process that is not connected to the physical world.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The researchers’ findings suggest that the way we experience sound is not simply a reflection of the physical world around us, but rather an internal process shaped by our minds and senses. The passage emphasizes this complex interaction, stating that people who have been deaf since birth experience sound in a way that is less connected to the physical world and more connected to their internal feelings and emotions.',
    'Review the passage and eliminate choices that contradict the text.',
    'A new study suggests that the way people experience the world, particularly with regards to sound, may be more complex than previously thought. The study focused on the ways in which people who have been deaf since birth experience sound compared to people who lost their hearing later in life. People who have been deaf since birth often experience sound in a way that is less connected to the physical world and more connected to their internal feelings and emotions. The researchers concluded that the experiences of people who have been deaf since birth suggest that the way we experience sound is not necessarily a simple reflection of the physical world around us, but rather an internal process shaped by a complex interaction between our senses and our minds.',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'e755b10c_english_01252',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"e755b10c","opensat_index":1252}'::jsonb
  ),
(
    gen_random_uuid(),
    'The main idea of this passage is that',
    'multiple_choice',
    '[{"id":"A","text":"it is important to be aware of the limitations of our sources of information.","is_correct":true,"explanation":""},{"id":"B","text":"it is important to be critical of the information we consume.","is_correct":false,"explanation":""},{"id":"C","text":"it is important to be aware of the different types of sources of information.","is_correct":false,"explanation":""},{"id":"D","text":"it is important to be able to identify accurate sources of information.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The text is focused on the importance of being aware of the limitations of our sources of information.  The text suggests that it is not enough to simply check the accuracy of a source, but that we should also consider the author''s motivations and potential biases. This idea suggests that there are limits to the information we can gain from any single source.',
    'Review the passage and eliminate choices that contradict the text.',
    'The text emphasizes that it is important to be aware of how the different sources of information can affect the way we see the world. The text states that one way to ensure that sources of information are trustworthy is to check their accuracy, but it also suggests that there are other factors to consider.  For example, the text suggests that we should also think about the author’s motivations and potential biases.  Which choice best represents the main idea of this passage?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_27f2e7e47d6be932_english_01253',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a9","opensat_index":1253}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author uses figurative language in this passage in order to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of realism and accuracy.","is_correct":false,"explanation":""},{"id":"B","text":"make the passage more engaging and memorable.","is_correct":true,"explanation":""},{"id":"C","text":"explain the author''s personal feelings and experiences.","is_correct":false,"explanation":""},{"id":"D","text":"suggest that the passage is about a specific time and place.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The author uses figurative language, such as describing the trees as "giants" and the river as "a ribbon of silver," to create a vivid and engaging image for the reader. This helps to make the passage more memorable and engaging.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author uses figurative language throughout the passage to create a vivid and memorable experience for the reader.  For example, the author describes the trees as "giants" and the river as "a ribbon of silver."   This use of figurative language helps to create a more vivid and engaging image for the reader, which can help to make the passage more memorable.  What is the most likely reason the author chooses to use figurative language?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'a456c789_english_01254',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"a456c789","opensat_index":1254}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following phrases would most effectively improve the clarity and precision of the sentence?',
    'multiple_choice',
    '[{"id":"A","text":"a variety of chambers","is_correct":false,"explanation":""},{"id":"B","text":"a number of chambers","is_correct":false,"explanation":""},{"id":"C","text":"several chambers","is_correct":true,"explanation":""},{"id":"D","text":"an array of chambers","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The phrase "several chambers" is the most clear and precise way to describe the multiple chambers that were used in the study. The other options are either too vague or too formal.',
    'Review the passage and eliminate choices that contradict the text.',
    'The text describes how a scientist designed and built a device to test the efficacy of a new type of medicine.  The text states that the device used "a series of chambers" that each contained a different type of medicine.  The text also mentions the number of subjects that were used in the study, the number of days that the experiment lasted, and the results of the experiment. Which of the following choices would be the best replacement for the phrase "a series of chambers" in the text?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_7340d453f88f954a_english_01255',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a2","opensat_index":1255}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author''s use of short, declarative sentences in this passage primarily serves to',
    'multiple_choice',
    '[{"id":"A","text":"emphasize the speed and dynamism of modern life in London.","is_correct":false,"explanation":""},{"id":"B","text":"create a sense of awe and wonder at the city''s grandeur.","is_correct":false,"explanation":""},{"id":"C","text":"highlight the complex and contradictory nature of London.","is_correct":true,"explanation":""},{"id":"D","text":"provide a vivid and detailed description of the city''s architecture.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The short, declarative sentences create a sense of immediacy and force, emphasizing the different, sometimes contradictory, aspects of London. This technique highlights the city''s complex and multifaceted nature.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author uses a series of short, declarative sentences to describe the city of London, each sentence focusing on a different aspect of the city. For example, the author writes: "London is a city of contrasts." "It is a city of ancient history and modern innovation." "It is a city of wealth and poverty." What is the effect of this series of short sentences?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '412c942b_english_01256',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"412c942b","opensat_index":1256}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best describes the reason Stein’s writing was often challenging and difficult to understand?',
    'multiple_choice',
    '[{"id":"A","text":"The themes of her writing were complex and abstract.","is_correct":false,"explanation":""},{"id":"B","text":"Stein’s writing was often considered controversial.","is_correct":false,"explanation":""},{"id":"C","text":"Stein used an experimental and unconventional style of writing.","is_correct":true,"explanation":""},{"id":"D","text":"Stein’s works were written in a foreign language.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The text states that Stein was a pioneer in using language in a new way and that she used repetition, short sentences, and unusual word order.  This strongly suggests that Stein’s writing was challenging and difficult to understand because it was experimental and unconventional.  The other choices are not supported by the text.',
    'Review the passage and eliminate choices that contradict the text.',
    'In the early 1900s,  the American writer Gertrude Stein was part of a group of artists and writers who worked in Paris.  She was known for her experimental and abstract writing, and her works were often challenging and difficult to understand. Stein was a pioneer in using language in a new way, and she helped to shape the course of modern literature.  Her use of repetition, short sentences, and unusual word order helped to create a sense of immediacy and directness in her writing.  What is the most likely reason why Stein’s writing was often “challenging and difficult to understand”?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'f635d36c_english_01257',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"f635d36c","opensat_index":1257}'::jsonb
  ),
(
    gen_random_uuid(),
    'A company''s reduction in reliance on fossil fuels is most likely to result in',
    'multiple_choice',
    '[{"id":"A","text":"increased air pollution.","is_correct":false,"explanation":""},{"id":"B","text":"decreased reliance on renewable energy sources.","is_correct":false,"explanation":""},{"id":"C","text":"reduced greenhouse gas emissions.","is_correct":true,"explanation":""},{"id":"D","text":"increased reliance on hydroelectric power.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The text states that reducing reliance on fossil fuels could have a positive impact on the environment. Reducing greenhouse gas emissions is a key way to improve the environment.',
    'Review the passage and eliminate choices that contradict the text.',
    'The text states that a company''s decision to reduce its reliance on fossil fuels, specifically coal, could have a positive impact on the environment. According to the text, what would likely happen if a company reduced its reliance on fossil fuels?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_a1c17da812d2f4e7_english_01258',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"random_id_a1","opensat_index":1258}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best describes the main idea of the passage?',
    'multiple_choice',
    '[{"id":"A","text":"The narrator is excited about the journey but also anxious about the unknown.","is_correct":false,"explanation":""},{"id":"B","text":"The narrator is feeling nostalgic for the island, which she has visited before.","is_correct":false,"explanation":""},{"id":"C","text":"The narrator is ambivalent about the island, feeling both drawn to and repelled by it.","is_correct":true,"explanation":""},{"id":"D","text":"The narrator is trying to convince her husband to turn back before they reach the island.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The passage uses contrasting language to describe the narrator''s feelings about the island. Words like "familiar" and "alien" as well as "drawn to" and "terrified by" highlight her ambivalence about the journey.',
    'Review the passage and eliminate choices that contradict the text.',
    'The following passage is from a novel set in the early 20th century. The narrator is a young woman who is traveling to a remote island with her husband.  The passage highlights her feelings about the island and the voyage. "My husband, a man of the sea, and I, a woman of the world, were sailing towards an island that seemed at once familiar and utterly alien, a place where the past and present were forever tangled. I had heard tales of the island’s beauty, of its verdant hills and sparkling beaches, but nothing could have prepared me for the sheer intensity of the place. I was drawn to it, yet terrified by it, a siren song calling me closer, yet threatening to swallow me whole."',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_5694ca9d10875dce_english_01259',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a7","opensat_index":1259}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best explains the author’s purpose in including this sentence? ',
    'multiple_choice',
    '[{"id":"A","text":"to argue that the Declaration of Independence was a flawed document.","is_correct":false,"explanation":""},{"id":"B","text":"to introduce the concept of natural rights as it was understood in the 18th century.","is_correct":false,"explanation":""},{"id":"C","text":"to explain how the concept of natural rights changed over time.","is_correct":true,"explanation":""},{"id":"D","text":"to suggest that the American Revolution was not about natural rights.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The author is highlighting the difference in how the concept of natural rights was understood before the Declaration of Independence was written and afterward. This sentence introduces the idea of change, which is a key point in the passage.',
    'Review the passage and eliminate choices that contradict the text.',
    'The passage discusses how the idea of “natural rights” was understood in the 18th century. The author writes: “The American Revolution, fought to secure these very rights, relied on a conception of natural rights that was quite different from what was later articulated in the Declaration of Independence.”  The most likely reason why the author includes this sentence is to',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_41ab03f93b498c0b_english_01260',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"random_id_15","opensat_index":1260}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the term "neuroplasticity" is used to',
    'multiple_choice',
    '[{"id":"A","text":"explain why the human brain is constantly evolving.","is_correct":false,"explanation":""},{"id":"B","text":"describe the process of rewiring the brain.","is_correct":true,"explanation":""},{"id":"C","text":"emphasize the importance of learning and growth.","is_correct":false,"explanation":""},{"id":"D","text":"suggest that it is never too late to learn something new.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The term "neuroplasticity" is a scientific term that refers to the brain''s ability to change and grow in response to experience. The writer uses this term to explain how the brain rewires itself to create new connections and pathways.',
    'Review the passage and eliminate choices that contradict the text.',
    'A well-known fact about the human brain is that it is constantly evolving.  Research indicates that the human brain is incredibly adaptable, able to change and grow in response to experience.  The brain’s ability to change in response to experience is known as "neuroplasticity." Neuroplasticity is a process that allows the brain to rewire itself, creating new connections and pathways as we learn and grow.  This process is particularly important in the early years of life, when the brain is developing rapidly.  However, neuroplasticity continues throughout our lives.  It’s never too late to learn something new or to change a behavior.  This ability to change is what allows us to adapt to new situations and to overcome challenges. What is the most likely reason why the writer includes the term "neuroplasticity"?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_93d9bd4863f6cad8_english_01261',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_23","opensat_index":1261}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best revises the underlined portion of the passage to create a more effective and concise sentence?',
    'multiple_choice',
    '[{"id":"A","text":"The most important thing is to learn from mistakes; I’ve made a lot of mistakes in my life, but I’ve also learned a lot from them.","is_correct":true,"explanation":""},{"id":"B","text":"The most important thing is to learn from mistakes, and I’ve made a lot of mistakes in my life, but I’ve also learned a lot from them.","is_correct":false,"explanation":""},{"id":"C","text":"The most important thing is to learn from mistakes, and I’ve made a lot of mistakes in my life, but I’ve also learned a lot from them.","is_correct":false,"explanation":""},{"id":"D","text":"The most important thing is to learn from mistakes—I’ve made a lot of mistakes in my life, but I’ve also learned a lot from them.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Choice A is the best answer because it uses a semicolon to create two independent clauses. This is a more effective way to join two independent clauses, and it makes the sentence more concise. The other choices use either a comma or a dash, which are not the correct way to join two independent clauses. Choice B uses a comma splice, which is a grammatical error. Choice C uses a comma instead of a semicolon, which is not the correct way to join two independent clauses. Choice D uses a dash, which is not the correct way to join two independent clauses.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author hopes that the reader will understand the value of learning from mistakes by emphasizing how the speaker has learned from his own experiences. This approach is shown in a paragraph in which the author writes: *The most important thing is to learn from mistakes. *I’ve made a lot of mistakes in my life, but I’ve also learned a lot from them. *I’ve learned that it’s okay to fail, and that failing can even be a good thing. *It’s okay to make mistakes, but it’s not okay to give up. *If you’re willing to learn from your mistakes, you can achieve anything you set your mind to.*',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_1858fae4bc3fb568_english_01262',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a2","opensat_index":1262}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice most effectively combines the sentences at the underlined portion without changing the meaning?',
    'multiple_choice',
    '[{"id":"A","text":"However, it was a crucial step in the development of the modern bicycle.","is_correct":false,"explanation":""},{"id":"B","text":"However, it was a very basic machine, a crucial step in the development of the modern bicycle.","is_correct":false,"explanation":""},{"id":"C","text":"However, it was a very basic machine, which was a crucial step in the development of the modern bicycle.","is_correct":false,"explanation":""},{"id":"D","text":"However, it was a very basic machine, but it was a crucial step in the development of the modern bicycle.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Choice D correctly combines the sentences by using the coordinating conjunction "but" to indicate a contrast between the two ideas.  The comma before "but" is necessary because it separates the two independent clauses within the sentence.  The other choices do not create a logical contrast between the two ideas, or they do not use the correct punctuation.',
    'Review the passage and eliminate choices that contradict the text.',
    'Although a few people have claimed to be the inventor of the modern bicycle, it was Kirkpatrick Macmillan who actually invented the velocipede, a forerunner of the modern bicycle. Macmillan, a Scottish blacksmith, built his velocipede in 1839, using wooden wheels. The velocipede was powered by the rider''s feet and could only travel in a straight line. It was a very basic machine. However, it was a crucial step in the development of the modern bicycle, which was invented several years later.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '5421a600_english_01263',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"5421a600","opensat_index":1263}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best combines the sentences at the underlined portion to make a more effective and precise use of language?',
    'multiple_choice',
    '[{"id":"A","text":"However, Meucci never sought to patent his invention, or to make it commercially available.","is_correct":false,"explanation":""},{"id":"B","text":"However, Meucci never sought to patent his invention, nor to make it commercially available.","is_correct":false,"explanation":""},{"id":"C","text":"However, Meucci never sought to patent his invention, and he never made it commercially available.","is_correct":true,"explanation":""},{"id":"D","text":"However, Meucci never sought to patent his invention; however, he never made it commercially available.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The use of the coordinating conjunction "and" is the best way to connect the two independent clauses. The use of the conjunction "or" in Choice A is incorrect because it suggests that Meucci was considering making his invention commercially available but simply did not. The use of the conjunction "nor" in Choice B is incorrect because it suggests that Meucci was considering making his invention commercially available but did not want to. The semicolon in Choice D creates a comma splice.',
    'Review the passage and eliminate choices that contradict the text.',
    'The invention of the telephone, attributed to Alexander Graham Bell, drastically changed the way people communicate. However, many people are unaware of the fact that Bell’s invention was not the only one that contributed to the development of the modern telephone.  Antonio Meucci, an Italian inventor, developed a device that could transmit sound over long distances, and his work is considered by some historians to have been a precursor to Bell’s invention.  However, Meucci never sought to patent his invention or to make it commercially available.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_70af0d3ca7b33e13_english_01264',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a9","opensat_index":1264}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following is the most effective way to combine the sentences in the underlined portion of the passage so that the passage conforms to the conventions of Standard English?',
    'multiple_choice',
    '[{"id":"A","text":"In fact, spending time in green spaces can help reduce stress and anxiety, however, some experts argue that these benefits are exaggerated.","is_correct":false,"explanation":""},{"id":"B","text":"In fact, spending time in green spaces can help reduce stress and anxiety; however, some experts argue that these benefits are exaggerated.","is_correct":false,"explanation":""},{"id":"C","text":"In fact, spending time in green spaces can help reduce stress and anxiety, some experts argue that these benefits are exaggerated, however.","is_correct":false,"explanation":""},{"id":"D","text":"In fact, spending time in green spaces can help reduce stress and anxiety, but some experts argue that these benefits are exaggerated.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Choice D is the best answer because it uses a comma plus the conjunction "but" to correctly combine the two main clauses. This creates a grammatically correct sentence that logically connects the two ideas expressed in the sentence.',
    'Review the passage and eliminate choices that contradict the text.',
    'A new study shows that people who spend more time in nature report feeling happier and more creative. In fact, spending time in green spaces can help reduce stress and anxiety. However, some experts argue that these benefits are exaggerated, and that the true source of happiness and creativity might be found in other activities, such as spending time with friends and family, or engaging in creative pursuits.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_71e64948935e91fd_english_01265',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_b8","opensat_index":1265}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author uses the word "however" to',
    'multiple_choice',
    '[{"id":"A","text":"introduce a counterargument to a previous point.","is_correct":true,"explanation":""},{"id":"B","text":"provide a personal opinion about the topic.","is_correct":false,"explanation":""},{"id":"C","text":"make a connection between two different ideas.","is_correct":false,"explanation":""},{"id":"D","text":"give a specific example to support a claim.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The author uses the word "however" to introduce a counterargument to a previous point. The author has previously argued that some historians have focused on the importance of individual people and events. However, the author then argues that it is also important to understand the broader context in which those events took place. The word "however" signals that the author is about to present a different perspective on the topic.',
    'Review the passage and eliminate choices that contradict the text.',
    'This passage is an excerpt from a book about the history of the United States. The author is discussing the different ways that people have interpreted American history. The author notes that some historians have focused on the importance of individual people and events. However, the author argues that it is also important to understand the broader context in which those events took place. What is the most likely reason why the author uses the word "however"?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_cf80594ae85f25ae_english_01266',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"random_id_e5","opensat_index":1266}'::jsonb
  ),
(
    gen_random_uuid(),
    'The phrase "for example" is used to',
    'multiple_choice',
    '[{"id":"A","text":"illustrate the key characteristics of traditional economic theory.","is_correct":false,"explanation":""},{"id":"B","text":"provide a specific example that supports a claim about behavioral economics.","is_correct":true,"explanation":""},{"id":"C","text":"introduce a distinction between behavioral economics and traditional economic theory.","is_correct":false,"explanation":""},{"id":"D","text":"compare the approaches used in behavioral economics and traditional economics.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The phrase "for example" is used to introduce an example that supports the claim made in the previous sentence. The previous sentence states that behavioral economics has shown that people may be more influenced by social factors than by rational considerations. The example provided in the following sentence illustrates this claim by mentioning that research has shown that people may be influenced by emotions, which is a social factor. Therefore, the phrase "for example" is used to provide a specific example that supports the claim about behavioral economics.',
    'Review the passage and eliminate choices that contradict the text.',
    'The passage describes how a certain type of research, namely, behavioral economics, challenges traditional economic theory. It''s given that the study of behavioral economics focuses on the ways in which people make decisions and how those decisions may deviate from those predicted by traditional economic theory. For example, the study of behavioral economics has shown that people may be more influenced by social factors, such as emotions and personal experiences, than by rational considerations. This leads researchers to conclude that traditional economic theory, based on the assumption of rational actors, may not be adequate for explaining all economic decisions and behaviors. What is the most likely reason why the writer uses the phrase "for example"?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'b897992a_english_01267',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"b897992a","opensat_index":1267}'::jsonb
  ),
(
    gen_random_uuid(),
    'The passage is primarily concerned with',
    'multiple_choice',
    '[{"id":"A","text":"the advantages and disadvantages of using technology in society.","is_correct":false,"explanation":""},{"id":"B","text":"the importance of considering the potential impacts of technology on the environment.","is_correct":true,"explanation":""},{"id":"C","text":"the way in which the introduction of new technology is often met with resistance.","is_correct":false,"explanation":""},{"id":"D","text":"the history of technological change and its impact on societies.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The passage suggests that the introduction of new technology can negatively impact the environment, and it argues that such negative impacts can be avoided by considering the potential impacts of new technologies before they are introduced. The passage does not discuss advantages and disadvantages, the history of technological change, or the resistance to new technology, which are the primary concerns of the other choices.',
    'Review the passage and eliminate choices that contradict the text.',
    'Many people, including historians, have been fascinated by the impact of technological change on societies. Although the impact of technology on society is often seen as a positive, it can have a negative effect, especially when a new technology is introduced into a society without much thought being given to its impact. For example, the introduction of new technologies to societies where traditional methods have been used for generations can have a negative impact on the environment.  Such environmental degradation, however, can be avoided by carefully considering the impact of new technologies before they are introduced. 

What is the main idea of the passage?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'f8626288_english_01268',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"f8626288","opensat_index":1268}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice completes the text so that it conforms to the conventions of Standard English?',
    'multiple_choice',
    '[{"id":"A","text":"suggests that giraffes are more intelligent than scientists had previously believed.","is_correct":false,"explanation":""},{"id":"B","text":"is not conclusive evidence that the humming sounds are an indication of intelligence.","is_correct":true,"explanation":""},{"id":"C","text":"indicates that the humming sounds are a complex form of communication, not a simple signal.","is_correct":false,"explanation":""},{"id":"D","text":"eliminates the possibility that the humming sounds are used as a simple signal.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The sentence "The fact that the giraffes only produced the humming sounds at night when they couldn’t see one another, therefore, ______" is followed by a comma, so it needs a phrase that will complete the sentence.  Choice B, "is not conclusive evidence that the humming sounds are an indication of intelligence," is the best choice because it accurately describes the research and how it supports the claim.  The other choices are incorrect because they either make an unwarranted claim or do not accurately describe the research.',
    'Review the passage and eliminate choices that contradict the text.',
    'While some scientists have argued that the ability of giraffes to make low-pitched humming sounds is a sign of intelligence, others have suggested that the humming noises are merely a form of communication between giraffes in a specific situation that doesn’t require complex thought. The researchers claim that giraffes, which have an excellent sense of vision and are able to see in color, only produce the humming sounds when it’s impossible for them to signal to one another visually, such as at night when they can’t see one another.  The fact that the giraffes only produced the humming sounds at night when they couldn’t see one another, therefore, ______',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_0ed8ac6734ab2e8f_english_01269',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"random_id_a3","opensat_index":1269}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best completes the sentence without changing the meaning? \"The protagonist is also very curious, and he is always ____ questions. One day, the protagonist discovers a mysterious object in the woods.\"',
    'multiple_choice',
    '[{"id":"A","text":"asking","is_correct":true,"explanation":""},{"id":"B","text":"asking,","is_correct":false,"explanation":""},{"id":"C","text":"asking—","is_correct":false,"explanation":""},{"id":"D","text":"asking:","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The correct answer is "asking". No punctuation is needed between a verb and its complement, as in this sentence.  A comma after "asking" would create a comma splice, and a dash or colon would be incorrect because "asking" does not introduce a list or a definition.',
    'Review the passage and eliminate choices that contradict the text.',
    'The story begins with a description of the protagonist’s childhood.  The protagonist is a young boy who lives in a small town.  He enjoys spending time with his friends, and he is always eager to learn new things.  The protagonist is also very curious, and he is always asking questions.  One day, the protagonist discovers a mysterious object in the woods.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '8519485a_english_01270',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"8519485a","opensat_index":1270}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which revision of the underlined portion of the sentence most effectively combines the two ideas presented in the sentence?',
    'multiple_choice',
    '[{"id":"A","text":"and has also created new opportunities for communication","is_correct":true,"explanation":""},{"id":"B","text":"though it has also created new opportunities for communication","is_correct":false,"explanation":""},{"id":"C","text":"despite creating new opportunities for communication","is_correct":false,"explanation":""},{"id":"D","text":"because it has also created new opportunities for communication","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Choice A is the best answer because it effectively combines the two ideas without introducing unnecessary emphasis or ambiguity. It accurately reflects the author''s point that the internet''s negative effects are offset by its positive effects. Choices B, C, and D create unnecessary contrast or implication and are not as clear and concise as Choice A.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author of the essay, a renowned historian, argues that the development of the internet has led to a decline in traditional forms of communication, such as letter writing.  However, the author is careful to point out that the internet has also created new opportunities for communication. The author does this by stating that "the internet has also created new opportunities for communication."  What is the most effective way to revise the underlined portion of the sentence?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_3c3f3411cf6c9486_english_01271',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a9","opensat_index":1271}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following revisions to the sentence above is the most effective way to combine the sentences?',
    'multiple_choice',
    '[{"id":"A","text":"The group of children is excited to visit the museum, they have been studying the history of the United States for weeks.","is_correct":false,"explanation":""},{"id":"B","text":"The group of children is excited to visit the museum and they have been studying the history of the United States for weeks.","is_correct":false,"explanation":""},{"id":"C","text":"The group of children is excited to visit the museum, having been studying the history of the United States for weeks.","is_correct":true,"explanation":""},{"id":"D","text":"The group of children is excited to visit the museum because they have been studying the history of the United States for weeks.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Choice C is the best option because it combines the two sentences using a participial phrase, "having been studying." This creates a more concise and grammatically correct sentence than the other choices. Choice A uses a comma splice, which is incorrect. Choice B creates a run-on sentence, which is also incorrect. Choice D uses a conjunction that doesn''t effectively connect the two ideas.',
    'Review the passage and eliminate choices that contradict the text.',
    'The group of children is excited to visit the museum; they have been studying the history of the United States for weeks.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '6e777d8f_english_01272',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"6e777d8f","opensat_index":1272}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice completes the text so that it conforms to the conventions of Standard English?',
    'multiple_choice',
    '[{"id":"A","text":"The African American novelist, Ernest Gaines, tells the story of an enslaved woman,","is_correct":true,"explanation":""},{"id":"B","text":"The African American novelist Ernest Gaines tells the story of an enslaved woman, ","is_correct":false,"explanation":""},{"id":"C","text":"The African American novelist, Ernest Gaines, tells the story of an enslaved woman","is_correct":false,"explanation":""},{"id":"D","text":"The African American novelist Ernest Gaines tells the story of an enslaved woman,","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Choice A correctly sets off the nonrestrictive appositive phrase  "The African American novelist, Ernest Gaines" with commas. The phrase is nonrestrictive because it provides additional information about the noun it modifies, "the African American novelist," but it is not essential to the meaning of the sentence. The comma after "Gaines" also prevents a comma splice, which is the error of joining two independent clauses with only a comma.',
    'Review the passage and eliminate choices that contradict the text.',
    'In her 1954 memoir, *The Autobiography of Miss Jane Pittman*, the African American novelist,  Ernest Gaines, tells the story of an enslaved woman,  who lives to see the end of the Jim Crow era.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '54d6446b_english_01273',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"54d6446b","opensat_index":1273}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice correctly punctuates the following sentence? The company decided, to invest in a new product line: a decision that would require significant capital.',
    'multiple_choice',
    '[{"id":"A","text":"The company decided to invest in a new product line: a decision that would require significant capital.","is_correct":false,"explanation":""},{"id":"B","text":"The company decided, to invest in a new product line; a decision that would require significant capital.","is_correct":false,"explanation":""},{"id":"C","text":"The company decided, to invest in a new product line, a decision that would require significant capital.","is_correct":false,"explanation":""},{"id":"D","text":"The company decided to invest in a new product line, a decision that would require significant capital.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The phrase “a decision that would require significant capital” is a nonessential clause that modifies the noun phrase “a new product line.” Nonessential clauses are set off with commas.  Choice A is incorrect because the colon should not be used in this context. Choice B is incorrect because the semicolon should not be used in this context. Choice C is incorrect because the comma after “product line” should be a semicolon.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'a698587d_english_01274',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"a698587d","opensat_index":1274}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;