INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'What is the main idea of the passage?',
    'multiple_choice',
    '[{"id":"A","text":"The use of music in the 1920s and 1930s reflected the changing values of society.","is_correct":true,"explanation":""},{"id":"B","text":"The use of music in the 1920s and 1930s was considered \"vulgar\" by some.","is_correct":false,"explanation":""},{"id":"C","text":"The use of music changed during the 1920s and 1930s.","is_correct":false,"explanation":""},{"id":"D","text":"The use of music in the 1930s was considered \"sophisticated\" by others.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The passage describes how the use of music in the 1920s and 1930s reflected the changing values of society. The passage also describes how the use of music changed during this time period, and how this change reflected the changing values of society.',
    'Review the passage and eliminate choices that contradict the text.',
    'The main idea of this passage is that the use of music in the 1920s was considered "vulgar" by some, and that the music of the 1930s was considered "sophisticated" by others. The passage also describes how the use of music changed during this time period, and how this change reflected the changing values of society.',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_36b6f1f48ada575d_english_00475',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"random_id_2","opensat_index":475}'::jsonb
  ),
(
    gen_random_uuid(),
    'As used in the text, what does the word “disturbed” most nearly mean?',
    'multiple_choice',
    '[{"id":"A","text":"Disorganized","is_correct":false,"explanation":""},{"id":"B","text":"Alarmed","is_correct":true,"explanation":""},{"id":"C","text":"Offended","is_correct":false,"explanation":""},{"id":"D","text":"Interrupted","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Choice B is the best answer because as used in the text, “disturbed” most nearly means alarmed. The text portrays the narrator traveling in a carriage as wolves howl in the surrounding darkness. The text contrasts the reaction of both the narrator and the horses pulling the carriage with that of the driver of the carriage: the narrator and horses are “dreadfully afraid,” but the driver is “not in the least disturbed.” In other words, the driver is not alarmed by the wolves nearby.

Choice A is incorrect. Although in some contexts, “disturbed” can mean disorganized, the text doesn’t portray a character acting in a disorganized manner; instead, the driver continues to drive the carriage, even though the horses pulling it are alarmed. Choice C is incorrect. Although in some contexts, “disturbed” can mean offended, the text doesn’t portray one character feeling offended, or upset, by another’s actions; instead, it contrasts the fear felt by the narrator with another character’s lack of fear. Choice D is incorrect. Although in some contexts, “disturbed” can mean interrupted, the text doesn’t portray an action being interrupted; indeed, the travel depicted in the scene continues despite the threat of the wolves outside the carriage.',
    'Review the passage and eliminate choices that contradict the text.',
    'The following text is from Bram Stoker’s 1897 novel Dracula. The narrator is being driven in a carriage through a remote region at night.

The baying of the wolves sounded nearer and nearer, as though they were closing round on us from every side. I grew dreadfully afraid, and the horses shared my fear. The driver, however, was not in the least disturbed; he kept turning his head to left and right, but I could not see anything through the darkness.',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '45a109a3_english_00476',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"45a109a3","opensat_index":476}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author’s use of the word “although” in the first sentence is most likely intended to',
    'multiple_choice',
    '[{"id":"A","text":"establish that the researchers’ findings were surprising and unexpected.","is_correct":false,"explanation":""},{"id":"B","text":"suggest that the researchers’ findings were controversial and debated.","is_correct":false,"explanation":""},{"id":"C","text":"highlight the contrast between the researchers’ findings and the accepted view.","is_correct":true,"explanation":""},{"id":"D","text":"emphasize the significance of the researchers’ findings.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The word "although" introduces a contrast between the researchers’ findings and the accepted view. The author is suggesting that the researchers'' findings were unexpected because they challenged the accepted view.  The use of "although" emphasizes this contrast and highlights the significance of the researchers’ findings.',
    'Review the passage and eliminate choices that contradict the text.',
    'The use of the word “although” in the first sentence of the passage is a deliberate choice made by the author. The author could have simply stated that the researchers’ findings were unexpected, but the use of the word “although” adds a layer of complexity to the sentence. What is the most likely reason why the author chose to use the word “although”?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'a3547b96_english_00477',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"a3547b96","opensat_index":477}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best completes the sentence so that it conforms to the conventions of Standard English?',
    'multiple_choice',
    '[{"id":"A","text":"As they are vastly different, their bond is unbreakable, and they support each other through thick and thin.","is_correct":false,"explanation":""},{"id":"B","text":"As they are vastly different, their bond is unbreakable, and they support each other through thick and thin.","is_correct":false,"explanation":""},{"id":"C","text":"Although they are vastly different, their bond is unbreakable, and they support each other through thick and thin.","is_correct":true,"explanation":""},{"id":"D","text":"Because they are vastly different, their bond is unbreakable, and they support each other through thick and thin.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The sentence requires a transition that indicates a contrast between the two sisters'' personalities and the strength of their bond. "Although" is the best choice to create this contrast, whereas the other choices are not appropriate.',
    'Review the passage and eliminate choices that contradict the text.',
    'The novel follows the lives of two sisters, Amelia and Beatrice, who are as different as night and day. Amelia is a bookish, introspective young woman, always lost in her thoughts, while Beatrice is vibrant and outgoing, a social butterfly who loves to be the center of attention.  While they are vastly different, their bond is unbreakable, and they support each other through thick and thin.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_175c5e506f62e2f6_english_00478',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_b7","opensat_index":478}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice provides the most effective and grammatically correct way to rewrite the underlined portion of the passage?',
    'multiple_choice',
    '[{"id":"A","text":"Sunken Ship of Uluburun","is_correct":true,"explanation":""},{"id":"B","text":"Sunken Ship, of Uluburun","is_correct":false,"explanation":""},{"id":"C","text":"Sunken Ship, Uluburun","is_correct":false,"explanation":""},{"id":"D","text":"Sunken Ship of Uluburun,","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The correct answer is A because it is the most concise and grammatically correct way to combine the three underlined words, avoiding unnecessary punctuation. Choice B uses a comma after "Ship" which is not needed. Choice C uses a comma after "Ship" and does not have a preposition following "of" which is also incorrect. Choice D incorrectly adds a comma after "Uluburun" and does not follow the rule for using commas after prepositions. ',
    'Review the passage and eliminate choices that contradict the text.',
    'The world''s oldest known intact ship, the 5,000-year-old  *Sunken*  *Ship*  of  *Uluburun,*   is  *located*  off the coast of Turkey.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_0324b94e3a0be7bd_english_00479',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_d3","opensat_index":479}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author emphasizes the difference in the approaches taken by the two groups of researchers most likely to',
    'multiple_choice',
    '[{"id":"A","text":"explain how the two groups are working together to achieve a common goal.","is_correct":false,"explanation":""},{"id":"B","text":"highlight the importance of studying both the physical and social aspects of an event.","is_correct":true,"explanation":""},{"id":"C","text":"suggest that one group’s approach is more effective than the other’s.","is_correct":false,"explanation":""},{"id":"D","text":"demonstrate that the two groups are using different research methods.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The author highlights the contrasting approaches taken by the two groups because the author is emphasizing that both the physical and social aspects of an event are important to consider. This difference in focus highlights the importance of studying both the physical and social aspects of an event.',
    'Review the passage and eliminate choices that contradict the text.',
    'The passage describes a significant difference between the approaches taken by the two groups of researchers. Both groups are studying the effects of the same event on the same ecosystem, but they are focusing on different aspects of that event. The first group is examining the impact of the event on the ecosystem’s physical environment. The second group is examining the impact of the event on the ecosystem’s social environment. This difference is highlighted by the use of contrasting language in the two passages. The first passage emphasizes the physical changes that occurred as a result of the event, while the second passage emphasizes the social changes that occurred as a result of the event. What is the most likely reason why the author highlights this difference in approach?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'e6645191_english_00480',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"e6645191","opensat_index":480}'::jsonb
  ),
(
    gen_random_uuid(),
    'The word “it” in the sentence refers to',
    'multiple_choice',
    '[{"id":"A","text":"the president’s victory.","is_correct":true,"explanation":""},{"id":"B","text":"the fact that the president was born in the United States.","is_correct":false,"explanation":""},{"id":"C","text":"the fact that a president has held office.","is_correct":false,"explanation":""},{"id":"D","text":"the history of the United States.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The word "it" refers to the event of the president’s victory. The sentence suggests that Americans are celebrating because of the president’s victory, not because of his place of birth or the history of the United States.',
    'Review the passage and eliminate choices that contradict the text.',
    'It’s the first time in recent history that an American-born president has held office.  His victory is a moment that many Americans are celebrating, as it represents a significant milestone in the history of the United States.  How is the word “it” used in the sentence?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_b4cb7bf5ce8456b7_english_00481',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"random_id_12","opensat_index":481}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the author focuses on one step of a larger process most likely because the author wants to',
    'multiple_choice',
    '[{"id":"A","text":"explain how to perform the larger process.","is_correct":false,"explanation":""},{"id":"B","text":"illustrate the complexity of the larger process.","is_correct":false,"explanation":""},{"id":"C","text":"emphasize the importance of the particular step.","is_correct":true,"explanation":""},{"id":"D","text":"suggest that the larger process is not very important.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The text describes the importance of one step of a larger process. This suggests that the author is emphasizing the importance of the particular step. The author is likely using the example to help the reader understand why this step is important.',
    'Review the passage and eliminate choices that contradict the text.',
    'The text describes a process that involves multiple steps, but the author focuses on only one of these steps. The author emphasizes how that step is crucial to the overall process.  What is the most likely reason why the author focuses on only one step in this passage?',
    'passage',
    'reading_writing',
    'Expression of Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Expression of Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Expression of Ideas']::text[],
    '2a49c11d_english_00482',
    'college_board_opensat',
    '{"opensat_domain":"Expression of Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"2a49c11d","opensat_index":482}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the phrase "as if they are missing out on something important" is used to',
    'multiple_choice',
    '[{"id":"A","text":"emphasize the speaker''s concern about the students'' dependence on technology.","is_correct":true,"explanation":""},{"id":"B","text":"describe the speaker''s feelings about the students'' lack of creativity.","is_correct":false,"explanation":""},{"id":"C","text":"suggest that the speaker is worried about the students'' future.","is_correct":false,"explanation":""},{"id":"D","text":"compare the students'' current situation to a past time.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The author uses the phrase "as if they are missing out on something important" to emphasize the speaker''s concern about the students'' dependence on technology. The speaker is suggesting that the students are missing out on something important by relying solely on technology to complete their tasks.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author of the passage is making a point about the dangers of relying solely on technology to solve problems. The passage states that the speaker is concerned about what is happening to the students who rely on technology to complete their tasks, as if they are missing out on something important. What is the most likely reason why the author uses the phrase "as if they are missing out on something important"?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    '8b3829d6_english_00483',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"8b3829d6","opensat_index":483}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice corrects the error in the sentence above?',
    'multiple_choice',
    '[{"id":"A","text":"Because, of the high-pitched sounds that flycatchers produce they have developed an exceptional sense of hearing.","is_correct":false,"explanation":""},{"id":"B","text":"Because of the high-pitched sounds that flycatchers produce, they have developed an exceptional sense of hearing.","is_correct":true,"explanation":""},{"id":"C","text":"Because of the high-pitched sounds that flycatchers produce; they have developed an exceptional sense of hearing.","is_correct":false,"explanation":""},{"id":"D","text":"Because of the high-pitched sounds that flycatchers produce, they, have developed an exceptional sense of hearing.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The sentence contains a comma splice. A comma splice occurs when two independent clauses are joined together with only a comma. To correct the sentence, we can either use a semicolon, a period, or a conjunction.  Choice B uses a comma followed by a coordinating conjunction, which corrects the comma splice.',
    'Review the passage and eliminate choices that contradict the text.',
    'The following sentence contains an error in punctuation: "Because of the high-pitched sounds that flycatchers produce, they have developed an exceptional sense of hearing."',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '8942f3d8_english_00484',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"8942f3d8","opensat_index":484}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author’s argument that "digital media makes us more conscious of the artificiality of the real" most likely serves to',
    'multiple_choice',
    '[{"id":"A","text":"contrast the author’s view of reality with the views of previous generations.","is_correct":false,"explanation":""},{"id":"B","text":"explain why digital media has a negative impact on students’ understanding of reality.","is_correct":false,"explanation":""},{"id":"C","text":"support the author’s claim that digital media has a more profound impact on students’ understanding of reality than previous generations.","is_correct":true,"explanation":""},{"id":"D","text":"provide an example of how digital media has changed students’ understanding of reality.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The author’s argument that "digital media makes us more conscious of the artificiality of the real" directly supports the claim that the current generation of students has a more complicated understanding of reality than previous generations. The author is arguing that digital media has had a profound effect on how students understand reality, which has made their understanding more complicated.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author argues that the current generation of students has a more complicated understanding of reality than previous generations, in part because of the prevalence of digital media. One reason the author gives for this is that digital media "makes us more conscious of the artificiality of the real." What is the most likely reason why the author includes this argument?',
    'passage',
    'reading_writing',
    'Expression of Ideas',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Expression of Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Expression of Ideas']::text[],
    'f8977781_english_00485',
    'college_board_opensat',
    '{"opensat_domain":"Expression of Ideas","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"f8977781","opensat_index":485}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice most effectively combines the sentences at the underlined portion to create a grammatically correct and stylistically appropriate sentence?',
    'multiple_choice',
    '[{"id":"A","text":"The teacher smiled, and pleased with their enthusiastic response began to discuss the history of the city.","is_correct":false,"explanation":""},{"id":"B","text":"The teacher smiled, pleased with their enthusiastic response, and began to discuss the history of the city.","is_correct":true,"explanation":""},{"id":"C","text":"The teacher smiled, being pleased with their enthusiastic response, and began to discuss the history of the city.","is_correct":false,"explanation":""},{"id":"D","text":"The teacher smiled, having been pleased with their enthusiastic response, and began to discuss the history of the city.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Choice B is the best option because it uses a comma to separate the introductory phrase, "pleased with their enthusiastic response," from the main clause. This creates a grammatically correct and stylistically appropriate sentence. Choice A creates a run-on sentence because it lacks necessary punctuation to separate the two independent clauses. Choice C is awkward because it uses the present participle "being" to create a modifier, and choice D is awkward because it uses the past participle "having been" to create a modifier. Both of these choices make the sentence unnecessarily wordy.',
    'Review the passage and eliminate choices that contradict the text.',
    'When the teacher asked, "What is the capital of France?" the students all shouted "Paris!" in unison. The teacher smiled, pleased with their enthusiastic response, and began to discuss the history of the city.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '12d8c11d_english_00486',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"12d8c11d","opensat_index":486}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author would most likely agree with which of the following statements about public acceptance of radical ideas?',
    'multiple_choice',
    '[{"id":"A","text":"The public is resistant to accepting ideas that challenge their established beliefs.","is_correct":true,"explanation":""},{"id":"B","text":"The public is only willing to accept radical ideas that are presented in a persuasive and compelling way.","is_correct":false,"explanation":""},{"id":"C","text":"The public is more likely to accept radical ideas that are supported by scientific evidence.","is_correct":false,"explanation":""},{"id":"D","text":"The public is more likely to accept radical ideas that are presented by experts in their field.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The passage states that the public is not ready to accept the idea that the earth is flat because the idea is too radical. This suggests that the author believes that the public is resistant to accepting ideas that challenge their established beliefs.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author''s central claim is that the public is not ready to accept the idea that the earth is flat because the idea is too radical. Which of the following statements would the author most likely agree with?',
    'passage',
    'reading_writing',
    'Expression of Ideas',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Expression of Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Expression of Ideas']::text[],
    'opensat_6cd49e113e790926_english_00487',
    'college_board_opensat',
    '{"opensat_domain":"Expression of Ideas","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"random_id_c8","opensat_index":487}'::jsonb
  ),
(
    gen_random_uuid(),
    'In this passage, the author’s use of both "true" and "a" to describe the protagonist is most likely intended to',
    'multiple_choice',
    '[{"id":"A","text":"emphasize the ambiguity of the protagonist’s actions.","is_correct":true,"explanation":""},{"id":"B","text":"suggest that the protagonist was not a true revolutionary.","is_correct":false,"explanation":""},{"id":"C","text":"create a contrast between the protagonist’s character and actions.","is_correct":false,"explanation":""},{"id":"D","text":"show that the author’s opinion of the protagonist is evolving.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'By using both "true" and "a" to describe the protagonist, the author emphasizes the ambiguity of the protagonist''s actions.  The word "true" suggests that the protagonist was a real revolutionary, while the word "a" suggests that the protagonist was simply one of many revolutionaries. This ambiguity is intentional, and it reflects the complexity of the protagonist’s character.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author of the novel states that the protagonist was a "true" revolutionary. However, that is not the only way to describe the protagonist. Although the character may have been a "true" revolutionary, the character was also described as "a" revolutionary in other parts of the book. What is the most likely reason why the author uses both "true" and "a" to describe the protagonist?',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '4743652d_english_00488',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"4743652d","opensat_index":488}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice provides the best transition between the first and second sentences?',
    'multiple_choice',
    '[{"id":"A","text":"However","is_correct":false,"explanation":""},{"id":"B","text":"For example","is_correct":true,"explanation":""},{"id":"C","text":"In contrast","is_correct":false,"explanation":""},{"id":"D","text":"Therefore","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The second sentence provides specific examples of musical genres. "For example" is the best choice to introduce these examples and show how the first sentence is supported.',
    'Review the passage and eliminate choices that contradict the text.',
    'The history of American popular music is a rich and varied one, full of experimentation and innovation.  From the earliest days of ragtime to the rise of hip-hop, musicians have constantly pushed the boundaries of what music can be.  This creative spirit is evident in the wide range of musical genres that have emerged in the United States, from jazz to rock and roll to country to electronic dance music.  No matter what your musical tastes, you’re sure to find something to enjoy in the vast and ever-evolving landscape of American popular music.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '6e26f32e_english_00489',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"6e26f32e","opensat_index":489}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author of the passage claims that',
    'multiple_choice',
    '[{"id":"A","text":"the human understanding of the natural world is often influenced by new scientific discoveries.","is_correct":true,"explanation":""},{"id":"B","text":"new scientific discoveries are often difficult and painful to accept.","is_correct":false,"explanation":""},{"id":"C","text":"new scientific discoveries have challenged our understanding of the world in a number of ways.","is_correct":false,"explanation":""},{"id":"D","text":"the human understanding of the natural world is constantly changing.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The author specifically focuses on how the human understanding of the world is shaped by new discoveries.  The passage highlights the process of re-evaluation but doesn''t make a claim about its difficulty or painfulness.  It also doesn''t claim that the world is constantly changing.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author of the passage is primarily concerned with the way in which the human understanding of the natural world is influenced by new scientific discoveries.  The author notes that new discoveries often lead to a re-evaluation of our understanding of the world around us, and that this re-evaluation can be a difficult and even painful process.  The author supports this claim by citing a number of historical examples of how new scientific discoveries have challenged our understanding of the world, such as the discovery of heliocentrism and the theory of evolution. What is the primary claim of the passage?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_8d7476449f62e05a_english_00490',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_b9","opensat_index":490}'::jsonb
  ),
(
    gen_random_uuid(),
    'This passage most likely suggests that the speaker is',
    'multiple_choice',
    '[{"id":"A","text":"a devoted dog owner.","is_correct":false,"explanation":""},{"id":"B","text":"uncomfortable around other people.","is_correct":false,"explanation":""},{"id":"C","text":"feeling isolated and alone.","is_correct":true,"explanation":""},{"id":"D","text":"concerned about the welfare of animals.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The speaker is feeling isolated and alone because they only feel like they are connecting with another living being when looking at the dog''s reflection. This suggests that the speaker is feeling disconnected from other humans.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author writes, "But the only time I see an actual, living, breathing human is when I see the dog''s reflection in the glass." What does this passage tell us about the speaker?',
    'passage',
    'reading_writing',
    'Expression of Ideas',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Expression of Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Expression of Ideas']::text[],
    'a7849c49_english_00491',
    'college_board_opensat',
    '{"opensat_domain":"Expression of Ideas","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"a7849c49","opensat_index":491}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author of this passage is most likely trying to',
    'multiple_choice',
    '[{"id":"A","text":"explain how a particular topic is currently understood.","is_correct":true,"explanation":""},{"id":"B","text":"criticize the current state of knowledge in a particular field.","is_correct":false,"explanation":""},{"id":"C","text":"advocate for a new way to approach a particular problem.","is_correct":false,"explanation":""},{"id":"D","text":"predict future developments in a particular field.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The passage describes how the topic is understood, including the fact that there is no single, universally accepted approach to it. The passage does not critique, advocate, or predict, which are all actions that would be outside of the passage’s scope.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author of the passage makes the claim that "[a particular topic] is an area where there’s been a lot of exploration." However, they go on to say that "no one has ever really managed to develop a comprehensive and complete theory."  In addition, they point out that "there are many different ways to approach the problem, and no one way is universally accepted."  What is the author’s main purpose in the passage?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_f8b829205d8628cb_english_00492',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_a3","opensat_index":492}'::jsonb
  ),
(
    gen_random_uuid(),
    'The shift to a description of the speaker''s physical environment serves to',
    'multiple_choice',
    '[{"id":"A","text":"create a sense of contrast between the speaker''s inner and outer worlds.","is_correct":false,"explanation":""},{"id":"B","text":"provide a more detailed explanation of the speaker''s feelings.","is_correct":false,"explanation":""},{"id":"C","text":"illustrate the speaker''s desire for connection.","is_correct":false,"explanation":""},{"id":"D","text":"highlight the speaker''s sense of isolation.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The description of the speaker''s physical environment serves to highlight the speaker''s sense of isolation. The details about the speaker''s surroundings suggest that the speaker is alone and isolated. The author then returns to the speaker''s feelings, showing that the speaker is longing for connection.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author begins the passage by describing the speaker''s feelings of loneliness and isolation. The author then shifts to a description of the speaker''s physical environment, using sensory details to create a vivid image for the reader. Finally, the author returns to the speaker''s feelings, focusing on the speaker''s desire for connection. What is the most likely reason why the author shifts to a description of the speaker''s physical environment?',
    'passage',
    'reading_writing',
    'Craft and Structure',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Craft and Structure',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Craft and Structure']::text[],
    'opensat_39c3c6d264c643ca_english_00493',
    'college_board_opensat',
    '{"opensat_domain":"Craft and Structure","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_c9","opensat_index":493}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following statements best summarizes the author’s view of "The Great Gatsby"?',
    'multiple_choice',
    '[{"id":"A","text":"The novel is a cautionary tale about the dangers of pursuing wealth.","is_correct":false,"explanation":""},{"id":"B","text":"The novel is a romantic story about the power of love.","is_correct":false,"explanation":""},{"id":"C","text":"The novel is a tragic story about the elusive nature of the American Dream.","is_correct":true,"explanation":""},{"id":"D","text":"The novel is a complex and multifaceted exploration of the American Dream.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The author states that the novel is about the difficulty of realizing the American Dream and that the novel is ultimately a tragic story about the unattainable nature of the American Dream. Choice C accurately summarizes the author''s view, while the other choices are either too narrow or too broad in their interpretation of the passage.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author of the passage states that the novel "The Great Gatsby" is about "the difficulty of realizing the American Dream." The author continues that "the novel explores the themes of wealth, love, and loss, and it shows how difficult it can be to achieve happiness and success." The author concludes by saying that "the novel is ultimately a tragic story about the unattainable nature of the American Dream."',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_f7fc18e72dfb0467_english_00494',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"random_id_a3","opensat_index":494}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice provides the best way to combine the second and third sentences in the passage so that it conforms to the conventions of Standard English?',
    'multiple_choice',
    '[{"id":"A","text":"The planet, which has been given the designation GJ 3470b, has a mass that is about 70% of Jupiter’s, but it orbits its star at a distance of only 1% of the distance between Jupiter and the Sun, and as a result of its close proximity to its star, GJ 3470b is estimated to have a surface temperature of more than 1,600 degrees Fahrenheit. ","is_correct":false,"explanation":""},{"id":"B","text":"The planet, which has been given the designation GJ 3470b, has a mass that is about 70% of Jupiter’s, but it orbits its star at a distance of only 1% of the distance between Jupiter and the Sun; as a result of its close proximity to its star, GJ 3470b is estimated to have a surface temperature of more than 1,600 degrees Fahrenheit. ","is_correct":false,"explanation":""},{"id":"C","text":"The planet, which has been given the designation GJ 3470b, has a mass that is about 70% of Jupiter’s, but it orbits its star at a distance of only 1% of the distance between Jupiter and the Sun; as a result, GJ 3470b is estimated to have a surface temperature of more than 1,600 degrees Fahrenheit.","is_correct":true,"explanation":""},{"id":"D","text":"The planet, which has been given the designation GJ 3470b, has a mass that is about 70% of Jupiter’s, but it orbits its star at a distance of only 1% of the distance between Jupiter and the Sun, as a result, GJ 3470b is estimated to have a surface temperature of more than 1,600 degrees Fahrenheit.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Choice C is correct because it uses a semicolon to separate two independent clauses that are closely related.  The semicolon is the best choice because the two clauses are long and contain internal punctuation; a comma would create a comma splice. Choice A is incorrect because a comma splice results from joining two independent clauses with a comma. Choice B is incorrect because a semicolon is not used correctly to separate two sentences. Choice D is incorrect because a comma is not used correctly to separate two sentences.',
    'Review the passage and eliminate choices that contradict the text.',
    'The following text is adapted from a news article about the latest discoveries in the field of astronomy.  
The discovery of a planet that is the size of Jupiter, but orbits its star in just 8.5 days, has caused astronomers to rethink what is possible, and the findings have been described as “a paradigm shift” in the field.  
The planet, which has been given the designation GJ 3470b, has a mass that is about 70% of Jupiter’s, but it orbits its star at a distance of only 1% of the distance between Jupiter and the Sun.  
As a result of its close proximity to its star, GJ 3470b is estimated to have a surface temperature of more than 1,600 degrees Fahrenheit.  The most surprising aspect of the discovery, however, is the planet’s rapid orbital speed, which can only be explained by its proximity to its host star.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'a84e518f_english_00495',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"a84e518f","opensat_index":495}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice best combines the sentences at the underlined portion to create a grammatically correct and stylistically effective sentence? ',
    'multiple_choice',
    '[{"id":"A","text":"However, the journey, beginning in 1961, was a long and arduous one, and many people worked tirelessly for years to get humans to the moon.","is_correct":false,"explanation":""},{"id":"B","text":"However, the journey, beginning in 1961, was a long and arduous one; many people worked tirelessly for years to get humans to the moon.","is_correct":true,"explanation":""},{"id":"C","text":"However, the journey, beginning in 1961, was a long and arduous one, for many people worked tirelessly for years to get humans to the moon.","is_correct":false,"explanation":""},{"id":"D","text":"However; the journey, beginning in 1961, was a long and arduous one, many people worked tirelessly for years to get humans to the moon.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The best way to combine these two independent clauses is to use a semicolon.  This punctuation creates a smooth transition between the two clauses and emphasizes the connection between the ideas.',
    'Review the passage and eliminate choices that contradict the text.',
    'The first time humans landed on the moon was a momentous occasion.  However, the journey, beginning in 1961, was a long and arduous one. Many people worked tirelessly for years to get humans to the moon. And the success of the Apollo 11 mission is a credit to the many individuals whose work made it possible.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    'opensat_f27701f741636afc_english_00496',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"random_id_e8","opensat_index":496}'::jsonb
  ),
(
    gen_random_uuid(),
    'The author of "The Lottery" uses a tone of normalcy to',
    'multiple_choice',
    '[{"id":"A","text":"make the reader question the morality of the villagers.","is_correct":false,"explanation":""},{"id":"B","text":"emphasize the shocking nature of the lottery.","is_correct":true,"explanation":""},{"id":"C","text":"create a sense of suspense and anticipation.","is_correct":false,"explanation":""},{"id":"D","text":"contrast the villagers'' peaceful lives with the violence of the lottery.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The author uses the tone of normalcy to make the violence of the lottery seem even more shocking. The contrast between the seemingly normal activities of the villagers and the sudden brutality of the lottery creates a sense of surprise and horror.',
    'Review the passage and eliminate choices that contradict the text.',
    'The story "The Lottery" by Shirley Jackson uses a tone of normalcy and routine to highlight the horror of the story''s central event.  The villagers are described as going about their everyday activities in a matter-of-fact way, which makes the sudden violence all the more shocking. What is the most likely reason that Jackson uses this tone?',
    'passage',
    'reading_writing',
    'Information and Ideas',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Information and Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Information and Ideas']::text[],
    'opensat_7d106ee9e1a52e0e_english_00497',
    'college_board_opensat',
    '{"opensat_domain":"Information and Ideas","opensat_difficulty":"Easy","section":"english","opensat_raw_id":"random_id_c8","opensat_index":497}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following pieces of evidence from the passage most directly supports the idea that the popularity of social media is related to a decline in the quality of interpersonal communication?',
    'multiple_choice',
    '[{"id":"A","text":"The author suggests that people have become less patient and more demanding in their communication habits.","is_correct":false,"explanation":""},{"id":"B","text":"The author suggests that people are more likely to be offended by criticism.","is_correct":false,"explanation":""},{"id":"C","text":"The author suggests that people are less likely to communicate in depth when they are communicating in writing.","is_correct":true,"explanation":""},{"id":"D","text":"The author suggests that people are more likely to focus on the outward appearance of their communication rather than its substance.","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The author directly connects the popularity of social media to a decline in the quality of interpersonal communication by suggesting that the rise of writing has led to a decline in depth of communication.  This is the only choice that explicitly connects social media to the quality of communication.',
    'Review the passage and eliminate choices that contradict the text.',
    'The author argues that the popularity of social media has led to a decline in the quality of interpersonal communication.  They suggest that people are less likely to communicate in depth when they are communicating in writing, and that people are more likely to focus on the outward appearance of their communication rather than its substance.  The author also suggests that people have become less patient and more demanding in their communication habits, and that they are more likely to be offended by criticism.  What is the best evidence from the passage that the popularity of social media is related to a decline in the quality of interpersonal communication?',
    'passage',
    'reading_writing',
    'Expression of Ideas',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Expression of Ideas',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Expression of Ideas']::text[],
    'opensat_5ec815c5e1f107cc_english_00498',
    'college_board_opensat',
    '{"opensat_domain":"Expression of Ideas","opensat_difficulty":"Hard","section":"english","opensat_raw_id":"random_id_c6","opensat_index":498}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which choice provides the best way to combine the sentences at the underlined portion to create a more concise and grammatically correct sentence?',
    'multiple_choice',
    '[{"id":"A","text":"In order to further their research, the team wanted to determine whether the birds’ preference for large feet is a learned behavior or an instinctive one; to this end, the researchers conducted an experiment in which some blue-footed boobies were raised in captivity and then released into the wild.","is_correct":false,"explanation":""},{"id":"B","text":"In order to further their research, the team wanted to determine whether the birds’ preference for large feet is a learned behavior or an instinctive one, the researchers conducted an experiment in which some blue-footed boobies were raised in captivity and then released into the wild.","is_correct":true,"explanation":""},{"id":"C","text":"In order to further their research, the team wanted to determine whether the birds’ preference for large feet is a learned behavior or an instinctive one, and the researchers conducted an experiment in which some blue-footed boobies were raised in captivity and then released into the wild.","is_correct":false,"explanation":""},{"id":"D","text":"In order to further their research, the team wanted to determine whether the birds’ preference for large feet is a learned behavior or an instinctive one so the researchers conducted an experiment in which some blue-footed boobies were raised in captivity and then released into the wild.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The best way to combine the sentences is to use a comma after “one” to indicate that the second clause is a dependent clause that clarifies the first clause. The semicolon is incorrect because it indicates that the two clauses are independent but of equal weight. The comma followed by “so” is incorrect because it indicates that the second clause is a dependent clause that provides a consequence of the first clause. The comma followed by “and” is incorrect because it indicates that the two clauses are independent but of equal weight, creating a run-on sentence.',
    'Review the passage and eliminate choices that contradict the text.',
    'A team of researchers has been studying the habits of a small species of bird, the blue-footed booby, in order to determine how the birds choose their mates. The researchers found that, in general, blue-footed boobies prefer to mate with individuals that have the largest feet.  The researchers theorize that larger feet may be an indicator of health and fitness.  In order to further their research, the team wanted to determine whether the birds’ preference for large feet is a learned behavior or an instinctive one.  To this end, the researchers conducted an experiment in which some blue-footed boobies were raised in captivity and then released into the wild.   To measure the birds’ preference for large feet, the researchers observed whether the birds, when given a choice between two potential mates, would choose the mate with the larger feet.  Of the twenty birds that were raised in captivity, fourteen chose the mate with the larger feet.  This finding suggests that the blue-footed booby’s preference for large feet may be an instinctive behavior, rather than a learned one.  Although the researchers’ findings do not prove their hypothesis, the results are suggestive.  However, the researchers acknowledged that their experiment had a significant limitation.  The birds were only allowed to choose between two potential mates, so it is not possible to know for certain that the birds would choose the mate with the larger feet if given more options.  Furthermore, the researchers did not consider other factors that may have influenced the birds’ mate selection, such as the birds’ age or the availability of food.  Despite these limitations, the researchers’ findings suggest that there is a genetic component to blue-footed boobies’ preference for large feet.',
    'passage',
    'reading_writing',
    'Standard English Conventions',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    false,
    'reading_writing',
    'Standard English Conventions',
    NULL,
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','english','Standard English Conventions']::text[],
    '76a4975b_english_00499',
    'college_board_opensat',
    '{"opensat_domain":"Standard English Conventions","opensat_difficulty":"Medium","section":"english","opensat_raw_id":"76a4975b","opensat_index":499}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;