INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'What is the median of the seven data values shown? 2, 2, 3, 4, 4, 11',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The median is the middle value when the data are ordered from least to greatest. Since the data are already presented in order from least to greatest, and there are 7 values, the median is the fourth value in the list, which is 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'f890dc20_math_00457',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"f890dc20","opensat_index":457}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = 2x^2 - 3x + 1$ is defined for all real numbers. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-15","is_correct":false,"explanation":""},{"id":"B","text":"-11","is_correct":false,"explanation":""},{"id":"C","text":"11","is_correct":false,"explanation":""},{"id":"D","text":"15","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substitute -2 for *x* in the function: f(-2) = 2(-2)^2 - 3(-2) + 1.  Simplify: f(-2) = 2(4) + 6 + 1 = 8 + 6 + 1 = 15.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_a6319da620cce2c2_math_00458',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c2","opensat_index":458}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following is equivalent to the expression $(x^2+1)(x^2-1)$?',
    'multiple_choice',
    '[{"id":"A","text":"x^4 - 1","is_correct":true,"explanation":""},{"id":"B","text":"x^4 + 1","is_correct":false,"explanation":""},{"id":"C","text":"x^4 + 2x^2 + 1","is_correct":false,"explanation":""},{"id":"D","text":"x^4 - 2x^2 + 1","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'This expression is in the form of the difference of squares: (a + b)(a - b) = a^2 - b^2. In this case, a = x^2 and b = 1.  Therefore, (x^2 + 1)(x^2 - 1) = (x^2)^2 - 1^2 = x^4 - 1.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '8d3b424f_math_00459',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"8d3b424f","opensat_index":459}'::jsonb
  ),
(
    gen_random_uuid(),
    'The average of 5 numbers is 12.  If 4 of the numbers are 10, 11, 13, and 14, what is the fifth number?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":false,"explanation":""},{"id":"B","text":"8","is_correct":false,"explanation":""},{"id":"C","text":"12","is_correct":false,"explanation":""},{"id":"D","text":"16","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The sum of the 5 numbers is 5 * 12 = 60.  The sum of the first 4 numbers is 10 + 11 + 13 + 14 = 48. Therefore, the fifth number is 60 - 48 = 12.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_6da9b3c5abd6e330_math_00460',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a3","opensat_index":460}'::jsonb
  ),
(
    gen_random_uuid(),
    'A bag contains 5 red marbles, 3 blue marbles, and 2 green marbles.  If a marble is chosen at random from the bag, what is the probability that the marble is blue?',
    'multiple_choice',
    '[{"id":"A","text":"1/5","is_correct":false,"explanation":""},{"id":"B","text":"1/3","is_correct":false,"explanation":""},{"id":"C","text":"3/10","is_correct":true,"explanation":""},{"id":"D","text":"2/5","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'There are 10 marbles in total.  The probability of choosing a blue marble is the number of blue marbles divided by the total number of marbles, or 3/10.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_e857b321e18ed8c2_math_00461',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"random_id_a2","opensat_index":461}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells apples and oranges. The price of an apple is $\$1.25$ and the price of an orange is $\$0.75$.  If a customer buys 3 apples and 2 oranges, how much will the customer spend in total?',
    'multiple_choice',
    '[{"id":"A","text":"$\\$5.00$","is_correct":false,"explanation":""},{"id":"B","text":"$\\$5.25$","is_correct":false,"explanation":""},{"id":"C","text":"$\\$6.00$","is_correct":false,"explanation":""},{"id":"D","text":"$\\$6.25$","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The cost of 3 apples is $3 \times $1.25 = $\$3.75$.  The cost of 2 oranges is $2 \times $0.75 = $\$1.50$.  The total cost is $\$3.75 + $1.50 = $\$5.25$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_9e34be924c23b9ca_math_00462',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c1","opensat_index":462}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a circumference of 10\pi.  What is the area of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":true,"explanation":""},{"id":"D","text":"100\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The circumference of a circle is given by C = 2\pi r, where r is the radius of the circle.  We are given that C = 10\pi, so we can solve for r: 10\pi = 2\pi r, so r = 5.  The area of a circle is given by A = \pi r^2.  Substituting r = 5, we get A = \pi (5)^2 = 25\pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_284c478963feb541_math_00463',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_d8","opensat_index":463}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of friends are planning a trip. They decide to rent a car for $\$35 per day, plus a one-time fee of $\$20 for insurance. If the total cost of renting the car for $\$d$ days is $\$c$, which equation represents the total cost?',
    'multiple_choice',
    '[{"id":"A","text":"c = 35d + 20","is_correct":true,"explanation":""},{"id":"B","text":"c = 35 + 20d","is_correct":false,"explanation":""},{"id":"C","text":"c = (35 + 20)d","is_correct":false,"explanation":""},{"id":"D","text":"c = 35d + 20d","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The daily cost is represented by 35d, and the one-time insurance fee is represented by 20.  Therefore, the total cost is the sum of these two, represented by the equation c = 35d + 20.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_6bb2cb87b313fea8_math_00464',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c1","opensat_index":464}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with center O has a radius of 5. Point P is on the circle, and line segment OP is a diameter of the circle. Point Q is on the circle such that \angle POQ = 60 degrees. What is the length of line segment PQ?',
    'multiple_choice',
    '[{"id":"A","text":"2.5","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":true,"explanation":""},{"id":"C","text":"5\\sqrt{3}","is_correct":false,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Triangle POQ is an equilateral triangle because all three sides are radii of the circle, and \angle POQ = 60 degrees.  Therefore, line segment PQ has a length of 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '841d1d98_math_00465',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"841d1d98","opensat_index":465}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people like apples, 40 people like bananas, and 20 people like both apples and bananas. How many people like only apples? ',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":true,"explanation":""},{"id":"B","text":"40","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":false,"explanation":""},{"id":"D","text":"80","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can use a Venn diagram to solve this problem. Draw two overlapping circles, one for apples and one for bananas. The overlap represents the people who like both.  Since 20 people like both, we write 20 in the overlap. Since 60 people like apples, we write 40 in the apple-only part of the apple circle.  Therefore, 40 people like only apples.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_e4b2bb509911b8bd_math_00466',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c2","opensat_index":466}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 2x - 15 = 0$, what is the sum of the solutions to this equation?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":true,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":false,"explanation":""},{"id":"D","text":"15","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The sum of the solutions to a quadratic equation in the form $ax^2 + bx + c = 0$ is given by $-b/a$.  In this case, the sum of the solutions is $-2/1 = -2$.  Therefore, the sum of the solutions to the equation $x^2 + 2x - 15 = 0$ is -2.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '8a4e419b_math_00467',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"8a4e419b","opensat_index":467}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 2x^2 - 5x + 3.  What is the value of *f*(-2)?',
    'multiple_choice',
    '[{"id":"A","text":"-21","is_correct":false,"explanation":""},{"id":"B","text":"-11","is_correct":false,"explanation":""},{"id":"C","text":"11","is_correct":false,"explanation":""},{"id":"D","text":"21","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substituting -2 for *x* in the function *f*(x) = 2x^2 - 5x + 3 yields *f*(-2) = 2(-2)^2 - 5(-2) + 3 = 8 + 10 + 3 = 21.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_c43770487c3bdca8_math_00468',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c4","opensat_index":468}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $f(x) = 3x^2 - 2x + 1$, what is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-11","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"13","is_correct":false,"explanation":""},{"id":"D","text":"17","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substitute -2 for $x$ in the function: $f(-2) = 3(-2)^2 - 2(-2) + 1$. Simplifying, we get $f(-2) = 3(4) + 4 + 1 = 12 + 4 + 1 = 17$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '37a147e1_math_00469',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"37a147e1","opensat_index":469}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the value of $x$ in the equation $x^2 - 9 = 0$?',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"-3 or 3","is_correct":true,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for $x$, we can add 9 to both sides of the equation: $x^2 = 9$. Taking the square root of both sides gives us $x = \pm 3$. Therefore, the solutions are $x = -3$ or $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '5a67db99_math_00470',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"5a67db99","opensat_index":470}'::jsonb
  ),
(
    gen_random_uuid(),
    'In a right triangle, one angle measures 30 degrees and the hypotenuse is 10 centimeters. What is the length of the shorter leg of the triangle?',
    'multiple_choice',
    '[{"id":"A","text":"5 centimeters","is_correct":true,"explanation":""},{"id":"B","text":"5\\sqrt{3} centimeters","is_correct":false,"explanation":""},{"id":"C","text":"10\\sqrt{3} centimeters","is_correct":false,"explanation":""},{"id":"D","text":"10 centimeters","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'In a 30-60-90 triangle, the shorter leg is half the length of the hypotenuse.  Therefore, the shorter leg is 10 centimeters / 2 = 5 centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_48770798498f2c34_math_00471',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c1","opensat_index":471}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 12 cm and a width of 5 cm. What is the area of the rectangle, in square cm?',
    'multiple_choice',
    '[{"id":"A","text":"60","is_correct":true,"explanation":""},{"id":"B","text":"34","is_correct":false,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"26","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The area of a rectangle is given by the formula *length* × *width*. So, in this case, the area is 12 cm × 5 cm = 60 square cm.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '927383ac_math_00472',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"927383ac","opensat_index":472}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x - 3y = 12$ and $x + 2y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":true,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for $x$, we can use elimination.  Multiplying the second equation by 3, we get $3x + 6y = 3$.  Adding this equation to the first equation, we get $5x = 15$. Dividing both sides by 5, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_63448ae422c99a5d_math_00473',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a8","opensat_index":473}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has legs of length 5 and 12. What is the length of the hypotenuse?',
    'multiple_choice',
    '[{"id":"A","text":"11","is_correct":false,"explanation":""},{"id":"B","text":"13","is_correct":true,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"19","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs.  In this case, the hypotenuse is  $\sqrt{5^2 + 12^2} = \sqrt{169} = 13$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_cef55521190560f7_math_00474',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_47","opensat_index":474}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people like apples, 40 people like oranges, and 20 people like both apples and oranges. How many people like only apples?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":true,"explanation":""},{"id":"B","text":"40","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":false,"explanation":""},{"id":"D","text":"80","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can use a Venn diagram to visualize the problem: [Venn Diagram] The 20 people who like both apples and oranges are in the overlap of the two circles.  Since 60 people like apples, and 20 of those like oranges, 60 - 20 = 40 people like only apples.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_3b1f6995e5c74f49_math_00475',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_b2","opensat_index":475}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by  *f*( *x* ) =  *x*<sup>2</sup>  +  *x*  - 2. If  *f*( *a* ) = 10, what is the value of *a*?',
    'multiple_choice',
    '[{"id":"A","text":"-4","is_correct":false,"explanation":""},{"id":"B","text":"-3","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":true,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can solve for *a* by substituting 10 for *f*( *a* ) in the equation and then solving the quadratic equation. This gives us  10 =  *a*<sup>2</sup>  +  *a*  - 2. Subtracting 10 from both sides of this equation, we get  0 =  *a*<sup>2</sup>  +  *a*  - 12. Factoring the quadratic expression, we get ( *a* + 4 )( *a* - 3 ) = 0. The solutions are *a* = -4 and *a* = 3. The value of *a* = 3 is the one that satisfies the given condition, so the answer is 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_1d9515f31bd7381e_math_00476',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_e7","opensat_index":476}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 8 centimeters and a width of 5 centimeters.  What is the area, in square centimeters, of the rectangle?',
    'multiple_choice',
    '[{"id":"A","text":"13","is_correct":false,"explanation":""},{"id":"B","text":"26","is_correct":false,"explanation":""},{"id":"C","text":"40","is_correct":true,"explanation":""},{"id":"D","text":"80","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is found by multiplying the length and width.  Therefore, the area of this rectangle is 8 * 5 = 40 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '13f17362_math_00477',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"13f17362","opensat_index":477}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $2x^2 + 5x - 3 = 0$ has two solutions. What is the sum of these two solutions?',
    'multiple_choice',
    '[{"id":"A","text":"-\\frac{5}{2}","is_correct":true,"explanation":""},{"id":"B","text":"-\\frac{3}{2}","is_correct":false,"explanation":""},{"id":"C","text":"\\frac{3}{2}","is_correct":false,"explanation":""},{"id":"D","text":"\\frac{5}{2}","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'For a quadratic equation in the form $ax^2 + bx + c = 0$, the sum of the roots (solutions) is given by $-\frac{b}{a}$. In this case, a = 2 and b = 5.  Therefore, the sum of the roots is $-\frac{5}{2}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'a3d227c8_math_00478',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"a3d227c8","opensat_index":478}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60% of them prefer apples to oranges. How many people prefer apples to oranges?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"40","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":true,"explanation":""},{"id":"D","text":"100","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find the number of people who prefer apples to oranges, we multiply the total number of people surveyed (100) by the percentage who prefer apples (60%): 100 * 0.60 = 60.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_c6c0f3ca9589f5c9_math_00479',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a4","opensat_index":479}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 12 inches and a width of 5 inches. What is the area, in square inches, of the rectangle?',
    'multiple_choice',
    '[{"id":"A","text":"17","is_correct":false,"explanation":""},{"id":"B","text":"34","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":true,"explanation":""},{"id":"D","text":"120","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is calculated by multiplying its length and width. So, the area is 12 inches * 5 inches = 60 square inches.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_de53dd0c2f55d2ae_math_00480',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c6","opensat_index":480}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x+7y=14$ and $2x-5y=1$, what is the value of $x+y$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for $x+y$, we can multiply the first equation by 5 and the second equation by 7 to eliminate $y$. This gives us $15x + 35y = 70$ and $14x - 35y = 7$. Adding these equations together, we get $29x = 77$. Solving for $x$, we find $x=\frac{77}{29}$.  Substituting this value of $x$ into the first equation, we get $3(\frac{77}{29})+7y=14$. Solving for $y$, we find $y=\frac{35}{29}$. Therefore, $x+y = \frac{77}{29} + \frac{35}{29} = \frac{112}{29} = 3\frac{25}{29}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '23c9d83a_math_00481',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"23c9d83a","opensat_index":481}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;