INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'If $3x + 2y = 17$ and $x - 2y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Adding the two equations together eliminates $y$: 

$(3x + 2y) + (x - 2y) = 17 + 1$ 

This simplifies to $4x = 18$. Dividing both sides by 4 gives us $x = \frac{18}{4}$, or $x = 4.5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_f7f14804ed132d75_math_00032',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c7","opensat_index":32}'::jsonb
  ),
(
    gen_random_uuid(),
    'If \(x + \frac{1}{x} = 3\), what is the value of \(x^2 + \frac{1}{x^2}\)?',
    'multiple_choice',
    '[{"id":"A","text":"7","is_correct":true,"explanation":""},{"id":"B","text":"9","is_correct":false,"explanation":""},{"id":"C","text":"11","is_correct":false,"explanation":""},{"id":"D","text":"13","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Squaring both sides of the equation \(x + \frac{1}{x} = 3\) gives \(x^2 + 2 + \frac{1}{x^2} = 9\). Subtracting 2 from both sides gives \(x^2 + \frac{1}{x^2} = 7\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_12e5233ccb8e63bd_math_00033',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_a5","opensat_index":33}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 2*x*<sup>2</sup> – 3*x* + 1. What is the value of *f*(–2)?',
    'multiple_choice',
    '[{"id":"A","text":"-17","is_correct":false,"explanation":""},{"id":"B","text":"-11","is_correct":false,"explanation":""},{"id":"C","text":"11","is_correct":false,"explanation":""},{"id":"D","text":"17","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'We substitute -2 for *x* in the function: *f*(–2) = 2(–2)<sup>2</sup> – 3(–2) + 1.  Simplifying, we get *f*(–2) = 2(4) + 6 + 1 = 8 + 6 + 1 = 15.  Therefore, *f*(–2) = 15.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'a23b7c3e_math_00034',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"a23b7c3e","opensat_index":34}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = \frac{x^2 - 4}{x - 2}$. For what value(s) of $x$ is $f(x)$ undefined?',
    'multiple_choice',
    '[{"id":"A","text":"x = 2","is_correct":true,"explanation":""},{"id":"B","text":"x = -2","is_correct":false,"explanation":""},{"id":"C","text":"x = 2, x = -2","is_correct":false,"explanation":""},{"id":"D","text":"All values of x","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'A function is undefined when the denominator of a fraction equals zero.  In this case, the denominator is  x - 2.  Solving for x, we find that x = 2 makes the denominator equal to zero, making the function undefined at that point. Therefore, the function f(x) is undefined for x = 2.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_34b49b522355769e_math_00035',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_5","opensat_index":35}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells apples for $1.20 per pound and oranges for $0.80 per pound. A customer buys pounds of apples and pounds of oranges. What is the total cost, in dollars, of the apples and oranges the customer bought? ',
    'multiple_choice',
    '[{"id":"A","text":"1.2x + 0.8y","is_correct":true,"explanation":""},{"id":"B","text":"1.2xy","is_correct":false,"explanation":""},{"id":"C","text":"2xy","is_correct":false,"explanation":""},{"id":"D","text":"2x + 2y","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The total cost of the apples is $1.20 times the number of pounds of apples, or 1.2x.  The total cost of the oranges is $0.80 times the number of pounds of oranges, or 0.8y.  The total cost of the apples and oranges is the sum of these two costs, or 1.2x + 0.8y.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_e5409a6434a2c684_math_00036',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c3","opensat_index":36}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined as $f(x) = \frac{x^2 - 9}{x - 3}$. For what value(s) of $x$ is $f(x)$ undefined?',
    'multiple_choice',
    '[{"id":"A","text":"x = 3 only","is_correct":true,"explanation":""},{"id":"B","text":"x = -3 only","is_correct":false,"explanation":""},{"id":"C","text":"x = 3 and x = -3","is_correct":false,"explanation":""},{"id":"D","text":"x = 0 only","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'A function is undefined when its denominator equals zero.  In this case, the denominator is $x-3$, so the function is undefined when $x-3 = 0$, which simplifies to $x=3$.  Therefore, the function is undefined for $x=3$ only.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '784322d6_math_00037',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"784322d6","opensat_index":37}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a diameter of 12 units has a chord that is 6 units long.  What is the distance, in units, from the center of the circle to the chord? ',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":true,"explanation":""},{"id":"B","text":"3$\\sqrt{3}$","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"6$\\sqrt{3}$","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'A chord of a circle divides the circle into two segments.  The line segment drawn from the center of the circle to the midpoint of the chord is perpendicular to the chord. This line segment also bisects the chord.  Since the diameter is 12 units, the radius is 6 units.  A right triangle is formed by the radius, the line segment drawn from the center of the circle to the midpoint of the chord, and half the length of the chord. This right triangle is a 30-60-90 triangle, as the hypotenuse is twice the length of the shorter leg. The shorter leg of this triangle is 3 units, and the longer leg, which is the distance from the center of the circle to the chord, is units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_3882eddbbdb630eb_math_00038',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c4","opensat_index":38}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 centimeters. A chord of the circle is 8 centimeters long. What is the distance, in centimeters, from the center of the circle to the chord?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":true,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Draw a diagram of the circle with the chord and the radius to the chord. The radius, the chord, and the line segment from the center of the circle to the midpoint of the chord form a right triangle, with the radius as the hypotenuse and the line segment from the center of the circle to the midpoint of the chord as one leg. Since the chord is 8 centimeters long, the line segment from the center of the circle to the midpoint of the chord is 4 centimeters long.  Applying the Pythagorean theorem, we get that the distance from the center of the circle to the chord is $\sqrt{5^2-4^2} = \sqrt{9} = 3$ centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_670ad2999ae769c3_math_00039',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c2","opensat_index":39}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units.  What is the area, in square units, of a sector of this circle that has a central angle of 72 degrees?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":true,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"20\\pi","is_correct":false,"explanation":""},{"id":"D","text":"50\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The area of a sector of a circle is given by (1/2) * r^2 * theta, where r is the radius and theta is the central angle in radians. We are given that the radius is 5 and the central angle is 72 degrees, which is equivalent to 72 * (\pi / 180) = 2\pi/5 radians.  Therefore, the area of the sector is (1/2) * 5^2 * (2\pi/5) = 5\pi square units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '627f145a_math_00040',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"627f145a","opensat_index":40}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve this system of equations using elimination. Multiplying the second equation by 3, we get $3x - 3y = 3$. Adding this equation to the first equation, we get $5x = 15$. Dividing both sides by 5, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '178f291d_math_00041',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"178f291d","opensat_index":41}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has legs of length 5 and 12. What is the length of the hypotenuse of this triangle?',
    'multiple_choice',
    '[{"id":"A","text":"11","is_correct":false,"explanation":""},{"id":"B","text":"13","is_correct":true,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"19","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs.  Therefore, the length of the hypotenuse is \(\sqrt{5^2 + 12^2} = \sqrt{169} = 13\)',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_a6a0188915092c4d_math_00042',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_22","opensat_index":42}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units. What is the circumference of the circle? ',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":true,"explanation":""},{"id":"C","text":"25\\pi","is_correct":false,"explanation":""},{"id":"D","text":"50\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula C = 2\pi r, where r is the radius. Substituting 5 for r, we get C = 2\pi(5) = 10\pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_a257b2ac7450cfed_math_00043',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c4","opensat_index":43}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x + 2y = 10$ and $x - 2y = 6$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":true,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve this system of equations by elimination. Notice that the y terms have opposite coefficients. Adding the two equations together, we get $(3x + 2y) + (x - 2y) = 10 + 6$, which simplifies to $4x = 16$. Dividing both sides by 4, we find $x = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_940c348cfea071b5_math_00044',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a4","opensat_index":44}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x+5 = 12$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"7","is_correct":true,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"60","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for \(x\), we subtract 5 from both sides of the equation: \(x + 5 - 5 = 12 - 5\), which simplifies to \(x = 7\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'f84da248_math_00045',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"f84da248","opensat_index":45}'::jsonb
  ),
(
    gen_random_uuid(),
    'A triangle has sides of length 5, 12, and 13. Is this triangle a right triangle? Explain your reasoning.',
    'multiple_choice',
    '[{"id":"A","text":"Yes, because the triangle satisfies the Pythagorean Theorem.","is_correct":true,"explanation":""},{"id":"B","text":"Yes, because the triangle has two equal sides.","is_correct":false,"explanation":""},{"id":"C","text":"No, because the triangle does not satisfy the Pythagorean Theorem.","is_correct":false,"explanation":""},{"id":"D","text":"No, because the triangle has one side that is longer than the sum of the other two sides.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Yes, the triangle is a right triangle because it satisfies the Pythagorean Theorem. The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the other two sides.  In this case,  5² + 12² = 25 + 144 = 169, and 13² = 169. Since the square of the longest side (13) is equal to the sum of the squares of the other two sides (5 and 12), the triangle is a right triangle.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '9f501aaf_math_00046',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"9f501aaf","opensat_index":46}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with radius 5 is inscribed in a square.  What is the area of the square?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":false,"explanation":""},{"id":"B","text":"25","is_correct":false,"explanation":""},{"id":"C","text":"50","is_correct":false,"explanation":""},{"id":"D","text":"100","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The diameter of the circle is equal to the side length of the square.  Since the radius of the circle is 5, the diameter is 10.  The area of the square is side length squared, which is 10² = 100.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '3c28f16b_math_00047',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"3c28f16b","opensat_index":47}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function \(f\) is defined by \(f(x) = 8\sqrt{x}\).  For what value of \(x\) does \(f(x) = 48\)?',
    'multiple_choice',
    '[{"id":"A","text":"6","is_correct":false,"explanation":""},{"id":"B","text":"8","is_correct":false,"explanation":""},{"id":"C","text":"36","is_correct":true,"explanation":""},{"id":"D","text":"64","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for x, we substitute 48 for f(x) in the equation f(x) = 8√x. This gives us 48 = 8√x. Dividing both sides of this equation by 8 yields 6 = √x. This can be rewritten as √x = 6. Squaring both sides of this equation yields x = 36. Therefore, the value of x for which f(x) = 48 is 36.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_09474171c6c27dc8_math_00048',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_a8","opensat_index":48}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 2x - 8 = 0$, what is the sum of the solutions to this equation?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"8","is_correct":false,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The sum of the roots of a quadratic equation in the form of $ax^2 + bx + c = 0$ is equal to $-b/a$. In this equation, $a = 1$, $b = -2$, and $c = -8$.  Therefore, the sum of the roots is $-(-2)/1 = 2$. ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_4c11bb98a40ed865_math_00049',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c8","opensat_index":49}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x + 2y = 10$ and $x - 2y = 6$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"6","is_correct":false,"explanation":""},{"id":"C","text":"8","is_correct":true,"explanation":""},{"id":"D","text":"16","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Adding the two equations together, we get  $2x = 16$. Dividing both sides of this equation by 2, we get $x = 8$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'easy'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '9479c17e_math_00050',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","opensat_difficulty":"Easy","section":"math","opensat_raw_id":"9479c17e","opensat_index":50}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people liked apples, 40 people liked oranges, and 10 people liked both apples and oranges. How many people liked only apples?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"20","is_correct":false,"explanation":""},{"id":"C","text":"50","is_correct":true,"explanation":""},{"id":"D","text":"60","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find the number of people who liked only apples, we subtract the number of people who liked both apples and oranges from the number of people who liked apples: 60 - 10 = 50.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '9827b6c3_math_00051',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"9827b6c3","opensat_index":51}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle is inscribed in a square. The area of the square is 64 square units. What is the area of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"16\\pi","is_correct":true,"explanation":""},{"id":"B","text":"32\\pi","is_correct":false,"explanation":""},{"id":"C","text":"64\\pi","is_correct":false,"explanation":""},{"id":"D","text":"128\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'If the area of the square is 64, then each side of the square is 8. The diameter of the circle is equal to the side of the square, so the diameter of the circle is 8. The radius of the circle is half the diameter, or 4. The area of the circle is \pi(r)^2 = \pi(4)^2 = 16\pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_c3df8f6e349a634c_math_00052',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"random_id_c5","opensat_index":52}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 12 centimeters and a width of 5 centimeters. What is the area, in square centimeters, of the rectangle?',
    'multiple_choice',
    '[{"id":"A","text":"17","is_correct":false,"explanation":""},{"id":"B","text":"34","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":true,"explanation":""},{"id":"D","text":"72","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is found by multiplying its length by its width.  Therefore, the area of the rectangle is 12 cm * 5 cm = 60 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_2d52711d64ed30ef_math_00053',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c7","opensat_index":53}'::jsonb
  ),
(
    gen_random_uuid(),
    'In triangle ABC, angle A measures 60 degrees, angle B measures 80 degrees, and side BC has length 10. What is the length of side AC?',
    'multiple_choice',
    '[{"id":"A","text":"5","is_correct":false,"explanation":""},{"id":"B","text":"5\\sqrt{3}","is_correct":false,"explanation":""},{"id":"C","text":"10","is_correct":false,"explanation":""},{"id":"D","text":"10\\sqrt{3}","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Triangle ABC is a 30-60-90 triangle. The ratio of the lengths of the sides of a 30-60-90 triangle is 1:√3:2. Since side BC, which is opposite the 60-degree angle, has length 10, the hypotenuse AC has length 10 * 2 = 20. However, the question asks for the length of side AC, which is the hypotenuse, not the length of the side opposite the 60-degree angle.  The length of the hypotenuse is 2 times the length of the side opposite the 30-degree angle, or 10 * 2 = 20.  Therefore, the length of side AC is 20.  Since the length of side AC is 20, the length of side AB is 10.  Therefore, the length of side AC is 10 * 2 = 20.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'hard'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '74735a92_math_00054',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","opensat_difficulty":"Hard","section":"math","opensat_raw_id":"74735a92","opensat_index":54}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the value of $x$ that satisfies the equation $\frac{x-5}{x+3} = 2$?',
    'multiple_choice',
    '[{"id":"A","text":"-11","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"11","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To solve for x, we multiply both sides of the equation by $x+3$: $(x+3) \cdot \frac{x-5}{x+3} = 2(x+3)$. This simplifies to $x-5 = 2x + 6$. Subtracting x and 6 from both sides, we get $-11 = x$, or $x = -11$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'f5943e1b_math_00055',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"f5943e1b","opensat_index":55}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 200 students found that 120 students prefer pizza, 80 students prefer burgers, and 50 students prefer both. How many students prefer neither pizza nor burgers?',
    'multiple_choice',
    '[{"id":"A","text":"30","is_correct":true,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"70","is_correct":false,"explanation":""},{"id":"D","text":"100","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Let P represent the set of students who prefer pizza, B represent the set of students who prefer burgers, and  represent the set of students who prefer both.  We know that  | = 120,  | = 80, and  | = 50. We are asked to find | , which represents the set of students who prefer neither pizza nor burgers. Using the principle of inclusion-exclusion, we have: | = | + | - | = 120 + 80 - 50 = 150.  Since there are 200 students in the survey, the number who prefer neither pizza nor burgers is 200 - 150 = 50. ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_76e0e4432391341d_math_00056',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","opensat_difficulty":"Medium","section":"math","opensat_raw_id":"random_id_c8","opensat_index":56}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;