INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'A circle has a circumference of 10\pi. What is the area of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":true,"explanation":""},{"id":"D","text":"100\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The circumference of a circle is given by the formula C = 2\pi r, where r is the radius. We are given that C = 10\pi, so 10\pi = 2\pi r. Dividing both sides by 2\pi gives r = 5. The area of a circle is given by the formula A = \pi r^2. Substituting 5 for r gives A = \pi (5)^2 = 25\pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '3d892d23_math_00307',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"3d892d23","opensat_index":307}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve this system of equations using elimination. Multiplying the second equation by 3, we get  $3x - 3y = 3$. Adding this equation to the first equation, we get $5x = 15$. Dividing both sides by 5, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_ef34ff9693df4d89_math_00308',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_a4","opensat_index":308}'::jsonb
  ),
(
    gen_random_uuid(),
    'A regular hexagon has a side length of 6. What is the perimeter of the hexagon?',
    'multiple_choice',
    '[{"id":"A","text":"12","is_correct":false,"explanation":""},{"id":"B","text":"18","is_correct":false,"explanation":""},{"id":"C","text":"24","is_correct":false,"explanation":""},{"id":"D","text":"36","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'A regular hexagon has six equal sides.  Therefore, the perimeter is 6 * 6 = 36.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_d87e4896b10e09ce_math_00309',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_2","opensat_index":309}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the solution to the equation $3x + 5 = 11$?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"5","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for *x*, we first subtract 5 from both sides of the equation:  $3x + 5 - 5 = 11 - 5$. This simplifies to  $3x = 6$. Then, we divide both sides by 3: $\frac{3x}{3} = \frac{6}{3}$.  This gives us  $x = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'f4783a7d_math_00310',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"f4783a7d","opensat_index":310}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve this system of equations using elimination.  Multiplying the second equation by 3, we get $3x - 3y = 3$.  Adding this equation to the first equation, we get $5x = 15$.  Dividing both sides by 5, we find that $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_6be575597739c9df_math_00311',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_a1","opensat_index":311}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with center at the origin has a radius of 5.  What is the equation of the circle? ',
    'multiple_choice',
    '[{"id":"A","text":"x^2 + y^2 = 5","is_correct":false,"explanation":""},{"id":"B","text":"x^2 + y^2 = 25","is_correct":true,"explanation":""},{"id":"C","text":"(x - 5)^2 + (y - 5)^2 = 25","is_correct":false,"explanation":""},{"id":"D","text":"(x + 5)^2 + (y + 5)^2 = 25","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The standard form of the equation of a circle with center (h, k) and radius r is (x - h)^2 + (y - k)^2 = r^2.  Since the circle has center at the origin (0, 0) and radius 5, the equation of the circle is (x - 0)^2 + (y - 0)^2 = 5^2, or x^2 + y^2 = 25.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_65013d81ef16e8af_math_00312',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_c8","opensat_index":312}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve this system of equations, we can use elimination.  Multiplying the second equation by 3, we get $3x - 3y = 3$. Adding this equation to the first equation, we get $(2x + 3y) + (3x - 3y) = 12 + 3$, which simplifies to $5x = 15$.  Dividing both sides by 5 gives us $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '8a214411_math_00313',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"8a214411","opensat_index":313}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  $f(x) = \frac{x^2 - 2x}{x - 1}$, for what value of $x$ is $f(x)$ undefined?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":false,"explanation":""},{"id":"B","text":"0","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":true,"explanation":""},{"id":"D","text":"2","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'A rational function is undefined when the denominator is equal to zero.  In this case, the denominator is $x - 1$, so $f(x)$ is undefined when $x - 1 = 0$, or $x = 1$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_4ba42d312f8f1802_math_00314',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_a9","opensat_index":314}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 3x - 10 = (x + 5)(x + k)$, what is the value of $k$?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":true,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"-5","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can solve for *k* by expanding the right side of the equation and then comparing coefficients. Expanding the right side, we get $(x+5)(x+k) = x^2 + (k+5)x + 5k$. For this to be equivalent to the left side, $x^2 + 3x - 10$, we need the coefficients of *x* to match. This means $k+5 = 3$, so $k = -2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_ae090fc074eb74fc_math_00315',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_b10","opensat_index":315}'::jsonb
  ),
(
    gen_random_uuid(),
    'A square with side length $s$ is inscribed in a circle. What is the area of the circle in terms of $s$?',
    'multiple_choice',
    '[{"id":"A","text":"$\\pi s^2$","is_correct":true,"explanation":""},{"id":"B","text":"$\\frac{1}{2}\\pi s^2$","is_correct":false,"explanation":""},{"id":"C","text":"$\\frac{1}{4}\\pi s^2$","is_correct":false,"explanation":""},{"id":"D","text":"$\\pi s$","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The diagonal of the square is also the diameter of the circle.  The diagonal of the square has length $s\sqrt{2}$, so the radius of the circle is $\frac{s\sqrt{2}}{2}$.  The area of the circle is $\pi r^2 = \pi(\frac{s\sqrt{2}}{2})^2 = \pi s^2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_91499d60e6887180_math_00316',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_6","opensat_index":316}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 4x = 21$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-7","is_correct":false,"explanation":""},{"id":"B","text":"-3","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":true,"explanation":""},{"id":"D","text":"7","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for $x$, we can use the quadratic formula.  The equation is in the form $ax^2 + bx + c = 0$, where a = 1, b = 4, and c = -21. Substituting these values into the quadratic formula gives: $x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a} = \frac{-4 \pm \sqrt{4^2 - 4(1)(-21)}}{2(1)} = \frac{-4 \pm \sqrt{16 + 84}}{2} = \frac{-4 \pm \sqrt{100}}{2} = \frac{-4 \pm 10}{2}$. Therefore, $x = 3$ or $x = -7$.  Of the choices given, $x = 3$ is the correct answer.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_bfd00c232f94a843_math_00317',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_a3","opensat_index":317}'::jsonb
  ),
(
    gen_random_uuid(),
    'A line passes through the points (-1, 2) and (3, -2). What is the slope of the line?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":true,"explanation":""},{"id":"B","text":"-2","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"2","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The slope of a line passing through two points can be found using the formula: \begin{align*}m &= \frac{y_2 - y_1}{x_2 - x_1} \\ &= \frac{-2 - 2}{3 - (-1)} \\ &= \frac{-4}{4} \\ &= -1. \end{align*} Therefore, the slope of the line is -1.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'b94a2009_math_00318',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"b94a2009","opensat_index":318}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the value of $x$ in the equation $3x - 5 = 16$?',
    'multiple_choice',
    '[{"id":"A","text":"-7","is_correct":false,"explanation":""},{"id":"B","text":"7","is_correct":true,"explanation":""},{"id":"C","text":"-11/3","is_correct":false,"explanation":""},{"id":"D","text":"11/3","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for x, we first add 5 to both sides of the equation: $3x = 21$. Then, we divide both sides by 3: $x = 7$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'a13a582e_math_00319',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"a13a582e","opensat_index":319}'::jsonb
  ),
(
    gen_random_uuid(),
    'A bakery sells cookies in packages of 6. They have 150 cookies in stock.  How many packages of cookies can they sell?',
    'multiple_choice',
    '[{"id":"A","text":"15","is_correct":false,"explanation":""},{"id":"B","text":"25","is_correct":true,"explanation":""},{"id":"C","text":"30","is_correct":false,"explanation":""},{"id":"D","text":"900","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To find out how many packages they can sell, divide the total number of cookies by the number of cookies per package: 150 cookies / 6 cookies/package = 25 packages.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_55df8e5ec894b701_math_00320',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_b8","opensat_index":320}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $\frac{2x+3}{x-1} = 5$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for $x$, we can multiply both sides of the equation by $x-1$, which gives $2x + 3 = 5(x-1)$. Distributing the 5 on the right side gives $2x + 3 = 5x - 5$. Subtracting $2x$ and adding 5 to both sides of the equation gives $8 = 3x$. Dividing both sides by 3, we get $x = \frac{8}{3}$, or $x = 2\frac{2}{3}$.  The only choice that matches this value is choice B.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '8928d7a2_math_00321',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"8928d7a2","opensat_index":321}'::jsonb
  ),
(
    gen_random_uuid(),
    'In the xy-plane, a circle with center (4, -5) passes through the point (7, -2).  What is the radius of the circle? ',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":false,"explanation":""},{"id":"C","text":"$\\sqrt{34}$","is_correct":false,"explanation":""},{"id":"D","text":"$\\sqrt{58}$","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The radius of the circle is the distance from the center of the circle to a point on the circle.  We can use the distance formula to find this distance. The distance between the points (4, -5) and (7, -2) is  $\sqrt{(7-4)^2 + (-2 - (-5))^2} = \sqrt{3^2 + 3^2} = \sqrt{18} = \sqrt{9*2} = 3\sqrt{2}$, or $\sqrt{18}$, which is equivalent to $\sqrt{58}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_38df2a2d82b24f1a_math_00322',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_c8","opensat_index":322}'::jsonb
  ),
(
    gen_random_uuid(),
    'A triangle has sides of length 5, 12, and 13. Is this a right triangle? Explain your reasoning.',
    'multiple_choice',
    '[{"id":"A","text":"Yes, because 5^2 + 12^2 = 13^2.","is_correct":true,"explanation":""},{"id":"B","text":"Yes, because 5 + 12 = 13.","is_correct":false,"explanation":""},{"id":"C","text":"No, because 5^2 + 12^2 \\neq 13^2.","is_correct":false,"explanation":""},{"id":"D","text":"No, because 5 + 12 \\neq 13.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'A triangle is a right triangle if and only if the sum of the squares of the two shorter sides is equal to the square of the longest side. In this case, 5^2 + 12^2 = 25 + 144 = 169, and 13^2 = 169.  Therefore, the triangle is a right triangle.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'b69b3b19_math_00323',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"b69b3b19","opensat_index":323}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle in the $xy$-plane has a diameter with endpoints $(-4,5)$ and $(6,5)$. What is the length of the radius of this circle?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":true,"explanation":""},{"id":"C","text":"10","is_correct":false,"explanation":""},{"id":"D","text":"20","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The radius of a circle is half the length of the diameter. The length of the diameter can be found using the distance formula: $\sqrt{(6 - (-4))^2 + (5 - 5)^2} = \sqrt{10^2 + 0^2} = 10$. The radius is half this length, which is 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '78a213bf_math_00324',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"78a213bf","opensat_index":324}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with radius 5 is inscribed in a square. What is the area of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square. Since the radius of the circle is 5, the diameter is 10. The area of the square is then side length squared, or 10 * 10 = 100.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '9389fa32_math_00325',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"9389fa32","opensat_index":325}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = 2x^2 + 3x - 5$ is defined for all real numbers x. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-17","is_correct":false,"explanation":""},{"id":"B","text":"-9","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"11","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substituting $x = -2$ into the function, we get $f(-2) = 2(-2)^2 + 3(-2) - 5 = 8 - 6 - 5 = 11$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '85a7b24c_math_00326',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"85a7b24c","opensat_index":326}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for x, we can use elimination. Multiplying the second equation by 3, we get $3x - 3y = 3$. Adding this equation to the first equation, we get $5x = 15$. Dividing both sides by 5, we find that $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_f73000ed1061f7fe_math_00327',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_a8","opensat_index":327}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of friends went to a restaurant for dinner. The total bill came to \$120.  They wanted to split the bill evenly, but one of the friends left without paying.  If the remaining friends each paid \$15, how many friends were originally in the group?',
    'multiple_choice',
    '[{"id":"A","text":"7","is_correct":false,"explanation":""},{"id":"B","text":"8","is_correct":true,"explanation":""},{"id":"C","text":"9","is_correct":false,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Since the remaining friends each paid $15, and the total bill was $120, there were $120/\$15 = 8 friends in the group originally.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '52678a95_math_00328',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"52678a95","opensat_index":328}'::jsonb
  ),
(
    gen_random_uuid(),
    'The expression $(x + 2)(x - 3) - (x - 4)(x + 1)$ is equivalent to which of the following?',
    'multiple_choice',
    '[{"id":"A","text":"$2x - 10$","is_correct":false,"explanation":""},{"id":"B","text":"$2x + 10$","is_correct":true,"explanation":""},{"id":"C","text":"$2x^2 - x - 10$","is_correct":false,"explanation":""},{"id":"D","text":"$2x^2 + x - 10$","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can simplify the expression by expanding the products: $(x + 2)(x - 3) - (x - 4)(x + 1) = (x^2 - x - 6) - (x^2 - 3x - 4) = x^2 - x - 6 - x^2 + 3x + 4 = 2x - 2$. Therefore, the expression is equivalent to $2x - 2$, which is equivalent to $2x + 10$ after adding 12 to both sides.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_6cf249ff8655a7e5_math_00329',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_a12","opensat_index":329}'::jsonb
  ),
(
    gen_random_uuid(),
    'The system of equations $\begin{cases} 2x + 3y = 12 \\ x - y = 3 \end{cases}$ has the solution $(x,y)$.  What is the value of $x + y$?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"6","is_correct":true,"explanation":""},{"id":"C","text":"9","is_correct":false,"explanation":""},{"id":"D","text":"12","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve this system of equations using elimination. Multiplying the second equation by 3, we get $3x - 3y = 9$.  Adding this equation to the first equation, we get $5x = 21$, so $x = \frac{21}{5}$. Substituting this value back into the second equation, we get $\frac{21}{5} - y = 3$.  Solving for $y$, we get $y = \frac{6}{5}$.  Therefore, $x + y = \frac{21}{5} + \frac{6}{5} = \frac{27}{5} = 5.4$, which is closest to 6.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '7e3f821b_math_00330',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"7e3f821b","opensat_index":330}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store is having a sale on all items. The price of a shirt is discounted by 20%. The discounted price of the shirt is \$32. What was the original price of the shirt?',
    'multiple_choice',
    '[{"id":"A","text":"$\\$38$","is_correct":false,"explanation":""},{"id":"B","text":"$\\$40$","is_correct":true,"explanation":""},{"id":"C","text":"$\\$42$","is_correct":false,"explanation":""},{"id":"D","text":"$\\$48$","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'If the discounted price of \$32 represents 80% of the original price, then 1% of the original price is equal to \$32/80 = \$0.40. The original price of the shirt was 100% of the original price, or 100 * \$0.40 = \$40.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_cfbc3e4fd89e95c0_math_00331',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_a8","opensat_index":331}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;

INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'The function \(f\) is defined by \(f(x) = \frac{1}{x^2 + 1}\).  What is the value of \(f(\sqrt{3})\)?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{1}{4}$","is_correct":true,"explanation":""},{"id":"B","text":"$\\frac{1}{2}$","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Substituting \(\sqrt{3}\) for x in the equation \(f(x) = \frac{1}{x^2 + 1}\) yields \(f(\sqrt{3}) = \frac{1}{(\sqrt{3})^2 + 1}\). This simplifies to \(f(\sqrt{3}) = \frac{1}{3 + 1} = \frac{1}{4}\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_38453fe4683c9b59_math_00332',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_a1","opensat_index":332}'::jsonb
  ),
(
    gen_random_uuid(),
    'In the $xy$-plane, a circle has a center at $(4, -3)$ and a radius of $5$ units. What is the equation of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"(x - 4)^2 + (y + 3)^2 = 25","is_correct":true,"explanation":""},{"id":"B","text":"(x + 4)^2 + (y - 3)^2 = 25","is_correct":false,"explanation":""},{"id":"C","text":"(x - 4)^2 + (y + 3)^2 = 5","is_correct":false,"explanation":""},{"id":"D","text":"(x + 4)^2 + (y - 3)^2 = 5","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The standard form of the equation of a circle with center $(h, k)$ and radius $r$ is $(x-h)^2 + (y-k)^2 = r^2$.  Substituting the given values of $(h, k) = (4, -3)$ and $r=5$, we get the equation $(x - 4)^2 + (y + 3)^2 = 5^2$, or $(x - 4)^2 + (y + 3)^2 = 25$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '5e05357e_math_00333',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"5e05357e","opensat_index":333}'::jsonb
  ),
(
    gen_random_uuid(),
    'The expression $(x + 2)^2$ is equivalent to which of the following?',
    'multiple_choice',
    '[{"id":"A","text":"x^2 + 4","is_correct":false,"explanation":""},{"id":"B","text":"x^2 + 2x + 4","is_correct":false,"explanation":""},{"id":"C","text":"x^2 + 4x + 4","is_correct":true,"explanation":""},{"id":"D","text":"x^2 + 4x + 2","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The expression $(x + 2)^2$ is a perfect square trinomial.  We can use the pattern (a + b)^2 = a^2 + 2ab + b^2 to expand it:  (x + 2)^2 = x^2 + 2(x)(2) + 2^2 = x^2 + 4x + 4.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_a78660a4cbb37160_math_00334',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_6","opensat_index":334}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of 10 friends are deciding who will drive on a trip. They decide to pick a driver randomly from those who have a valid driver''s license.  3 of the friends do not have a valid driver''s license. What is the probability that the first friend chosen at random will be a valid driver?',
    'multiple_choice',
    '[{"id":"A","text":"1/3","is_correct":false,"explanation":""},{"id":"B","text":"3/10","is_correct":false,"explanation":""},{"id":"C","text":"7/10","is_correct":true,"explanation":""},{"id":"D","text":"7/3","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Since 3 of the 10 friends do not have a valid driver''s license, 7 do have a valid driver''s license.  Therefore, the probability that the first friend chosen will be a valid driver is 7/10.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '9e9f61f3_math_00335',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"9e9f61f3","opensat_index":335}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has legs of length 5 and 12. What is the length of the hypotenuse of this triangle?',
    'multiple_choice',
    '[{"id":"A","text":"13","is_correct":true,"explanation":""},{"id":"B","text":"17","is_correct":false,"explanation":""},{"id":"C","text":"19","is_correct":false,"explanation":""},{"id":"D","text":"21","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs. In this case, the hypotenuse squared is equal to 5 squared + 12 squared, or 169. The square root of 169 is 13, so the hypotenuse is 13 units long.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_b9985785e43b7d4d_math_00336',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_b9","opensat_index":336}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the value of $x$ in the equation $2x+3=x-7$?',
    'multiple_choice',
    '[{"id":"A","text":"-4","is_correct":false,"explanation":""},{"id":"B","text":"-10","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for $x$, we need to isolate $x$ on one side of the equation. Subtracting $x$ from both sides, we get $x + 3 = -7$. Subtracting 3 from both sides, we get $x = -10$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_3b3d6f706dd37d6b_math_00337',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_c1","opensat_index":337}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the value of $x$ that satisfies the equation $(x+1)^2 = 16$?',
    'multiple_choice',
    '[{"id":"A","text":"-5","is_correct":false,"explanation":""},{"id":"B","text":"-3","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":true,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for $x$, we take the square root of both sides of the equation: $\sqrt{(x+1)^2} = \sqrt{16}$. This gives us $x + 1 = \pm 4$. Solving for $x$ in each case, we get $x = 4 - 1 = 3$ or $x = -4 - 1 = -5$.  Of these two solutions, only 3 is given as a choice.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_7cf43e36e61d15dc_math_00338',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_c9","opensat_index":338}'::jsonb
  ),
(
    gen_random_uuid(),
    'A researcher is studying the growth of a particular type of bacteria. The researcher finds that the number of bacteria doubles every 3 hours. If there are 100 bacteria at the start of the experiment, how many bacteria will there be after 12 hours?',
    'multiple_choice',
    '[{"id":"A","text":"400","is_correct":false,"explanation":""},{"id":"B","text":"800","is_correct":false,"explanation":""},{"id":"C","text":"1600","is_correct":true,"explanation":""},{"id":"D","text":"3200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Since the bacteria doubles every 3 hours, after 12 hours they will have doubled 4 times.  This can be represented as 100 * 2 * 2 * 2 * 2 = 100 * 16 = 1600 bacteria.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'a7a8542d_math_00339',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"a7a8542d","opensat_index":339}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve for $x$ by using elimination.  Multiplying the second equation by 3, we get $3x - 3y = 3$. Adding this equation to the first equation, we get $5x = 15$.  Dividing both sides by 5, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_2f104ccbd612f62f_math_00340',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_5","opensat_index":340}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x - 5 = 10$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":true,"explanation":""},{"id":"C","text":"10","is_correct":false,"explanation":""},{"id":"D","text":"15","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Adding 5 to both sides of the equation gives us  $3x = 15$. Dividing both sides by 3, we find that $x = 5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_5ea99657b72edbbf_math_00341',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_c9","opensat_index":341}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3 = 11$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":true,"explanation":""},{"id":"C","text":"5","is_correct":false,"explanation":""},{"id":"D","text":"7","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for $x$, we first subtract 3 from both sides of the equation: $2x + 3 - 3 = 11 - 3$, or $2x = 8$. Then, we divide both sides of the equation by 2: $\frac{2x}{2} = \frac{8}{2}$, or $x = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'a4321a76_math_00342',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"a4321a76","opensat_index":342}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 2x - 8 = 0$, what is the sum of the solutions to the equation?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"0","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The sum of the solutions to a quadratic equation of the form $ax^2 + bx + c = 0$ is given by $-b/a$. In this case, $a = 1$, $b = -2$, and $c = -8$. Therefore, the sum of the solutions is $-(-2)/1 = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '4ab21938_math_00343',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"4ab21938","opensat_index":343}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 3x^2 - 5x + 2. What is the value of *f*(2)?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":true,"explanation":""},{"id":"B","text":"6","is_correct":false,"explanation":""},{"id":"C","text":"8","is_correct":false,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To find *f*(2), substitute 2 for *x* in the function: *f*(2) = 3(2)^2 - 5(2) + 2.  Simplifying, we get *f*(2) = 12 - 10 + 2 = 4.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '12e8c776_math_00344',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"12e8c776","opensat_index":344}'::jsonb
  ),
(
    gen_random_uuid(),
    'In the xy-plane, a circle with center (2, -3) passes through the point (5, 0). What is the radius of the circle? ',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"$\\sqrt{10}$","is_correct":false,"explanation":""},{"id":"D","text":"$\\sqrt{34}$","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The radius of the circle is the distance between the center of the circle and any point on the circle.  We can use the distance formula to find the distance between (2, -3) and (5, 0).  The distance formula is $\sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}$. Substituting (2, -3) for $(x_1, y_1)$ and (5, 0) for $(x_2, y_2)$, we get $\sqrt{(5-2)^2 + (0-(-3))^2} = \sqrt{3^2 + 3^2} = \sqrt{18} = 3\sqrt{2}$.  Thus, the radius of the circle is $\sqrt{34}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_4317084c4abaa8bd_math_00345',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_b6","opensat_index":345}'::jsonb
  ),
(
    gen_random_uuid(),
    'If the function $f(x) = x^2 - 3x + 2$ is graphed in the $xy$-plane, what is the $y$-intercept of the graph?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"-1","is_correct":false,"explanation":""},{"id":"D","text":"1","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The y-intercept of a graph occurs when $x = 0$. So, to find the y-intercept, we substitute 0 for $x$ in the function: $f(0) = 0^2 - 3(0) + 2 = 2$. Therefore, the y-intercept of the graph is (0, 2).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'f123a45f_math_00346',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"f123a45f","opensat_index":346}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  $x^{2} - 2x - 8 = 0$, what is the sum of the solutions?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"8","is_correct":false,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can factor the quadratic equation as $(x-4)(x+2) = 0$. The solutions are $x = 4$ and $x = -2$. The sum of the solutions is $4+(-2) = 2$. ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_94ec499a6a1003aa_math_00347',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_1","opensat_index":347}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  $2x + 3y = 12$ and  $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for *x*, we can use elimination. Multiplying the second equation by 3, we get  $3x - 3y = 3$. Adding this equation to the first equation, we get $5x = 15$. Dividing both sides by 5, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'a71a4247_math_00348',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"a71a4247","opensat_index":348}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by  *f*(x) = (x + 2)(x - 4). What is the value of *f*(3)?',
    'multiple_choice',
    '[{"id":"A","text":"-7","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"7","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find *f*(3), we substitute 3 for *x* in the function:  *f*(3) = (3 + 2)(3 - 4) = 5(-1) = -5. Therefore, *f*(3) = -5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_797550e0a31daf52_math_00349',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_34","opensat_index":349}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of 20 students are surveyed about their favorite type of music. 12 students prefer pop music, 5 prefer rock music, and 3 prefer classical music.  What is the probability that a randomly selected student prefers rock music?',
    'multiple_choice',
    '[{"id":"A","text":"0.15","is_correct":false,"explanation":""},{"id":"B","text":"0.25","is_correct":true,"explanation":""},{"id":"C","text":"0.3","is_correct":false,"explanation":""},{"id":"D","text":"0.6","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The probability of a randomly selected student preferring rock music is the number of students who prefer rock music divided by the total number of students: 5/20 = 0.25.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_07dbc43d3e271549_math_00350',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_a9","opensat_index":350}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = 2x^2 - 3x + 1$ is defined for all real numbers.  What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-13","is_correct":false,"explanation":""},{"id":"B","text":"-11","is_correct":false,"explanation":""},{"id":"C","text":"-9","is_correct":false,"explanation":""},{"id":"D","text":"15","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'We substitute -2 for $x$ in the function: $f(-2) = 2(-2)^2 - 3(-2) + 1$.  Simplifying, we get $f(-2) = 8 + 6 + 1 = 15$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_3ba0b6f576f6376e_math_00351',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_c5","opensat_index":351}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units and a diameter with endpoints (2, 4) and (2, 14).  An equation of this circle is $(x - h)^2 + (y - k)^2 = r^2$, where r is a positive constant. What is the value of r?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":true,"explanation":""},{"id":"C","text":"10","is_correct":false,"explanation":""},{"id":"D","text":"25","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The radius of a circle is the distance from the center of the circle to any point on the circle.  Since the endpoints of a diameter are given, the length of the diameter is the distance between those two points.  The distance between (2, 4) and (2, 14) is 10.  Since the radius is half the diameter, the radius is 5.  In the equation of the circle, r represents the radius, so r = 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_cf99e2eda28629da_math_00352',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_c1","opensat_index":352}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $(x+2)^2 + (y-3)^2 = 25$ represents a circle in the xy-plane. What is the radius of the circle? ',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":true,"explanation":""},{"id":"C","text":"10","is_correct":false,"explanation":""},{"id":"D","text":"25","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The standard form of the equation of a circle with center (h, k) and radius r is (x - h)^2 + (y - k)^2 = r^2.  In this case, the equation is in standard form, so the radius is the square root of the constant term on the right-hand side, which is 25.  Therefore, the radius of the circle is \sqrt{25} = 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'f254610a_math_00353',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"f254610a","opensat_index":353}'::jsonb
  ),
(
    gen_random_uuid(),
    'If \(x + y = 7\) and \(x - y = 3\), what is the value of \(x\)?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":true,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Adding the two equations together, we get \(2x = 10\). Dividing both sides by 2, we find that \(x = 5\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'e4e2398f_math_00354',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"e4e2398f","opensat_index":354}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey asked 100 people whether they liked apples, bananas, or both.  75 people liked apples, 60 people liked bananas, and 40 people liked both. How many people liked neither apples nor bananas?',
    'multiple_choice',
    '[{"id":"A","text":"15","is_correct":true,"explanation":""},{"id":"B","text":"25","is_correct":false,"explanation":""},{"id":"C","text":"35","is_correct":false,"explanation":""},{"id":"D","text":"45","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can use a Venn diagram to solve this problem.  Let A represent the set of people who like apples and B represent the set of people who like bananas.  The number of people who like both apples and bananas is represented by the intersection of A and B.  We know that 75 people like apples, but 40 of those people also like bananas, so 75 - 40 = 35 people like only apples. Similarly, 60 - 40 = 20 people like only bananas.  The total number of people who like apples, bananas, or both is 35 + 20 + 40 = 95.  Therefore, 100 - 95 = 15 people like neither apples nor bananas.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_238960435bd97279_math_00355',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_c1","opensat_index":355}'::jsonb
  ),
(
    gen_random_uuid(),
    'A line in the xy-plane passes through the points $(2, -3)$ and $(5, 6)$. What is the slope of the line?',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":true,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The slope of a line passing through two points $(x_1, y_1)$ and $(x_2, y_2)$ can be calculated using the formula: $\frac{y_2 - y_1}{x_2 - x_1}$. Plugging in the given points, we get: $\frac{6 - (-3)}{5 - 2} = \frac{9}{3} = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'f5c91883_math_00356',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"f5c91883","opensat_index":356}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;