INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'A store sells two types of cookies: chocolate chip and peanut butter. The store sells 3 chocolate chip cookies for every 2 peanut butter cookies. If the store sells 45 chocolate chip cookies in a day, how many peanut butter cookies do they sell in a day?',
    'multiple_choice',
    '[{"id":"A","text":"15","is_correct":false,"explanation":""},{"id":"B","text":"22.5","is_correct":false,"explanation":""},{"id":"C","text":"30","is_correct":true,"explanation":""},{"id":"D","text":"67.5","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The ratio of chocolate chip cookies to peanut butter cookies is 3:2.  Since the store sells 45 chocolate chip cookies, which is 3 times the value of the ratio, the store must sell 2 times that value in peanut butter cookies, or 30 peanut butter cookies.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_b56beaa3bb78e306_math_00057',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_a3","opensat_index":57}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a diameter of 12 cm. What is the area of the circle, in square cm, in terms of \pi? ',
    'multiple_choice',
    '[{"id":"A","text":"12\\pi","is_correct":false,"explanation":""},{"id":"B","text":"36\\pi","is_correct":true,"explanation":""},{"id":"C","text":"72\\pi","is_correct":false,"explanation":""},{"id":"D","text":"144\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The area of a circle is given by the formula \pi r^2, where r is the radius. Since the diameter is 12 cm, the radius is 6 cm. The area of the circle is then \pi (6 cm)^2 = 36\pi square cm.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_e1033c172b83f031_math_00058',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_c8","opensat_index":58}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a circumference of $10\pi$ units. What is the area of the circle, in square units?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":true,"explanation":""},{"id":"D","text":"100\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius. We''re given that the circumference is $10\pi$, so we can solve for the radius: \begin{align*} 10\pi &= 2\pi r \\ 5 &= r  \end{align*} The area of a circle is given by the formula $A = \pi r^2$. Substituting 5 for $r$, we get $A = \pi (5)^2 = 25\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_3b5cf33cac1481ea_math_00059',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_c8","opensat_index":59}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 200 students found that 120 students prefer pizza, 80 students prefer burgers, and 50 students prefer both. How many students prefer neither pizza nor burgers?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":true,"explanation":""},{"id":"B","text":"30","is_correct":false,"explanation":""},{"id":"C","text":"50","is_correct":false,"explanation":""},{"id":"D","text":"70","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Let P represent the set of students who prefer pizza and B represent the set of students who prefer burgers. We are given that |P| = 120, |B| = 80, and |P \cap B| = 50.  We want to find |P'' \cap B''|, the number of students who prefer neither.  We can use the following formula: |P'' \cap B''| = |U| - |P \cup B| = |U| - (|P| + |B| - |P \cap B|). Since there are 200 students surveyed, we know |U| = 200.  Substituting the given values into the formula, we get |P'' \cap B''| = 200 - (120 + 80 - 50) = 200 - 150 = 50.  Therefore, the number of students who prefer neither pizza nor burgers is 50.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_f28d494a58e491f5_math_00060',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_c3","opensat_index":60}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 3x^2 - 2x + 1. What is the value of *f*(2)?',
    'multiple_choice',
    '[{"id":"A","text":"9","is_correct":false,"explanation":""},{"id":"B","text":"11","is_correct":false,"explanation":""},{"id":"C","text":"13","is_correct":true,"explanation":""},{"id":"D","text":"17","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Substitute 2 for *x* in the function: *f*(2) = 3(2)^2 - 2(2) + 1 = 3(4) - 4 + 1 = 12 - 4 + 1 = 13.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'f123456_math_00061',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"f123456","opensat_index":61}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of 100 students were surveyed about their favorite type of music. 60 students said they like pop music, 45 students said they like rock music, and 20 students said they like both pop and rock music. How many students like only pop music?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":false,"explanation":""},{"id":"B","text":"40","is_correct":true,"explanation":""},{"id":"C","text":"60","is_correct":false,"explanation":""},{"id":"D","text":"80","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can use a Venn diagram to solve this problem.  Let the circle labeled "Pop" represent all students who like pop music, and let the circle labeled "Rock" represent all students who like rock music. Since 20 students like both pop and rock music, we write "20" in the overlapping section of the circles. Since 60 students like pop music, and 20 of those also like rock music, 60 – 20 = 40 students like only pop music. Thus, the answer is 40.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_e02811712fb45260_math_00062',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_21","opensat_index":62}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells apples for $\$1.25$ each and oranges for $\$0.75$ each.  If a customer buys 3 apples and 5 oranges, how much does the customer spend in total?',
    'multiple_choice',
    '[{"id":"A","text":"$\\$6.25$","is_correct":false,"explanation":""},{"id":"B","text":"$\\$7.50$","is_correct":false,"explanation":""},{"id":"C","text":"$\\$8.75$","is_correct":true,"explanation":""},{"id":"D","text":"$\\$10.00$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The customer spends $\$1.25 \times 3 = $\$3.75$ on apples and $\$0.75 \times 5 = $\$3.75$ on oranges.  The total cost is $\$3.75 + $\$3.75 = $\$8.75$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_7bdcfe7cb0ff40eb_math_00063',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_b4","opensat_index":63}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units. What is the area of the circle, in square units? (Use $\pi$ = 3.14)',
    'multiple_choice',
    '[{"id":"A","text":"15.7","is_correct":false,"explanation":""},{"id":"B","text":"31.4","is_correct":false,"explanation":""},{"id":"C","text":"78.5","is_correct":true,"explanation":""},{"id":"D","text":"157","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula $A = \pi r^2$, where $r$ is the radius. Substituting 5 for $r$ and 3.14 for $\pi$ gives us $A = (3.14)(5)^2 = 78.5$ square units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '75da8b92_math_00064',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"75da8b92","opensat_index":64}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $\frac{x}{2} + 3 = 5$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":true,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for $x$, we first subtract 3 from both sides of the equation: $\frac{x}{2} + 3 - 3 = 5 - 3$. This gives us $\frac{x}{2} = 2$. Then, we multiply both sides of the equation by 2: $2 \cdot \frac{x}{2} = 2 \cdot 2$, which simplifies to $x = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '12d8c11d_math_00065',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"12d8c11d","opensat_index":65}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the value of  $x$ in the equation  $\frac{2x+1}{x-1} = \frac{3x-1}{x-2}$?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":false,"explanation":""},{"id":"B","text":"0","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"3","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To solve for $x$, we can cross-multiply: $(2x+1)(x-2) = (3x-1)(x-1)$. Expanding both sides gives us $2x^2 - 3x - 2 = 3x^2 - 4x + 1$. Combining like terms, we have $0 = x^2 - x + 3$. This quadratic equation doesn''t factor easily, so we can use the quadratic formula: \begin{align*} x &= \frac{-b \pm \sqrt{b^2 - 4ac}}{2a} \\\ &= \frac{1 \pm \sqrt{(-1)^2 - 4(1)(3)}}{2(1)} \\\ &= \frac{1 \pm \sqrt{-11}}{2} \end{align*} Since the discriminant is negative, the equation has no real solutions.  Therefore, the only possible value of $x$ is 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '89f638d2_math_00066',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"89f638d2","opensat_index":66}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x + 2y = 17$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":true,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for $x$, we can use elimination. Multiplying the second equation by 2, we get $2x - 2y = 2$. Adding this equation to the first equation, we get $5x = 19$. Dividing both sides by 5, we get $x = \frac{19}{5}$ or 3.8. Since the question asks for the value of $x$, and only 5 is given as a choice, the answer is 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '1915b42d_math_00067',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"1915b42d","opensat_index":67}'::jsonb
  ),
(
    gen_random_uuid(),
    'The graph of the equation $y = 2x^2 + 4x - 6$ intersects the x-axis at two points. What is the sum of the x-coordinates of these two points?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":true,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"2","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The x-intercepts of the graph occur when y = 0.  So, we need to solve the equation $2x^2 + 4x - 6 = 0$.  Dividing both sides by 2 gives us $x^2 + 2x - 3 = 0$. Factoring, we get $(x + 3)(x - 1) = 0$.  This gives us $x = -3$ or $x = 1$.  The sum of these x-coordinates is $-3 + 1 = -2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_1d3c858216df9fcd_math_00068',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_23","opensat_index":68}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm. What is the circumference of the circle in terms of $\pi$?',
    'multiple_choice',
    '[{"id":"A","text":"$\\pi$ cm","is_correct":false,"explanation":""},{"id":"B","text":"$\\pi$ cm","is_correct":false,"explanation":""},{"id":"C","text":"10$\\pi$ cm","is_correct":true,"explanation":""},{"id":"D","text":"25$\\pi$ cm","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius.  Substituting 5 for $r$ gives $C = 2\pi (5) = 10\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_ffdacbde69dd1c6b_math_00069',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_c2","opensat_index":69}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = \frac{x^2 - 4}{x - 2}$ is undefined for which value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"0","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":true,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'A function is undefined when the denominator of a fraction equals 0. In this case, the denominator $x - 2$ equals 0 when $x = 2$. Therefore, the function is undefined for $x = 2$. ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_cff70df35a05b5c6_math_00070',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_c4","opensat_index":70}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey asked 200 people whether they prefer apples or oranges. Of the 200 people surveyed, 120 people said they prefer apples. What percentage of people surveyed said they prefer oranges?',
    'multiple_choice',
    '[{"id":"A","text":"40%","is_correct":true,"explanation":""},{"id":"B","text":"60%","is_correct":false,"explanation":""},{"id":"C","text":"80%","is_correct":false,"explanation":""},{"id":"D","text":"120%","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'If 120 people prefer apples, then 200 - 120 = 80 people prefer oranges.  The percentage of people who prefer oranges is (80/200) * 100 = 40%.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '9821f84b_math_00071',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"9821f84b","opensat_index":71}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x+3y=17$ and $x-y=2$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":true,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for x, we can use elimination. Multiplying the second equation by 3, we get 3x - 3y = 6. Adding this equation to the first equation, we get 5x = 23. Dividing both sides by 5, we get x = 23/5.  Since x = 4.6, and of the choices, only 5 is close to 4.6, the answer is C.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_4f68fe027d16a2ba_math_00072',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_a1","opensat_index":72}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of students are planning a trip. They need to rent a van that costs \$60 per day. The students also need to pay a one-time fee of \$100 for insurance. Which of the following equations represents the total cost, *C*, in dollars, of renting the van for *d* days?',
    'multiple_choice',
    '[{"id":"A","text":"C = 60d + 100","is_correct":true,"explanation":""},{"id":"B","text":"C = 100d + 60","is_correct":false,"explanation":""},{"id":"C","text":"C = 60(d + 100)","is_correct":false,"explanation":""},{"id":"D","text":"C = 100(d + 60)","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The total cost is the daily rental cost times the number of days plus the insurance fee.  This can be represented by the equation C = 60d + 100.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_ab52d07629f670f1_math_00073',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_a5","opensat_index":73}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = \frac{x^2 - 4}{x-2}$. For what value(s) of $x$ is $f(x)$ undefined?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":true,"explanation":""},{"id":"B","text":"-2","is_correct":false,"explanation":""},{"id":"C","text":"2 and -2","is_correct":false,"explanation":""},{"id":"D","text":"There are no values of $x$ for which $f(x)$ is undefined.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'A function is undefined when the denominator of a fraction is zero.  In this case, the denominator is $x-2$, which equals zero when $x = 2$. Therefore, $f(x)$ is undefined when $x = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_389551c822cba24b_math_00074',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_d4","opensat_index":74}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = \frac{x^2 - 4}{x-2}$ is undefined for what value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The function is undefined when the denominator is equal to zero.  The denominator, $x-2$, is equal to zero when $x=2$. Therefore, the function is undefined for $x = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_604f487307bd80b4_math_00075',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_9","opensat_index":75}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people liked apples, 40 people liked oranges, and 20 people liked both apples and oranges. How many people liked only apples?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":true,"explanation":""},{"id":"B","text":"40","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":false,"explanation":""},{"id":"D","text":"80","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can use a Venn diagram to solve this problem.  Let A represent the set of people who like apples and O represent the set of people who like oranges.  The number of people who like both apples and oranges is the intersection of sets A and O.  Thus, 20 people like both apples and oranges, and 40 – 20 = 20 people like only oranges.  The total number of people who like apples is 60, so 60 – 20 = 40 people like only apples.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_7570d1ed0267d857_math_00076',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_c1","opensat_index":76}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle in the $xy$-plane has center $(1,2)$ and radius 3.  Which of the following is an equation of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"(x + 1)^2 + (y + 2)^2 = 3","is_correct":false,"explanation":""},{"id":"B","text":"(x - 1)^2 + (y - 2)^2 = 3","is_correct":false,"explanation":""},{"id":"C","text":"(x - 1)^2 + (y - 2)^2 = 9","is_correct":true,"explanation":""},{"id":"D","text":"(x + 1)^2 + (y + 2)^2 = 9","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The standard form of the equation of a circle with center $(h,k)$ and radius $r$ is $(x - h)^2 + (y - k)^2 = r^2$.  Substituting the given values, we get $(x - 1)^2 + (y - 2)^2 = 3^2$, or $(x - 1)^2 + (y - 2)^2 = 9$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_ca99b582f188c4b5_math_00077',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_c8","opensat_index":77}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 2x + 1 = 0$, what is the value of $x^3 + 3x^2 + 3x + 1$?',
    'multiple_choice',
    '[{"id":"A","text":"-8","is_correct":false,"explanation":""},{"id":"B","text":"0","is_correct":true,"explanation":""},{"id":"C","text":"8","is_correct":false,"explanation":""},{"id":"D","text":"16","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The expression $x^3 + 3x^2 + 3x + 1$ is a perfect cube: $(x+1)^3$.  Since $x^2 + 2x + 1 = 0$ is equivalent to $(x + 1)^2 = 0$, it follows that $x + 1 = 0$, and therefore, $(x + 1)^3 = 0^3 = 0$.  Thus, the value of $x^3 + 3x^2 + 3x + 1$ is 0.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_e8ce823015fe1c61_math_00078',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_c5","opensat_index":78}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5. What is the area of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"5$\\pi$","is_correct":false,"explanation":""},{"id":"B","text":"10$\\pi$","is_correct":false,"explanation":""},{"id":"C","text":"25$\\pi$","is_correct":true,"explanation":""},{"id":"D","text":"100$\\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula $\pi r^2$, where $r$ is the radius.  Substituting 5 for $r$, we get $\pi (5)^2 = 25\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '842454c_math_00079',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"842454c","opensat_index":79}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x = 2y + 3$ and $y = -x + 1$, what is the value of $y$?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":false,"explanation":""},{"id":"B","text":"1","is_correct":true,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"3","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve this system of equations by substitution.  Substitute the expression for $y$ from the second equation into the first equation: $x = 2(-x + 1) + 3$.  Simplifying this equation, we get $x = -2x + 2 + 3$, or $3x = 5$. Dividing both sides by 3, we find $x = \frac{5}{3}$.  Now, we can substitute this value of $x$ back into either of the original equations to solve for $y$.  Substituting into the second equation, we get $y = -\frac{5}{3} + 1$, or $y = \frac{-2}{3}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'c41b7f94_math_00080',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"c41b7f94","opensat_index":80}'::jsonb
  ),
(
    gen_random_uuid(),
    'In a right triangle, one angle measures 30 degrees, and the hypotenuse is 10 units long. What is the length of the side opposite the 30-degree angle?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":true,"explanation":""},{"id":"C","text":"5\\sqrt{3}","is_correct":false,"explanation":""},{"id":"D","text":"10\\sqrt{3}","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A 30-60-90 triangle has side ratios of 1:√3:2.  Since the hypotenuse is 10 units, the side opposite the 30-degree angle is half the length of the hypotenuse, which is 10/2 = 5 units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_768929148a3ca4c2_math_00081',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_a9","opensat_index":81}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;

INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'A circle is inscribed in a square with side length 8. What is the area of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"8\\pi","is_correct":false,"explanation":""},{"id":"B","text":"16\\pi","is_correct":true,"explanation":""},{"id":"C","text":"32\\pi","is_correct":false,"explanation":""},{"id":"D","text":"64\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The diameter of the circle is equal to the side length of the square, which is 8. Therefore, the radius of the circle is 4. The area of the circle is $\pi r^2 = \pi(4)^2 = 16\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'e55931d8_math_00082',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"e55931d8","opensat_index":82}'::jsonb
  ),
(
    gen_random_uuid(),
    'In a right triangle, one acute angle measures 30 degrees.  If the length of the hypotenuse is 10, what is the length of the side opposite the 30 degree angle?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":true,"explanation":""},{"id":"C","text":"5\\sqrt{3}","is_correct":false,"explanation":""},{"id":"D","text":"10\\sqrt{3}","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A 30-60-90 triangle has side lengths in the ratio 1 : \sqrt{3} : 2.  Since the hypotenuse has length 10, the side opposite the 30 degree angle has length 10 / 2 = 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_c8d6a5fcc42a976e_math_00083',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_c1","opensat_index":83}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by \(f(x) = x^2 + 3x - 10\). What is the value of *f*(2)?',
    'multiple_choice',
    '[{"id":"A","text":"-4","is_correct":false,"explanation":""},{"id":"B","text":"0","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"12","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find *f*(2), we substitute 2 for *x* in the function''s definition: *f*(2) = (2)^2 + 3(2) - 10 = 4 + 6 - 10 = 12.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_e5cebe2ea2024c2b_math_00084',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_d6","opensat_index":84}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells apples for $2 per pound and oranges for $1.50 per pound. A customer buys 3 pounds of apples and 2 pounds of oranges. What is the total cost of the apples and oranges?',
    'multiple_choice',
    '[{"id":"A","text":"$7.00","is_correct":false,"explanation":""},{"id":"B","text":"$7.50","is_correct":false,"explanation":""},{"id":"C","text":"$8.00","is_correct":false,"explanation":""},{"id":"D","text":"$9.00","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The cost of the apples is 3 pounds * $2/pound = $6. The cost of the oranges is 2 pounds * $1.50/pound = $3. The total cost is $6 + $3 = $9.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_c1b2142242bcd51c_math_00085',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_a9","opensat_index":85}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has legs of length 5 and 12. What is the length of the hypotenuse?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"13","is_correct":true,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"19","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs.  Therefore, the length of the hypotenuse is \sqrt{5^2 + 12^2} = \sqrt{169} = 13.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_e92b7f80c7a57c3d_math_00086',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_c9","opensat_index":86}'::jsonb
  ),
(
    gen_random_uuid(),
    'In a right triangle, one angle measures 30 degrees and the hypotenuse has a length of 10. What is the length of the side opposite the 30-degree angle?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":true,"explanation":""},{"id":"C","text":"5\\sqrt{3}","is_correct":false,"explanation":""},{"id":"D","text":"10\\sqrt{3}","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A 30-60-90 right triangle has sides in the ratio of 1:√3:2. Since the hypotenuse has a length of 10, the side opposite the 30-degree angle has a length of 10 / 2 = 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_1c4414f8a85cac1d_math_00087',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_a5","opensat_index":87}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 200 students found that 120 students enjoy watching movies, 80 students enjoy reading books, and 60 students enjoy both. How many of the 200 students enjoy neither watching movies nor reading books?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":false,"explanation":""},{"id":"B","text":"40","is_correct":true,"explanation":""},{"id":"C","text":"60","is_correct":false,"explanation":""},{"id":"D","text":"100","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can use a Venn diagram to solve this problem.  Let M represent the set of students who enjoy watching movies and B represent the set of students who enjoy reading books.  We are given that |M|=120, |B|=80, and |M∩B|=60.  The number of students who enjoy only watching movies is 120 - 60 = 60.  The number of students who enjoy only reading books is 80 - 60 = 20.  The total number of students who enjoy at least one of these activities is 60 + 20 + 60 = 140. Therefore, 200 - 140 = 60 students enjoy neither.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_81b4ee881760ff23_math_00088',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_c8","opensat_index":88}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells bags of apples for $\$3.50$ per bag.  If the store makes a profit of $\$0.75$ per bag, what is the cost, in dollars, of each bag of apples?',
    'multiple_choice',
    '[{"id":"A","text":"$\\$2.75$","is_correct":true,"explanation":""},{"id":"B","text":"$\\$3.25$","is_correct":false,"explanation":""},{"id":"C","text":"$\\$4.25$","is_correct":false,"explanation":""},{"id":"D","text":"$\\$4.75$","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The cost of a bag of apples is the selling price minus the profit: $\$3.50 - \$0.75 = \$2.75$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_dd5e7f9103d9cbeb_math_00089',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_c3","opensat_index":89}'::jsonb
  ),
(
    gen_random_uuid(),
    'In a right triangle, the length of one leg is 5 units and the length of the hypotenuse is 13 units.  What is the area of the triangle?',
    'multiple_choice',
    '[{"id":"A","text":"30","is_correct":false,"explanation":""},{"id":"B","text":"60","is_correct":false,"explanation":""},{"id":"C","text":"15","is_correct":true,"explanation":""},{"id":"D","text":"36","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a right triangle is given by (1/2)bh, where b is the length of the base and h is the length of the height.  In a right triangle, the legs can be considered the base and height.  Using the Pythagorean Theorem, we can find the length of the other leg: a^2 + b^2 = c^2, where a and b are the legs and c is the hypotenuse.  Plugging in the values, we get 5^2 + b^2 = 13^2.  This simplifies to 25 + b^2 = 169.  Subtracting 25 from both sides, we get b^2 = 144.  Taking the square root of both sides, we get b = 12.  Now, the area of the triangle is (1/2)(5)(12) = 30.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_a6afe1c7e19a43a9_math_00090',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_c3","opensat_index":90}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 students found that 60 students liked apples, 40 students liked oranges, and 15 students liked both apples and oranges. How many students liked neither apples nor oranges?',
    'multiple_choice',
    '[{"id":"A","text":"5","is_correct":false,"explanation":""},{"id":"B","text":"15","is_correct":false,"explanation":""},{"id":"C","text":"25","is_correct":true,"explanation":""},{"id":"D","text":"35","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can use a Venn diagram to solve this problem.  Let the number of students who like only apples be  and the number of students who like only oranges be .  We know that , , and .  We can use the following equation to find the number of students who like neither apples nor oranges: , or .  Therefore, students liked neither apples nor oranges.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_150c264b7747cd1d_math_00091',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_c4","opensat_index":91}'::jsonb
  ),
(
    gen_random_uuid(),
    'In a right triangle, one angle measures 30 degrees and the hypotenuse has a length of 10. What is the length of the side opposite the 30 degree angle?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":true,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'In a 30-60-90 right triangle, the side opposite the 30 degree angle is half the length of the hypotenuse. Therefore, the length of the side opposite the 30 degree angle is 10/2 = 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_f2cc9fc749b98ea1_math_00092',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_b5","opensat_index":92}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the median of the seven data values shown? 2, 2, 3, 4, 4, 11',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The median of a data set with an odd number of values is the middle value. The values are already presented in order from least to greatest, and there are 7 values. Therefore, the median is the fourth value in the list, which is 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'f890dc20_math_00093',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"f890dc20","opensat_index":93}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a radius of 5 units is inscribed in a square. What is the area, in square units, of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square.  Since the radius of the circle is 5 units, the diameter is 10 units. Therefore, the side length of the square is 10 units, and the area of the square is 10^2 = 100 square units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_3aa3671576896375_math_00094',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_a3","opensat_index":94}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x - 2y = 11$ and $x + 2y = 5$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Adding the two equations together, we eliminate y: $3x - 2y + (x + 2y) = 11 + 5$, which simplifies to $4x = 16$. Dividing both sides by 4, we find $x = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'a9f12c4a_math_00095',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"a9f12c4a","opensat_index":95}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x + 2y = 10$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve this system of equations using elimination. Multiplying the second equation by 2, we get $2x - 2y = 2$. Adding this equation to the first equation, we get $5x = 12$. Dividing both sides by 5, we get $x = \frac{12}{5}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_de748ca0d4c1ec1c_math_00096',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_5","opensat_index":96}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x - 2y = 10$ and $x + 2y = 2$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for x, we can add the two equations together. Notice that the y terms will cancel out: \begin{align*} 3x - 2y &= 10 \\ + (x + 2y &= 2) \\ \hline 4x &= 12 \\ \end{align*} Dividing both sides by 4, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_664f67917f06639a_math_00097',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_a2","opensat_index":97}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 randomly selected students found that 60 students prefer to study in a quiet environment and 40 students prefer to study in a noisy environment. If 300 students are surveyed, how many are likely to prefer to study in a quiet environment?',
    'multiple_choice',
    '[{"id":"A","text":"60","is_correct":false,"explanation":""},{"id":"B","text":"120","is_correct":false,"explanation":""},{"id":"C","text":"180","is_correct":true,"explanation":""},{"id":"D","text":"240","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The ratio of students who prefer quiet to the total number of students is 60/100 = 3/5. If 300 students are surveyed, we can multiply this ratio by 300 to estimate the number of students who prefer quiet: (3/5) * 300 = 180.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_cfcbffdc8f2d9bf2_math_00098',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_c9","opensat_index":98}'::jsonb
  ),
(
    gen_random_uuid(),
    'A triangle has vertices at the points $(0,0), (1,0),$ and $(0,1)$. What is the area of this triangle?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{1}{4}$","is_correct":true,"explanation":""},{"id":"B","text":"$\\frac{1}{2}$","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"2","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The triangle is a right triangle with a base of 1 and a height of 1. The area of a triangle is given by the formula $\frac{1}{2}bh$.  Therefore, the area of the triangle is $\frac{1}{2}(1)(1) = \frac{1}{2}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_b289b6061937add9_math_00099',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_c2","opensat_index":99}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has legs of length 5 and 12. What is the length of the hypotenuse?',
    'multiple_choice',
    '[{"id":"A","text":"7","is_correct":false,"explanation":""},{"id":"B","text":"13","is_correct":true,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"25","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The Pythagorean theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs.  In this case, the hypotenuse squared is equal to $5^2 + 12^2 = 25 + 144 = 169$.  The square root of 169 is 13, so the length of the hypotenuse is 13.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '12d8c11e_math_00100',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"12d8c11e","opensat_index":100}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 200 people found that 120 people liked apples, 80 people liked oranges, and 50 people liked both apples and oranges. How many people liked only oranges?',
    'multiple_choice',
    '[{"id":"A","text":"30","is_correct":true,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"70","is_correct":false,"explanation":""},{"id":"D","text":"130","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To find the number of people who liked only oranges, we subtract the number of people who liked both apples and oranges from the number who liked oranges: 80 - 50 = 30.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_9ff3d0f90f85d9e5_math_00101',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_a5","opensat_index":101}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 students found that 60 students like to play basketball, 50 students like to play soccer, and 20 students like to play both.  How many students like to play only basketball?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"20","is_correct":false,"explanation":""},{"id":"C","text":"40","is_correct":true,"explanation":""},{"id":"D","text":"60","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find the number of students who like only basketball, we need to subtract the number of students who like both sports from the total number of students who like basketball.  This gives us 60 – 20 = 40.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_8bf922ff74fca93b_math_00102',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_c9","opensat_index":102}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the value of  $\frac{x^2 + 2x + 1}{x^2 - 1}$ when $x=3$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":true,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"8","is_correct":false,"explanation":""},{"id":"D","text":"16","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can simplify the expression first by factoring the numerator and denominator:  $\frac{x^2 + 2x + 1}{x^2 - 1} = \frac{(x+1)(x+1)}{(x+1)(x-1)}$.  Since $x=3$, we can substitute to get $\frac{(3+1)(3+1)}{(3+1)(3-1)} = \frac{(4)(4)}{(4)(2)} = \frac{16}{8} = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_da7af8505ea56051_math_00103',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_a1","opensat_index":103}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units.  What is the area, in square units, of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":true,"explanation":""},{"id":"D","text":"100\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula A = \pi r^2, where r is the radius.  Substituting 5 for r, we get A = \pi (5)^2 = 25\pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_47f5f75604396bd3_math_00104',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_a7","opensat_index":104}'::jsonb
  ),
(
    gen_random_uuid(),
    'A regular hexagon is inscribed in a circle with a radius of 6. What is the perimeter of the hexagon?',
    'multiple_choice',
    '[{"id":"A","text":"18","is_correct":false,"explanation":""},{"id":"B","text":"24","is_correct":false,"explanation":""},{"id":"C","text":"36","is_correct":true,"explanation":""},{"id":"D","text":"48","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'A regular hexagon can be divided into 6 equilateral triangles. The side of each equilateral triangle is equal to the radius of the circle, which is 6. Therefore, the perimeter of the hexagon is 6 * 6 = 36.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_c7a8ec5bd9a81d5d_math_00105',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_a9","opensat_index":105}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with center (2,3) passes through the point (5,7). What is the radius of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":true,"explanation":""},{"id":"C","text":"8","is_correct":false,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The radius of the circle is the distance between the center of the circle and any point on the circle.  Using the distance formula, the distance between (2,3) and (5,7) is $\sqrt{(5-2)^2 + (7-3)^2} = \sqrt{3^2 + 4^2} = \sqrt{25} = 5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_8c5ca1ffe92f53c8_math_00106',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_9","opensat_index":106}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;