INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'If $\frac{2x+3}{x-1} = 5$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for x, we first multiply both sides of the equation by $(x - 1)$: $2x+3 = 5(x-1)$. Expanding the right-hand side of the equation gives $2x + 3 = 5x - 5$. Combining the x-terms on the left-hand side, we get $2x - 5x = -5 - 3$, or $-3x = -8$. Dividing both sides by -3, we get $x = \frac{-8}{-3} = \frac{8}{3} = 2\frac{2}{3}$. Since only 4 is given as a choice, the answer is 4.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'd84e67c3_math_00957',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"d84e67c3","opensat_index":957}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 2x - 15 = 0$, what are the solutions for $x$?',
    'multiple_choice',
    '[{"id":"A","text":"x = 3 or x = -5","is_correct":false,"explanation":""},{"id":"B","text":"x = -3 or x = 5","is_correct":true,"explanation":""},{"id":"C","text":"x = 15 or x = -1","is_correct":false,"explanation":""},{"id":"D","text":"x = -15 or x = 1","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for $x$, we can factor the quadratic expression.  The expression factors as $(x + 5)(x - 3) = 0$. For the product of two terms to equal zero, at least one of the terms must equal zero.  Therefore, either $x + 5 = 0$, or $x - 3 = 0$. Solving for $x$ in each case gives us $x = -5$ or $x = 3$.  Since neither of these solutions is listed as a choice, the correct answer is the only other option, $x = -3$ or $x = 5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'a3d8c31d_math_00958',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"a3d8c31d","opensat_index":958}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x+5=12$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"7","is_correct":true,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"60","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for *x*, we subtract 5 from both sides of the equation:  *x* + 5 - 5 = 12 - 5, which simplifies to *x* = 7.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_edd7b9529fcf1417_math_00959',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_a8","opensat_index":959}'::jsonb
  ),
(
    gen_random_uuid(),
    'A regular hexagon has a side length of 10.  What is the perimeter of the hexagon?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"20","is_correct":false,"explanation":""},{"id":"C","text":"30","is_correct":false,"explanation":""},{"id":"D","text":"60","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'A regular hexagon has 6 equal sides.  The perimeter is the total length of all the sides, so the perimeter of this hexagon is 6 * 10 = 60.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_d8ed7336c0ed382f_math_00960',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_c1","opensat_index":960}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve for $x$ using the elimination method.  Multiplying the second equation by 3, we get $3x - 3y = 3$. Adding this equation to the first equation, we get $5x = 15$.  Dividing both sides by 5, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'f298c515_math_00961',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"f298c515","opensat_index":961}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a circumference of 12\pi. What is the area of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"12\\pi","is_correct":false,"explanation":""},{"id":"B","text":"36\\pi","is_correct":true,"explanation":""},{"id":"C","text":"144\\pi","is_correct":false,"explanation":""},{"id":"D","text":"144","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula C = 2\pi r, where r is the radius.  We are given that the circumference is 12\pi, so 12\pi = 2\pi r.  Dividing both sides by 2\pi gives r = 6.  The area of a circle is given by the formula A = \pi r^2, so the area of this circle is A = \pi (6)^2 = 36\pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_d57611c7b934a672_math_00962',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_c8","opensat_index":962}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve for $x$ by using the elimination method. Multiplying the second equation by 3, we get $3x - 3y = 3$. Adding this equation to the first equation, we get $5x = 15$. Dividing both sides by 5, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_890390dc76002d34_math_00963',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_a7","opensat_index":963}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people like apples, 40 people like bananas, and 20 people like both apples and bananas. How many people like only bananas?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":true,"explanation":""},{"id":"B","text":"40","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":false,"explanation":""},{"id":"D","text":"80","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can use a Venn diagram to solve this problem.  Let the circle representing people who like apples be labeled "A" and the circle representing people who like bananas be labeled "B".  The overlap between the two circles represents the people who like both apples and bananas. We know that 20 people like both apples and bananas, so we can fill in the overlap of the circles with 20.  Since 60 people like apples in total, we can subtract the 20 who like both apples and bananas to find that 60 - 20 = 40 people like only apples.  Since 40 people like bananas in total, we can subtract the 20 who like both apples and bananas to find that 40 - 20 = 20 people like only bananas.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_6a238e47147966a3_math_00964',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_a4","opensat_index":964}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 12 cm and a width of 5 cm. What is the area of the rectangle, in square centimeters?',
    'multiple_choice',
    '[{"id":"A","text":"17","is_correct":false,"explanation":""},{"id":"B","text":"34","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":true,"explanation":""},{"id":"D","text":"120","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is found by multiplying its length and width. In this case, the area is 12 cm * 5 cm = 60 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_c40ef8a8d955a876_math_00965',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_a2","opensat_index":965}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = \sqrt{x}$ is defined for all $x \ge 0$. What is the value of $f(16)$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":true,"explanation":""},{"id":"C","text":"8","is_correct":false,"explanation":""},{"id":"D","text":"16","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The function $f(x) = \sqrt{x}$ means that the output of the function is the square root of the input.  Therefore, $f(16) = \sqrt{16} = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_cee4e591448f02f2_math_00966',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_c1","opensat_index":966}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a circumference of $10\pi$ centimeters. What is the area of the circle, in square centimeters?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":true,"explanation":""},{"id":"D","text":"100\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius of the circle.  We are given that the circumference is $10\pi$ centimeters, so $10\pi = 2\pi r$.  Dividing both sides by $2\pi$ gives us $r = 5$. The area of a circle is given by the formula $A = \pi r^2$, so the area of this circle is $A = \pi (5)^2 = 25\pi$ square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_a3d99ea4506f5844_math_00967',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_b8","opensat_index":967}'::jsonb
  ),
(
    gen_random_uuid(),
    'The expression  $\frac{x^{10}y^6}{x^2y^2}$ is equivalent to $x^ay^b$, where a and b are constants. What is the value of $a+b$?',
    'multiple_choice',
    '[{"id":"A","text":"6","is_correct":false,"explanation":""},{"id":"B","text":"8","is_correct":true,"explanation":""},{"id":"C","text":"10","is_correct":false,"explanation":""},{"id":"D","text":"12","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Using the properties of exponents, we can simplify the expression as follows:  $\frac{x^{10}y^6}{x^2y^2} = x^{10-2}y^{6-2} = x^8y^4$.  Therefore, $a+b = 8+4 = 12$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_bd68aa3721b46554_math_00968',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_27","opensat_index":968}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 6x + 5 = 0$, what is the sum of the solutions to the equation?',
    'multiple_choice',
    '[{"id":"A","text":"-6","is_correct":true,"explanation":""},{"id":"B","text":"-5","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The sum of the solutions to the quadratic equation $ax^2 + bx + c = 0$ is given by $-b/a$. In this case, the sum of the solutions is $-6/1 = -6$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '4a1f5b7a_math_00969',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"4a1f5b7a","opensat_index":969}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = 2x^2 - 4x + 3$ is defined for all real numbers.  What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-13","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"19","is_correct":true,"explanation":""},{"id":"D","text":"27","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Substitute -2 for $x$ in the function:  $f(-2) = 2(-2)^2 - 4(-2) + 3 = 8 + 8 + 3 = 19$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_fc76affcd9d56f24_math_00970',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_9","opensat_index":970}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells apples for $1.25 each and oranges for $0.75 each. A customer buys 5 apples and 3 oranges. How much did the customer spend in total?',
    'multiple_choice',
    '[{"id":"A","text":"$6.25","is_correct":false,"explanation":""},{"id":"B","text":"$7.50","is_correct":false,"explanation":""},{"id":"C","text":"$8.75","is_correct":false,"explanation":""},{"id":"D","text":"$10.00","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The cost of the apples is 5 x $1.25 = $6.25. The cost of the oranges is 3 x $0.75 = $2.25. The total cost is $6.25 + $2.25 = $8.50.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_d9a5a2492bd5ffa4_math_00971',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_4","opensat_index":971}'::jsonb
  ),
(
    gen_random_uuid(),
    'The area of a circle is $16\pi$ square inches.  What is the circumference of the circle, in inches?',
    'multiple_choice',
    '[{"id":"A","text":"4\\pi","is_correct":false,"explanation":""},{"id":"B","text":"8\\pi","is_correct":true,"explanation":""},{"id":"C","text":"16\\pi","is_correct":false,"explanation":""},{"id":"D","text":"64\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The area of a circle is given by $A = \pi r^2$, where $r$ is the radius of the circle.  We are given that the area is $16\pi$ square inches, so $16\pi = \pi r^2$. Dividing both sides by $\pi$ gives $16 = r^2$, so $r = 4$. The circumference of a circle is given by $C = 2\pi r$, so $C = 2\pi (4) = 8\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '4c9664d4_math_00972',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"4c9664d4","opensat_index":972}'::jsonb
  ),
(
    gen_random_uuid(),
    'In a right triangle, the length of the hypotenuse is 10 and the length of one leg is 6. What is the length of the other leg?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":false,"explanation":""},{"id":"B","text":"8","is_correct":false,"explanation":""},{"id":"C","text":"$\\sqrt{64}$","is_correct":false,"explanation":""},{"id":"D","text":"$\\sqrt{136}$","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'We can use the Pythagorean theorem to solve for the missing leg. The Pythagorean theorem states that in a right triangle, the square of the hypotenuse (the longest side) is equal to the sum of the squares of the other two sides.  Let $x$ be the length of the missing leg.  We have the equation: $10^2 = 6^2 + x^2$.  Simplifying, we get $100 = 36 + x^2$.  Subtracting 36 from both sides, we get $64 = x^2$.  Taking the square root of both sides, we get $x = \sqrt{64}$ or $x = -\sqrt{64}$.  Since a length cannot be negative, the length of the other leg is $x = \sqrt{64}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_cfc4e0e9455c5696_math_00973',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_d9","opensat_index":973}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm. What is the area of the circle, in square centimeters? (Use $\pi = 3.14$)',
    'multiple_choice',
    '[{"id":"A","text":"15.7","is_correct":false,"explanation":""},{"id":"B","text":"31.4","is_correct":false,"explanation":""},{"id":"C","text":"78.5","is_correct":true,"explanation":""},{"id":"D","text":"157","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula $A = \pi r^2$, where $r$ is the radius. Substituting $r = 5$ cm and $\pi = 3.14$, we get $A = 3.14 \cdot 5^2 = 3.14 \cdot 25 = 78.5$ square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_f5e4a6815d4396cf_math_00974',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_24","opensat_index":974}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2-4x+3 = 0$, what is the sum of the solutions of this equation?',
    'multiple_choice',
    '[{"id":"A","text":"-4","is_correct":false,"explanation":""},{"id":"B","text":"-3","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'We can factor the quadratic equation: $(x-1)(x-3)=0$.  This tells us that the solutions to the equation are $x=1$ and $x=3$. The sum of these solutions is $1+3 = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '2466792a_math_00975',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"2466792a","opensat_index":975}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 4x + 4 = 0$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":true,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The given equation is a perfect square trinomial: $(x+2)^2 = 0$. Taking the square root of both sides, we get $x+2 = 0$. Subtracting 2 from both sides, we get $x = -2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'f8f51193_math_00976',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"f8f51193","opensat_index":976}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by \(f(x) = 2x^2 + 3x - 1\). What is the value of \(f(-2)\)?',
    'multiple_choice',
    '[{"id":"A","text":"-9","is_correct":true,"explanation":""},{"id":"B","text":"-3","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Substituting -2 for *x* in the function, we get \(f(-2) = 2(-2)^2 + 3(-2) - 1\). Simplifying, we get \(f(-2) = 8 - 6 - 1\), or \(f(-2) = -9\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'c824d513_math_00977',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"c824d513","opensat_index":977}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 10 inches and a width of 5 inches. What is the area of the rectangle, in square inches?',
    'multiple_choice',
    '[{"id":"A","text":"15","is_correct":false,"explanation":""},{"id":"B","text":"25","is_correct":false,"explanation":""},{"id":"C","text":"50","is_correct":true,"explanation":""},{"id":"D","text":"100","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is calculated by multiplying its length and width.  In this case, the area is 10 inches * 5 inches = 50 square inches.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_01fdc28a51ee7ecf_math_00978',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_b9","opensat_index":978}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $\frac{2x-3}{x+1} = 5$ is equivalent to which of the following equations?',
    'multiple_choice',
    '[{"id":"A","text":"2x - 3 = 5x + 5","is_correct":true,"explanation":""},{"id":"B","text":"2x - 3 = 5x - 5","is_correct":false,"explanation":""},{"id":"C","text":"2x + 3 = 5x + 5","is_correct":false,"explanation":""},{"id":"D","text":"2x + 3 = 5x - 5","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To solve for x, we multiply both sides of the equation by (x+1).  This gives us $2x - 3 = 5(x+1)$.  Distributing the 5 on the right side, we get $2x - 3 = 5x + 5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_3b5549a8ae883f46_math_00979',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_a3","opensat_index":979}'::jsonb
  ),
(
    gen_random_uuid(),
    'A bakery has 120 cakes on display.  Of those cakes, 25% are chocolate, 30% are vanilla, and the rest are strawberry. How many strawberry cakes are on display?',
    'multiple_choice',
    '[{"id":"A","text":"36","is_correct":false,"explanation":""},{"id":"B","text":"48","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":true,"explanation":""},{"id":"D","text":"72","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'First, we need to find the total percentage of chocolate and vanilla cakes: 25% + 30% = 55%. This means 55% of the cakes are either chocolate or vanilla.  The remaining cakes must be strawberry: 100% - 55% = 45%.  To find the number of strawberry cakes, we multiply the total number of cakes by 45%: 120 cakes * 0.45 = 54 cakes.  The closest answer choice to 54 cakes is 60, so the answer is C.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '28f140fd_math_00980',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"28f140fd","opensat_index":980}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with radius 5 is inscribed in a square. What is the area of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square.  Since the radius of the circle is 5, the diameter is 10.  The area of the square is then $10^2 = 100$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_e765520698af8c42_math_00981',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_a9","opensat_index":981}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;

INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm. What is the circumference of the circle? (Use $\pi = 3.14$)',
    'multiple_choice',
    '[{"id":"A","text":"15.7 cm","is_correct":false,"explanation":""},{"id":"B","text":"31.4 cm","is_correct":true,"explanation":""},{"id":"C","text":"78.5 cm","is_correct":false,"explanation":""},{"id":"D","text":"157 cm","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius. Substituting 5 cm for $r$ and 3.14 for $\pi$, we get $C = 2(3.14)(5) = 31.4$ cm.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_88e07aa67bbfb458_math_00982',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_c2","opensat_index":982}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has legs of length 5 and 12. What is the length of the hypotenuse of the triangle?',
    'multiple_choice',
    '[{"id":"A","text":"13","is_correct":true,"explanation":""},{"id":"B","text":"17","is_correct":false,"explanation":""},{"id":"C","text":"19","is_correct":false,"explanation":""},{"id":"D","text":"25","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs.  Therefore, the length of the hypotenuse is  $\sqrt{5^2 + 12^2} = \sqrt{169} = 13$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'f1d7a634_math_00983',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"f1d7a634","opensat_index":983}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x+y = 5$ and $x-y=1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Adding the two equations together, we get $(x+y) + (x-y) = 5+1$, or $2x = 6$. Dividing both sides by 2 gives $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_f101fc79802c24a3_math_00984',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_d5","opensat_index":984}'::jsonb
  ),
(
    gen_random_uuid(),
    'A function is defined by the equation \(f(x) = 2x^2 + 3x - 5\). What is the value of \(f(-2)\)?',
    'multiple_choice',
    '[{"id":"A","text":"-17","is_correct":false,"explanation":""},{"id":"B","text":"-9","is_correct":true,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"13","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To find f(-2), we substitute -2 for x in the equation: \(f(-2) = 2(-2)^2 + 3(-2) - 5\). Simplifying, we get \(f(-2) = 8 - 6 - 5\), or \(f(-2) = -3\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_3ff063f611d1cdd8_math_00985',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_c9","opensat_index":985}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of friends is planning a trip. They decide to rent a car for the trip.  The cost to rent a car is a flat fee of $25, plus $15 per day.  Let *c* represent the total cost, in dollars, and *d* represent the number of days the car is rented.  Which of the following equations represents the relationship between *c* and *d*?',
    'multiple_choice',
    '[{"id":"A","text":"c = 25d + 15","is_correct":false,"explanation":""},{"id":"B","text":"c = 15d + 25","is_correct":true,"explanation":""},{"id":"C","text":"c = 25 + 15d","is_correct":false,"explanation":""},{"id":"D","text":"c = 15 + 25d","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The flat fee of $25 is a constant cost, and the cost per day, $15, is multiplied by the number of days, *d*.  Therefore, the total cost, *c*, is represented by the equation c = 15d + 25.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '23ef2021_math_00986',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"23ef2021","opensat_index":986}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x$ is a real number, and $x^2 - 4x + 4 = 0$, what is the value of $x + 1$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":true,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The equation $x^2 - 4x + 4 = 0$ factors as $(x-2)^2 = 0$. This tells us that $x - 2 = 0$, or $x = 2$.  Therefore, $x + 1 = 2 + 1 = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '3d985142_math_00987',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"3d985142","opensat_index":987}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people liked apples, 40 people liked oranges, and 20 people liked both apples and oranges. How many people liked only apples?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":true,"explanation":""},{"id":"B","text":"40","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":false,"explanation":""},{"id":"D","text":"80","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can use a Venn diagram to solve this problem.  Let''s represent the number of people who like only apples as  *a*, the number of people who like only oranges as *o*, and the number of people who like both as *b*. We are given that *a* + *b* = 60, *o* + *b* = 40, and *b* = 20. Substituting *b* = 20 into the first two equations, we get *a* + 20 = 60 and *o* + 20 = 40. Solving for *a*, we find *a* = 60 - 20 = 40.  Therefore, 40 people like only apples.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_6acd3daf8c556f65_math_00988',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_d8","opensat_index":988}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 2x - 3 = 0$, what is the value of $x^3 + 2x^2 - 3x$?',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":false,"explanation":""},{"id":"B","text":"0","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":true,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can factor the given equation as $(x+3)(x-1)=0$.  This means that $x=-3$ or $x=1$.  Substituting either value into the expression $x^3 + 2x^2 - 3x$ gives us 3.  Therefore, the value of $x^3 + 2x^2 - 3x$ is 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '13b8a32c_math_00989',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"13b8a32c","opensat_index":989}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people like apples, 45 people like oranges, and 20 people like both apples and oranges. How many people like only apples?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":false,"explanation":""},{"id":"B","text":"40","is_correct":true,"explanation":""},{"id":"C","text":"60","is_correct":false,"explanation":""},{"id":"D","text":"80","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can use a Venn diagram to solve this.  Let the number of people who like only apples be represented by x.  
[asy] 
label("Apples",(1.5,1.5));
label("Oranges",(2.5,1.5));
label("x",(1,1));
label("20",(2,1));
label("25",(3,1));
draw(Circle((1,1),1));
draw(Circle((2,1),1));
draw((0.5,0)--(3.5,0));
draw((0,0.5)--(0,2.5));
[/asy]  The number of people who like oranges is 45, so 20 + 25 = 45. Therefore, the number of people who like only apples is 40.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_381a3a81fc5dfbfa_math_00990',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_a8","opensat_index":990}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = \frac{x^2 - 4}{x - 2}$ is undefined for what value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-4","is_correct":false,"explanation":""},{"id":"B","text":"-2","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":true,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'A function is undefined when its denominator equals zero.  In this case, the denominator is $x-2$, which equals zero when $x=2$. Therefore, the function is undefined for $x=2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_79d8f8c66c43e1ae_math_00991',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_b21","opensat_index":991}'::jsonb
  ),
(
    gen_random_uuid(),
    'In the $xy$-plane, line $k$ passes through the points $(2,-1)$ and $(4,3)$. What is the slope of line $k$?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":true,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The slope of a line passing through two points $(x_1, y_1)$ and $(x_2, y_2)$ can be calculated using the formula: $m = \frac{y_2 - y_1}{x_2 - x_1}$.  Substituting the points (2, -1) and (4, 3) into the formula, we get: $m = \frac{3 - (-1)}{4 - 2} = \frac{4}{2} = 2$. Therefore, the slope of line $k$ is 2.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '1453c4d6_math_00992',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"1453c4d6","opensat_index":992}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $f(x) = \frac{x^2-1}{x+1}$ for $x \ne -1$, what is the value of $f(-3)$?',
    'multiple_choice',
    '[{"id":"A","text":"-4","is_correct":false,"explanation":""},{"id":"B","text":"-2","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substituting -3 for x in the function, we get: $f(-3) = \frac{(-3)^2-1}{-3+1}$. Simplifying the expression, we get $f(-3) = \frac{9-1}{-2} = \frac{8}{-2} = -4$. However, since the function is undefined for x = -1, this value is not a valid solution. Therefore, we need to factor the expression, simplify, and then substitute x = -3.  Factoring the expression, we get: $f(x) = \frac{(x+1)(x-1)}{x+1}$.  Since $x \ne -1$, we can cancel out the common factor of (x+1), leaving us with $f(x) = x-1$.  Substituting -3 for x in this simplified expression, we get $f(-3) = -3 - 1 = -4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'a22d8ac5_math_00993',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"a22d8ac5","opensat_index":993}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of 10 friends are planning a trip. They decide to split the cost of the trip evenly.  If the total cost of the trip is $1,200, how much will each friend pay?',
    'multiple_choice',
    '[{"id":"A","text":"$100","is_correct":false,"explanation":""},{"id":"B","text":"$120","is_correct":true,"explanation":""},{"id":"C","text":"$1,200","is_correct":false,"explanation":""},{"id":"D","text":"$12,000","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To find the cost per friend, we divide the total cost by the number of friends: $1,200 / 10 = $120.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_bded051901667ca4_math_00994',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_c3","opensat_index":994}'::jsonb
  ),
(
    gen_random_uuid(),
    'A regular hexagon is inscribed in a circle with a radius of 6. What is the perimeter of the hexagon?',
    'multiple_choice',
    '[{"id":"A","text":"12","is_correct":false,"explanation":""},{"id":"B","text":"18","is_correct":false,"explanation":""},{"id":"C","text":"24","is_correct":false,"explanation":""},{"id":"D","text":"36","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'A regular hexagon can be divided into 6 equilateral triangles. The side of each equilateral triangle is equal to the radius of the circle, which is 6. So the perimeter of the hexagon is 6 * 6 = 36.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_caf31c7be649d523_math_00995',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_c2","opensat_index":995}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $\frac{x}{y}= 3$ and $\frac{y}{z}= 2$, what is the value of $\frac{x}{z}$?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{1}{6}$","is_correct":false,"explanation":""},{"id":"B","text":"$\\frac{1}{2}$","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find the value of $\frac{x}{z}$, we can multiply the two given equations: $(\frac{x}{y}) \cdot (\frac{y}{z}) = 3 \cdot 2$.  Notice that the $y$ terms cancel out, leaving us with $\frac{x}{z} = 6$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_c81c2091c12ece7d_math_00996',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_a5","opensat_index":996}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm. What is the area of the circle in square centimeters?',
    'multiple_choice',
    '[{"id":"A","text":"10\\pi","is_correct":false,"explanation":""},{"id":"B","text":"25\\pi","is_correct":true,"explanation":""},{"id":"C","text":"50\\pi","is_correct":false,"explanation":""},{"id":"D","text":"100\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The area of a circle is given by the formula A = \pi r^2, where r is the radius.  Substituting 5 for r, we get A = \pi (5)^2 = 25\pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_810b3c694f3be1d9_math_00997',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_1","opensat_index":997}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of friends are planning a trip. They decide to split the cost of the trip evenly among themselves.  If the total cost of the trip is \$1500 and there are 5 friends, how much will each friend pay?',
    'multiple_choice',
    '[{"id":"A","text":"30","is_correct":false,"explanation":""},{"id":"B","text":"100","is_correct":false,"explanation":""},{"id":"C","text":"300","is_correct":true,"explanation":""},{"id":"D","text":"750","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find out how much each friend will pay, we divide the total cost by the number of friends: $1500 / 5 = $300.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_ff50ae08e6884e72_math_00998',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_15","opensat_index":998}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x$ is a positive integer, what is the smallest possible value of $x$ such that $\frac{x^2 - 4}{x - 2}$ is an integer?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The expression $\frac{x^2 - 4}{x - 2}$ can be simplified by factoring the numerator: $\frac{x^2 - 4}{x - 2} = \frac{(x+2)(x-2)}{x - 2} = x + 2$, as long as $x \neq 2$.  Since $x$ is a positive integer, the smallest possible value of $x$ that makes this expression an integer is $x = 4$. ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'd8c76f6a_math_00999',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"d8c76f6a","opensat_index":999}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - 2y = 4$, what is the value of $x + y$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for $x + y$, we can add the two equations together.  The $y$ terms will cancel out, leaving us with $3x = 16$.  Solving for $x$, we get $x = \frac{16}{3}$.  Substituting this value back into either of the original equations, we can solve for $y$.  Substituting into the first equation, we get $2 \cdot \frac{16}{3} + 3y = 12$, or $\frac{32}{3} + 3y = 12$.  Subtracting $\frac{32}{3}$ from both sides, we get $3y = 12 - \frac{32}{3}$, or $3y = \frac{4}{3}$.  Dividing both sides by 3, we get $y = \frac{4}{9}$.  Therefore, $x + y = \frac{16}{3} + \frac{4}{9} = 6$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'e83839db_math_01000',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"e83839db","opensat_index":1000}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a radius of 5 cm is inscribed in a square. What is the area, in square centimeters, of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square. Since the radius of the circle is 5 cm, the diameter is 10 cm.  Therefore, the side length of the square is 10 cm, and the area of the square is 10² = 100 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_e108864abd6adc57_math_01001',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_29","opensat_index":1001}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 12 meters and a width of 5 meters. What is the area of the rectangle, in square meters?',
    'multiple_choice',
    '[{"id":"A","text":"17","is_correct":false,"explanation":""},{"id":"B","text":"34","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":true,"explanation":""},{"id":"D","text":"72","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is calculated by multiplying its length and width.  In this case, the area is 12 meters * 5 meters = 60 square meters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_c98c7927fe878759_math_01002',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_c1","opensat_index":1002}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  $3x + 2y = 12$ and $x - 2y = 4$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for $x$, we can add the two equations together. Notice that the $y$ terms cancel out: $(3x + 2y) + (x - 2y) = 12 + 4$, which simplifies to $4x = 16$. Dividing both sides by 4, we get $x = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'a1293ac5_math_01003',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"a1293ac5","opensat_index":1003}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people like apples, 40 people like oranges, and 20 people like both apples and oranges. How many people like only apples?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":true,"explanation":""},{"id":"B","text":"40","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":false,"explanation":""},{"id":"D","text":"80","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can use a Venn Diagram to represent the information given. \begin{align*} \text{People who like only apples} &= \text{People who like apples} - \text{People who like both apples and oranges} \\ &= 60 - 20\\ &= 40 \end{align*} Therefore, 40 people like only apples.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_9b91642bf82b1997_math_01004',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_a1","opensat_index":1004}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x + 2y = 5$ and $x - y = 2$, what is the value of $y$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":true,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can solve this system of equations by elimination. Adding the two equations together, we get  (x + 2y) + (x - y) = 5 + 2, or 2x + y = 7. Simplifying the first equation, we get x = 5 - 2y. Substituting this into the second equation, we get (5 - 2y) - y = 2, or 3y = 3. Therefore, y = 1.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_30015fdec3ac23d8_math_01005',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_c1","opensat_index":1005}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function \(f(x)\) is defined by \(f(x) = 2x - 3\). If \(f(a) = 11\), what is the value of \(a\)?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"7","is_correct":true,"explanation":""},{"id":"C","text":"11","is_correct":false,"explanation":""},{"id":"D","text":"17","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for a, we substitute 11 for f(a) in the equation f(x) = 2x - 3.  This gives us 11 = 2a - 3.  Adding 3 to both sides of the equation gives 14 = 2a.  Dividing both sides of the equation by 2 gives a = 7.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '432ef812_math_01006',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"432ef812","opensat_index":1006}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;