INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'A circle with a radius of 5 centimeters is inscribed in a square. What is the area, in square centimeters, of the square?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":false,"explanation":""},{"id":"B","text":"25","is_correct":false,"explanation":""},{"id":"C","text":"50","is_correct":false,"explanation":""},{"id":"D","text":"100","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The diameter of the circle is equal to the side length of the square. Since the radius of the circle is 5 centimeters, the diameter is 10 centimeters. Therefore, the side length of the square is 10 centimeters, and the area of the square is 10^2 = 100 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_5c33b451c6a9d2de_math_00357',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_a5","opensat_index":357}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x + 2y = 12$ and $x - 2y = 4$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":true,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for $x$, we can add the two equations together.  This eliminates the $y$ terms, leaving us with $4x = 16$.  Dividing both sides by 4, we get $x = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'e8460d41_math_00358',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"e8460d41","opensat_index":358}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store is selling a shirt for $20. The store is having a sale where all items are 15% off. What is the discounted price of the shirt?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"17","is_correct":true,"explanation":""},{"id":"C","text":"25","is_correct":false,"explanation":""},{"id":"D","text":"30","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The discount amount is 15% of $20, which is 0.15 * $20 = $3. The discounted price is $20 - $3 = $17.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_3faa40abee1c421d_math_00359',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_a9","opensat_index":359}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm. What is the circumference of the circle, in terms of pi?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":true,"explanation":""},{"id":"C","text":"25\\pi","is_correct":false,"explanation":""},{"id":"D","text":"50\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula C = 2πr, where r is the radius.  Substituting 5 for r, we get C = 2π(5) = 10π.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'f42c912f_math_00360',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"f42c912f","opensat_index":360}'::jsonb
  ),
(
    gen_random_uuid(),
    'A square with side length 10 is inscribed in a circle. What is the area of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"25\\pi","is_correct":false,"explanation":""},{"id":"B","text":"50\\pi","is_correct":false,"explanation":""},{"id":"C","text":"100\\pi","is_correct":true,"explanation":""},{"id":"D","text":"200\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diagonal of the square is also the diameter of the circle.  Since the sides of the square are 10, the diagonal is 10√2 by the Pythagorean theorem.  The radius of the circle is half the diameter, so the radius is 5√2, and the area of the circle is π(5√2)² = 50π = 100π.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'f711e94e_math_00361',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"f711e94e","opensat_index":361}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x = 3$ and $y = 2$, what is the value of $3x + 2y$?',
    'multiple_choice',
    '[{"id":"A","text":"5","is_correct":false,"explanation":""},{"id":"B","text":"10","is_correct":false,"explanation":""},{"id":"C","text":"13","is_correct":true,"explanation":""},{"id":"D","text":"15","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Substituting $x = 3$ and $y = 2$ into the expression, we get $3(3) + 2(2) = 9 + 4 = 13$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '4231c004_math_00362',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"4231c004","opensat_index":362}'::jsonb
  ),
(
    gen_random_uuid(),
    'The expression $\frac{x^2 + 5x + 6}{x + 2}$ is equivalent to which of the following, when $x \neq -2$?',
    'multiple_choice',
    '[{"id":"A","text":"x + 3","is_correct":true,"explanation":""},{"id":"B","text":"x + 6","is_correct":false,"explanation":""},{"id":"C","text":"x^2 + 3","is_correct":false,"explanation":""},{"id":"D","text":"x^2 + 6","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The numerator can be factored as $(x+2)(x+3)$, so the expression becomes $\frac{(x+2)(x+3)}{x+2}$. Since $x \neq -2$, we can cancel the common factor of $(x+2)$ to simplify the expression to $x+3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '849f432a_math_00363',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"849f432a","opensat_index":363}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle is inscribed in an equilateral triangle. If the side length of the triangle is 6, what is the area of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{3\\pi}{4}$","is_correct":false,"explanation":""},{"id":"B","text":"$\\pi$","is_correct":false,"explanation":""},{"id":"C","text":"$\\frac{9\\pi}{4}$","is_correct":true,"explanation":""},{"id":"D","text":"$9\\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Let''s break down the solution:

1. **Equilateral Triangle Properties:** An equilateral triangle has three equal sides and three equal angles of 60 degrees.  The height of an equilateral triangle divides it into two 30-60-90 right triangles.

2. **30-60-90 Triangle Properties:** The sides of a 30-60-90 triangle are in the ratio of 1:√3:2. Since the side length of the equilateral triangle is 6, the height of the triangle is 3√3. The radius of the inscribed circle is equal to 1/3 of the height, so the radius of the inscribed circle is √3.

3. **Area of a Circle:** The area of a circle is given by the formula $A = \pi r^2$, where r is the radius.  Substituting √3 for r, we get $A = \pi (\sqrt{3})^2 = 3\pi$.

4. **Final Answer:** Since the circle is inscribed in the equilateral triangle, the diameter of the circle is equal to the height of the triangle, which is 3√3.  Therefore, the radius of the circle is (3√3)/2, and the area of the circle is $\pi (\frac{3\sqrt{3}}{2})^2 = \frac{27\pi}{4}$, which is equivalent to .',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_99f05e81f8cf2d0a_math_00364',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_c1","opensat_index":364}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 3x^2 + 5x - 2.  What is the value of *f*(2)?',
    'multiple_choice',
    '[{"id":"A","text":"14","is_correct":false,"explanation":""},{"id":"B","text":"20","is_correct":false,"explanation":""},{"id":"C","text":"28","is_correct":true,"explanation":""},{"id":"D","text":"36","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find *f*(2), we substitute 2 for *x* in the function: *f*(2) = 3(2)^2 + 5(2) - 2. Simplifying, we get *f*(2) = 3(4) + 10 - 2 = 12 + 10 - 2 = 28.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_7a13b7a1b25772ee_math_00365',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_c6","opensat_index":365}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation  $2x^2 - 5x + 3 = 0$ has two solutions.  What is the sum of these solutions?',
    'multiple_choice',
    '[{"id":"A","text":"-\\frac{5}{2}","is_correct":false,"explanation":""},{"id":"B","text":"\\frac{5}{2}","is_correct":true,"explanation":""},{"id":"C","text":"-\\frac{3}{2}","is_correct":false,"explanation":""},{"id":"D","text":"\\frac{3}{2}","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'For a quadratic equation in the form $ax^2 + bx + c = 0$, the sum of the solutions is given by -b/a. In this case, a = 2 and b = -5, so the sum of the solutions is -(-5)/2 = 5/2.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '1543281b_math_00366',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"1543281b","opensat_index":366}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 2x<sup>2</sup> + 3x - 1.  What is the value of *f*(2)?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"15","is_correct":false,"explanation":""},{"id":"D","text":"21","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find *f*(2), we substitute 2 for *x* in the function: *f*(2) = 2(2)<sup>2</sup> + 3(2) - 1.  Simplifying, we get *f*(2) = 8 + 6 - 1 = 13.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '2365d47f_math_00367',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"2365d47f","opensat_index":367}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x + y = 5$ and $x - y = 3$, what is the value of $x^2 - y^2$?',
    'multiple_choice',
    '[{"id":"A","text":"15","is_correct":true,"explanation":""},{"id":"B","text":"25","is_correct":false,"explanation":""},{"id":"C","text":"36","is_correct":false,"explanation":""},{"id":"D","text":"45","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can use the difference of squares factorization: $x^2 - y^2 = (x + y)(x - y)$.  Substituting the given values, we have $(x + y)(x - y) = (5)(3) = 15$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '25c21c5b_math_00368',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"25c21c5b","opensat_index":368}'::jsonb
  ),
(
    gen_random_uuid(),
    'The expression  $\frac{x^2 - 2x - 8}{x^2 - 16}$ is equivalent to which of the following expressions, where $x \neq 4$ and $x \neq -4$?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{x-4}{x-2}$","is_correct":false,"explanation":""},{"id":"B","text":"$\\frac{x + 2}{x + 4}$","is_correct":false,"explanation":""},{"id":"C","text":"$\\frac{x-2}{x+4}$","is_correct":true,"explanation":""},{"id":"D","text":"$\\frac{x + 4}{x - 2}$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can factor the numerator and denominator of the given expression:  $\frac{x^2 - 2x - 8}{x^2 - 16} = \frac{(x-4)(x+2)}{(x+4)(x-4)}$  Since $x \neq 4$ and $x \neq -4$, we can cancel the common factors, leaving us with $\frac{x-2}{x+4}$. ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_196d6233d971faad_math_00369',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_a4","opensat_index":369}'::jsonb
  ),
(
    gen_random_uuid(),
    'A bakery sells cookies in packages of 6, 12, and 24. A customer buys 3 packages of cookies, and the total number of cookies is 42.  If the customer bought at least one package of each size, how many packages of 12 cookies did the customer buy?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":true,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Let x be the number of packages of 12 cookies the customer bought.  Since the customer bought at least one package of each size, the customer bought 1 package of 6 cookies and 1 package of 24 cookies.  The total number of cookies is 6 + 12x + 24 = 30 + 12x.  Since the total number of cookies is 42, we can set up the equation 30 + 12x = 42. Subtracting 30 from both sides of this equation yields 12x = 12.  Dividing both sides of this equation by 12 gives x = 1.  Therefore, the customer bought 1 package of 12 cookies.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_5ef5fc75c033338d_math_00370',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_c4","opensat_index":370}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the solution to the equation $2x - 3 = 5x + 6$?',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":true,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"3","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To solve for x, we can subtract 2x from both sides of the equation to get $-3 = 3x + 6$.  Then, we can subtract 6 from both sides of the equation to get $-9 = 3x$.  Dividing both sides of the equation by 3 gives us $x=-3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'a987655b_math_00371',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"a987655b","opensat_index":371}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm. A chord of the circle is 8 cm long. What is the distance, in cm, from the center of the circle to the chord?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Draw a radius from the center of the circle to each endpoint of the chord. This creates an isosceles triangle with a base of 8 cm and two sides of 5 cm. Draw the altitude from the center of the circle to the chord. This altitude bisects the base of the isosceles triangle, creating two right triangles with a hypotenuse of 5 cm and a leg of 4 cm. Using the Pythagorean Theorem, the other leg of the right triangle (which is the distance from the center of the circle to the chord) is  cm.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_a7047e0e8e85ee44_math_00372',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_e3","opensat_index":372}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = \frac{x^2 - 4}{x - 2}$. For what value of $x$ is $f(x)$ undefined?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The function $f(x)$ is undefined when the denominator, $x - 2$, is equal to zero. Solving the equation $x - 2 = 0$, we find that $x = 2$. Therefore, the function is undefined when $x = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'e8a94f9a_math_00373',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"e8a94f9a","opensat_index":373}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x + 2y = 6$ and $x - 2y = 4$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":true,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Adding the two equations together, we get $(x+2y) + (x-2y) = 6 + 4$, which simplifies to $2x = 10$.  Dividing both sides by 2, we get $x=5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'a934f7dd_math_00374',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"a934f7dd","opensat_index":374}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey asked 100 people whether they prefer apples or oranges. 60 people said they prefer apples, and 40 people said they prefer oranges. What percentage of the people surveyed prefer oranges?',
    'multiple_choice',
    '[{"id":"A","text":"4%","is_correct":false,"explanation":""},{"id":"B","text":"10%","is_correct":false,"explanation":""},{"id":"C","text":"40%","is_correct":true,"explanation":""},{"id":"D","text":"60%","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The percentage of people who prefer oranges is the number of people who prefer oranges divided by the total number of people surveyed, multiplied by 100%.  This is (40/100) * 100% = 40%.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_7d0665f18663a0aa_math_00375',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_10","opensat_index":375}'::jsonb
  ),
(
    gen_random_uuid(),
    'A square has side length $s$.  A rectangle has length $2s$ and width $s$. What is the ratio of the area of the rectangle to the area of the square?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{1}{2}$","is_correct":false,"explanation":""},{"id":"B","text":"1","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":true,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of the square is $s^2$. The area of the rectangle is $(2s)(s) = 2s^2$. The ratio of the area of the rectangle to the area of the square is $\frac{2s^2}{s^2} = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'b8e213d6_math_00376',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"b8e213d6","opensat_index":376}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units.  What is the circumference of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":true,"explanation":""},{"id":"C","text":"25\\pi","is_correct":false,"explanation":""},{"id":"D","text":"50\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula C = 2πr, where r is the radius.  Substituting 5 for r, we get C = 2π(5) = 10π.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'c4594b5d_math_00377',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"c4594b5d","opensat_index":377}'::jsonb
  ),
(
    gen_random_uuid(),
    'The expression  $90y^2 - 54y^2$ is equivalent to $ry(15y-9)$, where r is a constant.  What is the value of r?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":true,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The expression $90y^2-54y^2$ can be simplified by factoring out a common factor of $18y^2$, giving us $18y^2(5-3)$. Since $ry(15y-9)$ is equivalent to $18y^2(5-3)$, it follows that $ry(15y-9)$ can be rewritten as $18y^2(5-3)$.  We can see that the coefficient of y in the original expression is 90, while the coefficient of y in the simplified expression is 90.  This means that the value of r must be 6. Therefore, the value of r is 6.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '4a85fea6_math_00378',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"4a85fea6","opensat_index":378}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the equation of the line that passes through the points (-2, 5) and (1, -1)?',
    'multiple_choice',
    '[{"id":"A","text":"y = -2x + 1","is_correct":false,"explanation":""},{"id":"B","text":"y = -2x + 9","is_correct":true,"explanation":""},{"id":"C","text":"y = 2x + 1","is_correct":false,"explanation":""},{"id":"D","text":"y = 2x + 9","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To find the equation of the line, we first need to find the slope.  The slope is given by: \begin{align*} \text{slope} &= \frac{\text{change in }y}{\text{change in }x} \\ &= \frac{-1 - 5}{1 - (-2)}\\ &= \frac{-6}{3} \\ &= -2 \end{align*} Now, we can use the point-slope form of a linear equation, which is: $y - y_1 = m(x - x_1)$, where $m$ is the slope and $(x_1, y_1)$ is a point on the line. We can use either point given in the problem. Let''s use (-2, 5): $y - 5 = -2(x - (-2))$. Simplifying this equation, we get: $y - 5 = -2x - 4$  $y = -2x + 1$  Therefore, the equation of the line that passes through the points (-2, 5) and (1, -1) is $y = -2x + 1$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'd4e91cb7_math_00379',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"d4e91cb7","opensat_index":379}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 2x^2 - 3x + 1.  What is the value of *f*(2) + *f*(3)?',
    'multiple_choice',
    '[{"id":"A","text":"11","is_correct":false,"explanation":""},{"id":"B","text":"14","is_correct":false,"explanation":""},{"id":"C","text":"17","is_correct":true,"explanation":""},{"id":"D","text":"20","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find *f*(2), we substitute 2 for *x* in the function: *f*(2) = 2(2)^2 - 3(2) + 1 = 8 - 6 + 1 = 3. To find *f*(3), we substitute 3 for *x* in the function: *f*(3) = 2(3)^2 - 3(3) + 1 = 18 - 9 + 1 = 10.  Therefore, *f*(2) + *f*(3) = 3 + 10 = 13.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'a23f283c_math_00380',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"a23f283c","opensat_index":380}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function \(f\) is defined by \(f(x) = \frac{x^2 - 4}{x - 2}\).  For what value(s) of \(x\) is \(f(x)\) undefined?',
    'multiple_choice',
    '[{"id":"A","text":"2 only","is_correct":true,"explanation":""},{"id":"B","text":"-2 only","is_correct":false,"explanation":""},{"id":"C","text":"2 and -2","is_correct":false,"explanation":""},{"id":"D","text":"The function is defined for all values of \\(x\\)","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'A rational function is undefined when the denominator equals zero.  The denominator of \(f(x)\) is \(x-2\), which equals zero when \(x=2\).  Therefore, \(f(x)\) is undefined for \(x=2\) only.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '3e679962_math_00381',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"3e679962","opensat_index":381}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;

INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'The function $f(x) = 2x^2 + 3x - 5$ is defined for all real numbers $x$. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-15","is_correct":false,"explanation":""},{"id":"B","text":"-9","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"11","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substituting -2 for $x$ into the function, we get:  $f(-2) = 2(-2)^2 + 3(-2) - 5$. Simplifying, we have $f(-2) = 8 - 6 - 5 = 11$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_4f41c727b13d527f_math_00382',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_c9","opensat_index":382}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with center O has a radius of 5.  A chord AB of the circle is 8 units long.  What is the distance from the center O to chord AB?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Draw a radius from O to point A and a radius from O to point B.  Draw a segment from O perpendicular to AB, and let the point of intersection of the segment and AB be point C.  Triangle AOC is a right triangle with hypotenuse OA = 5 and AC = 4.  By the Pythagorean Theorem,  OC = \sqrt{5^2-4^2} = \sqrt{9} = 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_0fb13ab167efcc39_math_00383',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_a1","opensat_index":383}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store is having a sale on all items.  The price of a shirt is reduced from $\$25 to $\$15. What is the percent decrease in the price of the shirt?',
    'multiple_choice',
    '[{"id":"A","text":"10%","is_correct":false,"explanation":""},{"id":"B","text":"20%","is_correct":false,"explanation":""},{"id":"C","text":"30%","is_correct":false,"explanation":""},{"id":"D","text":"40%","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The price decrease is $25 - $15 = $10.  The percent decrease is the price decrease divided by the original price, multiplied by 100%:  $\frac{10}{25} \times 100% = 40%$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_8b2aea99733efc20_math_00384',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_c1","opensat_index":384}'::jsonb
  ),
(
    gen_random_uuid(),
    'The vertices of a triangle are located at the points $(0,0)$, $(4,0)$, and $(0,3)$. What is the area of the triangle?',
    'multiple_choice',
    '[{"id":"A","text":"6","is_correct":true,"explanation":""},{"id":"B","text":"12","is_correct":false,"explanation":""},{"id":"C","text":"18","is_correct":false,"explanation":""},{"id":"D","text":"24","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The triangle is a right triangle with a base of 4 units and a height of 3 units. The area of a triangle is given by (1/2) * base * height, so the area of this triangle is (1/2) * 4 * 3 = 6 square units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_5fd132af14493deb_math_00385',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_a2","opensat_index":385}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = 3x^2 + 5x - 2$ is defined for all real numbers. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-12","is_correct":false,"explanation":""},{"id":"B","text":"-4","is_correct":false,"explanation":""},{"id":"C","text":"8","is_correct":true,"explanation":""},{"id":"D","text":"16","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Substituting $-2$ for $x$ in the function $f(x) = 3x^2 + 5x - 2$ yields  $f(-2) = 3(-2)^2 + 5(-2) - 2$ = 12 - 10 - 2 = 8.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '949c662a_math_00386',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"949c662a","opensat_index":386}'::jsonb
  ),
(
    gen_random_uuid(),
    'The graph of the function \(f(x) = x^2 + 2x - 3\) intersects the x-axis at two points. What are the coordinates of these points of intersection?',
    'multiple_choice',
    '[{"id":"A","text":"(1, 0) and (-3, 0)","is_correct":true,"explanation":""},{"id":"B","text":"(-1, 0) and (3, 0)","is_correct":false,"explanation":""},{"id":"C","text":"(2, 0) and (-1, 0)","is_correct":false,"explanation":""},{"id":"D","text":"(-2, 0) and (1, 0)","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The x-intercepts of a function occur where the graph intersects the x-axis, meaning when y = 0. So, we need to solve the equation \(0 = x^2 + 2x - 3\). Factoring the quadratic, we get \(0 = (x+3)(x-1)\), which means \(x = -3\) or \(x = 1\).  Since the y-coordinate at the x-intercept is always 0, the points of intersection are (1, 0) and (-3, 0).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '8436f365_math_00387',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"8436f365","opensat_index":387}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = \sqrt{x} - 4$. For what value of $x$ does $f(x) = 9$?',
    'multiple_choice',
    '[{"id":"A","text":"13","is_correct":false,"explanation":""},{"id":"B","text":"81","is_correct":false,"explanation":""},{"id":"C","text":"169","is_correct":true,"explanation":""},{"id":"D","text":"289","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for $x$, we set the function equal to 9: $\sqrt{x} - 4 = 9$. Adding 4 to both sides gives us $\sqrt{x} = 13$. Squaring both sides, we get $x = 13^2$, or $x = 169$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_e03452986a76eb94_math_00388',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_5","opensat_index":388}'::jsonb
  ),
(
    gen_random_uuid(),
    'In the $xy$-plane, a circle with center $(2,-3)$ is tangent to the line $y = 5$. What is the radius of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"5","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The radius of the circle is the perpendicular distance from the center of the circle to the tangent line.  Since the center of the circle is $(2,-3)$ and the tangent line is $y=5$, the radius is the difference between the y-coordinate of the center and the y-coordinate of the line, which is $5 - (-3) = 8$.  Therefore, the radius of the circle is 8.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '8976e141_math_00389',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"8976e141","opensat_index":389}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 centimeters. What is the circumference of the circle, in centimeters? (Express your answer in terms of $\pi$.)',
    'multiple_choice',
    '[{"id":"A","text":"$\\pi$","is_correct":false,"explanation":""},{"id":"B","text":"$5\\pi$","is_correct":false,"explanation":""},{"id":"C","text":"$10\\pi$","is_correct":true,"explanation":""},{"id":"D","text":"$25\\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius of the circle.  Substituting 5 for $r$, we get $C = 2\pi(5) = 10\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '34652f15_math_00390',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"34652f15","opensat_index":390}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x + y = 5$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Adding the two equations together, we get $(x + y) + (x - y) = 5 + 1$, which simplifies to $2x = 6$. Dividing both sides by 2, we find that $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_925e128c22ca8702_math_00391',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_a2","opensat_index":391}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 2x - 8 = 0$, what is the sum of the solutions to this equation?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"0","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The sum of the solutions to the quadratic equation $ax^2 + bx + c = 0$ is given by $-b/a$.  Factoring the given quadratic equation yields $(x - 4)(x + 2) = 0$. Therefore, the solutions to the equation are $x = 4$ and $x = -2$.  The sum of these solutions is $4 + (-2) = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_84b8b060145fb8ed_math_00392',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_c4","opensat_index":392}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units.  What is the area of the circle, in square units?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":true,"explanation":""},{"id":"D","text":"100\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula $A = \pi r^2$, where r is the radius of the circle.  Substituting r = 5 into the formula gives $A = \pi (5)^2 = 25\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_e95b8254796dfc0f_math_00393',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_a4","opensat_index":393}'::jsonb
  ),
(
    gen_random_uuid(),
    'A regular hexagon is inscribed in a circle with radius 10. What is the perimeter of the hexagon?',
    'multiple_choice',
    '[{"id":"A","text":"30","is_correct":false,"explanation":""},{"id":"B","text":"60","is_correct":true,"explanation":""},{"id":"C","text":"60\\sqrt{3}","is_correct":false,"explanation":""},{"id":"D","text":"120\\sqrt{3}","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A regular hexagon can be divided into 6 equilateral triangles.  The side length of each equilateral triangle is equal to the radius of the circle, which is 10.  Thus, the perimeter of the hexagon is 6 * 10 = 60.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'e9ff8933_math_00394',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"e9ff8933","opensat_index":394}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people like apples, 40 people like oranges, and 20 people like both apples and oranges. How many people like only oranges?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":true,"explanation":""},{"id":"B","text":"20","is_correct":false,"explanation":""},{"id":"C","text":"30","is_correct":false,"explanation":""},{"id":"D","text":"40","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can use a Venn diagram to visualize the information. Since 20 people like both apples and oranges, 60 - 20 = 40 people like only apples and 40 - 20 = 20 people like only oranges.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_9eb79a3c55a9fec2_math_00395',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_b8","opensat_index":395}'::jsonb
  ),
(
    gen_random_uuid(),
    'The area of a circle is 36$\pi$ square meters.  What is the circumference of the circle, in meters?',
    'multiple_choice',
    '[{"id":"A","text":"6$\\pi$","is_correct":false,"explanation":""},{"id":"B","text":"12$\\pi$","is_correct":true,"explanation":""},{"id":"C","text":"18$\\pi$","is_correct":false,"explanation":""},{"id":"D","text":"36$\\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The area of a circle is given by $A = \pi r^2$, where $r$ is the radius of the circle.  We are given that the area is 36$\pi$ square meters, so $36\pi = \pi r^2$. Dividing both sides by $\pi$ gives $36 = r^2$. Taking the square root of both sides gives $r = 6$. The circumference of a circle is given by $C = 2\pi r$. Substituting 6 for $r$ gives $C = 2\pi(6) = 12\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_cfe0cfbdbe66a4f6_math_00396',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_e9","opensat_index":396}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells apples for $1.25 each and oranges for $0.75 each.  A customer buys 3 apples and 5 oranges. What is the total cost, in dollars, of the customer''s purchase?',
    'multiple_choice',
    '[{"id":"A","text":"6.25","is_correct":false,"explanation":""},{"id":"B","text":"7.50","is_correct":false,"explanation":""},{"id":"C","text":"8.75","is_correct":false,"explanation":""},{"id":"D","text":"9.25","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The cost of the apples is 3 * $1.25 = $3.75.  The cost of the oranges is 5 * $0.75 = $3.75.  The total cost is $3.75 + $3.75 = $7.50.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_8fb395309980a38c_math_00397',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_1","opensat_index":397}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 2x + 1 = 0$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":true,"explanation":""},{"id":"B","text":"0","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"2","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The expression on the left side of the equation is a perfect square trinomial: $(x + 1)^2$.  Taking the square root of both sides, we get $x + 1 = 0$.  Subtracting 1 from both sides gives us $x = -1$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'f4a9fd2e_math_00398',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"f4a9fd2e","opensat_index":398}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = 3x^2 - 2x + 1$. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-9","is_correct":false,"explanation":""},{"id":"B","text":"1","is_correct":false,"explanation":""},{"id":"C","text":"13","is_correct":false,"explanation":""},{"id":"D","text":"17","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find the value of f(-2), we substitute -2 for x in the function: f(-2) = 3(-2)^2 - 2(-2) + 1. Simplifying, we get f(-2) = 3(4) + 4 + 1 = 12 + 4 + 1 = 17.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'e16a3ff5_math_00399',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"e16a3ff5","opensat_index":399}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 centimeters. What is the circumference of the circle, in centimeters? (Express your answer in terms of $\pi$.)',
    'multiple_choice',
    '[{"id":"A","text":"$\\pi$","is_correct":false,"explanation":""},{"id":"B","text":"$5\\pi$","is_correct":false,"explanation":""},{"id":"C","text":"$10\\pi$","is_correct":true,"explanation":""},{"id":"D","text":"$25\\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius.  Substituting 5 for $r$ gives $C = 2\pi (5) = 10\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'f86d2a4f_math_00400',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"f86d2a4f","opensat_index":400}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 6x + 5 = 0$, what is the sum of the solutions to the equation?',
    'multiple_choice',
    '[{"id":"A","text":"5","is_correct":false,"explanation":""},{"id":"B","text":"6","is_correct":true,"explanation":""},{"id":"C","text":"11","is_correct":false,"explanation":""},{"id":"D","text":"-6","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The sum of the solutions to a quadratic equation in the form $ax^2 + bx + c = 0$ is equal to $-b/a$.  In this case, $a = 1$ and $b = -6$, so the sum of the solutions is $-(-6)/1 = 6$. ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_220a2a76c802e38a_math_00401',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_c2","opensat_index":401}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with center O has a radius of 5.  A chord AB of the circle has length 8.  What is the distance from O to the chord AB?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Draw a segment from O perpendicular to chord AB, intersecting AB at point M.  Since the perpendicular from the center of a circle to a chord bisects the chord, AM = MB = 4.  Triangle OAM is a right triangle with OA as the hypotenuse and AM as a leg.  By the Pythagorean Theorem, .  Therefore, OM = 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_b026b93190344080_math_00402',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_c1","opensat_index":402}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units. A chord of the circle is 8 units long. What is the distance, in units, from the center of the circle to the chord?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Draw a diagram of the circle with the chord and the radius drawn to the midpoint of the chord.  The radius, the chord, and the line segment from the center of the circle to the midpoint of the chord form a right triangle, with the radius being the hypotenuse. Since the chord is 8 units long, the line segment from the center of the circle to the midpoint of the chord is 4 units long.  The Pythagorean Theorem tells us that  The distance from the center of the circle to the chord is 3 units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_d54dce100deb6b86_math_00403',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_a11","opensat_index":403}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells two types of cookies: chocolate chip and peanut butter.  On a particular day, the store sold 180 chocolate chip cookies. If the ratio of chocolate chip cookies to peanut butter cookies sold that day was 5:3, how many peanut butter cookies did the store sell?',
    'multiple_choice',
    '[{"id":"A","text":"60","is_correct":false,"explanation":""},{"id":"B","text":"90","is_correct":false,"explanation":""},{"id":"C","text":"108","is_correct":true,"explanation":""},{"id":"D","text":"180","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The ratio 5:3 means that for every 5 chocolate chip cookies sold, 3 peanut butter cookies were sold. We can set up a proportion:  \frac{5}{3} = \frac{180}{x}.  Cross-multiplying gives 5x = 540.  Dividing both sides by 5 gives $x = 108$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '54f587b2_math_00404',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"54f587b2","opensat_index":404}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with center (2, -1) is tangent to the x-axis. What is the radius of this circle? ',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":true,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Since the circle is tangent to the x-axis, the distance from the center of the circle to the x-axis is equal to the radius. The y-coordinate of the center is -1, so the radius of the circle is 1.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '97fb89f7_math_00405',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"97fb89f7","opensat_index":405}'::jsonb
  ),
(
    gen_random_uuid(),
    'In the xy-plane, a circle has a radius of 5 and a center at (3, -2). What is the equation of this circle?',
    'multiple_choice',
    '[{"id":"A","text":"(x - 3)^2 + (y + 2)^2 = 25","is_correct":true,"explanation":""},{"id":"B","text":"(x + 3)^2 + (y - 2)^2 = 5","is_correct":false,"explanation":""},{"id":"C","text":"(x + 3)^2 + (y - 2)^2 = 25","is_correct":false,"explanation":""},{"id":"D","text":"(x - 3)^2 + (y + 2)^2 = 5","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The standard form of the equation of a circle with center (h, k) and radius r is (x - h)^2 + (y - k)^2 = r^2. Substituting the given values of (h, k) = (3, -2) and r = 5, we get the equation (x - 3)^2 + (y + 2)^2 = 25.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_2f93035e17888838_math_00406',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_d4","opensat_index":406}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;