INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'The function f(x) is defined by $f(x)=3x^{2}-2x+1$. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-9","is_correct":false,"explanation":""},{"id":"B","text":"-3","is_correct":false,"explanation":""},{"id":"C","text":"13","is_correct":false,"explanation":""},{"id":"D","text":"21","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find f(-2), we substitute -2 for *x* in the function:  

 f(-2) = 3(-2)^2 - 2(-2) + 1  

 f(-2) = 3(4) + 4 + 1  

 f(-2) = 12 + 4 + 1  

 f(-2) = 17',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_6c7c70ed661a4427_math_00907',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_a10","opensat_index":907}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a radius of 5 centimeters is inscribed in a square. What is the area, in square centimeters, of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square. Since the radius of the circle is 5 centimeters, the diameter is 10 centimeters. Therefore, the side length of the square is 10 centimeters, and the area of the square is 10*10 = 100 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_e39cdbc9c56f66ef_math_00908',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_b8","opensat_index":908}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $f(x) = \frac{x^2 - 4}{x - 2}$ for $x \neq 2$, what is the value of $f(4)$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can simplify the function first by factoring the numerator: $f(x) = \frac{(x+2)(x-2)}{x-2}$. Since $x \neq 2$, we can cancel the common factor of $x-2$, giving us $f(x) = x+2$. Therefore, $f(4) = 4 + 2 = 6$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '232e1e87_math_00909',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"232e1e87","opensat_index":909}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for $x$, we can use elimination.  Multiplying the second equation by 3, we get $3x - 3y = 3$. Adding this equation to the first equation, we get $5x = 15$. Dividing both sides by 5, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_5a304dcf7022c1be_math_00910',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_c9","opensat_index":910}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 200 people found that 120 people prefer brand A, and 80 people prefer brand B. What percentage of people prefer brand B?',
    'multiple_choice',
    '[{"id":"A","text":"40%","is_correct":true,"explanation":""},{"id":"B","text":"60%","is_correct":false,"explanation":""},{"id":"C","text":"80%","is_correct":false,"explanation":""},{"id":"D","text":"120%","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To find the percentage of people who prefer brand B, divide the number of people who prefer brand B by the total number of people surveyed and multiply by 100%: (80/200) * 100% = 40%.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '4f556789_math_00911',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"4f556789","opensat_index":911}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $x^2 - 6x + k = 0$ has exactly one solution. What is the value of $k$?',
    'multiple_choice',
    '[{"id":"A","text":"9","is_correct":true,"explanation":""},{"id":"B","text":"-9","is_correct":false,"explanation":""},{"id":"C","text":"36","is_correct":false,"explanation":""},{"id":"D","text":"-36","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'A quadratic equation has exactly one solution when its discriminant is equal to 0. The discriminant of the quadratic equation  is , where a, b, and c are the coefficients of the quadratic equation.  In this equation, a=1, b=-6, and c=k.  Substituting these values into the discriminant formula yields .  Setting the discriminant equal to zero yields , or k = 9.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '7679a5a5_math_00912',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"7679a5a5","opensat_index":912}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has legs of length 5 and 12. What is the length of the hypotenuse?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"13","is_correct":true,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"19","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs.  Therefore, the length of the hypotenuse is $\sqrt{5^2 + 12^2} = \sqrt{169} = 13$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '34b49314_math_00913',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"34b49314","opensat_index":913}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x + 2y = 10$ and $x - y = 2$, what is the value of $x + y$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for $x + y$, we can manipulate the given equations. Multiplying the second equation by 2, we get $2x - 2y = 4$. Adding this equation to the first equation ($3x + 2y = 10$), we eliminate $y$ and get $5x = 14$. Dividing both sides by 5, we find that $x = \frac{14}{5}$. Substituting this value of $x$ into the second equation, we get $\frac{14}{5} - y = 2$. Solving for $y$ yields $y = \frac{4}{5}$. Therefore, $x + y = \frac{14}{5} + \frac{4}{5} = \frac{18}{5} = 3\frac{3}{5}$. Since the answer must be an integer, the answer is 6.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_aa57fd8b70d03efd_math_00914',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_e5","opensat_index":914}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 2x^2 - 5x + 3. What is the value of *f*(-2)?',
    'multiple_choice',
    '[{"id":"A","text":"-19","is_correct":false,"explanation":""},{"id":"B","text":"-11","is_correct":false,"explanation":""},{"id":"C","text":"11","is_correct":false,"explanation":""},{"id":"D","text":"19","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substituting -2 for *x* in the function *f*(x) = 2x^2 - 5x + 3 gives us *f*(-2) = 2(-2)^2 - 5(-2) + 3. Simplifying, we get *f*(-2) = 8 + 10 + 3, or *f*(-2) = 19.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_6b1b398cd684f3f7_math_00915',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_a9","opensat_index":915}'::jsonb
  ),
(
    gen_random_uuid(),
    'A square has a side length of 5.  What is the length of the diagonal of the square?',
    'multiple_choice',
    '[{"id":"A","text":"5","is_correct":false,"explanation":""},{"id":"B","text":"5\\sqrt{2}","is_correct":true,"explanation":""},{"id":"C","text":"10","is_correct":false,"explanation":""},{"id":"D","text":"10\\sqrt{2}","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The diagonal of a square divides the square into two right triangles. The diagonal of the square is the hypotenuse of these right triangles. Since the sides of the square are the legs of the right triangles, we can use the Pythagorean Theorem: a^2 + b^2 = c^2, where a and b are the legs of the right triangle and c is the hypotenuse. In this case, a = 5 and b = 5, so we have 5^2 + 5^2 = c^2. Simplifying, we get 25 + 25 = c^2, or 50 = c^2. Taking the square root of both sides gives c = \sqrt{50} = \sqrt{25*2} = 5\sqrt{2}$. Therefore, the length of the diagonal of the square is 5\sqrt{2}.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '60eb6869_math_00916',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"60eb6869","opensat_index":916}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $f(x) = 2x^2 + 3x - 1$, what is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-9","is_correct":true,"explanation":""},{"id":"B","text":"-3","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Substitute -2 for x in the expression for f(x):  
$f(-2) = 2(-2)^2 + 3(-2) - 1 = 2(4) - 6 - 1 = 8 - 6 - 1 = -9$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '28f4d38a_math_00917',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"28f4d38a","opensat_index":917}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 centimeters. What is the area of the circle, in square centimeters?  (Use 3.14 for $\pi$)',
    'multiple_choice',
    '[{"id":"A","text":"15.7","is_correct":false,"explanation":""},{"id":"B","text":"31.4","is_correct":false,"explanation":""},{"id":"C","text":"78.5","is_correct":true,"explanation":""},{"id":"D","text":"157","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula $A = \pi r^2$, where $r$ is the radius of the circle. In this case, the radius is 5 centimeters. So, the area is $A = (3.14)(5^2) = (3.14)(25) = 78.5$ square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_24ad0ea39bd39531_math_00918',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_b8","opensat_index":918}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for x, we can use elimination.  Multiplying the second equation by 3, we get $3x - 3y = 3$.  Adding this equation to the first equation, we get $5x = 15$.  Dividing both sides by 5 gives us $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_033afa92960edd97_math_00919',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_a2","opensat_index":919}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x - 2y = 10$ and $x + 2y = 6$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Adding the two equations together, we get $(3x - 2y) + (x + 2y) = 10 + 6$. This simplifies to $4x = 16$, so $x = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_0995747ef8ba15ef_math_00920',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_a3","opensat_index":920}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store is selling shirts for $\$15$ each.  If a customer buys 3 shirts and uses a coupon for $\$5$ off their total purchase, what is the total cost of the shirts?',
    'multiple_choice',
    '[{"id":"A","text":"$\\$35$","is_correct":false,"explanation":""},{"id":"B","text":"$\\$40$","is_correct":true,"explanation":""},{"id":"C","text":"$\\$45$","is_correct":false,"explanation":""},{"id":"D","text":"$\\$50$","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The total cost of 3 shirts without the coupon is 3 x $15 = $45.  With the coupon, the total cost is $45 - $5 = $40.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_e0f6df166f4ea807_math_00921',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_a5","opensat_index":921}'::jsonb
  ),
(
    gen_random_uuid(),
    'The lengths of the sides of a triangle are 5, 12, and 13.  Is this triangle a right triangle?  Explain your reasoning.',
    'multiple_choice',
    '[{"id":"A","text":"Yes, because the triangle satisfies the Pythagorean Theorem: 5^2 + 12^2 = 13^2.","is_correct":true,"explanation":""},{"id":"B","text":"Yes, because the triangle has one angle that measures 90 degrees.","is_correct":false,"explanation":""},{"id":"C","text":"No, because the triangle is not a right triangle, and the angles do not measure 90 degrees.","is_correct":false,"explanation":""},{"id":"D","text":"No, because the triangle does not satisfy the Pythagorean Theorem: 5^2 + 12^2 ≠ 13^2.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the other two sides. In this case, 5^2 + 12^2 = 25 + 144 = 169, and 13^2 = 169.  Since the sides satisfy the Pythagorean Theorem, the triangle is a right triangle.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_4c1ec0b0c4926ff1_math_00922',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_17","opensat_index":922}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells apples for $1.50 per pound and oranges for $2.25 per pound.  If a customer buys 3 pounds of apples and 2 pounds of oranges, how much does the customer spend in total?',
    'multiple_choice',
    '[{"id":"A","text":"$5.25","is_correct":false,"explanation":""},{"id":"B","text":"$6.75","is_correct":false,"explanation":""},{"id":"C","text":"$7.50","is_correct":false,"explanation":""},{"id":"D","text":"$9.00","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The customer spends 3 * $1.50 = $4.50 on apples and 2 * $2.25 = $4.50 on oranges. The total cost is $4.50 + $4.50 = $9.00.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_f6d35ec542068f24_math_00923',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_b5","opensat_index":923}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  $\frac{x-3}{x+2} = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-5","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To solve for *x*, we first multiply both sides of the equation by *x + 2*:  $x - 3 = x + 2$. Subtracting *x* from both sides, we get -3 = 2. This is a contradiction, which means there is no solution to the equation.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_eabdec4cbce77ccf_math_00924',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_c3","opensat_index":924}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 randomly selected students found that 60 students prefer to eat pizza for lunch, 30 students prefer to eat a sandwich for lunch, and 10 students prefer to eat salad for lunch.  If the survey results are representative of the entire student body, what is the probability that a randomly selected student prefers to eat a sandwich for lunch?  Express your answer as a decimal.',
    'multiple_choice',
    '[{"id":"A","text":"0.1","is_correct":false,"explanation":""},{"id":"B","text":"0.3","is_correct":true,"explanation":""},{"id":"C","text":"0.6","is_correct":false,"explanation":""},{"id":"D","text":"0.9","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Since 30 out of the 100 students surveyed prefer sandwiches, the probability that a randomly selected student prefers to eat a sandwich for lunch is 30/100, or 0.3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_6ae3c0be5e49001c_math_00925',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_c5","opensat_index":925}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a radius of 5 centimeters is inscribed in a square. What is the area, in square centimeters, of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square. Since the radius of the circle is 5 centimeters, the diameter is 10 centimeters. Therefore, the side length of the square is 10 centimeters, and the area of the square is 10^2 = 100 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_3d9f349e2480409d_math_00926',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_a5","opensat_index":926}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey asked 100 people whether they prefer apples or oranges. 60 people said they prefer apples, and 40 people said they prefer oranges. What is the ratio of the number of people who prefer apples to the number of people who prefer oranges, expressed in simplest form?',
    'multiple_choice',
    '[{"id":"A","text":"3:2","is_correct":true,"explanation":""},{"id":"B","text":"2:3","is_correct":false,"explanation":""},{"id":"C","text":"3:4","is_correct":false,"explanation":""},{"id":"D","text":"4:3","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The ratio of people who prefer apples to the number of people who prefer oranges is 60:40. Dividing both sides of this ratio by 20 gives the equivalent ratio 3:2.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_84dd6d1ae10779fc_math_00927',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_b8","opensat_index":927}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle is inscribed in a square. The side length of the square is 10 centimeters. What is the area, in square centimeters, of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"25\\pi","is_correct":true,"explanation":""},{"id":"B","text":"50\\pi","is_correct":false,"explanation":""},{"id":"C","text":"100\\pi","is_correct":false,"explanation":""},{"id":"D","text":"400\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The diameter of the circle is equal to the side length of the square, which is 10 centimeters.  The radius of the circle is half the diameter, or 5 centimeters. The area of the circle is $\pi r^2$, or $\pi (5)^2 = 25\pi$ square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_8fcf2efa5f513c57_math_00928',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_c6","opensat_index":928}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for x, we can use elimination.  Multiplying the second equation by 3 gives us $3x - 3y = 3$.  Adding this equation to the first equation, we get $5x = 15$. Dividing both sides by 5, we find that $x=3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_255218599de16feb_math_00929',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_b6","opensat_index":929}'::jsonb
  ),
(
    gen_random_uuid(),
    'In the figure below, right triangle $ABC$ has a right angle at $C$, and $AC = 6$ and $BC = 8$. What is the length of the hypotenuse $AB$?  [asy] draw((0,0)--(8,0)--(0,6)--cycle); draw((0,0)--(8,0),EndArrow); draw((0,0)--(0,6),EndArrow); label("A",(0,0),SW); label("B",(8,0),SE); label("C",(0,6),NW); label("6",(0,3),W); label("8",(4,0),S); [/asy]',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":true,"explanation":""},{"id":"B","text":"12","is_correct":false,"explanation":""},{"id":"C","text":"14","is_correct":false,"explanation":""},{"id":"D","text":"16","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Triangle $ABC$ is a right triangle, so we can use the Pythagorean Theorem to find the length of the hypotenuse. The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the other two sides. In this case, we have $AB^2 = AC^2 + BC^2$, so $AB^2 = 6^2 + 8^2 = 36 + 64 = 100$. Taking the square root of both sides, we get $AB = \sqrt{100}$, or $AB = 10$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_e9dbef981886bf9a_math_00930',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_c8","opensat_index":930}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x+3y=12$ and $x-y=1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve this system of equations using elimination.  Multiplying the second equation by 3, we get $3x-3y=3$. Adding this equation to the first equation, we get $5x=15$. Dividing both sides by 5, we find $x=3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_a119469d5bb6977a_math_00931',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_c11","opensat_index":931}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;

INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'A rectangular box has a length of 10 cm, a width of 5 cm, and a height of 8 cm. What is the volume of the box in cubic centimeters?',
    'multiple_choice',
    '[{"id":"A","text":"40","is_correct":false,"explanation":""},{"id":"B","text":"80","is_correct":false,"explanation":""},{"id":"C","text":"400","is_correct":false,"explanation":""},{"id":"D","text":"4000","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The volume of a rectangular box is calculated by multiplying its length, width, and height. Therefore, the volume of the box is 10 cm × 5 cm × 8 cm = 400 cubic centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '12d8c11d_math_00932',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"12d8c11d","opensat_index":932}'::jsonb
  ),
(
    gen_random_uuid(),
    'The following data set represents the number of hours a group of students spent studying for an exam: 2, 2, 3, 4, 4, 4, 8, 8, 8, 13, 13. What is the median number of hours spent studying for the exam?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":false,"explanation":""},{"id":"B","text":"6","is_correct":false,"explanation":""},{"id":"C","text":"8","is_correct":true,"explanation":""},{"id":"D","text":"13","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find the median, we must first order the data set from least to greatest: 2, 2, 3, 4, 4, 4, 8, 8, 8, 13, 13. Since there are 11 data points (an odd number), the median is the middle value, which is 8.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '52f9a246_math_00933',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"52f9a246","opensat_index":933}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = x^2 + 3x - 4. What are the *x*-intercepts of the graph of *y* = *f*(x) in the *xy*-plane?',
    'multiple_choice',
    '[{"id":"A","text":"-4 and 1","is_correct":false,"explanation":""},{"id":"B","text":"-1 and 4","is_correct":true,"explanation":""},{"id":"C","text":"0 and 4","is_correct":false,"explanation":""},{"id":"D","text":"1 and -4","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The *x*-intercepts of the graph of *y* = *f*(x) occur when *y* = 0.  So we need to solve the equation 0 = x^2 + 3x - 4.  Factoring this quadratic equation, we get 0 = (x + 4)(x - 1).  Therefore, the *x*-intercepts are at *x* = -4 and *x* = 1.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '98765432_math_00934',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"98765432","opensat_index":934}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $\log_2 8 = x$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The equation $\log_2 8 = x$ is equivalent to $2^x = 8$. Since $2^3 = 8$, the value of $x$ is 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_6242fea9f156496c_math_00935',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_a7","opensat_index":935}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function \(f(x)\) is defined by \(f(x) = x^3 + 2x^2 - 5x - 6\). What is the value of \(f(-2)\)?',
    'multiple_choice',
    '[{"id":"A","text":"-10","is_correct":false,"explanation":""},{"id":"B","text":"0","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":true,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can find the value of \(f(-2)\) by substituting -2 for x in the function: \(f(-2) = (-2)^3 + 2(-2)^2 - 5(-2) - 6 = -8 + 8 + 10 - 6 = 6\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '301a429b_math_00936',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"301a429b","opensat_index":936}'::jsonb
  ),
(
    gen_random_uuid(),
    'For all positive values of $x$, the expression $(\frac{x^2}{x^3 - 1})^{-1}$ is equivalent to which of the following expressions?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{x^3 - 1}{x^2}$","is_correct":true,"explanation":""},{"id":"B","text":"$\\frac{x^2}{x^3 - 1}$","is_correct":false,"explanation":""},{"id":"C","text":"$x^3 - 1$","is_correct":false,"explanation":""},{"id":"D","text":"$x^2$","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Recall that a term raised to a negative exponent is equivalent to its reciprocal with a positive exponent. Thus, $(\frac{x^2}{x^3 - 1})^{-1} = (\frac{x^3 - 1}{x^2})^1 = \frac{x^3 - 1}{x^2}$. ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'a94182ab_math_00937',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"a94182ab","opensat_index":937}'::jsonb
  ),
(
    gen_random_uuid(),
    'If the expression $\frac{4x^3 + 2x^2 - 6x}{2x}$ is simplified, what is the result?',
    'multiple_choice',
    '[{"id":"A","text":"$2x^2 + x - 3$","is_correct":true,"explanation":""},{"id":"B","text":"$2x^3 + x^2 - 3x$","is_correct":false,"explanation":""},{"id":"C","text":"$2x^2 + x$","is_correct":false,"explanation":""},{"id":"D","text":"$2x^2 - 3$","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Factoring out a 2x from the numerator, we get  $\frac{2x(2x^2 + x - 3)}{2x}$. Since x cannot be 0, we can cancel out the common factor of 2x, resulting in $2x^2 + x - 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '1743968a_math_00938',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"1743968a","opensat_index":938}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^{2} - 2x - 15 = 0$, what are the values of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-3 and 5","is_correct":false,"explanation":""},{"id":"B","text":"-5 and 3","is_correct":true,"explanation":""},{"id":"C","text":"3 and -5","is_correct":false,"explanation":""},{"id":"D","text":"5 and -3","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The equation $x^{2} - 2x - 15 = 0$ can be factored as $(x - 5)(x + 3) = 0$.  Setting each factor equal to zero, we get $x - 5 = 0$ or $x + 3 = 0$.  Solving for $x$, we find that $x = 5$ or $x = -3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_73cd3991ea98eeff_math_00939',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_a3","opensat_index":939}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm. What is the circumference of the circle, in terms of $\pi$?',
    'multiple_choice',
    '[{"id":"A","text":"$5\\pi$ cm","is_correct":false,"explanation":""},{"id":"B","text":"$10\\pi$ cm","is_correct":true,"explanation":""},{"id":"C","text":"$25\\pi$ cm","is_correct":false,"explanation":""},{"id":"D","text":"$50\\pi$ cm","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius. Substituting $r = 5$ cm, we get $C = 2\pi (5) = 10\pi$ cm.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_c6b099917808a6da_math_00940',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_b8","opensat_index":940}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangular prism has a volume of 72 cubic centimeters. If the length of the prism is 6 centimeters and the width is 4 centimeters, what is the height of the prism, in centimeters?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":true,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"12","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The volume of a rectangular prism is given by the formula $V = lwh$, where $l$ is the length, $w$ is the width, and $h$ is the height. We are given that the volume $V = 72$, the length $l = 6$, and the width $w = 4$.  Substituting these values into the formula, we get $72 = 6 \cdot 4 \cdot h$.  Simplifying the equation, we get $72 = 24h$.  Dividing both sides by 24, we get $h = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '14f4c19a_math_00941',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"14f4c19a","opensat_index":941}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with center $O$ has radius 10.  Points $A$ and $B$ lie on the circle, and the measure of central angle $AOB$ is 120 degrees.  What is the area of sector $AOB$?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{100\\pi}{3}$","is_correct":true,"explanation":""},{"id":"B","text":"$\\frac{50\\pi}{3}$","is_correct":false,"explanation":""},{"id":"C","text":"$100\\pi$","is_correct":false,"explanation":""},{"id":"D","text":"$50\\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The area of a sector of a circle is given by the formula  $\frac{\theta}{360} \pi r^2$, where $\theta$ is the measure of the central angle in degrees and r is the radius of the circle. In this case, $\theta = 120$ and $r = 10$, so the area of sector $AOB$ is $\frac{120}{360} \pi (10)^2 = \frac{100\pi}{3}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_047f1b8aacdc54f1_math_00942',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_c7","opensat_index":942}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the solution to the equation $2x - 3 = 7$?',
    'multiple_choice',
    '[{"id":"A","text":"-5","is_correct":false,"explanation":""},{"id":"B","text":"-2","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Adding 3 to both sides of the equation gives $2x = 10$. Dividing both sides by 2 gives $x = 5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '28f5623d_math_00943',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"28f5623d","opensat_index":943}'::jsonb
  ),
(
    gen_random_uuid(),
    'In the $xy$-plane, a circle with center $(2, -3)$ passes through the point $(5,1)$. What is the radius of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The radius of the circle is the distance from the center of the circle to any point on the circle. We can use the distance formula to find the distance between the center $(2,-3)$ and the point $(5,1)$: $\sqrt{(5-2)^2 + (1-(-3))^2} = \sqrt{3^2 + 4^2} = \sqrt{25} = 5$. Therefore, the radius of the circle is 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'b881f345_math_00944',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"b881f345","opensat_index":944}'::jsonb
  ),
(
    gen_random_uuid(),
    'A system of linear equations is graphed in the xy-plane. The equations are $x + 2y = 1$ and $x - 2y = -1$. Which of the following points represents a solution to the system? ',
    'multiple_choice',
    '[{"id":"A","text":"(-1, 1)","is_correct":false,"explanation":""},{"id":"B","text":"(0, 1)","is_correct":false,"explanation":""},{"id":"C","text":"(1, -1)","is_correct":false,"explanation":""},{"id":"D","text":"(1, 0)","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To solve the system of equations, we can use the elimination method.  Adding the two equations together, we get 2x = 0, which means x = 0.  Substituting 0 for x in either equation, we get 2y = 1, or y = 1/2. The solution to the system is (0, 1/2), but that point isn''t listed as an answer choice.  The point (1, 0) satisfies both equations, and therefore represents a solution to the system.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '77814f0c_math_00945',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"77814f0c","opensat_index":945}'::jsonb
  ),
(
    gen_random_uuid(),
    'The length of a rectangle is 12 inches and the width is 5 inches.  What is the area, in square inches, of the rectangle?',
    'multiple_choice',
    '[{"id":"A","text":"17","is_correct":false,"explanation":""},{"id":"B","text":"34","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":true,"explanation":""},{"id":"D","text":"72","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is the product of its length and width.  The area of the rectangle is 12 inches * 5 inches = 60 square inches.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_d98dd3b7e7570864_math_00946',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_c2","opensat_index":946}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 centimeters.  What is the circumference of the circle, in centimeters?  (Express your answer in terms of $\pi$.)',
    'multiple_choice',
    '[{"id":"A","text":"5$\\pi$","is_correct":false,"explanation":""},{"id":"B","text":"10$\\pi$","is_correct":true,"explanation":""},{"id":"C","text":"25$\\pi$","is_correct":false,"explanation":""},{"id":"D","text":"50$\\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius.  Substituting 5 for $r$ gives $C = 2\pi(5) = 10\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_12134dd006f3f02f_math_00947',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_a9","opensat_index":947}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x+5 = 10$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"5","is_correct":true,"explanation":""},{"id":"B","text":"10","is_correct":false,"explanation":""},{"id":"C","text":"15","is_correct":false,"explanation":""},{"id":"D","text":"50","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To solve for x, we subtract 5 from both sides of the equation:  $x + 5 - 5 = 10 - 5$.  This gives us $x = 5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_3fafd35fce97e495_math_00948',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_c7","opensat_index":948}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined as $f(x) = 3x^2 - 2x + 1$.  What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-11","is_correct":false,"explanation":""},{"id":"B","text":"11","is_correct":false,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"23","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find $f(-2)$, we substitute -2 for $x$ in the function: $f(-2) = 3(-2)^2 - 2(-2) + 1$. Simplifying, we get $f(-2) = 3(4) + 4 + 1 = 12 + 4 + 1 = 17$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_12fb8e831ac44d75_math_00949',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_a8","opensat_index":949}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5. What is the circumference of the circle? (Express your answer in terms of *pi*)',
    'multiple_choice',
    '[{"id":"A","text":"5*pi","is_correct":false,"explanation":""},{"id":"B","text":"10*pi","is_correct":true,"explanation":""},{"id":"C","text":"25*pi","is_correct":false,"explanation":""},{"id":"D","text":"50*pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula C = 2 * pi * r, where r is the radius.  Substituting 5 for r, we get C = 2 * pi * 5 = 10*pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'd7546482_math_00950',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"d7546482","opensat_index":950}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units. What is the area of the circle in square units?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":true,"explanation":""},{"id":"D","text":"100\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula A = \pi r^2, where r is the radius.  Substituting 5 for r, we get A = \pi (5)^2 = 25\pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_df25f94561788343_math_00951',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_b4","opensat_index":951}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people like apples, 40 people like oranges, and 20 people like both apples and oranges. How many people like only apples?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":true,"explanation":""},{"id":"B","text":"40","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":false,"explanation":""},{"id":"D","text":"80","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can use a Venn diagram to visualize the information.  Since 20 people like both apples and oranges, 60 - 20 = 40 people like only apples, and 40 - 20 = 20 people like only oranges.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_8005312cfd41b252_math_00952',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_c4","opensat_index":952}'::jsonb
  ),
(
    gen_random_uuid(),
    'A function f is defined by \(f(x) = \frac{x^2 - 4}{x + 2}\).  For what value of x does f(x) = 4?',
    'multiple_choice',
    '[{"id":"A","text":"-6","is_correct":false,"explanation":""},{"id":"B","text":"-2","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find the value of x for which f(x) = 4, we set \(\frac{x^2 - 4}{x + 2}\) equal to 4 and solve for x: \begin{aligned} \frac{x^2 - 4}{x + 2} &= 4\\ x^2 - 4 &= 4(x + 2)\\ x^2 - 4 &= 4x + 8\\ x^2 - 4x - 12 &= 0\\ (x - 6)(x + 2) &= 0\\ x &= 6, -2 \end{aligned} Since the function is undefined when x = -2, the only solution is x = 6.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_ba02ecd431f8ccbe_math_00953',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_a12","opensat_index":953}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells apples and oranges. The ratio of apples to oranges sold on a particular day was 3:5. If 120 apples were sold that day, how many oranges were sold?',
    'multiple_choice',
    '[{"id":"A","text":"80","is_correct":false,"explanation":""},{"id":"B","text":"160","is_correct":false,"explanation":""},{"id":"C","text":"200","is_correct":true,"explanation":""},{"id":"D","text":"300","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The ratio 3:5 means for every 3 apples sold, 5 oranges were sold.  We can set up a proportion: 3/5 = 120/x.  Solving for x, we get 3x = 600, and dividing both sides by 3 yields x = 200.  Therefore, 200 oranges were sold.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_28c72a376f942703_math_00954',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_8","opensat_index":954}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has legs of length 5 and 12. What is the length of the hypotenuse?',
    'multiple_choice',
    '[{"id":"A","text":"11","is_correct":false,"explanation":""},{"id":"B","text":"13","is_correct":true,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"22","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The Pythagorean theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs.  In this case, the hypotenuse squared is equal to 5 squared plus 12 squared, or 169.  The square root of 169 is 13, so the length of the hypotenuse is 13.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_b4f1bfea21c6b756_math_00955',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_15","opensat_index":955}'::jsonb
  ),
(
    gen_random_uuid(),
    'If the function $f(x) = \frac{x^2 + 3x + 2}{x + 1}$ is defined for all real numbers except for $x = -1$, what is the value of $f(2)$?',
    'multiple_choice',
    '[{"id":"A","text":"0","is_correct":false,"explanation":""},{"id":"B","text":"1","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find f(2), we substitute $x = 2$ into the function: $f(2) = \frac{2^2 + 3(2) + 2}{2 + 1}$. Simplifying, we get $f(2) = \frac{4 + 6 + 2}{3} = \frac{12}{3} = 4$. Therefore, the value of f(2) is 4.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '8a67c85f_math_00956',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"8a67c85f","opensat_index":956}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;