INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'If  $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve this system of equations using elimination. Multiplying the second equation by 3, we get $3x - 3y = 3$. Adding this equation to the first equation, we get $5x = 15$. Dividing both sides by 5, we find that $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_4017f04669e3db1f_math_00857',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_12","opensat_index":857}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 12 meters and a width of 5 meters. What is the area, in square meters, of the rectangle?',
    'multiple_choice',
    '[{"id":"A","text":"17","is_correct":false,"explanation":""},{"id":"B","text":"34","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":true,"explanation":""},{"id":"D","text":"144","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is found by multiplying its length and width. Therefore, the area of this rectangle is 12 meters * 5 meters = 60 square meters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_73876ddd2c8714f0_math_00858',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_a1","opensat_index":858}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 students found that 60 students like to play basketball and 40 students like to play soccer.  If 20 students like to play both basketball and soccer, how many students like to play only basketball?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":false,"explanation":""},{"id":"B","text":"40","is_correct":true,"explanation":""},{"id":"C","text":"60","is_correct":false,"explanation":""},{"id":"D","text":"80","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can use a Venn diagram to help visualize the problem.  Let $B$ represent the set of students who like basketball, and let $S$ represent the set of students who like soccer.  We know that $n(B) = 60$, $n(S) = 40$, and $n(B \cap S) = 20$.  The number of students who like only basketball is given by $n(B) - n(B \cap S) = 60 - 20 = 40$.  

[asy]
unitsize(0.6 cm);
label("Basketball", (2,7), E);
label("Soccer", (7,2), S);
draw(Circle((2,5), 2.5));
draw(Circle((6,1), 2.5));
draw((2,5)--(6,1));
label("20", (4,3.5));
label("40", (6,4.5), E);
label("20", (3,1), S);
[/asy]',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'f84c95a3_math_00859',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"f84c95a3","opensat_index":859}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 6x + 9 = 0$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":true,"explanation":""},{"id":"B","text":"6","is_correct":false,"explanation":""},{"id":"C","text":"9","is_correct":false,"explanation":""},{"id":"D","text":"18","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The given equation is a perfect square trinomial, which can be factored as $(x-3)^2 = 0$. Taking the square root of both sides, we get $x - 3 = 0$. Adding 3 to both sides, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '1348f21a_math_00860',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"1348f21a","opensat_index":860}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of 100 students took a test. The average score on the test was 75.  A second group of 50 students took the same test, and their average score was 85. What is the average score of all 150 students who took the test?',
    'multiple_choice',
    '[{"id":"A","text":"78","is_correct":false,"explanation":""},{"id":"B","text":"79","is_correct":false,"explanation":""},{"id":"C","text":"80","is_correct":true,"explanation":""},{"id":"D","text":"81","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The total score of the first group of students is 100 * 75 = 7500. The total score of the second group of students is 50 * 85 = 4250. The total score of all 150 students is 7500 + 4250 = 11750. Therefore, the average score of all 150 students is 11750 / 150 = 80.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_b086fd10d1619f93_math_00861',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_5","opensat_index":861}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $\frac{2x+1}{x-3} = 4$ is equivalent to which of the following equations?',
    'multiple_choice',
    '[{"id":"A","text":"$2x + 1 = 4x - 12$","is_correct":false,"explanation":""},{"id":"B","text":"$2x + 1 = 4$","is_correct":false,"explanation":""},{"id":"C","text":"$2x + 1 = 4(x - 3)$","is_correct":true,"explanation":""},{"id":"D","text":"$2x + 1 = 4x - 3$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for x, we multiply both sides of the equation by (x-3). This gives us $2x + 1 = 4(x - 3)$.  The other options are incorrect and may result from errors in distributing the 4 on the right-hand side of the equation.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_665311a3b5b94528_math_00862',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_a5","opensat_index":862}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5.  What is the circumference of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":true,"explanation":""},{"id":"C","text":"25\\pi","is_correct":false,"explanation":""},{"id":"D","text":"50\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius. In this case, $r = 5$, so the circumference is $C = 2\pi (5) = 10\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_54be56768246c728_math_00863',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_b6","opensat_index":863}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of friends are planning a trip. They decide to rent a car for \$45 per day plus a one-time insurance fee of \$20.  If the total cost of renting the car is \$145, how many days did the group rent the car?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Let''s use the variable *d* to represent the number of days the car was rented. The total cost can be represented by the equation: 45d + 20 = 145. Subtracting 20 from both sides gives 45d = 125. Dividing both sides by 45 gives d = 2.78. Since we can''t rent a car for a fraction of a day, the group rented the car for 3 days.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_dd99a7aa3b950851_math_00864',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_a9","opensat_index":864}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has legs of length 5 and 12. What is the length of the hypotenuse?',
    'multiple_choice',
    '[{"id":"A","text":"7","is_correct":false,"explanation":""},{"id":"B","text":"13","is_correct":true,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"24","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs.  Therefore, the length of the hypotenuse is $\sqrt{5^2 + 12^2} = \sqrt{169} = 13$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_319f954a30ac4ce3_math_00865',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_a9","opensat_index":865}'::jsonb
  ),
(
    gen_random_uuid(),
    'The sum of two numbers is 10, and their difference is 4. What is the value of the larger number?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"7","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Let the larger number be x and the smaller number be y. We are given that x + y = 10 and x - y = 4. Adding these two equations together eliminates y, giving us 2x = 14. Solving for x, we get x = 7. Therefore, the larger number is 7.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_b8e7affa938f3164_math_00866',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_b9","opensat_index":866}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = \frac{x^2 - 4}{x - 2}$. For what value(s) of $x$ is $f(x)$ undefined?',
    'multiple_choice',
    '[{"id":"A","text":"0","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"-2","is_correct":false,"explanation":""},{"id":"D","text":"2 and -2","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A function is undefined when the denominator of the fraction is equal to zero. In this case, the denominator is $x-2$. Solving the equation $x-2 = 0$, we find that $x = 2$. Therefore, $f(x)$ is undefined when $x = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '2c31ff5c_math_00867',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"2c31ff5c","opensat_index":867}'::jsonb
  ),
(
    gen_random_uuid(),
    'In triangle $ABC$, angle $C$ is a right angle, and $AC = BC$. What is the measure of angle $A$?',
    'multiple_choice',
    '[{"id":"A","text":"30°","is_correct":false,"explanation":""},{"id":"B","text":"45°","is_correct":true,"explanation":""},{"id":"C","text":"60°","is_correct":false,"explanation":""},{"id":"D","text":"90°","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Since $AC=BC$, triangle $ABC$ is a 45-45-90 triangle.  Therefore, the measure of angle $A$ is 45°.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_009b67088fd5e7cb_math_00868',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_a9","opensat_index":868}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells two types of cookies: chocolate chip and peanut butter. The store can sell a maximum of 100 cookies per day. On a particular day, the store sold 25 chocolate chip cookies. If the number of peanut butter cookies sold was 3 times the number of chocolate chip cookies sold, what was the number of peanut butter cookies sold that day?',
    'multiple_choice',
    '[{"id":"A","text":"30","is_correct":false,"explanation":""},{"id":"B","text":"60","is_correct":false,"explanation":""},{"id":"C","text":"75","is_correct":true,"explanation":""},{"id":"D","text":"90","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Since 25 chocolate chip cookies were sold, and the number of peanut butter cookies sold was 3 times that amount, the store sold 3 * 25 = 75 peanut butter cookies.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'f54c918d_math_00869',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"f54c918d","opensat_index":869}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangular prism has a length of 5 centimeters, a width of 4 centimeters, and a height of 3 centimeters. What is the volume, in cubic centimeters, of the prism?',
    'multiple_choice',
    '[{"id":"A","text":"12","is_correct":false,"explanation":""},{"id":"B","text":"24","is_correct":false,"explanation":""},{"id":"C","text":"36","is_correct":false,"explanation":""},{"id":"D","text":"60","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The volume of a rectangular prism is found by multiplying its length, width, and height.  So, the volume of the prism is 5 * 4 * 3 = 60 cubic centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '645fd11a_math_00870',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"645fd11a","opensat_index":870}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 5x - 6 = 0$, what is the sum of the solutions to this equation?',
    'multiple_choice',
    '[{"id":"A","text":"-5","is_correct":true,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The sum of the solutions to the quadratic equation $ax^2 + bx + c = 0$ is given by $-b/a$. In this case, $a = 1$ and $b = 5$, so the sum of the solutions is $-5/1 = -5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_77260794a90743ff_math_00871',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_6","opensat_index":871}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 2x^2 + 3x - 1. What is the value of *f*(2)?',
    'multiple_choice',
    '[{"id":"A","text":"11","is_correct":false,"explanation":""},{"id":"B","text":"15","is_correct":false,"explanation":""},{"id":"C","text":"19","is_correct":true,"explanation":""},{"id":"D","text":"23","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find *f*(2), we substitute 2 for *x* in the function: *f*(2) = 2(2)^2 + 3(2) - 1.  Simplifying, we get *f*(2) = 8 + 6 - 1, or *f*(2) = 13.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_f9ed043c304232e4_math_00872',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_a7","opensat_index":872}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the value of  $x$ if  $x^2 - 10x + 25 = 0$?',
    'multiple_choice',
    '[{"id":"A","text":"5","is_correct":true,"explanation":""},{"id":"B","text":"10","is_correct":false,"explanation":""},{"id":"C","text":"25","is_correct":false,"explanation":""},{"id":"D","text":"50","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The equation $x^2 - 10x + 25 = 0$ is a perfect square trinomial, which can be factored as $(x - 5)^2 = 0$. Taking the square root of both sides gives $x - 5 = 0$. Adding 5 to both sides gives $x = 5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '132b6748_math_00873',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"132b6748","opensat_index":873}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $\frac{2x + 3}{x - 1} = 5$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for $x$, we first multiply both sides of the equation by $x - 1$: $2x + 3 = 5(x - 1)$. Expanding the right side of the equation, we get $2x + 3 = 5x - 5$. Combining like terms, we get $8 = 3x$. Dividing both sides of the equation by 3, we get $x = \frac{8}{3}$ or $x = 2\frac{2}{3}$. Of the given choices, the closest value is 4. Therefore, the value of $x$ is 4.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '899b8d7b_math_00874',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"899b8d7b","opensat_index":874}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a radius of 5 units is inscribed in a square.  What is the area, in square units, of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square. The diameter of the circle is twice the radius, or 10 units.  The area of the square is the side length squared, so the area of the square is 10^2 = 100 square units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_f748949ec475f186_math_00875',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_d5","opensat_index":875}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5. What is the circumference of the circle?  (Express your answer in terms of \pi.)',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":true,"explanation":""},{"id":"C","text":"25\\pi","is_correct":false,"explanation":""},{"id":"D","text":"50\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula C = 2\pi r, where r is the radius.  Substituting 5 for r gives us C = 2\pi(5) = 10\pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_98b2b59387463744_math_00876',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_c6","opensat_index":876}'::jsonb
  ),
(
    gen_random_uuid(),
    'A line passes through the points $(-2, 5)$ and $(4, -3)$. What is the slope of this line?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":true,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"2","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The slope of a line passing through points $(x_1, y_1)$ and $(x_2, y_2)$ is given by the formula: $\frac{y_2 - y_1}{x_2 - x_1}$.  Substituting the given points into the formula, we get: $\frac{-3 - 5}{4 - (-2)} = \frac{-8}{6} = -\frac{4}{3}$.  Therefore, the slope of the line is $-\frac{4}{3}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'd42b6e8f_math_00877',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"d42b6e8f","opensat_index":877}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units.  What is the area of the circle in square units?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":true,"explanation":""},{"id":"D","text":"100\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula $A = \pi r^2$, where $r$ is the radius.  Substituting 5 for $r$, we get $A = \pi (5)^2 = 25\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_3f7414489623763a_math_00878',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_b8","opensat_index":878}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the solution to the equation $3x - 2 = 10 - x$?',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":false,"explanation":""},{"id":"B","text":"-2","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"3","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To solve for x, we add x to both sides of the equation: $3x - 2 + x = 10 - x + x$, which gives us $4x - 2 = 10$. Then, we add 2 to both sides: $4x - 2 + 2 = 10 + 2$, or $4x = 12$. Dividing both sides by 4, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '8b85219d_math_00879',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"8b85219d","opensat_index":879}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store is having a sale on all items, with a discount of 20%. If a customer buys an item originally priced at $150, how much will they save?',
    'multiple_choice',
    '[{"id":"A","text":"$15","is_correct":false,"explanation":""},{"id":"B","text":"$30","is_correct":true,"explanation":""},{"id":"C","text":"$60","is_correct":false,"explanation":""},{"id":"D","text":"$75","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A 20% discount on a $150 item is equivalent to 0.20 * $150 = $30.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_44b1c56aa1c6c4cc_math_00880',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_c9","opensat_index":880}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  $y = 2x + 1$ and  $x = 3$, what is the value of *y*?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"7","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substituting *x* = 3 into the equation  *y* = 2*x* + 1, we get *y* = 2(3) + 1, or *y* = 6 + 1, or *y* = 7.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'd3d44ee4_math_00881',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"d3d44ee4","opensat_index":881}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;

INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'The product of two positive integers is 48. The difference between the two integers is 2. What is the sum of the two integers?',
    'multiple_choice',
    '[{"id":"A","text":"14","is_correct":false,"explanation":""},{"id":"B","text":"16","is_correct":false,"explanation":""},{"id":"C","text":"20","is_correct":false,"explanation":""},{"id":"D","text":"26","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Let the two integers be x and y. We are given that xy = 48 and x - y = 2. Solving for x in the second equation gives us x = y + 2. Substituting y + 2 for x in the first equation gives (y + 2)y = 48, or y^2 + 2y = 48. Subtracting 48 from both sides yields y^2 + 2y - 48 = 0. Factoring this equation gives (y + 8)(y - 6) = 0, which means y = -8 or y = 6. Since the integers are positive, y must equal 6. Substituting 6 for y in the equation x = y + 2 gives us x = 6 + 2, or x = 8. Therefore, the sum of the two integers is 8 + 6 = 14.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'b587417a_math_00882',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"b587417a","opensat_index":882}'::jsonb
  ),
(
    gen_random_uuid(),
    'The expression $(x + 2)(x - 2)$ is equivalent to which of the following? ',
    'multiple_choice',
    '[{"id":"A","text":"x^2 - 4","is_correct":true,"explanation":""},{"id":"B","text":"x^2 + 4","is_correct":false,"explanation":""},{"id":"C","text":"x^2 - 2x + 4","is_correct":false,"explanation":""},{"id":"D","text":"x^2 + 2x - 4","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'This expression is a difference of squares, which follows the pattern $(a + b)(a - b) = a^2 - b^2$. In this case, $a = x$ and $b = 2$, so $(x + 2)(x - 2) = x^2 - 2^2 = x^2 - 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'a46732c5_math_00883',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"a46732c5","opensat_index":883}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells apples and oranges. The price of an apple is $\$0.75$ and the price of an orange is $\$1.25$. If a customer bought 3 apples and 5 oranges, how much did the customer spend in total?',
    'multiple_choice',
    '[{"id":"A","text":"$\\$8.25$","is_correct":false,"explanation":""},{"id":"B","text":"$\\$9.75$","is_correct":false,"explanation":""},{"id":"C","text":"$\\$10.00$","is_correct":false,"explanation":""},{"id":"D","text":"$\\$11.25$","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The cost of the apples is 3 * $0.75 = $2.25. The cost of the oranges is 5 * $1.25 = $6.25. The total cost is $2.25 + $6.25 = $8.50.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_3392ceecd1446986_math_00884',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_a1","opensat_index":884}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey asked 100 people whether they preferred dogs or cats. 60 people said they preferred dogs.  What percentage of the people surveyed preferred dogs?',
    'multiple_choice',
    '[{"id":"A","text":"30","is_correct":false,"explanation":""},{"id":"B","text":"40","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":true,"explanation":""},{"id":"D","text":"70","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find the percentage, divide the number who preferred dogs by the total number of people surveyed and multiply by 100%.  This gives  (60/100) * 100% = 60%.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_6644086d13a9d1a1_math_00885',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_1","opensat_index":885}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $\frac{x}{y} = 2$ and $\frac{y}{z} = 3$, what is the value of $\frac{x}{z}$?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{1}{6}$","is_correct":false,"explanation":""},{"id":"B","text":"$\\frac{2}{3}$","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'We can multiply the two given equations together:  $\frac{x}{y} \cdot \frac{y}{z} = 2 \cdot 3$. The y terms cancel, leaving $\frac{x}{z} = 6$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_3492d373de3b2f79_math_00886',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_d6","opensat_index":886}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units. If a chord of the circle has length 8 units, what is the distance, in units, from the center of the circle to the chord?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Draw a diagram of the circle with the chord and a radius drawn to an endpoint of the chord.  The radius will be perpendicular to the chord, dividing the chord into two equal segments.  The radius, the chord segment, and a radius drawn to the other endpoint of the chord will form a right triangle.  The hypotenuse of this triangle will be the radius of the circle, which is 5 units.  The other leg of the right triangle will be half of the chord, which is 4 units.  The Pythagorean Theorem states that the square of the hypotenuse is equal to the sum of the squares of the legs.  Therefore, the square of the distance from the center of the circle to the chord is equal to 5^2 - 4^2 = 25 - 16 = 9.  The distance from the center of the circle to the chord is the square root of 9, which is 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_1886900667182b7c_math_00887',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_1","opensat_index":887}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the value of $\frac{1}{2} + \frac{1}{4} + \frac{1}{8} + ...$ ?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":true,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"$\\frac{3}{2}$","is_correct":false,"explanation":""},{"id":"D","text":"$\\frac{5}{2}$","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'This is an infinite geometric series. The first term is $\frac{1}{2}$ and the common ratio is $\frac{1}{2}$. The sum of an infinite geometric series is given by $\frac{a}{1 - r}$, where $a$ is the first term and $r$ is the common ratio.  Therefore, the sum of this series is $\frac{\frac{1}{2}}{1 - \frac{1}{2}} = \frac{\frac{1}{2}}{\frac{1}{2}} = 1$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '89f3184c_math_00888',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"89f3184c","opensat_index":888}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 2x + 1 = 4$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"-1","is_correct":true,"explanation":""},{"id":"D","text":"-3","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The equation is a perfect square trinomial: $(x+1)^2 = 4$. Taking the square root of both sides gives $x+1 = \pm 2$.  Solving for x, we get $x = 1 \pm 2$, which means $x = 3$ or $x = -1$. The question asks for the value of x, so the answer is -1.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'f2947dd1_math_00889',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"f2947dd1","opensat_index":889}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people like apples, 50 people like oranges, and 20 people like both apples and oranges. How many people like only oranges? ',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"20","is_correct":false,"explanation":""},{"id":"C","text":"30","is_correct":true,"explanation":""},{"id":"D","text":"40","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can use a Venn diagram to visualize the problem. The number of people who like only oranges is represented by the region of the orange circle that doesn''t overlap with the apple circle. Since 20 people like both apples and oranges, and 50 people like oranges in total, then 50 – 20 = 30 people like only oranges.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_ba8c0a38f7131686_math_00890',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_a8","opensat_index":890}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a diameter of 10 centimeters. What is the area, in square centimeters, of the circle? (Use $\pi = 3.14$)',
    'multiple_choice',
    '[{"id":"A","text":"15.7","is_correct":false,"explanation":""},{"id":"B","text":"31.4","is_correct":false,"explanation":""},{"id":"C","text":"78.5","is_correct":true,"explanation":""},{"id":"D","text":"314","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula $A = \pi r^2$, where $r$ is the radius of the circle. Since the diameter is 10 centimeters, the radius is 5 centimeters.  Substituting 3.14 for $\pi$ and 5 for $r$ in the formula yields $A = 3.14 \cdot 5^2 = 3.14 \cdot 25 = 78.5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_bdb7ae2483bcbc65_math_00891',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_c3","opensat_index":891}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 2x - 15 = 0$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-5","is_correct":false,"explanation":""},{"id":"B","text":"-3","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To solve for $x$, we can factor the quadratic equation.  The factors of -15 that add up to -2 are -5 and 3.  So, the equation factors as $(x - 5)(x + 3) = 0$.  Setting each factor equal to zero, we get $x - 5 = 0$ or $x + 3 = 0$. Solving for x, we find $x = 5$ or $x = -3$.  Since the problem asks for the value of x, and 5 is a choice, x = 5 is the correct answer.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '209e74d9_math_00892',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"209e74d9","opensat_index":892}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x - 3y = 12$, what is the value of $y$ in terms of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"$y=\\frac{1}{3}x-4$","is_correct":false,"explanation":""},{"id":"B","text":"$y=x-4$","is_correct":false,"explanation":""},{"id":"C","text":"$y=\\frac{1}{3}x+4$","is_correct":false,"explanation":""},{"id":"D","text":"$y=-\\frac{1}{3}x-4$","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To solve for *y*, we can add *3y* to both sides of the equation, then subtract 12 from both sides. This gives us *3y = x - 12*. Dividing both sides by 3, we find that *y = -\frac{1}{3}x - 4*.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_bae784677c6327d3_math_00893',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_8","opensat_index":893}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = 2x^2 + 3x - 5$ is defined for all real numbers. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-15","is_correct":false,"explanation":""},{"id":"B","text":"-9","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":true,"explanation":""},{"id":"D","text":"13","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find f(-2), we substitute -2 for x in the function:  f(-2) = 2(-2)^2 + 3(-2) - 5 = 8 - 6 - 5 = 3',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'f456d12a_math_00894',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"f456d12a","opensat_index":894}'::jsonb
  ),
(
    gen_random_uuid(),
    'The expression $\frac{3x^2 - 6x}{x^2 - 4}$ is equivalent to $\frac{a}{x+2}$, where $x \neq -2$ and $x \neq 2$. What is the value of $a$?',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Factoring the numerator and denominator of the given expression yields $\frac{3x(x-2)}{(x+2)(x-2)}$. Since $x \neq 2$, the (x – 2) terms cancel, leaving $\frac{3x}{x+2}$.  Therefore, the expression is equivalent to $\frac{a}{x+2}$ when $a = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_e1009d4566014b44_math_00895',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_a7","opensat_index":895}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x + 3 = 7$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":true,"explanation":""},{"id":"B","text":"10","is_correct":false,"explanation":""},{"id":"C","text":"14","is_correct":false,"explanation":""},{"id":"D","text":"21","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Subtracting 3 from both sides of the equation, we get $x = 7 - 3$, or $x = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_906e3ee78b912eae_math_00896',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_a2","opensat_index":896}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $3x-12 = 6x+3$ is equivalent to which of the following equations?',
    'multiple_choice',
    '[{"id":"A","text":"$-3x=15$","is_correct":false,"explanation":""},{"id":"B","text":"$3x=9$","is_correct":false,"explanation":""},{"id":"C","text":"$-3x=9$","is_correct":true,"explanation":""},{"id":"D","text":"$-3x=-15$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for $x$, we can subtract $3x$ from both sides of the equation.  This gives us $-12 = 3x + 3$.  Subtracting 3 from both sides gives us $-15 = 3x$.  Dividing both sides by 3 gives us $-5 = x$.  This means $x$ must be equal to $-5$.  The only choice that gives a result of $-5$ when solved for $x$ is choice C.  Solving $-3x = 9$ for $x$ gives us $x = -3$, which is not correct.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'c789f218_math_00897',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"c789f218","opensat_index":897}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm. What is the circumference of the circle, in terms of pi?',
    'multiple_choice',
    '[{"id":"A","text":"5π","is_correct":false,"explanation":""},{"id":"B","text":"10π","is_correct":true,"explanation":""},{"id":"C","text":"25π","is_correct":false,"explanation":""},{"id":"D","text":"50π","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula C = 2πr, where r is the radius. Substituting 5 for r, we get C = 2π(5) = 10π.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_4d9acf84c24ab3ea_math_00898',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_a1","opensat_index":898}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has legs of length 5 and 12.  What is the length of the hypotenuse?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"13","is_correct":true,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"20","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs. So, if the legs are 5 and 12, the hypotenuse is $\sqrt{5^2 + 12^2} = \sqrt{169} = 13$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '1c6d5542_math_00899',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"1c6d5542","opensat_index":899}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units. A chord of the circle is 8 units long. What is the distance, in units, from the center of the circle to the chord?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":true,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Draw a diagram of the circle with the chord and the radius.  Draw a perpendicular segment from the center of the circle to the chord.  This perpendicular segment bisects the chord, forming two right triangles. The hypotenuse of each right triangle is a radius of the circle (5 units), and one leg is half the length of the chord (4 units).  Using the Pythagorean Theorem, the other leg (the distance from the center of the circle to the chord) is $\sqrt{5^2 - 4^2} = \sqrt{9} = 3$ units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'opensat_2425f72407922db2_math_00900',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math","opensat_raw_id":"random_id_c4","opensat_index":900}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for x, we can use the elimination method. Multiplying the second equation by 3, we get $3x - 3y = 3$. Adding this equation to the first equation, we get $5x = 15$. Dividing both sides by 5, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'opensat_3d85346d9ad8c2f3_math_00901',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math","opensat_raw_id":"random_id_c1","opensat_index":901}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of 100 people were surveyed about their favorite type of music. 40 people said they prefer pop music, 35 people said they prefer rock music, and the rest prefer country music. What percentage of the people surveyed prefer country music?',
    'multiple_choice',
    '[{"id":"A","text":"15%","is_correct":false,"explanation":""},{"id":"B","text":"25%","is_correct":true,"explanation":""},{"id":"C","text":"35%","is_correct":false,"explanation":""},{"id":"D","text":"40%","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'First, find the total number of people who prefer pop or rock: 40 + 35 = 75. Then, subtract that number from the total number of people surveyed to find the number who prefer country music: 100 - 75 = 25.  Finally, divide the number who prefer country music by the total number of people surveyed and multiply by 100% to find the percentage: (25 / 100) * 100% = 25%.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'c5992217_math_00902',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"c5992217","opensat_index":902}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey asked 1000 people whether they prefer to read books or watch movies. Of those surveyed, 600 people prefer to read books, and 400 people prefer to watch movies.  What percentage of the people surveyed prefer to watch movies?',
    'multiple_choice',
    '[{"id":"A","text":"40%","is_correct":true,"explanation":""},{"id":"B","text":"60%","is_correct":false,"explanation":""},{"id":"C","text":"400%","is_correct":false,"explanation":""},{"id":"D","text":"600%","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The percentage of people surveyed who prefer to watch movies can be found by dividing the number of people who prefer to watch movies by the total number of people surveyed and multiplying by 100%:  (400 / 1000) * 100% = 40%.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '545c7649_math_00903',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"545c7649","opensat_index":903}'::jsonb
  ),
(
    gen_random_uuid(),
    'For what values of $x$ is the expression \(\frac{x^2 - 9}{x^2 + 3x - 10}\) undefined?',
    'multiple_choice',
    '[{"id":"A","text":"x = 2 or x = 5","is_correct":false,"explanation":""},{"id":"B","text":"x = -5 or x = 2","is_correct":true,"explanation":""},{"id":"C","text":"x = -3 or x = 3","is_correct":false,"explanation":""},{"id":"D","text":"x = -5 or x = 3","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A rational expression is undefined when the denominator equals 0. Factoring the denominator, we get \(x^2 + 3x - 10 = (x + 5)(x - 2)\).  The denominator is equal to zero when x = -5 or x = 2.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_af6ddee124c62367_math_00904',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_8","opensat_index":904}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function f is defined by $f(x) = \frac{x^2 - 4}{x - 2}$. For what value(s) of x is the function f undefined?',
    'multiple_choice',
    '[{"id":"A","text":"x = 2","is_correct":true,"explanation":""},{"id":"B","text":"x = -2","is_correct":false,"explanation":""},{"id":"C","text":"x = 2, -2","is_correct":false,"explanation":""},{"id":"D","text":"x = 0, 2","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'A function is undefined when the denominator equals 0.  The denominator of the given function is  x - 2.  Setting x - 2 = 0 and solving for x, we get x = 2.  Therefore, the function is undefined for x = 2.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'opensat_ae3fd5d961275377_math_00905',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math","opensat_raw_id":"random_id_c9","opensat_index":905}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store is selling apples for $1.50 per pound and oranges for $2.25 per pound.  If a customer buys 3 pounds of apples and 2 pounds of oranges, how much will the customer spend in total?',
    'multiple_choice',
    '[{"id":"A","text":"$5.25","is_correct":false,"explanation":""},{"id":"B","text":"$6.75","is_correct":false,"explanation":""},{"id":"C","text":"$7.50","is_correct":false,"explanation":""},{"id":"D","text":"$9.00","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The cost of the apples is 3 pounds * $1.50/pound = $4.50.  The cost of the oranges is 2 pounds * $2.25/pound = $4.50.  The total cost is $4.50 + $4.50 = $9.00.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'opensat_bd73d7afd1ca1b29_math_00906',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math","opensat_raw_id":"random_id_a7","opensat_index":906}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;