"use client";

import { Suspense, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { ArrowLeft, Stack, BookOpen } from "@phosphor-icons/react";
import { toast } from "sonner";
import { NoteFlashcards } from "@/components/free-study/NoteFlashcards";
import {
  generateFlashcardsFromText,
  type FreeStudyFlashcard,
} from "@/lib/free-study/generateFlashcards";
import styles from "@/components/free-study/free-study-flashcards.module.css";

function FlashcardsContent() {
  const searchParams = useSearchParams();
  const initialText = searchParams.get("text") ?? "";
  const initialTitle = searchParams.get("title") ?? "";

  const [text, setText] = useState(initialText);
  const [title, setTitle] = useState(initialTitle);
  const [cards, setCards] = useState<FreeStudyFlashcard[]>([]);
  const [generating, setGenerating] = useState(false);
  const [showFlashcards, setShowFlashcards] = useState(false);

  const canGenerate = text.replace(/\s/g, "").length >= 40;

  const autoGenerated = useMemo(() => {
    if (initialText && initialText.replace(/\s/g, "").length >= 40) {
      return true;
    }
    return false;
  }, [initialText]);

  useEffect(() => {
    if (!autoGenerated || generating || showFlashcards) return;
    setGenerating(true);
    generateFlashcardsFromText({ text: initialText, count: 8 })
      .then((result) => {
        if (!result.ok) {
          toast.error(result.error);
          return;
        }
        setCards(result.data.cards);
        setShowFlashcards(true);
      })
      .catch((err) => {
        toast.error(
          err instanceof Error ? err.message : "Failed to generate flashcards",
        );
      })
      .finally(() => setGenerating(false));
  }, [autoGenerated, initialText, generating, showFlashcards]);

  const handleGenerate = useCallback(async () => {
    if (!canGenerate) return;
    setGenerating(true);
    try {
      const result = await generateFlashcardsFromText({ text, count: 8 });
      if (!result.ok) {
        toast.error(result.error);
        return;
      }
      setCards(result.data.cards);
      setShowFlashcards(true);
    } catch (err) {
      toast.error(
        err instanceof Error ? err.message : "Failed to generate flashcards",
      );
    } finally {
      setGenerating(false);
    }
  }, [text, canGenerate]);

  if (showFlashcards && cards.length > 0) {
    return (
      <NoteFlashcards
        cards={cards}
        onComplete={() => {
          toast.success("Flashcard review complete");
        }}
        onClose={() => {
          setShowFlashcards(false);
          setCards([]);
        }}
      />
    );
  }

  return (
    <div className={styles.page}>
      <Link href="/dashboard/free-study" className={styles.backLink}>
        <ArrowLeft size={14} weight="bold" aria-hidden />
        Back to Free Studying
      </Link>

      <h1 className={styles.title}>Flashcard Generator</h1>
      <p className={styles.subtitle}>
        {initialText
          ? `Generating flashcards from "${title || "your notes"}"…`
          : "Paste your study material below and we'll create flashcards to help you memorize key concepts."}
      </p>

      {initialText ? (
        <div className={styles.importedSource}>
          <BookOpen size={16} weight="fill" aria-hidden />
          <span>Imported from notes</span>
        </div>
      ) : null}

      <div className={styles.inputSection}>
        <textarea
          className={styles.textarea}
          value={text}
          onChange={(e) => {
            setText(e.target.value);
            setTitle("");
          }}
          placeholder="Paste your notes, textbook content, or study material here..."
          rows={8}
          readOnly={!!initialText}
        />
        <button
          type="button"
          className={styles.generateBtn}
          onClick={handleGenerate}
          disabled={!canGenerate || generating}
        >
          {generating ? (
            <span className={styles.loadingDots}>
              <span /><span /><span />
            </span>
          ) : (
            <>
              <Stack size={16} weight="fill" aria-hidden />
              {initialText ? "Regenerate Flashcards" : "Generate Flashcards"}
            </>
          )}
        </button>
      </div>
    </div>
  );
}

export default function FreeStudyFlashcardsPage() {
  return (
    <Suspense
      fallback={
        <div className={styles.page}>
          <div className={styles.loadingDots}>
            <span /><span /><span />
          </div>
        </div>
      }
    >
      <FlashcardsContent />
    </Suspense>
  );
}
