-- Seed 10 platform diagnostic questions for onboarding
DELETE FROM public.questions
WHERE generation_seed = 'onboarding_diagnostic_v1';

INSERT INTO public.questions (
  id,
  question_text,
  question_type,
  options,
  correct_answer,
  explanation,
  hint,
  stimulus_text,
  stimulus_type,
  section,
  topic,
  difficulty,
  exam_type,
  is_platform_question,
  generation_seed
) VALUES
(
  'd1000001-0000-4000-8000-000000000001',
  'If $3x + 7 = 22$, what is the value of $x$?',
  'multiple_choice',
  '[{"id":"A","text":"3","is_correct":false,"explanation":"Subtract 7 first."},{"id":"B","text":"5","is_correct":true,"explanation":"3x = 15, x = 5."},{"id":"C","text":"7","is_correct":false,"explanation":"Divide by 3."},{"id":"D","text":"15","is_correct":false,"explanation":"That is 3x."}]'::jsonb,
  'B',
  'Subtract 7, then divide by 3: x = 5.',
  'Isolate the x term.',
  NULL,
  NULL,
  'SAT Math',
  'Algebra',
  'medium',
  'SAT',
  true,
  'onboarding_diagnostic_v1'
),
(
  'd1000001-0000-4000-8000-000000000002',
  'A rectangle has a length of 12 and a width of 5. What is its area?',
  'multiple_choice',
  '[{"id":"A","text":"17","is_correct":false,"explanation":"That is sum."},{"id":"B","text":"34","is_correct":false,"explanation":"That is perimeter."},{"id":"C","text":"60","is_correct":true,"explanation":"12 × 5 = 60."},{"id":"D","text":"120","is_correct":false,"explanation":"Too large."}]'::jsonb,
  'C',
  'Area = length × width = 60.',
  'Multiply length by width.',
  NULL,
  NULL,
  'SAT Math',
  'Geometry',
  'medium',
  'SAT',
  true,
  'onboarding_diagnostic_v1'
),
(
  'd1000001-0000-4000-8000-000000000003',
  'Which choice best describes the main purpose of the text?',
  'multiple_choice',
  '[{"id":"A","text":"To argue reefs cannot recover","is_correct":false,"explanation":"Not argued."},{"id":"B","text":"To present findings that revise prior assumptions","is_correct":true,"explanation":"Matches the passage."},{"id":"C","text":"To compare ecosystems","is_correct":false,"explanation":"No comparison."},{"id":"D","text":"To criticize biologists","is_correct":false,"explanation":"Not critical."}]'::jsonb,
  'B',
  'The passage introduces research revising earlier models.',
  'What do the new findings do to old models?',
  'Recent studies in marine biology suggest that coral reef ecosystems respond to temperature changes more rapidly than previously documented.',
  'passage',
  'SAT Reading',
  'Main Idea',
  'medium',
  'SAT',
  true,
  'onboarding_diagnostic_v1'
),
(
  'd1000001-0000-4000-8000-000000000004',
  'As used in the text, what does ''mobility'' most nearly mean?',
  'multiple_choice',
  '[{"id":"A","text":"Ability to move through an area","is_correct":true,"explanation":"Planning context."},{"id":"B","text":"Financial flexibility","is_correct":false,"explanation":"Wrong sense."},{"id":"C","text":"Job relocation","is_correct":false,"explanation":"Wrong sense."},{"id":"D","text":"Vehicle ownership","is_correct":false,"explanation":"Wrong sense."}]'::jsonb,
  'A',
  'Mobility here means how people move through urban spaces.',
  'Think about pedestrians.',
  'Urban planners increasingly prioritize green corridors because they reduce heat islands while improving pedestrian mobility.',
  'passage',
  'SAT Reading',
  'Vocabulary',
  'medium',
  'SAT',
  true,
  'onboarding_diagnostic_v1'
),
(
  'd1000001-0000-4000-8000-000000000005',
  'Which choice completes the text with the most logical transition?',
  'multiple_choice',
  '[{"id":"A","text":"therefore","is_correct":false,"explanation":"Signals cause."},{"id":"B","text":"however","is_correct":true,"explanation":"Signals contrast."},{"id":"C","text":"similarly","is_correct":false,"explanation":"Comparison."},{"id":"D","text":"for instance","is_correct":false,"explanation":"Example."}]'::jsonb,
  'B',
  '"However" contrasts thoroughness with an omission.',
  'Look for contrast.',
  'The committee''s report was thorough; ______, it failed to address funding constraints.',
  'passage',
  'ACT English',
  'Transitions',
  'medium',
  'ACT',
  true,
  'onboarding_diagnostic_v1'
),
(
  'd1000001-0000-4000-8000-000000000006',
  'Which choice is most concise and grammatically correct?',
  'multiple_choice',
  '[{"id":"A","text":"due to the fact that","is_correct":false,"explanation":"Wordy."},{"id":"B","text":"because","is_correct":true,"explanation":"Concise."},{"id":"C","text":"on account of","is_correct":false,"explanation":"Wordy."},{"id":"D","text":"for the reason that","is_correct":false,"explanation":"Wordy."}]'::jsonb,
  'B',
  '"Because" is the most concise causal connector.',
  'Shorter is often better on ACT English.',
  NULL,
  NULL,
  'ACT English',
  'Concision',
  'medium',
  'ACT',
  true,
  'onboarding_diagnostic_v1'
),
(
  'd1000001-0000-4000-8000-000000000007',
  'What is 15% of 240?',
  'multiple_choice',
  '[{"id":"A","text":"24","is_correct":false,"explanation":"Check decimal."},{"id":"B","text":"36","is_correct":true,"explanation":"0.15 × 240 = 36."},{"id":"C","text":"48","is_correct":false,"explanation":"Too high."},{"id":"D","text":"60","is_correct":false,"explanation":"That is 25%."}]'::jsonb,
  'B',
  '15% of 240 = 36.',
  'Multiply 240 by 0.15.',
  NULL,
  NULL,
  'JAMB Math',
  'Percentages',
  'medium',
  'JAMB',
  true,
  'onboarding_diagnostic_v1'
),
(
  'd1000001-0000-4000-8000-000000000008',
  'If the ratio of boys to girls in a class is 3:2 and there are 30 students, how many are girls?',
  'multiple_choice',
  '[{"id":"A","text":"10","is_correct":false,"explanation":"Check parts."},{"id":"B","text":"12","is_correct":true,"explanation":"2/5 × 30 = 12."},{"id":"C","text":"15","is_correct":false,"explanation":"Half the class."},{"id":"D","text":"18","is_correct":false,"explanation":"That is boys."}]'::jsonb,
  'B',
  'Girls are 2 parts of 5: 12 students.',
  'Girls are 2/5 of the total.',
  NULL,
  NULL,
  'JAMB Math',
  'Ratios',
  'medium',
  'JAMB',
  true,
  'onboarding_diagnostic_v1'
),
(
  'd1000001-0000-4000-8000-000000000009',
  'What can most reasonably be inferred?',
  'multiple_choice',
  '[{"id":"A","text":"Daytime hours were reduced","is_correct":false,"explanation":"Not stated."},{"id":"B","text":"More people used the library when hours matched their schedules","is_correct":true,"explanation":"Supported by data."},{"id":"C","text":"The library closed on weekends","is_correct":false,"explanation":"Not stated."},{"id":"D","text":"Funding was cut","is_correct":false,"explanation":"Not stated."}]'::jsonb,
  'B',
  'Evening demand increased when hours expanded.',
  'Connect hours to visits.',
  'When the library extended evening hours, evening visits rose 40% while daytime visits stayed flat.',
  'passage',
  'General Reading',
  'Inference',
  'medium',
  'CUSTOM',
  true,
  'onboarding_diagnostic_v1'
),
(
  'd1000001-0000-4000-8000-000000000010',
  'Which statement is best supported by the text?',
  'multiple_choice',
  '[{"id":"A","text":"Spaced practice improved recall","is_correct":true,"explanation":"Direct evidence."},{"id":"B","text":"Cramming is always ineffective","is_correct":false,"explanation":"Too absolute."},{"id":"C","text":"All students preferred spaced practice","is_correct":false,"explanation":"Preference not given."},{"id":"D","text":"Recall did not change","is_correct":false,"explanation":"Contradicted."}]'::jsonb,
  'A',
  'The passage reports higher recall with spaced practice.',
  'Look at the percentage.',
  'The trial compared two study methods; students using spaced practice recalled 28% more terms after one week.',
  'passage',
  'General Reading',
  'Evidence',
  'medium',
  'CUSTOM',
  true,
  'onboarding_diagnostic_v1'
);
