INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'If  $x + 3 = 7$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":true,"explanation":""},{"id":"B","text":"10","is_correct":false,"explanation":""},{"id":"C","text":"14","is_correct":false,"explanation":""},{"id":"D","text":"21","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To solve for $x$, we subtract 3 from both sides of the equation: $x + 3 - 3 = 7 - 3$.  This gives us $x = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_a1',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $\frac{2x + 3}{x - 7} = 5$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-16","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"16","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To solve for $x$, we first multiply both sides of the equation by $(x - 7)$: $2x + 3 = 5(x - 7)$. Expanding the right side, we get $2x + 3 = 5x - 35$. Subtracting $2x$ from both sides, we get $3 = 3x - 35$. Adding 35 to both sides, we get $38 = 3x$. Finally, dividing both sides by 3, we get $x = \frac{38}{3} = 12\frac{2}{3}$, which is not one of the given choices. Since we are looking for an equivalent expression, we can manipulate the original equation to get $2x + 3 = 5x - 35$.  Subtracting $2x$ and adding 35 to both sides, we get $38 = 3x$.  Finally, dividing both sides by 3, we get $x = \frac{38}{3} = 12\frac{2}{3}$. Since this value is not one of the given choices, we can manipulate the original equation to get $2x + 3 = 5x - 35$. Subtracting $2x$ and adding 35 to both sides, we get $38 = 3x$.  Finally, dividing both sides by 3, we get $x = \frac{38}{3} = 12\frac{2}{3}$.  Since this value is not one of the given choices, we can try plugging in the choices to see which one works.  Plugging in 16 for $x$ gives us $\frac{2(16) + 3}{16 - 7} = \frac{35}{9}$ which simplifies to 5.  Therefore, $x = 16$ is a solution to the equation.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $\frac{2x + 3}{x - 1} = 5$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for $x$, we begin by multiplying both sides of the equation by $(x - 1)$: $2x + 3 = 5(x - 1)$. Expanding the right side gives us $2x + 3 = 5x - 5$. Subtracting $2x$ from both sides and adding 5 to both sides, we get $8 = 3x$. Dividing both sides by 3, we obtain $x = \frac{8}{3}$, or $x = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_a3',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the solution to the equation $2x-3 = 15$?',
    'multiple_choice',
    '[{"id":"A","text":"6","is_correct":false,"explanation":""},{"id":"B","text":"9","is_correct":true,"explanation":""},{"id":"C","text":"12","is_correct":false,"explanation":""},{"id":"D","text":"18","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for $x$, we add 3 to both sides of the equation: $2x - 3 + 3 = 15 + 3$. This gives us $2x = 18$. Dividing both sides by 2, we get $x = 9$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '1d6df679',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve for x by using elimination. Multiplying the second equation by 3, we get $3x - 3y = 3$.  Adding this equation to the first equation, we get $5x = 15$. Dividing both sides by 5, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a diameter of 10.  What is the area of the circle, in terms of $\pi$?',
    'multiple_choice',
    '[{"id":"A","text":"5$\\pi$","is_correct":false,"explanation":""},{"id":"B","text":"10$\\pi$","is_correct":false,"explanation":""},{"id":"C","text":"25$\\pi$","is_correct":true,"explanation":""},{"id":"D","text":"100$\\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The radius of a circle is half its diameter.  So, the radius of this circle is 5.  The area of a circle is $\pi r^2$, so the area of this circle is $\pi (5)^2 = 25\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c2',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of 10 friends are going to a concert.  They want to buy tickets in advance online, but there are only 6 tickets left.  What is the probability that all 10 friends will be able to get tickets?',
    'multiple_choice',
    '[{"id":"A","text":"0","is_correct":true,"explanation":""},{"id":"B","text":"1/10","is_correct":false,"explanation":""},{"id":"C","text":"1/6","is_correct":false,"explanation":""},{"id":"D","text":"1","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Since there are only 6 tickets left and 10 friends want tickets, it is impossible for all 10 friends to get tickets.  The probability of this event is 0.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_c3',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm. What is the circumference of the circle, in terms of $\pi$?',
    'multiple_choice',
    '[{"id":"A","text":"$5 \\pi$","is_correct":false,"explanation":""},{"id":"B","text":"$10 \\pi$","is_correct":true,"explanation":""},{"id":"C","text":"$25 \\pi$","is_correct":false,"explanation":""},{"id":"D","text":"$100 \\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2 \pi r$, where $r$ is the radius.  Substituting 5 for $r$, we get $C = 2 \pi (5) = 10 \pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x \neq 0$, what is the value of the expression $\frac{1}{x} + \frac{1}{x+1}$ expressed as a single fraction?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{1}{x(x+1)}$","is_correct":false,"explanation":""},{"id":"B","text":"$\\frac{2}{x(x+1)}$","is_correct":false,"explanation":""},{"id":"C","text":"$\\frac{2x+1}{x(x+1)}$","is_correct":true,"explanation":""},{"id":"D","text":"$\\frac{x+2}{x(x+1)}$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To add fractions, they must have a common denominator.  The least common denominator for $x$ and $x+1$ is $x(x+1)$.  Multiplying the first fraction by $\frac{x+1}{x+1}$ and the second fraction by $\frac{x}{x}$, we get: $\frac{1}{x} + \frac{1}{x+1} = \frac{1}{x} \cdot \frac{x+1}{x+1} + \frac{1}{x+1} \cdot \frac{x}{x} = \frac{x+1}{x(x+1)} + \frac{x}{x(x+1)}$.  Adding the numerators gives us $\frac{x+1 + x}{x(x+1)} = \frac{2x+1}{x(x+1)}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'd3897f3e',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a diameter of 10.  What is the circumference of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"5 \\pi","is_correct":false,"explanation":""},{"id":"B","text":"10 \\pi","is_correct":true,"explanation":""},{"id":"C","text":"25 \\pi","is_correct":false,"explanation":""},{"id":"D","text":"100 \\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula C = 2πr, where r is the radius of the circle. Since the diameter is 10, the radius is 5. Therefore, the circumference is C = 2π(5) = 10π.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '1f203579',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 4x + 3 = 0$, what is the sum of the solutions to the equation?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"7","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The sum of the roots of a quadratic equation in the form $ax^2 + bx + c = 0$ is given by $-b/a$.  In this equation, $a = 1$ and $b = -4$. Therefore, the sum of the roots is $-(-4)/1 = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_a2',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve for x by using elimination.  Multiplying the second equation by 3, we get  $3x - 3y = 3$. Adding this equation to the first equation, we get $5x = 15$.  Dividing both sides by 5, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '98d37f8d',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 6x + 9 = 0$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"0","is_correct":false,"explanation":""},{"id":"D","text":"-9","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The given equation is a perfect square trinomial. It can be factored as $(x-3)^2 = 0$. Taking the square root of both sides gives $x-3 = 0$. Adding 3 to both sides, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'b7539c69',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = 3x^2 - 5$. What is the value of $f(2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-11","is_correct":false,"explanation":""},{"id":"B","text":"-5","is_correct":false,"explanation":""},{"id":"C","text":"7","is_correct":true,"explanation":""},{"id":"D","text":"19","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find $f(2)$, we substitute 2 for $x$ in the function: $f(2) = 3(2)^2 - 5 = 3(4) - 5 = 12 - 5 = 7$. Therefore, $f(2) = 7$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_c9',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the solution to the equation $2x - 3 = 7$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":true,"explanation":""},{"id":"C","text":"7","is_correct":false,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for x, we first add 3 to both sides of the equation, which gives us $2x = 10$. Then, we divide both sides of the equation by 2, resulting in $x = 5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_c2',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the solution to the equation $2x + 5 = 17$?',
    'multiple_choice',
    '[{"id":"A","text":"-6","is_correct":false,"explanation":""},{"id":"B","text":"6","is_correct":true,"explanation":""},{"id":"C","text":"-11","is_correct":false,"explanation":""},{"id":"D","text":"11","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for x, we first subtract 5 from both sides of the equation: $2x + 5 - 5 = 17 - 5$, which simplifies to $2x = 12$.  Then we divide both sides of the equation by 2: $2x/2 = 12/2$, which gives us $x = 6$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for $x$, we can use elimination.  Multiplying the second equation by 3, we get $3x - 3y = 3$. Adding this equation to the first equation, we get $5x = 15$, so $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_a1',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people liked apples, 40 people liked oranges, and 20 people liked both apples and oranges. How many people liked neither apples nor oranges?',
    'multiple_choice',
    '[{"id":"A","text":"0","is_correct":false,"explanation":""},{"id":"B","text":"10","is_correct":false,"explanation":""},{"id":"C","text":"20","is_correct":true,"explanation":""},{"id":"D","text":"30","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can use a Venn diagram to solve this problem. Draw two overlapping circles, one for apples and one for oranges.  The overlap represents people who like both. Since 20 people liked both, we can fill in the overlap with 20. Since 60 people liked apples total, and 20 liked both, then 60-20 = 40 people liked only apples. Similarly, 40-20 = 20 people liked only oranges. This gives us a total of 40 + 20 + 20 = 80 people who liked at least one of the fruits.  Therefore, 100-80 = 20 people liked neither apples nor oranges.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '6a12b9d6',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = 2x^2 - 5x + 3$. What is the value of $f(2)$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":true,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find the value of $f(2)$, we substitute 2 for $x$ in the function: $f(2) = 2(2)^2 - 5(2) + 3$.  Simplifying the expression, we get $f(2) = 8 - 10 + 3$, or $f(2) = 5$. ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'e8923ac1',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The circumference of a circle is $12 \pi$. What is the area of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"12\\pi","is_correct":false,"explanation":""},{"id":"B","text":"36\\pi","is_correct":true,"explanation":""},{"id":"C","text":"144\\pi","is_correct":false,"explanation":""},{"id":"D","text":"144","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius of the circle.  We are given that $C = 12\pi$, so we can solve for the radius: \begin{align*} 12\pi &= 2\pi r \\ \Rightarrow \qquad 6 &= r \end{align*} The area of a circle is given by the formula $A = \pi r^2$.  Substituting 6 for $r$ gives us $A = \pi (6)^2 = 36\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c4',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x + y = 5$ and $2x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for *x*, we can add the two equations together.  This eliminates *y* and gives us $3x = 6$.  Dividing both sides by 3, we get $x = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '82101135',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a circumference of 12\pi. What is the radius of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"6","is_correct":true,"explanation":""},{"id":"C","text":"12","is_correct":false,"explanation":""},{"id":"D","text":"24","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula C = 2\pi r, where C is the circumference and r is the radius.  We are given that C = 12\pi. Substituting 12\pi for C in the formula gives 12\pi = 2\pi r.  Dividing both sides of this equation by 2\pi gives 6 = r. Therefore, the radius of the circle is 6.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '4534957f',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of friends are planning a trip. They decide to split the cost of the trip evenly.  The cost of the trip is \$1200. If there are 6 friends, how much will each friend pay?',
    'multiple_choice',
    '[{"id":"A","text":"$\\$100$","is_correct":false,"explanation":""},{"id":"B","text":"$\\$200$","is_correct":true,"explanation":""},{"id":"C","text":"$\\$300$","is_correct":false,"explanation":""},{"id":"D","text":"$\\$400$","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To find the cost per friend, divide the total cost of the trip by the number of friends: $\$1200 / 6 = \$200$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_b8',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = 2x^2 - 3x + 1$ is defined for all real numbers. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-17","is_correct":false,"explanation":""},{"id":"B","text":"-11","is_correct":false,"explanation":""},{"id":"C","text":"11","is_correct":false,"explanation":""},{"id":"D","text":"17","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substituting -2 for x in the function, we get: $f(-2) = 2(-2)^2 - 3(-2) + 1 = 8 + 6 + 1 = 15$. Therefore, the value of f(-2) is 15.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_c8',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has legs of length $12$ and $16$. What is the length of the hypotenuse of this triangle?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"20","is_correct":true,"explanation":""},{"id":"C","text":"28","is_correct":false,"explanation":""},{"id":"D","text":"40","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs.  In this case, the hypotenuse,  h, satisfies the equation $h^2 = 12^2 + 16^2 = 144 + 256 = 400$.  Therefore, the length of the hypotenuse is $h = \sqrt{400} = 20$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '2935a423',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;

INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'The average of 5 numbers is 12.  If one of the numbers is removed, the average of the remaining 4 numbers is 10. What is the value of the number that was removed? ',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"12","is_correct":false,"explanation":""},{"id":"C","text":"18","is_correct":false,"explanation":""},{"id":"D","text":"20","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The sum of the original 5 numbers is 5 * 12 = 60. The sum of the remaining 4 numbers is 4 * 10 = 40. Therefore, the number that was removed is 60 - 40 = 20.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_c5',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A function is defined by $f(x) = 2x^2 - 3x + 1$. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-17","is_correct":false,"explanation":""},{"id":"B","text":"-11","is_correct":false,"explanation":""},{"id":"C","text":"11","is_correct":false,"explanation":""},{"id":"D","text":"17","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substituting -2 for x in the function, we get: 

f(-2) = 2(-2)^2 - 3(-2) + 1

f(-2) = 2(4) + 6 + 1

f(-2) = 8 + 6 + 1

f(-2) = 15',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '37c9b215',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the solution to the equation $3x + 2 = 14$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":true,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for $x$, we subtract 2 from both sides of the equation, giving us $3x = 12$. Dividing both sides by 3, we get $x = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '9823421a',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a diameter of 10 units. What is the area of the circle? (Express your answer in terms of $\pi$.)',
    'multiple_choice',
    '[{"id":"A","text":"5$\\pi$","is_correct":false,"explanation":""},{"id":"B","text":"10$\\pi$","is_correct":false,"explanation":""},{"id":"C","text":"25$\\pi$","is_correct":true,"explanation":""},{"id":"D","text":"100$\\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula $A = \pi r^2$, where $r$ is the radius of the circle. Since the diameter is 10 units, the radius is 5 units.  Substituting 5 for $r$ in the formula yields $A = \pi (5)^2$, or $A = 25\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'd436b79a',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $x^2 - 6x + 8 = 0$ can be factored into the form $(x-a)(x-b) = 0$. What is the value of $a+b$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"6","is_correct":true,"explanation":""},{"id":"C","text":"8","is_correct":false,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To factor the quadratic, we need to find two numbers that add up to -6 (the coefficient of the x term) and multiply to 8 (the constant term). These numbers are -2 and -4. Therefore, the factored form of the equation is $(x-2)(x-4) = 0$, and $a+b = 2+4 = 6$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '74d55478',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  $3x - 2y = 12$ and $x + y = 4$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":true,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can use the elimination method to solve for x.  Multiplying the second equation by 2 gives us $2x + 2y = 8$.  Adding this equation to the first equation gives us $5x = 20$. Dividing both sides by 5 gives us $x = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_b1',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = \frac{x^2-1}{x+1}$.  What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"3","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substituting -2 for $x$ in the given function yields $f(-2) = \frac{(-2)^2 - 1}{-2 + 1}$.  Simplifying the expression gives us $f(-2) = \frac{4-1}{-1} = \frac{3}{-1} = -3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_d12',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The expression $(x + 3)^2$ is equivalent to which of the following?',
    'multiple_choice',
    '[{"id":"A","text":"x^2 + 9","is_correct":false,"explanation":""},{"id":"B","text":"x^2 + 6x + 9","is_correct":true,"explanation":""},{"id":"C","text":"x^2 + 9x + 9","is_correct":false,"explanation":""},{"id":"D","text":"x^2 + 3x + 9","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The expression $(x + 3)^2$ is equivalent to $(x + 3)(x + 3)$. Using the distributive property, we expand this to get $x^2 + 3x + 3x + 9$. Combining like terms gives us $x^2 + 6x + 9$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_12',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the value of  $\frac{3^4}{3^2}$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"9","is_correct":true,"explanation":""},{"id":"D","text":"27","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Using the rule of exponents that states $\frac{x^m}{x^n} = x^{m-n}$, we can simplify the expression as follows: $\frac{3^4}{3^2} = 3^{4-2} = 3^2 = 9$. Therefore, the value of $\frac{3^4}{3^2}$ is 9.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_c9',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $y=2x+3$ and $x=4$, what is the value of $y$?',
    'multiple_choice',
    '[{"id":"A","text":"5","is_correct":false,"explanation":""},{"id":"B","text":"11","is_correct":true,"explanation":""},{"id":"C","text":"14","is_correct":false,"explanation":""},{"id":"D","text":"17","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Substituting $x=4$ into the equation $y = 2x + 3$, we get $y = 2(4) + 3 = 8 + 3 = 11$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '11d2b54a',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If \(3x + 2y = 10\) and \(x - 2y = 6\), what is the value of \(x\)?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":true,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve this system of equations by elimination. Adding the two equations together, we get \(4x = 16\). Dividing both sides by 4, we find that \(x = 4\). ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '6835116d',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A regular hexagon has a side length of 6. What is the area of the hexagon?',
    'multiple_choice',
    '[{"id":"A","text":"54\\sqrt{3}","is_correct":true,"explanation":""},{"id":"B","text":"18\\sqrt{3}","is_correct":false,"explanation":""},{"id":"C","text":"36\\sqrt{3}","is_correct":false,"explanation":""},{"id":"D","text":"108\\sqrt{3}","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'A regular hexagon can be divided into 6 equilateral triangles.  The area of an equilateral triangle with side length s is  $\frac{\sqrt{3}}{4}s^2$, so the area of the hexagon is  $6 \cdot \frac{\sqrt{3}}{4}s^2 = \frac{3\sqrt{3}}{2}s^2$.  Substituting s = 6, we get $\frac{3\sqrt{3}}{2}(6)^2 = 54\sqrt{3}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 2x^2 + 3x - 5.  What is the value of *f*(2)?',
    'multiple_choice',
    '[{"id":"A","text":"15","is_correct":false,"explanation":""},{"id":"B","text":"19","is_correct":true,"explanation":""},{"id":"C","text":"21","is_correct":false,"explanation":""},{"id":"D","text":"25","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To find *f*(2), we substitute 2 for *x* in the function: *f*(2) = 2(2)^2 + 3(2) - 5 = 8 + 6 - 5 = 9.  Therefore, the value of *f*(2) is 9.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_11',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of friends are planning a trip. They want to rent a car that costs $40 per day plus $0.25 per mile driven. If they plan to drive 200 miles and rent the car for 3 days, what is the total cost of the car rental?',
    'multiple_choice',
    '[{"id":"A","text":"$120","is_correct":false,"explanation":""},{"id":"B","text":"$140","is_correct":false,"explanation":""},{"id":"C","text":"$160","is_correct":false,"explanation":""},{"id":"D","text":"$180","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The cost of driving 200 miles is 200 miles * $0.25/mile = $50. The cost of renting the car for 3 days is 3 days * $40/day = $120. The total cost of the rental is $50 + $120 = $170.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_a1',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function f(x) is defined as f(x) = 2x^2 + 5. What is the value of f(3)?',
    'multiple_choice',
    '[{"id":"A","text":"11","is_correct":false,"explanation":""},{"id":"B","text":"21","is_correct":false,"explanation":""},{"id":"C","text":"26","is_correct":false,"explanation":""},{"id":"D","text":"41","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find f(3), we substitute x = 3 into the function.  This gives us f(3) = 2(3)^2 + 5 = 2(9) + 5 = 18 + 5 = 23.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '90853d62',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x + 2y = 11$ and $x - y = 2$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":true,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for $x$, we can use elimination.  Multiplying the second equation by 2, we get $2x - 2y = 4$. Adding this equation to the first equation, we get $5x = 15$. Dividing both sides by 5, we find $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_11',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation  $\frac{1}{2}(x + 4) = 3$  has the same solution as which of the following equations?',
    'multiple_choice',
    '[{"id":"A","text":"$x + 4 = 6$","is_correct":true,"explanation":""},{"id":"B","text":"$x + 4 = 12$","is_correct":false,"explanation":""},{"id":"C","text":"$\\frac{1}{2}x + 2 = 3$","is_correct":false,"explanation":""},{"id":"D","text":"$\\frac{1}{2}x + 4 = 6$","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Multiplying both sides of the given equation by 2 gives $x + 4 = 6$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_a8',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a radius of 5 units is inscribed in a square. What is the area of the square, in square units?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square. Since the radius of the circle is 5 units, the diameter is 10 units. Therefore, the side length of the square is 10 units, and the area of the square is 10^2 = 100 square units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c9',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'In the figure above, lines l and m are parallel, and line t intersects lines l and m.  If the measure of angle 1 is 110 degrees, what is the measure of angle 2?',
    'multiple_choice',
    '[{"id":"A","text":"70","is_correct":true,"explanation":""},{"id":"B","text":"80","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":false,"explanation":""},{"id":"D","text":"110","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Since lines l and m are parallel, the angles 1 and 2 are alternate interior angles. Alternate interior angles have the same measure, so the measure of angle 2 is 110 degrees.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $\log_2 8 = x$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The equation $\log_2 8 = x$ asks: ''To what power must we raise 2 to get 8?''. Since $2^3 = 8$, the value of $x$ is 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_a3',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 centimeters. What is the circumference of the circle, in centimeters? (Use 3.14 for $\pi$)',
    'multiple_choice',
    '[{"id":"A","text":"15.7","is_correct":false,"explanation":""},{"id":"B","text":"31.4","is_correct":true,"explanation":""},{"id":"C","text":"78.5","is_correct":false,"explanation":""},{"id":"D","text":"157","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2 \pi r$, where $r$ is the radius.  Substituting 5 for $r$ and 3.14 for $\pi$, we get $C = 2(3.14)(5) = 31.4$ centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c5',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 centimeters.  What is the circumference of the circle, in centimeters?  (Use 3.14 for $\pi$.)',
    'multiple_choice',
    '[{"id":"A","text":"15.7","is_correct":false,"explanation":""},{"id":"B","text":"31.4","is_correct":true,"explanation":""},{"id":"C","text":"78.5","is_correct":false,"explanation":""},{"id":"D","text":"157","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius.  Substituting 5 for $r$ and 3.14 for $\pi$, we get $C = 2(3.14)(5) = 31.4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_3',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with radius $r$ is inscribed in a square.  If the area of the square is 64, what is the area of the circle in terms of $\pi$?',
    'multiple_choice',
    '[{"id":"A","text":"$4 \\pi$","is_correct":false,"explanation":""},{"id":"B","text":"$8 \\pi$","is_correct":false,"explanation":""},{"id":"C","text":"$16 \\pi$","is_correct":true,"explanation":""},{"id":"D","text":"$64 \\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Since the circle is inscribed in the square, the diameter of the circle is equal to the side length of the square.  The area of the square is 64, so the side length of the square is $\sqrt{64} = 8$.  The diameter of the circle is 8, so the radius is 4.  The area of the circle is $\pi r^2 = \pi (4)^2 = 16 \pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c8',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $2x^2 - 8x + c = 0$ has exactly one solution. What is the value of *c*?',
    'multiple_choice',
    '[{"id":"A","text":"8","is_correct":false,"explanation":""},{"id":"B","text":"16","is_correct":true,"explanation":""},{"id":"C","text":"-8","is_correct":false,"explanation":""},{"id":"D","text":"-16","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A quadratic equation has exactly one solution when its discriminant is equal to zero.  The discriminant of $ax^2 + bx + c = 0$ is $b^2 - 4ac$.  In this equation, $a = 2$, $b = -8$, and $c = c$.  Setting the discriminant equal to zero gives $(-8)^2 - 4(2)(c) = 0$, or $64 - 8c = 0$.  Solving for $c$ yields $c = 8$.  The correct answer is 8.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x + 2y = 5$ and $x - 2y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":true,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Adding the two equations together eliminates the $y$ terms and gives us $2x = 6$. Dividing both sides by 2, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_c3',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;

INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'A circle has a radius of 5.  A chord of the circle is 8 units long.  What is the distance from the center of the circle to the chord? ',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Draw a diagram of the circle and the chord.  Draw a perpendicular segment from the center of the circle to the chord.  This segment bisects the chord, creating two right triangles.  The hypotenuse of each triangle is the radius of the circle, 5, and the length of one leg is half the length of the chord, 4.  Using the Pythagorean theorem, we find the length of the other leg, which is the distance from the center of the circle to the chord: $\sqrt{5^2 - 4^2} = \sqrt{25-16} = \sqrt{9} = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_f8',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined as $f(x) = \frac{1}{x^2+1}$.  What is the value of $f(\frac{1}{2})$?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{1}{5}$","is_correct":true,"explanation":""},{"id":"B","text":"$\\frac{2}{5}$","is_correct":false,"explanation":""},{"id":"C","text":"$\\frac{4}{5}$","is_correct":false,"explanation":""},{"id":"D","text":"$\\frac{5}{4}$","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Substituting $\frac{1}{2}$ for $x$ in the equation $f(x) = \frac{1}{x^2+1}$ yields $f(\frac{1}{2}) = \frac{1}{(\frac{1}{2})^2+1}$. Simplifying the denominator gives us $f(\frac{1}{2}) = \frac{1}{\frac{1}{4}+1}$, or $f(\frac{1}{2}) = \frac{1}{\frac{5}{4}}$. Dividing 1 by $\frac{5}{4}$ is the same as multiplying by $\frac{4}{5}$, so $f(\frac{1}{2}) = \frac{4}{5}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_b9',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of 10 students took a test, and the average score on the test was 70.  If one student scored 100 on the test, what was the average score of the other 9 students? ',
    'multiple_choice',
    '[{"id":"A","text":"65","is_correct":false,"explanation":""},{"id":"B","text":"68","is_correct":true,"explanation":""},{"id":"C","text":"70","is_correct":false,"explanation":""},{"id":"D","text":"72","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The total score of all 10 students is 10 * 70 = 700. If one student scored 100, the total score of the other 9 students is 700 – 100 = 600. The average score of the other 9 students is 600 / 9 = 66.67, which rounds to 68.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_c5',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 centimeters. What is the circumference of the circle, in centimeters? (Express your answer in terms of $\pi$.)',
    'multiple_choice',
    '[{"id":"A","text":"$\\pi$","is_correct":false,"explanation":""},{"id":"B","text":"$5\\pi$","is_correct":false,"explanation":""},{"id":"C","text":"$10\\pi$","is_correct":true,"explanation":""},{"id":"D","text":"$25\\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius.  Substituting 5 for $r$ gives us $C = 2\pi (5) = 10\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_c3',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The sum of two numbers is 10.  One number is 4 less than twice the other number.  What is the value of the larger number?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Let x represent the smaller number.  The larger number is 2x - 4.  The sum of the two numbers is x + (2x - 4) = 10.  Combining like terms, we get 3x - 4 = 10.  Adding 4 to both sides, we get 3x = 14.  Dividing both sides by 3, we get x = 14/3.  The larger number is 2(14/3) - 4 = 28/3 - 4 = 16/3 = 5 1/3.  Therefore, the larger number is 6.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 2x - 15 = 0$, what are the solutions for $x$?',
    'multiple_choice',
    '[{"id":"A","text":"x = -5, x = 3","is_correct":false,"explanation":""},{"id":"B","text":"x = 5, x = -3","is_correct":true,"explanation":""},{"id":"C","text":"x = -15, x = 1","is_correct":false,"explanation":""},{"id":"D","text":"x = 15, x = -1","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for $x$, we can factor the quadratic equation: $(x + 5)(x - 3) = 0$. For this equation to equal 0, either $(x + 5) = 0$ or $(x - 3) = 0$. Solving for $x$ in each case, we get $x = -5$ or $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_b8',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm. What is the circumference of the circle? (Use $\pi = 3.14$)',
    'multiple_choice',
    '[{"id":"A","text":"15.7","is_correct":false,"explanation":""},{"id":"B","text":"31.4","is_correct":true,"explanation":""},{"id":"C","text":"62.8","is_correct":false,"explanation":""},{"id":"D","text":"157","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius.  Substituting the given values, we get $C = 2(3.14)(5) = 31.4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_2',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function f(x) is defined as $f(x) = x^2 - 3x + 2$. If the graph of y = f(x) intersects the x-axis at the points (a, 0) and (b, 0), what is the value of a + b?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The x-intercepts of the graph of y = f(x) occur where the function crosses the x-axis, which means y = 0.  So we need to find the roots of the equation f(x) = 0.  Factoring the quadratic, we get (x - 1)(x - 2) = 0.  Therefore, the roots are x = 1 and x = 2.  So, a + b = 1 + 2 = 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_a4',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $(x+2)^2 + (y-1)^2 = 4$ defines a circle in the $xy$-plane.  What is the radius of this circle?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The standard form of the equation of a circle with center $(h,k)$ and radius $r$ is $(x-h)^2 + (y-k)^2 = r^2$.  In this case, the equation of the circle is $(x+2)^2 + (y-1)^2 = 4$, which can be rewritten as $(x-(-2))^2 + (y-1)^2 = 2^2$.  Therefore, the radius of the circle is 2.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_a9',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the solution to the equation $\frac{x-3}{x+2} = 1$ ?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":false,"explanation":""},{"id":"D","text":"No solution","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Multiplying both sides of the equation by $x+2$ gives $x-3 = x+2$. Subtracting $x$ from both sides gives $-3 = 2$. This equation is false, so there is no solution to the original equation. The original equation is undefined when $x=-2$. ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_a3',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined as $f(x) = \frac{x^2 + 1}{x - 3}$. What is the value of $f(4)$?',
    'multiple_choice',
    '[{"id":"A","text":"-21","is_correct":false,"explanation":""},{"id":"B","text":"-5","is_correct":false,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"21","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find the value of f(4), we substitute 4 for x in the function''s definition: $f(4) = \frac{4^2 + 1}{4 - 3} = \frac{16 + 1}{1} = \frac{17}{1} = 17$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_15',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with center $O$ has a radius of 5.  Point $A$ lies on the circle, and the measure of angle $AOB$ is 60 degrees.  What is the length of chord $AB$?',
    'multiple_choice',
    '[{"id":"A","text":"5","is_correct":false,"explanation":""},{"id":"B","text":"10","is_correct":false,"explanation":""},{"id":"C","text":"5\\sqrt{3}","is_correct":true,"explanation":""},{"id":"D","text":"10\\sqrt{3}","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Angle $AOB$ is a central angle of the circle, so triangle $AOB$ is an equilateral triangle.  Therefore, chord $AB$ has the same length as the radius of the circle, 5.  The height of triangle $AOB$ is  $5\sqrt{3}$, and this is also the length of the altitude from point $O$ to chord $AB$, which divides chord $AB$ into two congruent segments.  Since the altitude bisects chord $AB$, the length of chord $AB$ is $2(5\sqrt{3}) = 5\sqrt{3}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '83a1729c',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 centimeters. What is the area, in square centimeters, of the circle?  (Use $\pi \approx 3.14$)',
    'multiple_choice',
    '[{"id":"A","text":"15.7","is_correct":false,"explanation":""},{"id":"B","text":"31.4","is_correct":false,"explanation":""},{"id":"C","text":"78.5","is_correct":true,"explanation":""},{"id":"D","text":"157","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula $A = \pi r^2$, where r is the radius. Substituting 5 for r and 3.14 for $\pi$, we get $A \approx 3.14 \cdot 5^2 \approx 3.14 \cdot 25 \approx 78.5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c7',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 2x - 3 = 0$, what is the value of $x^2 + 2x + 1$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":true,"explanation":""},{"id":"C","text":"7","is_correct":false,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Notice that $x^2 + 2x + 1$ is a perfect square trinomial: $(x+1)^2$. Since we know $x^2 + 2x - 3 = 0$, we can add 4 to both sides of this equation to get $x^2 + 2x + 1 = 4$. Therefore, $x^2 + 2x + 1$ is equal to 4.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '3a3f291c',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $f(x) = x^2 + 2x - 3$, what is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-7","is_correct":true,"explanation":""},{"id":"B","text":"-3","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To find the value of f(-2), we substitute -2 for x in the given function: f(-2) = (-2)^2 + 2(-2) - 3. This simplifies to 4 - 4 - 3 = -3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  \(3x+5=11\), what is the value of  \(x\)?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":true,"explanation":""},{"id":"D","text":"3","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    '1. Subtract 5 from both sides of the equation to get \(3x=6\). 2. Divide both sides by 3 to get \(x=2\). Therefore, the value of \(x\) is \(2\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '156d897b',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f$ is defined by $f(x) = \sqrt{x^2 + 1}$. What is the value of $f(\sqrt{3})$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"$\\sqrt{3}$","is_correct":false,"explanation":""},{"id":"D","text":"$\\sqrt{10}$","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Substituting $\sqrt{3}$ for $x$ in the function definition, we get $f(\sqrt{3}) = \sqrt{(\sqrt{3})^2 + 1}$. Simplifying, we have $f(\sqrt{3}) = \sqrt{3 + 1} = \sqrt{4} = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '728424a4',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x-2$ is a factor of $2x^2 + ax + b$, where $a$ and $b$ are constants, what is the value of $b$?',
    'multiple_choice',
    '[{"id":"A","text":"-8","is_correct":true,"explanation":""},{"id":"B","text":"-4","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'If $x-2$ is a factor of $2x^2 + ax + b$, then the polynomial must equal 0 when $x = 2$.  Substituting 2 for $x$ in the expression, we get $2(2)^2 + a(2) + b = 0$.  Simplifying, we have $8 + 2a + b = 0$. Since the coefficient of $x^2$ is 2, the coefficient of the constant term $b$ must also be 2 times the constant term in the factored form $(x - 2)$.  This means that $b = -8$, which is the constant term in the factored form,  $2(x-2)(x+2) = 0$.  Substituting $b = -8$ into the equation $8 + 2a + b = 0$ gives $8 + 2a - 8 = 0$, or $2a = 0$, so $a = 0$.  Therefore, the value of $b$ is -8.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'f125a218',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm. What is the circumference of the circle? (Use $\pi = 3.14$)',
    'multiple_choice',
    '[{"id":"A","text":"15.7 cm","is_correct":false,"explanation":""},{"id":"B","text":"31.4 cm","is_correct":true,"explanation":""},{"id":"C","text":"78.5 cm","is_correct":false,"explanation":""},{"id":"D","text":"157 cm","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius. Plugging in the values, we get $C = 2(3.14)(5) = 31.4$ cm.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_a4',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function f(x) is defined as $f(x) = x^2 - 3$. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-7","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"7","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find the value of $f(-2)$, we substitute -2 for $x$ in the function. This gives us  $f(-2) = (-2)^2 - 3$, or $f(-2) = 4 - 3 = 1$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '2d8c4434',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x + 4y = 17$ and $2x - 3y = 9$, what is the value of $x + y$?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"7","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To solve for $x+y$, we can add the two equations together.  Adding the left sides gives us $(3x + 4y) + (2x - 3y) = 5x + y$.  Adding the right sides gives us $17 + 9 = 26$.  Therefore, $5x + y = 26$.  Dividing both sides by 5 gives us $x + y = \frac{26}{5}$, or $x + y = 5.2$.  Since the answer must be a whole number, we round 5.2 to the nearest whole number, 5.  Therefore, $x + y = 5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'b678452b',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = \frac{1}{x} + 4$. What is the value of $f(\frac{1}{4})$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":false,"explanation":""},{"id":"D","text":"17","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find the value of $f(\frac{1}{4})$, we substitute $\frac{1}{4}$ for $x$ in the expression for $f(x)$: $f(\frac{1}{4}) = \frac{1}{\frac{1}{4}} + 4 = 4 + 4 = 17$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_8',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The area of a rectangle is $100$ square inches. If the width of the rectangle is $5$ inches, what is the length of the rectangle, in inches?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":true,"explanation":""},{"id":"B","text":"10","is_correct":false,"explanation":""},{"id":"C","text":"25","is_correct":false,"explanation":""},{"id":"D","text":"50","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The area of a rectangle is found by multiplying its length and width.  If the area is 100 square inches and the width is 5 inches, the length is 100/5 = 20 inches.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_b8',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with radius 5 is inscribed in a square. What is the area of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square.  Since the radius of the circle is 5, the diameter is 10.  Therefore, the side length of the square is 10, and the area of the square is 10² = 100.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_a2',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = \frac{x^2 - 4}{x - 2}$ is defined for all real numbers except $x = 2$. What is the value of $f(4)$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can simplify the function by factoring the numerator: $f(x) = \frac{x^2 - 4}{x - 2} = \frac{(x+2)(x-2)}{x-2}$.  Since $x \neq 2$, we can cancel the common factor of $x-2$ to get $f(x) = x + 2$. Therefore, $f(4) = 4 + 2 = 6$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '714fd53a',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;