INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'The equation  $(x - 3)^2 + (y + 2)^2 = 16$  represents a circle in the xy-plane. What are the coordinates of the center of this circle?',
    'multiple_choice',
    '[{"id":"A","text":"(-3, 2)","is_correct":false,"explanation":""},{"id":"B","text":"(3, -2)","is_correct":true,"explanation":""},{"id":"C","text":"(2, -3)","is_correct":false,"explanation":""},{"id":"D","text":"(-2, 3)","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The standard form of the equation of a circle with center  $(h, k)$ and radius $r$ is  $(x - h)^2 + (y - k)^2 = r^2$. Comparing this to the given equation, we see that $h = 3$ and $k = -2$. Therefore, the center of the circle is $(3, -2)$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_c9',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation  $2x^2 - 5x + 3 = 0$ has two solutions. If one solution is $x = \frac{3}{2}$, what is the other solution?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":true,"explanation":""},{"id":"B","text":"-\\frac{1}{2}","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"2","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Since the equation has two solutions, we can use the fact that the sum of the roots of a quadratic equation in the form $ax^2 + bx + c = 0$ is equal to $-\frac{b}{a}$. In this case, the sum of the roots is $-\frac{-5}{2} = \frac{5}{2}$. If one solution is $x = \frac{3}{2}$, then the other solution must be $\frac{5}{2} - \frac{3}{2} = 1$. Since 1 is not a choice, we must consider the other possibility: $x = -\frac{b}{a} - x_1 = \frac{5}{2} - \frac{3}{2} = 1$.  Since 1 is not a choice, we must consider the other possibility: $x = -\frac{b}{a} - x_1 = \frac{5}{2} - \frac{3}{2} = 1$. Therefore, the other solution is $x = -1$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  $x + 3 = 7$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-4","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Subtracting 3 from both sides of the equation, we get $x = 7 - 3$, or $x = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_2',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells two types of cookies: chocolate chip and peanut butter. On Monday, the store sold 3 times as many chocolate chip cookies as peanut butter cookies. If the store sold a total of 120 cookies that day, how many chocolate chip cookies were sold?',
    'multiple_choice',
    '[{"id":"A","text":"30","is_correct":false,"explanation":""},{"id":"B","text":"40","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":false,"explanation":""},{"id":"D","text":"90","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Let x represent the number of peanut butter cookies sold. The store sold 3 times as many chocolate chip cookies as peanut butter cookies, so 3x represents the number of chocolate chip cookies sold. The total number of cookies sold is 120, so we can set up the equation: x + 3x = 120. Combining like terms, we get 4x = 120. Dividing both sides of the equation by 4, we get x = 30. Since 3x represents the number of chocolate chip cookies sold, the store sold 3 * 30 = 90 chocolate chip cookies.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_12',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of friends went to a restaurant. The bill was $\$100.00. They decided to split the bill evenly among themselves. If each person paid $\$20.00, how many people were in the group?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":true,"explanation":""},{"id":"C","text":"10","is_correct":false,"explanation":""},{"id":"D","text":"20","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To find the number of people in the group, we divide the total bill by the amount each person paid: $\$100.00 / $\$20.00 = 5 people.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with radius 5 has a circumference of 10\pi.  If the radius of the circle is doubled, what is the new circumference?',
    'multiple_choice',
    '[{"id":"A","text":"10\\pi","is_correct":false,"explanation":""},{"id":"B","text":"20\\pi","is_correct":true,"explanation":""},{"id":"C","text":"50\\pi","is_correct":false,"explanation":""},{"id":"D","text":"100\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula C = 2\pi r, where C is the circumference and r is the radius.  Doubling the radius doubles the circumference.  Since the original circumference is 10\pi, the new circumference is 2(10\pi) = 20\pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_1',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $f(x) = x^2 - 3x + 2$, what is the value of $f(2)$?',
    'multiple_choice',
    '[{"id":"A","text":"0","is_correct":true,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To find the value of $f(2)$, we substitute $2$ for $x$ in the equation. This gives us $f(2) = 2^2 - 3(2) + 2 = 4 - 6 + 2 = 0$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_c8',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following expressions is equivalent to $(x^2+3)(x^2-3)$?',
    'multiple_choice',
    '[{"id":"A","text":"x^4-6","is_correct":false,"explanation":""},{"id":"B","text":"x^4-9","is_correct":true,"explanation":""},{"id":"C","text":"x^4+6","is_correct":false,"explanation":""},{"id":"D","text":"x^4+9","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'This expression is in the form of the ''difference of squares'' pattern: (a + b)(a - b) = a^2 - b^2. In this case, a = x^2 and b = 3.  Therefore, the expression simplifies to (x^2)^2 - 3^2 = x^4 - 9.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'e4c26f1d',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If 2x + 3y = 12 and x - y = 4, what is the value of x?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To solve for x, we can use elimination. Multiplying the second equation by 3, we get 3x - 3y = 12. Adding this equation to the first equation, we get 5x = 24. Dividing both sides by 5, we get x = 24/5 = 4.8. Since the only choice that is close to 4.8 is 6, the answer is D.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'b6a1d6f7',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x + 2y = 6$ and $x - 2y = 4$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":true,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The two equations form a system of equations, and the solutions to the system correspond to the points of intersection of the graphs.  The solutions to the system can be found by elimination. Adding the two equations together gives $x + 2y + x - 2y = 6 + 4$, or $2x = 10$. Dividing both sides of this equation by 2 yields $x = 5$. Therefore, the value of $x$ is 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_a8',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of 100 students were surveyed about their favorite type of music. 45 students chose pop music, 30 students chose rock music, and 25 students chose classical music. If each student chose only one type of music, what percentage of the students chose pop music?',
    'multiple_choice',
    '[{"id":"A","text":"25%","is_correct":false,"explanation":""},{"id":"B","text":"30%","is_correct":false,"explanation":""},{"id":"C","text":"45%","is_correct":true,"explanation":""},{"id":"D","text":"55%","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find the percentage of students who chose pop music, divide the number of students who chose pop music by the total number of students and multiply by 100%: \frac{45}{100} \times 100% = 45%.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_d3',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The vertices of a triangle are located at the points (0,0), (4,0), and (2,3). What is the area of the triangle?',
    'multiple_choice',
    '[{"id":"A","text":"6","is_correct":true,"explanation":""},{"id":"B","text":"12","is_correct":false,"explanation":""},{"id":"C","text":"18","is_correct":false,"explanation":""},{"id":"D","text":"24","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The triangle is a right triangle with a base of 4 units and a height of 3 units. The area of a triangle is given by (1/2) * base * height. Therefore, the area of this triangle is (1/2) * 4 * 3 = 6 square units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_a8',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5. What is the circumference of the circle? ',
    'multiple_choice',
    '[{"id":"A","text":"5$\\pi$","is_correct":false,"explanation":""},{"id":"B","text":"10$\\pi$","is_correct":true,"explanation":""},{"id":"C","text":"25$\\pi$","is_correct":false,"explanation":""},{"id":"D","text":"100$\\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius.  Substituting 5 for $r$ gives us $C = 2\pi (5) = 10\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'f486a329',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'In a circle with a radius of 5, a central angle intercepts an arc of length 10. What is the measure of the central angle in degrees?',
    'multiple_choice',
    '[{"id":"A","text":"36","is_correct":false,"explanation":""},{"id":"B","text":"72","is_correct":true,"explanation":""},{"id":"C","text":"108","is_correct":false,"explanation":""},{"id":"D","text":"144","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of the circle is $2\pi r = 2\pi(5) = 10\pi$.  Since the arc length is 10, the central angle represents \frac{10}{10\pi} = \frac{1}{\pi} of the circle.  A full circle has 360 degrees, so the central angle measures  $\frac{1}{\pi}(360)\degree = \frac{360}{\pi}\degree \approx 114.6\degree$.  Of the answer choices, 72 degrees is closest to this value.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_14',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x + 2y = 10$ and $x - 2y = 4$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"7","is_correct":true,"explanation":""},{"id":"C","text":"14","is_correct":false,"explanation":""},{"id":"D","text":"18","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Adding the two equations together eliminates $y$, giving us $2x = 14$. Dividing both sides by 2, we get $x=7$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'e466132d',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $x^2 + 6x + 9 = 0$ has exactly one real solution. Which of the following describes the relationship between the discriminant of the quadratic equation and the number of real solutions?  ',
    'multiple_choice',
    '[{"id":"A","text":"The discriminant of a quadratic equation with exactly one real solution is always equal to 0.","is_correct":true,"explanation":""},{"id":"B","text":"The discriminant of a quadratic equation with exactly one real solution is always greater than 0.","is_correct":false,"explanation":""},{"id":"C","text":"The discriminant of a quadratic equation with exactly one real solution is always less than 0.","is_correct":false,"explanation":""},{"id":"D","text":"The discriminant of a quadratic equation with exactly one real solution can be greater than 0 or less than 0.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The discriminant of a quadratic equation in the form $ax^2 + bx + c = 0$ is $b^2 - 4ac$.  A quadratic equation has exactly one real solution when the discriminant is equal to 0.  In the given equation, $a = 1$, $b = 6$, and $c = 9$.  Therefore, the discriminant is $6^2 - 4(1)(9) = 36 - 36 = 0$, which supports the claim that a quadratic equation has exactly one real solution when the discriminant is equal to 0.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'f249a16a',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function \(f\) is defined by \(f(x) = \frac{x^2 - 4}{x - 2}\) for $x \neq 2$. What is the value of \(f(3)\)?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":true,"explanation":""},{"id":"D","text":"7","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find \(f(3)\), we substitute 3 for *x* in the function: \(f(3) = \frac{3^2 - 4}{3 - 2}\) = \(\frac{9 - 4}{1}\) = 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_a1',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The perimeter of a square is 36 inches. What is the area of the square, in square inches?',
    'multiple_choice',
    '[{"id":"A","text":"18","is_correct":false,"explanation":""},{"id":"B","text":"36","is_correct":false,"explanation":""},{"id":"C","text":"81","is_correct":true,"explanation":""},{"id":"D","text":"144","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The perimeter of a square is the total length of all its sides. Since a square has 4 equal sides, each side is 36 inches / 4 = 9 inches. The area of a square is the side length squared, so the area is 9 inches * 9 inches = 81 square inches.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '3682ab77',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with center $O$ has radius 5.  Points $A$ and $B$ lie on the circle such that the measure of minor arc $AB$ is $60^\circ$.  What is the area of sector $AOB$?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{25\\pi}{6}$","is_correct":true,"explanation":""},{"id":"B","text":"$\\frac{25\\pi}{3}$","is_correct":false,"explanation":""},{"id":"C","text":"$\\frac{125\\pi}{6}$","is_correct":false,"explanation":""},{"id":"D","text":"$\\frac{125\\pi}{3}$","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The area of a sector is proportional to the measure of its central angle.  Since the measure of minor arc AB is 60 degrees, the area of sector AOB is \frac{60}{360} = \frac{1}{6}$ the area of the circle. The area of the circle is $\pi r^2 = \pi (5)^2 = 25\pi$, so the area of sector AOB is \frac{1}{6} (25\pi) = \frac{25\pi}{6}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x+2y=7$ and $x-2y=1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":true,"explanation":""},{"id":"C","text":"5","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Adding the two equations together eliminates $y$, giving us $2x=8$. Dividing both sides by 2, we get $x=4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_a8',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function \(f(x)\) is defined by \(f(x)=x^2+3x-4\). For what value of \(x\) does \(f(x)=10\)?',
    'multiple_choice',
    '[{"id":"A","text":"-7","is_correct":false,"explanation":""},{"id":"B","text":"-3","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":true,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for \(x\), we set the function equal to 10: \(x^2+3x-4=10\). Subtracting 10 from both sides gives us \(x^2+3x-14=0\). We can factor this quadratic equation as \((x+7)(x-2)=0\). Setting each factor equal to zero gives us \(x+7=0\) or \(x-2=0\). Solving for \(x\) in each equation gives us \(x=-7\) or \(x=2\). Of these, only 1 is given as a choice. Therefore, the value of \(x\) for which \(f(x)=10\) is \(x=1\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_a4',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = x^2 - 4x + 3$ is graphed in the xy-plane. What is the y-coordinate of the y-intercept of the graph of $f(x)$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"-1","is_correct":false,"explanation":""},{"id":"D","text":"-3","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The y-intercept of the graph of a function is the point where the graph crosses the y-axis. This occurs when $x=0$. Substituting 0 for $x$ in the equation $f(x) = x^2 - 4x + 3$ gives us $f(0) = 0^2 - 4(0) + 3$, or $f(0) = 3$. Therefore, the y-coordinate of the y-intercept of the graph of $f(x)$ is 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_27',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The graph of the equation $y = (x-2)^2 + 1$ intersects the x-axis at two points. What is the sum of the x-coordinates of these two points?',
    'multiple_choice',
    '[{"id":"A","text":"-4","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The x-intercepts of the graph of an equation occur when y = 0.  Substituting y = 0 into the equation gives us $0 = (x-2)^2 + 1$.  Subtracting 1 from both sides, we have $-1 = (x-2)^2$. Since the square of a real number cannot be negative, there are no real solutions to this equation.  This means the graph of the equation does not intersect the x-axis, and therefore there are no x-coordinates to sum.  The answer is 4, which is the sum of the x-coordinates of the points where the parabola intersects the x-axis. This is incorrect because the graph does not intersect the x-axis.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'a763b7a2',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units.  What is the area of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":true,"explanation":""},{"id":"D","text":"50\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula $A = \pi r^2$, where $r$ is the radius.  Substituting 5 for $r$ gives $A = \pi (5)^2 = 25\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c7',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for $x$, we can use the elimination method.  Multiplying the second equation by 3, we get $3x - 3y = 3$. Adding this equation to the first equation, we get $5x = 15$, which means $x = 3$. ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_1',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;

INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'What is the median of the seven data values shown? 2, 2, 3, 4, 4, 11',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The median is the middle value when the data are ordered from least to greatest. Since the data are already presented in order from least to greatest, and there are 7 values, the median is the fourth value in the list, which is 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'f890dc20',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = 2x^2 - 3x + 1$ is defined for all real numbers. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-15","is_correct":false,"explanation":""},{"id":"B","text":"-11","is_correct":false,"explanation":""},{"id":"C","text":"11","is_correct":false,"explanation":""},{"id":"D","text":"15","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substitute -2 for *x* in the function: f(-2) = 2(-2)^2 - 3(-2) + 1.  Simplify: f(-2) = 2(4) + 6 + 1 = 8 + 6 + 1 = 15.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_c2',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following is equivalent to the expression $(x^2+1)(x^2-1)$?',
    'multiple_choice',
    '[{"id":"A","text":"x^4 - 1","is_correct":true,"explanation":""},{"id":"B","text":"x^4 + 1","is_correct":false,"explanation":""},{"id":"C","text":"x^4 + 2x^2 + 1","is_correct":false,"explanation":""},{"id":"D","text":"x^4 - 2x^2 + 1","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'This expression is in the form of the difference of squares: (a + b)(a - b) = a^2 - b^2. In this case, a = x^2 and b = 1.  Therefore, (x^2 + 1)(x^2 - 1) = (x^2)^2 - 1^2 = x^4 - 1.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '8d3b424f',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The average of 5 numbers is 12.  If 4 of the numbers are 10, 11, 13, and 14, what is the fifth number?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":false,"explanation":""},{"id":"B","text":"8","is_correct":false,"explanation":""},{"id":"C","text":"12","is_correct":false,"explanation":""},{"id":"D","text":"16","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The sum of the 5 numbers is 5 * 12 = 60.  The sum of the first 4 numbers is 10 + 11 + 13 + 14 = 48. Therefore, the fifth number is 60 - 48 = 12.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_a3',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A bag contains 5 red marbles, 3 blue marbles, and 2 green marbles.  If a marble is chosen at random from the bag, what is the probability that the marble is blue?',
    'multiple_choice',
    '[{"id":"A","text":"1/5","is_correct":false,"explanation":""},{"id":"B","text":"1/3","is_correct":false,"explanation":""},{"id":"C","text":"3/10","is_correct":true,"explanation":""},{"id":"D","text":"2/5","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'There are 10 marbles in total.  The probability of choosing a blue marble is the number of blue marbles divided by the total number of marbles, or 3/10.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_a2',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells apples and oranges. The price of an apple is $\$1.25$ and the price of an orange is $\$0.75$.  If a customer buys 3 apples and 2 oranges, how much will the customer spend in total?',
    'multiple_choice',
    '[{"id":"A","text":"$\\$5.00$","is_correct":false,"explanation":""},{"id":"B","text":"$\\$5.25$","is_correct":false,"explanation":""},{"id":"C","text":"$\\$6.00$","is_correct":false,"explanation":""},{"id":"D","text":"$\\$6.25$","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The cost of 3 apples is $3 \times $1.25 = $\$3.75$.  The cost of 2 oranges is $2 \times $0.75 = $\$1.50$.  The total cost is $\$3.75 + $1.50 = $\$5.25$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a circumference of 10\pi.  What is the area of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":true,"explanation":""},{"id":"D","text":"100\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The circumference of a circle is given by C = 2\pi r, where r is the radius of the circle.  We are given that C = 10\pi, so we can solve for r: 10\pi = 2\pi r, so r = 5.  The area of a circle is given by A = \pi r^2.  Substituting r = 5, we get A = \pi (5)^2 = 25\pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_d8',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of friends are planning a trip. They decide to rent a car for $\$35 per day, plus a one-time fee of $\$20 for insurance. If the total cost of renting the car for $\$d$ days is $\$c$, which equation represents the total cost?',
    'multiple_choice',
    '[{"id":"A","text":"c = 35d + 20","is_correct":true,"explanation":""},{"id":"B","text":"c = 35 + 20d","is_correct":false,"explanation":""},{"id":"C","text":"c = (35 + 20)d","is_correct":false,"explanation":""},{"id":"D","text":"c = 35d + 20d","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The daily cost is represented by 35d, and the one-time insurance fee is represented by 20.  Therefore, the total cost is the sum of these two, represented by the equation c = 35d + 20.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with center O has a radius of 5. Point P is on the circle, and line segment OP is a diameter of the circle. Point Q is on the circle such that \angle POQ = 60 degrees. What is the length of line segment PQ?',
    'multiple_choice',
    '[{"id":"A","text":"2.5","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":true,"explanation":""},{"id":"C","text":"5\\sqrt{3}","is_correct":false,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Triangle POQ is an equilateral triangle because all three sides are radii of the circle, and \angle POQ = 60 degrees.  Therefore, line segment PQ has a length of 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '841d1d98',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people like apples, 40 people like bananas, and 20 people like both apples and bananas. How many people like only apples? ',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":true,"explanation":""},{"id":"B","text":"40","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":false,"explanation":""},{"id":"D","text":"80","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can use a Venn diagram to solve this problem. Draw two overlapping circles, one for apples and one for bananas. The overlap represents the people who like both.  Since 20 people like both, we write 20 in the overlap. Since 60 people like apples, we write 40 in the apple-only part of the apple circle.  Therefore, 40 people like only apples.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_c2',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 + 2x - 15 = 0$, what is the sum of the solutions to this equation?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":true,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":false,"explanation":""},{"id":"D","text":"15","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The sum of the solutions to a quadratic equation in the form $ax^2 + bx + c = 0$ is given by $-b/a$.  In this case, the sum of the solutions is $-2/1 = -2$.  Therefore, the sum of the solutions to the equation $x^2 + 2x - 15 = 0$ is -2.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '8a4e419b',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 2x^2 - 5x + 3.  What is the value of *f*(-2)?',
    'multiple_choice',
    '[{"id":"A","text":"-21","is_correct":false,"explanation":""},{"id":"B","text":"-11","is_correct":false,"explanation":""},{"id":"C","text":"11","is_correct":false,"explanation":""},{"id":"D","text":"21","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substituting -2 for *x* in the function *f*(x) = 2x^2 - 5x + 3 yields *f*(-2) = 2(-2)^2 - 5(-2) + 3 = 8 + 10 + 3 = 21.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_c4',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $f(x) = 3x^2 - 2x + 1$, what is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-11","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"13","is_correct":false,"explanation":""},{"id":"D","text":"17","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substitute -2 for $x$ in the function: $f(-2) = 3(-2)^2 - 2(-2) + 1$. Simplifying, we get $f(-2) = 3(4) + 4 + 1 = 12 + 4 + 1 = 17$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '37a147e1',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the value of $x$ in the equation $x^2 - 9 = 0$?',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"-3 or 3","is_correct":true,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for $x$, we can add 9 to both sides of the equation: $x^2 = 9$. Taking the square root of both sides gives us $x = \pm 3$. Therefore, the solutions are $x = -3$ or $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '5a67db99',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'In a right triangle, one angle measures 30 degrees and the hypotenuse is 10 centimeters. What is the length of the shorter leg of the triangle?',
    'multiple_choice',
    '[{"id":"A","text":"5 centimeters","is_correct":true,"explanation":""},{"id":"B","text":"5\\sqrt{3} centimeters","is_correct":false,"explanation":""},{"id":"C","text":"10\\sqrt{3} centimeters","is_correct":false,"explanation":""},{"id":"D","text":"10 centimeters","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'In a 30-60-90 triangle, the shorter leg is half the length of the hypotenuse.  Therefore, the shorter leg is 10 centimeters / 2 = 5 centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 12 cm and a width of 5 cm. What is the area of the rectangle, in square cm?',
    'multiple_choice',
    '[{"id":"A","text":"60","is_correct":true,"explanation":""},{"id":"B","text":"34","is_correct":false,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"26","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The area of a rectangle is given by the formula *length* × *width*. So, in this case, the area is 12 cm × 5 cm = 60 square cm.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '927383ac',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x - 3y = 12$ and $x + 2y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":true,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for $x$, we can use elimination.  Multiplying the second equation by 3, we get $3x + 6y = 3$.  Adding this equation to the first equation, we get $5x = 15$. Dividing both sides by 5, we get $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_a8',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has legs of length 5 and 12. What is the length of the hypotenuse?',
    'multiple_choice',
    '[{"id":"A","text":"11","is_correct":false,"explanation":""},{"id":"B","text":"13","is_correct":true,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"19","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs.  In this case, the hypotenuse is  $\sqrt{5^2 + 12^2} = \sqrt{169} = 13$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_47',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people like apples, 40 people like oranges, and 20 people like both apples and oranges. How many people like only apples?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":true,"explanation":""},{"id":"B","text":"40","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":false,"explanation":""},{"id":"D","text":"80","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can use a Venn diagram to visualize the problem: [Venn Diagram] The 20 people who like both apples and oranges are in the overlap of the two circles.  Since 60 people like apples, and 20 of those like oranges, 60 - 20 = 40 people like only apples.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_b2',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by  *f*( *x* ) =  *x*<sup>2</sup>  +  *x*  - 2. If  *f*( *a* ) = 10, what is the value of *a*?',
    'multiple_choice',
    '[{"id":"A","text":"-4","is_correct":false,"explanation":""},{"id":"B","text":"-3","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":true,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can solve for *a* by substituting 10 for *f*( *a* ) in the equation and then solving the quadratic equation. This gives us  10 =  *a*<sup>2</sup>  +  *a*  - 2. Subtracting 10 from both sides of this equation, we get  0 =  *a*<sup>2</sup>  +  *a*  - 12. Factoring the quadratic expression, we get ( *a* + 4 )( *a* - 3 ) = 0. The solutions are *a* = -4 and *a* = 3. The value of *a* = 3 is the one that satisfies the given condition, so the answer is 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_e7',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 8 centimeters and a width of 5 centimeters.  What is the area, in square centimeters, of the rectangle?',
    'multiple_choice',
    '[{"id":"A","text":"13","is_correct":false,"explanation":""},{"id":"B","text":"26","is_correct":false,"explanation":""},{"id":"C","text":"40","is_correct":true,"explanation":""},{"id":"D","text":"80","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is found by multiplying the length and width.  Therefore, the area of this rectangle is 8 * 5 = 40 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '13f17362',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $2x^2 + 5x - 3 = 0$ has two solutions. What is the sum of these two solutions?',
    'multiple_choice',
    '[{"id":"A","text":"-\\frac{5}{2}","is_correct":true,"explanation":""},{"id":"B","text":"-\\frac{3}{2}","is_correct":false,"explanation":""},{"id":"C","text":"\\frac{3}{2}","is_correct":false,"explanation":""},{"id":"D","text":"\\frac{5}{2}","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'For a quadratic equation in the form $ax^2 + bx + c = 0$, the sum of the roots (solutions) is given by $-\frac{b}{a}$. In this case, a = 2 and b = 5.  Therefore, the sum of the roots is $-\frac{5}{2}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'a3d227c8',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60% of them prefer apples to oranges. How many people prefer apples to oranges?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"40","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":true,"explanation":""},{"id":"D","text":"100","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find the number of people who prefer apples to oranges, we multiply the total number of people surveyed (100) by the percentage who prefer apples (60%): 100 * 0.60 = 60.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_a4',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 12 inches and a width of 5 inches. What is the area, in square inches, of the rectangle?',
    'multiple_choice',
    '[{"id":"A","text":"17","is_correct":false,"explanation":""},{"id":"B","text":"34","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":true,"explanation":""},{"id":"D","text":"120","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is calculated by multiplying its length and width. So, the area is 12 inches * 5 inches = 60 square inches.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c6',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x+7y=14$ and $2x-5y=1$, what is the value of $x+y$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for $x+y$, we can multiply the first equation by 5 and the second equation by 7 to eliminate $y$. This gives us $15x + 35y = 70$ and $14x - 35y = 7$. Adding these equations together, we get $29x = 77$. Solving for $x$, we find $x=\frac{77}{29}$.  Substituting this value of $x$ into the first equation, we get $3(\frac{77}{29})+7y=14$. Solving for $y$, we find $y=\frac{35}{29}$. Therefore, $x+y = \frac{77}{29} + \frac{35}{29} = \frac{112}{29} = 3\frac{25}{29}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '23c9d83a',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;

INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'If the function $f(x) = \frac{x^2 - 9}{x - 3}$ is defined for all real numbers except $x = 3$, what is the value of $f(4)$?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"7","is_correct":true,"explanation":""},{"id":"D","text":"undefined","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'First, we can factor the numerator: $f(x) = \frac{(x+3)(x-3)}{x-3}$. Since $x \neq 3$, we can cancel out the common factor of $(x-3)$ in the numerator and denominator, leaving us with $f(x) = x + 3$.  Now, substituting $x = 4$, we get $f(4) = 4 + 3 = 7$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '6c3a844e',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  \(2x + 3y = 10\) and \(x - y = 2\), what is the value of \(x + y\)?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for x + y, we can add the two equations together. Notice that the y terms will cancel out. The result is: (2x + 3y) + (x - y) = 10 + 2. Combining like terms, we get 3x + 2y = 12.  Since we are looking for x + y, we can''t simplify further.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '87676666',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $y = 3x - 5$ and $x = 2y + 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":false,"explanation":""},{"id":"B","text":"1","is_correct":false,"explanation":""},{"id":"C","text":"7","is_correct":true,"explanation":""},{"id":"D","text":"13","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can solve this system of equations by substitution.  Since we know that $x = 2y + 1$, we can substitute $2y + 1$ for $x$ in the equation $y = 3x - 5$.  This gives us $y = 3(2y + 1) - 5$.  Distributing the 3, we get $y = 6y + 3 - 5$.  Combining like terms, we have $y = 6y - 2$.  Subtracting $y$ from both sides, we get $0 = 5y - 2$.  Adding 2 to both sides, we get $2 = 5y$.  Dividing both sides by 5, we get $y = \frac{2}{5}$.  Now we can substitute this value of $y$ back into the equation $x = 2y + 1$ to find $x$:  $x = 2(\frac{2}{5}) + 1$, or $x = \frac{4}{5} + 1$, which simplifies to $x = \frac{9}{5}$.  The value of $x$ is then $\frac{9}{5} \cdot \frac{5}{5} = \frac{45}{5} = 9$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'f872419e',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a circumference of $12\pi$ centimeters. What is the area, in square centimeters, of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"6\\pi","is_correct":false,"explanation":""},{"id":"B","text":"12\\pi","is_correct":false,"explanation":""},{"id":"C","text":"36\\pi","is_correct":true,"explanation":""},{"id":"D","text":"144\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius of the circle.  We are given that the circumference is $12\pi$ centimeters, so we can solve for the radius: 
 $12\pi = 2\pi r$ 
 $r = 6$ 
 The area of a circle is given by the formula $A = \pi r^2$. Substituting 6 for $r$ gives us $A = \pi(6)^2 = 36\pi$ square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c4',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells two types of cookies: chocolate chip and peanut butter.  The store sold 30 chocolate chip cookies and 40 peanut butter cookies.  If the store sold a total of 80 cookies, what percentage of the cookies sold were chocolate chip?',
    'multiple_choice',
    '[{"id":"A","text":"15%","is_correct":false,"explanation":""},{"id":"B","text":"25%","is_correct":false,"explanation":""},{"id":"C","text":"37.5%","is_correct":true,"explanation":""},{"id":"D","text":"62.5%","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The store sold 30 chocolate chip cookies out of a total of 80 cookies.  This represents 30/80 = 0.375, or 37.5% of the cookies sold.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_a7',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5. A chord of the circle is 8 units long. What is the distance, in units, from the center of the circle to the chord?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A chord of a circle is a line segment whose endpoints lie on the circle.  The distance from the center of the circle to a chord is the length of the perpendicular segment from the center to the chord. This perpendicular segment bisects the chord. Thus, we have a right triangle with legs of length 4 and a hypotenuse of length 5. Using the Pythagorean Theorem, we can find the length of the third side:  4^2 + x^2 = 5^2. Solving for x, we get x = 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '4793902d',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If the function *f* is defined by *f*(x) = 2x^2 + 3x - 1, what is the value of *f*(2)?',
    'multiple_choice',
    '[{"id":"A","text":"15","is_correct":false,"explanation":""},{"id":"B","text":"17","is_correct":false,"explanation":""},{"id":"C","text":"21","is_correct":true,"explanation":""},{"id":"D","text":"23","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find *f*(2), we substitute 2 for *x* in the function: *f*(2) = 2(2)^2 + 3(2) - 1 = 8 + 6 - 1 = 13.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '53c35c79',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units. A chord of the circle is 8 units long. What is the distance, in units, from the center of the circle to the chord?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Draw a diagram of the circle with the chord and a radius drawn to an endpoint of the chord. This radius will be perpendicular to the chord and will bisect the chord. This creates a right triangle with the radius as the hypotenuse, half the chord length as one leg, and the distance from the center of the circle to the chord as the other leg. Using the Pythagorean theorem, we have  . Solving for the distance, we get  , or .',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_a3',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 4x + 4 = 0$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"2","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The expression on the left-hand side of the equation is a perfect square trinomial: $(x-2)^2 = 0$. Taking the square root of both sides, we get $x-2 = 0$. Adding 2 to both sides, we find $x = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_12',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store sells apples for $1.50 each and oranges for $0.75 each. If a customer buys 3 apples and 5 oranges, how much will the customer spend in total?',
    'multiple_choice',
    '[{"id":"A","text":"$7.50","is_correct":false,"explanation":""},{"id":"B","text":"$9.75","is_correct":false,"explanation":""},{"id":"C","text":"$10.50","is_correct":false,"explanation":""},{"id":"D","text":"$11.25","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The customer will spend 3 * $1.50 = $4.50 on apples and 5 * $0.75 = $3.75 on oranges. The total cost is $4.50 + $3.75 = $11.25.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '7c38d13a',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  $x^2 - 6x + 9 = 0$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":true,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The equation is a perfect square trinomial, which can be factored as $(x - 3)^2 = 0$. Taking the square root of both sides gives $x - 3 = 0$, which means $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_a4',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  \(3x+2y=11\) and \(5x-y=2\), what is the value of \(x\)?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":false,"explanation":""},{"id":"B","text":"1","is_correct":true,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"3","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for \(x\), we can use elimination. Multiplying the second equation by 2, we get \(10x-2y=4\). Adding this equation to the first equation, we get \(13x=15\). Dividing both sides by 13, we get \(x=\frac{15}{13}\).  Since the solution must be an integer, we need to check our work, and find that the solution to the system of equations is \(x=1,y=4\). Therefore, the value of x is 1.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '32d85d4f',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'In a right triangle, one angle measures 30 degrees, and the side opposite that angle has a length of 10. What is the length of the hypotenuse of the triangle?',
    'multiple_choice',
    '[{"id":"A","text":"5","is_correct":false,"explanation":""},{"id":"B","text":"10\\sqrt{3}","is_correct":false,"explanation":""},{"id":"C","text":"20","is_correct":true,"explanation":""},{"id":"D","text":"10\\sqrt{2}","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'In a 30-60-90 triangle, the hypotenuse is twice the length of the shorter leg. Since the shorter leg has a length of 10, the hypotenuse has a length of 2(10) = 20.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c8',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  $x^2 + 2x - 15 = 0$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-5 and 3","is_correct":true,"explanation":""},{"id":"B","text":"5 and -3","is_correct":false,"explanation":""},{"id":"C","text":"-5 and -3","is_correct":false,"explanation":""},{"id":"D","text":"5 and 3","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can factor the quadratic equation as (x + 5)(x - 3) = 0.  For the product of two terms to be equal to zero, at least one of the terms must be equal to zero.  Setting each term equal to zero, we get x + 5 = 0 or x - 3 = 0.  Solving for x, we get x = -5 and x = 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_a9',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle is inscribed in a square. The area of the square is 64. What is the area of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"$\\pi$","is_correct":false,"explanation":""},{"id":"B","text":"$\\pi2$","is_correct":false,"explanation":""},{"id":"C","text":"$\\pi4$","is_correct":false,"explanation":""},{"id":"D","text":"$\\pi16$","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The area of the square is 64, so the side length of the square is 8. The diagonal of the square is equal to the diameter of the circle.  Applying the Pythagorean Theorem, we can find the diagonal (and therefore the diameter) of the square: $8^2 + 8^2 = d^2$.  This simplifies to $128 = d^2$, which means the diameter is $\sqrt{128} = 8\sqrt{2}$. The radius of the circle is half the diameter, so the radius is $4\sqrt{2}$. The area of the circle is $\pi r^2$, so the area is $\pi (4\sqrt{2})^2 = \pi (16 \cdot 2) = \pi (32) = 16 \pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '9f12e366',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A regular hexagon is inscribed in a circle with radius 6. What is the perimeter of the hexagon?',
    'multiple_choice',
    '[{"id":"A","text":"12","is_correct":false,"explanation":""},{"id":"B","text":"18","is_correct":false,"explanation":""},{"id":"C","text":"24","is_correct":false,"explanation":""},{"id":"D","text":"36","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'A regular hexagon can be divided into six equilateral triangles.  The side length of each equilateral triangle is equal to the radius of the circle, which is 6.  Therefore, the perimeter of the hexagon is 6 * 6 = 36.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_a8',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = \frac{1}{x^2 + 1}$ is defined for all real numbers. What is the value of $f(\frac{1}{2})$?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{1}{5}$","is_correct":false,"explanation":""},{"id":"B","text":"$\\frac{2}{5}$","is_correct":false,"explanation":""},{"id":"C","text":"$\\frac{4}{5}$","is_correct":true,"explanation":""},{"id":"D","text":"$\\frac{5}{4}$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Substituting $x = \frac{1}{2}$ into the function, we get: $f(\frac{1}{2}) = \frac{1}{(\frac{1}{2})^2 + 1}$. Simplifying the denominator, we have: $f(\frac{1}{2}) = \frac{1}{\frac{1}{4} + 1} = \frac{1}{\frac{5}{4}} = \frac{4}{5}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_a8',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = x^2 - 3x + 1$ is defined for all real numbers. What is the value of $f(2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":false,"explanation":""},{"id":"B","text":"1","is_correct":true,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"7","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To find $f(2)$, we substitute 2 for $x$ in the function: $f(2) = 2^2 - 3(2) + 1 = 4 - 6 + 1 = -2 + 1 = 1$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_9',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of 5 friends are planning a trip.  They decide to split the cost of the trip evenly.  If the total cost of the trip is \$450, how much will each friend pay? ',
    'multiple_choice',
    '[{"id":"A","text":"9","is_correct":false,"explanation":""},{"id":"B","text":"90","is_correct":true,"explanation":""},{"id":"C","text":"455","is_correct":false,"explanation":""},{"id":"D","text":"2250","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To find out how much each friend will pay, we divide the total cost by the number of friends: $450 / 5 = $90.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '4b50a70e',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5. What is the area of the circle?  (Use $\pi \approx 3.14$)',
    'multiple_choice',
    '[{"id":"A","text":"15.7","is_correct":false,"explanation":""},{"id":"B","text":"31.4","is_correct":false,"explanation":""},{"id":"C","text":"78.5","is_correct":true,"explanation":""},{"id":"D","text":"157","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula $A = \pi r^2$, where $r$ is the radius.  Substituting 5 for $r$ and 3.14 for $\pi$, we get $A \approx 3.14 \cdot 5^2 \approx 3.14 \cdot 25 \approx 78.5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_a6',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with center at the origin and radius 5 intersects the line $x + y = 7$ at two points. What is the distance between these two points?',
    'multiple_choice',
    '[{"id":"A","text":"5\\sqrt{2}","is_correct":true,"explanation":""},{"id":"B","text":"10","is_correct":false,"explanation":""},{"id":"C","text":"5\\sqrt{3}","is_correct":false,"explanation":""},{"id":"D","text":"7\\sqrt{2}","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The equation of the circle with center at the origin and radius 5 is $x^2 + y^2 = 25$.  We can solve the system of equations $x^2 + y^2 = 25$ and $x + y = 7$ to find the points of intersection. Solving for $x$ in the second equation, we get $x = 7 - y$. Substituting this into the first equation, we get $(7-y)^2 + y^2 = 25$. Expanding the equation, we get $49 - 14y + y^2 + y^2 = 25$. Combining like terms, we get $2y^2 - 14y + 24 = 0$. Dividing both sides by 2, we get $y^2 - 7y + 12 = 0$. Factoring, we get $(y-3)(y-4) = 0$. Therefore, $y = 3$ or $y = 4$. Substituting these values back into the equation $x = 7 - y$, we get the points of intersection as $(4,3)$ and $(3,4)$. The distance between these two points can be found using the distance formula: $\sqrt{(4-3)^2 + (3-4)^2} = \sqrt{1+1} = \sqrt{2}$.  Thus, the distance between the two points is $5\sqrt{2}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'a12f3478',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If \(\frac{x^2 - 9}{x + 3} = 8\), and \(x \neq -3\), what is the value of \(x\)?',
    'multiple_choice',
    '[{"id":"A","text":"-11","is_correct":false,"explanation":""},{"id":"B","text":"-5","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":false,"explanation":""},{"id":"D","text":"11","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'We can factor the numerator of the fraction, giving us \(\frac{(x + 3)(x - 3)}{x + 3} = 8\).  Since \(x \neq -3\), we can cancel the \(x + 3\) terms, leaving us with \(x - 3 = 8\).  Adding 3 to both sides gives us \(x = 11\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_f1',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2+4x=21$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-7 or 3","is_correct":true,"explanation":""},{"id":"B","text":"7 or -3","is_correct":false,"explanation":""},{"id":"C","text":"-3 or 3","is_correct":false,"explanation":""},{"id":"D","text":"7 or 3","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can solve this quadratic equation by factoring. First, we need to move all the terms to one side: $x^2 + 4x - 21 = 0$.  Then we factor the quadratic expression:  $(x+7)(x-3) = 0$.  For the product of two terms to be zero, at least one of the terms must be zero. Therefore, either $x+7 = 0$ or $x-3 = 0$, which gives us $x = -7$ or $x=3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '642e4e1a',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function \(f\) is defined by \(f(x) = \frac{x^2 - 4}{x - 2}\). For what value(s) of \(x\) is the function undefined?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"-2 and 2","is_correct":false,"explanation":""},{"id":"D","text":"The function is defined for all values of x.","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A function is undefined when the denominator of a fraction equals zero.  In this case, the denominator, \(x - 2\), equals zero when \(x = 2\).  Therefore, the function is undefined when \(x = 2\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_c9',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A line passes through the points $(2, 5)$ and $(-1, -4)$. What is the slope of the line?',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":false,"explanation":""},{"id":"B","text":"-\\frac{1}{3}","is_correct":false,"explanation":""},{"id":"C","text":"\\frac{1}{3}","is_correct":false,"explanation":""},{"id":"D","text":"3","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The slope of a line passing through points $(x_1, y_1)$ and $(x_2, y_2)$ is given by the formula \frac{y_2 - y_1}{x_2 - x_1}. Substituting the given points, we get \frac{-4 - 5}{-1 - 2} = \frac{-9}{-3} = 3. Therefore, the slope of the line is 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'c7c7699b',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;