INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'If $\frac{x}{y} = 3$ and $\frac{y}{z} = 2$, what is the value of $\frac{x}{z}$?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{1}{6}$","is_correct":false,"explanation":""},{"id":"B","text":"$\\frac{3}{2}$","is_correct":false,"explanation":""},{"id":"C","text":"$\\frac{5}{3}$","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'We can multiply the two given equations together: $\frac{x}{y} \cdot \frac{y}{z} = 3 \cdot 2$. The $y$ terms cancel, leaving us with $\frac{x}{z} = 6$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_a8',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If \(\frac{x^2 - 4}{x - 2}\) is simplified to a single term, what is the value of this term when \(x = 5\)?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"6","is_correct":true,"explanation":""},{"id":"C","text":"7","is_correct":false,"explanation":""},{"id":"D","text":"11","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can simplify the expression by factoring the numerator and canceling common factors: \(\frac{x^2 - 4}{x - 2} = \frac{(x + 2)(x - 2)}{x - 2} = x + 2\).  When \(x = 5\), this expression evaluates to \(5 + 2 = 7\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_b6',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the solution to the equation $3x + 5 = 17$?',
    'multiple_choice',
    '[{"id":"A","text":"-4","is_correct":false,"explanation":""},{"id":"B","text":"-2","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To solve for $x$, we first subtract 5 from both sides of the equation: $3x + 5 - 5 = 17 - 5$, or $3x = 12$. Next, we divide both sides by 3: $\frac{3x}{3} = \frac{12}{3}$, or $x = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_a7',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5. What is the circumference of the circle? ',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":true,"explanation":""},{"id":"C","text":"25\\pi","is_correct":false,"explanation":""},{"id":"D","text":"50\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula C = 2πr, where r is the radius.  Substituting 5 for r gives us C = 2π(5), or C = 10π.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c2',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 3x^2 - 5x + 2.  What is the value of *f*(-2) ?',
    'multiple_choice',
    '[{"id":"A","text":"-20","is_correct":false,"explanation":""},{"id":"B","text":"-8","is_correct":false,"explanation":""},{"id":"C","text":"12","is_correct":false,"explanation":""},{"id":"D","text":"24","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substituting -2 for *x* in the equation for *f* gives: *f*(-2) = 3(-2)^2 - 5(-2) + 2.  Simplifying, we get *f*(-2) = 12 + 10 + 2 = 24.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '243b498c',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $f(x) = 2x^2 + 3x - 1$, what is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-9","is_correct":true,"explanation":""},{"id":"B","text":"-3","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Substituting -2 for x in the expression for f(x) gives:  

 f(-2) = 2(-2)^2 + 3(-2) - 1 = 2(4) - 6 - 1 = 8 - 6 - 1 = -9',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_c4',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by  *f*(x) = 3x^2 - 5x + 2. What is the value of *f*(2)?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":true,"explanation":""},{"id":"B","text":"6","is_correct":false,"explanation":""},{"id":"C","text":"8","is_correct":false,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To find *f*(2), we substitute 2 for *x* in the function: *f*(2) = 3(2)^2 - 5(2) + 2 = 12 - 10 + 2 = 4.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_10',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people like apples, 40 people like oranges, and 20 people like both apples and oranges. How many people like only oranges?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":true,"explanation":""},{"id":"B","text":"20","is_correct":false,"explanation":""},{"id":"C","text":"30","is_correct":false,"explanation":""},{"id":"D","text":"40","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can use a Venn diagram to solve this problem.  
[asy]
unitsize(0.6cm);
label("Apples",(3,5));
label("Oranges",(7,5));
filldraw(Circle((4,3),1),gray(0.7));
filldraw(Circle((6,3),1),gray(0.7));
label("20",(5,3));
label("40",(7,3));
label("60",(3,3));
[/asy]
Since 20 people like both apples and oranges, 60 - 20 = 40 people like only apples, and 40 - 20 = 20 people like only oranges. Therefore, the answer is 10.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '3894c42a',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 2x - 8 = 0$, what is the sum of the solutions to the equation?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"8","is_correct":false,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The sum of the roots of a quadratic equation of the form $ax^2 + bx + c = 0$ is given by $-b/a$. In this case, the sum of the solutions is $-(-2)/1 = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '61b8480a',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *g* is defined by *g*(x) = 10x + 8. What is the value of *g*(x) when x = 8?',
    'multiple_choice',
    '[{"id":"A","text":"0","is_correct":false,"explanation":""},{"id":"B","text":"8","is_correct":false,"explanation":""},{"id":"C","text":"10","is_correct":false,"explanation":""},{"id":"D","text":"88","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find the value of *g*(x) when x = 8, we substitute 8 for x in the given equation *g*(x) = 10x + 8. This yields *g*(8) = 10(8) + 8, or *g*(8) = 88. Therefore, when x = 8, the value of *g*(x) is 88.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '173a5c22',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people prefer to eat breakfast, 40 people prefer to eat lunch, and 20 people prefer to eat dinner. If a person is chosen at random from the survey, what is the probability that the person prefers to eat breakfast? ',
    'multiple_choice',
    '[{"id":"A","text":"0.2","is_correct":false,"explanation":""},{"id":"B","text":"0.4","is_correct":false,"explanation":""},{"id":"C","text":"0.6","is_correct":true,"explanation":""},{"id":"D","text":"0.8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The probability of an event is the number of favorable outcomes divided by the total number of outcomes. In this case, there are 60 people who prefer to eat breakfast out of a total of 100 people. Therefore, the probability that a randomly chosen person prefers to eat breakfast is 60/100, or 0.6.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_a9',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If \(3x - 2y = 10\) and \(x + 2y = 6\), what is the value of \(x\)?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Adding the two equations together, we eliminate \(y\): \(3x - 2y + (x + 2y) = 10 + 6\). This simplifies to \(4x = 16\). Dividing both sides by 4 gives us \(x = 4\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the value of $x$ in the equation $2^{x+1} = 8$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Since 8 is equal to 2 cubed (2 x 2 x 2 = 8), we can rewrite the equation as  2^(x + 1) = 2^3.  Since the bases are the same, the exponents must be equal:  x + 1 = 3.  Subtracting 1 from both sides gives x = 2.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'a8e9d4f2',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'In the figure below, $\triangle ABC$ is a right triangle with right angle at $C$. If $AC=4$ and $BC=3$, what is the length of $AB$?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":true,"explanation":""},{"id":"C","text":"7","is_correct":false,"explanation":""},{"id":"D","text":"25","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Since $\triangle ABC$ is a right triangle, we can use the Pythagorean Theorem to find the length of the hypotenuse, $AB$. The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the other two sides.  Therefore, $AB^2 = AC^2 + BC^2 = 4^2 + 3^2 = 16 + 9 = 25$. Taking the square root of both sides, we find $AB = \sqrt{25} = 5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '21f24749',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 students found that 60 students prefer to watch movies at home, 45 students prefer to watch movies at the theater, and 10 students prefer to watch movies at both home and the theater. What is the number of students who prefer to watch movies only at home?',
    'multiple_choice',
    '[{"id":"A","text":"15","is_correct":false,"explanation":""},{"id":"B","text":"25","is_correct":false,"explanation":""},{"id":"C","text":"50","is_correct":true,"explanation":""},{"id":"D","text":"60","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The 10 students who prefer to watch movies at both home and the theater are counted twice in the total, once for home and once for the theater. To find the number of students who prefer to watch movies only at home, we subtract the number of students who prefer both from the total number of students who prefer to watch movies at home: 60 - 10 = 50.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_1',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If 3x + 2y = 17 and x - y = 2, what is the value of x + y?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":true,"explanation":""},{"id":"C","text":"7","is_correct":false,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for x + y, we can use elimination. Multiplying the second equation by 2, we get 2x - 2y = 4. Adding this equation to the first equation, we get (3x + 2y) + (2x - 2y) = 17 + 4, which simplifies to 5x = 21. Dividing both sides by 5, we get x = 4.2. Substituting 4.2 for x in the equation x - y = 2, we get 4.2 - y = 2. Subtracting 4.2 from both sides gives -y = -2.2, or y = 2.2. Therefore, x + y = 4.2 + 2.2 = 6.4, which is closest to 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_c3',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'In triangle ABC, angle A is a right angle, and the lengths of sides AC and BC are 6 and 8, respectively.  What is the length of side AB?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"10","is_correct":true,"explanation":""},{"id":"C","text":"$\\sqrt{10}$","is_correct":false,"explanation":""},{"id":"D","text":"$\\sqrt{100}$","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Triangle ABC is a right triangle, so we can use the Pythagorean Theorem: $a^2 + b^2 = c^2$, where a and b are the lengths of the legs and c is the length of the hypotenuse.  In this case, AC = 6 and BC = 8, so  $6^2 + 8^2 = c^2$. Simplifying, we get $36 + 64 = c^2$, or $100 = c^2$.  Taking the square root of both sides, we get $c = \sqrt{100}$, or $c = 10$. Therefore, the length of side AB is 10.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c8',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x + y = 7$ and $x - y = 3$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":true,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for x, we can add the two equations together. Notice that the y terms will cancel out.  (x + y) + (x - y) = 7 + 3.  This simplifies to 2x = 10. Dividing both sides by 2 gives x = 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_d4',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the value of $\frac{x^2 + 6x + 9}{x+3}$ when $x = 2$?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":false,"explanation":""},{"id":"B","text":"1","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'First, factor the numerator: $\frac{x^2 + 6x + 9}{x+3} = \frac{(x+3)(x+3)}{x+3}$. Then, simplify by canceling out the common factor of $x+3$: $\frac{(x+3)(x+3)}{x+3} = x+3$.  Finally, substitute $x = 2$ into the expression: $2 + 3 = 5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'a214b1b9',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of 200 people were surveyed about their favorite type of music. 120 people said they prefer pop music, 80 people said they prefer classical music, and 50 people said they prefer jazz music. What percentage of the people surveyed prefer jazz music?',
    'multiple_choice',
    '[{"id":"A","text":"15%","is_correct":false,"explanation":""},{"id":"B","text":"20%","is_correct":false,"explanation":""},{"id":"C","text":"25%","is_correct":true,"explanation":""},{"id":"D","text":"40%","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The percentage of people who prefer jazz music is calculated by dividing the number of people who prefer jazz music by the total number of people surveyed and then multiplying by 100%.  So, the percentage of people who prefer jazz music is (50/200) * 100% = 25%.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_b8',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If \(3x + 2y = 10\) and \(x - y = 1\), what is the value of \(x + y\)?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":true,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for \(x + y\), we can add the two equations together. Adding the left-hand side of the first equation and the left-hand side of the second equation yields \(3x + 2y + (x - y) = 4x + y\). Adding the right-hand sides of the two equations yields \(10 + 1 = 11\). Thus, \(4x + y = 11\).  We can rewrite the first equation as \(x = \frac{10 - 2y}{3}\). Substituting this into the equation \(4x + y = 11\) gives \(4(\frac{10 - 2y}{3}) + y = 11\). Simplifying, we have \(\frac{40 - 8y}{3} + y = 11\), or \(\frac{40 - 8y + 3y}{3} = 11\), or \(\frac{40 - 5y}{3} = 11\).  Multiplying both sides by 3 gives \(40 - 5y = 33\). Subtracting 40 from both sides gives \(-5y = -7\). Dividing both sides by -5 gives \(y = \frac{7}{5}\).  Substituting this value of y into the equation \(x - y = 1\) gives \(x - \frac{7}{5} = 1\), or \(x = \frac{12}{5}\).  Therefore, \(x + y = \frac{12}{5} + \frac{7}{5} = \frac{19}{5}\), or 3.8.  Of the choices given, 5 is closest to 3.8.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_a1',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with center (2, 3) is tangent to the x-axis.  What is the radius of this circle?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"5","is_correct":false,"explanation":""},{"id":"D","text":"13","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Since the circle is tangent to the x-axis, the distance from the center of the circle to the x-axis is equal to the radius. The y-coordinate of the center of the circle is 3, so the radius of the circle is 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'b61e7b1d',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A square has a side length of 5 units. What is the area of the square?',
    'multiple_choice',
    '[{"id":"A","text":"5","is_correct":false,"explanation":""},{"id":"B","text":"10","is_correct":false,"explanation":""},{"id":"C","text":"20","is_correct":false,"explanation":""},{"id":"D","text":"25","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The area of a square is found by squaring the side length.  Therefore, the area of the square is 5² = 25 square units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_5',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $2x + 3 = 12$ is equivalent to which of the following equations?',
    'multiple_choice',
    '[{"id":"A","text":"x + 3 = 6","is_correct":false,"explanation":""},{"id":"B","text":"2x = 9","is_correct":true,"explanation":""},{"id":"C","text":"x = 9/2","is_correct":false,"explanation":""},{"id":"D","text":"x = 6","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Subtracting 3 from both sides of the equation $2x + 3 = 12$ gives us $2x = 9$. Therefore, the equation $2x + 3 = 12$ is equivalent to the equation $2x = 9$. ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'e29f31f4',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of 20 students took a test. The average score on the test was 75.  If 10 students scored an average of 80 on the test, what was the average score of the other 10 students?',
    'multiple_choice',
    '[{"id":"A","text":"65","is_correct":false,"explanation":""},{"id":"B","text":"70","is_correct":true,"explanation":""},{"id":"C","text":"75","is_correct":false,"explanation":""},{"id":"D","text":"80","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The total score for all 20 students is 20 * 75 = 1500. The total score for the 10 students who scored an average of 80 is 10 * 80 = 800.  The total score for the other 10 students is 1500 – 800 = 700. Therefore, the average score for the other 10 students is 700/10 = 70.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'f29e588f',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;

INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'A function f is defined by the equation $f(x) = 3x^2 - 5$. If $f(a) = 22$, what is the value of $a$?',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"3","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substitute 22 for $f(a)$ in the equation to get $22 = 3a^2 - 5$.  Add 5 to both sides to get $27 = 3a^2$. Divide both sides by 3 to get $9 = a^2$.  Take the square root of both sides to get $a = 3$ or $a = -3$.  Since the question asks for the value of $a$, the answer is 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '24d6843a',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The following data set represents the number of cars sold by a dealership each day for a week: 12, 15, 18, 14, 21, 16, 19. What is the median number of cars sold?',
    'multiple_choice',
    '[{"id":"A","text":"12","is_correct":false,"explanation":""},{"id":"B","text":"15","is_correct":false,"explanation":""},{"id":"C","text":"16","is_correct":true,"explanation":""},{"id":"D","text":"18","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find the median, we need to order the data set from least to greatest. This gives us: 12, 14, 15, 16, 18, 19, 21. The median is the middle value, which is 16.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'f890dc20',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units. What is the area of the circle, in square units?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":true,"explanation":""},{"id":"D","text":"50\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula $A = \pi r^2$, where $r$ is the radius.  Substituting 5 for $r$, we get $A = \pi (5)^2 = 25\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_a1',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 students asked whether they prefer to study in a quiet or noisy environment. Of the students surveyed, 60% preferred to study in a quiet environment. How many of the students surveyed preferred to study in a noisy environment?',
    'multiple_choice',
    '[{"id":"A","text":"40","is_correct":true,"explanation":""},{"id":"B","text":"60","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":false,"explanation":""},{"id":"D","text":"160","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'If 60% of the students surveyed preferred to study in a quiet environment, then 100% – 60% = 40% preferred to study in a noisy environment.  Since 40% of 100 is 40, 40 of the students surveyed preferred to study in a noisy environment.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_f7',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The expression $(x+2)(x-3)$ is equivalent to which of the following?',
    'multiple_choice',
    '[{"id":"A","text":"x^2 - 6","is_correct":false,"explanation":""},{"id":"B","text":"x^2 - x - 6","is_correct":true,"explanation":""},{"id":"C","text":"x^2 + x - 6","is_correct":false,"explanation":""},{"id":"D","text":"x^2 + 5x - 6","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Using the distributive property (or FOIL), we can expand the expression: (x+2)(x-3) = x(x-3) + 2(x-3) = x^2 - 3x + 2x - 6 = x^2 - x - 6.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '8a2110dd',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The graph of the equation $y = \frac{1}{2}(x+1)(x-3)$ intersects the x-axis at two points. What are the x-coordinates of these two points?',
    'multiple_choice',
    '[{"id":"A","text":"-1 and 3","is_correct":true,"explanation":""},{"id":"B","text":"1 and -3","is_correct":false,"explanation":""},{"id":"C","text":"2 and -2","is_correct":false,"explanation":""},{"id":"D","text":"-2 and 4","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The graph of the equation intersects the x-axis when y = 0.  Setting the equation equal to zero gives $0 = \frac{1}{2}(x+1)(x-3)$.  This equation is satisfied when either x+1=0 or x-3=0. Solving for x in each of these equations yields x = -1 and x = 3.  Therefore, the x-coordinates of the two points of intersection are -1 and 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_c6',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = 3x^2 - 2x + 1$. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-11","is_correct":false,"explanation":""},{"id":"B","text":"-7","is_correct":false,"explanation":""},{"id":"C","text":"11","is_correct":false,"explanation":""},{"id":"D","text":"19","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substituting -2 for x in the given equation yields $f(-2) = 3(-2)^2 - 2(-2) + 1$. This simplifies to $f(-2) = 3(4) + 4 + 1$, or $f(-2) = 12 + 4 + 1$, or $f(-2) = 19$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_a8',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the solution to the equation $2x + 3 = x - 5$?',
    'multiple_choice',
    '[{"id":"A","text":"-8","is_correct":true,"explanation":""},{"id":"B","text":"-2","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Subtracting $x$ from both sides of the equation gives $x + 3 = -5$.  Subtracting 3 from both sides gives $x = -8$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function f(x) is defined by the equation f(x) = (x^2 + 3x - 4)/(x - 1). For what values of x does the function f(x) have a vertical asymptote?',
    'multiple_choice',
    '[{"id":"A","text":"x = -4","is_correct":false,"explanation":""},{"id":"B","text":"x = -1","is_correct":false,"explanation":""},{"id":"C","text":"x = 1","is_correct":true,"explanation":""},{"id":"D","text":"x = 4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'A vertical asymptote occurs where the denominator of a rational function equals zero, making the function undefined.  The denominator of f(x) is (x - 1), and this equals zero when x = 1.  Therefore, the function f(x) has a vertical asymptote at x = 1.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '94831a0f',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = \frac{x^2 - 4}{x + 2}$. For what value of $x$ is $f(x)$ undefined?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":true,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'A function is undefined when the denominator is equal to zero. The denominator of the given function,  $x + 2$, is equal to zero when $x = -2$. Therefore, $f(x)$ is undefined for $x = -2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'a891379d',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 students asked whether they preferred pizza or burgers.  70 students preferred pizza, and 30 students preferred burgers.  What percentage of the students surveyed preferred burgers? ',
    'multiple_choice',
    '[{"id":"A","text":"10%","is_correct":false,"explanation":""},{"id":"B","text":"20%","is_correct":false,"explanation":""},{"id":"C","text":"30%","is_correct":true,"explanation":""},{"id":"D","text":"70%","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find the percentage, we divide the number who preferred burgers (30) by the total number of students (100) and multiply by 100%.  This gives us (30/100) * 100% = 30%.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_10',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x - 2 = 5$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"7","is_correct":true,"explanation":""},{"id":"C","text":"10","is_correct":false,"explanation":""},{"id":"D","text":"12","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Adding 2 to both sides of the equation $x - 2 = 5$ gives us $x = 5 + 2$, or $x = 7$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_d7',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x + 2y = 12$ and $x - 2y = 4$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":true,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Adding the two equations together eliminates $y$, giving us $4x = 16$. Dividing both sides by 4, we get $x = 4$. ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'f87e32ac',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 2x - 8 = 0$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-4","is_correct":false,"explanation":""},{"id":"B","text":"-2","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Factoring the quadratic equation gives us  (x - 4)(x + 2) = 0.  Setting each factor equal to zero, we get x - 4 = 0 or x + 2 = 0.  Solving for x in each equation gives us x = 4 or x = -2.  Therefore, x = 4 is a solution to the equation.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'f84948c7',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The expression $(\sqrt{x} + \sqrt{y})(\sqrt{x} - \sqrt{y})$ is equivalent to which of the following?',
    'multiple_choice',
    '[{"id":"A","text":"$\\sqrt{x^2 - y^2}$","is_correct":false,"explanation":""},{"id":"B","text":"$x^2 - y^2$","is_correct":false,"explanation":""},{"id":"C","text":"$x - y$","is_correct":true,"explanation":""},{"id":"D","text":"$\\sqrt{x} - \\sqrt{y}$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'This expression is in the form of the difference of squares: (a + b)(a - b) = a^2 - b^2.  In this case, a = \sqrt{x} and b = \sqrt{y}.  Therefore, (\sqrt{x} + \sqrt{y})(\sqrt{x} - \sqrt{y}) = (\sqrt{x})^2 - (\sqrt{y})^2 = x - y.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '23987fc8',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of friends are planning a trip. They decide to rent a car for the trip, and they agree that each person will pay an equal share of the rental cost. The rental cost for the car is \$150.  If there are \$f$ friends going on the trip, which of the following expressions represents the amount, in dollars, that each friend will pay?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{150}{f}$","is_correct":true,"explanation":""},{"id":"B","text":"$\\frac{f}{150}$","is_correct":false,"explanation":""},{"id":"C","text":"$150f$","is_correct":false,"explanation":""},{"id":"D","text":"$150 - f$","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To find the amount each friend will pay, we divide the total rental cost by the number of friends: $\frac{150}{f}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'f86d849c',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $2x^2 - 14x + 24 = 0$ can be factored as $2(x-a)(x-b) = 0$. What is the value of $a+b$?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"7","is_correct":true,"explanation":""},{"id":"C","text":"10","is_correct":false,"explanation":""},{"id":"D","text":"12","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Factoring the quadratic equation, we get $2(x-6)(x-2) = 0$.  Therefore, $a = 6$ and $b = 2$, and $a+b = 6+2 = 8$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_c5',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has legs of length 5 and 12. What is the length of the hypotenuse?',
    'multiple_choice',
    '[{"id":"A","text":"11","is_correct":false,"explanation":""},{"id":"B","text":"13","is_correct":true,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"19","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs.  Therefore, the length of the hypotenuse is $\sqrt{5^2 + 12^2} = \sqrt{169} = 13$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c2',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A triangle has vertices at the points $A(0, 0)$, $B(6, 0)$, and $C(3, 4)$. What is the area of triangle $ABC$?',
    'multiple_choice',
    '[{"id":"A","text":"12","is_correct":true,"explanation":""},{"id":"B","text":"18","is_correct":false,"explanation":""},{"id":"C","text":"24","is_correct":false,"explanation":""},{"id":"D","text":"36","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Triangle $ABC$ is a right triangle with base $AB = 6$ and height $BC = 4$.  The area of a triangle is given by $(1/2)bh$, so the area of triangle $ABC$ is $(1/2)(6)(4) = 12$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '97c2f6f4',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 17$ and $x - y = 2$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":true,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for $x$, we can use elimination.  Multiplying the second equation by 3, we get $3x - 3y = 6$.  Adding this equation to the first equation, we get $5x = 23$.  Dividing both sides by 5, we get $x = \frac{23}{5}$, or 4.6. Since the question asks for the value of $x$, we round 4.6 to the nearest whole number, which is 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_a9',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $x^2-2x+k=0$ has exactly one solution. What is the value of $k$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":true,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'A quadratic equation has exactly one solution when its discriminant is equal to zero.  The discriminant of the quadratic equation $ax^2 + bx + c = 0$ is $b^2 - 4ac$. For the given equation, $a = 1$, $b = -2$, and $c = k$.  Setting the discriminant equal to zero, we get $(-2)^2 - 4(1)(k) = 0$, or $4 - 4k = 0$. Solving for $k$ yields $k = 1$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_a1',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - 2y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for x, we can use elimination.  Multiplying the second equation by 2, we get $2x - 4y = 2$. Subtracting this equation from the first equation, we get $7y = 10$, so $y = \frac{10}{7}$.  Substituting this value of y into the second equation, we get $x - 2(\frac{10}{7}) = 1$, so $x = 1 + \frac{20}{7} = \frac{27}{7}$.  Therefore, the value of x is 4.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'How many feet are equivalent to 34 yards? (1 yard = 3 feet)',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"17","is_correct":false,"explanation":""},{"id":"C","text":"31","is_correct":false,"explanation":""},{"id":"D","text":"102","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'It''s given that 1 yard is equivalent to 3 feet. Therefore, 34 yards is equivalent to (34 yards)(3 feet / 1 yard), or 102 feet.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'd0d9ede4',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x = 3$, what is the value of $(x+1)^2$?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":false,"explanation":""},{"id":"B","text":"9","is_correct":false,"explanation":""},{"id":"C","text":"16","is_correct":true,"explanation":""},{"id":"D","text":"25","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Substitute $x = 3$ into the expression.  This gives us $(3+1)^2 = 4^2 = 16$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'f98f754f',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 centimeters. What is the circumference of the circle in centimeters?  (Express your answer in terms of \pi.)',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":true,"explanation":""},{"id":"C","text":"25\\pi","is_correct":false,"explanation":""},{"id":"D","text":"50\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula C = 2\pi r, where r is the radius of the circle.  Substituting 5 for r, we get C = 2\pi(5) = 10\pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_55',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;

INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'A circle is inscribed in a square. The side length of the square is 10.  What is the area of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"$\\pi$","is_correct":false,"explanation":""},{"id":"B","text":"$10\\pi$","is_correct":false,"explanation":""},{"id":"C","text":"$25\\pi$","is_correct":true,"explanation":""},{"id":"D","text":"$100\\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square, which is 10. The radius of the circle is half the diameter, or 5. The area of a circle is given by the formula $\pi r^2$, where r is the radius. Therefore, the area of the circle is $\pi(5^2) = 25\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_a8',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a radius of 5 is inscribed in a square. What is the area of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square.  Since the radius of the circle is 5, the diameter is 10.  Therefore, the area of the square is 10 * 10 = 100.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '75288e9f',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can solve this system of equations using elimination.  Multiplying the second equation by 3, we get $3x - 3y = 3$. Adding this equation to the first equation, we get $5x = 15$. Dividing both sides by 5, we get $x=3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_a4',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 centimeters.  What is the circumference of the circle, in centimeters?  (Express your answer in terms of pi.)',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":true,"explanation":""},{"id":"C","text":"25\\pi","is_correct":false,"explanation":""},{"id":"D","text":"50\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula C = 2πr, where r is the radius.  Substituting 5 for r gives C = 2π(5) = 10π.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c9',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x + 2y = 6$ and $x - 2y = 4$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Adding the two equations together, we get $(x+2y) + (x-2y) = 6 + 4$, which simplifies to $2x = 10$. Dividing both sides by 2 gives us $x=5$. Therefore, the value of $x$ is 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_a5',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a radius of 5 is inscribed in a square. What is the area of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square. Since the radius of the circle is 5, the diameter is 10.  The area of the square is side length squared, or 10^2 = 100.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The graph of the equation  $y = \frac{1}{2}(x-3)^2 + 1$  is a parabola. What is the vertex of this parabola?',
    'multiple_choice',
    '[{"id":"A","text":"(1, 3)","is_correct":false,"explanation":""},{"id":"B","text":"(3, 1)","is_correct":true,"explanation":""},{"id":"C","text":"(-3, 1)","is_correct":false,"explanation":""},{"id":"D","text":"(1, -3)","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The vertex form of a parabola is $y = a(x - h)^2 + k$, where $(h, k)$ is the vertex. In the given equation, $h = 3$ and $k = 1$. Therefore, the vertex of the parabola is $(3, 1)$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '73f19b0e',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has legs of length 5 and 12. What is the length of the hypotenuse of the triangle?',
    'multiple_choice',
    '[{"id":"A","text":"13","is_correct":true,"explanation":""},{"id":"B","text":"17","is_correct":false,"explanation":""},{"id":"C","text":"19","is_correct":false,"explanation":""},{"id":"D","text":"25","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs.  In this case, we have: $5^2 + 12^2 = 25 + 144 = 169$.  The square root of 169 is 13, so the length of the hypotenuse is 13.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_a7',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = ax^2 + bx + c$, where $a$, $b$, and $c$ are constants, has a minimum value of 5 at $x = 2$. If the graph of $f(x)$ intersects the y-axis at $(0, 9)$, what is the value of $c$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":false,"explanation":""},{"id":"C","text":"9","is_correct":true,"explanation":""},{"id":"D","text":"13","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Since the function has a minimum value of 5 at x = 2, the vertex of the parabola is at (2, 5).  We can use the vertex form of a quadratic equation to write the equation:  $f(x) = a(x - 2)^2 + 5$.  We know the graph intersects the y-axis at (0, 9), which means f(0) = 9. Substituting these values into the equation, we get: 9 = a(0 - 2)^2 + 5.  Simplifying the equation, we get: 9 = 4a + 5.  Solving for a, we get a = 1.  Substituting this value of a back into the vertex form, we get: $f(x) = (x - 2)^2 + 5$.  Expanding the equation, we get: $f(x) = x^2 - 4x + 4 + 5$, or $f(x) = x^2 - 4x + 9$.  Therefore, the value of c is 9.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '4444222',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $f(x) = \frac{1}{x+2}$, what is the value of $f(3)$?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":false,"explanation":""},{"id":"B","text":"0","is_correct":false,"explanation":""},{"id":"C","text":"$\\frac{1}{5}$","is_correct":true,"explanation":""},{"id":"D","text":"1","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find the value of $f(3)$, we substitute 3 for $x$ in the function: $f(3) = \frac{1}{3+2} = \frac{1}{5}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_a1',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $2x + 3y = 12$ represents a line in the xy-plane.  What is the y-intercept of the line?',
    'multiple_choice',
    '[{"id":"A","text":"-4","is_correct":true,"explanation":""},{"id":"B","text":"-3","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"12","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To find the y-intercept of a line, we set $x$ equal to 0 and solve for $y$.  Substituting 0 for $x$ in the equation $2x + 3y = 12$, we get $3y = 12$. Dividing both sides by 3, we find $y = 4$.  Therefore, the y-intercept of the line is (0, 4).  The y-intercept is -4, which is the y-value when $x$ is equal to 0.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '7777777',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  $3x + 2y = 12$ and $x - 2y = 4$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for *x*, we can add the two equations together. This eliminates *y* and gives us $4x = 16$. Dividing both sides of the equation by 4, we get *x* = 4. Therefore, the value of *x* is 6.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '894961da',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $y = 2x + 5$ and $x = -3$, what is the value of $y$?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":true,"explanation":""},{"id":"B","text":"1","is_correct":false,"explanation":""},{"id":"C","text":"-6","is_correct":false,"explanation":""},{"id":"D","text":"11","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Substituting $x = -3$ into the equation $y = 2x + 5$ gives us $y = 2(-3) + 5$, or $y = -6 + 5$, or $y = -1$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '45322232',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'In the $xy$-plane, a circle has center $(3,2)$ and a radius of 5. Which of the following points lies on the circle? ',
    'multiple_choice',
    '[{"id":"A","text":"(3,7)","is_correct":false,"explanation":""},{"id":"B","text":"(8,2)","is_correct":true,"explanation":""},{"id":"C","text":"(3,-3)","is_correct":false,"explanation":""},{"id":"D","text":"(0,2)","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The distance from the center of the circle to any point on the circle is equal to the radius of the circle.  The distance between the points $(3,2)$ and $(8,2)$ is $8 - 3 = 5$, so the point $(8,2)$ lies on the circle.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '3795d245',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If the system of equations $\begin{cases} 2x + 3y = 7 \\ x - 2y = 1 \end{cases}$ has solution $(x, y)$, what is the value of $x - y$ ?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":true,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"2","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for $x - y$, we can multiply the second equation by 2, giving us $2x - 4y = 2$.  Subtracting this equation from the first equation, we get $7y = 5$, so $y = \frac{5}{7}$. Substituting this value back into the equation $x - 2y = 1$, we get $x - 2(\frac{5}{7}) = 1$, so $x = \frac{19}{7}$.  Therefore, $x - y = \frac{19}{7} - \frac{5}{7} = \frac{14}{7} = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a radius of 5 is inscribed in a square. What is the area of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square. The diameter of the circle is twice the radius, so the diameter is 10. The area of a square is equal to the side length squared, so the area of the square is 10^2 = 100.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_a2',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm. What is the circumference of the circle in terms of $\pi$?',
    'multiple_choice',
    '[{"id":"A","text":"$\\pi$ cm","is_correct":false,"explanation":""},{"id":"B","text":"5$\\pi$ cm","is_correct":false,"explanation":""},{"id":"C","text":"10$\\pi$ cm","is_correct":true,"explanation":""},{"id":"D","text":"25$\\pi$ cm","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius.  Substituting 5 cm for $r$, we get $C = 2\pi (5) = 10\pi$ cm.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_b9',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a radius of 5 is inscribed in a square. What is the area of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square. Since the radius of the circle is 5, the diameter is 10. Therefore, the side length of the square is 10, and the area of the square is 10 * 10 = 100.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_a8',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 5*x*<sup>2</sup> - 3*x* + 2. What is the value of *f*(-2)?',
    'multiple_choice',
    '[{"id":"A","text":"-26","is_correct":false,"explanation":""},{"id":"B","text":"-16","is_correct":false,"explanation":""},{"id":"C","text":"16","is_correct":false,"explanation":""},{"id":"D","text":"26","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substituting -2 for *x* in the function, we get *f*(-2) = 5(-2)<sup>2</sup> - 3(-2) + 2. Simplifying, we have *f*(-2) = 5(4) + 6 + 2 = 20 + 6 + 2 = 26.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_a7',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 centimeters. A chord of the circle is 8 centimeters long. What is the distance, in centimeters, between the center of the circle and the chord?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Draw a radius from the center of the circle to one endpoint of the chord, and draw another radius to the other endpoint of the chord. This forms an isosceles triangle with the chord as the base. The altitude of this triangle from the center of the circle bisects the chord. This altitude forms a right triangle with one leg being 4 centimeters (half of the chord) and the hypotenuse being 5 centimeters (the radius).  Using the Pythagorean theorem, the other leg of the right triangle (which is the distance between the center of the circle and the chord) has length $\sqrt{5^2-4^2} = \sqrt{9} = 3$ centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_a10',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A line in the $xy$-plane passes through the points $(2,5)$ and $(4,11)$. What is the slope of the line?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The slope of a line passing through two points is given by the formula $\frac{y_2 - y_1}{x_2 - x_1}$.  Substituting the points $(2,5)$ and $(4,11)$ into the formula gives $\frac{11-5}{4-2} = \frac{6}{2} = 3$. Therefore, the slope of the line is 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '4d3672ba',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The graph of the line  is shown below. Which of the following is the equation of this line? \begin{align*} \text{A. }  y&= -2x - 8\ \text{B. }  y&= x - 8\ \text{C. } y&= -x - 8\ \text{D. }  y&= 2x - 8\ \end{align*}',
    'multiple_choice',
    '[{"id":"A","text":"y = -2x - 8","is_correct":false,"explanation":""},{"id":"B","text":"y = x - 8","is_correct":false,"explanation":""},{"id":"C","text":"y = -x - 8","is_correct":true,"explanation":""},{"id":"D","text":"y = 2x - 8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The equation of a line can be written in slope-intercept form: y = mx + b, where m is the slope of the line, and b is the y-intercept of the line.  The line shown passes through the point (-8, 0), so b = 0. The line shown also passes through the point (-1, 8).  The slope, m, of a line passing through two points and can be calculated using the equation . For the points and , this gives , or .  Substituting for m and for b in y = mx + b yields y = -x + 0, or y = -x. Therefore, an equation of the graph shown is y = -x - 8.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'd02193fb',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store manager recorded the number of customers who visited the store on each day of the week. The number of customers who visited the store on Monday was 150. The number of customers who visited the store on Tuesday was 20% greater than the number of customers who visited on Monday. What is the number of customers who visited the store on Tuesday?',
    'multiple_choice',
    '[{"id":"A","text":"120","is_correct":false,"explanation":""},{"id":"B","text":"180","is_correct":true,"explanation":""},{"id":"C","text":"240","is_correct":false,"explanation":""},{"id":"D","text":"300","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    '20% of 150 is equal to .20 x 150 = 30. Since 20% greater than 150 is 150 + 30, there were 180 customers who visited on Tuesday.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_26',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the solution to the system of equations $\begin{cases} x - 2y = 6 \\ x + 2y = 4 \end{cases}$ ?',
    'multiple_choice',
    '[{"id":"A","text":"(5, -1/2)","is_correct":false,"explanation":""},{"id":"B","text":"(5, -1)","is_correct":false,"explanation":""},{"id":"C","text":"(5, 1/2)","is_correct":false,"explanation":""},{"id":"D","text":"(5, 1)","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Adding the two equations together eliminates y, resulting in 2x = 10. Dividing both sides by 2 gives x = 5. Substituting 5 for x in the first equation gives 5 - 2y = 6. Subtracting 5 from both sides gives -2y = 1. Dividing both sides by -2 gives y = -1/2. Therefore, the solution to the system is (5, -1/2).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_a8',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A bakery sells two types of cookies: chocolate chip and oatmeal raisin. The bakery makes 120 cookies per day, and the ratio of chocolate chip cookies to oatmeal raisin cookies is 5:3. How many oatmeal raisin cookies does the bakery make per day?',
    'multiple_choice',
    '[{"id":"A","text":"20","is_correct":false,"explanation":""},{"id":"B","text":"36","is_correct":true,"explanation":""},{"id":"C","text":"48","is_correct":false,"explanation":""},{"id":"D","text":"60","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The ratio 5:3 means that for every 5 chocolate chip cookies, there are 3 oatmeal raisin cookies. This represents a total of 5 + 3 = 8 parts. Since the bakery makes 120 cookies per day, each part represents 120/8 = 15 cookies. Therefore, the bakery makes 3 * 15 = 45 oatmeal raisin cookies per day.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_c8',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;