INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'A group of friends went to a restaurant.  The bill came to \$120.  They agreed to split the bill evenly.  If each friend paid \$15, how many friends were in the group?',
    'multiple_choice',
    '[{"id":"A","text":"6","is_correct":false,"explanation":""},{"id":"B","text":"8","is_correct":true,"explanation":""},{"id":"C","text":"10","is_correct":false,"explanation":""},{"id":"D","text":"12","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To find the number of friends, we divide the total bill by the amount each friend paid: 120 / 15 = 8.  Therefore, there were 8 friends in the group.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_c7',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The expression $(2x+3)(x-7)$ is equivalent to which of the following expressions?',
    'multiple_choice',
    '[{"id":"A","text":"2x^2 - 11x - 21","is_correct":true,"explanation":""},{"id":"B","text":"2x^2 + 11x - 21","is_correct":false,"explanation":""},{"id":"C","text":"2x^2 - x - 21","is_correct":false,"explanation":""},{"id":"D","text":"2x^2 + x - 21","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Using the distributive property (also known as FOIL), we expand the expression: (2x+3)(x-7) = 2x(x-7) + 3(x-7) = 2x^2 - 14x + 3x - 21 = 2x^2 - 11x - 21',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '95f8da71',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 8 centimeters and a width of 5 centimeters. What is the area of the rectangle, in square centimeters?',
    'multiple_choice',
    '[{"id":"A","text":"13","is_correct":false,"explanation":""},{"id":"B","text":"26","is_correct":false,"explanation":""},{"id":"C","text":"40","is_correct":true,"explanation":""},{"id":"D","text":"64","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is calculated by multiplying the length and width. Therefore, the area of the rectangle is 8 cm * 5 cm = 40 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c3',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If 2x + 3y = 17 and x - y = 2, what is the value of x?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":true,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for *x*, we can use elimination.  Multiplying the second equation by 3, we get 3x - 3y = 6.  Adding this equation to the first equation, we get 5x = 23.  Dividing both sides by 5, we get *x* = 23/5, or *x* = 4.6.  Of the choices given, 5 is closest to 4.6.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '84f9203b',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 3x<sup>2</sup> - 5x + 2. What is the value of *f*(2)?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":false,"explanation":""},{"id":"B","text":"6","is_correct":false,"explanation":""},{"id":"C","text":"8","is_correct":true,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find *f*(2), we substitute 2 for *x* in the function: *f*(2) = 3(2)<sup>2</sup> - 5(2) + 2 = 3(4) - 10 + 2 = 12 - 8 = 4. Therefore, *f*(2) = 4.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_c4',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x + 3y = 10$ and $x = 2y$, what is the value of $y$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Substitute $2y$ for $x$ in the first equation: $2y + 3y = 10$. Combine like terms: $5y = 10$.  Divide both sides by 5 to get $y = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'In the xy-plane, a circle with center at (0, 0) passes through the point (4, 3). What is the radius of the circle? ',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":true,"explanation":""},{"id":"D","text":"7","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The radius of the circle is the distance between the center of the circle and any point on the circle.  We can use the distance formula to find this distance: $\sqrt{(4-0)^2 + (3-0)^2} = \sqrt{16 + 9} = \sqrt{25} = 5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c8',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has legs of length 5 and 12. What is the length of the hypotenuse?',
    'multiple_choice',
    '[{"id":"A","text":"11","is_correct":false,"explanation":""},{"id":"B","text":"13","is_correct":true,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"19","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs.  Therefore, the length of the hypotenuse is $\sqrt{5^2 + 12^2} = \sqrt{169} = 13$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_b24',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x - 2y = 5$ and $x + 2y = 7$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Notice that the $y$ terms have opposite signs in the two equations. Adding the two equations together, we get $(3x - 2y) + (x + 2y) = 5 + 7$. This simplifies to $4x = 12$, so $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_a6',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = 2x^2 + 3x - 1$ is defined for all real numbers. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-9","is_correct":true,"explanation":""},{"id":"B","text":"-3","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Substituting -2 for $x$ in the function, we get $f(-2) = 2(-2)^2 + 3(-2) - 1 = 8 - 6 - 1 = 1$. Therefore, the value of $f(-2)$ is -9.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_c8',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units. What is the area, in square units, of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"5","is_correct":false,"explanation":""},{"id":"B","text":"10","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":true,"explanation":""},{"id":"D","text":"50\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula  where r is the radius of the circle.  Substituting 5 for r in the formula, we get π(5)² = 25π.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'b646d131',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 10 centimeters and a width of 6 centimeters. What is the area, in square centimeters, of the rectangle? ',
    'multiple_choice',
    '[{"id":"A","text":"16","is_correct":false,"explanation":""},{"id":"B","text":"32","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":true,"explanation":""},{"id":"D","text":"106","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is equal to the product of its length and its width. So, the area of this rectangle is 10 centimeters * 6 centimeters = 60 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has sides of length 3, 4, and 5. What is the area of the triangle?',
    'multiple_choice',
    '[{"id":"A","text":"6","is_correct":true,"explanation":""},{"id":"B","text":"12","is_correct":false,"explanation":""},{"id":"C","text":"15","is_correct":false,"explanation":""},{"id":"D","text":"24","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The area of a right triangle is (1/2) * base * height. Since the sides of the triangle are 3, 4, and 5, we know it''s a Pythagorean triple, making it a right triangle. The base and height are the two shorter sides, so the area is (1/2) * 3 * 4 = 6.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people liked apples, 50 people liked bananas, and 20 people liked both apples and bananas. What is the probability that a person surveyed liked apples, given that the person liked bananas? ',
    'multiple_choice',
    '[{"id":"A","text":"1/5","is_correct":false,"explanation":""},{"id":"B","text":"3/5","is_correct":true,"explanation":""},{"id":"C","text":"2/3","is_correct":false,"explanation":""},{"id":"D","text":"3/4","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The probability that a person surveyed liked apples given that the person liked bananas is equal to the number of people who liked both apples and bananas divided by the number of people who liked bananas.  This gives us 20/50, or 3/5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '2ac7b45a',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = 2x^2 - 3x + 1$. What is the value of $f(2)$?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":true,"explanation":""},{"id":"B","text":"5","is_correct":false,"explanation":""},{"id":"C","text":"7","is_correct":false,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To find $f(2)$, we substitute 2 for x in the function: $f(2) = 2(2)^2 - 3(2) + 1 = 8 - 6 + 1 = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '4a32f0f5',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a circumference of 12\pi. What is the radius of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"6","is_correct":true,"explanation":""},{"id":"C","text":"12","is_correct":false,"explanation":""},{"id":"D","text":"24","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula C = 2πr, where r is the radius.  We are given that C = 12π, so 12π = 2πr.  Dividing both sides by 2π gives us r = 6.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '987fc19d',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  \(2x + 3y = 7\) and  \(x - y = 2\), what is the value of  \(x + y\)?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":true,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for x + y, we can use elimination. Multiplying the second equation by 3, we get \(3x - 3y = 6\).  Adding this equation to the first equation, we get \(5x = 13\).  Dividing both sides by 5, we get \(x = \frac{13}{5}\). Substituting this value back into the equation \(x - y = 2\), we get  \(\frac{13}{5} - y = 2\).  Solving for y, we get \(y = \frac{3}{5}\).  Therefore, \(x + y = \frac{13}{5} + \frac{3}{5} = \frac{16}{5}\), or 3.2. The closest answer choice is 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_b10',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 12 centimeters and a width of 5 centimeters. What is the area, in square centimeters, of the rectangle?',
    'multiple_choice',
    '[{"id":"A","text":"17","is_correct":false,"explanation":""},{"id":"B","text":"34","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":true,"explanation":""},{"id":"D","text":"120","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is found by multiplying its length by its width.  Therefore, the area of this rectangle is (12)(5) = 60 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_9',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey asked 100 people whether they prefer to eat pizza or tacos. The results showed that 60 people prefer pizza, and 40 people prefer tacos. What percentage of the people surveyed prefer tacos?',
    'multiple_choice',
    '[{"id":"A","text":"20%","is_correct":false,"explanation":""},{"id":"B","text":"40%","is_correct":true,"explanation":""},{"id":"C","text":"60%","is_correct":false,"explanation":""},{"id":"D","text":"80%","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The percentage of people who prefer tacos can be calculated by dividing the number of people who prefer tacos by the total number of people surveyed and multiplying by 100%. This gives (40/100) * 100% = 40%.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_c2',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 10 centimeters and a width of 6 centimeters. What is the area of the rectangle, in square centimeters?',
    'multiple_choice',
    '[{"id":"A","text":"16","is_correct":false,"explanation":""},{"id":"B","text":"32","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":true,"explanation":""},{"id":"D","text":"100","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is equal to its length multiplied by its width.  Therefore, the area of this rectangle is 10 centimeters * 6 centimeters = 60 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c4',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $2x^2 - 3x + 1 = 0$ has two solutions, $x_1$ and $x_2$. What is the value of $x_1^2 + x_2^2$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":false,"explanation":""},{"id":"C","text":"7","is_correct":true,"explanation":""},{"id":"D","text":"13","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can use the relationship between the roots and coefficients of a quadratic equation.  For the quadratic equation  $ax^2 + bx + c = 0$, the sum of the roots is $-b/a$ and the product of the roots is $c/a$.  In this case, the sum of the roots, $x_1 + x_2$, is $3/2$, and the product of the roots, $x_1x_2$, is $1/2$.  We want to find $x_1^2 + x_2^2$.  We can square the equation $x_1 + x_2 = 3/2$ to get $x_1^2 + 2x_1x_2 + x_2^2 = 9/4$.  Subtracting $2x_1x_2$ from both sides gives us $x_1^2 + x_2^2 = 9/4 - 2x_1x_2$.  Substituting $x_1x_2 = 1/2$, we get $x_1^2 + x_2^2 = 9/4 - 2(1/2) = 9/4 - 1 = 5/4 = 7$.  Therefore, the value of $x_1^2 + x_2^2$ is 7.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_d3',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $f(x) = 2x^2 + 3x - 1$, what is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-9","is_correct":true,"explanation":""},{"id":"B","text":"-3","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Substituting -2 for $x$ in the function $f(x) = 2x^2 + 3x - 1$, we get $f(-2) = 2(-2)^2 + 3(-2) - 1$. Simplifying, we have $f(-2) = 8 - 6 - 1 = 1$. Therefore, the value of $f(-2)$ is -9.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_c7',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 2x^3 - 5x + 3.  What is the value of *f*(-2)?',
    'multiple_choice',
    '[{"id":"A","text":"-13","is_correct":false,"explanation":""},{"id":"B","text":"-5","is_correct":false,"explanation":""},{"id":"C","text":"13","is_correct":false,"explanation":""},{"id":"D","text":"19","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Substitute -2 for x in the function: f(-2) = 2(-2)^3 - 5(-2) + 3.  Simplify: f(-2) = 2(-8) + 10 + 3 = -16 + 13 = 19.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '13e622f4',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x + 3 = 7$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":true,"explanation":""},{"id":"B","text":"10","is_correct":false,"explanation":""},{"id":"C","text":"14","is_correct":false,"explanation":""},{"id":"D","text":"21","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To solve for $x$, we subtract 3 from both sides of the equation: $x + 3 - 3 = 7 - 3$. This gives us $x = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_a4',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $x^2 - 6x + 9 = 0$ has exactly one solution. What is the value of the solution?',
    'multiple_choice',
    '[{"id":"A","text":"0","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The equation is a perfect square trinomial, which can be factored as $(x-3)^2 = 0$. Taking the square root of both sides yields $x-3 = 0$.  Adding 3 to both sides of the equation yields $x=3$.  Therefore, the solution to the equation is 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'f469d82a',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;

INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'A circle has a radius of 5 units.  What is the circumference of the circle, in units?  (Express your answer in terms of \pi.)',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":true,"explanation":""},{"id":"C","text":"25\\pi","is_correct":false,"explanation":""},{"id":"D","text":"50\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where r is the radius of the circle.  Substituting 5 for r, we get  C = 2\pi (5) = 10\pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '981d5815',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x+4y = 10$ and $2x-y = 5$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for $x$, we can use elimination. Multiplying the second equation by 4, we get $8x - 4y = 20$. Adding this equation to the first equation, we get $11x = 30$, which gives us $x = \frac{30}{11}$. Since 2 is the closest integer to $\frac{30}{11}$, the answer is B.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_d4',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey asked 100 people whether they prefer to eat pizza or tacos. 60 people said they prefer pizza, and 40 people said they prefer tacos. Of the people surveyed, what percentage prefer tacos?',
    'multiple_choice',
    '[{"id":"A","text":"4%","is_correct":false,"explanation":""},{"id":"B","text":"20%","is_correct":false,"explanation":""},{"id":"C","text":"40%","is_correct":true,"explanation":""},{"id":"D","text":"60%","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The percentage of people who prefer tacos is found by dividing the number who prefer tacos by the total number of people surveyed and multiplying by 100%: (40/100) * 100% = 40%.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_e3',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the solution to the equation  $x^{2} - 2x - 3 = 0$?',
    'multiple_choice',
    '[{"id":"A","text":"-3 and 1","is_correct":false,"explanation":""},{"id":"B","text":"-1 and 3","is_correct":true,"explanation":""},{"id":"C","text":"1 and -3","is_correct":false,"explanation":""},{"id":"D","text":"3 and -1","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The equation is in the form of a quadratic equation, where the coefficients are 1, -2, and -3. This equation can be solved by factoring. The factors of the equation are (x - 3) and (x + 1), which equal 0 when x = 3 and x = -1, respectively. Therefore, the solutions are x = -1 and x = 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'e60f8e2e',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle in the xy-plane has center (2, -3) and radius 5. Which of the following is an equation for this circle?',
    'multiple_choice',
    '[{"id":"A","text":"(x + 2)^2 + (y - 3)^2 = 25","is_correct":false,"explanation":""},{"id":"B","text":"(x - 2)^2 + (y + 3)^2 = 5","is_correct":false,"explanation":""},{"id":"C","text":"(x + 2)^2 + (y - 3)^2 = 5","is_correct":false,"explanation":""},{"id":"D","text":"(x - 2)^2 + (y + 3)^2 = 25","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The standard form of the equation of a circle with center (h, k) and radius r is (x - h)^2 + (y - k)^2 = r^2.  Substituting the values from the problem gives us (x - 2)^2 + (y + 3)^2 = 5^2, which simplifies to (x - 2)^2 + (y + 3)^2 = 25.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '1e20d548',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey was conducted to determine the number of people who own a dog in a certain town. The results showed that 30% of the  people surveyed own a dog.  If there are 200 people in the town, what is the best estimate for the number of people who own a dog?',
    'multiple_choice',
    '[{"id":"A","text":"6","is_correct":false,"explanation":""},{"id":"B","text":"60","is_correct":true,"explanation":""},{"id":"C","text":"200","is_correct":false,"explanation":""},{"id":"D","text":"600","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The best estimate for the number of people who own a dog is 30% of the total population, or (0.30)(200) = 60.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_c3',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 centimeters. What is the circumference of the circle, in centimeters? (Use 3.14 for *\pi*)',
    'multiple_choice',
    '[{"id":"A","text":"15.7","is_correct":false,"explanation":""},{"id":"B","text":"31.4","is_correct":true,"explanation":""},{"id":"C","text":"62.8","is_correct":false,"explanation":""},{"id":"D","text":"157","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula *C = 2πr*, where *r* is the radius.  Substituting 5 for *r* and 3.14 for *π*, we get *C = 2(3.14)(5) = 31.4*.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_a4',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The graph of $y = \frac{1}{x - 2}$ has a vertical asymptote at $x = k$. What is the value of $k$?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"0","is_correct":false,"explanation":""},{"id":"D","text":"1","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A vertical asymptote occurs where the denominator of a rational function equals zero.  In this case, the denominator is $x - 2$, and it equals zero when $x = 2$. Therefore, the value of $k$ is 2.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_c2',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people liked apples, 40 people liked oranges, and 20 people liked both apples and oranges. How many people liked only oranges?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"20","is_correct":true,"explanation":""},{"id":"C","text":"30","is_correct":false,"explanation":""},{"id":"D","text":"40","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can use a Venn diagram to solve this problem.  Let the number of people who like only apples be represented by x, and the number of people who like only oranges be represented by y.  We know that x + 20 + y = 100 (the total number of people surveyed), and that x + 20 = 60 (the number of people who like apples).  Solving for x, we get x = 40.  Substituting 40 for x into the equation x + 20 + y = 100, we get 40 + 20 + y = 100, or y = 40. Therefore, 40 people like only oranges.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If the function $f(x) = \frac{x^2 - 4}{x - 2}$ is defined, what is the value of $f(2)$?',
    'multiple_choice',
    '[{"id":"A","text":"0","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"The function is not defined at $x = 2$.","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The function is undefined at x = 2 because the denominator becomes 0 when x = 2, making the expression undefined. The function is not defined at a value where the denominator would equal zero.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_f4',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x+2y=6$ and $x-2y=4$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'We can solve for $x$ by adding the two equations together. Notice that the $y$ terms will cancel out.  $(x+2y) + (x-2y) = 6 + 4$ or $2x = 10$.  Dividing both sides by 2, we get $x = 5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'e54c34a5',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a circumference of 12π.  What is the area of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"12π","is_correct":false,"explanation":""},{"id":"B","text":"36π","is_correct":true,"explanation":""},{"id":"C","text":"144π","is_correct":false,"explanation":""},{"id":"D","text":"144","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula C = 2πr, where r is the radius of the circle.  We are given that C = 12π, so 12π = 2πr.  Dividing both sides by 2π, we get r = 6.  The area of a circle is given by the formula A = πr², so A = π(6)² = 36π.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_a7',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 6 units.  A chord of the circle is 8 units long.  What is the distance from the center of the circle to the chord?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":true,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"$\\sqrt{28}$","is_correct":false,"explanation":""},{"id":"D","text":"$\\sqrt{52}$","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Draw a diagram of the circle, the chord, and the radius from the center of the circle to the midpoint of the chord.  This radius bisects the chord, creating two right triangles.  The hypotenuse of each triangle is a radius of the circle (6 units), and one leg of each triangle is half the chord (4 units).  We can use the Pythagorean Theorem to find the other leg (the distance from the center to the chord):  $6^2 = 4^2 + d^2$, where $d$ is the distance from the center of the circle to the chord.  Solving for $d$, we find $d = \sqrt{6^2 - 4^2} = \sqrt{20} = 2\sqrt{5}$.  Since the distance from the center to the chord is half of this distance, the distance from the center of the circle to the chord is $\sqrt{5}$ units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_12',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units.  What is the area, in square units, of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":true,"explanation":""},{"id":"D","text":"50\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula $A = \pi r^2$, where $r$ is the radius.  Substituting 5 for $r$, we get $A = \pi (5)^2 = 25\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'f691e728',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = 2x^2 + 3x - 1$ is defined for all real numbers. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-9","is_correct":true,"explanation":""},{"id":"B","text":"-3","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Substituting -2 for x in the function, we get:  $f(-2) = 2(-2)^2 + 3(-2) - 1 = 2(4) - 6 - 1 = 8 - 6 - 1 = -9$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_c6',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people liked apples, 40 people liked oranges, and 20 people liked both apples and oranges. How many people liked only oranges?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"20","is_correct":true,"explanation":""},{"id":"C","text":"30","is_correct":false,"explanation":""},{"id":"D","text":"40","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can use a Venn Diagram to visualize the problem.  There are 20 people who like both apples and oranges, so we subtract this number from the total number of people who like oranges to find the number of people who like only oranges: 40 - 20 = 20.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_c4',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 200 students found that 120 students prefer pizza, 80 prefer burgers, and 60 prefer tacos.  What is the probability that a randomly selected student from this survey prefers tacos?',
    'multiple_choice',
    '[{"id":"A","text":"0.15","is_correct":false,"explanation":""},{"id":"B","text":"0.2","is_correct":false,"explanation":""},{"id":"C","text":"0.3","is_correct":true,"explanation":""},{"id":"D","text":"0.6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The probability of a student preferring tacos is the number of students who prefer tacos divided by the total number of students surveyed. This is 60/200, which simplifies to 0.3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_c6',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 3x^2 - 5x + 2. What is the value of *f*(2)?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":true,"explanation":""},{"id":"B","text":"6","is_correct":false,"explanation":""},{"id":"C","text":"8","is_correct":false,"explanation":""},{"id":"D","text":"10","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To find *f*(2), we substitute 2 for *x* in the function: *f*(2) = 3(2)^2 - 5(2) + 2 = 12 - 10 + 2 = 4.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '8a76bc7a',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by  *f*(x) = 3x^2 + 5. What is the value of *f*(2)?',
    'multiple_choice',
    '[{"id":"A","text":"11","is_correct":false,"explanation":""},{"id":"B","text":"17","is_correct":true,"explanation":""},{"id":"C","text":"21","is_correct":false,"explanation":""},{"id":"D","text":"27","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To find *f*(2), we substitute 2 for x in the equation *f*(x) = 3x^2 + 5. This gives us *f*(2) = 3(2)^2 + 5 = 3 * 4 + 5 = 12 + 5 = 17.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '87654321',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a circumference of 10\pi.  What is the area of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":true,"explanation":""},{"id":"D","text":"100\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The circumference of a circle is given by the formula C = 2\pi r, where r is the radius of the circle.  We are given that the circumference is 10\pi, so 10\pi = 2\pi r.  Dividing both sides by 2\pi gives us r = 5.  The area of a circle is given by the formula A = \pi r^2.  Substituting 5 for r gives us A = \pi (5)^2 = 25\pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_b8',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5. What is the area of the circle? (Express your answer in terms of $\pi$.)',
    'multiple_choice',
    '[{"id":"A","text":"$5\\pi$","is_correct":false,"explanation":""},{"id":"B","text":"$10\\pi$","is_correct":false,"explanation":""},{"id":"C","text":"$25\\pi$","is_correct":true,"explanation":""},{"id":"D","text":"$100\\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula $A = \pi r^2$, where $r$ is the radius.  Substituting 5 for $r$ gives $A = \pi (5^2) = 25\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_a7',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 10 centimeters and a width of 5 centimeters. What is the area, in square centimeters, of the rectangle?',
    'multiple_choice',
    '[{"id":"A","text":"15","is_correct":false,"explanation":""},{"id":"B","text":"25","is_correct":false,"explanation":""},{"id":"C","text":"50","is_correct":true,"explanation":""},{"id":"D","text":"100","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is found by multiplying the length and width.  Therefore, the area of this rectangle is 10 * 5 = 50 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c4',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If the function $f(x)=x^2 + 3x - 1$ is defined for all real numbers, what is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-7","is_correct":true,"explanation":""},{"id":"B","text":"-3","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'To find the value of f(-2), we substitute -2 for $x$ in the function: $f(-2) = (-2)^2 + 3(-2) - 1 = 4 - 6 - 1 = -3$. Therefore, the value of f(-2) is -3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '2795ab32',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm. What is the circumference of the circle? (Use $\pi = 3.14$)',
    'multiple_choice',
    '[{"id":"A","text":"15.7 cm","is_correct":false,"explanation":""},{"id":"B","text":"31.4 cm","is_correct":true,"explanation":""},{"id":"C","text":"78.5 cm","is_correct":false,"explanation":""},{"id":"D","text":"157 cm","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius.  Substituting the given values, we get $C = 2 (3.14)(5) = 31.4$ cm.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c7',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function \(f\) is defined by \(f(x) = 2x + 3\). What is the value of \(f(4)\)?',
    'multiple_choice',
    '[{"id":"A","text":"5","is_correct":false,"explanation":""},{"id":"B","text":"11","is_correct":true,"explanation":""},{"id":"C","text":"14","is_correct":false,"explanation":""},{"id":"D","text":"18","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To find the value of \(f(4)\), we substitute 4 for x in the function: \(f(4) = 2(4) + 3 = 8 + 3 = 11\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'f81b648f',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;

INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'A rectangular garden is feet long and feet wide.  The garden is surrounded by a path that is feet wide.  What is the area, in square feet, of the path?',
    'multiple_choice',
    '[{"id":"A","text":"64","is_correct":false,"explanation":""},{"id":"B","text":"96","is_correct":false,"explanation":""},{"id":"C","text":"144","is_correct":false,"explanation":""},{"id":"D","text":"192","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The area of the garden is  square feet. The area of the garden plus the path is  square feet. Therefore, the area of the path is  square feet.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '4e93f543',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 2x² – 3x + 5.  What is the value of *f*(–2)?',
    'multiple_choice',
    '[{"id":"A","text":"-19","is_correct":false,"explanation":""},{"id":"B","text":"-9","is_correct":false,"explanation":""},{"id":"C","text":"19","is_correct":false,"explanation":""},{"id":"D","text":"29","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find *f*(–2), we substitute –2 for *x* in the function.  *f*(–2) = 2(–2)² – 3(–2) + 5 = 2(4) + 6 + 5 = 8 + 6 + 5 = 19.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_d4',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If the function *f* is defined by *f*(x) = \sqrt{x} + 4, what is the value of *f*(16)?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":false,"explanation":""},{"id":"B","text":"8","is_correct":false,"explanation":""},{"id":"C","text":"12","is_correct":true,"explanation":""},{"id":"D","text":"20","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find *f*(16), we substitute 16 for *x* in the function: *f*(16) = \sqrt{16} + 4.  Since \sqrt{16} = 4, *f*(16) = 4 + 4 = 8.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '49e85755',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60% of them prefer apples, 30% prefer oranges, and 10% prefer bananas. If 20 more people are surveyed, and the same percentages of people prefer each fruit, how many of the 120 people surveyed would prefer oranges?',
    'multiple_choice',
    '[{"id":"A","text":"24","is_correct":false,"explanation":""},{"id":"B","text":"30","is_correct":false,"explanation":""},{"id":"C","text":"36","is_correct":true,"explanation":""},{"id":"D","text":"42","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Since 30% of the 100 people surveyed prefer oranges, 30 people prefer oranges.  If the same percentage of people prefer oranges out of 120 people, then 30% of 120 people prefer oranges.  30% of 120 is 0.30 * 120 = 36.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_a7',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the value of $\frac{1}{2} \times \frac{2}{3} \times \frac{3}{4} \times \frac{4}{5}$?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{1}{10}$","is_correct":true,"explanation":""},{"id":"B","text":"$\\frac{1}{5}$","is_correct":false,"explanation":""},{"id":"C","text":"$\\frac{3}{5}$","is_correct":false,"explanation":""},{"id":"D","text":"$\\frac{7}{10}$","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Notice that all of the numerators cancel with the denominators except for 1 in the numerator and 10 in the denominator.  This leaves us with $\frac{1}{10}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '234d5678',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The lengths of the sides of a right triangle are 5, 12, and 13. What is the cosine of the angle opposite the side of length 12?',
    'multiple_choice',
    '[{"id":"A","text":"5/13","is_correct":true,"explanation":""},{"id":"B","text":"12/13","is_correct":false,"explanation":""},{"id":"C","text":"5/12","is_correct":false,"explanation":""},{"id":"D","text":"12/5","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'In a right triangle, the cosine of an angle is the ratio of the length of the adjacent side to the length of the hypotenuse.  The side of length 5 is adjacent to the angle opposite the side of length 12, and the hypotenuse has length 13.  Therefore, the cosine of the angle opposite the side of length 12 is 5/13.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_69',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'In a right triangle, the length of the hypotenuse is 10, and the length of one leg is 6. What is the length of the other leg?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":false,"explanation":""},{"id":"B","text":"8","is_correct":false,"explanation":""},{"id":"C","text":"$\\sqrt{64}$","is_correct":false,"explanation":""},{"id":"D","text":"$\\sqrt{136}$","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'We can use the Pythagorean theorem to solve this. The Pythagorean theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the other two sides. So, $10^2 = 6^2 + x^2$, where $x$ is the length of the other leg. Simplifying, we get $100 = 36 + x^2$. Subtracting 36 from both sides, we get $64 = x^2$. Taking the square root of both sides, we get $x = \sqrt{64} = 8$. However, the problem asks for the length of the *other* leg, which is the hypotenuse minus 6, so the answer is $\sqrt{136}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_e4',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5. What is the circumference of the circle? ',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":true,"explanation":""},{"id":"C","text":"25\\pi","is_correct":false,"explanation":""},{"id":"D","text":"50\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula C = 2\pi r, where r is the radius.  Substituting 5 for r, we get C = 2\pi(5) = 10\pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c9',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 2x - 8 = 0$, what is the sum of the solutions to the equation?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":true,"explanation":""},{"id":"C","text":"-6","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The sum of the solutions to a quadratic equation in the form ax^2 + bx + c = 0 is given by -b/a. In this case, a = 1, b = -2, and c = -8. So, the sum of the solutions is -(-2)/1 = 2.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_a1',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a diameter of 10. What is the circumference of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":true,"explanation":""},{"id":"C","text":"20\\pi","is_correct":false,"explanation":""},{"id":"D","text":"100\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula C = 2\pi r, where r is the radius. Since the diameter is 10, the radius is 5.  Therefore, the circumference is C = 2\pi (5) = 10\pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c9',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 12 centimeters and a width of 5 centimeters. What is the area, in square centimeters, of the rectangle?',
    'multiple_choice',
    '[{"id":"A","text":"17","is_correct":false,"explanation":""},{"id":"B","text":"34","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":true,"explanation":""},{"id":"D","text":"125","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is found by multiplying the length by the width.  So, the area of this rectangle is 12 centimeters * 5 centimeters = 60 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_37',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5. What is the circumference of the circle? ',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":true,"explanation":""},{"id":"C","text":"25\\pi","is_correct":false,"explanation":""},{"id":"D","text":"100\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula C = 2\pi r, where r is the radius.  Substituting 5 for r, we get C = 2\pi (5) = 10\pi.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_e5',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A rectangle has a length of 12 meters and a width of 5 meters.  What is the area, in square meters, of the rectangle? ',
    'multiple_choice',
    '[{"id":"A","text":"17","is_correct":false,"explanation":""},{"id":"B","text":"34","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":true,"explanation":""},{"id":"D","text":"125","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a rectangle is the product of its length and its width.  The area of the rectangle is 12 meters * 5 meters = 60 square meters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c7',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The expression $\frac{2x+3}{5} + \frac{x-1}{5}$ is equivalent to which of the following expressions?',
    'multiple_choice',
    '[{"id":"A","text":"\\frac{2x + 2}{5}","is_correct":false,"explanation":""},{"id":"B","text":"\\frac{3x + 2}{5}","is_correct":false,"explanation":""},{"id":"C","text":"\\frac{3x + 4}{5}","is_correct":true,"explanation":""},{"id":"D","text":"\\frac{3x + 2}{10}","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Since the expressions have the same denominator, we can combine the numerators:  $\frac{2x+3}{5} + \frac{x-1}{5} = \frac{2x + 3 + x - 1}{5} = \frac{3x + 2}{5}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '6b4ebc8c',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey asked 100 people whether they prefer to watch movies at home or at the theater. 60 people said they prefer to watch movies at home, and 40 people said they prefer to watch movies at the theater.  What percentage of the people surveyed prefer to watch movies at the theater?',
    'multiple_choice',
    '[{"id":"A","text":"20%","is_correct":false,"explanation":""},{"id":"B","text":"40%","is_correct":true,"explanation":""},{"id":"C","text":"60%","is_correct":false,"explanation":""},{"id":"D","text":"80%","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The percentage of people who prefer to watch movies at the theater is the number of people who prefer to watch movies at the theater divided by the total number of people surveyed, multiplied by 100%. This gives us  (40/100) * 100% = 40%.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_c7',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5. What is the area of the circle? (Express your answer in terms of pi.)',
    'multiple_choice',
    '[{"id":"A","text":"5π","is_correct":false,"explanation":""},{"id":"B","text":"10π","is_correct":false,"explanation":""},{"id":"C","text":"25π","is_correct":true,"explanation":""},{"id":"D","text":"50π","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula  πr², where r is the radius of the circle.  Substituting 5 for r, we get π(5)² = 25π.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c9',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the value of  $x$ that satisfies the equation $2^x = 16$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":true,"explanation":""},{"id":"C","text":"8","is_correct":false,"explanation":""},{"id":"D","text":"16","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We know that 16 is equal to 2 to the power of 4, or $2^4$.  Therefore, $x = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_c8',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x + 5 = 14$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for x, we first subtract 5 from both sides of the equation:  $3x + 5 - 5 = 14 - 5$, which simplifies to $3x = 9$. Then, we divide both sides of the equation by 3: $3x / 3 = 9 / 3$, which gives us $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function \(f(x)\) is defined by \(f(x) = \frac{x^2-4}{x-2}\). For what value(s) of \(x\) is the function undefined?',
    'multiple_choice',
    '[{"id":"A","text":"x = 2","is_correct":true,"explanation":""},{"id":"B","text":"x = 4","is_correct":false,"explanation":""},{"id":"C","text":"x = -2","is_correct":false,"explanation":""},{"id":"D","text":"x = 2 and x = -2","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'A function is undefined when the denominator of a fraction equals 0. In the given function, the denominator is x-2, which equals 0 when x = 2. Therefore, the function is undefined when x = 2.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_c5',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle in the xy-plane has its center at $(4,-5)$ and a radius of 7. Which of the following is an equation for this circle?',
    'multiple_choice',
    '[{"id":"A","text":"(x - 4)^2 + (y + 5)^2 = 49","is_correct":true,"explanation":""},{"id":"B","text":"(x + 4)^2 + (y - 5)^2 = 49","is_correct":false,"explanation":""},{"id":"C","text":"(x - 4)^2 + (y + 5)^2 = 7","is_correct":false,"explanation":""},{"id":"D","text":"(x + 4)^2 + (y - 5)^2 = 7","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The standard form of the equation of a circle in the xy-plane with center (h, k) and radius r is (x - h)^2 + (y - k)^2 = r^2.  Since the center of the circle is (4, -5) and the radius is 7, the equation of the circle is (x - 4)^2 + (y + 5)^2 = 7^2, or (x - 4)^2 + (y + 5)^2 = 49.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'f84e4372',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 3x^2 + 2. For what value of *x* does *f*(x) = 29?',
    'multiple_choice',
    '[{"id":"A","text":"-3","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"3","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find the value of *x* that makes *f*(x) = 29, we set the equation 3x^2 + 2 = 29 and solve for *x*. Subtracting 2 from both sides, we get 3x^2 = 27. Dividing both sides by 3, we get x^2 = 9. Taking the square root of both sides, we get x = 3 or x = -3. Since the problem asks for the value of *x* that makes *f*(x) = 29, the answer is x = 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_a3',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  \(\frac{2x+3}{x-7}\) = 1, what is the value of x?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":false,"explanation":""},{"id":"C","text":"7","is_correct":false,"explanation":""},{"id":"D","text":"10","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'Multiplying both sides of the equation by (x - 7) gives 2x + 3 = x - 7. Subtracting x from both sides gives x + 3 = -7. Subtracting 3 from both sides gives x = -10.  Therefore, the value of x is 10.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '70a90772',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A regular hexagon is inscribed in a circle with radius 10. What is the perimeter of the hexagon?',
    'multiple_choice',
    '[{"id":"A","text":"30","is_correct":false,"explanation":""},{"id":"B","text":"60","is_correct":true,"explanation":""},{"id":"C","text":"60\\sqrt{3}","is_correct":false,"explanation":""},{"id":"D","text":"120\\sqrt{3}","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A regular hexagon can be divided into 6 equilateral triangles.  Each of these triangles has a side length equal to the radius of the circle, which is 10. Therefore, the perimeter of the hexagon is 6 * 10 = 60.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_9',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A regular hexagon is inscribed in a circle with radius 6. What is the perimeter of the hexagon?',
    'multiple_choice',
    '[{"id":"A","text":"12","is_correct":false,"explanation":""},{"id":"B","text":"18","is_correct":false,"explanation":""},{"id":"C","text":"24","is_correct":false,"explanation":""},{"id":"D","text":"36","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'A regular hexagon can be divided into 6 equilateral triangles.  The side length of each equilateral triangle is equal to the radius of the circle, which is 6.  Therefore, the perimeter of the hexagon is 6 * 6 = 36.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_a8',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 100 people found that 60 people liked apples, 50 people liked oranges, and 20 people liked both apples and oranges. How many people liked neither apples nor oranges?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"20","is_correct":false,"explanation":""},{"id":"C","text":"30","is_correct":true,"explanation":""},{"id":"D","text":"40","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can use a Venn Diagram to solve this problem.  Let A represent the set of people who like apples and O represent the set of people who like oranges.  We are given that  |A| = 60, |O| = 50, and  |A \cap O| = 20.  We want to find  |A \cup O|'' (the number of people who like neither apples nor oranges).  We can use the following formula:  |A \cup O| = |A| + |O| - |A \cap O|.  Substituting our known values, we get |A \cup O| = 60 + 50 - 20 = 90.  Since the survey included 100 people, the number who like neither apples nor oranges is 100 - 90 = 10.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_8',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;