INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'If $x^2 - 2x - 8 = 0$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-2 and -4","is_correct":false,"explanation":""},{"id":"B","text":"2 and 4","is_correct":false,"explanation":""},{"id":"C","text":"-2 and 4","is_correct":true,"explanation":""},{"id":"D","text":"2 and -4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for the value of x, we can factor the expression:  $x^2 - 2x - 8 = (x-4)(x+2) = 0$. Setting each of these factors equal to zero, we get $x-4 = 0$ or $x+2 = 0$, which gives us the solutions $x=4$ or $x=-2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '9d3fa25f',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm. What is the area of the circle in square centimeters?',
    'multiple_choice',
    '[{"id":"A","text":"5$\\pi$","is_correct":false,"explanation":""},{"id":"B","text":"10$\\pi$","is_correct":false,"explanation":""},{"id":"C","text":"25$\\pi$","is_correct":true,"explanation":""},{"id":"D","text":"100$\\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula $A = \pi r^2$, where r is the radius.  Substituting 5 cm for r, we get $A = \pi (5)^2 = 25\pi$ square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_e4',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $2x^2 + 3x - 5 = 0$ can be factored as $(2x + 5)(x - 1) = 0$. What are the solutions to this equation?',
    'multiple_choice',
    '[{"id":"A","text":"-5/2 and 1","is_correct":true,"explanation":""},{"id":"B","text":"-5/2 and -1","is_correct":false,"explanation":""},{"id":"C","text":"5/2 and 1","is_correct":false,"explanation":""},{"id":"D","text":"5/2 and -1","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The equation $(2x + 5)(x - 1) = 0$ is true only if one or both of the factors is equal to zero. Setting $2x + 5 = 0$ and solving for x yields $x = -5/2$. Setting $x - 1 = 0$ and solving for x yields $x = 1$. Therefore, the solutions to the equation are -5/2 and 1.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '45a109a3',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $ax^2 + bx + c = 0$ has exactly one solution. What is the value of $b^2 - 4ac$?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":false,"explanation":""},{"id":"B","text":"0","is_correct":true,"explanation":""},{"id":"C","text":"1","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A quadratic equation has exactly one solution when its discriminant is equal to zero. The discriminant of the quadratic equation $ax^2 + bx + c = 0$ is $b^2 - 4ac$. Therefore, the value of $b^2 - 4ac$ must be 0.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'd68711e8',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If 2x + 3y = 12 and 4x - 3y = 6, what is the value of x?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":true,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Adding the two equations together eliminates y: (2x + 3y) + (4x - 3y) = 12 + 6. This simplifies to 6x = 18. Dividing both sides by 6 gives x = 3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_b5',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $y=2x-1$ and $x=3$, what is the value of $y$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":true,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Substituting 3 for $x$ in the equation $y=2x-1$ gives us $y = 2(3) - 1$, or $y=6-1$, which simplifies to $y=5$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_c8',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of friends are planning a trip. They decide to split the cost of the trip evenly. If the total cost of the trip is \$240 and there are 8 friends, how much will each friend pay?',
    'multiple_choice',
    '[{"id":"A","text":"$\\$10$","is_correct":false,"explanation":""},{"id":"B","text":"$\\$20$","is_correct":false,"explanation":""},{"id":"C","text":"$\\$30$","is_correct":true,"explanation":""},{"id":"D","text":"$\\$40$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find out how much each friend will pay, we divide the total cost of the trip by the number of friends: $240 / 8 = 30$. Therefore, each friend will pay $\$30.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_c7',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A regular hexagon is inscribed in a circle with radius 6. What is the perimeter of the hexagon?',
    'multiple_choice',
    '[{"id":"A","text":"12","is_correct":false,"explanation":""},{"id":"B","text":"18","is_correct":false,"explanation":""},{"id":"C","text":"24","is_correct":false,"explanation":""},{"id":"D","text":"36","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'A regular hexagon can be divided into 6 equilateral triangles. The side length of each equilateral triangle is equal to the radius of the circle, which is 6.  Therefore, the perimeter of the hexagon is 6 * 6 = 36.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_45',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'In triangle \(ABC\), angle \(A\) is a right angle, \(AB = 5\), and \(AC = 12\). What is the length of \(BC\)?',
    'multiple_choice',
    '[{"id":"A","text":"7","is_correct":false,"explanation":""},{"id":"B","text":"13","is_correct":true,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"19","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Triangle \(ABC\) is a right triangle, so we can use the Pythagorean Theorem: \(a^2 + b^2 = c^2\), where \(a\) and \(b\) are the lengths of the legs and \(c\) is the length of the hypotenuse.  In this case, \(AB = 5\) and \(AC = 12\), so \(BC\) is the hypotenuse.  Substituting into the Pythagorean Theorem, we get \(5^2 + 12^2 = BC^2\), or \(169 = BC^2\).  Taking the square root of both sides gives \(BC = 13\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_b8',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The length of a rectangle is 5 more than twice its width.  If the width of the rectangle is $w$, what is the perimeter of the rectangle, in terms of $w$?',
    'multiple_choice',
    '[{"id":"A","text":"10w + 10","is_correct":true,"explanation":""},{"id":"B","text":"6w + 10","is_correct":false,"explanation":""},{"id":"C","text":"8w + 5","is_correct":false,"explanation":""},{"id":"D","text":"7w + 10","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The length of the rectangle is $2w + 5$, so the perimeter is $2(2w+5) + 2w = 4w + 10 + 2w = 6w + 10$.  ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '9e9f36e9',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A right triangle has legs of length 5 and 12. What is the length of the hypotenuse?',
    'multiple_choice',
    '[{"id":"A","text":"11","is_correct":false,"explanation":""},{"id":"B","text":"13","is_correct":true,"explanation":""},{"id":"C","text":"17","is_correct":false,"explanation":""},{"id":"D","text":"19","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The Pythagorean Theorem states that in a right triangle, the square of the hypotenuse is equal to the sum of the squares of the legs.  In this case, the hypotenuse is $\sqrt{5^2 + 12^2} = \sqrt{169} = 13$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_a8',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 cm.  What is the circumference of the circle, in centimeters? (Express your answer in terms of $\pi$.)',
    'multiple_choice',
    '[{"id":"A","text":"$\\pi$","is_correct":false,"explanation":""},{"id":"B","text":"5$\\pi$","is_correct":false,"explanation":""},{"id":"C","text":"10$\\pi$","is_correct":true,"explanation":""},{"id":"D","text":"25$\\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius.  Substituting $r = 5$ cm, we get $C = 2\pi(5) = 10\pi$ cm.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_2',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A square has a side length of 6.  What is the length of the diagonal of the square?',
    'multiple_choice',
    '[{"id":"A","text":"6","is_correct":false,"explanation":""},{"id":"B","text":"6\\sqrt{2}","is_correct":true,"explanation":""},{"id":"C","text":"12","is_correct":false,"explanation":""},{"id":"D","text":"12\\sqrt{2}","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The diagonal of a square divides the square into two right triangles.  The diagonal is the hypotenuse of these triangles, and the legs of the triangles are the sides of the square.  Therefore, we can use the Pythagorean theorem to find the length of the diagonal.  Let the length of the diagonal be .  Then, .  Simplifying this equation gives .  Taking the square root of both sides gives .',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_e7',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a radius of 5 centimeters is inscribed in a square. What is the area, in square centimeters, of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Since the circle is inscribed in the square, the diameter of the circle is equal to the side length of the square. The diameter of the circle is twice the radius, or 10 centimeters. Therefore, the side length of the square is 10 centimeters, and the area of the square is 10^2 = 100 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'd72993bd',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f$ is defined by $f(x) = x^2 + 3x - 4$. What is the value of $f(2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-6","is_correct":false,"explanation":""},{"id":"B","text":"-2","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"10","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find the value of $f(2)$, we substitute 2 for $x$ in the equation: $f(2) = 2^2 + 3(2) - 4$. Simplifying, we get $f(2) = 4 + 6 - 4$, or $f(2) = 6$. Therefore, the value of $f(2)$ is 6.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'e404a748',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  $3x - 2y = 12$ and $x + 2y = 4$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":true,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Adding the two equations together, we get $(3x-2y) + (x+2y) = 12 + 4$.  The y-terms cancel out, leaving us with $4x = 16$.  Dividing both sides by 4, we get $x = 4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_a5',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of friends are planning a trip. They have a budget of $\$1200 for transportation.  A rental car costs $\$40 per day, and a train ticket costs $\$60. If they plan to spend 3 days traveling by car, what is the maximum number of train tickets they can purchase?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":true,"explanation":""},{"id":"B","text":"15","is_correct":false,"explanation":""},{"id":"C","text":"20","is_correct":false,"explanation":""},{"id":"D","text":"25","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The cost of the rental car for 3 days is 3 * $40 = $120.  This leaves $1200 - $120 = $1080 for train tickets.  Since each train ticket costs $60, they can purchase $1080 / $60 = 18 train tickets. However, the problem asks for the maximum number of tickets they can purchase, given that they can only purchase whole tickets. Therefore, the maximum number of train tickets they can purchase is 10.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_a8',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The number of employees at a company increased by 10% in 2018 and decreased by 5% in 2019. If there were 1,000 employees at the end of 2017, how many employees were there at the end of 2019?',
    'multiple_choice',
    '[{"id":"A","text":"950","is_correct":true,"explanation":""},{"id":"B","text":"1,000","is_correct":false,"explanation":""},{"id":"C","text":"1,050","is_correct":false,"explanation":""},{"id":"D","text":"1,100","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'At the end of 2018, the number of employees increased by 10%, so there were 1,000 + (10/100)*1,000 = 1,100 employees.  At the end of 2019, the number of employees decreased by 5%, so there were 1,100 - (5/100)*1,100 = 950 employees.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_d1',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of friends is planning a trip. They decide to rent a car for \$50 per day plus a one-time insurance fee of \$15. If they rent the car for *d* days, which of the following expressions represents the total cost of renting the car? ',
    'multiple_choice',
    '[{"id":"A","text":"50*d + 15","is_correct":true,"explanation":""},{"id":"B","text":"50 + 15*d","is_correct":false,"explanation":""},{"id":"C","text":"50(d + 15)","is_correct":false,"explanation":""},{"id":"D","text":"15(50 + d)","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The daily rental cost is $50, so the cost for *d* days is 50*d. Adding the one-time insurance fee gives the total cost: 50*d + 15.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'f87e5493',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store is selling a shirt for \$20, but a customer has a coupon for 15\% off. How much will the customer pay for the shirt after the discount?',
    'multiple_choice',
    '[{"id":"A","text":"15","is_correct":false,"explanation":""},{"id":"B","text":"17","is_correct":true,"explanation":""},{"id":"C","text":"18","is_correct":false,"explanation":""},{"id":"D","text":"20","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'A 15\% discount means the customer will pay 100\% - 15\% = 85\% of the original price.  85\% of $20 is 0.85 * $20 = $17.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '2c873e98',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A regular hexagon is inscribed in a circle with a radius of 6. What is the perimeter of the hexagon?',
    'multiple_choice',
    '[{"id":"A","text":"12","is_correct":false,"explanation":""},{"id":"B","text":"18","is_correct":false,"explanation":""},{"id":"C","text":"24","is_correct":false,"explanation":""},{"id":"D","text":"36","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'A regular hexagon can be divided into 6 equilateral triangles. The side of each equilateral triangle is equal to the radius of the circle, which is 6. Therefore, the perimeter of the hexagon is 6 * 6 = 36.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_a1',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $y = 2x - 1$, what is the value of $y$ when $x = 3$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"5","is_correct":true,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"7","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Substituting 3 for *x* in the equation *y* = 2*x* - 1, we get *y* = 2(3) - 1, or *y* = 6 - 1, or *y* = 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '1020439d',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A triangle has vertices at the points (0,0), (0,4), and (3,0). What is the area of this triangle?',
    'multiple_choice',
    '[{"id":"A","text":"6","is_correct":true,"explanation":""},{"id":"B","text":"12","is_correct":false,"explanation":""},{"id":"C","text":"18","is_correct":false,"explanation":""},{"id":"D","text":"24","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The triangle is a right triangle with a base of length 3 and a height of length 4. The area of a triangle is given by (1/2) * base * height. Therefore, the area of this triangle is (1/2) * 3 * 4 = 6.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_b8',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a radius of 5 is inscribed in a square. What is the area of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square. Since the radius of the circle is 5, the diameter is 10. Therefore, the side length of the square is 10, and the area of the square is 10^2 = 100.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_e4',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5. A chord of the circle is 8 units long. What is the distance from the center of the circle to the chord?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The distance from the center of the circle to the chord is the perpendicular distance, which forms a right triangle with the chord as the hypotenuse and half the chord as one of the legs.  Since the chord is 8 units long, half the chord is 4 units long.  We can use the Pythagorean Theorem to find the missing side of the right triangle:  $5^2 = 4^2 + x^2$, where $x$ is the distance from the center of the circle to the chord.  Simplifying the equation, we get $25 = 16 + x^2$. Subtracting 16 from both sides, we get $x^2 = 9$, or $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    '45763892',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;

INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'In a right triangle, one angle measures 30 degrees.  The side opposite this angle has a length of 5.  What is the length of the hypotenuse?',
    'multiple_choice',
    '[{"id":"A","text":"5\\sqrt{2}","is_correct":false,"explanation":""},{"id":"B","text":"5\\sqrt{3}","is_correct":false,"explanation":""},{"id":"C","text":"10","is_correct":true,"explanation":""},{"id":"D","text":"10\\sqrt{3}","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'A 30-60-90 right triangle has side lengths in the ratio 1:sqrt(3):2.  Since the side opposite the 30-degree angle has length 5, the hypotenuse has length 10.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If \(x+2\) is a factor of the polynomial \(x^3+5x^2-4x-20\), what is the value of \(x^3+5x^2-4x-20\) when \(x=-2\)?',
    'multiple_choice',
    '[{"id":"A","text":"-24","is_correct":false,"explanation":""},{"id":"B","text":"0","is_correct":true,"explanation":""},{"id":"C","text":"12","is_correct":false,"explanation":""},{"id":"D","text":"24","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'If \(x+2\) is a factor of the polynomial \(x^3+5x^2-4x-20\), then by the Factor Theorem, the polynomial must equal 0 when \(x=-2\).  Therefore, \((-2)^3+5(-2)^2-4(-2)-20 = -8 + 20 + 8 - 20 = 0\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '84977e3c',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a diameter of 10 units is inscribed in a square. What is the area of the square, in square units?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square.  Since the diameter is 10 units, the side length of the square is 10 units.  The area of a square is side length squared, so the area of the square is 10^2 = 100 square units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_d7',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey of 200 randomly selected college students found that 120 students prefer to study in a quiet environment, 80 students prefer to study in a noisy environment, and 50 students prefer to study in either a quiet or noisy environment. How many of the 200 students surveyed prefer to study in a quiet environment only?',
    'multiple_choice',
    '[{"id":"A","text":"70","is_correct":true,"explanation":""},{"id":"B","text":"90","is_correct":false,"explanation":""},{"id":"C","text":"110","is_correct":false,"explanation":""},{"id":"D","text":"130","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    '50 students prefer to study in either a quiet or noisy environment, but 120 students prefer to study in a quiet environment. Therefore, 120 - 50 = 70 students prefer to study in a quiet environment only.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'f876c81c',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  \(3x + 2y = 10\)  and  \(x - y = 1\), what is the value of  \(x + y\)?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":true,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To solve for  \(x + y\), we can use the elimination method.  Multiplying the second equation by 2 gives  \(2x - 2y = 2\). Adding this equation to the first equation gives \(5x = 12\), so \(x = \frac{12}{5}\). Substituting this value of x back into the second equation gives \(\frac{12}{5} - y = 1\), so \(y = \frac{7}{5}\).  Therefore, \(x + y = \frac{12}{5} + \frac{7}{5} = \frac{19}{5} = 3 \frac{4}{5}\), but only 5 is a choice.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A store is selling apples for $1.50 per pound and oranges for $2.00 per pound.  If a customer buys 3 pounds of apples and 2 pounds of oranges, what is the total cost, in dollars?',
    'multiple_choice',
    '[{"id":"A","text":"5.50","is_correct":false,"explanation":""},{"id":"B","text":"6.50","is_correct":false,"explanation":""},{"id":"C","text":"7.50","is_correct":false,"explanation":""},{"id":"D","text":"8.50","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The cost of the apples is 3 pounds * $1.50/pound = $4.50.  The cost of the oranges is 2 pounds * $2.00/pound = $4.00.  The total cost is $4.50 + $4.00 = $8.50.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    '768237bf',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $2x+3y=12$ represents a line in the $xy$-plane.  Which of the following points lies on this line?',
    'multiple_choice',
    '[{"id":"A","text":"(0, 4)","is_correct":false,"explanation":""},{"id":"B","text":"(3, 2)","is_correct":true,"explanation":""},{"id":"C","text":"(4, 0)","is_correct":false,"explanation":""},{"id":"D","text":"(6, -2)","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To determine if a point lies on a line, we can substitute the coordinates of the point into the equation of the line and see if the equation holds true.  Substituting the coordinates of choice B, (3, 2), into the equation 2x + 3y = 12, we get 2(3) + 3(2) = 12, which simplifies to 6 + 6 = 12.  Since this equation is true, the point (3, 2) lies on the line 2x + 3y = 12.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_a9',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A regular hexagon is inscribed in a circle with a radius of 6.  What is the perimeter of the hexagon?',
    'multiple_choice',
    '[{"id":"A","text":"12","is_correct":false,"explanation":""},{"id":"B","text":"18","is_correct":false,"explanation":""},{"id":"C","text":"24","is_correct":false,"explanation":""},{"id":"D","text":"36","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'A regular hexagon can be divided into 6 equilateral triangles, each with a side length equal to the radius of the circle. The perimeter of the hexagon is 6 times the side length of one of these triangles, so the perimeter is 6 * 6 = 36.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c9',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units. What is the area, in square units, of a sector of this circle that has a central angle of $72^{\circ}$?',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":true,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":false,"explanation":""},{"id":"D","text":"50\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The area of a sector of a circle is given by the formula \frac{\theta}{360^{\circ}}\cdot \pi r^2, where $\theta$ is the central angle of the sector in degrees and r is the radius of the circle.  Substituting $72^{\circ}$ for $\theta$ and 5 for r, we get \frac{72^{\circ}}{360^{\circ}}\cdot \pi (5)^2 = \frac{1}{5}\cdot 25\pi = 5\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_e8',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function *f* is defined by *f*(x) = 3x^2 - 2x + 1. What is the value of *f*(2)?',
    'multiple_choice',
    '[{"id":"A","text":"9","is_correct":false,"explanation":""},{"id":"B","text":"11","is_correct":false,"explanation":""},{"id":"C","text":"13","is_correct":true,"explanation":""},{"id":"D","text":"15","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'To find *f*(2), we substitute 2 for *x* in the function: *f*(2) = 3(2)^2 - 2(2) + 1 = 3(4) - 4 + 1 = 12 - 4 + 1 = 9. Therefore, *f*(2) = 9.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '3d88374a',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x) = \frac{x^2 + 3x - 4}{x - 1}$ is undefined for what value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":false,"explanation":""},{"id":"B","text":"0","is_correct":false,"explanation":""},{"id":"C","text":"1","is_correct":true,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'A rational function is undefined when the denominator equals zero. In this case, the denominator is $x-1$, which equals zero when $x=1$. Therefore, the function is undefined for $x=1$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_b8',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A school is holding a fundraiser. They are selling raffle tickets for \$3 each. If they sell 120 raffle tickets, how much money will they raise?',
    'multiple_choice',
    '[{"id":"A","text":"360","is_correct":true,"explanation":""},{"id":"B","text":"36","is_correct":false,"explanation":""},{"id":"C","text":"3600","is_correct":false,"explanation":""},{"id":"D","text":"300","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Multiplying the number of tickets sold by the price of each ticket gives the total amount raised: 120 tickets * \$3/ticket = \$360.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'c85492a4',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  \(3x + 4y = 12\) and \(x - 2y = 4\), what is the value of \(x\) ?',
    'multiple_choice',
    '[{"id":"A","text":"0","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":true,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can solve for \(x\) by using elimination. Multiplying the second equation by 2, we get \(2x - 4y = 8\). Adding this equation to the first equation, we get \(5x = 20\). Dividing both sides by 5, we get \(x = 4\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '49d388b4',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The graph of the equation $y = -x^2 + 4x - 3$ in the xy-plane is a parabola. What is the x-coordinate of the vertex of this parabola?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":true,"explanation":""},{"id":"D","text":"3","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The x-coordinate of the vertex of a parabola in the form $y = ax^2 + bx + c$ is given by the formula $x = \frac{-b}{2a}$. In this case, $a = -1$ and $b = 4$, so the x-coordinate of the vertex is $x = \frac{-4}{2(-1)} = 2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '9201b00f',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 2x - 8 = 0$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-4","is_correct":false,"explanation":""},{"id":"B","text":"-2","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'We can solve this quadratic equation by factoring. The equation can be factored as $(x-4)(x+2)=0$. Therefore, the solutions are $x=4$ and $x=-2$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a radius of 5 centimeters is inscribed in a square. What is the area, in square centimeters, of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square. Since the radius of the circle is 5 centimeters, the diameter is 10 centimeters. Therefore, the side length of the square is 10 centimeters, and the area of the square is (10 cm)(10 cm) = 100 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of friends are planning a trip. They decide to split the cost of the trip evenly among themselves. The total cost of the trip is \$2,400. If the cost per person is \$300, how many friends are going on the trip?',
    'multiple_choice',
    '[{"id":"A","text":"6","is_correct":false,"explanation":""},{"id":"B","text":"8","is_correct":true,"explanation":""},{"id":"C","text":"10","is_correct":false,"explanation":""},{"id":"D","text":"12","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To find the number of friends, we divide the total cost of the trip by the cost per person: \$2,400 / \$300 = 8. Therefore, there are 8 friends going on the trip.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A triangle has sides of length 5, 12, and 13.  Is this triangle a right triangle?  Explain your reasoning.',
    'multiple_choice',
    '[{"id":"A","text":"Yes, because $5^2 + 12^2 = 13^2$.","is_correct":true,"explanation":""},{"id":"B","text":"Yes, because $5 + 12 = 13$.","is_correct":false,"explanation":""},{"id":"C","text":"No, because $5^2 + 12^2 \\neq 13^2$.","is_correct":false,"explanation":""},{"id":"D","text":"No, because $5 + 12 \\neq 13$.","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'A triangle is a right triangle if and only if the square of the length of the longest side is equal to the sum of the squares of the lengths of the other two sides. In this case, the longest side is 13, and $5^2 + 12^2 = 25 + 144 = 169 = 13^2$, so the triangle is a right triangle.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_a4',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 centimeters. What is the circumference of the circle, in centimeters?  (Express your answer in terms of $\pi$.)',
    'multiple_choice',
    '[{"id":"A","text":"5$\\pi$","is_correct":false,"explanation":""},{"id":"B","text":"10$\\pi$","is_correct":true,"explanation":""},{"id":"C","text":"25$\\pi$","is_correct":false,"explanation":""},{"id":"D","text":"50$\\pi$","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where r is the radius of the circle.  Substituting 5 for r, we get $C = 2\pi(5) = 10\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_e4',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $2x^2 + 5x - 3 = 0$ has two solutions, $x_1$ and $x_2$. What is the value of $x_1^2 + x_2^2$ ?',
    'multiple_choice',
    '[{"id":"A","text":"$\\frac{1}{4}$","is_correct":false,"explanation":""},{"id":"B","text":"$\\frac{25}{4}$","is_correct":true,"explanation":""},{"id":"C","text":"$\\frac{13}{4}$","is_correct":false,"explanation":""},{"id":"D","text":"$\\frac{65}{4}$","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'We can use the following relationship: for a quadratic equation of the form $ax^2 + bx + c = 0$, the sum of the squares of the roots is equal to $\frac{b^2 - 2ac}{a^2}$. In this case, $a = 2$, $b = 5$, and $c = -3$. Therefore, $x_1^2 + x_2^2 = \frac{5^2 - 2(2)(-3)}{2^2} = \frac{25 + 12}{4} = \frac{37}{4}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '3a6bd3a7',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If  $x^2 - 6x + 8 = 0$, what is the sum of the solutions to this equation?',
    'multiple_choice',
    '[{"id":"A","text":"-6","is_correct":false,"explanation":""},{"id":"B","text":"-8","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'Factoring the quadratic equation, we get  (x - 2)(x - 4) = 0.  The solutions to this equation are x = 2 and x = 4. The sum of these solutions is 2 + 4 = 6.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_1',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $2x + 3y = 12$ and $x - y = 4$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To solve for $x$, we can use the elimination method. Multiplying the second equation by 3, we get $3x - 3y = 12$.  Adding this equation to the first equation, we get $5x = 24$, or $x=\frac{24}{5}$ = 4.8, which is closest to 4.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'e89f2c9a',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A square has a side length of 10 cm. What is the area of the square in square centimeters?',
    'multiple_choice',
    '[{"id":"A","text":"10","is_correct":false,"explanation":""},{"id":"B","text":"20","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a square is found by multiplying the side length by itself.  Therefore, the area is 10 cm * 10 cm = 100 square centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_4',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle with a diameter of 10 inches is inscribed in a square. What is the area, in square inches, of the square?',
    'multiple_choice',
    '[{"id":"A","text":"25","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"100","is_correct":true,"explanation":""},{"id":"D","text":"200","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The diameter of the circle is equal to the side length of the square. Since the diameter is 10 inches, the side length of the square is also 10 inches. The area of a square is found by squaring the side length, so the area of the square is 10^2 = 100 square inches.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'd04919d8',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 2x - 8 = 0$, what is the sum of the solutions to the equation?',
    'multiple_choice',
    '[{"id":"A","text":"-2","is_correct":false,"explanation":""},{"id":"B","text":"-1","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":true,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The sum of the solutions to a quadratic equation of the form ax^2 + bx + c = 0 is -b/a. In this case, a = 1 and b = -2, so the sum of the solutions is -(-2)/1 = 2.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_a4',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;

INSERT INTO public.questions (
    id, question_text, question_type, options, correct_answer, explanation, hint,
    stimulus_text, stimulus_type, section, topic, difficulty, exam_type,
    is_platform_question, ai_generated, calculator_allowed, subject, subtopic,
    math_domain, pool_key, diagnostic_eligible, tags, external_id, source, source_metadata
  ) VALUES
(
    gen_random_uuid(),
    'The area of a rectangle is 48 square centimeters. If the length of the rectangle is 8 centimeters, what is the width, in centimeters, of the rectangle?',
    'multiple_choice',
    '[{"id":"A","text":"4","is_correct":false,"explanation":""},{"id":"B","text":"6","is_correct":true,"explanation":""},{"id":"C","text":"12","is_correct":false,"explanation":""},{"id":"D","text":"24","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The area of a rectangle is given by the product of its length and width.  If the area is 48 square centimeters and the length is 8 centimeters, the width is 48/8 = 6 centimeters.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_b8',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following is equivalent to $x^2 - 2x + 1$?',
    'multiple_choice',
    '[{"id":"A","text":"(x - 1)(x + 1)","is_correct":false,"explanation":""},{"id":"B","text":"(x - 1)^2","is_correct":true,"explanation":""},{"id":"C","text":"(x + 1)^2","is_correct":false,"explanation":""},{"id":"D","text":"(x - 2)(x + 1)","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The expression $x^2 - 2x + 1$ is a perfect square trinomial, which can be factored as $(x - 1)^2$.  This is because the first term is the square of $x$, the last term is the square of 1, and the middle term is twice the product of $x$ and 1.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '846ef93c',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units.  What is the area of the circle, in square units? ',
    'multiple_choice',
    '[{"id":"A","text":"5\\pi","is_correct":false,"explanation":""},{"id":"B","text":"10\\pi","is_correct":false,"explanation":""},{"id":"C","text":"25\\pi","is_correct":true,"explanation":""},{"id":"D","text":"100\\pi","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The area of a circle is given by the formula $\pi r^2$, where $r$ is the radius.  Since the radius is 5 units, the area of the circle is $\pi (5)^2 = 25\pi$ square units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_10',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = 2x^2 + 3x - 1$. What is the value of $f(-2)$?',
    'multiple_choice',
    '[{"id":"A","text":"-9","is_correct":false,"explanation":""},{"id":"B","text":"-3","is_correct":true,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"9","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Substituting -2 for x in the expression for f(x), we get $f(-2) = 2(-2)^2 + 3(-2) - 1 = 8 - 6 - 1 = 1$. Therefore, the value of f(-2) is -3.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'f42fd89d',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $f(x) = \frac{x^2 + 3x}{x+4}$ for all positive values of $x$, what is the value of $f(2)$?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To find $f(2)$, we substitute 2 for $x$ in the expression for $f(x)$: $f(2) = \frac{2^2 + 3(2)}{2+4} = \frac{4+6}{6} = \frac{10}{6} = \frac{5}{3}$.  However, none of the answer choices represent  $\frac{5}{3}$.  The answer choices likely represent errors made when evaluating the expression.  Note that $\frac{5}{3}$ can be represented as 1.666, 1.667, or $1\frac{2}{3}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '4c90f53e',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'For what value of $x$ does the equation $\frac{x+5}{x-2} = \frac{x+2}{x-4}$  have a solution? ',
    'multiple_choice',
    '[{"id":"A","text":"-1","is_correct":false,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"7","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'To solve for x, we can cross-multiply: $(x+5)(x-4) = (x+2)(x-2)$. Expanding both sides, we get $x^2 + x - 20 = x^2 - 4$. Subtracting $x^2$ from both sides, we get $x - 20 = -4$. Adding 20 to both sides, we get $x = 16$. However, we need to be careful because the original equation is undefined when $x = 2$ or $x = 4$. Since 16 is not equal to 2 or 4, the solution to the equation is $x = 16$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_d9',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x + 2y = 10$ and $x - 2y = 6$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":true,"explanation":""},{"id":"C","text":"6","is_correct":false,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Adding the two equations together eliminates the $y$ term.  The result is $4x = 16$.  Dividing both sides by 4, we get $x = 4$. ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'a699428d',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A regular hexagon is inscribed in a circle with radius 6. What is the perimeter of the hexagon?',
    'multiple_choice',
    '[{"id":"A","text":"12","is_correct":false,"explanation":""},{"id":"B","text":"18","is_correct":false,"explanation":""},{"id":"C","text":"24","is_correct":false,"explanation":""},{"id":"D","text":"36","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'A regular hexagon can be divided into 6 equilateral triangles.  The side of each equilateral triangle is equal to the radius of the circle, so the perimeter of the hexagon is 6 times the radius, or 6 * 6 = 36.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_a4',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The sum of two numbers is 10 and their product is 21. What are the two numbers?',
    'multiple_choice',
    '[{"id":"A","text":"3 and 7","is_correct":true,"explanation":""},{"id":"B","text":"2 and 10","is_correct":false,"explanation":""},{"id":"C","text":"4 and 6","is_correct":false,"explanation":""},{"id":"D","text":"1 and 21","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'We can find the two numbers by factoring 21.  The factors of 21 that add up to 10 are 3 and 7.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_c8',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function \(f\) is defined by \(f(x) = \frac{2x}{x+1}\). What is the value of \(f(\frac{1}{2})\)?',
    'multiple_choice',
    '[{"id":"A","text":"1","is_correct":true,"explanation":""},{"id":"B","text":"2","is_correct":false,"explanation":""},{"id":"C","text":"3","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Substitute \(x=\frac{1}{2}\) into the function: \(f(\frac{1}{2}) = \frac{2(\frac{1}{2})}{(\frac{1}{2})+1} = \frac{1}{(\frac{3}{2})} = \frac{2}{3}\).',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_c4',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The points A, B, and C lie on a circle with center O.  The measure of angle AOB is 120 degrees.  What is the measure of angle ACB?',
    'multiple_choice',
    '[{"id":"A","text":"30","is_correct":false,"explanation":""},{"id":"B","text":"60","is_correct":true,"explanation":""},{"id":"C","text":"90","is_correct":false,"explanation":""},{"id":"D","text":"120","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Angle ACB intercepts arc AB, and angle AOB is the central angle intercepting arc AB.  The measure of an inscribed angle is half the measure of its intercepted arc, so the measure of angle ACB is half the measure of angle AOB.  Therefore, the measure of angle ACB is 60 degrees.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'f21b71c2',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation $\frac{x^2 + 3x}{x^2 - 9}$ is undefined when $x$ is equal to which of the following?',
    'multiple_choice',
    '[{"id":"A","text":"-3 only","is_correct":false,"explanation":""},{"id":"B","text":"3 only","is_correct":false,"explanation":""},{"id":"C","text":"-3 or 3","is_correct":true,"explanation":""},{"id":"D","text":"0, -3, or 3","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'A rational expression is undefined when the denominator is equal to zero.  Factoring the denominator, we get $x^2 - 9 = (x+3)(x-3)$.  This expression equals zero when $x = -3$ or $x = 3$.  Therefore, the expression is undefined when $x = -3$ or $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '7178fa28',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A group of friends went to a restaurant and ordered 3 pizzas. They split the bill evenly, and each person paid $7.50. How many people were in the group?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":true,"explanation":""},{"id":"C","text":"5","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Since each person paid $7.50 and the total bill was for 3 pizzas, the total cost of the pizzas was 3 * $7.50 = $22.50.  Since they split the bill evenly, there were $22.50 / $7.50 = 3 people in the group.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'a332f5f8',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The equation  $\frac{2x + 1}{x - 1} = 5$ has how many solutions?',
    'multiple_choice',
    '[{"id":"A","text":"Zero","is_correct":false,"explanation":""},{"id":"B","text":"One","is_correct":true,"explanation":""},{"id":"C","text":"Two","is_correct":false,"explanation":""},{"id":"D","text":"Infinitely many","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'To solve for *x*, we multiply both sides of the equation by *x - 1*: $2x + 1 = 5(x - 1)$.  This simplifies to $2x + 1 = 5x - 5$.  Combining like terms, we get $6 = 3x$.  Dividing both sides by 3, we find that *x = 2*.  Since there''s only one solution, there''s only **one** solution.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_1',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x + y = 5$ and $x - y = 1$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"5","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Adding the two equations together, we get $(x + y) + (x - y) = 5 + 1$. This simplifies to $2x = 6$, so $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    '54f7b56c',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'Which of the following is equivalent to $x^{\frac{1}{2}} \cdot x^{\frac{2}{3}}$?',
    'multiple_choice',
    '[{"id":"A","text":"$x^{\\frac{1}{6}}$","is_correct":false,"explanation":""},{"id":"B","text":"$x^{\\frac{3}{5}}$","is_correct":false,"explanation":""},{"id":"C","text":"$x^{\\frac{5}{6}}$","is_correct":false,"explanation":""},{"id":"D","text":"$x^{\\frac{7}{6}}$","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'When multiplying exponents with the same base, you add the powers.  Therefore, $x^{\frac{1}{2}} \cdot x^{\frac{2}{3}} = x^{\frac{1}{2} + \frac{2}{3}} = x^{\frac{7}{6}}$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '738f4933',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $x^2 - 6x + 8 = 0$, what is the sum of the solutions to this equation?',
    'multiple_choice',
    '[{"id":"A","text":"-6","is_correct":false,"explanation":""},{"id":"B","text":"-8","is_correct":false,"explanation":""},{"id":"C","text":"6","is_correct":true,"explanation":""},{"id":"D","text":"8","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'The sum of the roots of a quadratic equation of the form $ax^2 + bx + c = 0$ is equal to $-b/a$. In this case, $a = 1$ and $b = -6$, so the sum of the solutions is $-(-6)/1 = 6$. ',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_b5',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 units. A chord of this circle is 8 units long. What is the distance, in units, from the center of the circle to the chord?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":true,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'Draw a diagram of the circle with the chord and the radius to the chord.  The radius, the chord, and the line segment from the center of the circle to the midpoint of the chord form a right triangle.  The radius is the hypotenuse of the triangle, and the line segment from the center of the circle to the midpoint of the chord is one of the legs.  Since the chord is 8 units long, the line segment from the center of the circle to the midpoint of the chord is 4 units long.  Thus, we have a right triangle with a hypotenuse of 5 units and a leg of 4 units. Using the Pythagorean Theorem, we can find the length of the other leg, which is the distance from the center of the circle to the chord:  $5^2 = 4^2 + x^2$. This gives us $x^2 = 9$, and so $x = 3$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_5',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'The function $f(x)$ is defined by $f(x) = x^2 - 3x + 2$. What are the x-intercepts of the graph of $y = f(x)$ in the xy-plane?',
    'multiple_choice',
    '[{"id":"A","text":"x = 1 and x = 2","is_correct":true,"explanation":""},{"id":"B","text":"x = -1 and x = -2","is_correct":false,"explanation":""},{"id":"C","text":"x = -1 and x = 2","is_correct":false,"explanation":""},{"id":"D","text":"x = 1 and x = -2","is_correct":false,"explanation":""}]'::jsonb,
    'A',
    'The x-intercepts of the graph of a function occur where y = 0.  So, we need to solve the equation $x^2 - 3x + 2 = 0$. This equation can be factored as $(x - 1)(x - 2) = 0$.  Therefore, the x-intercepts are at x = 1 and x = 2.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_a8',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 centimeters. What is the circumference of the circle in centimeters?  (Use $\pi \approx 3.14$)',
    'multiple_choice',
    '[{"id":"A","text":"15.7","is_correct":false,"explanation":""},{"id":"B","text":"31.4","is_correct":true,"explanation":""},{"id":"C","text":"78.5","is_correct":false,"explanation":""},{"id":"D","text":"157","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'The circumference of a circle is given by the formula $C = 2\pi r$, where $r$ is the radius.  Substituting 5 for $r$ and 3.14 for $\pi$, we get $C = 2(3.14)(5) = 31.4$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_c1',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A survey asked 100 people if they prefer to eat pizza or tacos.  Of the people surveyed, 60% preferred pizza.  If 30 people said they preferred tacos, how many people preferred pizza?',
    'multiple_choice',
    '[{"id":"A","text":"40","is_correct":false,"explanation":""},{"id":"B","text":"50","is_correct":false,"explanation":""},{"id":"C","text":"60","is_correct":false,"explanation":""},{"id":"D","text":"70","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'If 60% of the people surveyed preferred pizza, then 40% preferred tacos.  Since 30 people preferred tacos, then 30 represents 40% of the people surveyed. We can set up a proportion: \frac{30}{40} = \frac{x}{100}. Solving for $x$, we get $x = 75$.  Since 75 people preferred tacos, then 100 - 75 = 25 people preferred pizza.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Problem-Solving and Data Analysis',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Problem-Solving and Data Analysis',
    'problem_solving_data',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Problem-Solving and Data Analysis']::text[],
    'e8a7453f',
    'college_board_opensat',
    '{"opensat_domain":"Problem-Solving and Data Analysis","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5.  A chord of the circle is 8 units long.  What is the distance, in units, from the center of the circle to the chord?',
    'multiple_choice',
    '[{"id":"A","text":"2","is_correct":false,"explanation":""},{"id":"B","text":"3","is_correct":true,"explanation":""},{"id":"C","text":"4","is_correct":false,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'B',
    'Draw a diagram of the circle with the chord and the radius.  The distance from the center of the circle to the chord is the perpendicular distance from the center to the chord.  This perpendicular line bisects the chord.  The two halves of the chord, the radius, and the perpendicular distance form a right triangle with the radius as the hypotenuse.  The Pythagorean Theorem tells us that , or .  Thus, the distance from the center of the circle to the chord is 3 units.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Geometry and Trigonometry',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Geometry and Trigonometry',
    'geometry_trig',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Geometry and Trigonometry']::text[],
    'random_id_a2',
    'college_board_opensat',
    '{"opensat_domain":"Geometry and Trigonometry","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'A circle has a radius of 5 centimeters.  What is the area, in square centimeters, of the circle?',
    'multiple_choice',
    '[{"id":"A","text":"5","is_correct":false,"explanation":""},{"id":"B","text":"10","is_correct":false,"explanation":""},{"id":"C","text":"25","is_correct":false,"explanation":""},{"id":"D","text":"25\\pi","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'The area of a circle is given by the formula $A = \pi r^2$, where $r$ is the radius of the circle.  Substituting 5 for $r$, we get $A = \pi (5)^2 = 25\pi$.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    'random_id_b8',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'If $3x + 2y = 17$ and $x - y = 2$, what is the value of $x$?',
    'multiple_choice',
    '[{"id":"A","text":"3","is_correct":false,"explanation":""},{"id":"B","text":"4","is_correct":false,"explanation":""},{"id":"C","text":"5","is_correct":true,"explanation":""},{"id":"D","text":"6","is_correct":false,"explanation":""}]'::jsonb,
    'C',
    'We can solve for $x$ by using elimination. Multiplying the second equation by 2 gives us $2x - 2y = 4$. Adding this equation to the first equation, we get $5x = 21$. Dividing both sides by 5, we find $x = \frac{21}{5} = 4.2$.  The closest answer choice is C, 5.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Algebra',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Algebra',
    'algebra',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Algebra']::text[],
    'random_id_a4',
    'college_board_opensat',
    '{"opensat_domain":"Algebra","section":"math"}'::jsonb
  ),
(
    gen_random_uuid(),
    'What is the value of \(\frac{x^2 - 1}{x + 1}\) when \(x = -3\)?',
    'multiple_choice',
    '[{"id":"A","text":"-4","is_correct":false,"explanation":""},{"id":"B","text":"-2","is_correct":false,"explanation":""},{"id":"C","text":"2","is_correct":false,"explanation":""},{"id":"D","text":"4","is_correct":true,"explanation":""}]'::jsonb,
    'D',
    'First, we can factor the numerator, which gives us \(\frac{(x+1)(x-1)}{x+1}\).  Since \(x\neq -1\), we can cancel the \(x+1\) terms, leaving us with \(x-1\).  Substituting -3 for x gives -3 - 1 = -4, so the correct answer is D.',
    'Review the passage and eliminate choices that contradict the text.',
    NULL,
    NULL,
    'math',
    'Advanced Math',
    'medium'::difficulty,
    'SAT'::exam_type,
    true,
    false,
    true,
    'math',
    'Advanced Math',
    'advanced_math',
    'college_board_sat_v1',
    true,
    ARRAY['college_board','opensat','math','Advanced Math']::text[],
    '32df587a',
    'college_board_opensat',
    '{"opensat_domain":"Advanced Math","section":"math"}'::jsonb
  )
ON CONFLICT (source, external_id) WHERE external_id IS NOT NULL AND source IS NOT NULL
DO NOTHING;