import type { Metadata } from "next";
import { createMarketingMetadata } from "@/lib/seo/marketing-metadata";
import {
  PageContent,
  PageHero,
  PageSection,
} from "@/components/marketing/PageShell";
import { BaseCard, DarkCard, cardGrids } from "@/components/marketing/cards";

export const metadata: Metadata = createMarketingMetadata({
  title: "AI Courses",
  description:
    "Turn any YouTube video into a structured course — lessons, key points, and a quiz — generated by AI from the video's transcript.",
  path: "/learn",
});

const STEPS = [
  {
    step: "1",
    title: "Paste a YouTube link",
    description:
      "Drop in any lecture, explainer, or crash course you want to learn from.",
  },
  {
    step: "2",
    title: "AI builds the course",
    description:
      "Scho reads the transcript and organizes it into ordered lessons with the key points that matter.",
  },
  {
    step: "3",
    title: "Learn and test yourself",
    description:
      "Study the lessons, then check your understanding with an auto-generated quiz.",
  },
];

const BENEFITS = [
  {
    title: "Your own free key",
    description:
      "Bring a free Google AI Studio key — your courses run on your usage, stored only in your browser.",
  },
  {
    title: "Structured, not a summary",
    description:
      "You get ordered lessons, per-lesson key points, and a multiple-choice quiz — not just a wall of text.",
  },
  {
    title: "Made for active study",
    description:
      "Turn the SAT & ACT prep videos you already watch into something you actually practice against.",
  },
];

export default function LearnPage() {
  return (
    <PageContent>
      <PageHero
        eyebrow="AI Courses"
        title="Turn any YouTube video into a course"
        subtitle="Paste a link and Scho builds a structured course from the video — ordered lessons, key points, and a quiz. Free, using your own AI key."
        ctaLabel="Start free"
        ctaHref="/auth/signup"
      />

      <PageSection title="How it works">
        <div className={`${cardGrids.grid} ${cardGrids.cols3}`}>
          {STEPS.map((s) => (
            <BaseCard
              key={s.step}
              stepNumber={s.step}
              title={s.title}
              description={s.description}
            />
          ))}
        </div>
      </PageSection>

      <PageSection title="Why it's different" alt>
        <div className={`${cardGrids.grid} ${cardGrids.cols3}`}>
          {BENEFITS.map((b) => (
            <BaseCard
              key={b.title}
              title={b.title}
              description={b.description}
              centered
            />
          ))}
        </div>
      </PageSection>

      <PageSection>
        <DarkCard
          title="Ready to turn videos into courses?"
          description="Create your first AI course in under a minute — free."
          ctaLabel="Start free"
          ctaHref="/auth/signup"
        />
      </PageSection>
    </PageContent>
  );
}
